src/iconvert/iconvert.cpp, src/include/OpenImageIO/filesystem.h, src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/imagebuf.h, src/include/OpenImageIO/imagebufalgo.h, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/libOpenImageIO/imagebufalgo_yee.cpp, src/libOpenImageIO/maketexture.cpp, src/oiiotool/oiiotool.cpp, src/python/py_imagecache.cpp, src/python/py_oiio.h
These are all things that have been deprecated since 1.3 was in development (around 2 years ago). Everybody has had the full lifetime of 1.3 and 1.4 to stop using them. Proposing to remove them completely in time to branch for release 1.5.
=> Remove deprecated functions

src/doc/imagebuf.tex, src/doc/imagecache.tex, src/doc/openimageio.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/include/OpenImageIO/imagecache.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebuf_test.cpp, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/python/py_imagebuf.cpp, src/tiff.imageio/tiffinput.cpp
This has never been a high priority, but it comes up as a request from time to time, so I thought I'd try to squeeze it in before we lock down the API for 1.5 release.
History: ImageInput has a variety of the open() method that takes an ImageSpec whose metadata can communicate special options or hints that a reader would need to know when the file is first opened. It's a rare case, but sometimes is used to solve tricky problems, allowing an app to talk to a particular format reader in custom ways that are not easily accommodated by the main ImageInput API. Occasionally people have noticed that this does not allow the same options to be passed to the readers when using the higher-level ImageBuf or ImageCache APIs, which don't directly expose the underlying ImageInput.
This patch tries to …
=> "open with configuration" extended to ImageBuf, ImageCache

src/libutil/filesystem.cpp, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp, src/socket.imageio/socketinput.cpp, src/socket.imageio/socketoutput.cpp
Some places -- notably, the parts of OIIO that deal with field3d and OpenColorIO -- already put a catch(...) even after catches of other specific exceptions. But others, including OIIO::Filesystem wrappers and the places where we deal with OpenEXR, tried to catch specific exceptions, even std::exception&, which we would have thought would catch anything. But apparently not. At the very least, some versions of clang on Apple, when -fno-rtti is used for static linkage, have a bug that can still let through exceptions. Now we really, absolutely, catch everything, dammit.
Fixes #1025
=> Catch all exceptions with catch(...)

src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/missing_math.h, src/include/OpenImageIO/simd.h, src/libtexture/texturesys.cpp
The first commit has been checked with Visual Studio 2010 and Visual Studio 2013 (Win32 build only).
The second commit is more involved. There are a lot of changes but they are all of the same kind: every SIMD input to a function is changed to a const reference.
The annoying thing is that this change affect all platforms and that I am unable to say whether it has an adverse effect on performances or not. On the positive side, Embree does the same thing and nobody can really complain of its speed !
=> Compiler fixes for VS2010 & 2013

site/spi/Makefile-bits-arnold
This won't affect anybody outside of SPI.
=> SPI only: make COMPILER=clang or =gcc use the default clang or gcc in execution path

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
Add partial-load SIMD functions, and make the partial-load and partial-store use SSE ops for 1, 2, and 3-wise loads/stores (previously reverted to scalar ops for those cases).
=> SIMD improvements: partial load and store

src/doc/makefigures.bash, src/doc/oiiotool.tex, src/oiiotool/oiiotool.cpp, testsuite/oiiotool/run.py
I just like the new names better, and by being alphabetical neighbors to their image-wise counterparts, the documentation is easier to read and find what you want.
The old ones are left in as aliases, will keep working for a couple major releases, maybe indefinitely.
This is only about command-line arguments to oiiotool. Nothing changes about the C++ or Python APIs (which used function overloading all along, didn't have this naming problem).
Reminder: --add adds two images pixel-by-pixel, --addc (nee --cadd) adds a constant color to all pixels of an image.
=> oiiotool: rename -cadd, -csub, -cmul, -cpow to -addc, -subc, -mulc, -powc

src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp
Input: Tiles were always being read starting at 0,0 rather than the requested offset.  I matched variable names with similar existing logic in the deep tile output.
Output: Within spec_to_header, the call to put_parameter does a sanity check to make sure the image is tiled if setting lineOrder to randomY.  The problem in the case of deep exrs (any multipart exr, really) is that the sanity check was being done with m_spec before it was initialized.  This change instead gets the tile info from the header that is currently being built, with a comment to ensure that the tile description is set *before* the call to put_parameter.
=> Bug fixes to deep tiled exr input/output

src/python/CMakeLists.txt
From issue #1037, build the python module as a MODULE, not SHARED library.
=> python plugin should be built as a MODULE, not a SHARED library

CHANGES, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/doc/stdmetadata.tex, src/jpeg.imageio/jpeginput.cpp, src/jpeg.imageio/jpegoutput.cpp, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp, testsuite/gpsread/ref/out-alt.txt, testsuite/gpsread/ref/out.txt, testsuite/maketx/ref/out-alt-tiff4.txt, testsuite/maketx/ref/out.txt, testsuite/misnamed-file/ref/out.txt, testsuite/python-imagebuf/ref/out-alt.txt, testsuite/python-imagebuf/ref/out.txt, testsuite/python-imageinput/ref/out-alt.txt, testsuite/python-imageinput/ref/out.txt, testsuite/tiff-depths/ref/out.txt, testsuite/tiff-suite/ref/out.txt
Smarter handling of X/Y resolution (i.e. density), resunit, aspect for JPEG, TIFF, OpenEXR.
* We weren't reading or writing density for JPEG at all. The xdensity and ydensity in the JPEG header should turn into the standard OIIO attributes "XResolution" and "YResolution".
* JPEG and TIFF both don't have pixel aspect ratio metadata, it's implied by the densities when reading. When writing, if a pixel aspect ratio is requested, you may need to make up densities in order to imply the right aspect ratio.
* OpenEXR only has xDensity (aka XResolution), which we didn't read properly, and aspect ratio, and YResolution (y density) is implied by these when present. Also, OpenEXR dictates that densities are in pixels per inch, so set that upon input, and upon output, if we are given densities in …
=> Smarter handling of X/Y resolution (i.e. density), resunit, aspect

src/doc/imagecache.tex, src/doc/texturesys.tex
I propose this docs fix (to match the current behavior) to subsume pull request #1041.
=> Clarify docs for get_texture_info 'exists' query

src/include/OpenImageIO/string_ref.h
We renamed string_ref to be string_view a while back and, for the sake of not breaking anybody immediately, made this back-compatible header. I propose that we remove it now in master.
=> Remove deprecated header

src/include/OpenImageIO/simd.h
We have simd::float4 conversions from and to Imath::V4f. Turns out that
prior to OpenEXR 1.7-ish, there was no V4f. To make things extra fun,
back then OpenEXR/IlmBase did not have any handy #defines to let you
conditionally compile based on the Ilmbase version. Now it does.  So we
punt and only define the (rarely used?) V4f conversions when Ilmbase is
safely >= 2.0, which seems safe moving forward, but this header will
still compile without errors for somebody stuck with Ilmbase 1.0.1
(albeit without the ability to convert to and from V4f, which is moot
anyway for those without such a definition).
=> Make simd.h safe for older Ilmbase.h.

src/jpeg.imageio/jpeg_pvt.h, src/jpeg.imageio/jpeginput.cpp
So a CMYK or YCbCrK JPEG file will appear (to an OIIO client app) as an ordinary 3-channel sRGB file, silently converted by the plugin.
At present, writing CMYK is not supported. We will revisit in the future if this is a requirement for somebody.
=> Support JPEG files encoded as CMYK (by converting to RGB upon read).

CMakeLists.txt, src/libOpenImageIO/CMakeLists.txt, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageio_pvt.h.in
The new PLUGIN_SEARCH_PATH option allows for specifying a default plugin
search path at build time. More precisely, the plugin_searchpath
attribute is assigned the value of PLUGIN_SEARCH_PATH by default.
This makes it possible for example to simple install custom plugins to
PLUGIN_SEARCH_PATH without having to fiddle around with environment
variables (i. e. OIIO_LIBRARY_PATH).
=> Introduce a CMake option to specify a plugin search path

src/doc/imageinput.tex, src/doc/imageoutput.tex, src/include/OpenImageIO/imageio.h, src/openexr.imageio/exroutput.cpp
When strides are automatically computed rather than explicitly supplied,
it should have assumed data layout of a "full tile", even if it was the
last tile in a row in an image whose width was not an integral multiple
of the tile width. Instead, it was clamping the width and height by the
size of the remaining data. That didn't match the behavior of read_tile
(which assumed full-tile-size layout, even for edge tiles), nor the
behavior of write_tile for other tiled formats such as TIFF.
Used the occasion to tighten up the imageio.h comments and OIIO
documention on this matter, spelling out more carefully what happens
with AutoStride in write_tile versus write_tiles.
=> OpenEXR write_tile with AutoStride calculated the wrong strides.

src/libOpenImageIO/maketexture.cpp
There was one code path, that only comes into play when the source image
is a crop (data window != display window) that didn't take into
consideration the special names we use for requesting MIP map
sharpening, and it was issuing an "unknown filter name" error.
=> maketx: Fix botched filter with crop windows that need resize

src/bmp.imageio/bmp_pvt.h, src/bmp.imageio/bmpoutput.cpp, src/doc/imageoutput.tex, src/doc/openimageio.tex, src/dpx.imageio/dpxoutput.cpp, src/field3d.imageio/field3doutput.cpp, src/fits.imageio/fits_pvt.h, src/fits.imageio/fitsoutput.cpp, src/ico.imageio/icooutput.cpp, src/iff.imageio/iffoutput.cpp, src/include/OpenImageIO/imageio.h, src/jpeg.imageio/jpegoutput.cpp, src/jpeg2000.imageio/jpeg2000output.cpp, src/libutil/strutil_test.cpp, src/oiiotool/oiiotool.cpp, src/openexr.imageio/exroutput.cpp, src/png.imageio/pngoutput.cpp, src/pnm.imageio/pnmoutput.cpp, src/psd.imageio/psdoutput.cpp, src/ptex.imageio/ptexoutput.cpp, src/rla.imageio/rlaoutput.cpp, src/sgi.imageio/sgi_pvt.h, src/sgi.imageio/sgioutput.cpp, src/socket.imageio/socket_pvt.h, src/socket.imageio/socketoutput.cpp, src/targa.imageio/targaoutput.cpp, src/tiff.imageio/tiffoutput.cpp, src/webp.imageio/webpoutput.cpp
Before saving and encountering an error, check that the output file type supports the number of channels in the image being saved. If not, don't consider it an error, but rather just give a warning, and then do the best we can. What we try to do is: (a) if "R", "G", and "B" (and also "A", if the format supports it) are all in the list of channel names for the image that is being saved, save just those channels; (b) if those names are not found, just punt and save the first three channels (or 4, if the output supports alpha).
In order to facilitate this, we add two new tokens to ImageOutput::supports(): supports("alpha") if the file format supports saving an alpha channel, and supports("nchannels") if the file format supports saving an arbitrary number of channels. (We assume that ALL …
=> oiiotool: gracefully handle impossible requests to save too many channels.

src/jpeg.imageio/jpegoutput.cpp
Didn't realize that jpeg_set_defaults would clobber those fields.
=> JPEG: write density fields into header properly.

src/oiiotool/oiiotool.cpp, testsuite/oiiotool-readerror/ref/out.err-alt.txt, testsuite/oiiotool-readerror/ref/out.err.txt
Before, all read errors gave the same generic "Could not open file" message.  Now, it is more nuanced, as shown in the following examples:
$ oiiotool noexist.jpg
oiiotool ERROR: read : File does not exist: "noexist.jpg"
$ oiiotool empty.jpg
oiiotool ERROR: read : OpenImageIO could not open "empty.jpg" as jpg: Empty file "empty.jpg"
$ oiiotool corrupt.jpg
oiiotool ERROR: read : OpenImageIO could not open "corrupt.jpg" as jpg: "corrupt.jpg" is not a JPEG file, magic number doesn't match (was 0x6173)
=> Improve oiiotool error messages when files can't be read.

src/doc/imageioapi.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagespec_test.cpp, src/python/py_imagespec.cpp
* Add ImageSpec::find_attribute() that works for fixed fields in the spec like "width" (in addition to named metadata in extra_attribs).  But needs to be passed a temporary ImageIOParameter as scratch. By using this, we make get_int_attribute, get_float_attribute, and get_string_attribute also able to retrieve those fields. For example, imagespec.get_int_attribute("nchannels") might return 3, or imagespec.get_string_attribute("geom") might return "640x480+0+0".
* ImageSpec::metadata_val should be static (not merely const), since it doesn't need 'this' at all.
* ImageSpec::erase_attribute() fixups:
1. Document it (had somehow gone undocumented in the PDF)
2. Set up Python bindings for it (was missing)
3. Minor touch-ups in describing the workings of find_attribute.
=> ImageSpec minor additions & fixes

src/include/OpenImageIO/filesystem.h, src/libutil/filesystem.cpp
1. From Max Liani: improve exception safety of Filesystem::get_directory_entries. 
2. From LG: add Filesystem::rename(), and fix Filesystem::copy() which got the sense of the error code backwards.
=> Filesystem improvements

src/include/OpenImageIO/typedesc.h
* Allow 'equivalent' comparison to allow an unspecified-length array to
match any array of the same type.
=> TypeDesc - changes to better support arrays of unspecified length

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
Was glancing through code and spotted this embarrassing typo. Added the unit tests I always should have had, that would have found this.
"Untested code is broken code."
=> Fix simd.h typo that implemented >>= incorrectly

src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/hash.h, src/include/OpenImageIO/simd.h
Move rotl32 and rotl64 from hash.h to fmath.h (where other bit-twiddles live)
Also add a SIMD version of rotl to simd.h.
=> Move rotl32 and rotl64 from hash.h to fmath.h (where other bit-twiddles live)

src/include/OpenImageIO/simd.h
Please backport to RB-1.5, since the same issue exists there.
=> Fix build error in float4.xyz0() with SSE version < 4

src/libutil/filesystem.cpp
A tiny patch (1 character!) that allows %0Nd to match more than N digits. For example, if a sequence overflows 4 digits, frame 10000 should still be matched. 
This behavior is consistent with Nuke and RV.
cheers,
-Mark
=> allow e.g. %04d to match more than 4 digits, e.g. 10000

src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texture_pvt.h
ImageCache/TextureSystem: add create_thread_info() and destroy_thread_info() methods that let an app explicitly create an IC/TS per-thread info that the app can completely manage (and is responsible for destroying).
This augments the existing get_perthread_info(), which retrieves a unique Perthread* from a thread-specific pointer (whose storage and lifetime is controlled by the library, not the app).
The addition of the explicit create/destroy allows very savvy apps to pre-allocate PerThreadInfo that can persist even as threads come and go, and avoid the thread-specific-pointer retrieval. But beware -- it is up to the app to ensure that any created Perthread info (a) is eventually destroyed, and (b) under no circumstances may be shared by more than one thread at the same time. Bad things …
=> IC/TS: add create_thread_info() and destroy_thread_info() methods

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo.cpp, src/python/py_imagebuf.cpp
Add ImageBuf::make_writeable(), forces IC-backed read-only IB to force a full read into locally allocated pixels so they can be subsequently altered.
Make IB::Iterator constructors automatically do this, so that if somebody initializes an iterator to an IC-backed IB, it will automagically become safe to write. This does NOT happen for IB::const_iterator, which when used will keep IC-backed IB's using the IC rather than local storage.
Users shouldn't notice any difference, except for higher fault tolerance if they should try altering an ImageeCache-backed ImageBuf.
=> Add ImageBuf::make_writeable()

src/doc/imagecache.tex, src/doc/texturesys.tex, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/environment.cpp, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texture3d.cpp, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp
Ugh, I did it wrong. The find_file methods that did the name to IC handle lookups did more than just that -- that's also where the ImageInputs were opened (if not yet opened), duplicates found, 'used' flags updated, errors reported, etc.
It wasn't symptomatic until we started messing around with invalidating the files in the cache, which doesn't invalidate the handles themselves (and shouldn't), but at that point the files would be closed, and the re-opening wouldn't happen properly without the call to find_file, which of course wouldn't happen at all since the handle was already retrieved.
The solution is to split into separate "find" (just convert name to file cache handle, creating if necessary), and "verify" (open and other housekeeping and error checking). It's mostly just splitting …
=> Fixes to texture handle changes

src/doc/imageioapi.tex, src/doc/openimageio.tex, src/include/OpenImageIO/array_view.h
The most important fix is to do some tricks to allow a array_view<const float> to be constructed from a const std::vector<float>&.
Also added documentation of array_view to the PDF. (The changes you see to ustring docs aren't new, they just shifted position around.)
=> array_view fixes and docs

CHANGES, src/doc/oiiointro.tex, src/include/OpenImageIO/hash.h, src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/strutil.h, src/libOpenImageIO/CMakeLists.txt, src/libutil/CMakeLists.txt, src/libutil/farmhash.cpp, src/libutil/hash_test.cpp, src/libutil/xxhash.cpp
A non-OIIO app that happens to use OIIO's ustring extensively was performing badly when dealing with an absurd number of very long strings. We experimentally found that our Strutil::strhash (and therefore all the underlying hashing for ustring) was a primary culprit.
* Add Google's farmhash (MIT license) and update our prior use of xxhash to a more modern version that includes a nice fast 64 bit hash.
* Lots of benchmarking indicates that old strhash was the worst of the bunch.
* Settled on farmhash as the best replacement for strhash's guts.  For extremely short strings, it's slightly slower than the old implementation, but the crossover point is ~6 chars, and the longer the string, the bigger the speedup.  It's well over 10x faster than the old implementation for long strings (100-500 …
=> strhash replacement -- improve hashing of large strings by 10x or more

src/libutil/ustring_test.cpp
Modify ustring_test to give it thread wedging benchmark abilities
(modeled after spinlock_test)
To benchmark its thread performance, you'd use it like this (hint for Chris):
build/spinux1/src/libutil/ustring_test -wedge -trials 5 -iters 10000000 -threads 32
=> Modify ustring_test to give it thread wedging benchmark abilities

src/libOpenImageIO/imagebuf.cpp
This ensures that an "undefined" ROI intersected or unioned with a valid one produces the expected result (i.e., returning the valid one).
=> ROI improvement -- make instersection/union robust to uninitialized arguments

src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
A semi-random assortment of mostly recently-added operations were calling imagerec->read() directly instead of the wrapper ot.read(imagerec). The confusing thing was that the ot wrapper is where it was recording the tiling and pixel data format of the first image read, for later use as the default for any output files (in the absence of explicit -tile or -d directives). This would result in output files with the "wrong" data formats.
=> oiiotool: bug fix - input file data format didn't always end up in output

src/jpeg2000.imageio/jpeg2000input.cpp, src/jpeg2000.imageio/jpeg2000output.cpp, testsuite/jpeg2000/ref/out.txt, testsuite/jpeg2000/run.py
Reading:
* Fix horribly broken YUV->RGB conversion
* Correctly recognize sRGB encoding
* Pass along the ICC profile, if present
* Handle all bit depth precisions (previously, only 8, 10, 12, 16)
* Set the full/display window correctly
* Deal with differing per-channel data windows and sampling rates
Writing:
* De-associate alpha to match reader (and apparently the J2K spec).
* Handle all bit depth precisions
* Output ICC profile.
=> JPEG-2000 improvements

src/jpeg2000.imageio/jpeg2000input.cpp, src/jpeg2000.imageio/jpeg2000output.cpp
And having no principled way to detect the version from the header.
=> Deal with older version of libopenjpeg not having icc fields.

src/libOpenImageIO/imagespec_test.cpp
Use OIIO_CHECK_ASSERT(foo != NULL), not OIIO_CHECK_EQUAL(foo,NULL)
because the latter can try to print the NULL, which on some platforms
could be a problem depending on exactly how NULL is defined.
=> Fix unit test methodology regarding NULL pointers

src/libtexture/texturesys.cpp
We found an issue on Windows where the SIMD texture filtering code would sometimes generate NaNs in the alpha channel for 3 channel images.
What happens is that when doing an SIMD load of 4 floats, the 4th alpha channel value uses uninitialized memory. Note the pixel buffer is made big enough in `ImageCacheTile::memsize_needed()` to avoid reading past the end of the array so that's fine, the problem is uninitialized memory.
When the image size is not a multiple of the tile size, then tiles near the edge contain uninitialized values. Sometimes these are NaN. I don't know if the fact that these are uninitialized is a bug, if so then that should be fixed instead, but I'm not sure where exactly.
Here the fix is to use `blend0()` and `blend0not()` rather than multiplication with zero which …
=> Fix occasional NaNs in alpha channel with 3 channel images.

src/include/OpenImageIO/platform.h, src/include/OpenImageIO/simd.h, src/include/OpenImageIO/timer.h, src/iv/imageviewer.h, src/iv/ivgl.h, src/libutil/farmhash.cpp, src/libutil/plugin.cpp, src/libutil/sysutil.cpp
* The recently-added farmhash uses a 'LIKELY' macro that conflicts with something in Windows land. Replace it with our OIIO_LIKELY defined in platform.h.
* To fix recurrent min/max conflicts, move the magic symbols that fix it into platform.h. In the process, noticed that osdep.h exists only to fix that problem, it predates platform.h and clearly that's where it should be. So change all other references to osdep.h to include platform.h. We will eventually remove osdep.h when we are confident that no user programs are likely to reference it.
* simd.h can, if not at sufficiently high level of SSE support, use std::min and std::max. So we need to include <algorithm> to ensure those are defined.
=> Fixes for windows compilation

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/include/OpenImageIO/imagebufalgo.h, src/include/OpenImageIO/imagebufalgo_util.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/libOpenImageIO/imagebufalgo_xform.cpp, src/python/py_imagebuf.cpp
Something I was working on a couple weekends ago.
Basically, rewrite the OIIO_DISPATCH_COMMON_TYPES macros (used internally by ImageBufAlgo to specialize for the various combinations of pixel data types when combining images) so that instead of failing when they get uncommon types, they silently auto-convert to a supported type. Thus, these functions may have lower performance when not using one of the preferred types, but now they will never fail for that reason.
=> Overhaul OIIO_DISPATCH_COMMON macros

src/doc/imageinput.tex, src/doc/imageoutput.tex, src/doc/openimageio.tex, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imageioplugin.cpp
This is helpful on Windows if OIIO is used within plugins (DLLs) that may be loaded and unloaded. It can be problematic to have memory allocated (as is done by ImageOutput::create()) on one side of a DLL boundary, and then freed on the other side of the DLL boundary (as would happen with an ordinary 'delete'). Instead, prefer to get rid of ImageInput*'s and ImageOutput*'s by calling destroy().
If this solves the problem, I think it's safe to backport to 1.5 without breaking compatibility, because it only adds static methods to these classes and doesn't change any previously existing API calls or class structure layout.
=> Add destroy() methods to ImageInput and ImageOutput.

src/libOpenImageIO/imagebufalgo_compare.cpp
Make sure mismatched non-finite values are flagged as the biggest differences in the images, so you can find them right away.
=> Another tweak IBA::compare() for nonfinite values

src/libOpenImageIO/imagebufalgo.cpp
=> Fix IBA::convolve -- did not correctly use the temporary float buffer.

CHANGES, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/include/OpenImageIO/color.h, src/libOpenImageIO/color_ocio.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
This set of changes adds an --autocc (auto color convert) option to oiiotool. When specified, it makes oiiotool:
* Examine any input and output filenames, looking to see if they contain substrings which are any of the known OpenColorIO color space names.
* If so, then it will assume that an input file contains data in that color space, and will automatically convert it to a scene-linear space upon input. If there is no such hint in the filename, it will then examine any "oiio:ColorSpace" metadata found in the file and do the conversion based upon that (this metadata is set by any ImageInput that can discern the color space of the input data, for example, it knows that JPEG data is always sRGB).
* Similarly, when requesting output (-o), it will interpret any color space names in the …
=> oiiotool --autocc

src/include/OpenImageIO/filesystem.h, src/libutil/filesystem.cpp, src/libutil/filesystem_test.cpp
1. Add Filesystem::current_path() as portable way to get current working directory path.
2. Fix a unit test that failed with newer Boost (1.57) due to Boost's exception behavior changing in a certain spot. Nothing wrong with our Filesystem code, only that our unit test was testing the wrong conditions (it was testing a specific return value, when all we cared is that the function didn't crash).
3. Fix the sequence enumeration functions to clear their results vectors when the start. The documentation never advertised that they were appending, so replacing the results (including clearing it if no match was found) seems like the best way to adhere to the Principle of Least Surprise.
=> Filesystem utility enhancements and fixes

src/doc/imagebufalgo.tex, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/include/OpenImageIO/color.h, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/color_ocio.cpp, src/oiiotool/oiiotool.cpp
* Change ColorConfig wrapper to allow a reset() to point the color config to a new/custom OCIO configuration. (Also simplify the constructors by implementing in terms of reset.)
* IBA colorconvert, ociodisplay, and ociolook get new varieties that accept an optional ColorConfig, rather than having no choice but to construct a new one internally.
* oiiotool passes its colorconfig to the IBA functions so it will reuse the one stored in ot.colorconfig.
* New oiiotool --colorconfig lets you direct oiiotool to use a custom location of an OCIO configuration (rather than strictly relying on the $OCIO environment variable). This is especially handy in certain testing situations.
=> Allow use of custom ocio configuration files

src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
It's been bugging me for a while that all the operations in oiiotool (add, mul, etc.) are enormously repetitive, lots of similar boilerplate in all the ops: pop images off the stack, create a destination image, decode arguments and options, loop over subimages, time the whole thing. etc.
And sometimes the repetition is inexact -- either plain old errors, or else that because oiiotool has grown in pieces, improvements to methodology get incorporated into newly added functions but not old ones.
So I've been contemplating a big refactor for some time, and this past weekend I got the chance to experiment, and I think I like it. The gist is that I define an OiiotoolOp base class that contains all the common boilerplate code. Then the individual operations subclass, overriding just the tiniest …
=> Overhaul of oiiotool.cpp -- express operations as OiiotoolOp subclasses.

src/oiiotool/oiiotool.cpp
Nobody reported this as a problem, but in looking at action_crop, I
think the logic was all wrong. If the crop region was the same size as
the original pixel data window, it would merely change the origin. That
can't be right (and, in any case, is accomplished with the separate
--origin command).
=> oiiotool -crop : fix bug in the logic

src/doc/oiiotool.tex, src/oiiotool/diff.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
-n : "no saved output" performs all the calculations (including timing
and stats) but does not write any output files to disk. This is helpful
for debugging, for testing an oiiotool command line syntax or behavior
without wanting to accidentally write files with a malformed command,
and for performance testing of computation where you don't really care
about timing of I/O to write the tiles.
--debug : Previously the "-v" (verbose) performed two somewhat unrelated
tasks -- it increased the verbosity of essential output, but it alto
triggered certain debugging status messages. Now we have separate
controls for these two options.
=> oiiotool -n and --debug

src/include/OpenImageIO/texture.h, src/libtexture/texturesys.cpp
It had been creating a separate TS for every create call, but with a
shared ImageCache (if requested).  That's not good enough. If two spots
in an app each request a shared TS, They probably want it to actually be
the same one, including any attributes already set in it.
=> Make TextureSystem::create(shared=true) truly create a shared TS.

src/oiiotool/oiiotool.cpp
When oiiotool --frames was used, it overrode ALL frame sequence wildcards.
That's not correct; the argument to --frames should only override sequence
wildcards that don't explicitly spell out the sequences.
Example:   oiiotool --frames 1-5 a.#.exr -o b.1001-1005#.exr
This should copy a.0001.exr to b.1001.exr, NOT b.0001.exr. The --frames 1-5
should only apply to the "#" free sequence wildcard, not the 1001-1005# explicitly
ranged sequence wildcard.
=> Bug fix: frame sequences incorrectly overridden with --frames

src/include/OpenImageIO/imagebufalgo_util.h, src/include/OpenImageIO/platform.h, src/libutil/filesystem.cpp, src/python/py_paramvalue.cpp
CHANGES:
* imagebufalgo_util.h: export type_merge symbol
* platform.h : declare __cpuidex function
* filesystem.cpp : include `<windows.h>` after `"OpenImageIO/platform.h"`. Otherwise, NOMINMAX gets defined too late.
* py_paramvalue.cpp : make sure code uses make_tuple from boost::python and not make_tuple
from std::tr1. VS2010 gets confused with the current code.
Except for the second, all changes should be backported to RB 1.5
=> Misc WIN32 and VS2010 fixes

src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf_test.cpp
Otherwise, you set up your iterator that should loop over 0 pixels, and it
visits pixels incorrectly.
Fixes #1139. Note that the problem could crop up for things other than fill(). I think this solution would solve it for all IBA functions.
=> Make IB iterator constructors with 0-size ranges look "done".

src/include/OpenImageIO/missing_math.h, src/jpeg.imageio/jpeg_pvt.h, src/jpeg.imageio/jpeginput.cpp, src/jpeg.imageio/jpegoutput.cpp, src/psd.imageio/jpeg_memory_src.cpp, src/psd.imageio/jpeg_memory_src.h
`rintf` is not part of Visual Studio 2010 libraries. The first commit provides a default implementation.
The second commit is more controversial. Currently, `psd` & `jpeg` plugins do not compile on Windows for master and RB1.5 because `jpeg` headers define stuff that conflicts with `<windows.h>`. The patch attempts to prevent this in a simple manner but it is quite ugly.
The real issue here is that `<windows.h>` is included with each and every OIIO file: IMHO, it should not because this header is only really needed when using `Win32 API` (timers, threads, locks, ...).
I think a better patch would be to restore `osdep.h` usage in a few selected places and to remove `<windows.h>` from `platform.h`. I can certainly do this if you will.
=> Win32 fixes

src/doc/maketx.tex, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/maketexture.cpp, src/maketx/maketx.cpp
--stats if applicable, prints statistics about the program inputs.
--runstats prints runtime statistics about the operation of the program itself (timing, memory, etc.)
oiiotool already used this convention, but maketx used --stats to mean run stats.
=> Harmonize the way all binaries use --stats versus --runstats

Makefile
Tried this on a lark, and it was extremely easy to do, almost no change to workflow, and the speedup of incremental builds (just one source file changed, or nothing changes) is dramatic. I don't see any obvious downside to using this option to build with ninja, if it's available.
Full post-nuke, post-ccache-clear build goes from 1:46 to 1:40
ccache-aided full build goes from 11.7 to 6.5
"null" build with nothing changed goes from 3.8 to 0.2 -- almost instantaneous!
=> 'make USE_NINJA=1' creates ninja build files

src/doc/imageinput.tex, src/include/OpenImageIO/imageio.h, src/libtexture/imagecache.cpp
ImageCache should not fail resolve_filename if it's a procedural file.
=> New ImageInput supports() query: "procedural" -- if it's not corresponding to a file

src/libtexture/imagecache.cpp, src/libtexture/texturesys.cpp
There's no need to invalidate the cache just because somebody asks for
another copy of the shared cache.
=> Eliminate spurious cache invalidation.

Makefile
It's now always building single threaded after commit 735d43a.
GNU make requires ${MAKE} to be used to detect the child process is make, see the explanation for the `jobserver unavailable: using -j1` error message here:
https://www.gnu.org/software/make/manual/html_node/Error-Messages.html
The code duplication isn't great, but I don't know how to avoid it.
=> Fix multithreaded build with make -jN no longer working.

src/oiiotool/oiiotool.cpp
For "procedural" ImageInputs (as reported by supports("procedural")), don't give "file doesn't exist" errors, because of course it doesn't. Dig a little deeper for a better error message.
=> oiiotool: better error messages for bad "procedural" images

src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/imagebufalgo.cpp
Fix bug in fft -- was not zeroing out imaginary channel when copying from a real-only image. Just creating a buffer does NOT zero it out, as was assumed (and commented) in this code.
This bug has been there for a while, usually is not symptomatic, depends what was lying around in the buffer. But the python-imagebufalgo test would tickle it with some regularity, It was keeping me from having clean testsuite runs, so I finally tried to figure out why, and this was it.
=> Fix bug in fft -- was not zeroing out imaginary channel

src/include/OpenImageIO/hash.h, src/include/OpenImageIO/string_view.h
Had this small cleanup sitting locally for a while. These include lines are not used.
=> Remove unused boost dependency from public header hash.h

src/include/OpenImageIO/simd.h
nocona cpu's have SSE3 without SSSE3 which breaks by including tmmintrin.h
clang 3.3 - 3.7 and gcc 4.2 4.6 and 4.8 all seem to force this to be an error.
```/usr/include/clang/3.4.1/tmmintrin.h:28:2: error: "SSSE3 instruction set not enabled"```
While nocona cpu's are getting old, when a user has set nocona as the target arch the SSSE3 header comes in and breaks the build.
=> Separate test for SSE3 and SSSE3

src/libutil/ustring.cpp, src/libutil/ustring_test.cpp
This makes it work (and adds a test).
We still need to return and do something more clever for that case. I'll need to install gcc 5.1 first to see how the internals work. But in the mean time, at least this will unbreak things for people already on gcc 5.1.
Fixes #1174
=> ustring fixes for new gcc (5.1+) std::string ABI

CMakeLists.txt
Ugh, before 3.6, it doesn't know that warning, so it's an error to give it the command line option to suppress the warning.
The most important thing is just to enclose that -Wno-unused-local-typedefs in a version check (lines 113-115). All the rest is just getting the version from the compiler.
=> Amend last clang 3.6 fix -- ONLY suppress that warning for > 3.5

src/python/py_imagebuf.cpp
On my machine, building with warning treated as errors (the default I presume) results in the following error message regarding a comparison between signed and unsigned integer types. This PR fixes the issue using an appropriate cast.
```
In function ‘bool PyOpenImageIO::ImageBuf_set_pixels_array(OpenImageIO::v1_6::ImageBuf&, OpenImageIO::v1_6::ROI, boost::python::numeric::array)’:
/home/ghislain/workspace/oiio/src/python/py_imagebuf.cpp:371:55: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
if (type == TypeDesc::UNKNOWN || size*type.size() > pylen)
```
EDIT: added error message
=> fix signed / unsigned comparison error

src/doc/builtinplugins.tex, src/doc/imageinput.tex, src/doc/maketx.tex, src/libOpenImageIO/maketexture.cpp, src/tiff.imageio/tiffoutput.cpp
If present and set to 0, will not write an Exif tag directory to the file, even if Exif metadata is otherwise present. This can be useful when writing a TIFF file intended to be read by an application that links to a version of libtiff that is too old to properly read the Exif data and don't want it confused.
Note in particular that PRMan may fall into that category. Therefore, if you are using 'maketx' to prepare texture files for use with PRMan, you may find it prudent to set this special metadata like this:
maketx input.tif -prman -attrib "tiff:write_exif" 0 -o output.tx
=> Have TIFF output recognize special "tiff:write_exif" metadata.

src/doc/imageoutput.tex, src/jpeg.imageio/jpeg_pvt.h, src/jpeg.imageio/jpegoutput.cpp
I noticed that the JPEG reader mis-declared "supports", not having the const label, and so wasn't properly overriding the base class. Similar fix in the docs.
=> JPEG bug fix: misdeclared supports()

src/doc/pythonbindings.tex, src/include/OpenImageIO/imageio.h, src/python/py_imagebuf.cpp, src/python/py_imageoutput.cpp, src/python/py_oiio.cpp, src/python/py_oiio.h, testsuite/python-imageoutput/test_imageoutput.py
Change Python ImageOutput bindings to simplify the write_* methods.
They, oddly, took both an array and a TypeDesc describing the array. Nix the TypeDesc and just figure out the array type. If they didn't match, it would only have been trouble. Also, get rid of the stride parameters, they make sense in a C++ context, but are just confusing to Python.
=> Python bindings: revise ImageOutput

Makefile
Lets you instruct the build to skip OpenCV, even if it thinks it can find it on your system.
=> Top-level Makefile option for USE_OPENCV=0

src/python/py_imageoutput.cpp
Fixes this compiler warning/error:
`error: comparison between signed and unsigned integer expressions`
cheers
=> fixed compiler warnings due to type mismatch (size_t vs. int)

src/include/OpenImageIO/dassert.h
Use standard stuff for C++ >= 11 varieties, fall back on boost otherwise.
There are some place where I'd like to use static assertions.
=> OIIO_STATIC_ASSERT and OIIO_STATIC_ASSERT_MSG

src/oiiotool/oiiotool.cpp
oiiotool should suppress output of the "textureformat" metadata it inherited from any input, if it's not plausibly still a valid texture (in particular, if it's no longer tiled and MIPmapped).
=> oiiotool should suppress output of the "textureformat" metadata

src/include/OpenImageIO/array_view.h, src/include/OpenImageIO/coordinate.h, src/libutil/array_view_test.cpp
This is very close to backwards-compatible with our first implementation (which we did not yet use in any public APIs, so we shouldn't feel very conservative about it anyway).
The biggest change is that it is now templated on Rank (number of dimensions), so you can have 2D, 3D, etc., array views. The default is 1D, which works much as before.
Even for the 1D case, we re-jiggered our implementation and API to be very compatible with what appears to be on its way into C++17. After C++17 is released, we hope to phase out our own, so we seek compatibility. One change that came along with this is the offset<> and bounds<> templates in coordinate.h.
Also for conformance to what appears to be heading for C++17, we changed our implementation of array_view_strided to have the strides measured by …
=> Refactor array_view to be more in line with what is developing for C++17

src/doc/builtinplugins.tex, src/doc/openimageio.tex, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp, testsuite/tiff-suite/ref/out-alt.txt, testsuite/tiff-suite/run.py
The TIFF reader now correctly notices and reports the full range of possible compression modes supported by libtiff. The writer still only supports a subset of them, primarily because nobody needs them and I don't want to bother carefully testing their correctness.
Enable (previously-broken) reading of JPEG-compressed TIFF and YCrCb encoded images (even when the chroma is subsampled), as well as LAB and LOG encodings. For these rare edge cases we fall back on libtiff's "ReadRGBAImage". This makes some compromises (such as forcing uint8 and buffering the whole image), but I think it's well worth supporting these in a low-performance and low-precision way rather than not at all, yet not worth the immense effort to get fully performant support for these varieties that are extremely rare. …
=> TIFF support a wider range of compression and photometric modes.

src/nuke/txReader/txReader.cpp
Fixes a crash in the Nuke txReader when a .tx file is selected in the Nuke clip browser while the preview pane is open.
Issue: https://github.com/OpenImageIO/oiio/issues/1211
=> nuke: Handle NULL Knob* in TxReaderFormat::setMipLabels

src/include/OpenImageIO/argparse.h, src/libutil/argparse.cpp, src/maketx/maketx.cpp, src/oiiotool/oiiotool.cpp
This is really helpful for programs with many command line options.  The briefusage can be used by default, quickly listing all commands, while --help (or some other trigger) can call the very long usage() with full explanations of every command, its arguments, and description.
Used this new feature for oiiotool and maketx.
As an example, here is the original output from running "maketx" with no arguments, as well as when you use --help:
$ maketx --help
maketx -- convert images to tiled, MIP-mapped textures
OpenImageIO 1.6.5dev http://www.openimageio.org
Usage:  maketx [options] file...
--help                   Print help message
-v                       Verbose status messages
-o %s                    Output filename
--old                    Old mode
--threads %d             Number of …
=> ArgParse: new briefusage() method prints briefer help message.

CHANGES, src/doc/imagebufalgo.tex, src/doc/oiiotool.tex, src/include/OpenImageIO/color.h, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/color_ocio.cpp, src/oiiotool/oiiotool.cpp, src/python/py_imagebufalgo.cpp, testsuite/oiiotool-spi/run.py
In ImageBufAlgo (C++ and Python) and via oiiotool command line, we exposed OpenColorIO color conversion, look transforms, and display transforms.
There's something called a "filetransform" in OCIO which we didn't expose and now somebody needs it. This patch does it.
Also fix a minor bug in oiiotool (oiiotool.cpp:3530) using --autocc that will crash if the color space isn't found in the filename, because it checks for metadata before the file has been read, and falls off a NULL pointer when looking for the ImageSpec. A simple call to read the file in that case fixes.
=> ociofiletransform

site/spi/Makefile-bits-arnold, site/spi/Makefile-bits-spcomp2, src/cmake/externalpackages.cmake
I don't expect anyone not at SPI to understand or care about this. It's all in the site/spi specific parts, so won't affect anyone else.
Bump SpComp2 version and change spcomp2 build to use clang.
Major refactor of the Makefile-bits-arnold and Makefile-bits-spcomp2 to bring them in sync. It was a mess to try to understand how they differed before. Now you can xxdiff them and they are 90% identical, easy to see how they differ. I think that at some point after our upcoming OS upgrade (which will deprecate the whole 'spinux1' platform) I'll probably completely unify these two files. But for now, this is already a big cleanup accomplished, and I'm exhausted.
The overhaul isn't quite as awful as it looks. The arnold makefile had the spinux1 case first, then rhel4, whereas the spcomp2 version …
=> Changes for SPI build procedures

src/doc/builtinplugins.tex, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp, testsuite/tiff-depths/ref/out.txt
We always read all these oddball bit depths, just didn't write them,
instead we would round to uint8 or uint16.
=> Make TIFF output support 2, 4, 10, and 12 bits unsigned per sample.

CMakeLists.txt
Tried also to do a little refactoring for simplification of the compiler-specific bits of the CMakefile.
This was prompted by Apple's xcode 7.0 release, which broke a lot of our clang version detection.
I'll need to make an identical change to OSL.
=> cmake: Better detection of Clang version, including Apple vs OSS Clang.

src/iconvert/iconvert.cpp, src/igrep/igrep.cpp, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imageioplugin.cpp, src/libOpenImageIO/iptc.cpp, src/libOpenImageIO/xmp.cpp, src/libutil/strutil.cpp, src/libutil/strutil_test.cpp, src/maketx/maketx.cpp, src/oiiotool/diff.cpp, src/oiiotool/imagerec.cpp, src/oiiotool/oiiotool.cpp, src/socket.imageio/socket_pvt.cpp
Remove the last of the "bare" boost::filesystem references, EXCEPT the ones that are necessary inside the implementation of our Filesystem wrappers.
Remove references to boost::tokenizer, in favor of our Strutil::split.
=> Remove references to boost filesystem and tokenizer.

src/doc/imageinput.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imageinput.cpp, src/python/py_imageinput.cpp, src/python/py_oiio.h
Did this a few days back, related to something else I'm working on.
We have variants of read_scanlines and read_tiles that let you specify a contiguous subset of channels (for some formats, may be more efficient than reading all channels when you only need some). But we lacked a version of read_image that let you specify a channel range, so this just makes it symmetric to the others.
=> Add an ImageInput::read_image() variant that reads a subset of channels.

src/tiff.imageio/tiffoutput.cpp
Hi, this patch fixes a compiler warning due to signed/unsigned comparison mismatch.
Unless there's a valid reason to have a negative number of bits per pixel that I'm not aware of?
cheers
=> resolves "error: comparison between signed and unsigned integer expressions"

src/libOpenImageIO/imagebufalgo_xform.cpp, src/libutil/filter.cpp
This fixes artifacts that occur when using them as upsizing filters.
=> Turn lanczos3 and catrom filters from fixed width to scalable.

src/idiff/idiff.cpp
In quiet mode, output nothing for success, only minimal error messages to stderr for failure. The return code of running the program still indicates success or failure.
Fixes #1229
=> idiff -q makes quiet mode

src/iff.imageio/iffoutput.cpp
Weird construct when copying the 2 bytes of the uint16 value.
Fixes #933
=> Fix bug in IFF output of 16 bit uncompressed data.

src/pnm.imageio/pnminput.cpp, testsuite/pnm/ref/out.txt
Since PFM is uncompressed, we merely remember the file position right after the header ends, and when we need a scanline, seek to the right spot.
Fixes #1170
=> PFM file read: scanline order of pfm is bottom-to-top

src/doc/builtinplugins.tex, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp, testsuite/tiff-depths/ref/out.txt, testsuite/tiff-depths/run.py, testsuite/tiff-suite/ref/out-alt.txt, testsuite/tiff-suite/ref/out.txt
Needed at my place so that our usual oiiotool-based color correction pipeline can deliver certain marketing assets that need to be CMYK for some reason. 
The refactor of the TIFF code to make all this work was a little more involved than I'd hoped. It's not conceptually hard, but some code got shuffled around.
=> TIFF CMYK support

src/doc/imagecache.tex, src/doc/texturesys.tex, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texture3d.cpp, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp
Allow ImageCache/TextureSystem to store partial channel sets in cache.
ImageCache's original design would read all channels into a tile,    because (1) most files have only a few channels, (2) most uses (for    example, texture) tend to use most or all of the channels in the file,    in close temporal proximity if not in the same lookup, (3) most file    formats don't have a way to read a channel subset that's any more    efficient than reading all of them.
However, for the rare case that there are MANY channels, only a few of    which are needed (for example, looking up 3 channels of textures from a    40 channel file), this is very wasteful of texture space, and MAY    (depending on the format) also be wasteful of I/O.
So this patch:
* Modifies ImageCache so that a tile can store any …
=> Allow ImageCache/TextureSystem to store partial channel sets in cache.

src/libtexture/imagecache.cpp
We realize how a particular combination of multithread, low cache memory
limits, and big tiles / untiled can inadvertently trigger these
assertions. Let's turn it into a DEBUG-only assertion for now, so it
won't happen for release builds.
As a more long-term plan, we should probably automatically bump up the
cache limits any time we encounter a tile that is itself bigger than
the memory limit, to avoid hitting this impossible situation.
For detailed discussion, see https://github.com/OpenImageIO/oiio/issues/1239
Fixes #1239
=> Change tile & file limit assertions from ASSERT to DASSERT.

site/spi/Makefile-bits-arnold, site/spi/Makefile-bits-spcomp2
SPI -- use C++11 for rhel7 builds. Also fix missing rpath for field3d and other minor fixes.
Non-SPI don't need to worry about this, it won't affect you.
=> SPI -- use C++11 for rhel7 builds. Also fix missing rpath for field3d

src/doc/imageioapi.tex, src/libOpenImageIO/imageio.cpp, src/oiiotool/oiiotool.cpp, src/openexr.imageio/exrinput.cpp
The global OIIO "threads" attribute controls the default "fan out" of
spawned threads when an OIIO call has work that can be parallelized
(like for ImageBufAlgo functions). Apps with essentially single logic
thread leave this at 0, which means to spawn #cores threads, whereas
apps with lots of app-side threads set it to 1 to prevent OIIO from
internally spawning many threads for each app calling thread.
Unfortunately, we were using the same attribute value to set the size of
OpenEXR's thread pool size. In an app where we set "threads" to 1 to
prevent OIIO fan-out, this was unfortunately also limiting OpenEXR's
worker thread pool to 1, which means the various threads would block
against each other.
It seems like the best solution is to break this apart into separate
attributes: "threads" …
=> Separate global "threads" and "exr_threads" attributes.

src/doc/builtinplugins.tex
I spotted a typo in the documentation for the Tiff plugin, so this fixes it...
=> Fix typo in Tiff plugin documentation

src/tiff.imageio/tiffinput.cpp
I came across some documents that made me think that there may be TIFF files that directly have these tags in the main directory. So may as well recognize them.
=> TIFF: Recognize Exif tags in the regular directory, not special Exif dir.

src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageio_pvt.h.in, src/libOpenImageIO/imageioplugin.cpp, src/openexr.imageio/exroutput.cpp
It's echoed to stderr if global attribute("debug") is nonzero.
It defaults to 0 for ordinary runs, 1 for DEBUG, and the default is
overridden by he value of environment variable OPENIMAGEIO_DEBUG, if
present.
Suggested in #1242 
It is preferred that OIIO-internal code that's tempted to echo anything to stderr or stdout for debugging purposes (for example, selectively only when not NDEBUG) use this instead.
I have done this in a couple spots, but have not comprehensively scoured the code looking for examples. We can do it lazily, as we are visiting other parts of the code base.
=> OIIO::debugmsg() preferred over raw debugging output to stderr or stdout.

CMakeLists.txt, src/doc/imagebuf.tex, src/doc/imageinput.tex, src/doc/imageoutput.tex, src/include/OpenImageIO/imagebuf.h, src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/oiioversion.h.in, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imageinput.cpp, src/libOpenImageIO/imageoutput.cpp
Please see also #1258, this is an alternate proposal for the same basic issue. I think this one is far less intrusive to the APIs, and am leaning toward this if nobody strongly prefers the other.
----
This allows control over thread spawning for any ImageInput or
ImageOutput internals that may have the opportunity to parallelize work,
similar to the parameter on the various ImageBufAlgo functions. A value
of 0 means to use the global OIIO::attribute("nthreads") value (which in
turn defaults to have a thread fan-out equal to the hardware
concurrency). For a sole thread of execution, you want a big fan-out for
tasks that can be parallelized, whereas when the calling function is one
of many concurrent threads already underway, you just want the work done
directly by the calling thread, …
=> ImageInput/ImageOutput API change to allow thread policy per file.

src/include/OpenImageIO/array_view.h, src/include/OpenImageIO/coordinate.h, src/include/OpenImageIO/dassert.h, src/include/OpenImageIO/filesystem.h, src/include/OpenImageIO/imagebufalgo.h, src/include/OpenImageIO/imagebufalgo_util.h, src/include/OpenImageIO/strutil.h, src/include/OpenImageIO/unordered_map_concurrent.h, src/libtexture/imagecache_pvt.h
Some C++11 related cleanup.
The most important item is that when C++11 is detected, std::unordered_map will always be used rather than boost::unordered_map.
The rest is mostly changes to comments or minor rearrangements of headers.
=> C++11 cleanup

src/doc/imagebufalgo.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/python/py_imagebufalgo.cpp
For reasons I no longer remember, IBA::channels() didn't take an 'nthreads' parameter and didn't try to parallelize itself for large images.
Now it does.
=> Make IBA::channels() take an 'nthreads' parameter

src/include/OpenImageIO/sysutil.h, src/libOpenImageIO/imageio.cpp, src/libutil/atomic_test.cpp, src/libutil/spin_rw_test.cpp, src/libutil/spinlock_test.cpp, src/libutil/sysutil.cpp, src/libutil/ustring_test.cpp, src/testtex/testtex.cpp
These are merely implemented in terms of boost::thread functions of the same name.
But by wrapping them in Sysutil, it's part of a plan to reduce the need to include boost thread.hpp, especially for C++11.
Also, change our default concurrency (OIIO attribute("threads")) to physical rather than virtual cores. On the more recent boost (1.56 and higher), physical_concurrency is a more accurate count of physical cores, rather than virtual/hyperthread cores, so let's default to that for our concurrency (hyperthread cores aren't all they're cracked up to be; I feel comfortable defaulting to number of physical cores and of course the user can overthread to take hyperthreading into consideration if they want).
=> Sysutil::hardware_concurrency and physical_concurrency()

src/ffmpeg.imageio/ffmpeginput.cpp, src/include/OpenImageIO/imagebufalgo_util.h, src/include/OpenImageIO/refcnt.h, src/include/OpenImageIO/thread.h, src/iv/ivimage.cpp, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/imagebufalgo_compare.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp, src/libOpenImageIO/imagebufalgo_draw.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/libOpenImageIO/imagebufalgo_xform.cpp, src/libOpenImageIO/imagebufalgo_yee.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/maketexture.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texoptions.cpp, src/libtexture/texture_pvt.h, src/libutil/optparser_test.cpp, src/libutil/ustring_test.cpp, src/socket.imageio/socket_pvt.h, src/socket.imageio/socketinput.cpp, src/testtex/testtex.cpp, src/tiff.imageio/tiffinput.cpp
A series of changes with the aim of using only std, no boost, in public headers. For the most part, these only come into play with compiling with USE_CPP11=1. C++03 compiles still fall back to the boost versions.
There were three main sets of changes:
* thread.h: use std::mutex, recursive_mutex, lock_guard, thread, and make a simple thread_group, all to take the place of boost components of the same names. Also remove mention of thread_specific_ptr from thread.h, use the boost one directly from the couple of specific places in internals where we need it.
* refcnt.h handles all the reference-counted pointers -- use std::shared_ptr instead of boost, and make our own intrusive_ptr.
* imagebufalgo_util.h now uses the OIIO-namespaced thread_group, bind, ref, cref (which are std or our own for …
=> C++11 use boost alternatives (mainly std)

.travis.yml, CMakeLists.txt, Makefile, README.rst, src/travis/before_install.bash, src/travis/install.bash
This is an initial setup. At this moment, it only builds for OSX using clang.  Just getting my feet wet with it, but eventually we'll flesh it out to a more extensive build matrix.
I've still got lots of bells and whistles to add, and there's some debug scaffolding. 
Just a first stab, but it's already becoming kind of useful.
=> Travis setup

src/include/OpenImageIO/array_view.h
* array_view::size() must be constexpr only when bounds.size() is (C++14 only)
* Give explicit namespace for OIIO::bounds class type so it doesn't clash
with the name for array_view::bound() method.
=> Fix compiler warnings related to array_view

src/doc/imageioapi.tex, src/doc/openimageio.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/typedesc.h, src/libutil/typedesc.cpp, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp, src/python/py_typedesc.cpp, testsuite/python-typedesc/ref/out.txt, testsuite/python-typedesc/test_typedesc.py
Please see #1265. GitHub doesn't let me propose changes on the same ticket, grr. This is 99% the same as @shootfast's proposal, but I have
1. Added the Python binding changes he forgot.
2. Modified the docs appropriately.
3. Reverted a tiny bit so that the string representation of 4x4 matrices remains "matrix" rather than changing it to "matrix44". I'm proposing that we use "matrix33" is for 3x3, but stay with plain "matrix" for the usual common CG case of 4x4, for the same reason that "point" is the common CG case without needing to be called "point3"; and this way, we don't introduce any compatibility breaks for apps that expect the current behavior (especially for OSL).
If everybody is ok with this, before merging I will squash it down to just two commits: (a) all the changes to …
=> Alternative to #1265 openexr 3x3 matrix

.travis.yml, CMakeLists.txt, src/build-scripts/install_homebrew_deps.bash
Last night's web surfing discovery: 5 lines added to CMakeLists.txt that causes it to use ccache if it's installed on the system. 
This cuts the Travis build time in half, and also will speed up OIIO builds for anybody else with ccache on their system but haven't taken any steps on their own to use it. I can't think of any down-sides to this, can you?
Also some cleanup and reformatting after discovering that in the .travis.yml file I can split commands over several lines, makes it more readable.
=> Travis -- clean up, and use ccache

src/libOpenImageIO/imagebufalgo_deep.cpp
In the latest [OpenEXR documentation](http://openexr.com/TechnicalIntroduction.pdf), it is recommended to use AR/AG/AB channel names for RGB alpha, instead of RA/GA/BA. The latter was recommended in an earlier version of the documentation, and still recognized in this patch for compatibility.
=> Deep OpenEXR: recognize newer AR/AG/AB channel name convention.

src/tiff.imageio/tiffinput.cpp
This could run off the end of a buffer when reading images with
unassociated alpha, if the calling app passed an unusual ystride (or,
in the case I found, using a negative stride to flip the process
in the process of reading it).
=> TIFF read_scanlines of images with unassociated alpha didn't honor stride

src/include/OpenImageIO/dassert.h, src/include/OpenImageIO/platform.h, src/include/OpenImageIO/thread.h, src/libutil/hashes.cpp
(Note: I just found this lurking in my tree, something I did many weeks ago and never submitted.)
* Make sure LIKELY/UNLIKELY are defined for clang and Intel.
* More straightforward way to generate bools for LIKELY/UNLIKELY.
* Use OIIO_UNLIKELY in the ASSERT macros, since by definition we
aren't expecting the condition to usually be true.
* Feature-testing macro definitions for compilers that lack them
(and use them).
* More robust test for including windows.h.
* Remove redundant definitions from thread.h and hashes.cpp.
=> Minor platform.h related fixes

src/doc/imagebufalgo.tex, src/doc/maketx.tex, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/maketexture.cpp
Compare the command line from the last build (in the metadata) with the
current one, to help decide whether the texture needs to be rebuilt.
=> maketx -u : remake the file even with matching dates, for different command lnes

src/doc/builtinplugins.tex, src/doc/imageioapi.tex, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imageio.cpp, src/tiff.imageio/tiffoutput.cpp
Enable TIFF write of 'half' pixels, if "tiff:half" attribute is nonzero.
Set up a global OIIO attribute "tiff:half" that sets the default globally,    and also have the ImageOutput for TIFF recognize a per-file "tiff:half"    override. The default in both cases is 0, meaning that requests for    half pixel float files in the absence this attribute nonzero will be    automatically be upgraded to float, which is more widely read.
The reason for this is that nearly every non-OIIO-based reader fails to    correctly recognize half-valued pixels in TIFF files, including    PhotoShop and Nuke 9. So you are urged not to write half tiff, unless    you are sure that the only consumer of those files uses OIIO (which can    read them properly), or have verified that other consumers in your …
=> Enable TIFF write of 'half' pixels, if "tiff:half" attribute is nonzero.

.travis.yml, CMakeLists.txt, Makefile
* Top-level USE_CCACHE=0 can turn it off no matter what
* Avoid ccache if we're using clang and compiling Qt headers and the
$CCACHE_CPP2 env var is not set -- this leads to problems.
=> Refine ccache logic

Makefile, testsuite/runtest.py
Among other things, this makes things a lot easier when inspecting failed Travis builds -- the travis log will show the test output and any text file comparisons that fail.
=> Minor adjustments to make failed tests print their output and .txt files

src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp
Fixes #1282 -- oiiotool --ch was noticed to fail for deep images when the --ch didn't actually change or reorder the channels.
Some investigation showed that this "straight copy" fell back on the simpler ImageBuf::copy(), which in turn was not deep-safe. This patch fixes that.
Also noticed along the way the existence of a closely related but subtly incompatible method copy_from(), which also was both not public and never used! So remove it.
=> Fix IB::copy() and oiiotool --ch for deep

src/doc/imagebuf.tex, src/doc/imageioapi.tex, src/doc/openimageio.tex, src/doc/pythonbindings.tex, src/iinfo/iinfo.cpp, src/include/OpenImageIO/deepdata.h, src/include/OpenImageIO/hash.h, src/include/OpenImageIO/imagebuf.h, src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/oiioversion.h.in, src/libOpenImageIO/deepdata.cpp, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imageinput.cpp, src/libOpenImageIO/imageoutput.cpp, src/oiiotool/printinfo.cpp, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp, src/python/py_deepdata.cpp, src/python/py_imagebuf.cpp, src/python/py_oiio.h, src/testtex/testtex.cpp, testsuite/openexr-v2/ref/out.txt, testsuite/python-deep/test_deep.py, testsuite/python-imagebuf/ref/out-alt.txt, testsuite/python-imagebuf/ref/out.txt, testsuite/python-imagebuf/test_imagebuf.py
DeepData is ok for simple passing of data in and out of the ImageInput/ImageOutput functions, but its internal layout is actually horrible for doing any actual work. (Exercise for the reader: try to imagine how to add or delete individual samples in a particular pixel of a DeepData.)
I have longer-term goals of overhauling its internals to make these operations natural and efficient. But as a first step, I need to properly hide the current internals so that I'm free to change them later.
This patch has hides the internals of DeepData -- everything is private now, and the nontrivial parts are hidden behind a PIMPL idiom. So "client" code is now forced to use the public methods. This is going to be slightly painful for apps that are used to reaching into the guts and manipulating the …
=> DeepData refactor

src/doc/imageioapi.tex, src/doc/pythonbindings.tex, src/python/py_imagespec.cpp, src/python/py_oiio.cpp, testsuite/python-imagespec/ref/out.txt, testsuite/python-imagespec/test_imagespec.py
This is embarrassing: somehow we never added the global getattribute() calls to the Python bindings.
Also notice that the Python bindings for ImageSpec::getattribute were incorrectly bound to "get_attribute". So add "getattribute" and consider "get_attribute" a deprecated synonym.
I will backport this to 1.6, despite being at RC stage, since this is an obvious bug.
=> Fix missing Python bindings for OIIO::getattribute

src/include/OpenImageIO/deepdata.h, src/libOpenImageIO/deepdata.cpp, src/openexr.imageio/exroutput.cpp
The trickiest issue involved DeepData::get_pointers (std::vector<const void*>&). Some compilers won't eat a vector of a const type. Others seem fine.    Sidestep the problem by removing this variety of DeepData::get_pointers,    it's not necessary with the right casting inside the non-const version.
=> Fix compiler warnings

src/cmake/externalpackages.cmake, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp, src/python/py_imagecache.cpp, src/python/py_imagespec.cpp, src/python/py_oiio.h
Fixes #1299 
I don't know why it worked before or why it's broken now, but the    just-release Boost 1.60 refused to build OIIO, and all the problems    were in the ImageCache bindings. And they were weird, and in retrospect    some of the calls would probably not ever have worked. So after a big    refactor, we are building against Boost 1.60 and passing all tests. Luckily, the Python bindings for ImageCache are all but undocumented, and I suspect unused, so this late-stage overhaul should probably not hurt anyone. And I assure you, what we have before was very, very broken.
Along the way I noticed that ImageCache and TextureSystem both have their getattribute() methods curiously not marked as const! Sorry, that needs to be fixed. I need to backport all this to 1.6, and this would …
=> Fix for compilation with Boost 1.60 -- major Python ImageCache overhaul

src/include/OpenImageIO/filesystem.h, src/libutil/filesystem_test.cpp
Add tests for parent_path, path_is_absolute, replace_extension,
searchpath_split, read_text_file, fopen, create_directory,
exists, is_regular, is_directory, copy, rename, remove.
This makes filesystem_test almost completely test the contents of
filesystem.h. The only things still not directly tested are things that
would vary from run to run or from system to system, such as
get_directory_entries, temp_directory_path, unique_path, current_path,
and last_write_time.
=> filesystem_test: much more thorough testing

src/include/OpenImageIO/imagebufalgo_util.h, src/libOpenImageIO/imagebufalgo.cpp
This new flag causes an uninitialized destination image to be initialized with FLOAT pixels, rather
than the same type as the input image. Can be handy.
=> Add IBAPrep flag DST_FLOAT_PIXELS

src/include/OpenImageIO/imagebufalgo_util.h
* Ability to specify split direction (x, y, z, or along the longest axis).   The default is Y, which I found to be the fastest (about 3% faster than X, probably because of cache layout issues), but I can imagine algorithms for which you want a different choice.
* Raise the "minimum chunk size" to 16k pixels. It's not worth spawning  a thread to do less work than that. This should help when IBA functions are used on very small image regions for which the thread setup/teardown are significant costs compared to the actual work.
* Do the last chunk with the calling thread itself rather than needlessly  spawning yet another thread only to have the caller block until it's done.
=> Minor improvements to parallel_image:

src/libOpenImageIO/deepdata.cpp
When there are no samples for a pixel, the pointer to a particular sample (which should not be used) will compute something meaningless, which triggered the assertion.
=> DeepData::get_pointers - Fix pointer botch for 0-sample pixels

src/include/OpenImageIO/imagebuf.h
Another review from winter break. :-)
This small change -- guaranteeing inlining of two methods and slight
rearrangement of conditionals -- cuts the time it takes an iterator to
traverse an image by half, thus making it only a little bit slower than
looping over an array of pixels.
=> ImageBuf::Iterator performance improvement -- reduce "iterator penalty" by 50%

.travis.yml, src/include/OpenImageIO/array_view.h, src/libtexture/texturesys.cpp, testsuite/oiiotool-readerror/ref/out.err-debug.txt, testsuite/runtest.py
Make sure Travis CI includes a DEBUG build so we will never again check something in that works for optimize builds but breaks a debug build. Fix the few minor warnings and test failures that show up for DEBUG builds.
=> Add DEBUG build & test to Travis-CI matrix

src/include/OpenImageIO/simd.h
immintrin.h seems to always include a bunch of other files that we included explicitly, so those extra includes can go away.
Also, the guard around x86intrin.h needs to ensure that gcc version is at least 4.4 and it's also unnecessary unless f16c is requested.
=> simd.h include file logic cleanup.

src/include/OpenImageIO/hash.h, src/include/OpenImageIO/imagebuf.h, src/include/OpenImageIO/imagebufalgo.h, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/platform.h, src/include/OpenImageIO/texture.h, src/include/OpenImageIO/timer.h, src/include/OpenImageIO/typedesc.h, src/include/OpenImageIO/ustring.h, src/iv/imageviewer.h, src/iv/ivgl.cpp, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebuf_test.cpp, src/libOpenImageIO/imagebufalgo_compare.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp, src/libtexture/imagecache.cpp, src/libutil/hash_test.cpp, src/libutil/timer_test.cpp, src/libutil/typedesc.cpp, src/oiiotool/oiiotool.cpp, src/python/py_imagebuf.cpp, src/python/py_imagebufalgo.cpp, src/testtex/testtex.cpp
Mimics this PR from OSL: https://github.com/imageworks/OpenShadingLanguage/pull/602
Start marking deprecated things in public APIs as OIIO_DEPRECATED, and then it will generate warnings (hopefully with helpful tips for what to use instead) when apps use the deprecated calls.
=> OIIO_DEPRECATED

src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/CMakeLists.txt, src/libOpenImageIO/compute_test.cpp, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp
More fun from winter break...
I constructed a compute_test that benchmarks a number of ways of traversing an ImageBuf to do some math (in this case, R = A*A+B, three HD-res float images, RGB). Many ways to do it, how fast are they? Sample output like this:
```
Test straightforward as 1D array of float: 1658.6 Mvals/sec
Test array iterated like an image: 581.8 Mvals/sec
Test array iterated like an image, multithreaded: 2132.8 Mvals/sec
Test array as 1D, using SIMD: 1675.9 Mvals/sec
Test array iterated like an image, using SIMD: 1514.3 Mvals/sec
Test array iterated like an image, using SIMD, multithreaded: 3333.2 Mvals/sec
Test ImageBufAlgo::mad 1 thread: 352.6 Mvals/sec
Test ImageBufAlgo::mad multi-thread 4: 1245.9 Mvals/sec
```
There are some interesting observations here.
* Just looping …
=> Speed up IBA::mad, and compute speed tests

src/libtexture/imagecache.cpp
The original worked fine on all my platforms, but on certain Debian i386-based (32 bit) platforms, something funny about the original typecast/conversion ended up with m_max_memory_bytes == 0. This formulation of the cast appears to work correctly everywhere.
=> Be more careful with flaot max_memory_MB to long long max_memory_bytes conversion

src/iinfo/iinfo.cpp, src/include/OpenImageIO/typedesc.h, src/libutil/typedesc.cpp, src/oiiotool/printinfo.cpp, testsuite/dpx/ref/out.txt, testsuite/gif/ref/out.txt, testsuite/ico/ref/out.txt, testsuite/openexr-v2/ref/out.txt, testsuite/psd/ref/out-alt.txt, testsuite/psd/ref/out.txt, testsuite/ptex/ref/out.txt, testsuite/tiff-suite/ref/out-alt.txt, testsuite/tiff-suite/ref/out.txt
Something I fixed up during recent debugging -- more clear printing of the number of channels and formats, when summarizing the different subimages.
=> iinfo/oiiotool -info : more clearly print subimage formats

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
Define insert and extract for mask4 (already existed for float4 & int4).
Add xor for mask4 (int4 already had it).
Add bitwise complement for int4 and mask4.
Efficient int4::NegOne()
=> SIMD additions

src/libtexture/imagecache.cpp
On the last try (or the only try, if failure_retries was 0), we were
needlessly delaying.
=> IC: upon read failure, pause *between* tries, not *after* tries.

src/libOpenImageIO/imageinput.cpp, src/oiiotool/oiiotool.h, src/oiiotool/printinfo.cpp
A cascade of things we noticed when reading exr files with missing tile errors...
* For EXR read_tiles, neglecting to take an early out when the read fails (as we did for read_tile, read_scanline, read_scanlines) caused a confusing error message on the wrong topic to be printed.
* Error propagation is tricky in ImageBufAlgo functions when the ImageBuf's they are operating on are backed by ImageCache. A tile or scanline read error doesn't happen up front, it can happen as you iterate (when you pass from a valid tile to one that can't be read). But we don't want to slow things down by checking for read errors at every pixel, so instead use a generic way of checking after the IBA operation for any read errors accumulated along the way.
* Make sure that oiotool --stats passes along meaningful …
=> Tighten up error reporting

.travis.yml, CMakeLists.txt, Makefile, site/spi/Makefile-bits-arnold, site/spi/Makefile-bits-spcomp2
This does NOT make the codebase C++11-only. Although that will happen
sooner or later, almost certainly during the course of 1.7 development.
But for now, this just means that it defaults to C++11, and you need to
proactively use 'make USE_CPP11=0' (or 'cmake -DOIIO_BUILD_CPP11=0') to
stay on C++03 compatibility. This is to ensure that nobody is surprised
when the C++11 switch eventually comes, by requiring them to have
continued awareness that they are living on borrowed time.
=> Change default to USE_CPP11=1

src/cmake/modules/FindOpenEXR.cmake, src/doc/oiiotool.tex, src/oiiotool/printinfo.cpp
I guess I'd only used the `--dumpdata` on deep files?
1. Make sure for non-deep, that it works correctly! It was reading native, then walking through it as if it were float. Instead, read and convert to float properly.
2. For deep, the `--dumpdata:empty=0` option skipped the printing of values of pixels with no samples. For non-deep, make it also do something useful -- skip the printing of values of pixels where all channel values are 0.
=> oiiotool --dumpdata improvements for non-deep

.travis.yml, CMakeLists.txt, Makefile
make CODECOV=1
make CODECOV=1 test
on a gcc/clang system will run the testsuite and generate a code coverage
report in build/$PLATFORM/cov/index.html
I'm not yet sure how we should use this. It's just for information and to help spot places in the code that aren't covered by the testsuite. I do NOT think we should aim to get 100% coverage -- eliminating all the stragglers for every possible error case and early return would be so much labor that we'd never get any real work done. So take with a grain of salt and use wisely.
=> First stab at code coverage

src/libOpenImageIO/compute_test.cpp, src/libutil/atomic_test.cpp, src/libutil/fmath_test.cpp, src/libutil/hash_test.cpp
Some of our unit tests do benchmarking which is helpful for interactive,
optimized builds, but for DEBUG, code-coverage, or CI builds, the times
mean nothing. So in those cases, reduce the number of iterations and don't
do multiple trials. This speeds up running testsuites for those builds.
=> Faster unit tests for debug, code coverage, and continuous integration.

src/libOpenImageIO/imagebufalgo_pixelmath.cpp
Weirdness with const rules at the intersection of std::vector and array_view breaks on some versions of gcc.
Fixes #1364
=> Fix build break with constness and array_view.

src/doc/pythonbindings.tex, src/python/py_imageinput.cpp, src/python/py_oiio.cpp, testsuite/python-imageinput/ref/out-alt.txt, testsuite/python-imageinput/ref/out-rhel7.txt, testsuite/python-imageinput/ref/out-travis.txt, testsuite/python-imageinput/ref/out.txt, testsuite/python-imageinput/src/test_imageinput.py
Python bindings of ImageInout.read_image, read_scanline, read_scanlines,
read_tile, read_tiles:
* If you ask for HALF, since there is no half in Python, return the half
values packed into an 'unsigned short' array. (Old behavior was buggy
and confusing: it packed the half values into a float array of half
the expected size.)
* If you ask for UNKNOWN, like in C++ it means to give the raw/native
data, packed into an 'unsigned char' array. (Old behavior was that
UNKNOWN signified to return data in the type specified by spec.format.
Now, if you want spec.format, pass spec.format.)
* Let the default be type=FLOAT, generate a float array. (Old default was
UNKNOWN spec.format.)
=> Improve Python image input behavior for native data

CHANGES, src/include/OpenImageIO/timer.h
More descriptive, and judging by the comments, the name I originally intended.
=> Rename clobber() -> clobber_all_memory().

src/ffmpeg.imageio/ffmpeginput.cpp
After a recent 'brew upgrade ffmpeg' upgraded me from ffmpeg 2.8.6 to ffmpeg 3.0, it broke my OIIO build.
This seems to fix it.
=> Build correctly against FFMPEG 3.0, after some calls deprecated

src/include/OpenImageIO/fmath.h, src/libOpenImageIO/imagebufalgo_xform.cpp
IBA::resize() : speed up by approximately 2x
* Most of the heavy lifting is done by calculating the horizontal filter    taps for separable filters just once for each pixel column, rather than    for every pixel. (We already had a similar speedup for the vertical    taps, computing them just once per scanline.)
* Refactor a bit to break apart the separable and non-separable cases a    bit more coarsely, to reduce the number of conditionals inside the loop.
* Use Iterator::rerange rather than creating new iterators for each filter.
=> IBA::resize() - double the performance

src/include/OpenImageIO/imageio.h, src/openexr.imageio/exrinput.cpp
**exr_threads**: use -1 to disable usage of OpenEXR thread-pool (and to clean its threads)
See my comment in https://github.com/OpenImageIO/oiio/issues/1375
=> exr_threads: 0 means hardware_concurrency, -1 means no thread-pool

src/include/OpenImageIO/platform.h, src/include/OpenImageIO/timer.h
Define OIIO_CLANG_VERSION and OIIO_APPLE_CLANG_VERSION (similar to the existing OIIO_GNUC_VERSION).
Change definition of OIIO_GNUC_VERSION to be 0 for clang, only have      nonzero value for true gcc.
More careful guard around inline asm, older clang doesn't support it
=> platform.h compiler detection adjustments

src/include/OpenImageIO/color.h, src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/simd.h, src/include/OpenImageIO/timer.h, src/libOpenImageIO/color_ocio.cpp, src/libutil/simd_test.cpp
simd exp, log, pow (exact and approximate/fast versions)
Also add code to simd_test to not only verify that they work, but also
benchmark them.
=> simd exp, log, pow (exact and approximate/fast versions), and speed up sRGB<->linear

src/libOpenImageIO/color_ocio.cpp
* Be a little more forgiving about the color space name being "linear"
versus the color role name being "linear" when determining if we can
fall back on our best guess conversions between linear, sRGB, and
Rec709.
* If OCIO is present and then best it can do when asked for a color
processor is give a NoOp, go ahead and see if the space names
nevertheless are ones for which we have a fallback (linear, sRGB, and
Rec709). We strive to let OCIO handle color transformations if
present, but on the other hand, we know damn well that linear and sRGB
aren't the same, so if OCIO gives us a NoOp to convert between them,
I think it's fair for us to not believe it and try ourselves.
* Address bogusly minimal OCIO configuration in which all known color
spaces are simply marked as "raw" -- it's useless, …
=> Adjustments to color transformations for under-specified OCIO cases.

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/python/py_imagebuf.cpp
Handy conversion from (x,y,z) to indexed pixel within the data window.
We can use this to eliminate some redundant boilerplate code.
=> ImageBuf::pixelindex

src/doc/imagecache.tex, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/libOpenImageIO/imagebuf.cpp, src/oiiotool/imagerec.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
Thematically related but orthogonal changes:
* oiiotool --runstats tracks and reports max memory usage.
* oiiotool new options --cache and --autotile can explicitly set the ImageCache size and autotile settings.
* oiiotool --native behavior is adjusted so that it still uses the cache if the pixel data type is one that the cache supports natively (and it turns off "forcefloat" on the cache). This is actually closer to the way --native was described in the docs.
* ImageBuf::write (used by oiiotool) has been modified to be more memory efficient for very large files -- when IC-backed (not in memory), it will write scanlines or tiles in strips rather than force the whole input image to be read fully into RAM. This doesn't help when using oiiotool for "image processing", which will tend to …
=> Several oiiotool enhancements for big images

src/doc/oiiotool.tex, src/oiiotool/imagerec.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
Add -i command to input file. By default it's the same as just giving the filename, but it can take optional arguments, too.
The optional argument of particular interest to me to day is `-i:now=1` which causes the file to be read immediately, bypassing the cache. (There's also a bunch of other refactoring to make this cleaner.)
The reason this is helpful is for benchmarking, to more cleanly account for time of file reading, without it being spread into other operations, which is what would happen ordinarily for files backed by ImageCache.
=> oiiotool: -i 

src/include/OpenImageIO/deepdata.h, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/deepdata.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp, src/openexr.imageio/exrinput.cpp, src/python/py_deepdata.cpp, src/python/py_imagebufalgo.cpp, testsuite/python-deep/ref/out.txt, testsuite/python-deep/src/test_deep.py
The changes from last week that implemented deep merge were correct but
very inefficient. I realized that because every sample insertion or
deletion would have to insert or delete from the data vector, it was
essentially O(n^2) on the number of pixels.
As an alternate design, we try allowing each pixel to have a "capacity"
(allocated storage within the data array) in addition to "nsamples."
This lets three important things happen: (1) any algorithm that first
establishes the capacity for each pixel, even an approximate guess,
can essentially pre-allocate and apportion the storage without every
individual sample added later copying big portions of the array (much
like how it's helpful for a std::vector to reserve() before lots of
insertions); (2) erasing samples just shifts data in that …
=> Optimization of DeepData.

src/doc/imagebufalgo.tex, src/doc/oiiotool.tex, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/oiiotool/printinfo.cpp
Make IBA::fixNonFinite (and oiiotool -fixnan) work with deep images.
Also speed them up (for the non-deep case) by fixing a bug where, even
though it split the image for threads, each thread examined the whole
image instead of just its part. Oops.
Also modify oiiotool --stats for deep files to print locations of nonfinites.
=> oiiotool --fixnan for deep files

src/libOpenImageIO/color_ocio.cpp
Just a bad variable declaration, inner scope masked outer scope. Led to maketx refusing to do a certain color transform.
=> ColorConfig bug fix -- failed to find ColorProcessor for NoOp transformation

src/include/OpenImageIO/imagebufalgo_util.h, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/libOpenImageIO/imagebufalgo_test.cpp
Previously, when computing functions that had multiple inputs that did not have the same number of channels, ImageBufAlgo functions relied on logic in IBAprep() that would make the result have the number of channels of the FIRST input, but then usually restrict the ROI channel range to the lesser of the inputs. This was strange, having it so that reordering the inputs (for a supposedly commutative operation such as +) would change the channel range of the result.
This set of changes tightens up this logic:
* IBAprep now always chooses a result that's the maximum of the input   image channels by default (though passing the flag   IBAprep_MINIMIZE_NCHANNELS will instead choose the the minimum).
* IBAprep still restricts the ROI to the minimum (i.e. overlapping   channel set), and …
=> IBA: More control over result nchannels when inputs don't agree.

src/libOpenImageIO/imagebufalgo_opencv.cpp
=> Fix unused opencv_mutex compiler warning when not using opencv.

src/cmake/externalpackages.cmake, src/cmake/modules/FindOpenCV.cmake, src/libOpenImageIO/CMakeLists.txt
Fixes #1405 
I had not previously tried to build against OpenCV 3.x. Things have shifted around among the component libraries.
This is a patch against master, but I can backport it to the release branch.
=> Overhaul OpenCV dependency finding; make robust to OpenCV3.

src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp
TIFF is incapable of representing non-(0,0) origin "full" (or display) window. So there are some edge cases we need to handle more deftly:
* When writing to TIFF, if the ImageSpec says the full/display window is   nonzero origin, set it to 0 origin and expand the width&height   accordingly.  That's the best we can do, it's all TIFF can represent.
* When reading TIFF that does not say anything about the full window   at all, assume it should be interpreted as equal to the data window.
=> TIFF: Tighten up logic for non-zero origin of "full" size (aka display window)

src/doc/oiiotool.tex, src/doc/openimageio.tex, src/include/OpenImageIO/typedesc.h, src/libOpenImageIO/formatspec.cpp, src/libutil/typedesc.cpp, src/oiiotool/oiiotool.cpp, src/openexr.imageio/exrinput.cpp, testsuite/dpx/ref/out.txt
SMPTE timecodes are expressed as uint32[2], with various bit field
encodings (see OpenEXR's ImfTimeCode.h for details). This is really
hard for humans to understand and specify, so we take some extra steps:
* Have 'oiiotool -info -v' and 'iinfo -v' print a more human-readable
rendition ("hh:mm:ss:ff") via ImageSpec::metadata_val recognizing this
special case.
* Have oiiotool recognize and encode human-writeable timecode metadata,
as long as the type is specified to be a timecode.
For example:
$ oiiotool in.exr -attrib:type=timecode TimeCode 11:34:03:00' -o out.exr
$ oiiotool -v -info out.exr
Reading out.exr
out.exr              :   64 x   64, 3 channel, float openexr
...
smpte:TimeCode: 287572736, 0 (11:24:03:00)
=> Better handling of timecodes, especially for OpenEXR

src/include/OpenImageIO/thread.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libutil/atomic_test.cpp
A "redundant" read is when we read a tile that has been read before, but    had been evicted from cache and needs to be read again. We can use this    to measure effectiveness of the cache, detect thrashing, and narrow down    which files in particular are experiencing the kind of incoherent access    patterns that leads to redundant reads.
The statistics output now includes: the total number of redundant tiles    and bytes are printed, the per-file stats and totals say the number of    redundant tile reads and the total bytes (of uncompressed I/O) that it    represents, and at the end the "top 3" files are printed that    experienced the most redundant I/O.
This way this works basically involves keeping track of one bit per tile    that indicates if the tile was already read from disk. …
=> ImageCache/TextureSystem: collect stats on redundant reads

src/oiiotool/oiiotool.cpp
The --fullsize wasn't updating the spec properly in both places, and the
subsequent --attrib that re-copies some items from the underlying
ImageBuf's spec into the ImageRec's copy of the spec would overwrite the
previous changes of --fullsize. The --origin code path got it
right. Easy to adjust.
=> oiiotool: --fullsize followed by --attrib could lose the fullsize

src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h
I put these fields here in the very early days of IC development,
anticipating that I would fully elaborate the shadow() lookup functions,
for which these matrices are needed. But it was never a priority, so
they are effectively unused, yet take up a lot of space (64 bytes * 4,
per ImageCacheFile).
I'm not quite brave enough to remove them entirely, out of superstition
that either somebody else is using a modified OIIO that implements
shadow maps, or that the very minute I remove them, some situation will
come up where they are important. So for now I will #ifdef them out.
=> Save space in ImageCacheFile by eliminating unused shadow matrix fields.

src/include/OpenImageIO/typedesc.h, src/oiiotool/imagerec.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
* When no output is specified (and also no -info, etc, are used). This
usually indicates that the user forgot "-o" entirely.
* When an image is modified but not output. This indicates either a
forgotten -o, or even more insidious, using -o and then subsequenty
making more modifications (by users who don't realize that the -o
applies to the *current* top of stack in the sequence of commands,
and does not automatically get moved to the end).
* When -autocc causes output to be of a data format that overrides a
previous -d directive (when the OCIO color space name dictates a data
format or bit depth that contradicts -d).
=> oiiotool add warnings for common noob mistakes

src/include/OpenImageIO/hash.h
* Use std::unordered_map for MSVS 2013+ as well as C++11.
* Define OIIO::hash<> template (either as std::hash or boost::hash).
=> Minor hash.h fixes for C++11 compatibility

src/libOpenImageIO/imageoutput.cpp
This function is used as a helper by various ImageOutput implementations.
If you passed data to write_scanline or write_tile with UNKNOWN format (indicating "native" data) but the data were noncontiguous (the strides didn't match fully packed sizes), you would previously hit an assertion in some circumstances.
=> to_native_rectangle -- handle case with native data but non-contiguous strides

src/oiiotool/oiiotool.cpp
Amends #1419
Slight error failed to mark files as "written" in some output cases where
a temporary image has to be made during output (the temp was marked as
written, rather than the original). This resulted in an incorrect warning
about "modified images without outputting them. Did you forget -o" when
clearly there was a -o.
=> Fix to recent warning patch

src/libOpenImageIO/formatspec.cpp, testsuite/fits/ref/out.txt, testsuite/jpeg2000/ref/out-spinux.txt, testsuite/jpeg2000/ref/out.txt, testsuite/maketx/ref/out-alt-tiff4-2.txt, testsuite/maketx/ref/out-alt-tiff4.txt, testsuite/maketx/ref/out.txt, testsuite/oiiotool-maketx/ref/out.txt, testsuite/targa-tgautils/ref/out.txt, testsuite/tiff-depths/ref/out.txt, testsuite/tiff-suite/ref/out-alt.txt, testsuite/tiff-suite/ref/out.txt
In particular, 1-channel images (from formats without channel naming) will now get R, 2-channel images get R, G.
It's not perfect, because it's probably not really "red" and "green." But before, we were setting the default names to "A" and "I","A".  Which is probably much much worse, because "A" means alpha, and lots of operations treat alpha as special (such as PNG output dividing all the non-alpha channels by the alpha value!).
This is just for formats that don't actually store channel names in the files. Which is most formats.
=> Rethink default channel naming, just use R, G, B, A.

src/dpx.imageio/libdpx/Writer.cpp
gcc6 sets by default -Werror=misleading-indentation
That detects bad indentation in
src/dpx.imageio/libdpx/Writer.cpp
=> gcc6 missleading indentation

src/libtexture/imagecache.cpp
* For the "top 3" stats, print the top 3 that aren't broken. Previously,
if the top ones were also broken in some way, you could end up with
fewer than 3 printed.
* Print a count and list of broken and invalid files.
* A little bit of formatting cleanup
=> Improved IC/TS statistics

src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/imagecache_pvt.h, src/libtexture/texture_pvt.h, src/python/py_imagecache.cpp, src/python/py_oiio.h
It's not used, is empty, isn't even documented. So remove it.
I think this was put in within the first few minutes of laying out these
classes, but in the end was not needed; as the concepts got more refined,
we ended up with invalidate() and its variants.
=> Remove useless IC/TS clear() methods.

src/openexr.imageio/exroutput.cpp, src/png.imageio/png_pvt.h, testsuite/oiiotool/run.py, testsuite/python-imagebufalgo/src/test_imagebufalgo.py
* PNG
The PNG spec is quite particular that a 2-channel image is gray+alpha,    so make sure that we name channels Y,A and designate channel 1 as alpha.
Also, since writing PNG involves automatically un-premultiplying the    color channels by alpha, enforce the fact that for PNG, alpha can ONLY    be the last channel of a 2 or 4 channel image. This prevents an app that    has set channel names or spec.alpha_channel stupidly from messing up the    values in the file (we wouldn't want to un-premultiply by a channel that    can't, by definition, be alpha).
*  OpenEXR write -- watch out for duplicate channel names.
MOST of the time, the channel names in an ImageSpec are merely     "informational." But one of those times when it makes a real difference    is writing OpenEXR files -- if there …
=> More cleanup of bogus channel name edge cases

src/openexr.imageio/exrinput.cpp
Would you believe that there are some files whose headers contain the
TileDescription but aren't really tiled? Oy.
=> More robust detection of whether OpenEXR is tiled.

src/doc/imagecache.tex, src/doc/texturesys.tex, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/unordered_map_concurrent.h, src/libtexture/imagecache.cpp, src/testtex/testtex.cpp
Additional IC-wide (and TS-wide) queries for getattribute():
total_files
all_filenames
And now a variety of per-file statistics may be retrieved via
get_image_info():
broken
stat:tilesread
stat:bytesread
stat:redundant_tiles
stat:redundant_bytesread
stat:timesopened
stat:iotime
stat:mipused
stat:is_duplicate
=> Retrieve additional IC/TS statistics with getattribute & get_image_info()

src/doc/oiiotool.tex, src/doc/openimageio.tex, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h, src/oiiotool/printinfo.cpp, testsuite/oiiotool/ref/out.txt, testsuite/oiiotool/run.py
Very occasionally, you want to do an "open with config" where a configuration ImageSpec is supplied to the ImageInput::open() and contains metadata that gives special instructions (invariably they are format-specific).
It was awkward to do so for images read by oiiotool.
This command lets you set config metadata that will apply to the NEXT image read by referencing its name on the command line (after which the configuration metadata will be cleared).
Example:
oiiotool -iconfig "oiio:UnassociatedAlpha" 1 input.png -o out.exr
=> oiiotool --iconfig NAME VALUE lets you set input configurations.

src/doc/imageioapi.tex, src/doc/pythonbindings.tex, src/iconvert/iconvert.cpp, src/libOpenImageIO/formatspec.cpp, src/oiiotool/oiiotool.cpp
It seems to me that a call to set_format() should really completely overwrite the format, including per-channel information that may have been previously set.
There were a handful of places where we called set_format and specifically wanted to preserve channelformats. In those cases, we just changed it to `format = ...`.
=> Make sure ImageSpec::set_format clears any per-channel formats

src/openexr.imageio/exrinput.cpp
Recent change #1441 ("More robust detection of whether OpenEXR is tiled")
inadvertently used a call that is only available for OpenEXR >= 2.x.
Use the more robust test for OpenEXR 2.x, the old naive one for 1.x.
Fixes #1447
=> Fix EXR tile logic for OpenEXR 1.x

src/include/OpenImageIO/strutil.h, src/include/OpenImageIO/sysutil.h, src/libutil/strutil.cpp, src/libutil/sysutil.cpp
Some minor changes to Strutil & Sysutil that I did a while back but hadn't committed.
* Change declaration of utf_to_unicode from taking a string_view& to a string_view. This was probably just a typo in the original code.
* Strutil::base64_encode -- does what it says.
* Sysutil::getenv -- wraps getenv in a nice string_view wrapper, which means you can directly compare it rather than needing to separately see if a raw getenv call returns NULL before strcmp'ing it.
=> Strutil & Sysutil odds and ends

src/build-scripts/install_homebrew_deps.bash, src/cmake/modules/FindOpenJpeg.cmake, src/jpeg2000.imageio/CMakeLists.txt, src/jpeg2000.imageio/jpeg2000input-v1.cpp, src/jpeg2000.imageio/jpeg2000output-v1.cpp
To avoid making a mess of #ifdef's, I just punted and made copies of the
existing jpeg2000input.cpp and jpeg2000output.cpp for 1.x, and altered
the usual ones for 2.x. Eventually those 1.x ones will go away.
Fixes #957
Fixes #1449 
I had to disable ICC support when writing, when using OpenJpeg 2.x.  It
hits assertions and I can't figure out why. But since as far as I know
very few OIIO users make use of JPEG-2000 and even fewer use it with
OpenJpeg 2.x (I can confidently say ZERO, until now, since it didn't
build against it before), I can't justify any more time tracking down
the problem until somebody runs into it as a practical matter.
=> Add ability to build against OpenJPEG 2.x

src/openexr.imageio/exroutput.cpp
Fixes #1214
Thanks, Thiago, for spotting this, and I'm a real dunce for not only doing
it in the first place, but for so badly misunderstanding the point of your
issue that I let it go unaddressed for months.
=> Fix typo: was getting XResolution metadata when YResolution was intended

src/libOpenImageIO/imageioplugin.cpp
Try/catch in ImageInput::create() and ImageOutput::create() to properly trap if something deep in an ImageInput/ImageOutput constructor throws an unanticipated exception, thereby not crashing but instead just turning it into an ordinary (recoverable) error opening the file.
=> Try/catch in ImageInput::create() and ImageOutput::create()

src/cmake/modules/FindOpenColorIO.cmake
Hello there! This change fixes an issue when we try to find the ocio header with __OCIO_INCLUDE_PATH__ defined (and not __OCIO_PATH__).
Example (with boost, python-2.7 and cmake installed on your system):
```bash
export OCIO_INCLUDE_PATH=/path/to/ocio/include
export OCIO_LIBRARY_PATH=/path/to/ocio/lib
cmake . -DVERBOSE=1
```
Tested with CMake 3.4.3.
=> CMake: fixed how to find ocio header with OCIO_INCLUDE_PATH

src/include/OpenImageIO/simd.h
Got this error while compiling with "Visual Studio 11 2012 Win64":
```
~\src\include\OpenImageIO/simd.h(2318): error C3861: 'roundf': identifier not found [~\build\src\libutil\simd_test.vcxproj]
```
This fixes the build for me but I'm not sure if this is the correct way to fix it.
------
Fixes `~\src\include\OpenImageIO/simd.h(2318): error C3861: 'roundf': identifier not found [~\build\src\libutil\simd_test.vcxproj]`
=> Fix roundf: identifier not found

src/include/OpenImageIO/sysutil.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libutil/sysutil.cpp
There is trouble if the user tries to set ImageCache's "max_open_files" below the limit of open file handles. Clamp it somewhat below that number.
=> Clamp ImageCache max_open_files below the system limit

src/libutil/filesystem.cpp, src/libutil/strutil.cpp
Both `Strutil::utf8_to_utf16` and `Strutil::utf16_to_utf8` had a bug in which the converted string would include the trailing `'\0'`, e.g., `"foo"` (len 3) would become `L"foo\0"` (len 4). This caused an infinite recursion on `Filesystem::searchpath_find` during recursive searches.
Also reduce the implicit conversions in `Filesystem::searchpath_find` happening when calling the helper oiio functions. Instead, keep explicit `boost::filesystem::path` objects for as long as possible and call the `boost::filesystem` methods directly.
=> Fix Filesystem::searchpath_find on Windows

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
* simd::float3 is just like float4, but only loads and stores 3
components.  It's meant to be a Vec3f replacement. It's 4 wide, there
is padding, so that it can use 4-wide SIMD ops.
* simd::matrix44 is a 4x4 matrix, replacement for Imath::M44f. The key
feature is point- and vector-like transformation of float3's.
* Augment float4 (& float3) with x,y,z,w access and set functions, dot
products, safe_div, hdiv, sqrt, rsqrt, normalize.
* In the process, I cleaned up some other very minor things in simd.h,
and also beefed up simd_test.cpp to do more extensive timing tests,
including comparing the speed of many simd ops to the equivalent using
Imath::Vector/Matrix types.
The matrix transformations are interesting: My benchmarks show that a
"native" matrix44 x float3 transformation is twice as …
=> simd.h additions (highlights: float3, matrix44)

src/include/OpenImageIO/simd.h
This doesn't introduce any new functionality, just moves code around within simd.h MASSIVELY. The net effect is to reorganize the header file so that it has the important class and functions declared and documented very cleanly in the first section of the file, and then all the gory details and architecture-specific implementation following that.  This makes it so that users of the simd.h functionality can more easily read the relevant parts of the header to understand the classes, and never need to poke around the ugly implementation.
We could, in the future, move the implementation details to one or more secondary files included from here, perhaps split by class or by architecture.  No need for that now, but this refactor makes it easier. 
It also makes it easier to block-copy-and-paste …
=> Refactor simd.h to separate declarations from implementations.

src/field3d.imageio/field3doutput.cpp, src/libOpenImageIO/deepdata.cpp, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagebuf.cpp, src/libutil/sysutil.cpp, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp
Some should be errors, not assertions.
Others should at least have messages to make them more apparent why
they are asserting.
A few should occur only when compiled in DEBUG mode.
Reminder: assertions are not intended to handle error conditions (and
especially NEVER supposed to be hit because of "bad input"). They are
meant to catch "impossible situations" that indicate an error in program
logic from which no meaningful recovery can be made at runtime.
=> Fix unhelpful ASSERT(0) calls.

src/include/OpenImageIO/sysutil.h, src/libutil/sysutil.cpp
Example-as-documentation:
// Make a Term object that understands whether the intended output
// channel is a live terminal (pass a stream, or a FILE*, or the
// default ctr just assumes ANSI codes are ok).
Sysutil::Term term(std::cout);
// Term.ansi("command") produces the code for the given attribute
// (such as "bold" or "red", and you can combine them with commas),
// IF the term supports ANSI codes, otherwise returns a safe empty
// string.
std::cout << "Normal " << term.ansi("bold") << "bold stuff"
<< term.ansi("default") << "\n";
// Term.ansi ("command", "string") returns the string that turns on
// the attribute, then has the string, then goes back to the default
// appearance.
std::cout << "Normal "
<< term.ansi("bold", "bold") << " "
<< term.ansi("underscore", "underscore") << " …
=> Sysutil additions: Simple terminal output with ANSI text formatting codes.

src/include/OpenImageIO/fmath.h
The sign bit of expm1 could be wrong (due to the "denormals crush" technique we use to speed things up).
Since expm1 is a strictly increasing function passing through 0, we can just force in the sign bit we want from the argument.
=> Make sure the sign bit of expm1 is correct for small arguments

src/include/OpenImageIO/fmath.h
`log1p` is the natural companion to `expm1` and we were missing a fast version of it.
Just like in `expm1`, care is taken to get the sign bit right for small arguments (which simply calling `fast_log(1+x)` gets wrong for roughly 50% of inputs between -1 and 1).
After more careful measurement, I also found I could relax the threshold for small angles in `expm1` without changing the maximum error. This makes it slightly faster.
=> Add an optimized (and sign accurate) version of log1p

src/doc/imagecache.tex, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/testtex/testtex.cpp
The size statistics reported by IC/TS are the *data* size -- that is,
the size of all pixels of the image if they were read into memory, as
represented in the cache (uncompressed, and in one of the data types
supported by the cache).
But this doesn't accurately reflect the size of the images as they exist
on disk. The three main ways they differ are: (a) the image data doesn't
count the size of the headers, metadata, etc; (b) the pixel data on disk
is often compressed, making it much smaller stored on disk than the
in-cache size; (c) the data on disk may be in a format not directly
supported by the cache, and is "expanded" upon being read (for example,
10 bit per channel data would be expanded to 16 bits per channel in
the cache, palette images might be represented by one byte per pixel …
=> ImageCache/TextureSystem: collect stats on total size on disk.

src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp, testsuite/openexr-suite/ref/out.txt, testsuite/openexr-suite/run.py
"Chromaticites" has a custom attribute type to OpenEXR, so need a bit of special handling to get it right.
=> Fix OpenEXR input and output of chromaticities

CHANGES.md, CMakeLists.txt, Makefile, src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
The quick summary is that it adds float8, int8, bool8 classes that are analogous to the 4-way versions. The existing float4, int4, bool4 classes are more or less the way they were before.
So much changed and moved around within simd.h, it's not worth bothering to understand the diff. Read the new file if you care about the details.
They are quite speedy on AVX/AVX2, but fall back on a mixture of SSE (4-wide) and scalar if AVX is not available. Note that the float classes are generally fully performant on AVX, but it takes AVX2 for most of the 8-wide instructions for integers. In many cases, we get pretty close by doing it in 4-way chunks rather than falling back to fully scalar. If there are particular methods that need to be faster on AVX 1.0 (or SSE), I'm happy to give them a closer …
=> Massive overhaul of simd.h leading to full support of AVX and AVX2.

src/include/OpenImageIO/simd.h
=> simd.h needs cstring header to get declaration of memcmp

src/oiiotool/oiiotool.cpp
Oiiotool took care to remember the data format of the first input file
it reads, and proagate that to the outputs (if not explicitly set by
-d).  And the -d could handle specifying per-channel data types. But we
didn't handle the case of remembering per-channel data types from the
input and propagating to the output.
Example:
oiiotool -create 64x64 3 -d R=half,G=float,B=half -o test.exr
properly makes a half/float/half mixed file. But then subsequently,
oiiotool test.exr -o out.exr
lost that info, saving it entirely as float/float/float.
With this patch, this works properly, and out.exr will correcly end up
as half/float/half.
I believe this fixes #1445
=> oiiotool: make sure to propagate channel formats of input to output

src/doc/builtinplugins.tex, src/raw.imageio/rawinput.cpp
Per discussion on oiio-dev, the consensus seems to be:
* Turn off auto-bright adjustment
* turn on camera whie balance
* set maximum thresholding to 0
Add "config" overrides for all of these, for anybody who doesn't like
the default.
Also, document these, and the other existing-but-undocumented configuration
settings.
=> RAW reader: turn off some auto-adjustments

src/python/py_imagebuf.cpp
It was pointed out in oiio-dev that these routines didn't seem to know their arg names or default for named-parameter passing.
=> Make Python bindings of ImageBuf::reset() know the arg names & defaults.

CHANGES.md, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/oiiotool/oiiotool.cpp, testsuite/oiiotool-subimage/run.py
This causes all images on the stack to be output (not just the top), using
the filename pattern (assumed to have an integer substitution '%d'). The
number substituted will be index of the image (starting with the bottom
of the stack, beginning with number n).
Example of how this is useful:
oiiotool multiimage.tif -sisplit -o:all=1 subimage%04d.tif
Splits multiimage.tif into individual subimages and saves them all
as separate images with names subimage0001.tif, subimage0002.tif, etc.
=> oiiotool: new -o option: -o:all=n <pattern>

src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
--attrib, --iscolorspace, --keyword, --caption, --orientation, and maybe
some other attribute-setting commands, confusingly applied only to the
first subimage of a multi-subimage file. Now by default they will apply
to all the subimages, which almost certainly is what people probably
expect.
=> oiiotool: slight refactoring of attribute setting internals

CHANGES.md, src/doc/builtinplugins.tex, src/openexr.imageio/exroutput.cpp
For example, oiiotool in.exr -compression dwaa:200 -o out.exr
This is more convenient than separately needing to set the
"openexr:dwaCompressionLevel" metadata.
This came from discussion on a thread on oiio-dev mail list.
=> OpenEXR: allow dwaaCompressionLevel to be appended to compression name.

CMakeLists.txt, src/libOpenImageIO/imagebufalgo_copy.cpp, testsuite/dup-channels/ref/out.txt, testsuite/dup-channels/run.py, testsuite/runtest.py
For OpenEXR, channel names are not merely informational -- channel names *must* be unique within an image part, or else the ones with duplicate names will be dropped silently when the file is outout.
IBA::channel_append (and therefore `oiiotool --chappend`) tried to protect against that by renaming duplicate channels "channelN". (As would happen if you chappend'ed two images that each were R,G,B.)
There's a special case to consider: taking a multi-subimage (or multi-part, in EXR lingo) and turning into a many-channel image. Like you'd do with this command:
oiiotool manyparts.exr -sisplit -chappend -o manychannels.exr
Having channels named R, G, B, channel3, channel4, ... isn't the best we can do.
This patch modifies the renaming of duplicate channel names within channel_append so that if …
=> Smarter channel_append channel renaming: use subimage name if available

src/libtexture/imagecache.cpp
In general, ImageCache::get_image_info (or the TextureSystem equivalent, get_texture_info) fails for UDIM texture patterns, for all but the "UDIM" query (which means, "is this a UDIM file").
This is because the UDIM name is a pattern, not a concrete file. The specific file is not resolved until the texture() call itself, because the actual filename will depend on the st coordinates being looked up. The get_texture_info query is not for a particular coordinate.
But let's say that you are writing a shader and want different behavior or code paths depending on properties of the file, such as the number of channels. Those queries would fail.
So the purpose of this patch is to make the "channels" query to succeed. It will find the first file to match the pattern (the 0,0 corner may not exist …
=> UDIM get_image_info query for "channels" should succeed.

src/include/OpenImageIO/simd.h
=> simd.h: add missing int8 functions

src/include/OpenImageIO/simd.h
=> Fix gcc warning about casting for AVX2

src/ffmpeg.imageio/ffmpeginput.cpp
This PR adds support for the new ffmpeg API using `avcodec_send_packet` and `avcodec_receive_frame` instead of `avcodec_decode_video2`. #1465 
I've tested the changes briefly, but haven't made any deeper testing.
=> ffmpeg: Added support for new API introduced with ffmpeg 3.1

src/libtexture/imagecache.cpp
Forgot to recheck for broken file after changing UDIM name pattern into
a concrete file. A better solution is to fully recurse (just one level)
to perform all the initial checks on the concrete file.
=> Fix bug in recently modified UDIM code

src/doc/imageioapi.tex, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagespec_test.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h, src/oiiotool/printinfo.cpp
Airplane project from last weekend. This is for you, @danwexler 
* ImageSpec::to_xml() improvement: output contents of extra_attrib.
* ImageSpec::serialize() serializes the spec, as text or xml. Leaves
room for other formats in the future. (JSON? YAML?)
* 'oiiotool -info:format=xml' prints metadata as xml
A bunch of refactoring to support this.
=> Overhaul of metadata printing.

src/libOpenImageIO/maketexture.cpp
maketx (and IBA::make_texture underneath) writes its results to a temporary file to avoid overwriting an existing file and leaving an invalid file there if the command should be terminated before it's done. After it's done being written, the temp file is "moved" to the final destination, replacing it atomically.
But as Ramon points out, if multiple processes are running on the same shared disk partition and might try to maketx the same texture at the same time, they could clobber each other by both writing to identically named temp files. So the solution is to ask the OS to make a unique name for that temporary file, using Filesystem::unique_path().
=> Make temporary texture filename unique to avoid classes on shared drives

CMakeLists.txt
This ensures that the local include directories are considered before
any system directories, which avoids confusion if there are conflicting
versions of OIIO installed elsewhere.
Fixes #1522
=> Fix include order at the suggestion of Rob Pieke.

src/libutil/sysutil.cpp
Windows 10 supports VT100 escape sequences since the Anniversary Edition. Except for the define, this patch uses APIs that have been present for quite some time, so it should fail gracefully on older versions of Windows
Test  with simd_test. It looks much better !
------
=> Add ANSI terminal support to Windows platform

src/cmake/modules/FindOpenColorIO.cmake
Fixes the search for the OpenColorIO headers by removing the trailing `OpenColorIO` subdirectory from the `OCIO_INCLUDES` result, since the includes in `color_ocio.cpp` are already qualified.
Confirmed working on RB-1.6.
=> FindOpenColorIO.cmake: Fix for location of OCIO headers

src/doc/CMakeLists.txt, src/iv/CMakeLists.txt
On Unix systems if txt2man is found, we automatically build man pages from our command-line binaries. It was smart enough to skip doing so for iv if USE_QT was 0 (that is, if the build was set up to purposely exclude anything using QT). But if USE_QT was not set to 0 but iv was skipped anyway (perhaps Qt or other iv-specific dependencies weren't found at build time), it would fail in trying to make the man page for iv, since the iv program itself could not be executed.
This logic fix instead predicates it on whether iv actually got built, regardless of whether its failure to build was due to explicitly skipping it, dependencies not found, or whatever.
Fixes #1509 (I think)
=> Be more careful about building iv man page

src/libtexture/imagecache.cpp
Logic was botched, it was still getting errors if the first file was not
present. Needed to verify the file and check that it wasn't broken,
because only in verify is it actually opened. Just checking for a
non-NULL result from resolve_udim() isn't enough.
=> Fix for UDIM channels query

CHANGES.md, src/cmake/externalpackages.cmake, src/include/OpenImageIO/thread.h, src/libtexture/imagecache_pvt.h, src/libutil/filesystem.cpp
VFX platform dictates 1.55, but I think we can be more flexible, as there is nothing we use that was introduced between 1.50 and 1.55. But by definitively excluding 1.4x, we can clean up some conditional compilation guards. In filesystem.cpp in particular, we no longer have to worry about boost::filesystem prior to v3 (which is the one that will form the basis of C++17 filesystem).
=> Bring boost floor to 1.50

src/libtexture/texturesys.cpp
For some reason, certain 32 bit platforms have gcc errors about this spot leading to uninitialized variables (they don't! but gcc can't seem to figure that out). The 64 bit platforms figure it out just fine, so just eat the cost of a couple useless assigns on the platforms where it's a problem.
=> Fix warnings on some 32 bit platforms

src/iv/imageviewer.cpp, src/iv/imageviewer.h, src/iv/ivgl.cpp, src/iv/ivgl.h, src/iv/ivinfowin.cpp, src/iv/ivmain.cpp, src/iv/ivpref.cpp
* strip directories from #includes of Qt headers.
* Reorder OpenGL-related headers.
This is preliminary work towards eventual migration to Qt5.
The original header locations are incompatible with Qt5, but if we
eliminate the directories, they will mostly work for both Qt4 and Qt5.
=> Qt migration WIP

site/spi/Makefile-bits-arnold, site/spi/Makefile-bits-spcomp2
* Change default to use clang 3.5 rather than 3.4.
* More flexibility for overriding which compiler version.
* Some refactoring to regularize the Arnold vs SpComp2 builds, and also
between the OIIO and OSL cmake files.
This doesn't affect non-SPI sites.
=> SPI - Options to run other compilers

src/doc/imagebufalgo.tex, src/doc/oiiotool.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/color.h, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/color_ocio.cpp, src/oiiotool/oiiotool.cpp, src/python/py_imagebufalgo.cpp
Extend ColorConfig::createLookTransform & createDisplayTransform to
accept mutiple key/value pair, by allowing their context_key and
context_value paramters to each be comma-separated lists (which
obviously must both contain the same number of items).
=> Allow multiple key/value pairs in OCIO wrappers.

src/tiff.imageio/tiffinput.cpp, testsuite/misnamed-file/ref/out.txt, testsuite/tiff-suite/ref/out-alt.txt, testsuite/tiff-suite/ref/out.txt
Many RAW files are really structured like TIFF underneath, and we
forcefully open them as a TIFF file to read their metadata, which is not
read as well by libraw. OK, but they also contain some of these oddball
tags, and that could lead to crashes. This patch makes it more robust to
some of these odd cases.
=> Fix to TIFF handling of certain unusual tags, which also affected raw files

src/include/OpenImageIO/fmath.h, src/libOpenImageIO/imagebuf.cpp, src/libutil/fmath_test.cpp
Caused me to also modify the template to clamp to prevent a cascade of type errors.
=> templatize round_to_multiple so it works with other types (like size_t)

src/iff.imageio/iff_pvt.cpp, src/iff.imageio/iff_pvt.h, src/iff.imageio/iffoutput.cpp, testsuite/iff/ref/out.txt, testsuite/iff/run.py, testsuite/oiiotool-spi/ref/out.txt, testsuite/oiiotool-spi/run.py, testsuite/runtest.py
The main thing is that the writer dropped the "Artist" and "Date" metadata.
The reader would read them, but botched the padding slightly and could
end up with extra spaces at the end of the fields.
Fixes #1546
=> IFF fixes: didn't write metadata, didn't read properly, some cleanup, tests

src/libOpenImageIO/color_ocio.cpp
Well, sometimes you (and by "you" I mean some script you wrote) ask
oiiotool to do a 'colortransform sRGB sRGB' or some other color
transform that is just identity. Fine. But if $OCIO environment variable
is not defined so no OCIO config is found, that was an error!
Simple fix -- detect that case and return a do-nothing color processor.
=> Fix errors when doing identify transform when no OCIO is present.

src/include/OpenImageIO/atomic.h, src/include/OpenImageIO/thread.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h
=> atomic.h: Use std::atomic for C++11 (and related cleanup)

CHANGES.md, src/cmake/externalpackages.cmake, src/doc/oiiointro.tex, src/include/OpenImageIO/parallel.h, src/include/OpenImageIO/thread.h, src/libOpenImageIO/CMakeLists.txt, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageio_pvt.h.in, src/libutil/CMakeLists.txt, src/libutil/parallel_test.cpp, src/libutil/spin_rw_test.cpp, src/libutil/spinlock_test.cpp, src/libutil/thread.cpp, src/libutil/thread_test.cpp
* Bring thread_group into modern C++11 era: use std components, no more
boost dependency, use variadic templates for a better create_thread
signature. Also remove the last vestigages of using boost::thread_group
instead of ours.
* Modernize spin_mutex to use C++11 std::atomic_flag instead of doing
everything with bespoke code.
* thread_pool : persistent threads feeding from a task queue. This is
generally a better way forward than explicitly spawning new threads
with thread_group every time you want to do things in parallel.
* task_set : Because the thread_pool is asynchronous (fire and forget,
or fire and get future's back), a simple task_set object lets you collect
a set of related asynchronous tasks and wait for them to all have been
completed before proceeding.
* parallel_for : …
=> thread.h: modernize, thread_pool, parallel_for

src/include/OpenImageIO/parallel.h, src/include/OpenImageIO/thread.h, src/libutil/parallel_test.cpp, src/libutil/thread.cpp, src/libutil/thread_test.cpp
I discovered that the thread_pool could deadlock if the pool queue
filled and then the subtasks themselves added further subtasks to
the queue and waited for their results (since those subtasks would
never themselves get around to executing, with all the pool threads
waiting).
The solution is primarily to modify task_set::wait() so that instead
of unconditionally blocking for the subtasks to complete, it polls
them without blocking, and so when it finds itself waiting for queue
results to still complete, it steals some work from the queue to do
itself. This unclogs the system nicely.
I also modified parallel_for_chunked (which is the basis for the
unchunked parallel_for as well) so that the calling thread itself
executes the last (or only) subtask rather than send it to the pool.
This is …
=> Fix threadpool

src/include/OpenImageIO/fmath.h
The lerp(y[seg], y[seg+1], x), if on the very last segment and x ==
1.0f, was possible to read past the end of y into uninitialized memory.
Even though it would weight that value by 0, if it happened to contain a
NaN, NaN*0 == NaN, and it was also possible to read past the end of
usable memory. So it is safer to use an appropriate clamp to be super
sure we never read past the end of y.
=> fmath: Avoid edge case bug in interpolate_linear

CMakeLists.txt, src/idiff/idiff.cpp, src/oiiotool/diff.cpp, src/oiiotool/oiiotool.cpp, testsuite/diff/ref/out.txt, testsuite/diff/run.py
* Print more info about mismatch in idiff and oiiotool --diff. In
addition to the pixel coordintes and difference of the biggest
difference, print the full values of all channels at that pixel
for both images.
* testsuite test for idiff and oiiotool --diff
* Don't have oiiotool print the warning about no output for --diff, when
the console output is all that's wanted.
=> idiff and oiiotool --diff enhancements

src/include/OpenImageIO/parallel.h, src/libutil/thread.cpp
Also avoid sizing thread to 0 by default (it better be on purpose).
This is an edge case I don't expect to see much in the real world, but
it was really messing with our Travis-CI builds, which seem to run on
VMs that think they have only one core allocated. This would initialize
the pool to 0 size, which could lead to a math exception, ugh.
=> parallel_for_chunked: avoid divide by 0 when pool size is 0

src/libtexture/imagecache.cpp
Hey, I don't have CLA, but hopefully it's not necessary for a trivial bugfix ( Maybe I should have just made an issue, but I wasn't sure what the issue was until tracking down the code. )
It looks like these return statements were just missed for displaywindow and datawindow - the if statements for every other dataname return true if there is a match.
I noticed this while using OSL, where the symptom is that a call like "r = gettextureinfo (filename, "datawindow", datawin);" will fill out the datawindow correctly, but will incorrectly set r to 0.
The corresponding test case in OSL checks the return values for other gettextureinfo calls, but does not check the return value for displaywindow and datawindow:
https://github.com/imageworks/OpenShadingLanguage/blob/master/testsuite/gettextureinf …
=> Fix imagecache handling of "displaywindow" and "datawindow"

src/libOpenImageIO/exif.cpp
(Fix discovered by J Robert Ray)
When using gcc 4.8 on centos7, with debug compile, in a certain app, we get core dumps involving SIGSEGV in __memcmp_sse4_1 deep inside operator[](std::string&&).
We don't understand it, and in fact suspect a compiler bug. Can't reproduce on other platforms or compiler releases. Sweep it under the rug with this patch, that seems to work around it, though we admit we don't know why.
=> Fix seg fault at initalization in debug mode

src/include/OpenImageIO/dassert.h, src/include/OpenImageIO/strutil.h, src/include/OpenImageIO/ustring.h, src/libOpenImageIO/formatspec.cpp, src/libutil/CMakeLists.txt, src/libutil/strutil.cpp, src/libutil/strutil_test.cpp
They are like std printf/fprintf, except with all the typesafe goodness of Strutil::format (a.k.a. Tinyformat), and also I rigged them to internally use a mutex to prevent simultaneous threads from clobbering each other's console or file output. The full contents of printf's from different threads may end up interleaved non-deterministically, but each print individually will be "atomic" and not get mixed up character-by-character with those of other threads.
These are so much easier now that we are C++11 and can rely on variadic templates.
=> Add Strutil::printf and fprintf.

.travis.yml, src/cmake/oiio_macros.cmake, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageioplugin.cpp, src/openexr.imageio/exroutput.cpp, testsuite/runtest.py
Rolling up several things I did while debugging something recently:
1. debugmsg tweaks
* Rename debugmsg -> debug
* Use variadic templates
* Use Strutil::fprintf underneath, to guarantee threads not clobbering each other.
* Use OPENIMAGEIO_DEBUG_FILE to let you redirect it to a file.
2.   Debugging and testsuite improvements:
* For failed tests, print full test output, and debug.log, if it exists. 
* Reduce unnecessary travis verbosity
* testsuite cmake tweak: allow optional decouple of test name from dir name       This makes it possible, for debugging purposes, to make a test dir run       several times as separate tests. Why? Maybe you have a spurious       nondeterministic error you are tracking down and want your travis runs       to have a higher chance of triggering it, so you run …
=> Debugging improvements

src/cmake/modules/FindOpenJpeg.cmake
Tweak OpenJPEG include file search rules to prefer newer versions when multiple are installed on the system.
=> Tweak OpenJPEG include file search rules to prefer newer versions

src/libOpenImageIO/imageio.cpp
29766348b27a2030820147561ef47cf44835c595 never actually worked, because the -1 value was getting clamped.
=> Fix exr_threads value -1 to disable thread pools not working.

src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
Helpful for debugging which oiiotool operations take the time or cause memory use to expand.
=> oiiotool: -debug now prints total time / mem after each op.

src/include/OpenImageIO/imageio.h, src/jpeg.imageio/jpeginput.cpp, src/libOpenImageIO/exif.cpp, src/psd.imageio/psdinput.cpp
Use string_buf to patrol the buffer size.
Fixes #1576
=> Be more reslient to malformed Exif data blocks with bogus offsets.

src/include/OpenImageIO/imagebufalgo_util.h, src/include/OpenImageIO/parallel.h, src/include/OpenImageIO/thread.h, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/compute_test.cpp, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/imagebufalgo_compare.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp, src/libOpenImageIO/imagebufalgo_draw.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/libOpenImageIO/imagebufalgo_test.cpp, src/libOpenImageIO/imagebufalgo_xform.cpp, src/libOpenImageIO/imagebufalgo_yee.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/maketexture.cpp, src/libutil/fmath_test.cpp, src/libutil/parallel_test.cpp, src/libutil/thread.cpp, src/testtex/testtex.cpp
It took me a long time of working on this as a background task, but it's finally in good shape. This is a continuation of the thread pool & parallel loop work I merged a few weeks ago.
------
2D parallelism loops:
* Add parallel_for_2D varieties for easy thread_pool parallelization over 2D domains.
* Refactor ImageBufAlgo::parallel_image:
- Use thread pool rather than spawning new threads.
- Options struct includes max number of threads to use, domain subdivision hints, minimum number of pixels per thread task, and custom pool. Users should almost never need to adjust any of these.
* Refactor all the places using parallel_image to use the new style, and to use lambdas in a pleasing way rather than the prior idiom of recursing and handling the 1-thread and many-thread cases separately.
* …
=> Improvements to thread_pool and 2D parallelism

INSTALL.md
This commit fix the link to Windows build instruction in INSTALL.md The correct link is https://sites.google.com/site/openimageio/building-oiio-on-windows
=> Add correct link for Windows build instructions

src/include/OpenImageIO/imagebufalgo_util.h
Visual Studio Professional 2015 can't properly deduce template type for a std::max. This patch directly specify the type in the std::max call.
=> [Windows] Fix std::max error in imagebufalgo_util.h

src/libtexture/texturesys.cpp
Same as the fix we had for certain 32 bit 386 platforms.
=> Fix compiler warning on Fedora aarch64

src/doc/oiiotool.tex, src/doc/openimageio.tex, src/iv/ivmain.cpp, src/libOpenImageIO/maketexture.cpp, src/oiiotool/oiiotool.cpp, testsuite/maketx/ref/out-alt-tiff4-2.txt, testsuite/maketx/ref/out-alt-tiff4.txt, testsuite/maketx/ref/out.txt, testsuite/maketx/run.py, testsuite/oiiotool-maketx/ref/out.txt, testsuite/oiiotool-maketx/run.py, testsuite/runtest.py
The results when comparing "maketx --hicomp" versus without that flag
were especially hilarious when using 'iv' to view the images -- for high
resolution images, it will fall back on ImageCache, which thinks two
images with the same hash are identical and don't need to be redundantly
read from disk. So, the hicomp and nohicomp images looked identical in
iv, leading to even more confusion.
So, also turn off the ImageCache de-duplication for iv so we don't
get bitten by this again. I don't think there is a legit case where we
rely on deduplication for iv, so this seems like the safe choice.
=> maketx did not incorporate "highlight compensation" into the hash!

src/doc/pythonbindings.tex, src/python/py_imagebufalgo.cpp, testsuite/python-imagebufalgo/ref/out-alt.txt, testsuite/python-imagebufalgo/run.py, testsuite/python-imagebufalgo/src/test_imagebufalgo.py
Oops, noticed recently that the Python binding for this function was never implemented.
=> Fix unimplemented Python ImageBufAlgo.computePixelStats

src/include/OpenImageIO/imageio.h
Declaration of declare_imageio_format currently doesn't match it's definition.
=> Fix declare_imageio_format declaration.

src/cmake/compiler.cmake, src/cmake/install.cmake
Don't set CMAKE_INSTALL_RPATH to be LIB_INSTALL_DIR until **AFTER**
we have set the value of LIB_INSTALL_DIR.
The order got flipped around as a result of the refactor.
=> Fix bug in recent cmake refactor

src/oiiotool/oiiotool.cpp
action_crop function in oiiotool wasn't working working with multiple subimages as ot.allsubimages wasn't taken into account.
To fix that I just convert ot.allsubimages into a string (so the boolean will give "0" or "1") and options["allsubimages"] becomes valid to use.
I could also have use directly ot.allsubimages directly, as it is into the other functions, but it feels that this change is the one that less touch the logic of the function.
=> oiiotool.cpp: fix action_crop to actually take into account the allsubimages option

src/oiiotool/oiiotool.cpp, testsuite/oiiotool-readerror/ref/out.err-alt.txt, testsuite/oiiotool-readerror/ref/out.err-alt2.txt, testsuite/oiiotool-readerror/ref/out.err-debug.txt, testsuite/oiiotool-readerror/ref/out.err.txt
It's common to call oiiotool from a script, which may assemble the
command line programmatically. If it botches this and ends up with a
mangled command line, it really helps in debugging the script if its
author can see exactly what oiiotool got as a command (essentially,
as part of the original error message).
=> For error conditions, print the full command line.

src/include/OpenImageIO/fmath.h, src/libutil/fmath_test.cpp
Remember that floating point comparisons involving NaN always return
false. This rearrangement guarantees that clamp(x,lo,hi) always returns
a value in [lo,hi], even if x is NaN. (Specifically, it returns lo.)
=> fmath: slight reformulation of clamp() to ensure NaN safety

.travis.yml, site/spi/Makefile-bits-arnold, src/dicom.imageio/dicominput.cpp
Because there are rumblings that VFXPlatform for CY2018 will probably upgrade the C++ requirements to gcc 5.x, add a gcc5 test to the Travis build matrix, fix a compiler warning that popped up. We want to make sure we are not introducing anything that will give us a headache next year.
Also add gcc 4.9,because we've recently discovered that gcc 4.8 doesn't have full support for C++11 (lacks proper std::regex), so maybe people will try using it, so we want it to work.
Finally, modify the Travis matrix (now that we have several distinct gcc versions) so that loads packages per-matrix-entry rather than for all, so each matrix test is only downloading and installing the gcc packages for the specific version it wants to run. Trims a little fat off the CI build times.
=> Bring gcc5 and gcc4.9 back into the Travis build

src/libOpenImageIO/imagebuf.cpp
And worse, it had a bit of a const/non-const mismatch I had to patch up.
This is going to need a backport to release branch as well.
Thanks to Alex Wells for spotting this!
=> Oops, didn't pass value properly to ImageBuf::threads()

CMakeLists.txt, src/include/OpenImageIO/argparse.h, src/include/OpenImageIO/imagebuf.h, src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/strutil.h, src/include/OpenImageIO/tinyformat.h, src/include/OpenImageIO/ustring.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageio_pvt.h.in, src/libtexture/imagecache_pvt.h, src/libtexture/texture_pvt.h, src/libutil/strutil_test.cpp, src/oiiotool/oiiotool.h
* Found a bug in Srutil::format that was introduced recently when we
switched it to use variadic templates -- when passed just a single bare
string (with no arguments to format), it wasn't doing correct conversion
of %% to %, as it should to match printf-like behavior.
* Convert all the other places that used TINYFORMAT_WRAP_FORAMT into
much more straightforward use of variadic templates, now that we are
C++11 minimum.
=> Cleanup of Strutil::format and similar functions.

site/spi/Makefile-bits-arnold, src/cmake/compiler.cmake, src/cmake/externalpackages.cmake, src/igrep/igrep.cpp, src/iinfo/iinfo.cpp, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/maketexture.cpp, src/libOpenImageIO/xmp.cpp, src/libutil/filesystem.cpp, src/oiiotool/imagerec.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/printinfo.cpp, src/tiff.imageio/tiffinput.cpp
On the currently supported compilers, we believe the only time we need to fall back to boost::regex is for g++ 4.8.x. The rest of the time, we can rely on C++11 std::regex.
=> Use std::regex any time it is available.

src/tiff.imageio/tiffinput.cpp
Obvious cut and paste error. Spotted by Frédéric Devernay.
Fixes #1624
=> Fix typo that prevented reading of all possible Exif tags in TIFF files.

src/libOpenImageIO/exif.cpp, src/libOpenImageIO/xmp.cpp
OK, this is subtle. When decoding XMP, I originally thought that it wouldn't include Exif data, but sometimes it does. But the XML is just string data.  So this patch will look up the name to see if it's a known Exif field, and if so, use the type we know it ought to be to correctly decode from a string.
Also in exif.cpp, changed the implementation of the tag map used by exif_tag_lookup so that it's case insensitive (because, ugh, some raw images have their Exif data in XMP as "exif" rather than "Exif").
The bottom line is that these changes improve proper recognition of certain metadata when reading RAW files.
=> Improvement to decoding metadata from files with XMP blocks

src/doc/builtinplugins.tex, src/doc/openimageio.tex, src/raw.imageio/rawinput.cpp
Fixes #1628
1. The default value for missing "raw:use_camera_matrix" attribute should have been 1, not 0, in order to match the default behavior of libraw/dcraw.
2. The demosicing control logic wanted to erase the "raw:Exposure" attribute, but incorrectly specified the search to be constrainted to a string attribute (thereby failing to erase the attribute which is actually a float). The simple solution is that those erase_attribute calls really don't need to constrain the type at all.
3. Add support for newer (as of LibRaw 0.16) demosaic algorithms "DMT" (mode 11) and "AAHD" (mode 12). Also allow the demosaic algorithm names to be case insensitive.
4. Rename "Modified AHD" to "AHD-Mod", to simplify the name and match libraw terminology.
=> Minor bug fixes in raw file input.

src/oiiotool/oiiotool.cpp, src/raw.imageio/rawinput.cpp
The "raw" reader by default will convert its input to sRGB color space, but allows you to request that it be converted upon read to other color space (or not alter the values) by setting the "configuration" option "raw:ColorSpace" to the name of the color space you want.
This patch adds "ACES" to the list of color spaces it understands,  at least for the versions of libraw that support it (version 0.18 and newer, it seems). In cases where it's not supported, you'll get an error message like this:
$ oiiotool -iconfig raw:ColorSpace "ACES" ~/Downloads/L1004220.DNG  -o out.jpg
oiiotool ERROR: read : raw:ColorSpace value of "ACES" is not supported by libRaw 0.17.2
While I was in there, I changed the color space names it recognizes to be case-insensitive.
Also, in order to test that the error …
=> RAW: Support RAW input to ACES color space.

src/doc/oiiotool.tex, src/doc/openimageio.tex, src/oiiotool/oiiotool.cpp
This adds an --echo MESSAGE command to oiiotool, which will print the
message to the console at that point the left-to-right evaluation of
command line arguments.
For example:
oiiotool test.tif --resize 256x0 --echo "result is {TOP.width}x{TOP.height}"
This will resize the input to be 256 pixels wide and automatically size
it vertically to preserve the original aspect ratio, and then print
a message to the console revealing the resolution of the resulting image.
=> oiiotool --echo

src/libOpenImageIO/formatspec.cpp, testsuite/jpeg2000/ref/out.txt, testsuite/psd/ref/out-alt.txt, testsuite/psd/ref/out.txt, testsuite/targa-tgautils/ref/out.txt
In various contexts (such as oiiotool -v -info) when printing metadata that consists of an arbitrarily long array of values, it will print the first several values and then "..." to avoid going haywire if there are 100000 values, say.
But, hmmm, in such a case you just might want to know how many values there are and their type. So now instead of
Foobar: 0, 0, 0, 0, 0, 0, 0, 0, ...
it will more helpfully say
Foobar: 0, 0, 0, 0, 0, 0, 0, 0, ... [557168 x uint8]
And then you know who you can yell at about what.
=> Improvement to printing of long metadata

src/libOpenImageIO/exif.cpp
This is an attempt to solve #1635. This avoids the crash by ignoring
any directory entry which is outside of the parsing buffer (that would
be really weird if there is a legit memory pointer to an outside memory
block).
There are much more places where there is potential crash is burried
in here, but those i don't feel like going into.
For such things it's really good idea to trust no input data and verify
it, otherwise it's really easy to run into crashes and even possibly
security issues.
Maybe it's also not a bad idea to add an option tyo ignore exif headers
reading for the applications which doesn't need exif.
Unfortunately, can't run testsuite, all the tests are failing on some
`os.symlink` stuff. Why would tests mock around with file system anyway?
=> Add some extra checks to exif parser to avoid memory access issues

CMakeLists.txt, src/doc/imageioapi.tex, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/paramlist.h, src/libOpenImageIO/formatspec.cpp, src/oiiotool/oiiotool.cpp, testsuite/oiiotool-attribs/ref/out.txt, testsuite/oiiotool-attribs/run.py
Extend ImageSpec::erase_attribute so that the name of the attribute to
erase is a regex, and any matching attributes will be erased.
Add oiiotool --eraseattrib, taking an argument with regex pattern,
and it will strip any matching metadata from the top image.
Example uses:
oiiooool in.jpg --eraseattrib smpte:TimeCode -o no_timecode.jpg
oiiotool in.jpg --eraseattrib "GPS:.*" -o no_gps_metadata.jpg
oiiotool in.jpg --eraseattrib ".*" -o no_metadata_at_all.jpg
=> oiiotool --eraseattrib [regex]

src/cmake/compiler.cmake
1. Wasn't setting the C++ standard flags properly for the test, so it failed
on some platforms and didn't use std::regex when it could.
2. Revised test -- the prior C++ did not properly discriminate between
what was implemented vs unimplemented on the broken gcc 4.8 (at least
some subsets of regex_match work, but regex_replace does not, until
it was all fully implemented in gcc 4.9).
=> Fix test for ability to use std::regex

src/doc/builtinplugins.tex, src/doc/openimageio.tex, src/jpeg.imageio/jpegoutput.cpp
JFIF files, as you know, only support 1 or 3 channels (grayscale and RGB, respectively).
Previously, we accepted the special case of 4 channel output (presumably RGBA) by silently dropping the last channel (A, not representable in JFIF files), but for any other channel count (2, or >= 5) would just allow open() to fail.
With this patch, we make the JPEG writer even more forgiving. For nchannels > 3, we truncate to just the first three channels, and for 2 channels, we truncate to just the first channel (outputting grayscale).
The reason why we want this extra flexibility is that JPEG is such a common format for "proxies", "thumbnails", and other kinds of embedded or web-facing images, where we might want to just quickly generate such a proxy for arbitrary images without wanting to think …
=> JPEG: auto conform to supported channel count.

src/include/OpenImageIO/strutil.h, src/libutil/strutil.cpp, src/libutil/strutil_test.cpp
Utility to return whether the identifier at the head of a string matches
a pattern, and advance the pointer only if it does.
=> Strutil::parse_identifier_if

src/doc/oiiotool.tex, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
On oiiotool command line {expressions}, FRAME_NUMBER is replaced based
on the numeric wildcard iteration, and FRAME_NUMBER_PAD is the same
value but as a string that appears zero padded to the number of digits
specificed by --framepadding.
So, for example, to burn in frame numbers to every image in a sequence:
oiiotool -framepadding 4 -frames 1-100 in.#.exr \
-text:x=50:y={TOP.height-50} "Frame {FRAME_NUMBER_PAD}" \
-o out.#.exr
=> oiiotool: expressions recognize FRAME_NUMBER and FRAME_NUMBER_PAD

Makefile, src/cmake/compiler.cmake, src/ffmpeg.imageio/ffmpeginput.cpp, src/fits.imageio/fitsinput.cpp, src/hdr.imageio/rgbe.cpp, src/include/OpenImageIO/pugixml.cpp, src/libOpenImageIO/exif.cpp, src/libtexture/environment.cpp, src/libtexture/texture3d.cpp, src/libtexture/texturesys.cpp, src/libutil/hashes.cpp, src/libutil/xxhash.cpp, src/oiiotool/oiiotool.cpp, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp, src/png.imageio/pngoutput.cpp, src/psd.imageio/psdinput.cpp, src/raw.imageio/rawinput.cpp
clang-tidy is part of the llvm/clang suite of tools. It a fancy linter, with deep ties into the clang AST, providing has a whole bunch of static code analysis tools and stylistic checks.
Turns out that cmake is pretty clang-tidy aware, so just by setting a cmake variable (CMAKE_CXX_CLANG_TIDY) to the clang-tidy command line args you want, cmake will run clang-tidy on every .cpp file that it would compile in the course of the build.
This PR adds new build flags to control this: CLANG_TIDY, CLANG_TIDY_CHECKS, CLANG_TIDY_ARGS, CLANG_TIDY_FIX
All off by default, but allows really easy use of clang-tidy while building.
For example,
make CLANG_TIDY=1 CLANG_TIDY_CHECKS="-*,modernize-*"
or if you are really adventurous
make CLANG_TIDY=1 CLANG_TIDY_CHECKS="-*,modernize-*" CLANG_TIDY_FIX=1
And then …
=> First stab at using clang-tidy

Makefile, src/cmake/compiler.cmake
The first review of clang-tidy support neglected to use the --header-filter=
command, thus excluding headers from analysys.
Also, when tidying headers, if you use -fix, it's very important to
ensure that only one module is compiled at a time, or two processes
might try to modify a header at the same time, garbling it.
=> clang-tidy fixes: include headers in analysys

CMakeLists.txt, src/cineon.imageio/libcineon/CineonHeader.h, src/cmake/compiler.cmake, src/gif.imageio/gif.h, src/hdr.imageio/rgbe.h, src/include/OpenImageIO/SHA1.h, src/include/OpenImageIO/filesystem.h, src/include/OpenImageIO/image_view.h, src/include/OpenImageIO/platform.h, src/include/OpenImageIO/pugixml.hpp, src/include/OpenImageIO/sysutil.h
Be even more thorough with our header name filer -- now get all the "_pvt.h" files, as well as anything with the short and lower case project name in the filename. 
And this finds a handful of additional old headers.
=> More deprecated header fixes

src/libtexture/imagecache.cpp
At the end of the IC/TS stats, there's a list of "broken" files, and what printed there were those files which were either `broken() || !validspec()`.
Two circumstances lead to the spec being not valid, without it being also broken:
(1) Calls to invalidate() mark the spec as invalid, of course! But just because the app invalidated the file (perhaps because it thought the file might be subsequently updated on disk and wanted a fresh look at
it) doesn't mean the file was ever broken.
(2) When the app requests an ImageCacheFile handle up front (as OSL does) but then never opens the file. That also doesn't mean it was broken. You just never read from it.
For both of these circumstances, it's misleading to list the file among those that are known to be broken (presumed corrupted or missing).
=> ImageCache stats: don't print files as "broken" if they aren't

src/include/OpenImageIO/strutil.h, src/libutil/strutil.cpp
Same interface, just pass a std::ostream& instead of a FILE*.
=> Strutil: extend type-safe variadic fprintf to stream output.

src/cineon.imageio/cineoninput.cpp, src/dpx.imageio/dpxinput.cpp, src/iconvert/iconvert.cpp, src/idiff/idiff.cpp, src/igrep/igrep.cpp, src/iinfo/iinfo.cpp, src/iv/ivgl.cpp, src/iv/ivmain.cpp, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp, src/libOpenImageIO/imagebufalgo_draw.cpp, src/libOpenImageIO/imagespeed_test.cpp, src/libOpenImageIO/xmp.cpp, src/libutil/argparse.cpp, src/libutil/filesystem_test.cpp, src/libutil/strutil_test.cpp, src/maketx/maketx.cpp, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp, src/psd.imageio/psdinput.cpp, src/python/py_oiio.cpp, src/python/py_oiio.h, src/raw.imageio/rawinput.cpp, src/testtex/testtex.cpp, src/zfile.imageio/zfile.cpp
Using vector::push_back when constructing a new object can cause
extra copies or allocations/deallocations. The new (C++11) emplace_back
grows the vector first and then constructs the object in place, avoiding
any unnecessary moves, copies, or allocations.
Thanks, clang-tidy, for finding all of these for us with no hassle.
=> Use C++11 vector::emplace_back()

src/cineon.imageio/libcineon/InStream.cpp, src/cineon.imageio/libcineon/OutStream.cpp, src/dpx.imageio/libdpx/InStream.cpp, src/dpx.imageio/libdpx/OutStream.cpp, src/include/OpenImageIO/color.h, src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/simd.h, src/libOpenImageIO/maketexture.cpp
Submitted on behalf of Ray Molenkamp (diff sent to me via email):
1. Fix several instances where int was passed or returned where a bool was expected, resulting in warnings on Windows.
2. Change places were simd types were passed to functions by value -- which apparently MSVS is not happy about because it can't guarantee alignment on the stack -- with pass by const value ref. Should be harmless, I think all the functions in question are inline anyway.
=> Fix Windows warnings (simd and bool/int)

src/include/OpenImageIO/function_view.h, src/include/OpenImageIO/timer.h, src/libutil/timer.cpp, src/libutil/ustring_test.cpp
It's for helping with benchmarks where you want to see how something scales
with number of threads.
Example output:
threads    time   speedup  efficient  its/thread   range (best of 1)
1        2.3     1.00x    100.00%   20000000     0.00
2        1.2     1.97x     98.50%   10000000     0.00
4        0.7     3.59x     89.86%    5000000     0.00
=> timer.h: Add handy timed_thread_wedge()

src/libutil/ustring.cpp
Pad the length of pool allocations for ustring::TableRep so that the next one allocated will also be aligned.
This was noticed by the undefined behavior sanitizer.
I don't think this was causing any issues, but its an easy fix that doesn't cost too much.
=> Fix ustring issue flagged by ubsan

src/libtexture/imagecache.cpp
=> Protect IC::get_image_info against out-of-range subimage or miplevel.

src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebuf_test.cpp, src/libOpenImageIO/imagebufalgo_test.cpp
It was not working, had an assertion.
Remove the assertion, fix the logic to make it work, add a test.
While I was there, I moved a histogram test from imagebuf_test.cpp to
imagebufalgo_test.cpp, it seemed to be more on-topic there.
=> Fix broken ImageBuf copy constructor from ImageBuf that wraps app buffer

CMakeLists.txt, Makefile, src/cmake/install.cmake
1. Some complaints (including failures in OSL TravisCI builds) led me to
believe that the 'cmake_policy (SET CMP0042 OLD)' was not correct and
that we should remove that and set MACOS_RPATH ON. This seems to clean
up some rpath troubles on OSX. It should not have any effect on non-OSX
builds.
2. For the Makefile wrapper, allow INSTALL_PREFIX to be set, which is
passed along to cmake as CMAKE_INSTALL_PREFIX. It defaults to the usual
of ./dist/PLATFORM, but this lets you override to, for example, instruct
the build to put the full installed files in another location. You could
always do this if invoking cmake directly, but it was tricky for those
who preferred to use the make wrapper.
=> OSX rpath fix and Makefile INSTALL_PREFIX setting

src/include/OpenImageIO/refcnt.h
I realized that if `intrusive_ptr<T>::reset(T*)` is called with a pointer
to the same object it already refers to, it could be erroneously freed
because it was decrementing the existing refcnt before incrementing the
refcnt of the new value. So rewrote reset() to be safe under that
circumstance.
=> intrusive_ptr bug fix

src/openexr.imageio/exrinput.cpp
A finger malfunction ages ago botched the list of channel names that
help us sort channels into canonical order. Where I wanted to say
RA, GA, BA, somehow I said RA, RG, RB. Oh boy.
=> EXR input: Fix to canonical sorting order -- typo bug fix

src/include/OpenImageIO/paramlist.h, src/python/py_paramvalue.cpp
We can remove most of the complexity of this class by making
ParamValueList inherit from `std::vector<ParamValue>` and just add the few
extra methods we want (like a version of find that is case-insensitive
on name, but excludes potential matches that are the wrong data type).
In other words, a change of "has-a" to "is-a" makes most of the code go
away.
=> Refactor ParamValueList

src/include/OpenImageIO/array_view.h, src/include/OpenImageIO/coordinate.h, src/include/OpenImageIO/platform.h, src/include/OpenImageIO/refcnt.h
Use C++11 constexpr and noexcept instead.
=> Deprecate OIIO_CONSTEXPR, OIIO_CONSTEXPR_OR_CONST, OIIO_NOEXCEPT

src/libutil/filesystem.cpp
searchpath_find had a couple calls to the underlying is_directory
and is_regular_file without catching any exceptions they might throw.
Those should be changed to Filesystem is_directory and is_regular
which are our existing wrappers that already catch any exceptions.
=> Exception safety improvements for Filesystem::searchpath_find.

src/cmake/modules/FindPugiXML.cmake, src/include/OpenImageIO/pugiconfig.hpp, src/include/OpenImageIO/pugixml.cpp, src/include/OpenImageIO/pugixml.hpp, src/libOpenImageIO/xmp.cpp
1. If pugi load_buffer finds syntax errors in the XML it is parsing, it returns an error code, which caused us to ignore the XMP block entirely, even the parts that were successfully parsed. It turns out that's a poor strategy, because lots of files have XMP that is ever so slightly malformed, so we weren't picking up their XMP at all! So, just ignore the fact there was a parsing error, go ahead and try to make sense of whatever portion (maybe all?) of the block was able to be parsed.  It works!
2. Added additional XMP tags for GPano, Google's Photo Sphere metadata    schema.
3. Replace linear search of the XMP tag list with a flat_map::find    (which underneath is a sorted vector with binary search).
4. Also add a bunch of camera raw (crs: prefix) XMP tags to the table.
5. Upgrade our …
=> Improve XMP parsing

src/doc/oiiotool.tex, src/oiiotool/oiiotool.cpp
When using --autocc, previously having the deduced color space be one
whose transformation was unknown was a hard error that would exit
oiiotool.  This patch changes an unknown color space be a warning, with
the rest of the oiiotool commands proceeding despite not transforming
the colors (this is just for the automatic transformations triggered by
--autocc).
=> Make oiiotool -autocc gracefully handle unknown color spaces.

src/include/OpenImageIO/simd.h
(C4714  : function marked as __forceinline not inlined)
Curious bug, MSVC refuses to inline the algorithmic operators in simd.h , but only tells you about it when you turn up the warning level to 4 or higher.  the [msdn docs](https://msdn.microsoft.com/en-us/library/a98sb923.aspx) list a number of reasons why it chooses not to inline a function, but the one that applies in this case is
> Functions returning an unwindable object by value when -GX/EHs/EHa is on.
By having a destructor (even an empty one) msvc deems the object unwindable and will refuse to inline it causing some rather severe performance issues in oiio. (blenders classroom benchmark scene rendered with OSL, reference : 09:15.15, with this fix: 06:49.26 , identical output) 
No tests changed, besides a performance difference …
=> Remove empty destructors to resolve MSVC warning C4714 

CMakeLists.txt
Fixes #1682
A little bit of extra cleanup in that area, too.
=> Fix cpack rename issue on OSX

src/bmp.imageio/bmpoutput.cpp, src/doc/imageioapi.tex, src/dpx.imageio/dpxoutput.cpp, src/field3d.imageio/field3doutput.cpp, src/hdr.imageio/hdroutput.cpp, src/ico.imageio/icooutput.cpp, src/include/OpenImageIO/imageio.h, src/jpeg.imageio/jpeginput.cpp, src/jpeg.imageio/jpegoutput.cpp, src/jpeg2000.imageio/jpeg2000output-v1.cpp, src/jpeg2000.imageio/jpeg2000output.cpp, src/libOpenImageIO/exif.cpp, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagespec_test.cpp, src/libOpenImageIO/iptc.cpp, src/libOpenImageIO/maketexture.cpp, src/libOpenImageIO/xmp.cpp, src/libtexture/imagecache.cpp, src/oiiotool/oiiotool.cpp, src/openexr.imageio/exroutput.cpp, src/png.imageio/png_pvt.h, src/python/py_imagespec.cpp, src/rla.imageio/rlaoutput.cpp, src/sgi.imageio/sgioutput.cpp, src/targa.imageio/targaoutput.cpp, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp, src/webp.imageio/webpoutput.cpp, src/zfile.imageio/zfile.cpp
Just use ParamValue and ParamValueList. Those typedefs never served any purpose, just deprecate them.
=> Stop using typedefs ImageIOParameter & ImageIOParameterList

src/doc/imagebufalgo.tex, src/doc/imageioapi.tex, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/deepdata.h, src/include/OpenImageIO/imagebufalgo.h, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/deepdata.cpp, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp, src/oiiotool/oiiotool.cpp, src/python/py_deepdata.cpp, src/python/py_imagebufalgo.cpp, src/python/py_imagespec.cpp, testsuite/python-deep/ref/out.txt, testsuite/python-deep/src/test_deep.py, testsuite/python-imagespec/ref/out.txt, testsuite/python-imagespec/src/test_imagespec.py
The deep holdout function is one that culls the deep samples in one deep    image (A) that are behind the opaque depth of a second deep image (B).    No samples of B are included in the output, it is only used to mask    parts of A. Samples of A that straddle the opaque frontier are split.
This is implemented as ImageBufAlgo::deep_holdout(), and also in  oiiotool --deepholeout.
This was suggested/requested by users. I believe the use case is that you have separately rendered volumetric elements and hard surfaces, and the user wants an oiiotool-based workflow that can inexpensively cull large sections of the volume that will get hidden by the opaque hard surfaces anyway, to make it much lighter and faster in Nuke or other processing that needs to happen to it.
Along the way, I made several …
=> deep holdout operation

src/libtexture/imagecache.cpp
In issue #1239, @lgritz described a situation in which the assertion in `check_max_mem()` could be triggered because `m_tilecache` could be empty, but `m_mem_used` could still be over the limit due to "dead man walking" tiles still being held in per-thread microcaches. A temporary fix was created in PR #1240, simply replacing the ASSERT with a DASSERT so that release builds wouldn't trigger the assertions. But this just allowed release builds to execute exactly the code path that the assertions were intended to protect - leading to the dereferencing of an invalid TileCache iterator. Here we simply replace the DASSERT with an early return if we detect this unexpected (but still entirely possible) situation. …
=> ImageCache :  Fix crash caused by dereferencing end iterator

src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/color_ocio.cpp, src/python/py_imagebufalgo.cpp
For several ImageBufAlgo functions related to color conversion:
* Deprecated in 1.7 -> turn on the OIIO_DEPRECATED attribute.
* Deprecated in 1.6, attribute turned on in 1.7 -> remove them.
=> Adjust deprecated IBA color conversion functions

src/libOpenImageIO/deepdata.cpp
Though it's against the OpenEXR spec, sometimes files are written with channel name "alpha". Be tolerant of that.
=> Allow 'alpha' alternate channel name in deep files

src/libtexture/imagecache.cpp
Analogous to #1696, but for the file cache.
=> Guard against dereferencing invalid file cache iterator.

src/cmake/compiler.cmake
After recent refactoring OPENEXR_DLL is defined when LINKSTATIC=ON which I'm guessing was not an intentional change. This restores the behavior before the refactor, fixing a bunch of LNK4217 warnings when building with static IlmBase libraries.
This matches the OSL fix in imageworks/OpenShadingLanguage#768
=> Fix Ilmbase linker warning with LINKSTATIC on Windows.

src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imagespec_test.cpp
Safely means, even if the channelnames is not filled out or you ask
for an out-of-range index, it will not crash or overrun the array, but
rather just return an empty channel name.
=> ImageSpec::channel_name(int) returns channel name safely

src/include/OpenImageIO/simd.h
* Add a bool4 and bool8 setcomp() method. It's a safer alternative to the existing `int& operator[]`, which is very sketchy with its exposing an `int&`, which isn't guaranteed to be the underlying representation (and won't be, when we add AVX-512). Eventually we'll make the unsafe ones deprecated. We certainly won't be extending them to bool16.
* Properly const bool4 and bool construction and load from `bool *`. Lack of const here was just an oversight.
* Fix a comment and remove a redundant declaration.
=> Minor simd.h touchups

src/iv/ivgl.cpp
After upgrading to Qt5, display scaling was all wrong on my Mac laptop with retina display. Some web searching revealed how to retrieve the device pixel ratio and use it as a scaling factor for GL.
This seems to mostly fix things.
=> iv / Qt5 -- compensate for display scaling

src/include/OpenImageIO/fmath.h, src/libOpenImageIO/deepdata.cpp, src/libutil/array_view_test.cpp, src/testtex/testtex.cpp
Just removing some pointless `#if` guards that are no longer needed.
=> Remove C++11 guards that are no longer needed

src/include/OpenImageIO/thread.h, src/iv/CMakeLists.txt, src/libutil/strutil.cpp
The following are small fixes caught by the GCC 7.1.0 compiler when used in combination with Qt 5.8.
As it stands there are still a number of warnings being emitted, but their scope was much greater than my drive-by edit had time to fix.
=> Gcc 7 1 0 / Qt 5.8 fixes

src/include/OpenImageIO/imageio.h
In this case implicit conversion caused the allocation of a temporary
std::string, which is deallocated before the string_view can be used.
=> Fix invalid string_view return from channel_name()

src/include/OpenImageIO/color.h, src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/platform.h, src/include/OpenImageIO/simd.h, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/compute_test.cpp, src/libOpenImageIO/imageio.cpp, src/libtexture/environment.cpp, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp, src/libutil/CMakeLists.txt, src/libutil/simd_test.cpp
* Add float16, int16, bool16 classes.
* When 16x HW support (AVX512) is selected, it is used, but otherwise just fall back to 8x[2] style      implementation. The aim is to make it convenient to code AS IF we were on AVX-512, but have pretty decent performance for AVX. The 16-wide classes should also run for SSE class hardware (or no SIMD at all), but I'm not working hard to optimize its performance in that case. Let's just accept that using 16-wide classes if you don't have at least 8-wide HW available is not going to get you a performance gain over scalar code.
* Preliminary support for masked loads & stores (including propagating those to 8x and 4x, which admittedly will not be very efficient for older HW).
* Lots of miscellaneous fixes to the 4x and 8x classes and cleanup of      this …
=> simd.h overhaul for 16-wide and AVX-512 support

src/openexr.imageio/exrinput.cpp
Background: OpenEXR forces channels to be stored (or at least presents
it through its API) in strictly alphabetical order. But OIIO expects
uniform channel orders for all the common cases such as RGBA.
For a 2-channel image that's intensity and alpha, we name the channels
"Y" and "A", and expect it to be presented with alpha second, as usual.
But OpenEXR was flipping the channel order because "A" comes before "Y"
alphabetically. Sheesh. It was because we neglected to put "Y" in the
list of special channel names that have order imposed. Easy fix.
=> OpenEXR: ensure that "YA" images get channels presented in the right order

src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp
For 2-channel images where the first channel is intensity and the second is
alpha, TIFF output was neglecting to set the TIFF "EXTRASAMPLES" tag to mark
the alpha channel. In particular, it just didn't consider extrasamples for images
that had fewer than 4 channels.
This was in turn causing the file, when re-input, to not realize that
the second channel was "A" or that there was an alpha channel at all
(since TIFF does not store channel names, we infer it all from the
EXTRASAMPLES tag).
One consequence of this mistake was that a grey-alpha image (say, coming
from OpenEXR or PNG or some other format that allows it) and run through
'maketx' (converting to TIFF if not otherwise specified) would lose this
knowledge, which in turn would affect the ability of the TextureSystem's
"gray_to_rgb" …
=> TIFF: clean up alpha channel handling

src/include/OpenImageIO/array_view.h, src/libutil/array_view_test.cpp
I don't remember exactly why these were commented out. But now I want them.
=> array_view: enable front() and back()

.travis.yml, src/include/OpenImageIO/simd.h
Primarily, this is adding test cases to the Travis matrix to build for AVX2 and AVX512F. The Travis VMs can't execute code compiled for that ISA, so I disable the running of tests for those cases. But it can build it, so at least we'll avoid accidentally breaking the build for those architectures.
Along the way, I did some minor touch-ups to substitute different intrinsics for some of the ones that appeared to be missing from the compiler versions on Travis (and thus would probably have caused troubles for other people as well).
=> SIMD - new Travis cases, fixups

src/include/OpenImageIO/unittest.h, src/libutil/simd_test.cpp
* Move the SIMD-oriented comparisons from simd_test.cpp into unittest.h.
* Use Strutil::Term() to use color in the unit test error message macros,
it makes it a lot easier to spot the assertion messages in the middle
of a long console output. I had used this in the simd_test.cpp ones
and really liked it and wanted to propagate the practice to all
unit test checks.
* Change the global unit_test_failures from a regular int to a special
counter class that will automatically print an OK/ERRORS message at
the end of execution when it destructs, and also automatically call
std::exit() with a nonzero return code if errors occurred, making it
impossible for a file using the unit tests to accidentail forget to
return an error code if there were errors.
=> unittest.h improvements

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
We previously had load_mask and store_mask for the 8x and 16x classes, but neglected to add them to the 4x classes until now.
Also, add scatter/gather operations for all classes (not expected to be efficient until AVX2), both regular and masked varieties.
=> simd: load_mask and store_mask for 4-wide, scatter/gather

src/libOpenImageIO/deepdata.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp
When merging, high number of splits was crippling performance due to
constant realocation.
New strategy more carefully pre-computes the NUMBER of splits expected
in the merged pixel, and allocates enough storage for the result pixel
to hold the number of samples in both of the input images, and also the
expected number of new segments that will result from splitting.
This speeds things up for very complicated frames by a couple orders of
magnitude.
=> Fix important performance issues with IBA::deep_merge()

src/include/OpenImageIO/parallel.h, src/include/OpenImageIO/thread.h, src/libutil/parallel_test.cpp
Upon reviewing parallel.h, it was apparent that there was a cut-and-paste
error that resulted in parallel_2D() having extra unused parameters.
Put it like I clearly meant it to be.
=> Fixes for parallel_for_2D

src/include/OpenImageIO/platform.h
Obsolete -- this is the standard noexcept declaration in C++11.
We don't seem to use it anywhere, so I'm going to take a chance and
just remove it straightaway, rather than deprecating it.
=> Remove unused OIIO_NOTHROW macro -- should use C++11 'noexcept' instead

src/include/OpenImageIO/paramlist.h
ParamValue move constructor was not copying the internal ParamValue type.
=> oiio: fixed move constructor of ParamValue class.

src/include/OpenImageIO/platform.h
Also finally remove the long-deprecated OIIO_USING_CPP11 macro.
Because (1) C++11 is the minimum now anyway, and (2) we switched
some time back to using OIIO_CPLUSPLUS_VERSION.
=> Try to detect C++17

CHANGES.md, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp
The TIFF spec says these (which we use to generate the ImageSpec x,y fields giving the data window origin of the image) should be relative to the "resolution units" described by the XRESOLUTION and YRESOLUTION.
But OIIO has always just stored the data origin directly in this field, without regard to any scaling factor of the [XY]RESOLUTION fields.
Now, let's realize that it's not very common to have files with nonzero data origin (crop windows) in TIFF files, also not common to have any RESOLUTION tags in the files. So the problematic combination, which would be interpreted differently by versions on either side of this patch, is rare.
But one way that we can get into trouble is the following sequence: (a) a JPEG from a camera (or any number of other cases) has resolution or density data …
=> TIFF: Change interpretation of XPOSITION,YPOSITION.

CMakeLists.txt, Makefile, src/cmake/oiio_macros.cmake, src/doc/texturesys.tex, src/include/OpenImageIO/texture.h, src/libtexture/environment.cpp, src/libtexture/texoptions.cpp, src/libtexture/texture3d.cpp, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp, src/testtex/testtex.cpp
There was previously a set of TextureSystem API calls (with multi-point TextureOptions struct and a fancy VaryingRef helper class) that was a multi-point interface, but we never did much with it and in retrospect, it does not use a data organization that is good for future-looking architectures. We are therefore depcrecating it, it will remain for 1.8 in case anybody is using it, but will thereafter be removed. 
But we are adding a new set of batched routines that are organized differently, we think in a way that will be well-suited for better parallelism.
The new API assumes that the inputs and outputs have a SOA rather than AOS layout, and the arrays are a fixed width, defined by Tex::BatchWidth, which is a constant and set to 16. Build-time overrides let us change this for …
=> SIMD batched texture APIs

src/libtexture/environment.cpp
My stupid bug, introduced during a minor refactoring related to the
static analysis from two commits ago. The static analysis was right,
by my fix to an apparent possible null ptr dereference was flawed. I
avoided the null dereference, alright, but broke some other logic in
the process.
=> Fix regression in environment()

site/spi/Makefile-bits-arnold, site/spi/Makefile-bits-spcomp2, src/nuke/txReader/CMakeLists.txt, src/nuke/txWriter/CMakeLists.txt
The most important bit is to disable warnings about deprecated auto_ptr in the Nuke 10 headers.
=> Support (and minor fixes) for building with clang 5.0

src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h
If a file is "broken", remember the error message that caused us to
consider it broken, so it can be properly reported later.
This is particularly helpful for files that are rejected for being
untiled or not mip-mapped (if "accept_untiled" or "accept_unmipped" are
false).  It's confusing to see "invalid file" as if the image file
itself was corrupted, much more helpful to see a specific error message
about the reason why it was rejected.
=> IC/TS: Improve error messages for broken files.

src/libutil/sysutil.cpp
For Unix/Linux, check the TERM env variable to be sure the particular
terminal supports color output. Inspired by Google Benchmark.
=> Refine terminal analysis for color console output

CHANGES.md, src/raw.imageio/rawinput.cpp
I'm concerned about this breaking raw reads. Looks ok to me and works on my cursory tests, but other stakeholders that rely on the raw format reader should please try this patch on their end and let me know if it's ok!
=> raw: unpack the pixels when you need them, not when you open

src/libutil/strutil.cpp, src/maketx/maketx.cpp
Fixes #1750
These two spots were implicated in the initialization order fiasco. (See: https://isocpp.org/wiki/faq/ctors#static-init-order )
The solution for maketx.cpp is that since we only are using the ColorConfig for the sake of generating a help message, there's no reason it can't be an ordinary local variable in the one (rarely called) function where it's used.
For the std::locale involved in strutil.cpp, use the old trick where instead of a file static, we have a function returning a reference, which itself has a function-static pointer that's allocated the first time it's needed. This leaks (a single std::locale), but who cares?
=> Fix statics contributing to static initialization order fiasco

CHANGES.md, INSTALL.md, src/cmake/externalpackages.cmake, src/openexr.imageio/exrinput.cpp, src/openexr.imageio/exroutput.cpp
VFXPlatform has dictated a minimum OpenEXR version of 2.0 since 2014,
and 2.2 since 2015.
Upgrading our minimum to 2.0 eliminates a lot of `#if` nonsense that was
necessary to continue supporting OpenEXR 1.x. There's no real burden
in continuing to support 2.0 & 2.1 for now. But we will continue to
re-evaluate the appropriate minimum in future releases.
=> Bump minimum OpenEXR/Ilmbase to 2.0

CMakeLists.txt, src/cmake/install.cmake, src/cmake/oiio_macros.cmake, src/doc/CMakeLists.txt, src/fonts/CMakeLists.txt, src/include/CMakeLists.txt, src/libOpenImageIO/imagebufalgo_draw.cpp, src/nuke/txReader/CMakeLists.txt, src/nuke/txWriter/CMakeLists.txt
Change all hard coded paths to GNUInstallDirs varibles.
Remove variable setting in main CMakeFiles.txt file since
GNUInstallDirs does all this for you.
Signed-off by: Jonathan Scruggs <j.scruggs@gmail.com>
As discussed in the similar PR from OpenShadingLanuage. I can sign the CLA as needed.
The new Python install directory code is just my attempt at a single variable to hold the install path. The idea was to show how GNUInstallDirs can be used for the path. You may be able to think of a better way. None of the prefixing …
=> oiio/master: Use GNUInstallDirs for installation paths

site/spi/Makefile-bits-arnold, site/spi/Makefile-bits-spcomp2, src/include/OpenImageIO/image_view.h, src/include/OpenImageIO/strided_ptr.h, src/libutil/array_view_test.cpp
Templatize based on the stride units. The default strided_ptr<T>
is equivalent to strided_ptr<T,sizeof(T)>, which means that strides
are measured in terms of the size of the element type. But, if you
really want to, you could make strided_ptr<T,1> which would be a
strided pointer where the strides are bytes rather than T's.
Note that this is a compatibility break -- previously, strided_ptr<>
used byte addressing all the time. This was counter-intuitive in many
circumstances, so now the default is to use array-like addressing where
the strides are measured in units of sizeof(T)>. But we have the ability
to still use byte addressing when really needed.
While I was in there, I changed a lot of the declarations to use
constexpr and noexcept very liberally, to maximize the chances that the …
=> strided_ptr<> improvements

src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/simd.h, src/include/OpenImageIO/unittest.h, src/libtexture/texturesys.cpp, src/libutil/fmath_test.cpp, src/libutil/simd_test.cpp
Say it together, boys and girls: "Untested code is buggy code!"
In this episode, I realize that the ifloor() function in fmath.h,
and also the inconsistently-named floori() from simd.h, both of which
have been used for many years without complaint, have a rather
startling bug: they give the wrong answer for negative integers!
The formal specification is that it returns the equivalent of
int(floor(x)), but the implementation tried to execute faster by using a
bit twiddling trick to avoid the 'floor' part of the computation, just
cast to int and then correct for negative values.
I don't even remember how I stumbled across this, but something caused
me to make a unit test for ifloor, and to my surprise, it failed for
exact negative integers. (For reasons that are head-smackingly obvious
once …
=> Fixes for ifloor, fast_ifloor, floatfrac

src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imageio_pvt.h.in, src/libtexture/imagecache.cpp, src/openexr.imageio/exrinput.cpp, src/tiff.imageio/tiffinput.cpp, testsuite/maketx/ref/out-alt-tiff4-2.txt, testsuite/maketx/ref/out-alt-tiff4.txt, testsuite/maketx/ref/out.txt, testsuite/oiiotool-maketx/ref/out.txt
It came to my attention that somebody could take a maketx-generated (or,
`oiiotool -otex`, same thing) texture, load it in Photoshop or other
utility, change it, and save it, and it just might still have some of
the maketx-specific metadata in the altered file, such as the SHA-1 hash
that allows us to find duplicates, and those data may be totally wrong
in the new file.
So this patch is intended to do a sanity check: if there is no
"textureformat" metadata present, or if it's not tiled, or if the
"Software" metadata doesn't say maketx or OpenImageIO, then it can't
have come straight out of maketx/oiiotool, so erase any of the
problematic attributes that maketx writes, because they are very likely
wrong and no longer match the potentially modified pixel values in the
file.
Photoshop always …
=> Protect against bogus texture SHA-1 and other attributes

CMakeLists.txt, src/doc/oiiotool.tex, src/libOpenImageIO/imagebuf.cpp, src/oiiotool/imagerec.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h, src/oiiotool/printinfo.cpp, testsuite/oiiotool-copy/ref/out.txt, testsuite/oiiotool-copy/run.py
So, oiiotool reads one or more images, might combine them, might
generate some from whole cloth. And the ones read from disk might not be
stored internally with the same data format as it existed on disk (it's
biased to store in float internally). How does it decide what data
format to write to disk for output?
We thought we were doing something sensible -- which is to allow an
explicit override (via `-d`), but in other cases to write using the
same data format as whatever was the FIRST file input. That at least
guarantees that a basic read-write cycle preserved the format.
But Chris Allen pointed out an interesting corner case, which is that
when you use `--siappend`, it will write out all subimages using the
first format it encountered.  But it seems like in this case, it ought
to be …
=> oiiotool: Revamp of logic for propagating data format.

src/include/OpenImageIO/paramlist.h, src/libutil/paramlist.cpp, src/libutil/paramlist_test.cpp
These are handy for extracting values from aggregates or arrays.
They still do the conversion to int or float, even if the real data
in the ParamValue is stored in a different (vaguely compatible) type,
such as converting a uint16 data to an int when requested.
=> ParamValue -- add get_int_indexed() and get_float_indexed() methods.

src/include/OpenImageIO/platform.h, src/include/OpenImageIO/string_view.h, src/libutil/strutil.cpp
See the comments in the patch for details. It's been like this for a
long time. I think in practice, we'll never hit the bug. But we'll
probably phase this method out anyway, since it's not part of the C++17
std::string_view.
=> string_view -- document a subtle but rare bug, turn off address sanitizer

CMakeLists.txt, src/libOpenImageIO/imageioplugin.cpp, src/libutil/filesystem.cpp, src/null.imageio/CMakeLists.txt, src/null.imageio/nullimageio.cpp, testsuite/null/ref/out.txt, testsuite/null/run.py
This I/O plugin for "null" images are a file "format" where output of a null file does nothing at all (no I/O, not even any data copying), and input of a null file just fills the result buffers with black pixels (0 values), with no I/O or data copying.
What's this good for?
* Benchmarking, if you want to have OIIO's input or output truly take as close to no time whatsoever.
* "Dry run" of applications where you don't want it to produce any real      output (akin to a Unix command that you redirect output to /dev/null).
* Make "fake" input that looks like a file, but the file doesn't exist      (if you are happy with constant-colored pixels).
The filename allows a REST-ful syntax, where you can append little doodads    that specify things like resolution (of the non-existent file), etc. …
=> null image input & output

src/include/OpenImageIO/simd.h
A bunch of things in `#if OIIO_AVX512VL_ENABLED` had cut and paste typos, I guess I never compiled in that mode before. Fixed and tested now.
=> simd.h: fix a bunch of broken code for AVX512VL

src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/tiffutils.h, src/jpeg.imageio/jpeginput.cpp, src/jpeg.imageio/jpegoutput.cpp, src/libOpenImageIO/CMakeLists.txt, src/libOpenImageIO/exif-canon.cpp, src/libOpenImageIO/exif.cpp, src/libOpenImageIO/exif.h, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/xmp.cpp, src/libutil/paramlist.cpp, src/oiiotool/oiiotool.cpp, src/png.imageio/png_pvt.h, src/psd.imageio/psdinput.cpp, src/raw.imageio/rawinput.cpp, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp, testsuite/gpsread/ref/out-alt.txt, testsuite/gpsread/ref/out.txt, testsuite/gpsread/run.py, testsuite/oiiotool-attribs/ref/out.txt, testsuite/psd/ref/out-alt.txt, testsuite/psd/ref/out.txt, testsuite/tiff-suite/ref/out-alt.txt, testsuite/tiff-suite/ref/out-jpeg9b.txt, testsuite/tiff-suite/ref/out.txt
"Maker notes" are extra camera manufacturer-specific metadata stored as
opaque blobs inside Exif records. The manufacturers don't seem to
publish the specs for these blobs, but they have been reverse engineered
and with some hunting you can find tinkerer-prouced documentation (at a
range of levels of completeness or correctness).
With this patch, we do a substantial refactor of exif.cpp to incorporate
full awareness of maker notes into our metadata processing. At this
stage, we only read Canon makernotes, and quite incompletely. But we get
a lot more of the metadata than we used to (previously we just ignored
any makernotes we found), and the structure is now sound for adding more
complete support for this and other cameras. It involved a substantial
refactor of exif.cpp, as well as some …
=> Refactor of metadata printing and Exif read/write

INSTALL.md, src/raw.imageio/rawinput.cpp
An API call I recently started using turns out not to be available in older versions of libraw. Like the one we have installed at work, ahem.
=> Fix build break for old libraw

.travis.yml, INSTALL.md, src/cmake/externalpackages.cmake, src/libOpenImageIO/exif.cpp
The recent Exif patch broke for old TIFF versions. Fix.
Also document more clearly what the TIFF library version requirements
are.
=> Fix recent build break against old libtiff

src/include/OpenImageIO/color.h, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/maketexture.cpp
* Change ColorConfig to return shared ptrs to ColorProcessors. This frees
the caller from having to own the resource and remember to delete it.
It also makes leaks impossible.
* Establish an internal cache of ColorProcessors, so that repeated requests
for the same processor (i.e., same color space transformation) doesn't
need to do any allocations or trigger anything expensive on the OCIO
side.
* Added new create...() methods that take ustring arguments, in addition
to the existing ones that take string_view. That version is faster
if you already have ustrings on the app side -- especially the part of
looking it up in the cache. The string_view ones are still fine to use,
they just build ustrings on their own.
* A little bit of C++ modernization.
NOTE that this is a breaking change, …
=> ColorConfig refactor

src/include/OpenImageIO/thread.h, src/libutil/spin_rw_test.cpp
You can see the performance in the following two tables. It's a
benchmark using our unit test spin_rw_test.cpp. We vary the ratio of
writers to readers from 1:9 (one write lock and modify for every 9 read
locks) to 1:9999.
All times are in seconds for this workload (smaller is better), and
they were executed on Linux on a machine with 32 physical cores (64
hyperthread cores).
Old code:
threads  1:9     1:99      1:999     1:9999
--------------------------------------------
1       0.3      0.3       0.3        0.3
2       0.5      0.5       0.6        0.5
4       5.4      3.4       3.2        2.8
8       9.9      9.5      10.6        9.0
12      12.3     13.1      11.8       12.1
16      13.7     14.3      14.0       14.8
24      17.9     16.9      18.3       18.1
32      21.4     22.2 …
=> New spin_rw_mutex implementation with greatly improved performance

src/include/OpenImageIO/unittest.h
It previously worked for the OIIO tests that all seemed to have a
'using namespace OIIO', but failed for external projects that just wanted
to use unittest.h and weren't inside namespace OIIO.
=> unittest.h: Make the reference to Strutil fully qualified with OIIO::

Makefile, src/openexr.imageio/exrinput.cpp
1. Remove debugging output that is no longer needed.
2. Bug in Makefile where CMAKE_BUILD_TYPE was set to Debug any time CODECOV was specified on the make command line, even when setting `CODECOV=0`.
Fixes #1790
=> Minor debug fixes

src/libOpenImageIO/CMakeLists.txt
This is simple change that fix MSVC error:
```
CMake Error at src/libOpenImageIO/CMakeLists.txt:154 (add_dependencies):
The dependency target "" of target "OpenImageIO" does not exist.
```
=> Fix CMake error with MSVC compiler

.travis.yml, src/fits.imageio/fitsinput.cpp, src/include/OpenImageIO/optparser.h, src/include/OpenImageIO/strutil.h, src/include/OpenImageIO/tinyformat.h, src/include/OpenImageIO/ustring.h, src/iv/imageviewer.cpp, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/maketexture.cpp, src/libtexture/imagecache.cpp, src/libtexture/texturesys.cpp, src/libutil/argparse.cpp, src/libutil/benchmark.cpp, src/libutil/filesystem.cpp, src/libutil/strutil.cpp, src/libutil/strutil_test.cpp, src/libutil/ustring.cpp, src/maketx/maketx.cpp, src/oiiotool/oiiotool.cpp, src/rla.imageio/rlainput.cpp
This refactor comes after a belated realization that our numeric
conversion routines (principally from_string<> and format) are
"locale-dependent" via their use of strtod, as well as atof() scattered
through the code.
In particular, this means that when software using this code is running
with a locale in which the decimal mark is something other than '.'
(e.g., many European locales that use ',' for decimal mark), these
functions will incorrectly parse text floating point numbers that use
the standard period as decimal mark.  For example, if the locale is
"fr_FR", atof("123.45") will return 123.0, rather than the correct
123.45.
After much debate, and a few implementations, we are declaring that
since the whole point of OIIO is about reading and writing persistent
data (image files!), …
=> More principled handling of string<->numeric conversions.

src/libtexture/imagecache_pvt.h, src/testtex/testtex.cpp
Increase the number of shards in the unordered_map_concurrent used by the ImageCache for file and tile caches. As we get machines with larger core counts and thread them more heavily, the previous limits were causing bottlenecks.
This solution is not perfect nor complete. But it does push the bottleneck from ~16 to more like ~32 threads. I'm separately working on some other strategies to reduce the amount of locking, with an eye toward every-growing core counts. But this is a solid step forward for our newer machines.
I also made some of the timings printed by testtex be just a bit more explanatory.
=> ImageCache: improve thread contention

src/libOpenImageIO/imagebufalgo_draw.cpp
Clearly a bug. Found in CI when compiled by gcc6 (as a warning)!
=> Indentation vs brace typo bug

src/libOpenImageIO/imagebufalgo_draw.cpp
When USE_FREETYPE=0, the resolve_font() function was declared but never
called, generating a warning on some platforms.
Solution is to move the whole function inside the `#ifndef USE_FREETYPE` guard.
=> Fix USE_FREETYPE=0 build

src/oiiotool/oiiotool.cpp
maketx (really, the underlying IBA::make_texture() call) writes to a
temporary output file, then after it's done, atomically moves the file
to its requested destination. This ensures proper operation if the user
foolishly specifies that output should overwrite input (same file), and
also is a guard against a crashing program leaving a corrupted
half-written file behind that could be mistaken for proper output.
This patch employs the same trick to oiiotool. It was "safe" to have
oiiotool in.exr ...blah... -o in.exr
if in.exr was small enough -- in which case it would be fully read into
its ImageBuf when first encountered. But if it was a large file, it would
rely on ImageCache, so it was possible that when the output started to
overwrite it, trashing the file, not all the parts of the …
=> File output safety for oiiotool

src/libtexture/texturesys.cpp
A use case has come up that makes me think 6 channel textures are going to be important for us, so I want the threshold for splitting tiles to include that situation.
=> TextureSys: bump max_tile_channels limit to 6

src/include/OpenImageIO/paramlist.h, src/libutil/paramlist.cpp, src/libutil/paramlist_test.cpp
ParamValue holds "small" data locally (in the struct), and only
allocates when above that threshold. Previously, the threshold was 8
bytes, the size that the allcoated pointer would be anyway. But it seems
to me that the way we us ParamValue frequently must contain a color (3
floats), so I bumped the local space from 8 to 16 bytes (meaning it can
hold up to 4 floats or ints before a malloc). This increases the total
size of a ParamValue from 32 to 40 bytes, but I think it will make it
fairly rare to allocate, so we'll come out ahead.
This should all be inconsequential from an API perspective.
=> Increase "local" space of ParamValue

src/doc/imageinput.tex, src/doc/oiiotool.tex, src/include/OpenImageIO/argparse.h, src/libOpenImageIO/imagebuf.cpp, src/libutil/argparse.cpp, src/oiiotool/oiiotool.cpp, src/python/py_imagebuf.cpp
Most notable is that `oiio --help` now prints some important usage tips
that explain command parsing, syntax of optional modifiers, and the path
where you can find the full PDF docs.
Along they way, I made a couple small additions to ArgParse, in order to
make it easier to insert this extra help information in the place where I
wanted it to appear.
=> Some documentation, help, and error message improvements

src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/xmp.cpp
A strange edge case turned up: when parsing a file with XMP data block,
and the XMP contained metadata "Exif:PixelXDimension" (or PixelYDimension),
a cascade of failures eventually led to a crash in `oiiotool -info -v`.
Fixes herein include:
* Add those two entries to the table of xmp fields we expect to see, in
xmp.cpp.
* In xmp.cpp's add_attrib(), if something is not found in the xmp table
(which among other things translates the XMP name into an OIIO name),
stick with the xmp name it came with. We were actually adding it as an
attribute using 'oiioname', which for that case was uninitialized!
* Finally, in ImageSpec::attribute(), check for empty names, which are
obviously errors, and don't add those attributes.
=> Fix xmp parsing bug

src/include/OpenImageIO/imagebufalgo.h, src/include/OpenImageIO/imagebufalgo_util.h, src/include/OpenImageIO/parallel.h, src/include/OpenImageIO/thread.h, src/libutil/strutil.cpp, src/libutil/thread.cpp, src/libutil/thread_test.cpp
* Move parallel_image_options to OIIO level in parallel.h as parallel_options.
* Add field to parallel_options to allow for recursion within the
thread pool (use with caution to avoid thread explosion!).
* Use parallel_options as a control parameter to the various parallel_for
family of functions as a way of communicating preferences for maximum
threads, custom thread pool, and recursion.
* Some minor logic changes in chunking logic.
* More careful tracking of which threads are participating in the pool --
not only pool threads, but also the *calling* threads that opportunistically
execute tasks from the queue while they are waiting for the rest of the
task set to be done... those also need to be protected from inadvertent
recursively adding things to the queue.
Note that this should be …
=> parallel utility improvements

src/libOpenImageIO/compute_test.cpp, src/libutil/atomic_test.cpp, src/libutil/filter_test.cpp
(had this sitting in my tree for weeks, helps speed up build/test cycles)
For compute_test and filter_test, switch from time_trial to Benchmarker.
This reduces the code complexity, and because Benchmarker figures out
on its own how many iterations to do in order to get good timings, it
runs MUCH faster overall (we were using too many iterations), so this
will speed up testsuite runs.
Also reduce time spend on atomic_test by lowering iterations, raising trials.
=> Simplify and speed up some unit tests

src/include/OpenImageIO/platform.h, src/libtexture/imagecache.cpp, src/libutil/sysutil.cpp
A small collection a minor performance tweaks. The most important is probably correctly aligning the `ImageCache` struct because this isn't guaranteed by the C++ standard.
These aren't moving the needle too much just yet, but show a small decrease in the relevant functions in vtune.
=> Performance tweaks

src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h
It has been set to false by default for a while now and setting it to true seems to be always slightly slower
=> Remove read_before_insert parameter

CMakeLists.txt, src/cmake/externalpackages.cmake, src/include/OpenImageIO/unordered_map_concurrent.h, src/libOpenImageIO/CMakeLists.txt, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/testtex/CMakeLists.txt
This improves performance of the texture cache by a bit (proper benchmark numbers running over the weekend).
This is a very conservative first step, lots more can be done to further speed this up, and there are more uses of `std::unordered_map` we should benchmark, but I want to do those one at a time.
=> Replace std::unordered_map in the concurrent hash map

src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h
It seems that the clock sweeping algorithm for finding cache pages to
evict (i.e., the uts of ImageCacheImpl::check_max_mem) relied on the
fact that it could erase entries from the cache and continue sweeping
with the iterator.
This worked fine for the original unordered_map, and as well for the
unordered_map_concurrent as long as the individual shards were also
implemented by unordered_map -- but only because unordered_map used
chaining and thus an iterator would still be valid after an erase
(assuming the iterator wasn't pointing to the erased item itself).
But when Chris tried using a different underlying hash table which didn't
have this property, things broke.
Some refactoring of check_max_mem fixes the problem. Basically, I just
save the ID of the advanced iterator, allow the …
=> IC Cache "clock" algorithm -- fix iterator invalidation problem

src/libOpenImageIO/imagebuf.cpp
Critical bug fix when dealing with certain odd data types.
I recently broke this when trying to streamline compilation by changing some uses of DISPATCH_TYPES to DISPATCH_COMMON_TYPES.
=> Bug fix with ImageBuf::copy of rare types

src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageio_pvt.h.in
Get rid of parameters we don't use, clean up a bit.
These are internals only, doesn't affect any public APIs.
=> Simplify from_float

src/libOpenImageIO/imagebufalgo.cpp, testsuite/oiiotool/ref/out.txt, testsuite/oiiotool/run.py
Interesting edge case I came across:
oiiotool rgb.exr rgba.exr -add -o out.exr
The logic was that the result had 4 channels (the greater of the two
inputs), but the channel names were just copied straight from the first
input, and it was (coincidentally, in this example) the one with fewer
channels, so it did not know that channel 3 was alpha, it would just get
"R", "G", "B", "channel3".
The new logic is that for all channels, it tries to get the name from
the first image, and if it doesn't exist, then it gets it from the
second. Also it's smarter about setting alpha_channel and z_channel in
the spec of the output, even if those didn't come along with the first
input.
=> oiiotool: Better channel name logic when combining images

src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageoutput.cpp, src/tiff.imageio/tiffoutput.cpp
TIFF didn't have write_scanlines() of its own, just depending on the
default implementation, which calls write_scanline repeatedly.  So we
give it a proper write_scanlines implementation, which tries to speed
things up by first doing all the conversions and data shuffling on the
whole block (which can be parallelized by our code), before writing the
individual scanlines.
Slightly adjust the chunk size for write_image (it was a little too
conservative).
In parallel_convert_from_float, instead of a hard-coded block size, let
parallel_for_chunked make the choice on its own, which will be better
because it takes into account the number of threads in the pool
These changes, cumulatively, speed up whole-image writes of scanline TIFF
files by about 10%. I was hoping for more than this, but the …
=> Speed up TIFF scanlines output

src/zfile.imageio/zfile.cpp
This could make crashes with certain filenames on Windows. And even though zfiles are rare, when OIIO is not sure which plugin to use, it tries them all, so when given a bogus filename or a file that isn't really an image, it will be called sooner or later.
Submitted on behalf of Thiago Ize.
=> More careful gzopen on windows.

src/libOpenImageIO/imageoutput.cpp
This supersedes #630, which was never finished and won't merge correctly now anyway. But its idea was sound, and it's simpler to implement now, since the quantize fields are no longer in ImageSpec.
=> ImageOutput: avoid needless data conversion in to_native_rectangle

src/cmake/modules/FindOpenCV.cmake
It is not necessary to link against the OpenCV highgui component in version 3.X and above as it has been split into 3 components.
- [x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x ] I have updated the documentation, if applicable.
- [x ] My code follows the prevailing code style of this project.
=> Linking with OpenCV highgui component is not needed for 3.X and newer.

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
* Minor improvements to rcp_fast, rsqrt_fast for AVX512.
* Maked load/store tweaks:
* Remove some concern comments on 4-wide masked load/store for AVX
because benchmarks show it to be no concern (the lines of potential
concern were indeed faster on AVX).
* Change implementation of 4-wide scatter and masked scatter for avx512
after benchmarks show that the non-SIMD way is faster. Come back to
retest on future hardware.
* Speed up reduce_and / reduce_or for vbool16
* Fix typo
=> simd.h touchups

src/field3d.imageio/field3dinput.cpp
Field3D is supposed to just throw an exception that we can catch if it
can't open the file, but under some circumstances it just plain crashes
when asked to open a file that isn't a f3d file at all.
The reason this comes up is that OIIO's behaveior when the usual reader
can't open a file is to try ALL of them (hoping that maybe the file is
just mis-named) or the hint heuristics are wrong.
I'm not inclined to try to fix the field3d internals myself at this
moment, so for now I'm just making the OIIO field3d reader fail if the
file is not named ".f3d". This violates our intended rule of "it doesn't
matter what the file is called", but I can only rely on that if the
underlying format library is rock solid when presented a file of the
wrong type.
=> Field3d: don't crash under opening failures

src/iinfo/iinfo.cpp, src/openexr.imageio/exrinput.cpp
The EXR spec allows for channels to be subsampled, but we don't handle
this properly in the exr ImageInput, and it can lead to a crash.  Since
it's a rarely used feature (if ever), I'm not inclined to fix it for
real until somebody says they actually need it. Instead, let's just
detect this unusual case and correctly issue an error saying that we
don't support it.
This required a bit of housekeeping to allow the errors to be propagated
up from the place where it was convenient to notice this.
=> OpenEXR reader: gracefully reject subsampled channels

src/libutil/strutil.cpp
Fix Strutil::strtod_l/strtod_l, so it builds on Hurd, and on systems using the fallback code using the non-_l versions.
Builds on Hurd, using both fallback code and _l versions.
=> Fix Strutil::strtod_l/strtod_l on Hurd

src/raw.imageio/rawinput.cpp
This commit exposes the HighlightMode setting in libraw to allow users to control the method of highlight clamping performed by the library. This follows the usage of "-H" in the dcraw command line utility.
The valid values are:
0 (default) - clip
1 - unclip
2 - blend
3-9 - rebuild / interpolate (at various levels of intensity).
There are not currently any raw image tests that I know of, but it works on my machine!™
=> raw: Added raw:HighlightMode attribute to control highlight clamping

src/build-scripts/nosanitize.txt, testsuite/runtest.py
* Add a few places (mainly in boost) to the nosanitize.txt exception
list for lsan.
* Make runtest.py skip any test directory that contains a file called
TRAVIS_SKIP_LSAN, but only if it's running the sanitize test case on
Travis. On local machines, or for all other test matrix entries, it
will run as usual.  So we set up this file for 4 testsuite directories
where it's just not practical to fix the extremely minor leaks.
This cleans up a handful of tests that recently started to fail the
Travis test that runs the sanitizer. (Nothing changed on my side; I
suspect some minor compiler upgrade on the Travis side started catching
additional cases.) It all passes with this patch, now that I'm ignoring
a few specific cases where I've verified that the "leaks" are small
one-time allocations that …
=> Clean up spurious leak sanitizer errors

src/oiiotool/oiiotool.cpp
I think it's possible to deadlock when doing certain parallel IBA functions in combination with autotile. When the deadlock possibility is fixed, maybe we'll turn it back to on by default, but for now this seems safer.  Users can always turn it on with the --autotile command line flag to oiiotool.
I think we've been lucky up until now. To trigger, it needs the right combination of enough threads, timing just right and traversing particular patterns, large enough image that the autotile uses more than one tile (remember, the default was 4k, so I only noticed the problem on an 8k image).
I think I know how to fix it, but I don't have time to do it right now. So better to just change the default oiiotool behavior to not trigger the possible bug.
=> oiiotool: autotile off by default.

src/libOpenImageIO/CMakeLists.txt
OpenImageIO leaves undefined symbols for dlopen / dlclose / dlsym and friends. At the moment it seems we are working around the issue by explicitly linking ${CMAKE_DL_LIBS} in the unit tests, but this still leaves the main library missing symbols. This commit makes the dependency on ${CMAKE_DL_LIBS} explicit.
=> Added explicit link to CMAKE_DL_LIBS for OpenImageIO target

src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/imagebufalgo_compare.cpp, src/libOpenImageIO/maketexture.cpp
ImageBufAlgo::computePixelStats was completely serialized. Turns out that
this was a big chunk of "unaccounted" time in maketx.
So parallelize it in the usual way, with parallel_for_chunked_2D,
and some other cleanup to the PixelStats struct.
Also modify the stats keeping in make_texture() to account for and
report the computePixelStats time separately.
=> Parallelize computePixelStats

CHANGES.md, src/doc/oiiotool.tex, src/doc/openimageio.tex, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/oiiotool/oiiotool.cpp, testsuite/oiiotool-spi/ref/out.txt, testsuite/oiiotool-spi/run.py
After some deep thinking and discussion with people who know more color
than me, I have become convinced that you *almost always* want to make
sure to un-premultiply colors (i.e. divide by alpha) before doing color
space transformations with OCIO, and then re-multiply by alpha (to get
back to "associated alpha") immediately after the color transformation.
To support this,
* For the ImageBufAlgo color transformation functions, change the default
value of the `unpremult` parameter from `false` to `true`.
* `oiiotool --colorconvert` and the various `--ocio` commands will
also default to doing the unpremult/premult steps, unless a new optional
modifier is used: `:unpremult=0`.
* `oiiotool --autocc` will do the unpremult/premult steps surrounding any
automatic color transformations that it …
=> Color transform unpremult logic changes.

src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebuf_test.cpp
The fully general case uses IB::iterator element by element and can
handle ImageCache-backed images.
For the common case of the image being fully in memory, it reduces to
a call to parallel_convert_image, which is about 3x faster.
=> Speed up ImageBuf::get_pixels()

src/libOpenImageIO/imagebuf.cpp
I realized/remembered that the "general" version that uses iterators is
not only necessary for the ImageCache-backed case, but also handles wrap
modes and samples outside the data window. Thus, it is not safe to use
the fast parallel_convert_image unless the ROI we are dealing with stays
strictly within the pixel data window of the image. So add that check.
=> Bug fix addendum to recent get_pixels speedup

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/python/py_roi.cpp, testsuite/python-roi/ref/out.txt, testsuite/python-roi/src/test_roi.py
To both C++ and Python. Also add unit tests for this as well as the
recently-added contains(x,y,z,ch).
=> Add ROI::contains(ROI)

src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imagebufalgo_test.cpp
Both of these (crop calls copy underneath) were threaded, but used
iterators to be fully general.
Much like the recent ImageBuf::get_pixels fix, using
parallel_convert_image (which has been heavily optimized) speeds up the
common situation where the source image is already in local memory and
the ROI being copied is fully contained in the pixel data window.
I'm seeing speedup of copy about 35% when copying a 4 channel float
image (to either a float or an uninitialized buffer), 3x speedup when a
data conversion is involved (copying a 4 channel float to a 4 channel
uint8 buffer), and almost 4x improvement copying 4-chan half to 4-chan
half (because the general code did an expensive half->float->half set of
conversions in the process).
=>  Speed up IBA::copy and IBA::crop

src/doc/pythonbindings.tex, src/python/py_imagebuf.cpp
Only one of the two read methods was properly exposed, and only the other one was documented.
This could be really bad if you tried using the other (documented) one, as the default arguments could kick in and make the interpretation quite different. In particular, your 'force' and 'convert' hints may be misinterpreted, ugh.
=> Fix ImageBuf::read python bindings

src/doc/imagebuf.tex, src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebuf_test.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp
Let the pixeladdr also take a channel offset.
Clean up some legacy versions of pixeladdr(); only one version is
needed with parameter defaults properly used.
Simplify the implementation of pixel_stride, scanline_stride, z_stride
to be based on the already-computed byte counts (I just didn't remember
that they existed when I exposed those functions).
With the new pixeladdr method that takes a channel offset, I can
lift the restrictions on special cases of copy and crop that require
starting at channel 0.
=> ImageBuf::pixeladdr() -- extend with channel parameter

src/include/OpenImageIO/parallel.h, src/include/OpenImageIO/thread.h, src/libutil/parallel_test.cpp, src/libutil/thread.cpp, src/libutil/thread_test.cpp
There was no reason for task_set to be a template -- the templated type
was no longer used for anything. Changing it from template to normal
class also means that it was convenient to move task_set::wait() and
wait_for_task() from inline to be in thread.cpp. This makes it so that
tinkering with these methods just rebuilds one file, whereas when it's
in thread.h, any changes to it forces a recompile of most of OIIO.
=> task_set refactor

src/libOpenImageIO/imagebufalgo_draw.cpp, src/libOpenImageIO/imagebufalgo_test.cpp
Convert the (float[]) values to the data type of the buffer once, rather
than building float->buftype data conversion into every channel of every
pixel.
Fill of float and half buffers speed up by about 1.5x.
Fill of uint8 and uint15 buffers speed up by about 2.5x.
=> Speed up IBA::fill of constant color

CHANGES.md, src/doc/imageioapi.tex, src/include/OpenImageIO/imagebufalgo.h, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/imagebufalgo_addsub.cpp, src/libOpenImageIO/imagebufalgo_channels.cpp, src/libOpenImageIO/imagebufalgo_compare.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imagebufalgo_deep.cpp, src/libOpenImageIO/imagebufalgo_draw.cpp, src/libOpenImageIO/imagebufalgo_mad.cpp, src/libOpenImageIO/imagebufalgo_muldiv.cpp, src/libOpenImageIO/imagebufalgo_opencv.cpp, src/libOpenImageIO/imagebufalgo_orient.cpp, src/libOpenImageIO/imagebufalgo_pixelmath.cpp, src/libOpenImageIO/imagebufalgo_xform.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageio_pvt.h.in, src/libOpenImageIO/maketexture.cpp
All ImageBufAlgo functions (for now; other functionality may be added to logging down the line) are outfitted with optional timers to count the number of executions and total time spent for each.
This is enabled by a new global OIIO attribute "log_times", which can be enabled and disabled at any time (for example, to only log a certain phase of execution of an app).
The default is 0, meaning not to log -- and I believe that when turned off, there is no added runtime cost (except for checking the flag once per IBA function).
The initial default can be changed with the OPENIMAGEIO_LOG_TIMES environment variable.
When log_times is nonzero, logging will occur, with a slight increase in runtime expense to check the times and to lock and access the map that stores all the running totals (stored …
=> Option to time all IBA functions

CMakeLists.txt, src/doc/CMakeLists.txt
I've been carrying around this patch for a while. It's much easier for me to use rpmbuild to install the documentation in the right places for Fedora. This allows me to build the documentation without installing it. 
It also uses the target to find IV instead of looking for the binary directly as it will always find the installed iv of the previous released package instead of the one in the build tree.
=> Make building and installing of documentation more packaging friendly.

src/include/OpenImageIO/parallel.h, src/include/OpenImageIO/thread.h, src/libOpenImageIO/imagebuf.cpp, src/libutil/thread.cpp
1. Move the body of parallel_for_chunked and parallel_for_chunked_2D
from an inline in parallel.h to being non-inlined in thread.cpp.
The main advantage is so that as I tinker with the internals of these
functions, it's just one module that needs to recompile, rather than
the fact that an altered parallel.h forces a rebuild of most of the
project.
2. Implement a thread_pool::jobs_in_queue() that reports how many tasks
are waiting to execute (but haven't started yet) and a
thread_pool::very_busy() method that basically tells whether the number
of tasks waiting in the queue is significantly larger (currently: >4x)
than the number of threads in the pool. The idea here is that clients of
the thread pool could use this to avoid putting things onto the end of a
greatly oversubscribed queue and …
=> Thread pool and parallel-for refactor/improvements

src/include/OpenImageIO/missing_math.h, src/include/OpenImageIO/platform.h
We've advertised for some time that 2013 was the minimum version. Get
rid of some cruft from before that.
=> Remove accommodations for MSVS older than 2013

src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/platform.h
To support compilation for CUDA targets, we have added device-friendly specializations of a subset of functions in ``fmath.h``. Where necessary, include directives and function definitions that are not able to be compiled in device mode have been guarded with a preprocessor macro.
The changes are guarded by a preprocessor macro and are only active when being compiled by a CUDA compiler. Since CPU compilation is not affected, no additional test cases have been added at this time.
=> Modifying fmath.h to allow CUDA compilation

src/libutil/filesystem.cpp, src/oiiotool/oiiotool.cpp, testsuite/oiiotool/ref/out.txt, testsuite/oiiotool/run.py
Fixes #1889, which reported that frame sequence wildcards involving
negative frame numbers were not correctly supported. For example,
oiiotool --frames 1-5 ...      # 1, 2, 3, 4, 5  (as usual)
oiiotool --frames -3-3 ...     # -3, -2, -1, 0, 1, 2, 3
oiiotool --frames -3--1 ...    # -3, -2, -1
In addition to handling negative frame numbers and ranges, I also made a
change to facilitate testing and benchmarking, which is that the
presence of `--frames` is now itself enough to trigger the looping +
wildcard expansion. Previously, if there were no numeric wildcards in
any of the filenames, it would not execute the frame loop (even if there
was a --frames).
=> Improvements for frame sequence wildcards

src/libOpenImageIO/CMakeLists.txt
=> MSVC: use /bigobj on some other large files

src/libOpenImageIO/imageinput.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageoutput.cpp, src/libutil/fmath_test.cpp, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp
OpenEXR's library has a neat feature where it maintains a thread pool and if you are using the multi-scanline or multi-tile I/O API calls, it will do the compression/decompression of the scanlines or tiles in parallel, even though the disk I/O itself is serial (but the codec work accounts for most of the time, so this is a big speed win). The result is that with many threads, a 5-7x speedup in I/O is typical, versus the single threaded case.
libtiff doesn't do this -- it is not thread-safe or reentrant (for a single file), and lacks API calls to write multiple tiles or scanlines at once (small exception: it will output a "strip" of several scanlines, but not in a flexible way like OpenEXR's). So any straightforward use of libtiff means using one core to do all the work writing (or …
=> TIFF whole-file I/O speedup 5-10x with multithreading

src/include/OpenImageIO/fmath.h
Turns out that nvcc considers it an error if a `__device__` function is
called from a `__host__ __device__` function, even if the latter is
conditionally compiled only for Cuda mode.  So a function like fast_sin
(which for Cuda calls `__sinf` underneath), this will hit the error.
To make it even more complicated, this is only a problem with nvcc, not
with clang when compiling Cuda, which is how this was overlooked before.
So, as an example, you can't do this:
__host__ __device__ void myfunc () {
#ifndef __CUDACC__
...generic code...
#else
device_only_func();
#endif
}
It seems you have to structure it like this:
#ifndef __CUDACC__
void myfunc () {
...generic code...
}
#else
__device__ void myfunc () {
device_only_func();
}
#endif
I'm sorry, @timgrant , this is the original way you …
=> Refactor fmath.h for Cuda.

src/libOpenImageIO/CMakeLists.txt
Expand the set of files to all the imagebufalgo_*.cpp, which are the most likely files to need it because they tend to have template expansion for big sets of data type pairings.
Does anybody know if there is an advantage to limiting it to just the files that most need it? Or is it better to make it totally foolproof by using /bigobj for all our modules on Windows?
=> More care with /bigobj on Windows

src/include/OpenImageIO/color.h, src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/hash.h
I have added ``HOSTDEVICE`` decorators to hash.h to pave the way for using the OSL noise generation functions on CUDA devices.
Other minor changes include guarding some SIMD-enabled color conversion functions in color.h, and making use of the ``__funnelshift`` intrinsic in fmath.h.
No explicit tests added. Indirect testing through exercising the noise functions in OSL.
=> Refactor hash.h for CUDA

src/tiff.imageio/tiffinput.cpp
Just noticed this while doing other things. Nobody has reported a problem, but it's clear to me that if people were using the special "give me the unassociated values" attribute, and reading multiple tiles, this would be using the wrong dimensions for the buffer.
=> Bug fix: wrong dimensions for premult in TIFFInput::read_tiles

src/libtexture/texture3d.cpp, src/libtexture/texturesys.cpp
We realized that for the error condition of the optional "subimage"
specifying a nonexistant subimage would issue an error and return
without writing any values into the location of the color result.
The proposed patch treats the nonexistant-subimage case just like we
always treated the nonexistant-texture case: issue an error and store
the "fill" color in the result, unless the "missingcolor" optional
parameter is supplied, in which case return the missingcolor and do
not issue an error.
=> texture()/texture3d() -- don't let subimage error be nondeterministic

CMakeLists.txt, src/build-scripts/install_test_images.bash, src/tiff.imageio/tiffinput.cpp
The recent patch that greatly speeds up reading whole TIFF images, where we do our own decompression, forgot to consider the case where the TIFF was written with the opposite byte order as the machine reading. Luckily, that doesn't seem to come up frequently in practice, but it's still a critical error when dealing with old TIFF files.
Embarrassingly, I also noticed that our CI tests were not running some of the important TIFF unit tests, due to the libtiff project losing its domain and moving to a new URL a few months back. The download location for the test images in our scripts was therefore inoperative, and I hadn't noticed. This is now fixed as well.
=> TIFF bug fix: don't forget byte swap when we uncompress ourselves

src/tiff.imageio/tiffinput.cpp
Calls to TIFFSetDirectory are redundant if the file was just opened
and you are positioning to the first subdirectory.
Yet, libtiff seems not to notice that, and will happily repeat a bunch
of the header reading that it already did for the TIFFOpen.
So making sure that we only call TIFFSetDirectory when we need to
actually change the current subimage, saves some work (and in fact
can approximately double the speed of reading the header).
=> TIFF header read speedup

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
MSVC gets in a huff if you pass simd types by value, because it can't guarantee alignment.
Fixes #1932
=> SIMD Fixes for 32 bit windows builds

src/ffmpeg.imageio/ffmpeginput.cpp
There are some intermediate checkins between ffmpeg 3.4 and 4.0 where my previous attempt at this broke. So switch to the new symbol as soon as it was introduced (a while back). Fixes #1935
=> ffmpeg: more precise time for switching symbol to AV_CODEC_CAP_DELAY

src/libtexture/imagecache.cpp
I didn't realize that the prior number I picked inadvertently included
a 4.9 version that did not in fact support this feature.
Changing to the new value will not have any more "false positives" (error
by incorrectly thinking the feature is present), but does make a "false
negative" (avoid the feature even though it's supported) for gcc 5 and
gcc < 6.2, even though it would work there. That will still behave
correctly, though at a very slight performance penalty, but VFXPlatform
skips from gcc 4.8 to gcc 6.3, thus leapfrogging over those false
negative cases. So I'm going to not care that we get less than maximal
performance from some compiler+library versions that we are unlikely to
use.
=> Adjust __GLIBCXX__ test guarding use of std::atomic_load(ptr)

.travis.yml, src/libOpenImageIO/CMakeLists.txt
This had been broken for a while, I guess we stopped testing the EMBEDPLUGINS=0 case (i.e. building each format reader/writer as a separate DSO/DLL instead of compiling them all into the main libOpenImageIO library). This is still an important case to test, since it verifies that it's still easy to supply run-time / site-specific / custom format-reading functionality as dynamic libraries.
The only thing that was really broken was where certain include files were found. Easy to fix. Add the EMBEDPLUGINS=0 to one of the Travis test cases to be sure we don't break again.
=> Fixes to un-break the EMBEDPLUGINS=0 build

src/openexr.imageio/exrinput.cpp
We already were careful when opening the file to use the
OpenEXRInputStream to ensure proper UTF-8 filename handling.
But valid_file() used Imf::isOpenExrFile, which is not careful enough.
So we instead switch to making an IStream and then calling the version
of isOpenExrFile that takes the stream. Should be correct.
=> OpenEXR better UTF-8 filename support

src/libutil/filesystem.cpp
* unique_path() and temp_directory() were not properly handling UTF-8
results on Windows.
* A whole lot of `#if` cleanup by adding u8path and pathstr functions.
=> Filesystem UTF-8 cleanup

src/python/py_imagebuf.cpp, src/python/py_imagebufalgo.cpp, src/python/py_oiio.h
=> Avoid warning from pybind11 vs Python.h interaction

src/include/OpenImageIO/fmath.h
The rational approximation used here had maximum error at s=1.0. This meant that due to the argument reduction changing from x to 1/x at this point, a discontinuity could be observed.
I recalculated better coefficients such that atan(1.0) is exact (accepting slightly higher error elsewhere).
In my benchmarks, I found this to be still faster that switching to a higher order polynomial.
=> Fix discontinuitity in atan approximations

src/iv/ivgl.cpp
The viewer iv was broken under OS X with QT5. It was not showing the image or responding to user input correctly. This fixes it for me under OS X Sierra
=> Fix iv on OS X with QT5

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/oiiotool/oiiotool.cpp, src/python/py_imagebuf.cpp, testsuite/python-imagebuf/ref/out-alt-python3.txt, testsuite/python-imagebuf/ref/out-alt.txt, testsuite/python-imagebuf/ref/out-python3.txt, testsuite/python-imagebuf/ref/out.txt, testsuite/python-imagebuf/src/test_imagebuf.py
We had set_roi_full() to change the display window metadata, needed an
equally easy way to alter the pixel data window origin. (But note that
for pixel data, it's only safe to change the origin with metadata, not
the size, which would change the whole pixel data layout, lead to
reallocations, etc.)
=> ImageBuf::set_origin()

src/doc/imagecache.tex, src/doc/texturesys.tex, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp, src/testtex/testtex.cpp
The existing methods invalidate() and invalidate_all() fully invalidate
everything the IC/TS knows about a file (or all files) -- the specs,
the pixels, etc.
But sometimes you just want to close any currently-open handles, but not
necessarily forget about what you know about those images, or any pixel
tiles in the cache. That wasn't possible before, but this patch adds the
functionality as close(filename) and close_all() methods to both IC and
TS.
One interesting use case that this enables is a render-paint loop:
render();
ts->close_all();
... here, it's ok to modify the texture files ...
ts->invalidate_all (false);
render();
... repeat
The close_all(), performed after the render, closes any open file
handles, which is especially important on Windows where the IC holding
the file open …
=> IC/TS close() and close_all() methods

src/include/OpenImageIO/span.h, src/libutil/array_view_test.cpp
Something exactly like our array_view<> template is coming to standard
C++20, but it's named span<>. Slowly, we will migrate our nomenclature
and behavior to match it exactly, eventually (I assume in the late
2020's) just switching entirely to std.
In this first step, we merely establish a span.h that defines span<> as
a template alias for array_view<>. This will let applications (and our
internals) freely use array_view or span as synonyms. I will even
backport this change to older branches, since it's totally harmless to
existing code that uses array_view.
In a later step (not this patch) in master only, we'll swap those roles,
so that moving forward, span<> will be the "real" template, and
array_view will be the synonym for compatibility with legacy apps.
=> span.h: Work towards the C++20 nomenclature (instead of array_view)

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/python/py_imagebuf.cpp
* Add a 'move' constructor
* Add variety of copy() that returns a copy of *this.
* Add operator=, both copy and move varieties. I has avoided this purposely in the early days, but with C++11 move semantics, I think it's not as unavoidably wasteful as it once was.
=> ImageBuf: tweak copy and assignment

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/python/py_imagebuf.cpp, testsuite/python-imagebuf/src/test_imagebuf.py
(more weekend tinkering)
This avoids the need for separate set_write_format() call if you're only
needing it to affect this one write call. Less clunky this way.
=> ImageBuf: add pixel data type override to write() method

src/python/py_oiio.h, testsuite/python-imageinput/src/test_imageinput.py
Spotted an obvious typo in make_numpy_array.
The manefestation of the bug is that ImageInput.read_scanline would
make the wrong "shape" of the numpy array, mashing all channels of all
pixels in the scanline into a 1D array of values, instead of properly
making it a 2D array of pixels which are each arrays of the channels
within a pixel. (I also had not noticed the presence of that symptom in
the python-imageinput unit test.
=> Fix Python typo bug

src/field3d.imageio/field3d_pvt.h, src/field3d.imageio/field3dinput.cpp, src/field3d.imageio/field3doutput.cpp
Field3DInput::valid_file locked, then called open() which also locked.
How did this ever work? Yet, this was only symptomatic in one internal
renderer test, and only when OIIO was compiled in DEBUG mode.
The simple solution is just to change to a recursive lock. Field3d isn't
an important enough file type to try to be more clever than that.
=> Fix potential field3d mutex deadlock

.travis.yml, INSTALL.md, site/spi/Makefile-bits-arnold, src/cineon.imageio/libcineon/CineonHeader.cpp, src/cineon.imageio/libcineon/CineonHeader.h, src/dpx.imageio/libdpx/DPXHeader.cpp, src/dpx.imageio/libdpx/DPXHeader.h, src/include/OpenImageIO/paramlist.h, src/include/OpenImageIO/texture.h, src/libOpenImageIO/color_ocio.cpp, src/libOpenImageIO/exif.cpp, src/libOpenImageIO/imagebufalgo_draw.cpp, src/libutil/array_view_test.cpp, src/libutil/paramlist.cpp, src/libutil/ustring.cpp, src/raw.imageio/rawinput.cpp, src/testtex/testtex.cpp
Add gcc8 to the TravisCI test matrix.
Fixed a bunch of minor things for all the new warnings that cropped up with gcc8. Many were legit things that were questionable (though asymptomatic). In a few cases, they were clearly false positives and I just disabled the new warnings in the narrowest way I could.
=> Many small fixes for gcc 8.1

.travis.yml, src/cmake/compiler.cmake, src/doc/oiiointro.tex, src/include/OpenImageIO/function_view.h, src/python/py_oiio.h, src/raw.imageio/rawinput.cpp
Add a test to the TravisCI matrix that builds with C++17 using gcc8.
There were a couple minor warnings to fix (including those I found building for C++17 with clang on my Mac), nothing dramatic.
The only significant change was that the implementation of `function_view` gave me all sorts of trouble with C++17, stemming from the fact that C++17 considers 'noexcept' to be part of the function signature for template matching. I looked into alternate implementations and found out that LLVM's `FunctionRef` was extremely similar and worked flawlessly. So I swapped it in, in place of our previous implementation (but keeping our old name, function_view, so there should be no break in source compatibility).
=> Add C++17 to CI tests and fix issues

src/doc/builtinplugins.tex
I had to create an EXR with single scanline zip compression today and I couldn't find how to do it in the documentation. After some searching online I found the `zips` option. 
This patch adds `zips` to the list of compressors in the built in plugin part of the docs.
PS! Apologize for the unnecessary commit. My intentions were good.. 
I have not added any tests for this patch. Neither have I built OIIO with the patch unfortunately.
=> Added "zips" to the list of compressors in the OpenEXR plugin documentation

INSTALL.md, src/cmake/externalpackages.cmake
On older platforms (eg ubuntu 14.04) ffmpeg is detected, so it builds the plugin but the build fail as does not meet the minimum version.
=> [cmake] ffmpeg ensure minimal required version

INSTALL.md, src/build-scripts/install_homebrew_deps.bash
libraw on homebrew just upgraded to the new 0.19.0. This breaks our raw
tests (builds ok, but seems to not find all the metadata). I'm not sure
if this is a bug in 0.19.0, or if the API changed in some way that we need
to change things on our side. But in either case, it's a more lengthy
investigation than I have time for today, so disabling it on OSX Travis
tests seems like the expedient workaround. Libraw (0.15) is still exercised
on the Linux Travis tests.
As soon as I track down the real problems satisfactorally, I'll restore
the tests.
=> Travis: on OSX, don't load libraw from homebrew (temporary)

Makefile, site/spi/Makefile-bits-arnold, src/cmake/compiler.cmake
Add a build-time option to select which std::string ABI to use.
Building with GLIBCXX_USE_CXX11_ABI=1 uses the new (C++11 compliant) ABI,
building with =0 uses the traditional gcc string ABI for compatibility.
This only affects gcc builds.
Also automatically define _GLIBCXX_SANITIZE_VECTOR=1 when compiling for
sanitize mode, it turns on some extra instrumentation to detect running
off the end of a std::vector but still within its allocated capacity.
=> Select gcc string ABI, etc.

.travis.yml
We have a growing matrix of tests, and there is development friction from the fact that every push to a working branch kicks off the whole matrix, many of which exist to test very specialized things that are probably not changed by the vast majority of patches.
TravisCI recently started supporting "conditions" that can let you limit which test cases or stages to run.
I'm proposing that the full test matrix always run when it's:
* a pull request
* a direct push of an updated "master" or "RB" top of tree.
* a nightly cron job (which, also, are only for "master" and certain "RB" branches)
But in other cases -- that is, ordinary work branch pushes while we develop -- there are many tests that don't really need to run every time, and just clog up our Travis queue. So I'm adding the following …
=> Use TravisCI conditions to limit builds

src/include/OpenImageIO/refcnt.h
refcntptr::release() sets the pointer to null and reduces the ref count, returns the original pointer, but does NOT free the object even if the new ref count is 0.
The motivation for this will be in a forthcoming OSL PR.
=> RefCnt enhancement: release()

src/iv/ivmain.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h, src/oiiotool/printinfo.cpp, src/tiff.imageio/tiffinput.cpp
It's an abomination, but it's one we have to sometimes live with.
This patch has several small goodies for people who are forced to
deal with "unpremultiplied" images.
* A variety of fixes to oiiotool --no-autopremult, which turns off the
automatic premultiplication that is ordinaryily done for
unpremultiplied inputs. It was only working for inputs that were
backed by the ImageCache, which excluded small files read directly,
and also excluded --info results (which bypass the cache and to
straight for an ordinary ImageInput).
* iv: add a `--no-autopremult` flag, much like the one for oiiotool.
This makes it easier to use iv to examine the unmodified input values.
* TIFF read: be sure to set an attribute called "tiff:UnaociatedAlpha"
to indicate that the original input was unpremultiplied …
=> Fixes to handle input images with unassociated alpha ("unpremultiplied")

src/libOpenImageIO/imagebuf.cpp
While updating my [Go language bindings](https://github.com/justinfx/openimageigo) to oiio 1.7 compatability, I found that `ImageBuf::contains_roi()` was always returning true. There looked to be a bug where the `roi` input parameter was always being compared against itself instead of the `roi` of the `ImageBuf` instance.
=> Fix ImageBuf::contains_roi always returning true

src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagebuf_test.cpp
Prompted by Justin Israel's patch #1996
... and in the process of making a good unit test, I found a minor bug
in the ImageSpec ctr from an ROI -- the data window was set properly, but
the display window (aka "full roi") got the proper width/height but not
the right origin. Yay unit tests!
=> Unit test for ImageBuf ROI access and roi_contains() and ImageSpec roi access

src/libtexture/imagecache.cpp
Found this bug with valgrind. The `std::atomic` default constructor does not initialize the memory. Therefore this array was not getting properly filled in.
I am not really sure how this didn't cause problems, it could be I am missing something subtle. But the valgrind warning definitely goes away after this fix.
=> Fix uninitialized read within texture system

src/gif.imageio/gifinput.cpp
The GIFInput::read_gif_extension method segfaults when reading a GIF that has a Comment Extension with no Comment Data. I don't know how the problem GIF was generated and unfortunately I can't share it but it seems valid and can be opened without issue in other applications.
Prior to the change OpenImageIO was segfaulting as soon as the image was opened, now it opens without issue.
=> Fix segfault when reading gif with Comment Extension and no Comment Data

src/jpeg.imageio/jpegoutput.cpp
The X_density and Y_density fields in the JPEG header are uint16. We
were botching it if it happened to think the pixel densities were
expressed as values needing > 16 bits. Do some refactoring and handle
this case cleanly.
Fixes #1999
=> JPEG output: more robust handling of "density" outputs.

src/libOpenImageIO/formatspec.cpp
While testing my [Go language bindings](https://github.com/justinfx/openimageigo) against the 1.8 branch, I found that one of my `ImageSpec::erase_attribute` tests was failing when checking the `casesensitive=true` option. Digging into the history it looks like with the addition of the `std::regex` ifdef, a copy-paste error has left the opposite check for the boolean. So you get case-insensitive when you as for case-sensitive. Again this is only when not using boost::regex. 
One other issue I noticed, after fixing this bug, was that the `TypeDesc` is no longer honored when searching for the attribute. Another test that I have fails on this assumption, but I am not sure if this was the intended new behavior. My test tries to set an int, and then erase it as a float. Previously it will not …
=> Fix ImageSpec::erase_attribute using backwards logic for casesensitive

.travis.yml, appveyor.yml, site/spi/Makefile-bits-arnold, site/spi/Makefile-bits-spcomp2, src/build-scripts/build_openexr.bash
No longer need to build an lgritz private one, since 2.3.0 has some
fixes we needed for gcc7 and C++17 compatibility.
Also move the OpenEXR download and installation into the ext/ subdir
where we put other build dependencies.
For SPI, change the site/Makefile-bits files so that OPENEXR_HOME env
variable can override the default system install of OpenEXR (makes it
easier for me to test custom builds).
=> For Travis Linux, build against OpenEXR 2.3.0

src/cmake/modules/FindOpenEXR.cmake
Inspired by the FindFFmpeg.cmake and FindLibRaw.cmake files I added similar use of pkgconfig to locate IlmBase and OpenEXR include directories.
The potentially found paths are appended to `GENERIC_INCLUDE_PATHS` respecting the search order that was before.
I have not added any tests, but it seems to build the way it should.
=> Use pkgconfig in FindOpenEXR.cmake if available

src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texture3d.cpp
What happens when texture3d is called on a point? There was a special
back door for Field3d, but this didn't generalize well. For example, we
want to support texture3d lookups from OpenVDB files (coming soon under
a separate PR -- this is a necessary prelude).
This patch:
* Makes each ImageCacheFile::SubimageInfo contain a unique_ptr to a 4x4
matrix (so it doesn't use as much space except when needed, which is a
small minority of all texture files). This also moves (commented-out)
matrix info for (unsupported) shadow maps from per-file to per-subimage.
* If reading the spec for that subimage yields a "worldtocamera" or
"worldtolocal" matrix metada, we allocate the space and stash the
matrix there.
* The texture3d() call looks for the matrix, and if found, uses it to
transform the input …
=> Reorganize how texture3d transforms points to local space of the volume.

src/libutil/thread.cpp
More details, including a hopefully easy repro that works on OSX, are in #1991.
The way this fix works is that instead of detaching threads, which by bad luck might stay running and access thread pool data after the thread pool is destroyed, we stay attached and move the threads into a list of threads that we have to explicitly wait on to be finished, just like we already do for the active threads.
The crash is very hard to reproduce without adding a 1s sleep, and even then I suspect the 1s worked for me because my process runs in under 1s. Maybe you'll need to sleep for at least as long as it takes to go from lowering the number of threads to terminating the process so that we can be assured the detached threads survive to the end?
- [ x] I have read the [contribution …
=> Fixes rare crash when lowering number of threads

src/include/OpenImageIO/imagecache.h, src/libOpenImageIO/imagecache_test.cpp, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/null.imageio/nullimageio.cpp, testsuite/null/ref/out.txt, testsuite/null/run.py
The point of this feature is that your app has a buffer of pixels, and
you want the IC or TextureSystem to use that buffer directly, without
copying the texels or owning the memory. It should also not count the
memory against the limits of the cache.
See imagecache_test.cpp, the test I added as text_app_buffer() which
pretty much spells out how to do it from the app point of view.
From an API standpoint, all that changes is an optional argument to
add_tile that lets you disable the copy.
You need to make it a tile of an image in the cache, though, and the
obvious no-drama choice is just to use a "null" ImageInput as a
placeholder.  In the process, I noticed two helpful enhancement I could
make to the null ImageInput better:
1. Make sure that passing a "config" spec results in the right …
=> ImageCache: add a way to add_tile without a pixel copy

src/raw.imageio/rawinput.cpp, testsuite/raw/ref/out-libraw0.18.11.txt, testsuite/raw/ref/out-oldlibraw0.15.txt, testsuite/raw/ref/out.txt
We were previously reporting "oiio:ColorSpace" for raw images always as "linear", but that's not really how the underlying libraw operates.  It converts to one of several color spaces as part of the debayering process (by default, sRGB), so make sure to report back the correct one, which should be the one you ask for. Also, no need to set the "raw:ColorSpace" attribute, that doesn't really tell you anything useful (it just repeats back the hint you asked for, but that's the same as the "oiio:ColorSpace").
=> raw DSLR image read improvements to color space identification.

src/include/OpenImageIO/paramlist.h
It should be a no-op for self-assignment.
=> Fix possibly broken operator= for ParamValue.

src/doc/texturesys.tex, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/imagecache.cpp, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp
* Add an optional argument to TS::create() that lets the caller directly
supply a pointer to an IC (which will not be freed when the TS destroys --
it's owned by the caller).
* Add a TextureSystem::imagecache() method that returns a blind,
non-owning pointer to the underlying IC.
* Clean up the 'destroy' methods, which previously for the sake of not
breaking compatibility mid-release had two separate varieties, but
clearly they can be one signature with an optional argument.
=> ImageCache/TextureSystem create/destroy adjustment

src/include/OpenImageIO/imagecache.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texturesys.cpp
It is split in two commits, see the log. First one fixes a double free bug when the imagecache is provided to the texture system. The second is an option to make add_file() replace any existing entries. Useful for providing user buffers as textures that have already been queried (for instance to get a handle).
=> Fix a double free of imagecache and add a replace mode for add_file()

src/cmake/externalpackages.cmake
I was finding crashes with certain combinations of OIIO, Python 3.6.x, and NumPy/PyTorch -- crashes upon import of either oiio or torch (whichever was second). Seems to be all better when I upgrade pybind to 2.2.4, I guess we were using one that was a year old.
=> Bump pybind11 version from 2.2.1 to 2.2.4

src/doc/builtinplugins.tex, src/doc/openimageio.tex, src/raw.imageio/rawinput.cpp
Using a new "raw:aber" (float[2]) input config attribute.
Fixes #2029
Example command line to see this in action:
oiiotool -iconfig:type="float[2]" "raw:aber" "1.01,0.99" ../oiio-images/raw/RAW_OLYMPUS_E3.ORF  -o out.exr
=> RAW: control of libraw's correction for chromatic aberration

src/doc/imageioapi.tex, src/doc/openimageio.tex, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageio_pvt.h.in
* ImageBuf: more careful tracking of allocations, print alloc/free/total  messages when "debug" attrib (or env OPENIMAGEIO_DEBUG) > 1.
* Change interpretation of the debug attribute so that 1 is ordinary debug, values > 1 are extra debugging for developers.
* Add oiio query for process resident memory in MB (this is helpful  for Python scripts that want to check how each OIIO call they make  might have changed the overall memory footprint).
* Add docs for the "hw:simd" and "oiio:simd" attribute -- not changed here, just happened to notice they were undocumented.
=> Improved memory-use debugging

src/libOpenImageIO/imageio.cpp, src/tiff.imageio/tiffinput.cpp
If read_scanlines (et al) was called with the 'format' parameter as
TypeUnknown -- which is supposed to mean "use the native format" -- would
accidentally and silently fall through the switch statement inside
OIIO::premult(), causing it to do nothing.
If called with an explicit type, it all worked find. Subtle to track down.
The particular symptom was that if you were calling ImageBuf::read()
with `force=true` but relying on the default `convert` value of UNKNOWN
(meaning, no conversion, stay in native format), it would trigger this
bug and neglect to premultiply the unassociated colors.
=> Fix for TIFF with unassociated alpha

src/raw.imageio/rawinput.cpp
=> [RAW] fix TimeStamp typo in exif

src/null.imageio/nullimageio.cpp
For the "null" reader, we were clobbering any configuration hints about
the "full" (i.e. "display window") size parameters. This had bad effects
when using a fake "null" image along with ImageCache::add_file() in
order to set up an in-memory buffer that behaves like a texture, if that
buffer was a crop region or had overscan.
=> null input reader: be more careful with "full" (display) size

src/libutil/thread.cpp
Prevent deadlock from illegal communication with already terminated threads when global shared thread_pool is being destroyed during DLL unloading. This scenario is detected by checking native threads status.
Fix #1795 
Tested on Windows 7 with Visual Studio 2017. 
Fixes the deadlock issue for global static thread_pool destruction and does not modify the current behavior when thread_pool is used as a non-static variable.
=> Safer thread_pool destruction using native threads status (Windows)

src/libOpenImageIO/maketexture.cpp, src/maketx/maketx.cpp, src/oiiotool/oiiotool.cpp
This option prevents situations where the bumpslopes exporter fails to detect an input bump format as an height map. The typical situation is a 3 channels RGB height map we would expect to be monochromatic (R=G=B for all pixels) but having subtle color variations introduced by a texture publication process (typically a precision or rounding error). In such situation the exporter will automatically interpret the bump map as a false normal map, resulting in a corrupted texture output.
The bumpformat option allows the user to bypass the automatic detection and manually specify the input bump format.
=> Add a bumpformat option for the bumpslopes exporter

src/include/OpenImageIO/unittest.h
This causes the color only to be used to the terminal, not incorrectly
injected when the output is redirected to a file.
=> Make unit test errors respect whether stdout is a terminal

CHANGES.md, src/include/OpenImageIO/ustring.h, src/libtexture/imagecache.cpp, src/libtexture/texture3d.cpp, src/libtexture/texturesys.cpp
As pointed out by Thiago Ize and John Haddon (but unfortunately not
heard by me until literally years later), this is error prone because
there are times when a ustring is converted to an int/bool in unexpected
situations. It even led to verifiable errors in OSL that I only
discovered after commenting out this operator to see what would happen.
Neither std::string nor std::string_view have this operator, bolstering
Thiago & John's arguments.
So we are removing it from OIIO 2.0. Hopefully this won't break too many
people's apps that happen to make use of ustring. The fix is simple, just
change:
if (myustring)
to
if (! myustring.empty())
Because this is a back-compatibility break, this change will only be merged into master, NOT backported to any current release branches.
=> Remove ustring::operator int()

src/cmake/modules/FindOpenVDB.cmake, src/openvdb.imageio/openvdbinput.cpp
VDB library exposes a magic one can test against, so use this before initializing the library.
CMake fixes for custom VDB locations in release mode.
=> VDB tweaks for library initialization and CMake

src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/simd.h, src/libutil/fmath_test.cpp, src/oiiotool/oiiotool.cpp, src/oiiotool/printinfo.cpp
We found that certain 'half' pixel values that involved "denormalized"
values (very close to zero) were inexplicably getting squashed to exact
0.0f in some circumstances but not others. Long story short, we traced
this to an older version of libopenjpeg (in turn pulled in by ffmpeg's
libraries) that set the x86 DENORMALS_ZERO_MODE upon its DSO load, and
left it like that, which is a truly terrible thing to do because it can
inject math bugs elsewhere into the app, even in parts that seemingly
have nothing to do with decoding jpeg-2000 images.
The code is only symptomatic in OIIO when we build with SSE support but
not with f16c instruction support -- the symptom is specific to the
series of ops we use to accelerate the half->float conversion with SSE
but without f16c. There could be other …
=> Fixes related to debugging half -> float conversion

src/doc/imagebufalgo.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/imagebufalgo_compare.cpp, src/libOpenImageIO/imagebufalgo_test.cpp, src/python/py_imagebufalgo.cpp
A situation came up recently that made me realize it would be good to
have a handy way of knowing whether an image is *almost* a constant
color (e.g., allow the channels in a pixel to differ within some
expected threshold and still be considered monochrome).
So this patch proposes to add an optional `threshold` parameter to
these three IBA functions. The default is 0.0, which is identical to
the old behavior and checks for exact matches only.
While I was in there, I noticed that these three functions were not
previously parallelized/threaded, so I added that as well. That should
speed them up considerably when running on multicore machines.
=> Add thresholds to IBA::isConstantColor, isConstantChannel, isMonochrome

src/oiiotool/printinfo.cpp
As mentioned in #2054, windows paths have backslashes which are getting removed by `oiiotool --info`.  This fix solves the filename issue and I verified still works with the maketx "Software" metadata which has backslashed filenames but does not the unescaping to be skipped.
I have not run the testsuite nor made a test.
=> fix oiiotool --info windows_path

src/cmake/modules/FindOpenEXR.cmake
Detecting the OpenEXR version by parsing a C header can be unreliable.  Since
we already use pkg-config to detect the presence of the library, we can also
use the version number it gives us, if available, and only resort to parsing
the header file if that failed.
See-Also: https://bugs.gentoo.org/668412
Fixes: ec4f679cd7ba175a5470a6198c07ebc6780f4c29
See commit message.  I suggest to backport this to branch RB-1.8.
I applied this patch to release 1.8.16 and successfully compiled a Gentoo package with it.
- N/A
- N/A
- N/A
=> Fix FindOpenEXR.cmake to use version detected by pkg-config, if available

.clang-format, .travis.yml, Makefile, src/build-scripts/install_homebrew_deps.bash, src/cmake/compiler.cmake
clang-format is a part of the LLVM/Clang compiler suite that will
reformat your code -- but much better than most code reformatters,
because this one is based on a compiler toolkit and is working on the
fully understood AST, not just text.
The idea here is that we give up a little bit of individual creativity
in code formatting, in exchange for every pull request trivially being
able to conform to the house style and never having to go through
multiple rounds of PR edits for formatting issues, nor ever have any
squabbles about it. I know that nobody will be 100% happy with the
require formatting (even me), but I think if we can make everybody 80%
happy and avoid those other problems forever after, it's worth it.
People I respect running othe projects consistently swear that adopting …
=> Add a .clang-format file and a 'make clang-format' target

src/doc/imageioapi.tex, src/libOpenImageIO/formatspec.cpp, src/libutil/paramlist.cpp, src/libutil/typedesc.cpp, src/oiiotool/oiiotool.cpp, testsuite/dpx/ref/out.txt, testsuite/oiiotool/ref/out.txt, testsuite/oiiotool/run.py, testsuite/rational/ref/out.txt
1. Allow embedded single or double quotes to group arbitrary text in metadata name. This solves the problem that the default parsing of a metadata name in the expression syntax uses "C identifier" rules. For example, suppose somebody has put a metadata attribute in an exr file named "foo/bar". If you do:
oiiotool file.exr -echo "{TOP.foo/bar}"
it will be wrong, thinking that it's looking up TOP.foo ("foo" attribute, which doesn't exist) and dividing by "bar", which isn't a value it knows. Instead, we now allow
oiiotool file.exr -echo "{TOP.'foo/bar'}"
It's not pretty, but it allows arbitrary strings to be used as metadata lookups, like "foo/bar" or "foo.bar" or other ill-advised names. (Oh, and for that matter, it was hard to retrieve "foo:bar", which we use all the time, oops. Now it is …
=> oiiotool expression evaluation enhancements

src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h, src/oiiotool/printinfo.cpp
Use of variadic templates cleans up a lot of awkward format calls in the
middle of error/warning calls.
=> oiiotool error/warning cleanup

src/dpx.imageio/dpxinput.cpp, src/dpx.imageio/dpxoutput.cpp, src/dpx.imageio/libdpx/DPXHeader.cpp, src/dpx.imageio/libdpx/DPXStream.h, src/dpx.imageio/libdpx/OutStream.cpp, src/dpx.imageio/libdpx/Writer.cpp, src/dpx.imageio/libdpx/WriterInternal.h, src/oiiotool/oiiotool.cpp
It was reported that if you filled a disk while writing a DPX file, no
errors would be reported, just leaving a corrupted file. (Admittedly,
filling disk volumes is not something I had thoroughly tested.)
The problem turned out to be threefold:
First, inside the DPX library (which was an imported project from
Patrick Palmer, which to the best of my knowledge is no longer actively
maintained outside of OIIO), the underlying OutStream class was used
incorrectly throughout its own library -- in particular, the Write()
method returned the number of bytes correctly written, but the return
results were almost always used incorrectly by merely checking != 0 (as
if it was a bool return for success, when in fact it should check for
any value != the number of bytes being requested to write).
To …
=> DPX: catch write errors

src/doc/builtinplugins.tex, src/dpx.imageio/dpxinput.cpp, src/dpx.imageio/dpxoutput.cpp
I noticed that an open() configuration hint that causes non-RGB color
channels (such as YCbCr) to not get auto-translated to RGB was
implemented in three different plugins, but not all with the same
name. Settle on "oiio:RawColor" for all of them, and also update the
docs accordingly.
Also a little bit of variable renaming in the DPX plugin.
=> Documentation and config parameter naming conventions

INSTALL.md, src/include/OpenImageIO/platform.h
We think that as a practical matter, this has been the case for a long
time. But the documentation didn't keep up.
=> Formally bump MSVS minimum to 2015

src/include/CMakeLists.txt, src/include/OpenImageIO/oiioversion.h.in, src/include/OpenImageIO/platform.h
I had not correctly understood that __has_attribute is specifically for
GCC `__attribute__((attr))` things, and `__has_cpp_attribute` is the new
C++20 test for standard `[[attr]]` style attributes. Fix up that use.
Also get rid of `__has_builtin` and `__has_feature`, those are gcc only,
not the way the standard works, and we don't use it anywhere.
Some other very minor fixes related to discerning which C++ standard
we're using.
=> Fix __has_attribute vs __has_cpp_attribute and other C++ std things

src/include/OpenImageIO/SHA1.h, src/rla.imageio/rlaoutput.cpp
snprintf is a C++11 feature. No need for Windows to try to substitute
_snprintf, which in any case didn't behave quite the same (didn't add a
terminating null character in the case where the alotted space will
filled and the string had to truncate).
=> All platforms can rely on std::snprintf now.

src/libtexture/imagecache.cpp
The m_fingerprint key is supposed to be the hash, but we were searching by filename. End result is that no fingerprints were ever removed from the m_fingerprint container. This results in crashes later on if OIIO thinks a duplicate file already exists and so rather than read it in, it tries to use the now non-existent data.
=> m_fingerprint key is the hash, not the filename.

src/libutil/strutil.cpp
I know there's a comment about vsnprintf not working properly on Windows and old linux, but that's no longer the case.  VS2015, along with linux and OSX all return -1 when there's an encoding error. Otherwise they all return the full size.
See: https://msdn.microsoft.com/en-us/library/1kt27hek.aspx and http://www.cplusplus.com/reference/cstdio/vsnprintf/.
This means that on encoding error we'll always get -1 and OIIO will keep doubling the buffer size until we run out of memory and crash.
=> vsnprintf only returns -1 on encoding error

src/doc/imagebufalgo.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebufalgo.h, src/python/py_imagebufalgo.cpp
It came to my attention that IBA.ociodisplay (and also it turns out
ociolook and colorconvert) have parameters named 'from', which it turns
out that if you use the `name=value` named argument syntax in Python
will actually be a syntax error because 'from' is a reserved word!
Rename that parameter 'fromspace', and to be symmetric, also rename
'to' to 'tospace'. And do the same in C++ bindings so that they match.
=> Python: can't use 'from' as a parameter name -- it's a reserved word!

CHANGES.md, src/gif.imageio/gifoutput.cpp, src/include/OpenImageIO/imageio.h, src/libOpenImageIO/imagebuf.cpp, src/libOpenImageIO/imagebufalgo_copy.cpp, src/libOpenImageIO/imageinput.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/imageoutput.cpp
`convert_image()` and `parallel_convert_image()` had alpha_channel and
z_channel parameters that weren't actually used. I don't even remember
why they were present; I think I imagined that certain conversions might
dither the color channels or something and need to know not to do it to
these channels. But in any case, they were unused, so remove the
clutter.
=> Remove unused channel arguments from convert_image()

CHANGES.md, INSTALL.md, src/cmake/modules/FindOpenCV.cmake, src/doc/imagebufalgo.tex, src/include/OpenImageIO/imagebufalgo.h, src/libOpenImageIO/imagebufalgo_opencv.cpp, src/libOpenImageIO/imagebufalgo_test.cpp, src/libOpenImageIO/imageio_pvt.h.in, src/oiiotool/oiiotool.cpp
Should now build against OpenCV 2.x, 3.x, and 4.x. (Note that 4.x was just released days ago.)
Added more modern from_OpenCV and to_OpenCV, converting ImageBuf <-> cv::Mat, and taking the common ROI and nthreads parameters that we use for the rest of IBA.  Deprecate the old IplImage-based functions, which is an OpenCV 1.x thing.
Add a test of ImageBuf -> cv::Mat -> ImageBuf round trip to make sure it works.
Fixes #2087
=> Modernize OpenCV support

.travis.yml, src/build-scripts/build_ocio.bash
We only need the OCIO libraries, can exclude building binary utilities, python and java bindings, docs, etc., to reduce the time needed to build OCIO and thus shave a minute or so off of every Travis test.
=> Make Travis build OCIO faster, only build the parts we need

src/python/py_oiio.cpp
Had overlooked this.
Also fixed a couple spots where we should have used PY_STR to make
the right kind of python 2/3 type.
=> python: define __version__ for the module

.clang-tidy, .travis.yml, site/spi/Makefile-bits-arnold, src/build-scripts/install_homebrew_deps.bash, src/cmake/compiler.cmake
Clang-tidy is part of clang tooling that's a static analyzer of
everything from "unsafe" code that violates security guidelines, to
stylistic fixes.  There are dozens and dozens of tests. Initially we are
just enabling some basic security and correctness tests. Will add more
later.
All you need to do to run it is
make CLANG_TIDY=1
Or if running cmake directly, use -DCLANG_TIDY=1
Warning: it is a long compile.
Set up a Travis test to run clang-tidy for static analysis. But after
much trial and error, I just couldn't get it to run in the 50 minutes
that Travis allows. So for now it's disabled. But if we ever have a CI
solution that executes faster or has longer time limits, I would love to
do a full static analysis on every PR. For now, I will have to be
content running it by hand on my own …
=> Cleanup and refinement of our "clang-tidy" pipeline.

src/libOpenImageIO/imagebufalgo_channels.cpp
When the result image was uninitialized, it previously forced it to
be a float image result. Now we make it use our usual type_merge logic.
=> IBA::channel_append(): improve result data type choice

src/doc/oiiotool.tex, src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h, testsuite/oiiotool/ref/out.txt, testsuite/oiiotool/run.py
Because what if some loon has curly braces in a filename? It must be
rare because nobody has come across this problem in the years since
OIIO 1.6 added expression evaluation. But it happened today!
So you can do this:
oiiotool -echo {3+4} -evaloff -echo {1+1} -evalon -echo {8*2}
And you will see ouput
7
{1+1}
16
=> oiiotool: -evaloff -evalon to temporarily disable expression evaluation.

src/hdr.imageio/hdrinput.cpp, src/hdr.imageio/hdroutput.cpp, src/hdr.imageio/rgbe.cpp, src/hdr.imageio/rgbe.h, src/jpeg.imageio/jpegoutput.cpp, src/libutil/SHA1.cpp
Use of clang-tidy found several instances of "unsafe" string copy or concatenation -- using functions that don't take a buffer length.
In truth, we humans know that these were probably fine in their context, but it's true that those unsafe string functions should be avoided and it's desirable to get clean static analysis on all the security-related tests.
It's worth noting that these changes in rgba.{h,cpp} diverge us from the original sources (they were imported from code by Greg Ward and Bruce Walter). I usually prefer that when we import entire modules of code from elsewhere, we don't make any changes at all, or even reformat to our conventions, so that we can easily integrate future improvements to the upstream sources. But after mulling this over, I think that in this case, it's not …
=> Fix instances of possibly unsafe string copying

src/png.imageio/png_pvt.h
Exceptions are better than setjmp (for various code safety reasons), but that's how libpng does it, so what can you do? At least mark them so that static analyzer doesn't complain.
=> Mark setjmp exceptions to clang-tidy cert-err52-cpp test

src/include/OpenImageIO/benchmark.h
=> Resolve conflict on some platforms where 'inline' and '__optnone__' are incompatible

src/include/OpenImageIO/strided_ptr.h
This is a very small nit to pick, but pre-increment and pre-decrement is
supposed to return a ref, not a const ref.
=> strided_ptr: fix subtly incorrect semantics of increment/decrement

src/libutil/typedesc.cpp, src/python/py_imagespec.cpp, src/python/py_paramvalue.cpp, testsuite/python-imagebuf/src/test_imagebuf.py
The most important change is that we were missing the `__iter__` method.
That was preventing proper iteration over the entries in a
ParamValueList (you could still iterate over the length and index like
an array to retrieve the entries). I did some other cleanup as well, to
conform to the pybind11 examples that handle similar cases.  Also added
a `copy` method to ImageSpec, which it was lacking.
Iterating still seems to fail for me on OSX, only for some image files,
dumps core after visiting the last item in the list (I guess, as it
iterates past the end).  Works on Linux, works on TravisCI (both Linux
and OSX).  I've struggled with this for a few days and I'm not sure what
to try next.  Maybe the problem is sensitive to particular python
versions?
In any case, if you can't get this to …
=> Clean up Python ability to iterate over ParamValueList

src/cineon.imageio/libcineon/CineonHeader.cpp, src/fits.imageio/fitsinput.cpp, src/fits.imageio/fitsoutput.cpp, src/include/OpenImageIO/pugixml.cpp, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imageio.cpp, src/libOpenImageIO/xmp.cpp, src/libutil/argparse.cpp, src/libutil/strutil_test.cpp, src/oiiotool/oiiotool.cpp, src/rla.imageio/rlaoutput.cpp, src/socket.imageio/socketinput.cpp
atoi/atof are frowned upon because they don't have ways to report errors, so are typically flagged as unsafe by static analysis, they have the "pipe-fitting" issue of taking only a `const char*`, and for atof in particular can have is behavior changed by the system's current locale. Instead, we prefer our Strutil::stoi and stof which take string_view and are guaranteed locale-independent.
There are just a couple places where we keep the old functions -- one is pugixml (because it's an import and we don't want to diverge from the upstream source), and the other is in strutil_test where we are specifically trying to benchmark our functions against atoi/atof (and so therefore must call them). In these instances, we at least mark them as exceptions for the static analyzer to not complain …
=> Change remaining atoi/atof to use Strutil::stoi/stof

src/include/OpenImageIO/strutil.h, src/include/OpenImageIO/timer.h, src/libutil/sysutil.cpp, src/libutil/thread.cpp
Since <windows.h> is included in platform.h, and with great care about
certain symbols being defined beforehand (such as `WIN32_LEAN_AND_MEAN`
and `NOMINMAX`), rely on that one and eliminate other places where we
may include windows.h. This ensures that we don't forget to define those
symbols in other places or get confused by include order.
=> Minor fixups of including windows.h

src/doc/imageioapi.tex, src/doc/openimageio.tex, src/libOpenImageIO/formatspec.cpp, src/libOpenImageIO/imagespec_test.cpp, src/libtexture/imagecache.cpp
These are "pseudo-attributes", they aren't metadata themselves as we store them in an ImageSpec, but
aggreagate from x,y,z,width,height,depth (and the full_ versions). The "datawindow" and "displaywindow" are OpenEXR nomenclature, but it's likely that people will want to refer to them that way.
Also, minor fix to `ImageCache::get_image_info` and `TextureSystem::get_texture_info`, to make the right kind of ImageSpec::find call to retrieve the pseudo-attributes.
=> Allow ImageSpec::find_attribute of "datawindow" and "displaywindow"

appveyor.yml
Get rid of much cruft, install all dependencies with vcpkg. Super easy.
No messing with finding nuget packages and then weeping over their
oddities. And now we have a lot more optional dependencies in place,
which means we're building more of the OIIO code base (fewer parts
disabled for lack of deps), therefore more code coverage in the windows
test build.
There's a trick to this -- it can't actually build all these packages
from source within the 1 core hour it's allotted. It all depends on the
run-to-run caching that leaves the built vcpkg packages in place, and I
had to build it up a few packages at a time.
=> Appveyor overhaul

src/include/OpenImageIO/string_view.h, src/libutil/strutil_test.cpp
We already supported the position parameter for the character-based
versions, but not the string-based versions.
=> string_view: add pos parameter to find_first_of/find_last_of

src/libOpenImageIO/imageinput.cpp
read_tiles was calling all errors "no support for format", but that's
really weird. If it's a bad tile read, the error will already have
been set by the underlying read_native_tiles.
=> Get rid of confusing/bogus ImageInput error

src/tiff.imageio/tiffinput.cpp
JPEG compression was one of the cases where we fell back on the TIFFRGBAImage interface of libtiff. This worked for some JPEG images, but crashed on others, inside the TIFF library. Never did figure out why.
But do we really need to to use the RGBAImage interface?  Turns out, no! At least, not if it's still a spectral RGB image.
So just using the regular interface for ordinary RGB JPEG-compressed TIFF images is fine, fixes the problem.
Also improved an error message while I was in there.
=> Fix broken TIFF with JPEG compression

src/oiiotool/printinfo.cpp
Sloppiness printed uint8 vals as characters themselves intead of
integer values.
=> Fix oiiotool --dumpdata for uint8 pixels

src/tiff.imageio/tiffinput.cpp
If you are reading a TIFF file with unassociated alpha, but you have
called the variety of read_scanlines or read_tiles that let you restrict
the channel range and your range doesn't include the alpha channel, the
automatic premult will be using bogus values. Oh brother.
Solution is to skip the premult if the alpha channel was not available.
Note that this makes it possible for read_scanlines() of channels 0-2 to
NOT MATCH the first three channels if you had read all 4 channels.
Seems odd, but what else can we expect? You get what you deserve if you
purposely exclude the alpha channel from the read, but it's an
unassociated alpha file that needs the alpha for the premult.
Also noticed that read_scanlines was not quite as careful with
thread safety as it should be, accessing m_spec outside …
=> Fix subtle TIFF read problems with unassociated + channel ranges

src/libOpenImageIO/imagebufalgo_xform.cpp
They had previously outright rejected if the destination and source
images didn't have the same number of channels.
But actually, it doesn't matter. If they differ, it will only operate on
the minimum channel count in the two images. If dst has more channels
than src, that's fine, it just won't fill in the "missing" channels.  If
dst has fewer channels than src, then that's also fine, and in fact it
is totally reasonable to want to resize an RGBA image into an RGB
buffer, resizing while only copying the first 3 channels.
=> Relax channel restrictions on IBA::resize, fit, resample.

src/python/py_imagebuf.cpp, src/python/py_imageoutput.cpp, src/python/py_oiio.cpp, src/python/py_oiio.h
The underlying decoding of pixel value arrays -- used by some of the
ImageOutput methods and ImageBuf.set_pixels -- threw exceptions when
the pixel array didn't conform to expectations. This led to very
confusing behavior, and crashes if the python program didn't carefully
catch them. Instead of throwing exceptions, bubble up an error message
for the usual OIIO error reporting, so wrongly-shaped pixel data arrays
are treated similarly to other kinds of error.
Also, detect with a better error message cases where user tries to write
scanlines to a tiled file or vice versa -- it was handled well in C++,
but the Python would start by parsing the pixel array, then have a
confusing error that it was the wrong shape, instead of the more clear
error message about using tiles instead of scanlines.
=> Improve Python error reporting for ImageOutput and IB.set_pixels

.travis.yml, src/build-scripts/install_homebrew_deps.bash, src/cmake/compiler.cmake, src/iinfo/iinfo.cpp
Homebrew updated its copy of clang-format several days ago. Something
in it changed formatting rules and caused our builds to break on the
formatting verification test.
This patch changes the way we look for the clang-format binary -- you
can supply a hint about which directory it's in as
`CLANG_FORMAT_EXE_HINT` cmake variable, or an env variable of the same
name, or it will also try to find a clang-format in your LLVM distro if
you have a LLVM_DIRECTORY env variable set.
This lets us more easily lock down the clang-format to the one with llvm,
not separately installed, so it should get changed less frequenty and is
easier to standardize across users and platforms. Currently, then, we're
trying to tie it to clang 7.
=> clang-format fixes

src/openvdb.imageio/openvdbinput.cpp
Changes for fopen on Windows and containing all exceptions that may be thrown.
=> [OpenVDB] Don't allow any exceptions to escape and use Filesystem::fopen

src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/simd.h, src/libtexture/texturesys.cpp
`wrap_periodic_sharedborder_simd` had a `%` that could divide by zero when width=1 (top level MIPmap). It tried to protect about it, but it did so after the fact, so on some platforms the `%0` would create an exception.
Elegant fix required adding scalar and simd function `safe_mod` that protects against this case.
=> Fix possible div-by-0 bug in texturesystem

src/doc/imageioapi.tex, src/include/OpenImageIO/optparser.h, src/libOpenImageIO/imageio.cpp
Akin to how we have `OPENIMAGEIO_IMAGECACHE_OPTIONS` and `OPENIMAGEIO_TEXTURE_OPTIONS`.
`OPENIMAGEIO_TEXTURE_OPTIONS` is a comma-separated list of name=val pairs that upon startup will seed the global options that are usually set by the OIIO::attribute() call.
Along the way, I beefed up the OptParser to be able to handle both single and double quotes equally well. That lets you set an option that is a string, that itself contains quotes.
Also document all of these options -- I realized the PDF docs don't talk about even the existing env variables.
=> Allow env OPENIMAGEIO_OPTIONS to set global OIIO::attribute()

src/doc/imagecache.tex, src/doc/texturesys.tex, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/texture.h, src/libtexture/imagecache.cpp, src/libtexture/imagecache_pvt.h, src/libtexture/texture_pvt.h, src/libtexture/texturesys.cpp, src/oiiotool/oiiotool.cpp, src/python/py_imagecache.cpp
This works the same way as the `force` argument to `invalidate_all()` --
if true, invalidates unconditionally; if false, invalidates only if the
file's modifiation date has changes since the cache first opened it.
The default is true for back compatibility, but probably you will often
want `false`, only invalidating if the file has changed.
=> IC/TS: add optional `force` argument to `invalidate()` method

src/doc/imagebufalgo.tex, src/doc/oiiotool.tex, src/include/OpenImageIO/filter.h, src/libutil/filter.cpp, src/libutil/filter_test.cpp, src/oiiotool/oiiotool.cpp
* Main event: add "nuke-lanczos6" as an alias for our "lanczos3" filter.
(Nuke names it according to the full width, which makes sense but is
different than our more conventional lanczos3 nomenclature. Made the
alias to make it more obvious which to choose if you want to exactly
replicate what Nuke calls lanczos6.)
* Added new flavor of get_filterdesc() that returns a const ref,
instead of copying into a parameter by pointer. (In retrospect, I'm
not even sure why I did it that way.)
* Made `oiiotool --help -v` print the available filters, for handy
reference.
=> Filter selection enhancements

src/cmake/compiler.cmake
* Don't need to condition things on whether they are gcc >= 4.8; gcc 4.8 is the minimum these days.
* Fix some confusion between -Wno-blah and -Wno-error=blah
* Get rid of the misleading-indentation warning suppression, I that now that we use clang-format, we shouldn't have any weird indentation.
=> Clean up warning suppression a bit

src/libtexture/imagecache.cpp
When performing get_image_info() on udim files, we may have to try
out several individual tiles until we find one that exists (the set
is allowed to be sparse). We were not properly suppressing any error
messages set for the missing files, once we hit one that worked.
=> Fix MIA ImageCache errors from missing udim tiles

src/openexr.imageio/exroutput.cpp
dwa? compression fails when saving single channel files with small tile sizes (< 16)
Larry determined in #1844 that the underlying issue is in OpenEXR.
While that gets fixed we should skip dwa compression for the failure cases. This patch replaces dwa compression with the default zip for the failing cases.
=> OpenEXROutput: skip dwa compression for single channel small tile images

CMakeLists.txt, Makefile, site/spi/Makefile-bits-arnold, src/cmake/modules/FindOpenImageIO.cmake, src/libOpenImageIO/CMakeLists.txt, src/libutil/CMakeLists.txt
This patch allows an optional suffix to be specified that will let you
produce something like libOpenImageIO_CIA.so or whatever. Use with
caution, or preferably not at all, if you don't absolutely need it).
Example of how it's used: Suppose you're at a facility that needs (don't
ask why) multiple versions of OpenImageIO to be built. And namespacing
is not enough, because if you have two copies of libOpenImageIO.so, you
can't separately rpath them.
=> Allow optional library name suffix

src/iv/ivgl.h
Defining this symbol turns it off. Somewhere on my list is to remove the
OGL dependency from iv, but this band-aid will help until I get some
free time for that.
=> OSX Mojave gives rude messages about OpenGL being deprecated

src/iv/ivimage.cpp
The sorting makes it a lot easier to compare the lists of metadata of two images.
=> iv info window: sort metadata, like we do for 'oiiotool -info'

src/include/OpenImageIO/errorhandler.h, src/include/OpenImageIO/fmath.h, src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/string_view.h, src/include/OpenImageIO/sysutil.h, src/include/OpenImageIO/thread.h, src/include/OpenImageIO/tiffutils.h, src/include/OpenImageIO/tinyformat.h, src/include/OpenImageIO/typedesc.h, src/include/OpenImageIO/unittest.h, src/include/OpenImageIO/ustring.h, src/libOpenImageIO/imageio.cpp, src/libutil/typedesc.cpp
It shouldn't change anything about how you use these. Just marking a bunch
of things that already didn't/couldn't throw exceptions as 'noexcept'.
There will be more of this moving forward, I'm just getting some basic
classes now.
=> Sprinkle noexcept widely over many of the core utility classes

src/libtexture/imagecache.cpp
When we recently made invalidate(file) have a 'force' parameter, we
botched it by not so forcing a particular call in invalidate_all().
In the line being changed here, we're dealing with a list of files
that definitely need invalidation due to special tests, so once
we've established that, we want to force it.
Pointed out by @ThiagoIze in a post-merge comment in #2133
=> Fix bug in IC::invalidate()

src/include/OpenImageIO/simd.h, src/libutil/simd_test.cpp
Also remove some conditionally-compiled clauses for Ilmbase 1.x. We've
had OpenEXR/Ilmbase 2.0+ as a minimum since OIIO 1.8.
=> simd.h: vec4 * matrix44 multiplication

src/libOpenImageIO/imagebuf.cpp
The unassociated alpha handling setting of the ImageCache was
overriding the setting specific to the ImageBuf itself, for the path
where for "forced" reads bypass the cache. Good intentions to still
honor the IC setting, but IB-specific request should take precedent.
=> IB: Fix bug in propagating unassociated alpha behavior request

src/include/OpenImageIO/strutil.h, src/libOpenImageIO/imagebufalgo.cpp, src/libOpenImageIO/maketexture.cpp, src/libutil/filesystem.cpp, src/libutil/strutil.cpp, src/libutil/strutil_test.cpp, src/oiiotool/imagerec.cpp, src/oiiotool/oiiotool.cpp, src/tiff.imageio/tiffinput.cpp
Certain regex_replace tasks seem to crash on Windows with MSVS's implementation of std::regex.
After considering a more sophisticated test for when we should use boost.regex instead, I instead settled on just replacing the few uses of regex_replace with our own string processing. None were very    sophisticated or truly needed regex functionality.
=> Avoid std::regex_replace

testsuite/runtest.py
Restore its ability to run by hand from inside the
build/PLATFORM/testsuite/TEST directory, which had been lost recently
with some overhaul to the testing scripts.
=> Restore runtest.py ability to run from inside the individual test dir.

src/fits.imageio/fits_pvt.h, src/fits.imageio/fitsinput.cpp, src/fits.imageio/fitsoutput.cpp, testsuite/fits/ref/out.txt, testsuite/fits/run.py
Upon reading FITS specs, I realized that 16 and 32 bit int pixels in
FITS are signed, not unsigned. Also beefed up our support for what
appear to be multi-channel FITS files and other oddities in the
image dimensions.
=> Fixes to FITS file support

site/spi/Makefile-bits, src/cmake/externalpackages.cmake
Non-SPI people can ignore this.
The motivation was to let us switch between several Boost versions,
including a new layout for our local boost install. But I took the
time to do a bunch of cleanup on the spi Makefile-bits, mostly just
regrouping so all the compiler stuff is together, all the python stuff
is together, all the spcomp2 stuff is together.
=> SPI build script revisions, mostly for boost

src/hdr.imageio/rgbe.cpp
Switching the relative order of the is-it-past-the-end test with the whats-the-value test fixes it.
=> Asan-revealed bug touched beyond the bound of allocation

src/jpeg2000.imageio/CMakeLists.txt
Some new unit tests show crashes inside libopenjpeg, but only for
libjpeg<2.0 and only when we build with EMBEDPLUGINS=0 (apparently
it's fine when =1, which is the default, I don't know why).
I have no particular desire to try to track this down, especially
since it requires the combination of an obsolete version of libjpeg,
and a build mode that probably very few people use. So I'm taking the
easy way out: just disable jpeg2000 suppor for this unusual
combination.  If you need EMBEDPLUGINS=0 and care about openjpeg,
upgrade to 2.0.
=> Turn off openjpeg < 2.0 when EMBEDPLUGINS=0 -- buggy

src/heif.imageio/heifinput.cpp, src/include/OpenImageIO/filesystem.h, src/libOpenImageIO/CMakeLists.txt, src/libOpenImageIO/imagebuf_test.cpp, src/libOpenImageIO/imageinout_test.cpp, src/libutil/filesystem.cpp, src/tiff.imageio/tiffoutput.cpp
Added a new unit test, imageinout_test, which for every supported
format writes an image file, reads it back and makes sure it matches
the original.  For formats supporting "ioproxy", it also writes to
memory and makes sure it matches the disk file, and reads from memory
and makes sure it gets the original pixels back. I removed the
hard-coded tests for ioproxy on png and exr, this is more
comprehensive.
Over time, I'll add more to this test. It's a good central place to
test behaviors that should work for all formats.
=> imageinout_test -- test every format

src/libtexture/imagecache_pvt.h
find_file() assumes a non-null thread_info parameter.  But it's called
from get_image_handle in a way that could pass a null pointer. Fix.
Fixes #2179
=> TS: Fix possible nullptr dereference

src/openexr.imageio/exrinput.cpp
It's been reported that V-Ray writes images with this metadata field
present but empty. If you happen to take those images (and their
metadata) and turn them into a multi-part exr, the names all being the
same is problematic. The expedient fix is just to ignore empty names
on input.  Suggested by Chris Allen.
=> exr read: suppress empty string submage name

src/jpeg.imageio/jpeg_pvt.h, src/jpeg.imageio/jpeginput.cpp, src/libutil/filesystem.cpp, testsuite/python-imageinput/src/test_imageinput.py
One consequence is that format readers or writers that relied on
IOFile (such as PNG) would not properly notice certain I/O errors.
=> IOFile: did not properly set m_mode upon open failure.

src/bmp.imageio/bmpoutput.cpp, src/dpx.imageio/dpxoutput.cpp, src/fits.imageio/fitsoutput.cpp, src/gif.imageio/gifoutput.cpp, src/hdr.imageio/hdroutput.cpp, src/ico.imageio/icooutput.cpp, src/iff.imageio/iffoutput.cpp, src/jpeg.imageio/jpegoutput.cpp, src/jpeg2000.imageio/jpeg2000output-v1.cpp, src/jpeg2000.imageio/jpeg2000output.cpp, src/libOpenImageIO/imageinout_test.cpp, src/openexr.imageio/exroutput.cpp, src/png.imageio/pngoutput.cpp, src/pnm.imageio/pnmoutput.cpp, src/rla.imageio/rlaoutput.cpp, src/sgi.imageio/sgioutput.cpp, src/targa.imageio/targaoutput.cpp, src/tiff.imageio/tiffinput.cpp, src/tiff.imageio/tiffoutput.cpp, src/webp.imageio/webpoutput.cpp, src/zfile.imageio/zfile.cpp
Augment imageinout_test to try to write each format to a path that
includes a nonexistant directory (to test generally what happens when
asked to write to a place that doesn't exist or doesn't have write
permissions).
Also a bunch of other refacoring of imageinout_test.
This turned up failures in several format writers:
* DPX crashed (solved with PR 2186)
* HEIF silently failed, not returning any errors for this condition
(solved with PR 2188)
* PNG silently failed (solved with PR 2187)
* JPG silently failed and sometimes crashed (solved with PR 2187)
Also this made me notice that the error messages for open failures
were not uniform across the various file formats, so I picked one
phrasing I liked best and made the others conform.
(Note: to make this test succeed and for reviewers to see …
=> Systematically test output formats for writing unwriteable file

src/libutil/strutil_test.cpp
Especially for CI or user systems that don't have the oddball locale
we used for some testing, make sure the tests complete rather than
crash with local exceptions.
=> strutil_test -- guard against locale exception

src/include/OpenImageIO/argparse.h, src/libutil/CMakeLists.txt, src/libutil/argparse.cpp, src/libutil/argparse_test.cpp
ArgParse had no unit test! Add one.
Also, add a new feature: %1 is like %* (catch-all for all
miscalleneous arguments that aren't dash-led commands and their
following data).  But if %1 is present, its list will receive any
arguments that come BEFORE any other dash-led args, whereas the %*
will receive all the misc args that happen after the first dash-led
arg. If there is no %1, then %* will capture all the misc args
regardless of whether they are before or after the first dash-led arg.
Why is this useful? So you can have programs that require certain
arguments before any options. Like "git add ..." "git rm ...", you
would achieve something like that via:
std::string mode;
std::string files;
static int
callback(int argc, const char* argv[])
{
for (int i = 0; i < argc; i++) …
=> Argparse -- add test, %1

.circleci/config.yml, .travis.yml, CMakeLists.txt, Makefile, src/build-scripts/build_ocio.bash, src/build-scripts/build_openexr.bash, src/build-scripts/ci-build-and-test.bash, src/build-scripts/ci-startup.bash, src/build-scripts/circleci-installdeps.bash, src/build-scripts/install_homebrew_deps.bash, src/build-scripts/install_test_images.bash, testsuite/raw/ref/out-libraw0.17.2-circle.txt, testsuite/raw/run.py
A bit of material has been refactored out of .travis.yml into separate
scripts so it can be shared with circleci.
CircleCI is an alternative CI system like TravisCI or Appveyor.
Mostly I'm doing this as a prototype and to learn about it, because
it's under discussion as a potential favored CI system for ASWF.
But as it turns out, the VMs provisioned by CircleCI are more capable
CPUs than the ones with Travis. In particular, it looks like they
support AVX-512. Right now, the Travis VMs top out at AVX 1.0, so
although we have Travis test matrix entries that "build" for AVX2 and
AVX512 just to make sure we haven't broken the build, we aren't able
to run the tests when compiled for that architecture. But we can on
CircleCI. So I'm thinking of throwing CircleCI into the mix just for
certain …
=> CircleCI - prototype

src/include/OpenImageIO/timer.h
Strutil::printf does its underlying output atomically, so if these
destructors are triggered from multiple threads, they won't get
"interleaved" on the terminal, making them unreadable, as they would be
with ordinary stream output.
=> Timer dtr print, change from stream I/O to Strutil::printf

site/spi/Makefile-bits, src/build-scripts/install_homebrew_deps.bash, src/iinfo/iinfo.cpp, src/libutil/benchmark.cpp, src/libutil/fmath_test.cpp, src/python/py_deepdata.cpp, src/python/py_imagebuf.cpp, src/python/py_imagecache.cpp, src/python/py_imageinput.cpp, src/python/py_imageoutput.cpp, src/python/py_imagespec.cpp, src/python/py_oiio.cpp, src/python/py_paramvalue.cpp, src/python/py_typedesc.cpp
The recent upgrade to clang 8 (via homebrew on the TravisCI configuration that we use to verify formatting) brought some minor changes to what clang-format wants to do.
I think it's easier to just accept these occasional arbitrary changes with major clang releases rather than to try to painfully adjust the clang-format parameters to exactly preserve the old behavior.
=> Adjustments from clang-format update

src/include/OpenImageIO/fmath.h, src/iv/imageviewer.cpp, src/iv/ivgl.cpp, src/iv/ivutils.h, src/libOpenImageIO/maketexture.cpp, src/libtexture/imagecache.cpp, src/libutil/fmath_test.cpp
This is in keeping with the nomenclature of the C++20 `<bit>` header which
contains the equivalent functions.
Also give them the constexpr and noexcept treatment.
=> Rename pow2roundup/pow2rounddown -> ceil2, floor2

src/oiiotool/oiiotool.cpp, src/oiiotool/oiiotool.h
Background:
By default, most oiiotool operations ignore multiple subimages. For
commands that modify metadata in place, that means it will only modify
the first subimage (leaving the rest untouched). For commands that
remove inputs from the stack and produce outputs to be put back on the
stack, generally their output will only be based on the first
subimage, and subsequent subimages will be dropped.
`-a` says that any ops ought to work on all subimages if at all
possible; that means that in-place metadata modifiers will apply to
all subimages, and stack ops should produce outputs with the same
number of subimages as their inputs, doing the right operation to each
subimage in turn.
Most commands (but not 100%) also respect an optional
`:allsubimages=VAL` that override `-a` on that one …
=> Better oiiotool support of multiple subimages

src/tiff.imageio/tiffinput.cpp
Redo of #2206 -- safer approach. I was overwriting important memory in the first try.
=> Fix crash reading certain old nconvert-written tiff files

src/libOpenImageIO/imagebufalgo_xform.cpp
The innards of IBA::resize() has to accumulate the weighted
contributions of source pixels under the filter window, and that
accumulator used 'float'. This is fine except when the input image is
'double', in which case you might want just a touch more precision.
So we define an Accum_t typedef template that is double when double is
needed, and float for all other cases. Adds the precision that double
image resize needs, but retains the speed and precision of the prior
float behavior in all other cases.
Fixes #2210
=> IBA::resize -- fix precision for double images

src/build-scripts/install_homebrew_deps.bash, src/libOpenImageIO/imagebufalgo_xform.cpp, src/tiff.imageio/tiffinput.cpp
Oops, a few merges ago I changed the .travis.yml to "source" the
install_homebrew_deps.bash script (instead of making a subshell)
and this caused the "exit 0" early out in it to not just terminate
that script as intended, but to terminate the entire Travis test,
making it look like it passed even though it never got around to
running clang-format at all. Oh dear.
This fixes it. It also uncovers a few minor formatting changes
we should have made over the last few days, but missed.
=> Travis: Fix clang-format test

src/cmake/externalpackages.cmake, src/ico.imageio/CMakeLists.txt, src/png.imageio/CMakeLists.txt, src/ptex.imageio/CMakeLists.txt, src/tiff.imageio/CMakeLists.txt, src/zfile.imageio/CMakeLists.txt, src/zfile.imageio/zfile.cpp
* Correct use of ZLIB_INCLUDE_DIRS (not ZLIB_INCLUDE_DIR!).
* Only add include dirs for modules that need it.
* Also, change from obsolete PNG_INCLUDE_DIR to correct PNG_INCLUDE_DIRS.
=> Fix ZLIB references

.travis.yml, src/build-scripts/ci-build-and-test.bash, src/build-scripts/ci-startup.bash
A few test errors had crept in lately because we inadvertently broke this and therefore weren't properly seeing test failures in master for the last ~week.
=> Fix Travis -- broke ability for broken build to error

src/iconvert/iconvert.cpp, src/idiff/idiff.cpp, src/igrep/igrep.cpp, src/iinfo/iinfo.cpp, src/include/OpenImageIO/sysutil.h, src/iv/ivmain.cpp, src/libOpenImageIO/maketexture.cpp, src/libtexture/imagecache_pvt.h, src/libutil/sysutil.cpp, src/maketx/maketx.cpp, src/oiiotool/oiiotool.cpp
Set up signal handlers in all the command line utils so that if they
crash, they will print stack traces that will help track down CI or
user-side failure cases.
This relies on Boost >= 1.65 for its stacktrace library. When built
against older versions of boost, stacktrace() will return an empty
string and the stacktrace-printing signal handles will have no effect.
C'est la vie.
=> Sysutil: add utilities to get stack traces

src/include/OpenImageIO/filesystem.h, src/libutil/filesystem.cpp
We've been plagued by recently-introduced bugs with PNG and JPEG
reading that stemmed from the first IOProxy-related patch.  The
problem was our use of the Windows ReadFile call, which seems to not
preserve the file pointer as we'd assumed (the MSDN docs are ambiguous
about this). I also began to doubt its thread safety, so in the end I
just replace the code with a simpler approach with a mutex and calls
to tell/seek/read.
=> Fix IOProxy::pread on Windows that botched PNG & JPEG read

src/cineon.imageio/libcineon/Writer.cpp, src/dpx.imageio/libdpx/RunLengthEncoding.cpp, src/dpx.imageio/libdpx/Writer.cpp, src/libOpenImageIO/imageinput.cpp, src/libOpenImageIO/imageoutput.cpp, src/openexr.imageio/exroutput.cpp
Sometimes for very large images, either the number of pixels (w * h * d)
or the total data size (npixels * pixelbytes) can overflow int32 math.
Find several places where this may be a problem and use casts to ensure
64 bit multiplication.
I don't claim this is a comprehensive fix, but I did a cursory check of
some obvious places and found these to squash.
=> Defensive programming to prevent integer overflow for large images

src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/typedesc.h, src/libOpenImageIO/imageio.cpp, src/libutil/typedesc.cpp
I realized that there is a convert_type function in typedesc.h and a
convert_types function in imageio.h that are subtly and confusinginly
different in their meaning and arguments.
* Expand typedesc.h `convert_type()` to take an optional number of
values parameter (defaulting to 1, old behavior of converting one
value).
* Rename imageio.h `convert_types()` to `convert_pixel_values()` and
clarify comments to emphasize the important differece -- that this
one is dealing with pixel-like normalized values (e.g., the max
value of an int-like type corresponds to float 1.0).
So you should use convert_type to do a straightforward "cast" of the
value from one data type to the same value in another data type, but
convert_pixel_values to convert a pixel-like intensity to the
equivalent normalized …
=> Adjustment to convert_type/convert_types functions

src/doc/imagebuf.tex, src/doc/pythonbindings.tex, src/include/OpenImageIO/imagebuf.h, src/libOpenImageIO/imagebuf.cpp, src/python/py_imagebuf.cpp
* Docs, header, and implementation were not all consistent about
whether the ImageBuf construct-from-ImageSpec (or the `reset()` call
of the same flavor) zeroes out the newly allocated buffer, or if the
pixel values are left uninitialized.
* Change the call signature to take an optional `zero` parameter -- which
defaults to true, meaning that the pixels are zeroed out when allocated
(this is the foolproof approach, at the cost of writing all the memory
of the buffer). If zero==false, the newly allocated pixels will remain
uninitialized (this is for power users who want to maximize performance
when they know that they will soon overwrite all the vaues in the buffer
and want to avoid any unnecessary writes).
* Touch up the docs and header comments to be consistent and explain the
behavior …
=> Straighten out construction of ImageBuf from spec -- zero or not?

src/openexr.imageio/exrinput.cpp
The GCD functionality moved several versions ago, from boost::math to
boost::integer. It's been "replicated" in both places for a while, but
at least on 1.69, it issues warnings. At some point it will be
permanently moved. So let's get out ahead of that potential breakage.
=> Adjust boost gcd based on version

src/libutil/sysutil.cpp, src/oiiotool/oiiotool.cpp
Also fix warning if symbol is already defined.
I added it to all the other command line utils. And I must have had it working in oiiotool at some point because that's where I put the hidden `--crash` option to test it. I might have had accidentally deleted those couple line before merging somehow.
=> Fix: somehow forgot to add crash stacktrace to oiiotool

src/oiiotool/oiiotool.cpp
It worked with the global -a, but not the customary `:allsubimages=1`
modifier to that individual command. Either is supposed to make it
apply the channel shuffling to all subimages of a multi-subimage file
(for example, a multipart exr file).
=> oiiotool --ch did not honor `allsubimages=1` modifier

src/doc/Doxyfile, src/doc/Makefile, src/doc/conf.py, src/doc/imageioapi.rst, src/doc/index.rst, src/doc/oiiointro.rst, src/include/OpenImageIO/deepdata.h, src/include/OpenImageIO/imagecache.h, src/include/OpenImageIO/imageio.h, src/include/OpenImageIO/span.h, src/include/OpenImageIO/string_view.h, src/include/OpenImageIO/ustring.h
Years ago we made Doxygen docs. I hated it, I think they look ugly and
are a poor user experience trying to make sense of them. So at some
point we stopped the charade and let it rust away. Though it lives on
a bit by the fact that I'd already established the habit of using
`///` for documentary comments.
This leaves us with the problem of how to make the header files
self-documenting, while also maintaining the beautiful LaTeX PDF book
that I consider the primary documentation of OIIO. I've been keeping
up as best as I can, but this leads to redundancy of the writing (at
best), and divergence (at worst, which is to say, always).
I'm not a huge fan of "restructured text" (rst), but the documentation
that Sphinx makes is fairly pleasing, it can generate html web pages
and also a PDF (via …
=> Experiment: Try the combination of Doxygen + Sphinx + Breathe + rst

src/doc/Doxyfile, src/doc/imageioapi.rst, src/doc/imageoutput.rst, src/doc/index.rst, src/doc/pythonbindings.tex, src/include/OpenImageIO/imageio.h
A few virtual functions in ImageOutput have had their order changed
for the sake of clearer documentation, and that introduces link
incompatibility in the vtbl.  This is only in master, so we're allowed
to have breaking changes. But just mentioning it so it's noted in the
history.
=> More doxygen/breathe/sphinx/rst: Convert ImageOutput chapter

src/openexr.imageio/exroutput.cpp
Typo! Was grabbing from this->spec before it was assigned, should have
looked in the parameter spec (to OpenEXROutput::spec_to_header).
Fixes #2251
=> Fix broken ability to specify compression of multipart exr files

.travis.yml, CMakeLists.txt, src/include/OpenImageIO/color.h, src/libOpenImageIO/color_ocio.cpp, src/python/CMakeLists.txt, src/python/py_colorconfig.cpp, src/python/py_oiio.cpp, src/python/py_oiio.h, testsuite/python-colorconfig/ref/out-noocio-python27.txt, testsuite/python-colorconfig/ref/out-noocio.txt, testsuite/python-colorconfig/ref/out-python27.txt, testsuite/python-colorconfig/ref/out.txt, testsuite/python-colorconfig/run.py, testsuite/python-colorconfig/src/test_colorconfig.py
Background: ColorConfig is our wrapper around some OpenColorIO
functionality, so that apps whose only need for OCIO is for the sake
of OIIO color conversion functions, they can go though this thin
interface instead of directly needing to navigate the more complicated
APIs of OCIO. It also allows us to abstract whether OCIO is actually
available, if it's not it understands just a couple hard-coded color
transformations.
* Add getColoSpaceFamilyByName, which was some OCIO functionality we
did not expose before.
* Add methods that return a vector of strings containing the list of
all color spaces, looks, displays, or views for a display.
* Expose all this to Python. And add a simple unit test.
* Make sure one Travis test disables OCIO support, so we know what
breaks under those …
=> ColorConfig additions

.travis.yml, src/libOpenImageIO/CMakeLists.txt, src/libutil/CMakeLists.txt
* Switch where I get gcc9 from in the Travis setup, the previous one has
broken (it was a "gcc-latest", which is now an in-progress gcc10).
* Fix a gcc9 warning
=> gcc9 Travis build and warning fixes

src/raw.imageio/rawinput.cpp, testsuite/raw/ref/out-libraw0.17.1.txt, testsuite/raw/ref/out-libraw0.17.2-circle.txt, testsuite/raw/ref/out-libraw0.18.11.txt, testsuite/raw/ref/out-oldlibraw0.15.txt, testsuite/raw/ref/out.txt, testsuite/raw/run.py
We were not using certain libraw parameters correctly.
New default behavior is to decode to sRGB (both primaries and
response) -- because for a naive user that just reads a raw file and
slaps it up for display, this behaves like a jpeg.
But configuration hints "raw:ColorSpace" can request various other
things, like "ACES" (linear ACES), "Adobe" (Adobe gamut with 1.8
gamma), and so on. Asking for "linear" gives you sRGB primaries
with linear response.
Fixes #2256
=> Revise raw processing

CMakeLists.txt, LICENSE.md
* Slight reformat to make it more automatically discoverable as exactly
the 3-clause BSD license.
* Change copyright name from "me, et al" to "Contributors to the
OpenImageIO project."  This is more accurate; it's always been the
case that copyright belongs to each contributor for their own
additions, we never have requested copyright assignment. The "et al"
was supposed to indicate that, but I think taking my name out makes
it even more clear.
=> LICENSE.md reformat

src/include/OpenImageIO/dassert.h, src/include/OpenImageIO/platform.h
* Use pretty function printing to show what func it failed in.
* Changing wording to more closely match built in assert().
* Make DASSERT simply define to built in assert(), which has the
advantage compiling without warnings and running correctly with Cuda!
The ASSERT (works in debug mode as well) and [D]ASSERT_MSG macros
still are not Cuda friendly because they specifically mention stderr.
=> Spruce up ASSERT macros

src/libtexture/environment.cpp
Just copying from texture/texture3d. Must have forgotten to port it to environment when I did it for the others.
=> Resolve environment subimage by name, as we do for texture and texture3d

src/include/OpenImageIO/simd.h
This proposed patch just #undef's it. 
Optionally, I could also re-define it at the end, like:
#ifdef _X11_XLIB_H_ /* regrettable */
#define True 1
#define False 1
#endif 
I'm not sure if that's clever, or "too clever" and will cause more trouble.
=> Protect simd.h against stray #define of True or False

src/python/py_oiio.h, testsuite/python-imagespec/ref/out-python3.txt, testsuite/python-imagespec/ref/out.txt, testsuite/python-imagespec/src/test_imagespec.py
It actually boiled down to trouble with setting unsigned int array attribute
from Python int tuples.
Make sure to test this in testsuite/python-imagespec
Fixes #2275
=> Fix inability for python to set timecode

src/python/py_colorconfig.cpp, src/python/py_oiio.h
Python.h will set POSIX_C_SOURCE it was built with and py_oiio.h includes that first
=> Reorder includes for Python.h and POSIX_C_SOURCE macro

src/include/OpenImageIO/ustring.h, src/libutil/strutil_test.cpp
The logic was wrong in cases where the string_view was longer than the
ustring, but they has the same character sequence up to the length of
the ustring.
Add some unit tests to ferret out this case.
To do: fully flesh out unit tests for every last bit of functionality
of ustring and string_view.
=> Fix embarrassing ustring::compare(string_view) bug

src/cmake/externalpackages.cmake
Building on centos 6, I get errors such as:
```
[ 90%] Linking CXX executable iconvert
../../../../external/dist/linux64/lib/boost_1_64_0/libboost_thread.a(thread.o):libs/thread/src/pthread/thread.cpp:function boost::this_thread::no_interruption_point::hidden::sleep_until(timespec const&): error: undefined reference to 'clock_gettime'
../../../../external/dist/linux64/lib/boost_1_64_0/libboost_thread.a(thread.o):libs/thread/src/pthread/thread.cpp:function boost::this_thread::no_interruption_point::hidden::sleep_until(timespec const&): error: undefined reference to 'clock_gettime'
../../../../external/dist/linux64/lib/boost_1_64_0/libboost_thread.a(thread.o):libs/thread/src/pthread/thread.cpp:function boost::this_thread::no_interruption_point::hidden::sleep_until(timespec const&): error: …
```
=> linking with rt is required on older linux distros

src/iv/imageviewer.cpp, src/iv/imageviewer.h, src/iv/ivimage.cpp, src/iv/ivmain.cpp
For better inspection of raw values of CMYK or other non-RGB color
spaces that would ordinarily be automatically converted.
=> iv: Add -rawcolor option to skip auto-convert to RGB

src/oiiotool/printinfo.cpp
Like, let's say it's a CMYK file, and you want to know the stats about the original CMYK values, not the stats about the emulated RGB translation...
=> oiiotool -stats not communicating the input configuration hints
