AcademySoftwareFoundation/OpenImageIO

- src/include/OpenImageIO/missing_math.h
- src/include/OpenImageIO/simd.h
While compiling OSL, I found that my commits from two weeks ago needed to be extended.
> OIIO fixes for compiling OSL on Win32

- src/include/OpenImageIO/simd.h
It looks like we're trading simd for serial ops here, but looking at the assembly output shows that gcc and clang (especially clang!) recognize this pattern and turn it into very efficient code. Furthermore, I benchmarked it very carefully, and this makes a definite speedup (significantly so for the 3-float load). I still don't fully understand why my trickery wasn't the fastest method, but the timings could not be more clear, on multiple platforms.
I should clarify: My artificial benchmark that times the load and store of 3-vecs shows marked improvement with this patch. The 3-vec load is recently added and not yet used at all in the code base (except for unit tests), and the 3-vec store is only used in a couple places so far, so this does not yet show any improvement in overall rendering …
> simd.h refinement: found faster load(...,3) and store(...,3) idioms.

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Fun utility function. My use of it will be in a later review.
> Added Strutil::parse_nested -- parse to end of nested paren, bracket, or brace

- src/libOpenImageIO/formatspec.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/texture_pvt.h
Submitting on behalf of Max:
1. In formatspec.cpp, simplify format_raw_metadata and fix the string case to handle string arrays.
2. Imagecache: improve printing of IO rates when the time spent is 0 (avoid divide by zero)
3. Comment typo fixes
> Odds and ends from Max Liani

- src/libOpenImageIO/maketexture.cpp
This improves robustness by eliminating the possibility of a half-written texture file that lacks all the MIPmap levels (which might be inexplicably slow to render if nobody realizes it's a partial file) or is otherwise malformed in a way that leads to chaos. Basically, a crash or failure no longer will write to the output filename, only to a temporary file. The temp file is renamed/moved when the full file write is complete without errors.
Submitted on behalf of Max Liani. (With just a teensy bit of minor editing by LG.)
> maketx improvement: write to temp file, rename upon successful completion

- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
insert<>, xyz0, vreduce_add, dot, dot3, vdot, vdot3, AxBxCxDx, blend0not
Supports some ongoing work I'm doing to use SSE to speed up various things.
> SIMD utility additions

- src/include/OpenImageIO/thread.h
I actually did this a while back and never got around to submitting it.
Bring ourselves closer to emerging consensus on the right APIs for atomic operations.  (And by "emerging", I mean several years ago with C++11 and C11.) To wit:
* extend our atomic_exchange_and_add, atomic_compare_and_exchange, and atomic_exchange to take memory_order parameters (with default values giving behavior as before, and safe). Now, for some of the (older) underlying implementations, it does not use the new parameter (equivalent to a full fence), but for the common/modern case of the new gcc __atomic intrinsics (and in the future, for C++11), we pass the parameters on properly.
* Our atomic<T> gets load(), store(), exchange(), fetch_add(), and fetch_sub() methods to more closely conform to the C++11 atomic<> …
> atomic additions

- src/include/OpenImageIO/fmath.h
fmath: safe_fast_pow should special-case x^2.0 to have as much precision and speed as multiply. We're assuming that ^2.0 issues will be way more noticeable than other integer powers, which we'll continue to sweep under the rug. If you want more exact, use safe_pow. But getting squaring right seems like the right balance.
> fmath: safe_fast_pow should special-case x^2.0

- src/libOpenImageIO/imagebufalgo_compare.cpp
The way the comparisons were arranged, an image that had NaNs would not
notice that the NaN values were different between two images. Yikes!
> Make IBA::compare() (and therefore idiff & oiiotool -diff) robust to NaN/Inf values

- src/tiff.imageio/tiffoutput.cpp
> Fix build against older libtiff -- better guard around new API calls.

- site/spi/Makefile-bits-arnold
Build changes to compile on rhel7 for SPI
> fixes for rhel7 at SPI

- src/include/OpenImageIO/typedesc.h
(Submitted on behalf of Daniel Heckenberg)
Instead of arraylen == -1 meaning "unsized" and length < -1 having no
meaning, -n means "unsized with default length n".
This is helpful in supporting OSL arrays with runtime-settable lengths. It doesn't
have any immediate impact on OIIO per se, which has no internal uses for the
"array of indeterminite length" notation.
> Tweaks to TypeDesc to allow arraylen -n to mean unsized, with default length n.

- src/libutil/ustring.cpp
Now that our custom implementation of ustring tables has been working for a while, it should be ok to remove the old one.
> Remove old implementations of ustring

- src/png.imageio/png_pvt.h
> PNG writes should honor PixelAspectRatio attribute

- src/include/OpenImageIO/timer.h
Also some cleanup of ScopedTimer -- doesn't need to be a template.
I did this a while back, never submitted, but now I want to use part of it.
> Timer: enums, naming, print upon destruction

- src/oiiotool/oiiotool.cpp
Make it easy to tell from running oiiotool what format support was included at build time.
> Have oiiotool help message list the formats supported.

- src/tiff.imageio/tiffinput.cpp
Rearrange the order in which we examine TIFF header order. When reading MIPmap levels (beyond the first one), we assume that all the ordinary metadata should be the same for all levels, so we don't laboriously read all that stuff. But in our zeal to skip this needless work, we took the early out before examining some essential fields such as planarconfig, photometric interpretation, palette processing, and extrasamples.  If a file should change this from one MIP level to the next -- which no sane file should do, but hey, it did happen in the wild -- that would bring chaos. Now we are more robust to this, while still avoiding all the detailed metadata reading for non-head MIP levels.
Fixes #1220
> Make TIFF read robust to subimge-to-subimage changes in some header fields

- src/libutil/filter.cpp
One more bit of work related to the filter fixes from about a week ago -- forgot radial-lanczos3.
> Make radial-lanczos3 filter scale properly

- src/openexr.imageio/exroutput.cpp
Fix issue raised in https://github.com/OpenImageIO/oiio/issues/1237
> OpenExrOutput : Add true return for supports("deepdata")

- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imagecache_test.cpp
- src/libtexture/imagecache.cpp
> Fix data copy error in IC::get_pixels, add unit test for ImageCache

- src/openexr.imageio/exroutput.cpp
Refactor is an improvement but the real motivation was to ensure that
the OpenEXR standard metadata knew what types they were expecting, and
could more deftly handle type mismatches including conversions when the
intent is obvious (example: passing an int rather than a float for
PixelAspectRatio).
Fixes #1242
> OpenEXR refactor of translating OIIO standard metadata to EXR names.

- src/libtexture/texturesys.cpp
Bug fix in special pole handling for env map lookups + tile channel subsets.
Oy, remember that recent ImageCache change where tiles may hold channel subsets for many-chaneled files? It doesn't play well with the particular way that pole_color walked through the tile's pixel memory to compute the pole color, and in fact to get the pole color right we need all the channels (because we want to do it just once per MIP level).
The simplest way of handling this is just to NOT do the tile channel constriction when dealing with environment maps, at the one-tile MIP levels (the only time that the pole color facing happens).
The only way this would come up is when doing environment map lookups right smack at the poles, only when blurred enough that the MIP level fits on one tile, and only for …
> Bug fix in special pole handling for env map lookups + tile channel subsets

- src/openexr.imageio/exroutput.cpp
A few checkins ago, we refactored some EXR metadata output, making a
table.  Well, turns out that this can be subject to the "initialization
order fiasco", because the static table in exroutput.cpp referenced the
static global variables TypeDesc::TypeMatrix (and several others) that
are defined in typedesc.cpp, and thus may not yet have been initialized.
Why, exactly, the fairly trivial constructors don't automatically bake
down into POD that can be statically initialized in the DSO, I don't
understand.
But anyway, slight modification of the table to not depend on any prior
initializations fixes it.
Also put in automatic float[16]-to-matix44 translation, though it turns
out that wasn't the problem after all, and beefed up a debug message.
> Fix recent exr metadata break

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Handy utility to repeat a string n times
> Strutil::repeat

- src/libOpenImageIO/deepdata.cpp
The old DeepData required clients to call an explicit deep_alloc, which
they could do serially, after which parallel data accesses were
thread-safe. But the new DeepData doesn't have deep_alloc; instead, the
allocation happens implicitly whenever data needs to be accessed (i.e.,
in the potentially parallel section). So the internals themselves need
to ensure thread safety of the allocation, whenever it happens.
> DeepData: need to make internal alloc() thread-safe

- src/include/OpenImageIO/SHA1.h
> Including <climits> in SHA1.h fixes some typing/linking issues.

- src/libOpenImageIO/imagespeed_test.cpp
* Allow specification of image conversion type upon read
* Allow skipping of ImageBuf iteration tests
* Allow specification of cache size
> imagespeed_test flexibility

- src/libOpenImageIO/imagebuf.cpp
IB was usually falling back on IC::get_pixels to go through the cache,
even when asked to "force" a read. Making it accept a wider variety of
circumstances in which it just does a direct read via
ImageInput::read_image (and not making an extra copy out of the IC)
roughly doubles read performance for typical cases.
I suppose that this could bite you if you ended up with a bunch of IB's
in the app all wanting the same image, in which case going through the
cache would have been a win. And this was obviously the intent of the
original design. But I think we have enough experience now to realize
that this is an unusual case -- in most apps (aside from "texture") a
particular image is not likely to be read more than once in a short
period of time, and so does not benefit from a copy being kept …
> Double speed of ImageBuf read by bypassing the IC for "forced" reads.

- src/include/OpenImageIO/simd.h
- src/libtexture/texturesys.cpp
This is stuff I did weeks ago, just been sitting on as low priority. 
No changed functionality.
* New macros for declaring static constants
* For no-SSE case, use loops
* Improved ARM NEON support
> Minor simd.h refactoring

- .travis.yml
- src/include/OpenImageIO/simd.h
Broke builds for some configurations.
Fixes #1340
> simd.h fixes

- src/pnm.imageio/pnminput.cpp
Sent in by Frédéric Devernay.
Fixes #1343
> Fix PNM endian issue.

- src/libOpenImageIO/imageinput.cpp
> Fix error reading tiles for mixed-format exr files.

- src/libOpenImageIO/imagebufalgo.cpp
By (1) guaranteeing and exploiting the kernel being a float image in
local memory (which is expected to always be the case anyway), and (2)
being smarter about incrementing the source iterator rather than fully
resetting its position at every filter tap, this speeds up
IBA::convolve() by about 35%. It also speeds up anything that uses
convolve underneath, including unsharp_mask and blurring.
> Speed up IBA::convolve()

- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/maketexture.cpp
* parallelize
* for special case of in-memory, same data type, copy raw data rather
than go through iterator overhead for each channel value.
This allows us to remove the now-redundant copy_block in make_texture,
use ImageBuf::copy_pixels.
> ImageBuf::copy_pixels speedup

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Recently, GitHub allowed for PR and Issue templates. Let's try them out! Also a CONTRIBUTING guidelines.
There is no way to "preview" the experience of using them, so I think I just have to push it to master and see what it's like. If we aren't crazy about it, we can revise or eliminate the templates.
> First stab at CONTRIBUTING guidelines and PR/issue templates [ci skip]

- src/openexr.imageio/exrinput.cpp
This PR fixes the following issue https://github.com/OpenImageIO/oiio/issues/1375
> Fix exr_threads attribute

- src/libOpenImageIO/compute_test.cpp
- src/libOpenImageIO/imageio.cpp
> Initialize thread counts to hardware_concurrency, not physical_concurrency

- src/libOpenImageIO/deepdata.cpp
> Fix critical DeepData bug -- reversed insertion/deletion

- src/libutil/simd_test.cpp
> Fix error for some compilers

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
> Strutil::replace

- src/include/OpenImageIO/thread.h
> mutex_pool

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
> Filesystem::file_size() and Filesystem::read_bytes()

- src/libutil/sysutil.cpp
> Implementation of Sysutil::terminal_columns() for window

- src/cineon.imageio/cineoninput.cpp
Pointed out in #154 by Frédéric Devernay.
> More robust test for gamma value in cineon files.

- src/include/OpenImageIO/simd.h
* Macros to un-4-ify the generic code. This reduces some clutter and
will makes it much easier to clone these classes for 8-wide and 16-wide
in the future.
* Define simd_raw_t<N> and simd_bool_t<N> tempaltes that make it easier
to reduce a bit of the #if clutter.
> Next round of simd.h cleanup

- CMakeLists.txt
- site/spi/Makefile-bits-arnold
- site/spi/Makefile-bits-spcomp2
- site/spi/libOpenImageIO.map
Of concern only to SPI peeps, won't affect anybody else.
* Link against static libtiff to solve .so hell.
* Make SPI-specific visibility map file
* Fix Nuke location
> SPI build fixes

- src/libutil/filesystem.cpp
> SPI: fix old boost limitation. Last fix for boost 1.42, I promise.

- site/spi/Makefile-bits-arnold
- site/spi/Makefile-bits-spcomp2
Non-SPI people can ignore this
> SPI: stop building for old OS

- src/cmake/modules/FindOpenJpeg.cmake
Fixes #1517 -- that's the issue in which Mikael suggested the fix, I'm just turning it into a PR in his behalf.
> Adjust OpenJpeg finding to look in -2.2 directories.

- src/rla.imageio/rla_pvt.h
- src/rla.imageio/rlainput.cpp
- src/rla.imageio/rlaoutput.cpp
Bad channel logic made RGBZ file think channel 3 was alpha as well as Z. Confusing!
> RLA fix: bad channel logic made RGBZ file think channel 3 was alpha

- src/nuke/txReader/txReader.cpp
Proposed fix for https://github.com/OpenImageIO/oiio/issues/1455.
The issue is caused by the fact that the user-facing `Enumeration_knob` is populated from within the Reader's constructor, which is too late when the Read is created with a non-default mip level (e.g. when loading a saved script).
To work around this without resorting to saving all of the knob's menu items, the menu index is no longer stored by the Read or used in the op hash. Instead, its value is copied to a hidden `Int_knob`, which drives the actual Reader and gets saved when the Read is serialized.
Also, the txReader now sets the bit-depth metadata key properly when the input file contains `half` data, which was an earlier oversight.
> nuke: Fix txReader to properly restore saved mip level knob value

- src/field3d.imageio/field3dinput.cpp
- src/iconvert/iconvert.cpp
- src/igrep/igrep.cpp
- src/iinfo/iinfo.cpp
- src/iv/imageviewer.cpp
- src/iv/ivgl.cpp
- src/iv/ivimage.cpp
- src/iv/ivmain.cpp
- src/libOpenImageIO/exif.cpp
- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imageioplugin.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libtexture/imagecache.cpp
- src/libutil/filesystem.cpp
- src/libutil/strutil.cpp
- src/oiiotool/oiiotool.cpp
- src/psd.imageio/psdinput.cpp
For master only, where C++ is the minimum.
> Replace BOOST_FOREACH with C++11 'range for'

- src/include/OpenImageIO/fmath.h
> Fix typo in fmath bitcast_to_float declaration

- src/libOpenImageIO/color_ocio.cpp
The specific case is OCIO is present, a straightforward color conversion is requested such as "sRGB" to "linear", but because the particular OCIO config doesn't know about sRGB, it fails. That's silly, we still know how to apply the sRGB transforms.
So, if OCIO fails to find a suitable transform, we place a hold on the error until we check the set of transformations we can implement even when no OCIO is found. If it's still not found, then we pass along the error as usual. Also, we assume that the very common names "lnh" and "lnf" are synonyms for "linear" (for the purposes of sRGB conversion), even if they are not marked as such.
I know, the color purists will have all sorts of very technically correct reasons to think this is wrong. And it is. But it's the lesser evil, compared to …
> Improve colorconvert heuristic for case with OCIO, but spaces not found.

- src/libtexture/imagecache.cpp
Changing the IC's "autotile" value triggers a call to invalidate_all(),
but even there, it was not recognizing that as a condition to invalidate
a file. For untiled files in the cache, the file should be invalidated
if the "virtual tile size" doesn't match the autotile size.
(This PR is a patch against RB-1.7, but obviously I will apply it to master as well.)
> IC: be robust to changes in autotile after opening a file.

- .travis.yml
- CHANGES.md
- CMakeLists.txt
- README.md
- src/build-scripts/install_homebrew_deps.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindDCMTK.cmake
- src/dicom.imageio/CMakeLists.txt
- src/dicom.imageio/dicominput.cpp
- src/dicom.imageio/dicomoutput.cpp
- src/doc/builtinplugins.tex
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imageioplugin.cpp
A little rough around the edges, but seems to work. We'll probably come
back and revise as shortcomings are discovered, but this is enough to
get started.
> DICOM reader. DICOM is the main format used for medical imaging.

- src/libOpenImageIO/maketexture.cpp
- src/openexr.imageio/exroutput.cpp
- src/png.imageio/png_pvt.h
- src/tiff.imageio/tiffoutput.cpp
I think the changed format is a more accurate interpretation of the TIFF spec.
> Fix date formatting to use "%02" for hour.

- src/oiiotool/oiiotool.cpp
It was just fitting the first subimage and dropping the others on the floor.
> oiiotool: make --fit:exact=1 work for all subimages

- CHANGES.md
- src/doc/builtinplugins.tex
- src/raw.imageio/rawinput.cpp
Request from a user for this control over the corresponding libraw internal parameter.
> RAW input: add config hint for maximum camera value

- src/include/OpenImageIO/typedesc.h
> Modernize and constexpr-ify typedesc.h

- src/libOpenImageIO/xmp.cpp
- src/png.imageio/png_pvt.h
Also, recognize some additional xmp tags in the tiff namespace.
> Better extraction of XMP from PNG files.

- src/python/CMakeLists.txt
> Make search for boost_python3 more reliable

- src/cmake/install.cmake
- src/python/CMakeLists.txt
Floating this test... maybe it fixes #926 ?
> Fix python site-packges path for install

- src/field3d.imageio/field3doutput.cpp
- src/fits.imageio/fitsoutput.cpp
- src/iconvert/iconvert.cpp
- src/igrep/igrep.cpp
- src/iv/imageviewer.cpp
- src/iv/ivgl.cpp
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libOpenImageIO/iptc.cpp
- src/libOpenImageIO/xmp.cpp
- src/libtexture/imagecache_pvt.h
- src/libutil/argparse.cpp
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
- src/libutil/thread.cpp
- src/libutil/ustring.cpp
- src/oiiotool/oiiotool.cpp
- src/openexr.imageio/exroutput.cpp
- src/python/py_oiio.cpp
- src/python/py_oiio.h
- src/softimage.imageio/softimageinput.cpp
Suggestions courtesy of clang-tidy.
> Convert to range-for loops

- src/testtex/testtex.cpp
testtex has a `--handle` flag that lets you test performance differences
between the texture calls that take handles, versus the ones that take
filenames and figure out the handles by looking it up in the file
cache. But it turns out I had implemented that option fully for the
usual "make a texture image" tests, but not for the special thread
workload test you get with the `--threadtimes` option.
> testtex: make the tex_thread_workout cases all honor --handle

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
Add some stat collection to try to measure how much time we spend waiting for the mutex that guards access to the ImageInput for each texture file.
> IC: collect stats on how long we wait for imageinput mutexes

- src/libOpenImageIO/CMakeLists.txt
Windows build fix from Patrick Hodoul.
> Fix Windows build issue

- INSTALL.md
This PR formats a table in the [INSTALL.md](https://github.com/OpenImageIO/oiio/blob/master/INSTALL.md) file to fix misalignments:
> Format table in "INSTALL.md" file.

- src/include/OpenImageIO/unordered_map_concurrent.h
Use the upper bits of the hash for bin selection instead of hashing the hash.
This is a small but measurable improvement on the benchmark I am looking at now.
> unordered_map_concurrent performance improvement

- src/testtex/testtex.cpp
* Only print the detailed stats if -v is used.
* New option --noinvalidate instructs it to not invalidate the cache
when starting each threadtimes trial. Combined with setting --cachesize
very large, this makes it possible to time the texturing math and
resident cache behavior without any disk access (because after the
first trial, all the needed tiles will probalby be resident).
> testex improvements

- src/testtex/testtex.cpp
* For more realism in the "thread_workout" tests, which I noticed had
filter shape with exactly 1.0 aspect ratio, add a --anisoratio option
that lets you set anisotropic shape. By making a 2.0 or 4.0 aspect
ratio, that's a bit more realistic in terms of what a 3D renderer will
see for average aspect ratio.
* For clarity, change the older --aniso option to --anisomax, to emphasize
that it's setting the maximum allowable anisotropy.
* Make test thread_working samples twice as big, so it's sampling between
levels 1 and 2 instead of between levels 0 and 1, that's more realistic,
I think. The old way biased the tests much more to bicubic sampling which
is probably less common than the tests made it out to be.
* Stats were printing only for the ImageCache, not for the TextureSystem.
Fix by …
> testtex fixes

- src/cmake/externalpackages.cmake
- src/cmake/modules/FindDCMTK.cmake
- src/dicom.imageio/dicominput.cpp
> Fix dcmtk build errors on some platforms

- src/include/OpenImageIO/thread.h
This lets you wait for just one task in the task set to finish. Versus
the usual wait() that waits for all tasks in the set to be completed.
This is handy for "pipelining", where you are using the tasks as a
queue, and as they are done, you can pass them off to the next
stage. There's no reason to wait for all to complete to begin processing
the first-completed tasks coming out of the queue.
> task_set : add wait_for_task

- src/libOpenImageIO/color_ocio.cpp
This speeds up the general case by about 30%, and the special/common case of 4 channel float -> 4 channel float by 50%. Most of what remains is inside OCIO.
Note that all the IBA::ocio* functions also use colorconvert underneath, so these will all speed up proportionally.
> IBA::colorconvert(): Speed up color conversions with SIMD

- src/cmake/modules/FindOpenJpeg.cmake
> Update FindOpenJpeg for openjpeg-2.3

- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
Big improvements on avx512 and in some cases avx2.
> simd.h: speed up some load/store ops especially to/from uint16, uint8

- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
I'm seeing a little over 2x improvement for the common special case
of both fg and bg being RGBA float buffers in memory.
> Speed up IBA::over

- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
At least on the system I have, some of the masked partial load/store are
actually slower than the non-avx512 fallbacks, so disable the fancy one
until I find hardware where it truly runs faster.
> Fine tuning of AVX512 partial load/store

- src/cmake/modules/FindNuke.cmake
Adds additional Nuke versions that the FindNuke cmake module can look for.
> add up to date nuke versions to cmake module

- src/libOpenImageIO/imagebuf.cpp
When we write an IB, it presumably changes the pixels, so we should
invalidate the file we're writing if it's in an ImageCache. Also, be
careful that were not writing an "in-place" file that hasn't been read
fully yet (because it's IC-backed).
> ImageBuf::write should be careful about the effect on ImageCache.

- src/ffmpeg.imageio/ffmpeginput.cpp
> Changes to allow building against the new ffmpeg 4.0

- src/tiff.imageio/tiffinput.cpp
Extend the recent work on reading "raw" strips and then decompressing
them ourselves concurrently, to handle "separate" planarconfig as well
as "contiguous". This required another big refactor of
read_native_scanlines.
With this change, even contig images now take the fast path for some
combiations that it didn't before: uncompressed, and zip compressed but
without the horizontal predictor selected.
> TIFF: Overhaul read_native_scanlines to speed up more cases

- src/cmake/modules/FindLibRaw.cmake
Fixes FindLibRaw to work on Windows.
None.
- [ x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ x ] My code follows the prevailing code style of this project.
> Bug fixed FindLibRaw to work also on Windows.

- src/cmake/externalpackages.cmake
Instead of downloading unconditionally, look for system install.
Sorry, this looks like a bigger change than it really is. Most of the "changed lines" are just indented differently because they are enclosed in an `if`.
> Modify robin-map download to look in system first

- src/include/OpenImageIO/platform.h
Replicate the `endian` enum class that will be in C++20 (eventually we'll
eliminate our own) instead of nonstandard tricks.
> More modern way to test endianness.

- site/spi/Makefile-bits-arnold
- site/spi/Makefile-bits-spcomp2
Default Makefiles build to use vanilla boost.
> Default to use vanilla boost

- src/libutil/spinlock_test.cpp
Spring cleaning. This was sitting in my tree since last year.
> spinlock_test: modernize with Benchmarker; also time spin_mutex vs std::mutex

- src/libtexture/texturesys.cpp
Mea culpa. Ramon Montoya alerted me to a problem in 2013 and I either forgot about it, ignored it, or failed to understand it. But I rediscovered his email while trying to purge my inbox of long-ago unresponded emails and decided to look into it again.
The problem situation is that we figure out the filter ellipse based on the derivatives, and then "thicken" it based on the amount of blur requested.  Ramon pointed out that a very uneven amount of blur (very different in s and t) could thicken the minor axis so much more than the major axis that, you know, they aren't the proper axes any more. And that could lead to odd behavior later on, because the samples are laid out along the major axis and assuming in all the math that `majorlegnth >= minorlength`. 
I tried a few approaches, and the …
> Texture: Fix edge case bug in adjust_blur

- src/libutil/farmhash.cpp
> Windows: disable warning in the farmhash code

- src/oiiotool/oiiotool.cpp
This didn't work properly. Example:
oiiotool -pattern constant:color=.1,.2,.3,.4,.5 256x256 5 -chnames R,G,B,A,Z -d half -o 1.exr
oiiotool 1.exr -d Z=float -o 2.exr
would end up with 2.exr having all half channels, not Z float as expected.
What can I say? It was a bug.
> oiiotool fix logic with -d chan=datatype

- src/libOpenImageIO/color_ocio.cpp
If no 'from' space name was provided, it tried to look up the
"oiio:ColorSpace" metadata of the source image, and if that also wasn't
found, fell back on "linear."
But the OCIO config may not literally have "linear" as a color space
name. So instead, the fallback should be on whatever color space has the
*role* of linear (aka scene_linear). This in turn makes the default "no
'from' parameter supplied -> use linear" less prone to error.
> IBA::ociodisplay: better logic for missing 'from' space name

- src/include/imagebufalgo.h
- src/libOpenImageIO/imagebufalgo.cpp
- src/psd.imageio/psdinput.cpp
- src/rla.imageio/rlaoutput.cpp
- fixes build failures of https://github.com/OpenImageIO/oiio.git on Ubuntu 18.04
N/A
- [N/A] If this is more extensive than a small change to existing code, I
- [N/A] I have updated the documentation, if applicable.
- [N/A] I have ensured that the change is tested somewhere in the testsuite
- [N/A] My code follows the prevailing code style of this project.
> Fixed a few compiler warnings issued by gcc 7.3.0-27ubuntu1~18.04

- src/libOpenImageIO/imagebuf_test.cpp
- src/libOpenImageIO/imageinput.cpp
Reported in #2106, there was a subtle bug in read_image/scanline/tile
where we fell into the "contiguous and no data type translation"
case when that was not really the case.
The symptom could be triggered by the following case: You want to read a
1-channel float image into a buffer meant to hold a 4-channel UINT8
image with a 4-byte xstride. The correct behavior is to translate the
floats into uint8's and place them in channel 0 of each 4-channel pixel.
But because the buffer stride length (4 x uint8 = 4 bytes) matched the
native stride length (1 x float = 4 bytes), it was copying the floats
instead of translating and depositing them correctly in channel [0]
(leaving channels [1-3] unchanged).
The fix isn't too hard, but we made the same mistake in several places.
Basically, we were …
> Fix buffer stride logic in ImageInput read methods

- src/tiff.imageio/tiffoutput.cpp
Our TIFF output doesn't support per-channel data types (because the underlying libtiff does not).
This patch makes the TIFF writer check that the spec it's passed doesn't have a filled-in `channelformats` and will refuse to open, with error, if it does.  (Exception: if the vector is filled in but all elements are equal to spec.format, then it's accepted.)
> TIFF output -- check for unsupported per-channel formats

- src/dpx.imageio/dpxinput.cpp
- src/dpx.imageio/dpxoutput.cpp
- src/dpx.imageio/libdpx/DPXHeader.h
> Amend DPX to recognize new transfer/colorimetric code for ADX

- src/libutil/thread.cpp
The thread_pool already attempts to keep track of its worker threads,
and if they themselves attempt to submit tasks to the pool, it will just
execute those recursive tasks immediately rather than enqueuing. This
helps prevent deadlock where all the queue workers are running tasks
which themselves are waiting for other tasks, which are so far back in
the queue that nobody progresses.
But, as Thiago points out in #2131, if there are multiple app threads
submitting to the thread pool simultaneously, you can get into similar
trouble, and since those submitting threads are not themselves pool
worker threads, the "am I a worker" test fails.
Moment of honesty: I'm not sure exactly how this can happen. At first
blush, it seems like it shouldn't matter, but nonetheless it does and I
know from …
> Fix potential threadpool deadlock from recursive use

- src/libOpenImageIO/imagebufalgo_opencv.cpp
> Fix warning in OpenCV area

- src/libOpenImageIO/maketexture.cpp
For the purposes of deciding whether a `maketx -u` command is an
unnecessary repeat, we compare this command line to the last one to see
if it's the same. In so doing, we strip the directories off any
arguments that look like filenames so that changes is how relative path
names are expressed don't cause us to unnecessarily remake the texture.
It's a little naive to do this for all args. Thiago noticed situations
where color space names (args after `--colorconvert`) might have slashes
and so you don't want to strip them of their "directories."
This patch addresses that, and also several other maketx/oiiotool
commands that might have following args that look like filenames but in
fact are not. Also uniformize the interchangeable -cmd and --cmd so that
those pointless differences don't …
> Modify maketx command line directory stripping to be smarter

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
A handy complement to parse_until().
> Strutil::parse_while()

- src/libutil/argparse.cpp
> Bug: fixed possible null ptr dereference

- src/libOpenImageIO/color_ocio.cpp
The fast_rcp had the strange effect of turning alpha=1 into alpha=0.99999994.
Ick!
> Improve precision of unpremult/premult of color conversion

- src/include/OpenImageIO/filesystem.h
- src/jpeg.imageio/jpeg_pvt.h
- src/jpeg.imageio/jpeginput.cpp
- src/openexr.imageio/exrinput.cpp
- src/png.imageio/pnginput.cpp
- src/png.imageio/pngoutput.cpp
* Add read-from-memory for JPEG.
* Add ioproxy read to PNG (only write was supported before).
* Had forgotten before to add correct supports("ioproxy") response to exr
and PNG.
> More work on IOProxy support

- src/libOpenImageIO/imageioplugin.cpp
ImageInput::create(name) and ImageOutput::create(name) are supposed to
create a new II or IO for given name, which can be a filename (such as
"foo.exr", the extension determines the format), or just an extension
(such as "exr"), or the name of the format itself (such as "openexr").
Except that the latter didn't work, due to a botched test of whether
the format name was already in the table. This has been a bug for
many years, so it seems!
> Fix failure to II/IO::create() the format name itself.

- src/heif.imageio/heifoutput.cpp
Turns out that libheif's `write_to_file()` does not throw exceptions
upon write errors, as it is advertised to do. So we didn't catch them
at all. Solve by using the more general `write()` that takes a custom Writer class.
> heif output: catch write errors

- src/include/OpenImageIO/fmath.h
This can get rid of some macro ugliness in https://github.com/imageworks/OpenShadingLanguage/pull/974
> Make OIIO:invert a host/device function

- src/libOpenImageIO/imagebuf.cpp
My callback was never being called!
> Forward ProgressCallback in ImageBufImpl::read

- src/include/OpenImageIO/imagebufalgo_util.h
Internal to ImageBufAlgo functions, we are faced with the fact that we
have 1, 2, or 3 input images in addition to an output image, and they
each could be any of the 9 pixel data types we support (float, uint8,
uint16, half, int8, int16, uint, int, double).  This means that the
template expansion of all possible combination would tend to be 9^2=81
specializations for unary functions, 9^3=729 for binary functions, and
9^4=6561 for ternary functions (I think mad() is the only ternary
function we have).
This is unworkable, leads to infeasible compilation times, so for a
long time we have made the following shortcut: handle the full
cross-product of just the 4 commonly used types (uint8, uint16, float,
half), and in all other cases convert to and from float. So that means
unary needs 16 …
> Make OIIO_DISPATCH_COMMON_TYPES2/3 handle more type combinations.

- src/tiff.imageio/tiffinput.cpp
I don't claim to understand exactly why is is problematic, but certain
files written by an older versin of "nconvert" have something strange
about their tags that was leading to a crash. Solved with use of
our existing safe_tiffgetfield() versus TIFFGetField when retrieving
the PREDICTOR tag.
Also refactored safe_tiffgetfield a bit so that for the calls that
"fail" (results are ignored), it doesn't overwrite the results. Do this
by retrieving into a temp buffer and then copying to the caller's
memory upon success.
TODO: How many other TIFFGetField calls ought to be replaced by
safe_tiffgetfield? All? Some? What are the circumstances that lead to
this inexplicable problem? Is there a better tag-reading idiom we
should be using? Investigating this on all on the side, but it need
not hold up …
> Fix crash reading certain old nconvert-written tiff files

- src/include/OpenImageIO/typedesc.h
Also re-jigger some of the constructors to make them a little compact
by more liberally using default argument values and delegated
constructors.
> TypeDesc: Beef up doxygen-like comments

- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/simd.h
- src/include/OpenImageIO/ustring.h
Submitted on behalf of Patrick Hodoul, with some minor mods by LG.
Fixes #2246
> Fix Windows warnings

- src/doc/conf.py
- src/doc/imagebuf.rst
- src/doc/imagebufalgo.rst
- src/doc/index.rst
- src/include/OpenImageIO/imagebufalgo.h
The latest in my documentation overhaul, in case anybody is interesting in how this is progressing.
> More Doxygen/Breathe/Sphinx: ImageBufAlgo

- site/spi/Makefile-bits
- src/openvdb.imageio/CMakeLists.txt
Also some adjustments for SPI only for where to find it properly, we
have weird paths.
> vdb reader build pulled in the tbb libraries using wrong CMake variable.

- src/include/OpenImageIO/fmt/core.h
- src/include/OpenImageIO/fmt/format-inl.h
- src/include/OpenImageIO/fmt/format.h
- src/include/OpenImageIO/fmt/ostream.h
- src/include/OpenImageIO/fmt/printf.h
Resolves #2276 
I don't expect anybody to "review" the code itself, it's just syncing with the latest fmtlib.
But perhaps @yann-lty can try building from this PR and see if it avoids the error? (If it works, I will also backport to RB-2.0 if you need it there.)
> Update fmt implementation to fix windows warnings

- src/rla.imageio/rlainput.cpp
Previously, any 32 bit channel would force the "single best type" to be float.
But what if it was a 32 bit int?
Instead, use our standard type_merge logic, where we've carefully considered
all the edge cases.
> RLA: fix logic for determining single best type for all channels

- src/nuke/txWriter/txWriter.cpp
Updates to the Nuke txWriter knob interface, based on changes we needed to make internally:
- Expose "highlight compensation" option (necessary for HDR processing)
- Expose constant color, monochrome, and opaque detection options
- Remove mostly redundant (and broken) "output stats" knob
- Write "Software" metadata containing OIIO and Nuke version strings
At some point I want to try building a more general interface for setting attributes in the outgoing `ImageSpec` using the available Nuke knob types (which are... limited), but I'll submit a separate PR later if that experiment comes to anything.
Not really CI-compatible, but I've put it through its paces pretty well internally.
([individual](../src/doc/CLA-INDIVIDUAL), and if …
> [Nuke] Expose additional `make_texture` options through the txWriter

- CMakeLists.txt
- src/include/OpenImageIO/export.h
- src/include/OpenImageIO/simd.h
- src/iv/ivmain.cpp
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/farmhash.cpp
Small fixes allowing to build OpenImageIO with mingw
> Some fixes to allow build with mingw

- src/raw.imageio/rawinput.cpp
- testsuite/raw/ref/out-libraw0.18.11.txt
- testsuite/raw/ref/out.txt
> Remove references to fields deprecated in libraw master

- src/include/OpenImageIO/simd.h
Amendment to #2299: I was over-zealous in use of an intrinsic.
> Fix rotl for avx512

- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
The recent AttrDelegate and other notational improvements lead to a clearer and
more compact way to express and extract modifiers as ParamValueList instead
of parsed maps of strings.
> oiiotool internals: overhaul optional modifier processing

- src/libutil/ustring.cpp
- src/libutil/ustring_test.cpp
The main change here is to tune the default size and shard count for the ustring table. The average workstation has changed quite a bit since I last measured the performance of this code, and a simple tweak to these constants gives a nice speed boost on the `ustring_test` stress test.
On a machine with 100+ hardware threads, the new code stays efficient much longer. Previously the wedge test maxed out around 14% efficiency, and its close to 100% under the new code.
Measuring the cost of making 2M ustrings with a single thread is around 0.5s, while with all threads running at once (one will make progress while the others wait) it takes 4.0s (vs. 24.2s before this change).
On a more modest machine with 32 hardware threads, the tuned code is also faster (27% efficiency for the wedge test …
> Performance tuning for ustring table

- src/include/OpenImageIO/SHA1.h
- src/libutil/SHA1.cpp
Fixes #2337 
Wth a big hammer -- upgrade SHA1 from the source and hope for the best.
> Upgraded to a more recent sha1 implementation.

- .github/workflows/workflow.yml
- src/build-scripts/build_openexr.bash
- src/build-scripts/ci-build-and-test.bash
- src/build-scripts/ci-startup.bash
- src/build-scripts/gh-win-installdeps.bash
- src/build-scripts/install_homebrew_deps.bash
- src/build-scripts/install_test_images.bash
It's not entirely working yet -- I can get a more or less full build,
but am having trouble with tests. But I'd like to merge the
refactoring and progress I've made so far.
> Working towards Windows builds on GitHub Actions CI

- .github/workflows/workflow.yml
- .travis.yml
- src/build-scripts/gh-installdeps.bash
- src/build-scripts/gh-win-installdeps.bash
- src/cmake/compiler.cmake
- src/cmake/modules/FindFFmpeg.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/openvdb.imageio/CMakeLists.txt
* Add more test matrix cases, include gcc8/9 builds.
* Fix some warnings with various compile versions.
> GitHub CI tweaks

- CHANGES.md
- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool/ref/out.txt
- testsuite/oiiotool/run.py
// is integer division (like in Python3)
% is integer modulus
Examples:
{7/3}  --> 2.33333
{7//3} --> 2
{7%3}  --> 1
> Extend oiiotool expression eval with // and %

- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/platform.h
- src/iv/ivgl.cpp
- src/libOpenImageIO/exif.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_addsub.cpp
- src/libOpenImageIO/imagebufalgo_channels.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagebufalgo_deep.cpp
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/maketexture.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/texoptions.cpp
- src/libtexture/texturesys.cpp
- src/libutil/argparse.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_imagebuf.cpp
- src/rla.imageio/rlaoutput.cpp
- src/testtex/testtex.cpp
- src/tiff.imageio/tiffoutput.cpp
* Make sure alloca is properly declared on all platforms by including cstdlib in platform.h.
* Change all stray ALLOCA and alloca to OIIO_ALLOCA.
> alloca cleanup

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
This is a revision of #2350. I like this solution better.
> Cleaner PIMPL idiom for ImageBuf

- src/python/py_oiio.h
Was making lots of warnings on Windows.
> Fix cast warning

- src/iff.imageio/iffoutput.cpp
In the header, the total number of tiles is stored as uint16.
> IFF: be mindful of max resolution

- src/targa.imageio/targainput.cpp
- src/targa.imageio/targaoutput.cpp
Several areas to be more careful, but ultimately Targa headers contain
uint16 resolution values and uint32 tag offsets within the file.
> Targa big file and int overflow safety

- src/include/OpenImageIO/dassert.h
The new preferred assertion macro, OIIO_ASSERT, tests a condition, and
if not true, prints an error message and aborts for debug builds. For
release builds, only tests and reports the error, but does not abort.
OIIO_DASSERT is identical for debug buils, but does nothing at all for
release builds (not even test the condition).
ASSERT and DASSERT are the old macros, but because of namespace
pollution and less desirable behavior, we consider them deprecated
want to phase out their use. (In a separate review we'll convert calls
to these.)
Moving forward, then, the attitude about assertions should be:
* OIIO_ASSERT for when you want an error message in all cases, and also
abort for debug builds (but not release builds).
* OIIO_DASSERT when you want error/abort for debug builds, and nothing
for …
> Assertion overhaul

- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
This resulted from some post-commit discussion on issue #2301
> Simplify isfinite idiom.

- LICENSE-THIRD-PARTY.md
- src/doc/oiiointro.rst
- src/gif.imageio/gif.h
We have used this for a long time to write animated gifs. Just updating
from its git repo.
Also noticed that we neglected to list it in the docs where we
acknowledge 3rd party embedded software and licenses. Sorry.
> Update gif.h from original source

- src/include/OpenImageIO/platform.h
Inspired by some work by Alex Wells in the OSL project.
> platform.h: helpful macros for dealing with pragmas

- src/cineon.imageio/libcineon/CineonHeader.h
- src/dpx.imageio/libdpx/DPXHeader.h
- src/dpx.imageio/libdpx/RunLengthEncoding.cpp
- src/dpx.imageio/libdpx/Writer.cpp
- src/iv/imageviewer.cpp
- src/iv/ivgl.cpp
- src/libtexture/texturesys.cpp
- src/oiiotool/oiiotool.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
- src/targa.imageio/targainput.cpp
- src/testtex/testtex.cpp
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
- src/webp.imageio/webpinput.cpp
- src/zfile.imageio/zfile.cpp
This is the last installment for now.
> Address strict warnings about unused parameters to functions (pt 3)

- INSTALL.md
- Include some of the various package manager that can be used to manage dependencies libraries.
- Removed some missing links in the instructions.
- Added vcpkg method for Windows build.
Signed-off-by: Mei Chu <meimchu@gmail.com>
> Updated INSTALL instructions.

- src/cmake/modules/FindOpenColorIO.cmake
- src/include/OpenImageIO/color.h
- src/libOpenImageIO/color_ocio.cpp
- src/python/py_colorconfig.cpp
- testsuite/python-colorconfig/ref/out-noocio-python27.txt
- testsuite/python-colorconfig/ref/out-noocio.txt
- testsuite/python-colorconfig/ref/out-ocio2-python27.txt
- testsuite/python-colorconfig/ref/out-ocio2.txt
- testsuite/python-colorconfig/ref/out-python27.txt
- testsuite/python-colorconfig/ref/out.txt
- testsuite/python-colorconfig/src/test_colorconfig.py
Added Role accessors to ColorConfig class.
Added OpenColorIO_STATIC define (needed to pass Windows dllimport definitions)
> OCIO improvements

- src/iinfo/iinfo.cpp
- src/rla.imageio/rlainput.cpp
> RLA: sanity checks to detect corrupt or non-RLA files and prevent crashes

- src/include/OpenImageIO/fmath.h
> fmath: add vint versions of clamp

- src/raw.imageio/rawinput.cpp
> raw: use mutex to guard non-reentrant LibRaw constructor

- src/doc/oiiotool.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/color_ocio.cpp
> Adjust to API changes in OpenColorIO v2

- src/include/OpenImageIO/oiioversion.h.in
People have occasionally asked for this.
> Handy macro to construct an integer version code

- .github/ISSUE_TEMPLATE/bug_report.md
> fix minor typo in bug report issue template

- src/doc/builtinplugins.rst
- src/png.imageio/pngoutput.cpp
> PNG output: add "png:filter" to control PNG filter options

- src/python/py_imagespec.cpp
- testsuite/python-imagespec/ref/out-python3.txt
- testsuite/python-imagespec/ref/out.txt
- testsuite/python-imagespec/src/test_imagespec.py
> Fix python binding of ImageSpec.erase_attribute

- site/spi/Makefile-bits
> Add llvm-11.0.0 to Makefile-bits.

- src/include/OpenImageIO/simd.h
https://en.wikipedia.org/wiki/Elbrus_2000
From Michael Shigorin
> Fix build for Elbrus 2000 architecture

- src/doc/pythonbindings.rst
- src/python/py_imageinput.cpp
> Restore missing python ImageInput.read_image signature

- src/cmake/externalpackages.cmake
Sometimes the true minimum version of a dependency that we are able to
build against is lower than the minimum *recommended* version (perhaps
because some important feature was added in a subsequent release that
we would like to expose if available).
This patch allows checked_find_package to take two new optional
arguments: RECOMMEND_MIN is the minimum *recommended* version (but
not the true rejection minimum) and RECOMMEND_MIN_REASON is some text
to add to the error message if there is a succinct explanation for why
we recommend a higher version than the true minimum.
As an example, we will (currently) build against any OpenEXR 2.x. But
if it's not at least 2.2, we can't support DWAA and DWAB compression.
> Enhancements to checked_find_package

- src/oiiotool/oiiotool.cpp
> Improved IB error message for corrupted input

- src/include/OpenImageIO/platform.h
> Declare aligned_malloc and aligned_free as OIIO_API

- src/iv/ivmain.cpp
> Convert iv to use new style argparse

- .readthedocs.yml
> Make readthedocs generate downloadable html as well as pdf

- src/build-scripts/install_homebrew_deps.bash
> Work around GHCI Mac problem with homebrew openssl

- src/gif.imageio/gif.h
- src/gif.imageio/gifinput.cpp
- src/gif.imageio/gifoutput.cpp
- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
> Support UTF-8 filenames for GIF

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/build_gif.bash
- src/build-scripts/build_ninja.bash
- src/cmake/externalpackages.cmake
Also add build scripts for ninja and gif.
> CI: Make sure we test the latest fmt, PugiXML, and pybind11 releases

- src/doc/maketx.rst
Removed some duplicates in documentation
> Removed some duplicates in maketx.rst doc

- src/psd.imageio/psdinput.cpp
- testsuite/psd/ref/out-alt.txt
- testsuite/psd/ref/out.txt
Loads the icc profile from the file and adds it to the common specs.
> Add ICC profile support for PSD input

- src/heif.imageio/heifinput.cpp
* 0 size metadata causes an issue in the libheif cxx wrapper
* fixes #2794
I have tested with the samples from #2794 
Upstream fix: https://github.com/strukturag/libheif/pull/415
> Fix error decoding Apple HEIF files

- testsuite/heif/ref/out-libheif1.9-with-av1.txt
- testsuite/heif/run.py
> Fix tests with libheif built without AV1 support

- src/build-scripts/gh-installdeps.bash
> Re-enable libheif for Ubuntu

- src/libOpenImageIO/xmp.cpp
- testsuite/psd/ref/out-alt.txt
- testsuite/psd/ref/out.txt
* Better handling of lists/sequences -- append into attribute arrays
instead of allowing each value to overwrite the previous one.
* Better inference of unknown attributes that look like int, float, or
rational, rather than cramming into strings.
* Fixed what I now think were bugs in handling rational values.
Fixes #2874
> Improve parsing of xmp records

- src/build-scripts/OpenImageIO.pc.in
> pkgconfig OpenImageIO.pc was setting include dir one level too deep

- src/libOpenImageIO/imageio.cpp
Change imageio.cpp convert_from_float to use the convert_type function
from fmath.h, rather than defining redundant functionality in that
module.
This has the added benefit that the ones in fmath.h have some interesting
specializations to use SIMD ops and other optimizations that the one-offs
in imageio.cpp lacked.
> Remove redundant format conversion code from imageio.cpp.

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
I need these utilities for something coming in a later PR.
> Strutil: add find, rfind, ifind, irfind

- src/cmake/compiler.cmake
- src/cmake/externalpackages.cmake
- src/igrep/igrep.cpp
- src/iinfo/iinfo.cpp
- src/libOpenImageIO/formatspec.cpp
- src/libutil/filesystem.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/printinfo.cpp
This is safe in master, now that gcc4.8 is not on the menu.
> Remove last remnants of boost regex

- src/cmake/checked_find_package.cmake
Both global and per-package controls have been added to our
checked_find_package cmake function, to cause it to first check for
an exported config for the dependency, and only if not found, revert
to potentially using a FindPackage.cmake module.
This reflects our general leaning toward assuming that a package that
exports a cmake config probably does a better job of it than we would
do writing a Find module for it.
> CMake: Make checked_find_package able to prefer configs

- .github/workflows/ci.yml
(Note: the new test will fail until #3003 is merged; they are related.)
> CI: make a specific test for buildling with clang11 and C++17

- src/openexr.imageio/exrinput_c.cpp
- testsuite/missingcolor/ref/out.err-openexrcore.txt
- testsuite/oiiotool-readerror/ref/out.err-opencore.err.txt
- testsuite/oiiotool-readerror/ref/out.err-openexrcore.txt
The core API has been made consistent with the language in the file
layout documentation. This is an update after that lands
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>
> Updates after API simplification pass in EXR master

- src/openexr.imageio/exrinput.cpp
These just weren't used at all, relics of the long distant past.
Seems like at some point we only read through the "part" interface,
even for files that are not multipart.
> openexr reader internals: Remove unused fields

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
Also improve comment documenting get_directory_entries, I realized it
was a little garbled.
> filesystem.h: Switch some methods to using string_view

- INSTALL.md
This PR fixes various broken links in the  `INSTALL.md` file.
N/A
- [N/A] If this is more extensive than a small change to existing code, I
- [N/A] I have updated the documentation, if applicable.
- [N/A] I have ensured that the change is tested somewhere in the testsuite
> PR: Fix broken section links in "INSTALL.md" file.

- src/doc/imageioapi.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
* Honor env $OPENIMAGEIO_FONTS as an additinal font searchpath.
* Global attribute "font_searchpath" as an additional font searchpath.
* Refactor and simplify the code that assembles the list of directories
to search.
> Improvements to font finding

- src/include/OpenImageIO/fmath.h
- src/libutil/fmath_test.cpp
* More clearly document, test, and correctly handle the cases where
the value < 0.
* Add `round_down_to_multiple`.
> fmath: Improvements to round_to_multiple

- src/libutil/stb_sprintf.h
Solves some security problems and/or just false positives in
address sanitizer.
> Update to newer stb_printf for our implementation of vsnprintf

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindJPEGTurbo.cmake
- src/doc/builtinplugins.rst
- src/jpeg.imageio/jpeg_pvt.h
- src/jpeg.imageio/jpeginput.cpp
- src/jpeg.imageio/jpegoutput.cpp
IOProxy was already supported for JPEG input.
> JPEG output IOProxy support

- src/cmake/testing.cmake
> Testing: Gracefully handle failing to find git for test data download

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
To try to combat long template instantiation times, did some refactoring
on the ImageBuf iterators:
* Pushed more functionality from the templated Iterator and
ConstIterator to the non-templated base class IteratorBase. This
should reduce the amount of code that is separately instantiated for
every data type, in every module that uses iterators.
* Pushed many implementations from inline defined in imagebuf.h to
separately compiled in imagebuf.cpp. The most important methods that
are called on every pixel are still inline, but we are switching to
separate compilation for all the methods that are only called upon
construction (once per image being iterated over) and most of the
code that is called only when we wrap to the next scanline.
* Some other miscellaneous refactor to remove …
> Refactor ImageBuf::Iterator, ConstIterator

- INSTALL.md
Just a note to INSTALL.md that git might be required
> Mention that git is needed for certain dependencies

- src/doc/imageioapi.rst
The reference in the docs were broken when referencing the Python bindings.
N/A
N/A
> [DOCS] Fix the reference to the python bindings file

- src/doc/Doxyfile
- src/doc/Makefile
- src/doc/builtinplugins.rst
- src/doc/iconvert.rst
- src/doc/imagebufalgo.rst
- src/doc/imageinput.rst
- src/doc/imageioapi.rst
- src/doc/imageoutput.rst
- src/doc/stdmetadata.rst
- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/imageio.h
* Clean up references.
* New explanaions about input and output configuration hints.
* More code examples in both C++ and Python.
* Fix some formatting flubs.
> Docs improvements

- src/doc/imageoutput.rst
* Add Python examples comprehensively to the ImageOutput chapter.
* Clean up some of the C++ code, too, using more modern idioms.
> Docs: more C++/Python dual examples

- src/tiff.imageio/tiffinput.cpp
- testsuite/tiff-depths/ref/out.txt
- testsuite/tiff-depths/run.py
> TIFF: make it work for 16-bit palette images

- src/include/OpenImageIO/string_view.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Brings us more in line with C++17 std::string_view.
> Fully templatize our string_view

- .github/workflows/ci.yml
Just some renames and minor refactoring as I settle into the "strategy"
style.
> Minor tweaks to CI workflow

- src/cineon.imageio/cineoninput.cpp
- src/iinfo/iinfo.cpp
- src/libOpenImageIO/formatspec.cpp
- src/libutil/hash_test.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/ptex.imageio/ptexinput.cpp
- src/python/py_imageoutput.cpp
- src/python/py_oiio.cpp
- src/python/py_roi.cpp
- src/raw.imageio/rawinput.cpp
- src/sgi.imageio/sgi_pvt.h
- src/sgi.imageio/sgiinput.cpp
- src/sgi.imageio/sgioutput.cpp
Bit by bit, we convert all our formatted string from the sprintf
convention to the std::format convention.
> More format conversion

- src/libutil/SHA1.cpp
- src/libutil/paramlist_test.cpp
- src/oiiotool/oiiotool.cpp
- src/psd.imageio/psdinput.cpp
- src/term.imageio/termoutput.cpp
- src/tiff.imageio/tiffoutput.cpp
Fixing a few small things that MSVC complains about when building oiio.
> Fix a number of small warnings on windows

- src/libOpenImageIO/imagebufalgo_compare.cpp
Reminder: isConstantColor() finds out if an ImageBuf is constant
color.  It uses the thread pool to check several areas in
parallel. Once any task finds that its subregion is not constant, it
sets a flag so that as other subregions are pulled off the task queue,
they will take an early out if one of their siblings already knows the
image is not constant.
Turns out this isn't much of a big savings in practice, because lots
of regions may be in flight by the time one region realizes it's
non-constant, and once a region task starts, it doesn't check the flag
again.
This patch speeds up isConstantColor by a pretty big factor for
non-constant images (it can't really help for images that ARE
constant) in the following ways:
1. Before doing anything, it checks to see if the FIRST TWO pixels of …
> Speed up IBA::isConstantColor

- src/include/OpenImageIO/simd.h
- src/libtexture/environment.cpp
- src/libtexture/texture3d.cpp
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
- src/libutil/paramlist.cpp
- src/libutil/thread.cpp
- src/socket.imageio/socket_pvt.cpp
* Everything in texture system
* simd.h
* thread.cpp
* paramlist
> More unity-ready changes

- src/gif.imageio/gifoutput.cpp
- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- src/png.imageio/pnginput.cpp
- src/png.imageio/pngoutput.cpp
- src/targa.imageio/targaoutput.cpp
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
gif, png, targa, tiff, openexr
> More changes to support unity/jumbo builds

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/build_llvm.bash
- src/build-scripts/ci-build.bash
- src/build-scripts/gh-installdeps.bash
- src/libtexture/texturesys.cpp
- src/oiiotool/oiiotool.h
A couple very minor changes were necessary to address new warnings.
> CI: add clang14 test

- src/cmake/Config.cmake.in
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenColorIO.cmake
- src/cmake/testing.cmake
We were using it inconsistently. Switch to OpenColorIO_FOUND everywhere.
> Straighten up OpenColorIO_FOUND vs OPENCOLORIO_FOUND

- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
It's a very minor internal idiom modernization.
> TextureSystem: Change internal hq_filter to std::unique_ptr

- src/psd.imageio/psdinput.cpp
Try to have an error message for every possible failure.
> PSD: beef up error message to help track down PSD failures

- src/build-scripts/build_opencolorio.bash
> update ocio to 2.1.2

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
Handy utility, will use in a subsequent PR
> Strutil::safe_strlen

- src/targa.imageio/targainput.cpp
It was getting too big. Split off the tga-2.0 header reading parts
into a separate method.
> Refactor TGAInput::open to simplify.

- .github/workflows/analysis.yml
- .github/workflows/scorecards.yml
- src/bmp.imageio/bmp_pvt.cpp
- src/iff.imageio/iff_pvt.cpp
- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/ustring.h
- src/jpeg.imageio/jpegoutput.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo_yee.cpp
- src/libutil/stb_sprintf.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
- src/oiiotool/oiiotool.cpp
- src/psd.imageio/psdinput.cpp
- src/python/py_roi.cpp
- src/python/py_typedesc.cpp
- src/tiff.imageio/tiffinput.cpp
Also re-split the scorecard workflow from the analysis workflow.
> Miscellaneous static analysis warning issues

- .github/workflows/analysis.yml
- src/jpeg.imageio/jpegoutput.cpp
- src/libOpenImageIO/color_ocio.cpp
- src/libutil/filesystem_test.cpp
- src/libutil/paramlist.cpp
- src/sgi.imageio/sgioutput.cpp
- src/softimage.imageio/softimageinput.cpp
Knocking these out a few at a time
> Several minor fixes for Sonar warnings

- src/cmake/compiler.cmake
> Build: Don't force MACOSX_RPATH on

- src/libtexture/imagecache.cpp
When enforcing the max open files limit, there's a heuristic where we
only "try" to get the lock, and if we can't, rather than block, we
just defer the cleanup step until the next time around. So what if we
go slightly over the limit temporarily?
Interesting edge case: what if max_open_files is relatively low, but
the number of threads is very high and you have a high contention rate?
Then you can end up *significantly* over the limit, because almost all
the threads say "somebody else has the lock, I'll leave it to them to
clean up" and blithely open new handles.
So this patch modifies the logic so we do the defer trick only if
we're only a little over the limit. If we've exceeded the limit by
16 handles, grab the lock unconditionally and do the cleanup.
> ImageCache: improve file handle limits under heavy thread contention.

- CHANGES.md
- CMakeLists.txt
We have branched 2.4 and released its first beta.
This patch bumps the "master" version to the 2.5 series.
> This is now the branch that leads to 2.5

- src/png.imageio/png_pvt.h
> PNG: fix memory leak when error takes early exit

- src/raw.imageio/rawinput.cpp
- testsuite/raw/ref/out-libraw-0.20.2-gh.txt
- testsuite/raw/ref/out-libraw-0.20.2.txt
- testsuite/raw/ref/out-libraw0.18.8-gh.txt
- testsuite/raw/ref/out-libraw0.18.8-gh2.txt
- testsuite/raw/ref/out-libraw0.19.5-gh.txt
- testsuite/raw/ref/out-libraw0.20.0-gh.txt
- testsuite/raw/ref/out-libraw0.20.0.txt
- testsuite/raw/ref/out-libraw0.21.0-gh.txt
- testsuite/raw/ref/out-libraw0.21.0-mac.txt
- testsuite/raw/ref/out.txt
This is an addendum to #3561 to fix reference output
> Update ref output after recent raw change and clang-format

- src/cmake/testing.cmake
- testsuite/iinfo/ref/out.txt
- testsuite/iinfo/run.py
- testsuite/runtest.py
Believe it or not, iinfo was never run in the testsuite before this!
> Testing: make a test specifically for iinfo

- src/cmake/testing.cmake
Quoted it wrong the first time
> Fix exr core test options

- src/doc/builtinplugins.rst
- src/libOpenImageIO/imageinout_test.cpp
- src/rla.imageio/rlainput.cpp
- src/rla.imageio/rlaoutput.cpp
Also take the opportunity to convert to std::format style formatting and output.
> RLA IOProxy support

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
Also cull some cruft that no longer is used for OIIO >= 2.4
> Filesystem::is_executable and find_program

- src/jpeg.imageio/jpegoutput.cpp
> Fix type mismatch warning in JPEG code

- src/oiiotool/printinfo.cpp
We weren't copying the full spec, so didn't get the channel names.
> oiiotool --dumpdata : fix channel name output

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/simd.h
> Some fixes for compilation with MSVC for Windows ARM64

- src/build-scripts/build_openexr.bash
> bump to 3.1.5 for vfxreferenceplatform cy2022

- src/cmake/testing.cmake
- src/igrep/igrep.cpp
- testsuite/igrep/ref/out.txt
- testsuite/igrep/run.py
Add exception safety in igrep test.
> Add testsuite coverage of igrep utility

- src/raw.imageio/rawinput.cpp
> fix(raw): handle raw 1-channel raw images

- src/libOpenImageIO/imagebufalgo_draw.cpp
Chris Gloor points out that after my latest change, the "font_dir_list" got loaded with every directory underneath that it discovered through that one level of recursion. Not harmful, but very cluttered. My original intention was for font_dir_list to only have the search path directories.
So this prompted me to do a bigger refactor to fix that up and clean up some other things. Now all the searching is done once when it builds up the initial inventory the first time a font is needed, no more potential directory searching or touching non-essential files for each font-using operation.
> refactor: refactor font search

- .github/workflows/ci.yml
- src/cmake/testing.cmake
Because it's broken in exr core!
> test: Don't run exr core version of openexr-compression testsuite

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
Based on a suggestion Matt Chaput on the oiio-dev mail list.
> feat(oiiotool): expression eval NIMAGES gives current stack depth

- src/include/OpenImageIO/strutil.h
This is a continuation/fix for #3825
> One more revision to synchronized Strutil::print

- CONTRIBUTING.md
- SECURITY.md
Just a routine update of these files as I proofread them in light of the move to ASWF. This patch is addressing the "old" project, there will be further ASWF-specific edits for changes that will take effect after the project is fully moved.
> docs: Update CONTRIBUTING and SECURITY

- CONTRIBUTING.md
- README.md
- RELEASING.md
- src/doc/index.rst
Everybody please go to https://lists.aswf.io/g/oiio-dev and sign up for the new mail list as soon as possible. The old list is on its last legs and having trouble, let's get this done.
> admin: Update mail list URL

- src/doc/builtinplugins.rst
> docs(raw): Fix explanation of raw:Exposure config hint

- RELICENSING.md
For the relicensing request in #3905 and signed with my personal PGP key.
> relicensing: Add DevilishSpirits to RELICENSING.md

- .github/ISSUE_TEMPLATE/build_problem.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
The most important fix is to remove links to the old CLAs and update references to the mail list to the new one.
Also spruced up some language while I was there, hopefully to coax out improved PRs and Issues.
> admin: Update pull request and issue templates

- src/libOpenImageIO/color_ocio.cpp
First, some background: In the course of working toward OIO 2.5, we added some heuristics that used OpenColorIO 2.2's new isColorSpaceLinear, and also using its new "built-in config" to figure out if an arbitrarily named color spaces in a user's config were equivalent to some built-in ones that are commonly used.
All seemed well until... we recently discovered that it was moderately expensive (~0.1s per color space!) on the OCIO side, which wasn't particularly noticeable when I was testing, but can add up to several seconds of needless startup time when inventorying large configs with dozens and dozens of color spaces. And even worse, it was exceptionally expensive for color spaces with LUT3Ds because of a bug on the OCIO side that would invert the 3D LUT needlessly (taking >10s per LUT3D …
> fix: Overhaul of ColorConfig internals to solve perf issues

- testsuite/python-imageinput/ref/out-python3-win.txt
> admin: Adjust repo location

- src/libOpenImageIO/imagebufalgo_test.cpp
Testing to make sure we can convert an IC-backed IB to a cv::Mat.
Related to issue #3800 and PR #4013
> testing: Add opencv regression test

- src/include/OpenImageIO/simd.h
Don't want that include for Cuda compilation, either.
> build: fix include guard

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
Historically, ImageBuf has provided Iterator for writing to mutable IB's and ConstIterator for reading into IBs. If you initialized an Iterator to an IB that was ImageCache-backed (and therefore by definition not mutable), it would convert the IB to the mutable kind (basically by allocating the memory and reading the file through the IC, thus freeing the IB of its dependence on the cache.
An important bug was fixed by PR 3997, which kinda proved that people were not depending on this behavior, since it would tend to fail. But it also got me thinking about to what degree the whole Iterator vs ConstIterator was really necessary, or did it just make things harder for users.
In this proposed patch, we change the Iterator behavior so that instead of immediately making the IB writable as soon …
> feat(ImageBuf): make IB::Iterator lazy in its making the image writable

- .mailmap
Please look this over. If you are one of the duplicated names and I haven't chosen your preferred canonical email (I made my best guess), please comment here with corrections.
> admin: Account for duplicate emails in the .mailmap

- .github/workflows/analysis.yml
- .github/workflows/ci.yml
- sonar-project.properties
- src/build-scripts/ci-build.bash
- src/build-scripts/ci-coverage.bash
- src/build-scripts/ci-startup.bash
This broke some time back, probably partly related to our change in repository home. This seems to get it mostly working? The reports are still not showing up, but I think the solution might be to make sure this is checked into master, so we need to merge this before assessing whether there is more work to be done in this area.
> ci: Repair Sonar scanner analysis

- .github/workflows/release-notice.yml
The one we were using is broken. John's is surely the GOAT notifier.
> admin: Switch to jmertic's slack notifier action

- src/include/OpenImageIO/simd.h
Some of the ways we were using unions for type punning in the vbool16 class were unnecessary, as both union members were basically the same type. Simplify by getting rid of the unnecessary m_bits union member.
This also makes Sonar static analysis happier about these dubious uses of unions for type punning.
> refactor(simd.h): Simplify vbool16 casting

- src/doc/imageinput.rst
- testsuite/docs-examples-python/src/docs-examples-imageinput.py
> docs: Fix python example

- .github/workflows/analysis.yml
- .github/workflows/ci.yml
> ci: Switch away from deprecated GHA idiom set-output

- src/build-scripts/build_ninja.bash
> Fix download ninja and download directory

- .github/workflows/scorecard.yml
Also rename file so it matches what's listed in the file to trigger it.
> ci: Update scrorecard workflow to fix breakage

- src/libutil/filesystem.cpp
> Fix: repair bug in Filesystem::unique_path on Windows

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
Format string didn't match the number of arguments.
> fix: Incorrectly formed debug output

- src/cmake/externalpackages.cmake
> build(deps): Raise Robin-map minimum to 1.2.0

- src/cmake/build_libjpeg-turbo.cmake
Build and link missing libjpeg-turbo shared + static libs
> build(deps): Add libjpeg-turbo recipe

- src/include/OpenImageIO/span_util.h
* Added as_bytes and as_writable_bytes that convert spans of arbitrary type to spans of std::byte. (This mimics C++20 utilities of the same name.)
* spancopy, spanset, spanzero: add parameter defaults for the common case of wanting to do the operation on the whole span, also simplify the bound-limiting logic in those functions a bit (but still performing precisely the same task).
> dev: span utility improvements

- src/doc/imageinput.rst
- testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
- testsuite/docs-examples-python/src/docs-examples-imageinput.py
Convert scanline C++ and Python examples from the "imageinput" chapter into tests within the "docs-examples" testsuites (https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/3992).
nonconforming.
> docs:imageinput-scanlines

- .github/workflows/scorecard.yml
Experimental. But I can't seem to get it to run without a PR to test it.
> ci: Make scrorecards workflow not fail constantly

- THIRD-PARTY.md
- docs/dev/Build_Profiling.md
- src/build-scripts/ninjatracing.py
- src/cmake/compiler.cmake
> build: add option for build profiling with clang -ftime-trace

- SECURITY.md
Proposed revision to security version policy post 3.0 branch.
> admin: Update SECURITY.md for 3.0 beta

- testsuite/heif/ref/out-libheif1.9-alt2.txt
- testsuite/heif/ref/out-libheif1.9-with-av1-alt2.txt
The latest libheif patch release changed something very slightly that requires us to update some saved reference output.
> deps: Add new ref output for libheif updates

- README.md
- docs/QuickStart.md
Having such a document is one of the remaining steps to getting our OpenSSF Best Practices silver level badge.
> doc: Quickstart guide

- SECURITY.md
- docs/dev/RELEASING.md
Fixes #4403
Also updated some other language in the RELEASING.md document.
> admin: Document how to make signed release tags

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
Convenience function to safely read one line of text from an open FILE* and return it as a string.
> feat: Filesystem::getline()

- .github/workflows/analysis.yml
- .github/workflows/build-steps.yml
Safer than letting it inherit all secrets.
> ci: Only pass build-steps the secrets it needs

- .github/workflows/analysis.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/scorecard.yml
* Fix syntax error, other minor touch-ups
* Don't run other workflows when only scorecard.yml changes
> ci: Unbreak the scorecard workflow

- .gitignore
Prevents people from accidentally committing their Visual Studio configuration files.
> admin: Add ".vs" to .gitignore

- src/libOpenImageIO/oiio_gpu.cpp
Sonar was complaining that initialize_cuda() contained a loop that would only iterate once. Upon looking, this was true, but mainly because we just didn't adequately check errors. Fix up, which should both make the code more robust and also silence the Sonar complaint.
> refactor: Rearrange initialize_cuda() for better err check, no warn

- src/iv/imageviewer.cpp
- src/iv/imageviewer.h
Drag and drop of files. Tested on my own Mac and it seem to work just fine.
Fixes #4771
> feat(iv): Implement files drag and drop into an iv window

- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
Fix some `oiiotool --missingfile` behavioral corner cases:
When substituting, warn rather than making a true error. This didn't seem like a big deal for a single command line, but when doing a loop over frames, it would prevent correct behavior from pressing on to the next iteration.
How big is the substitute image? It uses the rez and channels of the first image successfully read (if available). But it when in a frame loop, it resets this on every iteration, so any missing frame looks like it doesn't have a good size guess -- but it does, as long as it's not the first iteration of the loop. This involves safely gettingthe first image dimensions from the *parent* (each iteration is a child Oiiotool object).
> fix(oiiotool): fixes to --missingfile behavior

- CHANGES.md
- CREDITS.md
- docs/CHANGES-2.x.md
Just my periodic updating of the CHANGES doc in main.
Will merge immediately, as it's administrative docs.
> docs: CHANGES update
