- src/libOpenImageIO/imagebufalgo_compare.cpp
By not passing the nthreads param to the parallel_for_chunked loop,
it was always running fully threaded instead of being controlled by
the nthreads passed to it.
> IBA::computePixelStats was not properly controlling the number of threads

- src/oiiotool/oiiotool.cpp
I can't think of any reason why the old code was making a custom
cache, but it interfered with setting certain cache options from
the command line.
> oiiotool: use a shared IC

- src/cmake/externalpackages.cmake
The FindBoost.cmake interface is broken if it uses boost's installed cmake
output (e.g. boost 1.70.0, cmake <= 3.14) at least in the case that boost
was installed to a non-standard prefix. Specifically it fails to set
variables as indicated in FindBoost.cmake documentation. So until that's
fixed force FindBoost.cmake to use the original path which is consistent
with its docs.
> Work around find_package() failure for boost versions with cmake output

- src/include/OpenImageIO/fmath.h
- src/libutil/fmath_test.cpp
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
- testsuite/tiff-depths/ref/out.txt
- testsuite/tiff-depths/run.py
- testsuite/tiff-suite/ref/out-alt.txt
- testsuite/tiff-suite/ref/out-jpeg9b.txt
- testsuite/tiff-suite/ref/out.txt
- testsuite/tiff-suite/run.py
In the process, move some bit depth serializing functions into fmath.h so
we can reuse it. (It's not float math exactly, but it is bit depth conversion,
which for historical reasons we also have here.)
> TIFF fixes: enhance r/w of 6, 14, and 24 bit per sample images.

- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
I recently discovered that, when running `maketx` on an HDR that included the sun, the extremely high channel values (> 145,000) were being rolled off to just over 65,000. Eventually, I was able to track the cause of the "rolloff" down to the use of `--fixnan box3`, and from there, I found that float/double values were being incorrectly flagged as non-finite due to an implicit cast to half.
Basically, because a cast to half is possible, the local `isfinite` [in `imagebufalgo_pixelmath.cpp`](https://github.com/OpenImageIO/oiio/blob/master/src/libOpenImageIO/imagebufalgo_pixelmath.cpp#L1003) is being preferred over `std::isfinite` for float and double values.
The fix uses a templated shim around `std::isfinite`, with an explicit specialization for `half`.
I can add an additional …
> ImageBufAlgo: Fix implicit float/double casts to half incorrectly flagging values as non-finite

- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/simd.h
- src/libutil/fmath_test.cpp
- src/libutil/simd_test.cpp
This matches the C++20 std notation.
> rotl template, instead of rotl32/rotl64

- src/doc/builtinplugins.rst
- src/raw.imageio/rawinput.cpp
Added two LibRaw options to the RAW plugin.
half_size: Processes image at 50% size.
user_mul: Allows the input of white balance coefficients to set a custom WB.
I have added some lines to builtinplugins.rst, not sure if that is sufficient for the documentation?
> Added half_size and user_mul options to rawinput plugin

- src/include/OpenImageIO/attrdelegate.h
- src/include/OpenImageIO/paramlist.h
- src/include/OpenImageIO/ustring.h
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
* ParamValueList::contains() should be const
* ustring: make an explicit conversion to std::string
* AttrDelegate: make `get<string_view>()` work correctly without
improperly referencing a temp string whose lifetime is shorter than
the string_view.
* AttrDelegate: allow default `get()` template to return a string_view. You need
`get<T>()` to retrieve/convert some other type.
* ParamValueList: have getattribute of string do auto conversion. 
If you getattribute() of any non-string type (like an int or float),
it will try hard to convert whatever it finds to that type, even if it
was stored as a different type internally. But if you asked for a
string, it would fail unless it was stored internally as a
string. Make these symmetric by always converting if possible.
> Several small improvements to the ParamValueList / delegate interface

- src/doc/oiiotool.rst
- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/paramlist.h
- src/libOpenImageIO/imagebufalgo.cpp
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/python/py_paramvalue.cpp
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-copy/run.py
- testsuite/python-paramlist/ref/out.txt
- testsuite/python-paramlist/src/test_paramlist.py
Most oiiotool commands copy metadata to their result from their first
input. Using `--metamerge` causes >2 arity image ops to try to merge
metadata from all of its input images (though earlier arguments have
precedence in the case of name clashes).
Also make IBAprep utility have a bitfield flag for the same purpose,
though it's not the mechanism we use for the oiiotool calls.
Along the way, added `ParamValueList::merge()` merges two PVLs together.
Also fixed a couple typos and updated the oiiotool --help message to point
to the new online docs.
> `oiiotool --metamerge` gives output merged metdata of all inputs

- src/include/OpenImageIO/unordered_map_concurrent.h
- src/libtexture/imagecache_pvt.h
The hash table underlying `unordered_map_concurrent` has support for queries using a precomputed hash value.
Since we need to hash once to figure out which bin to use, we may as well re-use that value for the lookup when possible, which avoids an extra hash operation while we are holding the lock.
Benchmarks show a 1-2% speedup in some cases (as part of a whole renderer).
Also swapped the `FingerprintMap` to  `tsl::robin_map` while I was in there, there's no good reason to use `std:unordered_map`.
> Small improvements concurrent map

- src/include/OpenImageIO/unordered_map_concurrent.h
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
Use all bits of the hash to pick the bin in unordered concurrent map instead of just the low 32 bits we used before (because the previous hash function was 32 bits only).
Minor cleanups to the TileID struct
In preliminary benchmarks, this simple change has a dramatic impact on some scenes (from 10% to close to 2x faster), while having a relatively no measurable impact on scene that are not stressing the texture system.
Something I've yet to play with: instead of mixing in the filename hash, just use the file pointer itself (which should be unique as well). This would avoid the two caches misses it takes to lookup the filename's hash at the expense of making the hash function non-deterministic.
> Improve the hash function for the tile ID

- CMakeLists.txt
- site/spi/Makefile-bits
- site/spi/README-SPI.md
- site/spi/appcfg.xml.in
- site/spi/cmake/sitecustom.cmake
- site/spi/format_version.py
- site/spi/rez/build.py
- site/spi/rez/package.py.in
- src/cmake/install.cmake
This mostly concerns builds at SPI, but a tiny bit touches the generic
build scripts. Most of you will want to tune out now, unless you're
especially curious.
Changes for everybody:
* Switching to a 4-part formal version number (e.g. 2.1.3.0), so there
is an additional (rarely used) CMake variable
OPENIMAGEIO_VERSION_TWEAK. This gives me a little more flexibility
with certain tags and releases in the master branch but there are
very few contexts in which anybody will care about or refer to the
last tweak number, and in practice we may rarely or never use it.
* New CMake option `OIIO_NAMESPACE_INCLUDE_PATCH`, if turned on, will
make the "inner namespace" include the patch number (such as
namespace OpenImageIO_v2_1_3), whereas the default is the usual
major/minor (OpenImageIO_v2_1). In …
> Changes to SPI custom build scripts, versioning/disting policy changes

- src/cmake/externalpackages.cmake
- src/cmake/modules/FindLibheif.cmake
- testsuite/heif/ref/out-libheif1.4.txt
A little more flexibility in overriding where to find libheif
Update ref output after libheif 1.5 release
> Updates after release of libheif 1.5

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texturesys.cpp
Just a small cleanup I noticed while I was looking at the texture code. We were potentially creating a new thread info struct while resolving udims.
> Avoid creating a new thread info struct while resolving udims

- src/include/OpenImageIO/thread.h
- src/libutil/thread.cpp
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
This has *very* occasionally popped up for a while. I've only seen it
on OSX for some reason, too hard to reproduce but once every several
days.  But a totally unrelated set of changes caused me to see it
happen quite regularly and it's icky.
Long story short, our thread pool seemed to have two different ways of
finding out whether the current thread is a member of the pool, one of
them only used from the TIFF reader/writer, and they didn't match!
Specifically, the correct one tried to know if the calling thread was
doing work for the pool, either being a member of the pool itself or a
nonmember that was stealing work because the pool was too full to add
to. The other one merely said whether it was a fully fledged pool
worker thread. Turns out this difference could get you into trouble, …
> Fix potential deadlock in TIFF I/O: minor flaw with threadpool method

- src/dpx.imageio/dpxinput.cpp
- src/psd.imageio/psdinput.cpp
Quite some time ago (early in OIIO 2.0 development, after it was
separated from 1.8), we changed the ImageInput::read_native functions
to be thread-safe and stateless. This meant that a seek_subimage would
be called inside the read (which now had a lock) whereas it was
previously assumed that the user had already called it.
All good, as long as your seek_subimage checks whether it's seeking to the
subimage it's already on, in which case no work need be done.
DPX failed to do this, so every scanline read involved a costly header
examination.  Somehow nobody noticed this until now, but it's fairly
icky. It can slow down DPX reads by 2x, and this is greatly exacerbated
in a heavily multithreaded environment.
I found and fixed a similar error for psd files.
While I was at it, I also added a …
> Fix DPX performance regression

- src/include/OpenImageIO/fmath.h
Two problems (sorry for not testing better):
1. I botched the template syntax for the Cuda specialization.
2. The Cuda specialization uses intrinsic __funnelshift_lc which is
not constexpr, so let's just un-constexpr this whole thing for now.
> Fix rotl<> for Cuda safety

- INSTALL.md
- site/spi/Makefile-bits
Nothing to see here, folks. It build and tested fine the first time against clang 9.0.0_rc4, so I'm just updating the docs to say so.
> Tested fine against clang 9

- src/build-scripts/build_openexr.bash
- src/build-scripts/ci-startup.bash
- src/cmake/modules/FindOpenEXR.cmake
I realized that HINTS is higher precedence than PATHS, and that
allowed some simplification of the exr finding logic.
Clean up install_openexr script, more control over the generator type
and build configuration. Use `cmake --build` instead of `make` so it
will work on all platforms and not only make.
> FindOpenEXR and install_openexr cleanup

- src/doc/builtinplugins.rst
- src/doc/stdmetadata.rst
- src/ffmpeg.imageio/ffmpeginput.cpp
- src/openexr.imageio/exrinput.cpp
- testsuite/dup-channels/ref/out.txt
- testsuite/maketx/ref/out.txt
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-fixnan/ref/out.txt
- testsuite/oiiotool-maketx/ref/out.txt
- testsuite/oiiotool/ref/out.txt
- testsuite/openexr-chroma/ref/out.txt
- testsuite/openexr-multires/ref/out.txt
- testsuite/openexr-suite/ref/out.txt
- testsuite/openexr-v2/ref/out.txt
- testsuite/rational/ref/out.txt
It's the number of frames for movie files, number of subimages for
other files.
Set and positive only if it can be known inexpensively from the file
header. If absent or zero, it means there was no easy way to determine
the number of frames or subimages from just reading the header (in that
case, you'll have to discover the subimages the old fashioned way,
repeatedly seeking to subimages until you fail).
> New attrib "oiio:subimages" says number of subimages, if known

- src/ffmpeg.imageio/ffmpeginput.cpp
- src/libtexture/imagecache.cpp
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
Several small, subtle, interacting issues were making it particularly
difficult for oiiotool to process frames within movie files (and,
less noticeably, other multi-subimage files). The fixes:
* The ffmpeg reader had no valid_file() method, which meant it fell
back to the default of doing a full open() and looking for success,
which is expensive in this case. Replace it with the cheap and naive
test of just ensuring that the file exists and its name has one of
the proper file extensions.
* ImageCache::read_untiled(), when reading an untiled image as one
single tile, closed the file immediately thereafter, which seems
like a prudent thing to do because once you have read the whole
image into the cache, you may as well free the resources associated
with the open file, since you don't need …
> Fixes that make multi-subimage and movie files faster

- INSTALL.md
- src/cmake/externalpackages.cmake
- testsuite/python-imagebufalgo/ref/out-freetype2.4.11-py2.7-pybind2.3.txt
- testsuite/python-imageinput/ref/out-travis-py2.7-pybind2.3.txt
The newly released pybind11 v2.4.0 and v2.4.1 are actually broken for
C++11 (accidentally used constexpr in a place where it's only valid
for C++14). Communication with the pybind11 team quickly resulted in a
v2.4.2 release that fixes the problem.
This patch adds logic to our build scripts so that if one of the two
broken versions are found on the system and we're building for C++11,
it falls back to our "download our own copy" logic. The new default
for downloading our own is updated to 2.3.0 (including updating some
ref output).
> Update pybind11 version logic to work around bugs

- site/spi/Makefile-bits
- src/ffmpeg.imageio/ffmpeginput.cpp
The original code was always asking ffmpeg to give it RGB uint8 frames.
This patch modifies it so that it asks for RGBA when alpha is present,
1-channel image when it's a greyscale movie, and retrieve as uint16
when >8 bits per channel are stored in the file.
If you are, to pick a hypothetical example at random, trying to
convert a 10 bit rgba quicktime of an fx element into individual
frames to save out as TIFF files, this will fully preserve the 10 bits
and alpha channel, whereas before you would just get back a crappy 8
bit rgb.
Also updated where the SPI build gets its ffmpeg, to pick up a newer
version.
> Movie reader enhancement

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
This seems to have gone unnoticed by the compilers except for a very
recent update of MSVS 2019...
But the opaque class ImageBufImpl we define publicly in imagebuf.h
in order to use PIMPL idiom has a problem where the std::unique_ptr
doesn't know what deleter to use for an incompletely declared class.
Do some magic to make a public well-defined base class with a deleter,
keeping the full ImageBufImpl private to imagebuf.cpp.
> Fix undefined deleter for ImageBufImpl / MSVS errors

- src/include/OpenImageIO/imageio.h
In a C++11 world, we can define these using int64_t and uint64_t:
simple, standard, identical size on all platforms.
The prior convoluted definitions were from an earlier time when we
couldn't count on these being present.
> Define stride_t and imagesize_t in a modern way.

- site/spi/format_version.py
- src/doc/conf.py
- src/doc/help2man_preformat.py
- testsuite/misnamed-file/run.py
- testsuite/missingcolor/src/makepartialexr.py
- testsuite/oiiotool-xform/run.py
- testsuite/python-colorconfig/run.py
- testsuite/python-colorconfig/src/test_colorconfig.py
- testsuite/python-deep/src/test_deep.py
- testsuite/python-imagebuf/src/test_imagebuf.py
- testsuite/python-imagebufalgo/src/test_imagebufalgo.py
- testsuite/python-imageinput/src/test_imageinput.py
- testsuite/python-imageoutput/src/test_imageoutput.py
- testsuite/python-imagespec/src/test_imagespec.py
- testsuite/python-paramlist/src/test_paramlist.py
- testsuite/python-roi/src/test_roi.py
- testsuite/python-typedesc/src/test_typedesc.py
- testsuite/raw/run.py
- testsuite/runtest.py
With this additional set of changes, we now have a 100% clean bill of
health from pylint --py3k.
> Python3 safety

- testsuite/gif/run.py
- testsuite/maketx/run.py
- testsuite/oiiotool-color/run.py
- testsuite/oiiotool-maketx/run.py
- testsuite/oiiotool-text/run.py
- testsuite/oiiotool-xform/run.py
After a fresh build, sometimes a parallel test would fail because
certain tests tried to get ../oiiotool/src/... but that link is not
set up until oiiotool test runs. It is listed first, but sometimes
when doing parallel test runs (via CTEST_PARALLEL_LEVEL=...) the
timing can be just right to fail.
> Tests: remove order dependency of some tests

- src/iconvert/iconvert.cpp
- src/idiff/idiff.cpp
- src/igrep/igrep.cpp
- src/iinfo/iinfo.cpp
- src/iv/ivmain.cpp
- src/maketx/maketx.cpp
`command --help` is a well-formed command that should have a "success"
error code of 0. Most of the command line utilities returned a failure
code. (Only oiiotool got it right.)
> Make all command line utilities --help return 0 exit code

- src/doc/pythonbindings.rst
- src/libOpenImageIO/color_ocio.cpp
- src/python/py_imagebufalgo.cpp
* The Python bindings of both ociotransform and ociolook mixed up the
order of inverse and unpremult params. Oh no!
* Python bindings of both ociotransform and ociolook sometimes called
"inverse" "invert", which would be bad for named parameter binding.
* Underlying C++ IBA::ociofiletransform issued an error message when
no color config was found. This is unnecessary, since the config is
only used to make a processor, no color spaces need to be known
since the LUT comes from the file.
> ociofiletransform fixes

- .gitignore
- src/cmake/modules/FindOpenImageIO.cmake
* Covers #2331
This adds two imported targets to the default OIIO cmake finder `OpenImageIO::OpenImageIO` and `OpenImageIO::oiiotool`.
None
> Add imported library to FindOpenImageIO.cmake

- src/include/OpenImageIO/plugin.h
- src/libutil/plugin.cpp
On OSX, Plugin::plugin_extension() returned "dylib". But actually, OSX
distinguishes between true shared libraries ("dylib") and what they
call "bundles" -- the latter is what we think of as a runtime-loadable
plugin and is traditionally given the extension "so".  This choice
also corresponds to what is chosen by new CMake conventions where we
use "MODULE" as the argument to add_library() when making plugins.
I apologize for not understanding this distinction previously.
> Use more standard convention for plugin_extension on OSX

- src/libOpenImageIO/maketexture.cpp
- src/openexr.imageio/exroutput.cpp
We've run into bugs with DWAA/DWAB compression of OpenEXR images in
the specific case of 1-channel images where tile size is either < 16
or not a power of 2.  There was already special logic in the exr
output module that notices this problem case and switches to zip
compression.
However, in the case of outputting MIPmaps, the top level may satisfy
the conditions under which DWA compression works fine (power of 2,
tile size >= 16). But in the course of outputting the MIP levels, we
will eventually reach a tile size < 16, and the OpenEXR format doesn't
allow us to select a different tile size per MIP level (it's just
stored once in the header for the whole file).
So add some logic to our MIPmap generation (maketx, etc), so that
single channel exr texture maps preemptively switch from …
> Rig exr texture output to avoid dwa compression for 1-channel images

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
It's a wash for small thread counts, but for highly threaded renders,
I'm seeing 1-2% speedups across real world scenes.
> ImageCache per-thread file cache to deal with thread contention

- CMakeLists.txt
Hi. We use OIIO as a submodule. The CMake build did not work because the step that copies the runtest.py file used CMAKE_SOURCE_DIR/CMAKE_BINARY_DIR instead of CMAKE_CURRENT_SOURCE_DIR/CMAKE_CURRENT_BINARY_DIR, which resulted in invalid paths in our case.
Now this step works whatever the location of OIIO with respect to the root project's location.
- [X ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [X ] If this is more extensive than a small change to existing code, I
- [X ] I have updated the documentation, if applicable.
- [X ] I have …
> Fix runtest.py copy when OIIO is a submodule

- src/libtexture/imagecache.cpp
- src/libutil/filesystem.cpp
These are just a few simple changes that avoid an excessive number of syscalls to "stat" when opening a file for the first time (especially through the `ImageCache` which the texture system uses internally).
Noticed these while using `strace` on a render.
There are 2 `stat` calls left, both of which seem useful. One gets the size of the file for the stats, the other gets the last modification time for the invalidation logic.
> Reduce the number of stat calls when opening files

- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Two subtle bugs in Strutil::parse_string:
1. Toggling whether we are in an escape code based on the first
character in the original string, rather than the next character to
scan.  Big oops!
2. Not realizing that a second backslash in a row should *clear* the
flag (i.e. `\\` does not leave you in an escaped state).
I beefed up the unit tests, looking at the example I added should
explain the edge case where this crops up -- a double-quoted string
with embedded \\\" within it, if you catch my drift. Just look at the
unit test, it explains better than I can do here. It's very hard to
talk and write (and reason correctly) about escaped strings with
embedded quotes!
> Fix bugs in Strutil::parse_string that would fail for escaped quotes

- src/include/OpenImageIO/filesystem.h
- src/libtexture/imagecache.cpp
- src/libutil/filesystem.cpp
A number of calls in the Filesystem API were using std::string instead of
the more efficient string_view. This was leading to extra conversions in a few places in the code.
Also mask the usage of boost::system::error_code behind an alias so we can (one day) move to std::filesystem more easily.
Fix some internal roundtrip between string and path representations in the Filesystem module.
> Switch Filesystem API to use string_view more consistently

- src/libutil/strutil.cpp
strutil: specify the global namespace for strtof and strtod calls. avoids infinite loop.
Did run the testsuite on Haiku, without python tests. Some tests were previously crashing with an infinite loop in strtof.
> strutil: specify the global namespace for strtof and strtod calls.

- src/dpx.imageio/dpxoutput.cpp
> DPX: guard against int32 overflow for very big images

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
These utility functions are natively 64 bits, so you don't need to
worry about what nonstandard functions to call. Prefer Filesystem::fseek
and ftell over std to guarantee safety for enormous files.
> Add Filesystem fseek & ftell, always are 64 bit offsets

- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/maketexture.cpp
When color correcting single channel images, oiio just color corrects them as (y, 0, 0), it's better to use (y, y, y). We also fix a couple of spots in maketx with the same issue.
> upgrade to 3 channels when doing color conversions

- src/iff.imageio/iff_pvt.cpp
- src/iff.imageio/iff_pvt.h
- src/iff.imageio/iffinput.cpp
Ultimately this was to simplify the header reading and make sure that an
error message is returned to make it easier to understand where things
failed.
> Refactor iff header reading for better error messages

- src/sgi.imageio/sgiinput.cpp
- src/sgi.imageio/sgioutput.cpp
Watch out for int32 overflows, practice 64 bit seeking.
> sgi: big file safety

- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- src/bmp.imageio/bmpoutput.cpp
* Fix places that could overflow int32.
* Speed up read/write by about 40%, mostly by avoiding the pointless
zeroing out of allocated memory in cerain std::vector temporary buffers.
> BMP safety for big files and int32 overflow for offsets, and speedups

- src/hdr.imageio/rgbe.cpp
- src/hdr.imageio/rgbe.h
It was calling fread/fwrite for each pixel! Allocate a little memory and
do just one write per scanline.
> Speed up hdr/rgbe read and write uncompressed by 5-10x

- src/include/OpenImageIO/strutil.h
- src/libOpenImageIO/maketexture.cpp
- src/libutil/strutil_test.cpp
* Since it uses an ostrstream internally, make sure it is set up to be
locale-independent (floats will always render with '.' decimal).
* Add a version with a parameter that allows you to set the number of
items joined to something other than the length of the sequence,
truncating or padding with default values as needed.
And I illustrate its use in make_texture.
> Improvements to Strutil::join()

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture3d.cpp
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
Each texture query may perform many samples, and each sample may fetch a
tile (or more). EVERY time it was making sure that the 'used' atomic int
was set to 1. That's potentially a lot of contention.
Idea: Only set it once for all those samples. We really only need to mark
it 'used' per texture call, not per sample.
So I augmented find_tile() with an optional parameter mark_same_tile_used
(defaulting to true), and the effect is that if it happens to be the
most recently used tile in the microcache, it will only call use() if
mark_same_tile_used is true. So then, when looping over sampling, it
passes sample==1 for that param, having the effect that for the first
sample only (or of course if any other tile is needed than the last one)
will it mark used and diddle the atomic variable.
In our …
> Reduce tile cache entry 'used' contention

- src/cmake/compiler.cmake
- src/doc/oiiointro.rst
- src/libutil/stb_sprintf.h
- src/libutil/strutil.cpp
- src/rla.imageio/rla_pvt.h
- src/rla.imageio/rlaoutput.cpp
We relied on vsnprintf underneath, which is locale dependent.  This is
important for OSL, which generates code that uses this (it will botch
the formatting of floating point values in OSL printf, format, error,
and other similar calls, if the user has their system set to a locale
with commas as decimal separators).
I don't yet have an all-platforms solution, but for OSX, FreeBSD, and Windows,
we can use vsnprintf_l which allows passing a locale (for which we use
the "C" locale).
It makes me very unhappy that I don't yet have a solution for Linux, which
lacks the *printf_l family of functions. I'm keeping my eyes open for
a fix here. But in the mean time, I think Windows is the platform
most likely to have users whose machines are set to foreign locale
without realizing the implications, …
> More care with locales -- Strutil::vsprintf was not locale independent

- src/include/OpenImageIO/string_view.h
- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
We already had strip, which trims chars from both sides. Sometimes you
just want to strip the left or right.
Also add some missing unit tests. And saw a > vs >= improvement in
in string_view::substr().  (I don't think it was wrong before, just
failed to take an early out for an empty substring.)
> Strutil::lstrip, rstrip

- src/bmp.imageio/bmpoutput.cpp
Difference between padded scanline width and number of pixel values was
not properly considered or zeroed out. This was (nondeterministically)
botching occasional CI tests.
> BMP fix uninitialized data in output

- src/doc/oiiotool.rst
- src/libOpenImageIO/imagebuf.cpp
- src/oiiotool/oiiotool.cpp
* Detect failed allocations when ImageBuf tries to allocate local memory
but there is not enough memory -- catch the exception, leave the IB
uninitialized, set an error in the IB. This at least allows oiiotool
to issue an understandable error message if --create or --pattern fail
because too high a resolution was specified.
* oiiotool --create and --pattern take a new optional parameter:
`:type=name` that overrides the default behavior of allocating all
internal buffers as float. An important application of this might be
if you are creating a huge image that would not usually fit in memory
as floats, might as a half or uint8. For example,
oiiotool -pattern checker 64000x32000 3 -o big.exr
writes a really big checkerboard, but will fail on a machine that can't
muster an allocation of 23 GB …
> oiiotool & ImageBuf improvements for huge images

- src/libOpenImageIO/imageinout_test.cpp
One test is to write an image file to disk, then write the same image
as a "file" to an in-memory buffer, and make sure resulting bit patterns
match exactly.
Every once in a while, it would spuriously fail. I'm pretty sure it's
because of metadata not matching exactly if the two writes happen on
opposite sides of a minute boundary!
This patch attempts to preempt that by setting "DateTime" metadata to
a fixed value, so that individual format writers don't, in its absence,
supply the "now" value, which could vary from run to run.
> Fix occasional CI failure in imageinout_test

- src/include/OpenImageIO/imagecache.h
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
The default is 0, old behavior. If you set to nonzero, you are
promising the ImageCache that it will always be able to identify a
texture file's format based on the filename extension (e.g. ".exr"
always means it's an openexr file, ".tif" or "tx" for TIFF files, and
you will NEVER call a file ".tx" if it's really openexr, or if you do,
you are ok with it being unable to open it). When you enable it with
that promise, it can eliminate a few redundant file opens and header
reads, by not needing to verify file format types at certain stages of
processing.
I'm not sure I would recommend enabling this in general. But if you
are operating in a closed environment where you are sure that file
extensions will match their types (such as a studio with rigid naming
conventions, where all possible …
> IC/TS option "trust_file_extensions"

- LICENSE-THIRD-PARTY.md
- src/doc/oiiointro.rst
- src/include/OpenImageIO/fmt/core.h
- src/include/OpenImageIO/fmt/format-inl.h
- src/include/OpenImageIO/fmt/format.h
- src/include/OpenImageIO/fmt/ostream.h
- src/include/OpenImageIO/fmt/printf.h
- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/typedesc.h
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
- src/libutil/strutil_test.cpp
- src/libutil/typedesc.cpp
- src/oiiotool/printinfo.cpp
This updated version of fmt has its floating point conversions to be
locale-independent as we wanted. But we are still not (for this
commit) chaning which places we use fmt versus which we use
tinyformat.
> Update embedded fmtlib to v6.0.0

- src/python/py_oiio.h
- src/python/py_paramvalue.cpp
- testsuite/python-paramlist/ref/out.txt
- testsuite/python-paramlist/src/test_paramlist.py
We previously exposed the PV constructors from just a plain int, float,
or string, but there wasn't an easy way to construct from arbitrary data
like there is in C++.
> Python: add binding for missing ParamValue constructors

- src/include/OpenImageIO/strutil.h
Oh boy, I discovered that something in the new fmt make Cuda unhappy,
and this in turn bites OSL. So I made it so that to really get out of
such a jam, one could `#define OIIO_USE_FMT 0` before including
strutil.h, and then the fmt headers will not be included nor called,
falling back on tinyformat where possible (for sprintf, to_string) and
for std::format style simply fail to format. This is sufficient for
now, we don't actually need the formatting to work from within Cuda at
the moment.
Also fixed some out of date comments while I was there.
> fmt fixes -- allow a way to fully disable it

- src/libOpenImageIO/exif-canon.cpp
The dataptr() function returns nullptr if the offset is out of proper
range. But the array_to_spec function calling dataptr did not check for
a nullptr return, ended up segfaulting.
> Exif read: guard better against out of range offests

- .github/workflows/workflow.yml
- .travis.yml
The ffmpeg we were using was from a repo whose owner just took it offline.
This was making our TravisCI Linux builds fail. But it's well tested in
the GitHub CI matrix, so just remove it here.
Also... remove another Linux test from Travis that seems redundant, as
it is nearly an identical configuration to one in the GH test matrix.
And for that matter, we don't need to do the clang-format check on
both testing platforms, so remove it from Travis, too. Now we only use
Travis for the gcc 4.8 tests and Mac with Python 2.7 (I've had trouble
getting both of those working on GH CI).
> Fix ffmpeg package availability problem on Travis

- src/libOpenImageIO/imageio.cpp
- src/libutil/thread.cpp
- src/tiff.imageio/tiffinput.cpp
There is still one use left, in ImageCache. I'm not sure how to get rid
of that yet, because the C++11 std version only works for global or static
variables, but we are using it in a class. We'll come back to that later.
In the mean time, this gets rid of all other uses.
One thing this does is fix a link error I get on MacOS when building
with EMBEDPLUGINS=0.
> Replace most uses of boost::thread_specific_ptr with C++11 thread_local

- src/include/OpenImageIO/refcnt.h
- src/include/OpenImageIO/thread.h
- src/include/OpenImageIO/unordered_map_concurrent.h
- src/libtexture/imagecache.cpp
To reduce thread contention on the IC/TS caches, change from unique
locks to reader-writer locks.
* unordered_map_concurrent: Change the shards from spin_lock to
spin_rw_lock. Most operations (insert, erase, holding an iterator,
and find, which returns an iterator) are unique (write) locks. But
the underappreciated retrieve() method is stateless and can be a reader
lock!
* In imagecache.cpp, change a bunch of the find() calls and fiddling
with iterators into simpler calls to retrieve(), which should be
able to happen concurrently.
On a highly threaded machine (52 cores) this resulted in a 6% gain
(geometric mean) across a set of production render frames that we like
to test with, but that disguises what's really happening.  Most of the
individual tests in that suite don't change at all …
> Allow rw locking of texture caches

- src/iconvert/iconvert.cpp
- src/oiiotool/oiiotool.cpp
- src/testtex/testtex.cpp
Never reported, not on CI tests, but I've seen it happen. Only on MacOS, only
for builds with EMBEDPLUGINS=0, only for tests involving Field3D files.
I seem to be able to fix it (or at least make it asymptomatic when I
run tests) by forcing all the open texture file handles to close
before the DSOs are unloaded, for a few of the utilities.
> Fix occasional static destructor order fiasco.

- src/cmake/compiler.cmake
> Fix typo that set the wrong definition for static libs

- src/build-scripts/install_homebrew_deps.bash
Something changed about homebrew versons, I guess, and the combination
of python + cmake on both GitHub CI and TravisCI broke OSX. Modifying
install_homebrew_deps.bash to be sure it upgraded to the latest
version of both packages seems to solve the problem.
> Compensate for CI machine changs for python install

- src/cmake/pythonutils.cmake
> Bump version of pybind11 that we auto-download

- src/include/OpenImageIO/refcnt.h
We used the assertion macros, but didn't include the header. I guess
coincidentally, all other files that included refcnt happened to have
included dassert first? But 3rd party code that wants to use refcnt
for some reason shouldn't have this pop up as an error
> Add missing include of dassert.h to refcnt.h

- src/python/py_oiio.cpp
- src/python/py_oiio.h
- src/python/py_paramvalue.cpp
- testsuite/python-paramlist/ref/out.txt
- testsuite/python-paramlist/src/test_paramlist.py
Previously the data passed had to be tuples.
Also add ParamValueList.attribute() variety that takes an nvalues
parameter.
> Extend Python ParamValueList to take lists and numpy arrays

- src/include/OpenImageIO/imagebuf.h
- src/python/py_imagebuf.cpp
Convenience function. Preferred to use spans over ptr+length. Also, this matches the Python interface.
> Add ImageBuf::setpixel() methods that use cspan instead of ptr/len.

- CMakeLists.txt
- src/cmake/Config.cmake.in
- src/include/CMakeLists.txt
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
* Relax version compatibility specification to just matching major version.
* Specify targets cmake name correctly.
* Make sure install include dir is listed in the public include dirs of the
libraries.
* Some other cleanup and genericization.
I believe this corrects some deficiencies in the generated OpenImageIOConfig.cmake that projects can use that exclusively (with imported targets) and have no need for a copy of FindOpenImageIO.cmake.
Unless objections are raised, I will also backport this to 2.1 for the patch release that's coming in a few days.
> Fixes to cmake config generation

- CMakeLists.txt
- src/doc/imagebufalgo.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
- src/python/py_imagebufalgo.cpp
Troy Sobotka pointed out to me that the implementation of colorconvert
where unpremult=1 (i.e., unpremult, then transform, then premult) was
wrong: the unpremult operation was careful to preserve the color value
of pixels where alpha==0, but the premult we did at the end was just a
straight multiply of the color by the alpha. This would have the
effect of crushing those "glow" (A==0, RGB > 0) pixels to black in
their round trip, whereas we want the original glow to be preserved.
So really, the kind of premult we want for a one-time conversion of
unpremultiplied to premultiplied is subtly different from the "re-premult"
that we want as part of a round-trip operation.
The fix in this patch is to add IBA::repremult() to do this modified
operation (multiply color by alpha, unless alpha is 0), …
> repremult: Fix subtle edge case in color conversion with unpremult=1

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/unordered_map_concurrent.h
Background: unordered_concurrent_map<> is a thread-safe map that is
parameterized by the type of the underlying "shard" maps. The default
underlying map type is std::unordered map. Though for a while, as used
by ImageCache, we have been using robin_map as the underlying map
type, having found it has superior performance.
PR #2314 improved performance even more by taking advantage of the fact
that robin_map has a find(key,hash) that lets you supply the
precomputed hash value (in situations where you already had it), thus
avoiding redundant hash computations.
BUT... we failed to notice that unordered_map doesn't have this kind
of find() variety, and so even though the u_c_m is templated on the
map type, this meant that it would no longer work with
std::unordered_map. That's especially …
> Fix misdesign in unordered_map_concurrent that broke it for unordered_map

- src/doc/imageinput.rst
- src/doc/imageoutput.rst
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/oiioversion.h.in
- src/jpeg.imageio/jpeg_pvt.h
- src/jpeg.imageio/jpeginput.cpp
- src/libOpenImageIO/imageinout_test.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageioplugin.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
- src/png.imageio/pnginput.cpp
- src/png.imageio/pngoutput.cpp
- testsuite/python-imagespec/ref/out-python3.txt
- testsuite/python-imagespec/ref/out.txt
Make it a first class thing the API knows about, not the very weird back
door of passing via configuration hint.
For the sake of backward compatibility, the "old" method of passing
config attribute "oiio:ioproxy" with a PTR data will continue to be
supported for at least a couple major releases.  But moving forward
for 2.2+ (which, remember, won't be a supported release for many
months), the preferred and documented way will be through these new
API calls.
It is still the case that only some format readers/writers support
IOProxies -- it is not only lots of work to extend support to more
formats (volunteers?) but since we rely on 3rd party libraries for
some of our important formats, if they don't have support for some way
to supply custom low level I/O function overrides, it would be …
> Modify ImageInput/ImageOutput APIs to directly support IOProxy

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindPybind11.cmake
- src/cmake/pythonutils.cmake
Recent changes (2347) seem to rely on some pybind declarations that
are newer than the minimum version we checked for. Bump the pybind11
required version.
> Bump the minimum pybind11 that we need

- INSTALL.md
- src/build-scripts/gh-win-installdeps.bash
- src/build-scripts/install_homebrew_deps.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindLibsquish.cmake
- src/dds.imageio/CMakeLists.txt
- src/dds.imageio/ddsinput.cpp
This patch checks for libsquish already on the system, and if found,
uses it. If not found on the system, it falls back on the embedded
version in src/dds.imageio/squish. CMake option USE_EMBEDDED_LIBSQUISH
can be used to force use of the embedded version even if found on the
system.
Background: Our DDS support (by Leszek Godlewski in 2010, as a GSoC
student) relies on an embedded copy of libsquish (MIT license) for DXT
compression.  Embedding was a reasonable choice at the time, but in
2020 it's easily installed an Ubuntu, Homebrew, Vcpkg.  Furthermore,
it's also a Debian package and runs up against their rule that we
should never embed code that is available from other Debian packages
that can be used as dependencies.
This is all I want to do in this patch -- comply with Debian rules, …
> Use external libsquish if found

- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
For apps using atomic.h, on architectures where certain atomic operations
need libatomic, they'll need to know about it. The `${GCC_ATOMIC_LIBRARIES}`
should have been a "PUBLIC" designaton for target_link_libraries, not a
private one (since atomic.h, which calls them, are public).
> libatomic linkage fixes

- src/doc/imagebuf.rst
- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
* Tried to expand and clarify explanations of the constructors and
reset methods in particular, after an issue was filed with some
confusion.
* Added checks to ensure that for the ctrs and reset methods that take
an ImageSpec and allocate (or wrap) a buffer, if the spec doesn't
have enough information to do the allocation or know the size of the
wrapped memory (spec lacking nonzero width, height, depth,
nchannels, and a concrete data format), the buffer stays marked as
UNINITIALIZED.
* Added `ImageBuf::reset()` as a synonym for `clear()` and a reset
variety corresponding to the "wrapped app buffer" constructor.
This makes it so that every ctr has a corresponding reset method, and
vice versa. As I was clarifying the docs, I realized that this would
be better if fully symmetric. Because …
> Improve docs for ImageBuf, and some error detection and missing methods

- src/include/OpenImageIO/platform.h
The main change is recognizing which MSVS version is C++14 compliant.
Also fixed some comment typos, and initial support for C++20 detection.
> Slight revision of detection of C++ version

- .github/workflows/workflow.yml
- .travis.yml
- src/build-scripts/build_llvm.bash
- src/build-scripts/build_ocio.bash
- src/build-scripts/gh-installdeps.bash
* Add GH CI test for Linux + clang
* Needed to port build_llvm.bash from OSL to get the right clang.
* Some cleanup of build_ocio.bash, including renaming varibles more
clearly and instructing the OCIO build to only make static libs if
requested.
* Also touched up the travis -- we have recently pared the travis tests
to just a few, so there's no perf-related reason to restrict some tests
to just PRs, may as well do them on every push.
* GH CI: install libsquish & qt5 to get a more thorough build a tests.
> CI enhancements and cleanup

- src/include/OpenImageIO/plugin.h
- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagebufalgo_orient.cpp
- src/libutil/paramlist.cpp
More exploring what -Wextra turns up.
Found several buglets!
* The string version of getsym didn't pass along report_error.
* ImageBuf::getchannel did not honor its wrap parameter.
* ImageSpec::erase_attribute did not honor its 'searchtype' parameter.
* IBA::reorient did not pass its nthreads params to its children.
* IBA::computePixelHashSHA1 did not honor its nthreads parameter.
* Get rid of useless parameter in internal helper function parse_elements.
> Fixes related to unused parameters.

- src/ico.imageio/icoinput.cpp
- src/iv/ivgl.cpp
- src/iv/ivgl.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/exif-canon.cpp
- src/libOpenImageIO/imageio.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture3d.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/oiiotool/printinfo.cpp
- src/png.imageio/png_pvt.h
- src/png.imageio/pnginput.cpp
- src/targa.imageio/targainput.cpp
- src/testtex/testtex.cpp
More actual (unreported) buglets revealed by -Wextra pointing out function
parameters that were unused.
* Failed to properly swap endianness when decoding Canon camera info.
* ColorProcessor::apply methods were not using chanstride param.
* texture3d fixes: some deriv results dropped on the floor
* Get rid of unused parameters in some internal functions. Not a bug
per se, but could be misleading about how the functions operate.
> More fixes for problems found by -Wextra

- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/ustring.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
- src/libutil/ustring.cpp
- src/libutil/ustring_test.cpp
`concat(s,t)` is semantically equivalent to `sprintf("%s%s",s,t)`, but
concat carefully avoids copying any of the characters more than once,
and it performs at most one temporary allocation (typically it does
not allocate temp memory from the heap at all, if the sum of the
strings' lengths are not too long).
Added both a std::string-returning and a ustring-returning version.
Also reworked the implementation of `Strutil::repeat()` to similarly
perform at most one one temporary allocation (typically none) and
not perform any unnecessary copies.
Inspired by work Chris Kulla did in OSL.
> Add concat function to ustring and Strutil

- src/doc/imagebufalgo.rst
- src/doc/imagebufalgo.tex
- src/doc/pythonbindings.rst
- src/doc/pythonbindings.tex
Simply changed instances of 'maketx:opaquedetect' to 'maketx:opaque_detect'.
To address #2482.
> Correcting documentation for opaque detection

- .github/workflows/workflow.yml
- CHANGES.md
- CMakeLists.txt
- src/doc/imagebuf.rst
- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imageinout_test.cpp
- src/png.imageio/pnginput.cpp
Pass an optional IOProxy* to ImageBuf ctr for reading, supply via new
call set_write_ioproxy() to set one up for subsequent write().
This is much easier than fumbling around with a PTR attribute in the
configuration hints.
Add tests to imageinout_test to check that proxy reads and writes via
ImageBuf works for all the same file types as they did for ImageInput
and ImageOutput.
In the process, found some subtle bugs in the PNG proxy support, needs
to ensure it starts at the beginning when we open, or else multiple
open/close cycles (as will happen in some cases for ImageBuf) will
get all confused.
> Add IOProxy interface to ImageBuf

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
I was previously testing for whether the openexr version was >= 2.2,
which is when the ImfFloatVectorAttribute.h header was introduced.
BUT... OpenEXR has two build systems, and the CMake one (which I use
to build OpenEXR for OIIO's CI tests) worked fine, but the
autotools-based one had a bug that inadvertently omitted installation
of this and some other headers. This problem with openexr's buid system
was fixed in 2.4.
So my preprocessor tests for >= 2.2 was not good enough. This patch
refines the tests so that it's looking for openexr >= 2.4 (when
everything was fixed), or openexr >= 2.2 AND the header is present
(meaning it was built with cmake rather than autotools).
> Fix test for whether OpenEXR has support for FloatVectorAttribute

- src/libOpenImageIO/imagebuf.cpp
The dst-stride parameters are being silently ignored, making RGB -> RGBA conversion fail.
> Fix dst-strides not begin honored for format conversion.

- CMakeLists.txt
- src/cmake/compiler.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
Versioning embedded in the shared library .so name should reflect ABI
compatibility level. For supported release branches, we guarantee
back-compatibility of the ABI, and therefore 2-digit naming
(major.minor) is appropriate, as we have always done. Changes to the
patch (and tweak) are guaranteed to not break ABI.
On the other hand, development in the master branch (as well as alpha
and probably to be safe betas also) may have ABI changes at any time,
so it is not sufficient for apps to link against libOpenImageIO.2.2.so.
They really should end up with major.minor.patch in order to not cause
trouble for people working from tagged developer previews in the
master branch. In master, "patch" level changes in master may change
ABI, but "tweak" level changes will not.
> More nuance in how so name versioning works

- src/doc/Makefile
On latest release, relative path for 'oiiotool' binary on build has changed but the documentation Makefile doesn't reflect this change and it would fail on the doc creation stage.
> Fix relative path for oiiotool binary

- src/include/OpenImageIO/fmath.h
- src/libutil/fmath_test.cpp
Also add clamp unit test and benchmark, and the previously missing
implementation of clamp for vfloat16.
> Rewrite of clamp() from Alex Wells generates 2x faster code.

- src/include/OpenImageIO/fmath.h
- src/libutil/fmath_test.cpp
I was previously trying to use std::fma, but upon further investigation
it was turning into a single vfmadd instruction a lot less than I thought,
in many cases ending up as a function call (which itself was extra slow
when emulating fma on hardware that lacked it).
The better strategy seems to be just saying `a*b+c`, which on gcc &
icc compilers automatically turns into vfmadd when available on the
hardware, and adding a clang-specific pragma ensures this behavior for
clang as well.
Thanks to Alex Wells of Intel for pointing this out to me (in OSL land).
> Improve fmath.h madd function

- src/include/OpenImageIO/fmath.h
* static_assert to check sizes
* use force inline
* use intrinsics where available
> fmath.h bit_cast improvements

- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/platform.h
- src/libutil/fmath_test.cpp
A variety of minor rewrites of certain math functions to ensure they
generate better machine code and auto-vectorize more cleanly.
* Lots of inline -> OIIO_FORCEINLINE
* Improve clamp used in fast_sin and cos
* fast_safe_pow improve code gen with OIIO_UNLIKELY
* Introduce `OIIO_FMATH_SIMD_FRIENDLY` to allow application switching
between implementations that give the best scalar performance versus
sacrificing scalar perf to have the best SIMD vectorization of loops
containing the fmath function. This is anticipated to be very rare,
and of course we strive to be simultaneously fastest on scalar & simd,
but we have one or two cases where such a tradeoff exists.
* Lots of additional fmath benchmarks to help us judge how good they are
compared to std functions.
* New safe_fmod which not only …
> Backport fmath performance and other fixes from OSL

- src/oiiotool/oiiotool.cpp
Previously, --autotrim when applied to a multi-subimage file would trim
all subimages to the nonzero region of just the first subimage.
This fixes, now examining all subimages and trimming them all to the
union of their nonzero regions (as --trim always did).
Technically, a multi-part OpenEXR can trim each subimage ("part")
separately, each having a different data window. But in practice, many
reading applications (including RV and Nuke!) seem to have trouble
reading files like that. So we go with the union approch.
> Fix oiiotool --autotrim to use all subimages

- src/include/OpenImageIO/strutil.h
Otherwise it would be an error if another (non-OIIO) header includes any fmt headers on its own before it includes strutil.h.
> Protect against double definition of FMT_USE_GRISU

- src/cmake/modules/FindOpenEXR.cmake
Debug builds of OpenEXR have an _d suffix (on Windows at least). This patch adds these file names to the searched library names.
Built the code on Windows and linked against both Release and Debug builds of OpenEXR 2.4.1
> FindOpenEXR.cmake: Add detection of debug builds

- src/build-scripts/install_homebrew_deps.bash
Seems that Homebrew has removed the field3d package, as its scons
build system needs discontinued python2.7 and other parts have fallen
into disrepair and are having trouble on modern compilers and cmake.
> CI: allow homebrew field3d installation failure

- CMakeLists.txt
- testsuite/pnm/run.py
- testsuite/targa-tgautils/ref/out.txt
- testsuite/targa-tgautils/run.py
The place where the TGAUTILS samples were stored seems to have disappeared
from the web. So put them in oiio-images. Adjusted the targa-tgautils test
for the new location.
Also took the opportunity to clean up the pnm test and simplify how it's
declared.
> Adjust testsuite after adding tga samples to oiio-images

- src/jpeg.imageio/jpegoutput.cpp
To give an indication of the physical dimensions (pixels per inch, pixels per mm,...) of the image we can set the "ResolutionUnit", "XResolution" and "YResolution" attributes in the image spec.
For instance for PNG and TIFF this works perfectly, for JPEG however the resolution unit is not properly written.
In jpegoutput.cpp in the open() function the "ResolutionUnit" attribute was read and set in the m_cinfo.density_unit entry. 
However this was overwritten by the jpeg_set_defaults(&m_cinfo) call. 
As a fix I moved the "ResolutionUnit" code to resmeta_to_density(). …
> Fix resolution unit not properly set in JPEG export

- src/cineon.imageio/libcineon/CineonHeader.cpp
- src/dpx.imageio/libdpx/DPXHeader.cpp
- src/dpx.imageio/libdpx/DPXHeader.h
- src/include/OpenImageIO/fmath.h
- src/psd.imageio/psdinput.cpp
Note that some of the warnings related to the dpx/cineon readers highlight suspicious code, but I've opted to retain the existing behavior. The offending variables to not appear to actually do anything, they are just carried around as metadata.
> Fix clang 10.x warnings

- src/build-scripts/build_cmake.bash
- src/build-scripts/build_libraw.bash
- src/build-scripts/build_llvm.bash
- src/build-scripts/build_ocio.bash
- src/build-scripts/build_openexr.bash
- src/build-scripts/build_pybind11.bash
`set -ex` exists the whole script if any individual command fails.  I
think this will help ensure that people know when these dependency
building scripts have errors, instead of (hypothesized) seeming to
execute fully but actually the installation of that dependency was not
complete.
> Make sure all build_foo.bash scripts exit upon any error.

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/maketexture.cpp
- src/tiff.imageio/tiffoutput.cpp
Sometimes people try to make a texture from a source image that has
"overscan" (that is, when the pixel data window goes outside the
bounds of the "display" window that is assumed to be the 0-1 texture
space). Thiago Ize in particular noticed that this works fine when
outputting the texture as exr, but not as the default TIFF-based
mipmapped textures.
Alas, the only way this can work is if the texture file format has a
way to represent fully general display windows, and TIFF does not. So
it should never have been allowed, but there was no error message, just
strange runtime behavior.
This patch:
1. Tightens up some of the tests for whether the user is requesting an
overscan texture, so that it is an error to use overscan and the
output file type doesn't support display windows (previously …
> Better error messages when overscan texture is not possible

- src/libutil/filesystem.cpp
It is possible for the constructor for filesystem::directory_iterator
to throw an exception. Switch those to the ones that take an error code
reference and do not throw exceptions.
Also fix what must be a bug (how did it ever compile?) at line 208,
where we tried to find out if the status() (!!!) was a diretory, rather
than the path. Huh?
Closes #2517
> Fix possible uncaught exceptions in Filesystem utils

- src/include/OpenImageIO/paramlist.h
- src/libutil/paramlist.cpp
* New `find_pv()` method wraps `find()` but returns a pointer rather than
an iterator, and nullptr if the attribute is not found.
* Fix `add_or_replace()` -- it was previously failing to "replace" if the
new attribute had a different type than the existing one.
> ParamValueList enhancements

- src/include/OpenImageIO/attrdelegate.h
- src/include/OpenImageIO/paramlist.h
- src/include/OpenImageIO/typedesc.h
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
This lets you pull out a single base value from an aggregate and/or
array attribute.
> Add get_indexed() to ParmValueList and AttrDelegate.

- .github/workflows/workflow.yml
- src/libOpenImageIO/color_ocio.cpp
- testsuite/python-colorconfig/ref/out-ocio2-python27.txt
- testsuite/python-colorconfig/ref/out-ocio2.txt
And incorporate a build against OCIO master into the "bleeding edge" CI test, so we don't drift out of sync again.
> Build correctly against OCIO 2.x (in progress)

- src/idiff/idiff.cpp
- src/igrep/igrep.cpp
- src/iinfo/iinfo.cpp
- src/include/OpenImageIO/argparse.h
- src/libOpenImageIO/compute_test.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libutil/argparse.cpp
- src/libutil/argparse_test.cpp
- src/libutil/atomic_test.cpp
- src/libutil/filter_test.cpp
- src/libutil/fmath_test.cpp
- src/libutil/hash_test.cpp
- src/libutil/parallel_test.cpp
- src/libutil/simd_test.cpp
- src/libutil/spin_rw_test.cpp
- src/libutil/spinlock_test.cpp
- src/libutil/thread_test.cpp
- src/libutil/timer_test.cpp
- src/libutil/ustring_test.cpp
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/testtex/testtex.cpp
I've been thinking about overhauling ArgParse for a couple years, and
did most of the work in December when I was home from work. Then sat
on it except for slow burn weekend tinkering, but finally got a chance
to put the final touches on and write the docs this week.
The bottom line is that this is a major rewrite of the APIs for
ArgParse to make them much richer, more flexible, and more closely
resembling those of python's argparse module.
Rather than trying to explain the syntax here, I simply will refer you
to the extensive inline documentation in argparse.h, as well as the
examples in the code base of where it's used.
It sill respects the old syntax, so this change is hoped to not alter
the behavior of any programs using the deprecated API.
Start by reading argparse.h, it's design …
> Overhaul ArgParse to make it more like python argparse

- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/strutil.h
A couple other spots, too.
Thanks to Alex Wells for the suggestion.
> span: allow ctr from vector to allow nonstandard allocators

- src/cmake/externalpackages.cmake
When compiling OIIO against a static version of boost where only a subset of boost libs have been built:
(eg, boost configured with --link=static --with-filesystem --with-system --with-thread --with-headers)
We want to disable the automatic MSVC linking, which will otherwise also try to link against unused and non-existant boost libraries (such as date_time).
> externalpackages.cmake: Fix static boost to not overlink

- src/libOpenImageIO/exif.cpp
Prerelease snapshots of libtiff now define these in tiff.h.
Closes #2538
> Protect against double definitions of GPSTAG values.

- src/tiff.imageio/tiffinput.cpp
After a call to TIFFReadEXIFDirecory, we needed to call TIFFSetDirectory.
We were doing it if the call succeeded, but not if the call failed.
Also, just TIFFSetDirectory is enough, we never needed to close and reopen
the file again.
This had been asymptomatic all along, but some changes in the current
libtiff master made the problems apparent.
> TIFF: fix subtle bug when reading EXIF directory in header

- src/doc/imagebufalgo.rst
- src/doc/index.rst
- src/include/OpenImageIO/imagebufalgo.h
Some IBA functions specified the wrong version of the function, thus
leaving out the explanation from the header that was associated with
the other form of the function.
Some groups had bad identifiers, apparently, and were dropping
pieces of text.
Typo in the intro, oops!
> Fix some problems with the docs

- .github/workflows/workflow.yml
Ugh, homebrew just updated some packages (including numpy!) to be
python 3.8-based, but the 'python' homebrew package is still 3.7.
Need to jump through some hoops to make it work.
> Fix GH CI Mac for python

- .github/workflows/workflow.yml
- src/build-scripts/build_libtiff.bash
- src/build-scripts/gh-installdeps.bash
- testsuite/tiff-suite/ref/out-alt2.txt
The idea of this "bleeding edge" entry in the CI test matrix is to
really use the very latest toolchain, in order to spot problems long
before users will encounter them.
To that end, let's make sure we are building and testing the current
master of libtiff and OpenEXR.
> Make the 'bleeding edge' CI test build libtiff and openexr from master

- src/jpeg.imageio/jpeg_pvt.h
- src/jpeg.imageio/jpeginput.cpp
- src/png.imageio/pnginput.cpp
Both the JPEG and PNG readers, because the can only read scanlines in
strictly ascending order, have a section where if they need to backtrack,
they do so by closing the file and re-opening.
But in this close/open, any 'config' settings they were passed when they
opened the first time would get lost. And this could include the IOProxy
they were supposed to be using.
The config info needs to be remembered and applied again if the file
is closed and reopened internal to the reader's operations.
> JPEG & PNG: Fix loss of config info upon close and reopen

- src/libutil/filesystem_test.cpp
I suspected that extra dots within a filename was confusing `extension()`.
It's behaving correctly, it turns out. But this is a good test to add.
> Beef up the test of Filesystem::extension

- src/include/OpenImageIO/unordered_map_concurrent.h
- src/libtexture/imagecache.cpp
I was investigating thread behavior while fixing a totally unrelated
bug, and I spotted a way that redundant I/O happens when the same tile
is needed by multiple threads at once. (And it really did happen, I
could see the extra reads in the stats.)
A small additional method to `unordered_map_current` allows us to
simplify the logic in `add_tile_to_cache` fully avoid the redundant
read.
Testing against our production benchmarks, this makes no measurable
difference to performance, even under heavy threading. I think that's
because we make sure that all our texture files are prepared with
'maketx', and thus are tiled, so even the presence of a few redundant
tile reads is essentially undetectable in a full render. However, for
somebody who is using untiled textures (such as jpegs), which will …
> IC/TS: Plug a hole that led to redundant tile reads

- src/openvdb.imageio/CMakeLists.txt
I have no idea if this if the right "cmake" way to fix this, but we've been trying to flush out tbbmalloc from our link path and this was one of the places it was being added.
> Avoid pulling in tbbmalloc

- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
Correct some spelling issues in these two headers. One change I did **not** make was
`make_writeable()` -> `make_writable()`, for obvious reasons.
It still compiles.
> clean up spelling in image{buf,io}.h

- .github/workflows/workflow.yml
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/imagebufalgo_opencv.cpp
> Fully hide IplImage references when no OpenCV headers are included

- CMakeLists.txt
- src/cmake/modules/FindFFmpeg.cmake
- src/cmake/modules/FindField3D.cmake
- src/cmake/modules/FindLibheif.cmake
- src/cmake/modules/FindLibsquish.cmake
- src/cmake/modules/FindOpenVDB.cmake
- src/cmake/modules/FindWebp.cmake
- src/dds.imageio/CMakeLists.txt
- src/ffmpeg.imageio/CMakeLists.txt
- src/field3d.imageio/CMakeLists.txt
- src/heif.imageio/CMakeLists.txt
- src/openvdb.imageio/CMakeLists.txt
- src/webp.imageio/CMakeLists.txt
We were getting warnings from newer cmake versions in cases where we
had modules named FindFoo.cmake, but the "found" variable was FOO_FOUND
(instead of matching the module/package name with Foo_FOUND).
Clean that up, as well as imposing a few more namespaced imports to
change to a more modern notation.
> CMake modernization and warning suppression

- src/raw.imageio/rawinput.cpp
Adding the "raw:flip" attribute. 
This field is set by LibRaw when the image has been rotated internally. 
From my understanding, this is an equivalent to the exif:orientation (Don't know why it is not in this exif).
I don't think a test is needed as it is only an export of a known LibRaw structure's field.
- [ X My code follows the prevailing code style of this project.
> Add the raw:flip attribute

- .clang-format
- src/include/OpenImageIO/ustring.h
From here on, clang-format 10 will be our official reference formatter.
> Minor formatting changes in ustring with new clang-format

- CHANGES.md
- src/doc/imagebuf.rst
- src/doc/imagebuf.tex
- src/doc/imagecache.tex
- src/doc/pythonbindings.rst
- src/doc/pythonbindings.tex
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagecache.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_mad.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libOpenImageIO/imageinout_test.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/maketexture.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_imagebuf.cpp
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imagebuf/src/test_imagebuf.py
Nick Black points out that in many places we have used "writeable", which
is (depending on which dictionary you check) is either a less commonly
used variant of "writable", or just an outright misspelling.
Even charitably interpreting it as an alternate spelling, let's standardize
on the more common variant.
There's only one API function where this comes into play, so to preserve
link compatibility, we'll have both ImageBuf::make_writable() and
make_writeable() as a deprecated synonym that will eventually disappear.
> writeable -> writable

- src/ffmpeg.imageio/ffmpeginput.cpp
Codecs which set the CODEC_CAP_DELAY capability led to infinite
loops during reading (see #2571). Once AVERROR_EOF is returned,
no more packets are going to be received, regardless of internal
buffering. break out of the loop in that case.
I've verified that this resolves the livelock following decoding
of the first packet in the Notcurses AVI test case which
illustrated this problem. I've also verified that said AVI
advertises the CODEC_CAP_DELAY attribute, matching the proposed
fix. In addition, I verified that OIIO continues to decode all
my other test cases without trouble. I hand-inspected the media,
and verified that the frame counts were precisely correct.
It is legal to pass NULL/0 into the decoder regardless of
CODEC_CAP_DELAY, and thus this whole conditional can really
be …
> Break infinite loop in FFMpeg::read_frame()

- src/cmake/modules/FindOpenImageIO.cmake
> Avoid CMake warnings by updating naming of found variable

- .github/workflows/workflow.yml
Also use the new OpenEXR 2.5 in the ~2021 test.
Try using aswftesting/ci-osl docker images. We will correct those to
regular aswf/ci-osl after the aswf-side merge is completed.
> Add VFXPlatform 2020 based test to CI

- CMakeLists.txt
- src/cmake/Config.cmake.in
- src/libOpenImageIO/CMakeLists.txt
> Put PLUGIN_SEARCH_PATH in the exported config

- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
oiiotool dates from pre-C++11, and has grown by accretion. As a
result, the individual actions are implemented using multiple
different idioms, and there is a lot of complex boilerplate.
A recent PR added subimage selection widely to all commands that use
the idiom of an implementation that inherits from the OiiotoolOp
class. The convinced me that we want to migrate as many actions as
possible to this idiom. I also realized that the current use of
OiiotoolOp could be greatly simplified by using lambdas in most
cases, which weren't available in the pre-C++11 ancient times when
oiiotool was first being developed.
This patch:
* Has the OiiotoolOp base class contain (and accept in its ctr) a
std::function for the meat of the impl() and setup() methods.
* If init() and setup() are the only …
> Overhaul oiiotool internal idioms

- .github/workflows/workflow.yml
- INSTALL.md
- src/build-scripts/gh-installdeps.bash
* Turns out no code changes were needed for gcc10!
* Also updated some dependency ranges in INSTALL.md.
* Make a new CI test "latest" -- using the latest supported release of
the toolchain and dependencies. That includes gcc10 in this case.
(This is different than the "bleeding edge" test, which tests against
the development master of many dependencies.)
* Make several test matrix entries (including bleeding edge, static
libs, and sanitizers) no longer test on every push. That makes
things take too long. They all still run nightly, and if you're
pushing a branch with the name "RB", "release", or "master", so they
will catch problems before releases. Also, all tests run any time
the branch name is "gh", so if you are preparing a patch
specifically to make changes to CI, make sure to do …
> Add CI test to exercise gcc10

- src/doc/oiiotool.rst
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
* Make sure the opname is always canonicalized
* Refactor to allow setup() to call skip_impl() to skip the impl and
copy instead.
* --ummip : make OiiotoolOp subclass (but note, it doesn't honor the
`:subimages=` modifier).
* --chnames : now OiiotoolOp and honors the `:subimages=` modifier.
* --chsum : now OiiotoolOp and honors the `:subimages=` modifier.
* --chappend : now OiiotoolOp and honors the `:subimages=` modifier.
> oiiotool continued refactor

- src/libutil/simd_test.cpp
SSE2 lacks an instruction for 32 bit SIMD int multiply. SSE4 has
it. We simulate it with a trick using unsigned multiply on SSE2. Chris
wondered if this alternate code path was adequately tested for
negative numbers, so I added a test to be sure.
> Extra test for multiplication

- src/include/OpenImageIO/fmath.h
OIIO::clamp had the property that if `val <= low`, it sets `low`.
But actually, when `val == low`, we want to use `val`, not `low`.
This may seem like the same thing, and it is for ordinary types.  But
OSL uses this clamp template for "dual" types (implementing automatic
differentiation), and it causes a case where `val == low` but `val`
carries derivatives that we want preserved, not written over by the
0-derivatives of the fixed `low` value.
> Fix minor issue with fmath's OIIO::clamp

- src/openexr.imageio/exrinput.cpp
- testsuite/openexr-suite/ref/out.txt
- testsuite/openexr-suite/run.py
Brief background: OpenEXR sorts channel names alphabetically. Most
formats dont allow channel naming at all, let alone forcing a
particular order contrary to the order the user tries to write it to
the file. OIIO promises that if there is RGB, they will be first and
in that order, next will be alpha if present, then depth, then
everything else.
So our exr reader will reshuffle channels into this canonical order
before presenting to the calling app. In addition to literal R, G, and
B being first, also obvious synonyms are accepted and understood to be
first ("Red", "Green", "Blue", and also "Y" in case it's just a
1-channel intensity and then maybe alpha).
A user noticed an interesting edge case: what if it's a normal map or
positional info, so the channel names are x, y, z? You want it in …
> Revise OpenEXR sorting of channel names into canonical order

- src/cmake/oiio_macros.cmake
On Fedora, Python must be run using version specific binaries, python2 or python3. Since we go to the trouble of finding python for the main library, we might as well use the discovered binary name and path.
This should fix errors for python not being found while running 'make test'
> Use discovered python executable

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
One-line utility function to open file, write a string, close file,
return if it succeeded. Analogous to the existing read_text_file().
> Filesystem::write_text_file()

- src/doc/pythonbindings.rst
- src/python/py_imagebufalgo.cpp
- src/python/py_oiio.h
- testsuite/python-imagebufalgo/ref/out-freetype2.4.11-py2.7-pybind2.3.txt
- testsuite/python-imagebufalgo/ref/out-freetype2.4.11.txt
- testsuite/python-imagebufalgo/ref/out-python2-alt.txt
- testsuite/python-imagebufalgo/ref/out-python3-freetype2.4.11.txt
- testsuite/python-imagebufalgo/ref/out-python3.txt
- testsuite/python-imagebufalgo/ref/out.txt
- testsuite/python-imagebufalgo/src/test_imagebufalgo.py
Was in C++, but seems it never quite got implemented in the python bindings.
> Implement Python version of IBA color_range_check

- .github/workflows/workflow.yml
- src/build-scripts/ci-build-and-test.bash
- testsuite/runtest.py
This will make it much easier to investigate failures or update ref
output when failures only happen on CI -- any test that fail tests
will produce a downloadable "artifact" consisting of all tests'
captured console output.
> Use GH CI to upload test output for any job that fails tests

- CMakeLists.txt
- src/iconvert/iconvert.cpp
- src/iinfo/iinfo.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/oiiotool/printinfo.cpp
- src/openexr.imageio/exrinput.cpp
- testsuite/missingcolor/ref/out.err.txt
- testsuite/oiiotool-readerror/ref/out.err-alt.txt
- testsuite/oiiotool-readerror/ref/out.err-alt2.txt
- testsuite/oiiotool-readerror/ref/out.err-debug.txt
- testsuite/oiiotool-readerror/ref/out.err.txt
- testsuite/openexr-chroma/ref/out.txt
- testsuite/openexr-chroma/run.py
- testsuite/openexr-damaged/ref/out-exr2.3.txt
- testsuite/openexr-damaged/ref/out-exr2.4-clang-noptex.txt
- testsuite/openexr-damaged/ref/out-exr2.4-noptex-spi.txt
- testsuite/openexr-damaged/ref/out-exr2.4-noptex.txt
- testsuite/openexr-damaged/ref/out-exr2.5.txt
- testsuite/openexr-damaged/run.py
- testsuite/openexr-multires/ref/out.txt
- testsuite/openexr-multires/run.py
- testsuite/openexr-suite/ref/out.txt
- testsuite/openexr-suite/run.py
- testsuite/openexr-v2/ref/out.txt
- testsuite/openexr-v2/run.py
- testsuite/openexr-window/ref/out.txt
- testsuite/openexr-window/run.py
Test more images that have been part of the openexr-images suite for
a while. Three cases:
* New images that weren't in the suite when I first set up these tests.
* Images that were "broken" because of (originally) missing features
in our exr support, that over the years are now supported.
* Images I was unaware of or somehow fell through the cracks.
In the process, improve and uniformize a number of error messages in
oiiotool, iinfo, openexr reading.
> Add more exr compliance tests and improve error messages

- INSTALL.md
Added a line for vcpkg users to discover additional opencolorio features they can build with that tool. This will help avoid people trying to build manually to enable features available via that relatively obscure package manager. Looking in the vcpkg repo isn't as helpful for people unfamiliar with that package manager or how it is configured.
None. Documentation patch only.
> Updated vcpkg instructions to aid discoverability

- src/doc/builtinplugins.rst
- src/doc/stdmetadata.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/texture.h
- src/include/OpenImageIO/typedesc.h
- src/maketx/maketx.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
This seems wrong. EXR standard metadata "worldToNDC" is exactly what it
says, not screen space. I'm not sure how we ended up with the historical
accident of reading "worldToNDC" from exr headers and auto-translating
it to "worldtoscreen".
The hope is that nearly no one is affected by any of this, since the
use case for these matrices was shadow maps, which were never
fully implemented in OIIO's TextureSystem anyway (they were last on
the list, and the VFX world switched to ray tracing before anybody got
angry enough at my procrastination to force me to implement it).
> EXR: Stop translating "worldToNDC" to "worldtoscreen".

- src/raw.imageio/rawinput.cpp
LibRaw recently fixed their long lasting spelling error on longitude (https://github.com/LibRaw/LibRaw/pull/304)
This means that any version of LibRaw from 0.20-Beta3 and newer has this fix and it will break oiio which uses the old misspelled parameter name.
This fix adds a LibRaw version check to know if it should use the misspelled parameter or the correct one.
Just keep in mind that this will cause LibRaw 0.20 versions older than Beta3 (i.e.. Beta1 and Beta2) to not work any more.
Don't think a test is needed for this small fix.
(adding new test cases if …
> Update LibRaw longitude

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
They already existed for float{4,8,16}, but were never implemented for
float3.
Add to simd_test.cpp both unit sanity checks and benchmarks for these
functions (including for the other classes where it already existed,
they were nonetheless not unit tested).
Also beef up simd_test by testing and benchmarking load/construcution
from scalar. Rename some test functions for clarity.
Along the way I realized a difference between scalar std::round and
our vector simd::round() in how they handle exact middle values
i+0.5. Because our round is more efficient (one instruction, whereas
std::round cannot be done in one op on x64, because "round midpoint
away from zero" is not a native hw rounding mode), put a big fat
comment warning about the difference.
> simd.h: add abs,sign,ceil,floor,round for float3

- src/include/OpenImageIO/simd.h
I was browsing some NEON docs and took the opportunity to fill in
implementations of a few more simd methods.
I don't have a way to directly test this myself, but hopefully
simd_test.cpp has enough unit tests to uncover if I've used the wrong
intrinsics for any of this.
I'm hoping that soon GitHub will add a way to run CI jobs on ARM CPUs
for Mac, if nothing else, so we'll have a way to verify this
architecture.
> simd.h: More support for ARM NEON

- src/oiiotool/oiiotool.cpp
Doesn't trigger an error on other compilers, or on newer MSVS. But this
minor rearrangement makes VS2015 happy, so let's just go with it and
not look under that rug.
Closes #2611
> Avoid unexplained build break with VS2015 -- presumed compiler bug

- .github/workflows/workflow.yml
- appveyor.yml
- src/build-scripts/gh-win-installdeps.bash
- src/include/OpenImageIO/argparse.h
- src/libutil/argparse_test.cpp
- src/oiiotool/oiiotool.h
To help track down build issues with MSVS 2015, re-enable appveyor.
Also split GHA CI to test windows for both MSVS 2019 and 2017.
Also address some warnings on windows.
> argparse -- try to resolve overload ambiguity

- src/include/OpenImageIO/unordered_map_concurrent.h
> unordered_map_concurrent: fix missing size decrement upon erase

- .github/workflows/workflow.yml
- src/build-scripts/ci-build-and-test.bash
- src/build-scripts/gh-installdeps-centos.bash
- src/build-scripts/gh-installdeps.bash
- src/include/OpenImageIO/argparse.h
- src/openexr.imageio/exrinput.cpp
- src/python/py_imagebufalgo.cpp
- src/python/py_oiio.h
A few weeks back, I rearranged a bit of ci-build-and-test.bash to invoke
cmake directly instead of the makefile wrapper. But in the process, I
accidentally caused it to always build `--target install` instead of
using the optional target `$BUILDTARGET` which is how clang-format runs
were supposed to have been triggered.
The result was the 'clang-format' test did a full *build* instead of
running clang-format. This was both much more expensive, and also
pointless: we weren't testing clang-format during CI at all.  Oops.
Thus, some recent checkouts weren't properly formatted. We also amend
the minor fixes that bring us into format compliance.
I also noticed that I can use apt-get to install OCIO on the Ubuntu
instances used by GH CI, so modify to only build OCIO from source if a
specific …
> Fix broken clang-format test

- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
SIMD improvements for emulating 8-wide on 4-wide HW: for many methods
on 8-wide SIMD types when running on 4-wide hardware, it's better (as
revealed by benchmarks) to implement as two 4-wide ops rather than
falling back to a purely scalar path.
Add operator*(vfloat{4,6,16}, float). On SSE, it hardly matters, no
better than letting the float be promoted to vfloat. But NEON has
vec*float.
Add NEON implementation of blend, min, max, reduce_add.
> simd.h improvements

- CMakeLists.txt
- src/cmake/oiio_macros.cmake
We previously disabled tests for a format when its library was not
found, but didn't consider if the library was found but the
`ENABLE_FOO` variable was set to intentionally disable it.
> Disable tests when support for format is disabled

- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool-attribs/ref/out.txt
- testsuite/oiiotool-attribs/run.py
Either -a or optional modifier :allsubimages=1 ought to have erased
an attribute from all subimages, but it was erased from only the first.
Add a test to verify that --attrib and --eraseattrib both apply
correctly to all subimages when requested.
> oiiotool: Fix --eraseattrib not applying to all subimages

- .github/workflows/workflow.yml
- src/python/py_oiio.h
By using the explicit `cast<TypeDesc>()` instead of allowing the
template system to figure it out, we were losing the `const` detection
and making it fail to match templates. It used to work, but a recently
added change in pybind11's master branch caused this to finally fail.
Also change the "latest releases" to use pybind11 2.5. (Only semi-related,
2.5 was fine, it was post-2.5 where we broke.)
> Fix build break due to pybind11 master recent change

- .travis.yml
- src/build-scripts/build_cmake.bash
- src/build-scripts/ci-build-and-test.bash
- src/build-scripts/ci-startup.bash
- src/build-scripts/gh-installdeps.bash
- src/make/detectplatform.mk
This is a step toward making sure we are habitually testing on ARM64.
It is incomplete at the moment, several individual tests fail and need
to be tracked down, so the test is marked as "allow_failures" so it
will never appear to fail.
> Re-enable travis and include an arm64 (aka aarch64) build

- src/doc/builtinplugins.rst
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageinout_test.cpp
- src/libOpenImageIO/imageioplugin.cpp
- src/oiiotool/oiiotool.cpp
- src/term.imageio/CMakeLists.txt
- src/term.imageio/termoutput.cpp
This is a little kooky maybe, but it was something I was playing a couple
years ago, finally inspired by Chris to clean it up and PR it.
This patch adds a "term" format which, instead of writing files,
outputs a preview image to a true color text terminal window.
Is any of this useful? I have no idea. But it's kinda fun.
The quick demo of this is:
oiiotool myfile.exr -o out.term
It will only do something useful if on a color terminal emulator with
24 bit color capability and Unicode. (I've tested it on the
gnome-terminal on Linux, and iTerm2 on Mac.)
The best quality results are on Mac if you are using iTerm2, it can
additionally do an actual pixel output (iTerm2 has as a nonstandard
feature the ability to send inline images to the terminal). This is
the "iterm2" method, but it's only …
> Terminal I/O of images

- .github/workflows/workflow.yml
- src/include/OpenImageIO/typedesc.h
- src/libOpenImageIO/formatspec.cpp
- src/libutil/paramlist.cpp
fmt is supposed to (if you include fmt/ostream.h) automatically
support any user type that defines an `operator<<()`. And so it did
through version 6.1.2.
Starting with 6.2.x, the presence of `operator bool()` throws it off,
particularly for our TypeDesc, which started rendering as "true" rather
than "uint8" or whatever. It seems that the fact that it can convert
to bool takes precedence, it formats as a bool, rather than notice that
there's a stream ouput option.
In this patch, we add a custom formatter for TypeDesc, which solves
the problem for `format("{}", typedesc)`, but unfortunately not for
`sprintf("%s", typedesc)`. I've filed an issue, but in any case, the
workaround to avoid incorrect formatting when using sprintf is to be
sure to use typedesc.c_str().
Signed-off-by: Larry Gritz …
> Build against more recent versions of {fmt}

- src/python/py_paramvalue.cpp
The `__getitem__` method taking an integer index correctly set the
return value policy so it returns in internal reference rather than
a copy, but the `__getitem__` method taking a string did not.
Also fix indentation.
> Minor fix to Python binding for ParamValueList

- src/doc/builtinplugins.rst
> PNG: Document the "png:compressionLevel" output hint.

- src/python/py_imagebuf.cpp
> Typo fix -- got 'ImageBuf.writable' name wrong

- src/libOpenImageIO/imagebufalgo_xform.cpp
Resizing an enormous image by a large scale factor could end up having
this allocation, which is xres*ntaps*sizeof(float), end up big enough
to overflow the stack. It's only done once per thread worker, so there
is no perf penalty to making it a heap allocation just in case it's
too big.
Closes #2004 
> IBA::resize: Use heap instead of stack for an allocation

- src/include/OpenImageIO/errorhandler.h
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/typedesc.h
- src/libOpenImageIO/imagebuf.cpp
- src/libtexture/environment.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture3d.cpp
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
- src/libutil/typedesc.cpp
- src/tiff.imageio/tiffinput.cpp
Another step toward switching to std::format notation.
The basic strategy is to make sure that all the classes that have
errorf (etc) methods using printf notation will also have errorfmt
(etc) methods using std::format notation. These will coexist for a
while to let people switch, before the printf ones will be marked
deprecated and then eventually removed.
In some cases where the methods aren't really part of the public
API, but only are used by interns, we are already skipping to the
deprecation marking or just changing them completely.
> More gradual fmt conversion

- src/png.imageio/png_pvt.h
- src/png.imageio/pngoutput.cpp
We weren't setting up the proper handler callbacks for libpng internal
errors to bubble up to the caller.
Tell libpng to turn off sRGB color profile check. There are many
false positives where embedded ICC profiles that don't match its
expectations (but that other people and apps consider fine) trigger
errors in libpng.
> Improved propagation of png write errors and fix sRGB profile check

- src/libOpenImageIO/imagebuf.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
* Fix some incorrect error calls in ImageBuf internals.
* Make sure that if no message bubbles up, we say "unknown error".
> Minor fixes to ImageBuf error reporting

- src/hdr.imageio/hdrinput.cpp
When the texture cache reads scanlines in random order, the same pixels could
be read many times over. Now the file offset for scanlines is cached for quick
random access.
Example command that is 18x faster here with this change:
```
oiiotool 8k.hdr --autotile 16 --flip -o out.exr
```
I'm not aware of an existing mechanism to test such performance issues.
> Fix poor performance with texture cache and HDR files

- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
In order to support Windows extended-length / long paths ("\\?\" style), I've added code to disregard the long path prefix when getting the REST arguments, for opening files.
Added 3 test cases in `test_get_rest_arguments()` of "strutil_test.cpp".
> Fix Windows long paths when opening files

- src/libOpenImageIO/exif.cpp
Fixes a compilation error, that appears on alpine linux.
```
/builds/lmarz/aports/testing/openimageio/src/oiio-Release-2.1.18.0/src/libOpenImageIO/exif.cpp: In function 'void OpenImageIO_v2_1::read_exif_tag(OpenImageIO_v2_1::ImageSpec&, const TIFFDirEntry*, OpenImageIO_v2_1::cspan<unsigned char>, bool, int, std::set<unsigned int>&, const OpenImageIO_v2_1::pvt::TagMap&)':
/builds/lmarz/aports/testing/openimageio/src/oiio-Release-2.1.18.0/src/libOpenImageIO/exif.cpp:789:20: error: comparison of integer expressions of different signedness: 'unsigned int' and 'OpenImageIO_v2_1::span<const unsigned char, -1>::index_type' {aka 'int'} [-Werror=sign-compare]
789 |         if (offset >= buf.size()) {
|
``` …
> Fix compilation error with armv7, x86

- .github/workflows/ci.yml
- src/build-scripts/build_libjpeg-turbo.bash
- src/build-scripts/build_libpng.bash
- src/build-scripts/build_libtiff.bash
- src/build-scripts/build_openexr.bash
- src/build-scripts/build_pugixml.bash
- src/build-scripts/build_pybind11.bash
- src/build-scripts/build_zlib.bash
- src/build-scripts/ci-build-and-test.bash
- src/build-scripts/gh-win-installdeps.bash
Last week, Vcpkg apparently had some flaw that recently caused it to
fail when building/installing libpng (among other things). It's been
fixed in the vcpkg main branch, but that hasn't propagated to the
vcpkg that's installed on the GitHub Actions CI runners, and that's
causing our Windows CI tests to fail.
Rather than wait out the fix, I'm just taking it into my own hands by
building all our dependencies from source on Windows. This means adding
bash scripts to download and build zlib, libpng, and libjpeg-turbo (and
maybe those will be helpful to others as well).
**Late breaking news** They beat me to it, vcpkg has been updated and
the GitHub CI Windows tests are passing again.
But I had already done this work! So I still would like to switch to
this methodology because:
* Sometimes …
> Windows CI: build dependencies ourselves

- src/include/OpenImageIO/fmath.h
> bit_cast should take a reference, not a value

- src/dpx.imageio/dpxinput.cpp
It's important not to mess with a passed-in IOProxy* in Input::close(),
because that proxy may not still exist.
> Fix to DPX IOProxy support

- CMakeLists.txt
- src/include/CMakeLists.txt
This just makes the build area's directory layout more closely resemble the source and install areas. The 'detail' directory, just in the temp build area, was one level below where we put it in src and install.
> Rejigger the build dir's detail area to be in the same spot as dist

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
The thing about IOProxy is, once closed, it can't be reopened. So it's
important that if an IOProxy-based file is in the IC, its ImageInput
should not be reclaimed by closing it (and that might not help the
file handle count anyway, since the main use of an IOProxy under those
circumstances is probably to read an image from memory).
> ImageCache should not close IOProxy-based files to stay in file limits

- src/include/OpenImageIO/typedesc.h
A previous patch removed the definition of OIIO_USE_FMT, which
inadvertently removed this helper class from the compilation stream.
> Re-enable fmt formatting helper for TypeDesc

- src/python/py_paramvalue.cpp
Oops, ParamValue.type ought to be a TypeDesc, just like in C++.  In
the Python binding overhaul of 2.0, it seems that I made a mistake and
unintentionally changed it to appear to Python as a string (e.g.,
'int' rather than TypeDesc('int')).
Fixing it to be the way it was originally intended would involve a
breaking change and not appropriate until such things are allowed by a
2.x -> 3.0 transition, so we'll just have to live with it.
Closes #2672 
> Document design flaw in Python ParamValue.type

- INSTALL.md
These were so out of date and unhelpful, it has to be better to
have no instructions at all. Tear it down and make room for somebody
to do it right.
> Remove old and misleading Windows install instructions

- .git-blame-ignore-revs
This new file contains the hashes of commits whose only function was
to reformat large amounts of code.
Ordinarily, this would make for confusing 'git blame' output, by
making old code written by author A appear to have a new modification
date and authorship by B, when in fact we know that B just did some
reformatting. This can make it especially hard to discern code history
after after commits that establish the use of "clang-format".
A new git feature (requiring git >= 2.23) allows pointing to a file
containing hashes of commits to be ignored by git blame:
git blame --ignore-revs-file .git-blame-ignore-revs
To avoid having to remember this all the time, consider adding this to
your git config:
git config blame.ignoreRevsFile .git-blame-ignore-revs
Note that git supports this feature but …
> Use .git-blame-ignore-revs

- INSTALL.md
- src/libOpenImageIO/imageinout_test.cpp
HEIF is a lossy format, and it seems libheif 1.8 changed internally
in such a way that the bit-for-bit comparsions of the write-read
cycle we do in imageinout_test started failing. (Bummer on our Mac
CI, where the homebrew version of libheif updated automatically and
then started failing.)
The easy solution is that just for this test, write zeros to the image,
not 1.0 values (which were coming out 254, not the expected 255).
> Support for libheif 1.8

- src/oiiotool/oiiotool.cpp
Plain old bug in all cases:
--croptofull botched the subimage count by reserving space for results
based on the subimages in the input image, but then only producing
results for the first one if -a (or :allsubimages=1) was not used.
Output specific bugs:
There are some operations that happen ephemerally upon output, mostly
to account for output file formats that don't support some feature of
the top image (like action_croptofull if the output format doesn't
support differing display and data windows, or action_channels if
there are more channels than are supported by the format, or
action_colorconvert when --autocc is used).
In these cases, we were forgetting that those operations may tend to
drop all but the first subimages, if no -a or :allsubimages=1 is not
used.  But that's NOT the …
> oiiotool: fix some multi-subimage bugs when outputting images

- CMakeLists.txt
It's been endless trouble, because the nature of the test is malformed
images that fail in inconsistent ways. I can never seem to make a
stable set of reference output for it, especially for OpenEXR
development master, which is always adding new fixes or tinkering with
exceptions and error messages.
So just don't run that test in the automated CI.
> Stop running the "openexr-damaged" test for CI.

- src/tiff.imageio/tiffinput.cpp
- testsuite/tiff-suite/ref/out-alt.txt
- testsuite/tiff-suite/ref/out-alt2.txt
- testsuite/tiff-suite/ref/out-jpeg9b.txt
- testsuite/tiff-suite/ref/out.txt
For a few rare edge cases of photometric interpretation, we fall back
on libtiff's ability to auto-translate to an RGBA image for us. It
only does this for the whole image at once, so we do it for the first
scanline we read (storing the whole image in a buffer, skipping the
conversion for subsequent scanlines -- and it can tell it's the
"first" scanline because the buffer isn't yet allocated).
The bug was that for these cases (such as a photometric YCbCr), if the
file was *multi-subimage*, we were not clearing the rgba buffer, so
upon reading the second subimage, it thought its buffer was already
filled, so it wasn't actually doing the read and convert, just using
whatever was already living in the buffer. Oops.
Also, I noticed that we should clear m_use_rgba_interface for each
subimage …
> Fix broken TIFF reads of multi-subimage non-spectral files

- src/ffmpeg.imageio/ffmpeginput.cpp
Don't copy from the data pointer if it's null, that indicates an error.
Related to issue #2688, but doesn't fully solve it.
> ffmpeg reader: avoid potential crash when frame can't be read

- src/python/py_oiio.cpp
- src/python/py_oiio.h
- testsuite/python-imageinput/ref/out-alt.txt
- testsuite/python-imageinput/ref/out-alt2.txt
- testsuite/python-imageinput/ref/out-python3.txt
- testsuite/python-imageinput/ref/out-travis-py2.7-pybind2.3.txt
- testsuite/python-imageinput/ref/out-travis.txt
- testsuite/python-imageinput/ref/out.txt
- testsuite/python-imageoutput/ref/out.txt
- testsuite/python-imageoutput/run.py
- testsuite/python-imageoutput/src/test_imageoutput.py
When transferring blocks of pixels (for example, by ImageInput.read_image
or ImageOutput.write_image), "half" pixels ended up mangled into uint16,
the only type of the right bit width.
But NumPy has a numpy.float16 type! A little bit of extra hinting to
pybind11 makes this work as users probably expect.
Fixes #2689  
> Python: Direct support for 'half' using numpy.float16 type

- src/include/OpenImageIO/fstream_mingw.h
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/sysutil.cpp
New versions of pugixml no longer generates variables like PUGIXML_LIBRARIES. The proper way is to link to `pugixml`. I also removed the `BEFORE` statement as it is unnecessary as far as I can tell.
I fixed a few problems for cross compiling with mingw from linux. All windows include files should be in lower case. I replaced some _MSC_VER macro checks with _WIN32.
> Fix pugixml linkage and some mingw build problems

- src/cmake/externalpackages.cmake
Seems that cmake's FindGIF.cmake isn't good at discerning minor
releases (prior to GIF 5.x including more info in its headers),
so saying "find_package(GIF 4.1)" doesn't work the way
we'd like, and seems to fail to find a legit 4.1 installation.
Go back to find_package(GIF 4).
We seem to have broken this in PR 2681, and I'm worried that people
with gif_lib 4.1 will find themselves mysteriously lacking GIF support
in their OIIO builds. I may do an emergency tweak release of 2.2 just
to address this.
> Fix GIF min dependency

- src/python/py_imagespec.cpp
- src/python/py_oiio.cpp
We have many classes that have methods
.attribute(name, intval)
.attribute(name, floatval)
.attribute(name, stringval)
.attribute(name, TypeDesc, anyval)
For ImageSpec.attribute() and OIIO.attribute(), the anyval was
restricted to only accept tuples. Fix these to bring them in line with
many other classes' attribute calls in which the 'anyval' really can
be just about anything -- tuples, lists, numpy arrays or other buffer
objects, or scalar values.
Fixes #2674 
> Python: be more forgiving in what's passed to attribute()

- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
This could stack overflow for large images.
Fixes #2703
> IBA::contrast_remap -- move alloca outside loop

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
ImageBuf uses ImageCache underneath. But this can lead to the following
unexpected behavior if you don't understand this:
1. Make an ImageBuf for an image, read it (even just header info).
2. Done with it, destroy the ImageBuf.
3. Some other part of the program, or even a different process, changes
that file on disk.
4. Make another ImageBuf with the same filename, thinking you're getting
the updated image, but in fact it's relying on the cached representation
which doesn't contain the changes made in step 3.
So these tiny changes try to make this much harder to shoot yourself in the
foot:
* New ImageBufs automatically call cache->invalidate on the filename
before they start reading, to ensure that if the file has changed on
disk, anything in the cache is invalidated.
* When you destroy …
> Fix ImageBuf vs ImageCache out-of-date image problem

- src/oiiotool/oiiotool.h
This was subtle. Empty subimage include/exclude specifications would
confuse compute_subimages(), which in turn would MUCH later do a
mis-allocation and lead to a situation in --resize where it would
iterate over subimages that had not been allocated.
> Fix crash in oiiotool --resize with multi-subimages

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Fix cause of a subtle bug: splitting an empty string returned one
string piece (also empty) instead of 0 pieces.
Beef up the Strutil unit tests in this area.
> Strutil::splits, splitsv should return NO pieces for empty string

- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/typedesc.h
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_channels.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libutil/typedesc.cpp
- src/openexr.imageio/exrinput.cpp
I wanted to use this elsewhere, decided it was general enough to be in
typedesc.h, not specific to ImageBufAlgo.
> Move type_merge functionality from IBA to TypeDesc

- src/tiff.imageio/tiffinput.cpp
For "mip-mapped" TIFF files where we use the multiple images in the file
to emulate MIP-maps rather than what we ordinarily consider subimages,
a call to `ImageInput::spec(subimage,miplevel)` was not properly
recognizing invalid subimage values and returning an empty ImageSpec
as advertised. Basically, we assumed that they would only ask for a
valid subimage and miplevel and didn't properly handle out of range
values.
Same problem for spec_dimensions().
Fixes #2719 
> TIFF: Fix spec() and spec_dimensions() for mipmapped tiff files

- src/include/OpenImageIO/platform.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imageinput.cpp
- src/tiff.imageio/tiffoutput.cpp
A bug (issue #2713) revealed that an alloca in IBA::colorconvert could
cause a stack overflow on an image that had an unusually wide number of
columns per scanline.
This patch takes a number of measures to help root out these problems
in the future:
* The OIIO_ALLOCA macro is amended to assert (in DEBUG builds only)
upon any attempt to alloca more than 1MB, which is surely a sign that
we have used alloca in an inappropriate place.
* A new OIIO_ALLOCATE_STACK_OR_HEAP macro is used to encapsulate an
idiom I have used before, to alloca small things but new[] big things,
and ensure in both cases that the memory is freed when the function
exists scope. I choose arbitrarily for "big thing" to mean <= 64 KB,
which is big enough for one 64x64 tile or one scanline of a 4k image
if it has 4 float …
> More principled approach to alloca to avoid stack overflows

- src/tiff.imageio/tiffoutput.cpp
Added 1 bits per sample support when writing tiffs (#2720).
```c++
#include <iostream>
#include <OpenImageIO/imagebuf.h>
#include <OpenImageIO/imagebufalgo.h>
#include <OpenImageIO/imageio.h>
using namespace OIIO;
int main(void) {
std::cerr << "Loading\n";
OIIO::ImageBuf buf("this_is_a_image.png");
buf.specmod().attribute("compression", "zip");
std::cerr << "Writing 3x2bpp\n";
buf.specmod().attribute("oiio:BitsPerSample", 2);
buf.write("this_is_a_3x2bit.tiff");
std::cerr << "Writing 3x1bpp\n";
buf.specmod().attribute("oiio:BitsPerSample", 1);
buf.write("this_is_a_3x1bit.tiff");
auto spec = buf.spec();
spec.nchannels = 1;
OIIO::ImageBuf buf2(spec);
OIIO::ImageBufAlgo::paste(buf2, 0, 0, 0, 0, buf);
std::cerr << "Writing 1x2bpp\n";
buf2.specmod().attribute("oiio:BitsPerSample", 2); …
```
> #2720 - Adding 1 bits per sample support to tiffs.

- src/webp.imageio/webpoutput.cpp
Support a `lossless` spec attribute to be able to output lossless webp images
TODO
> WIP: add support for lossless attribute ofimage spec for webp

- src/build-scripts/gh-win-installdeps.bash
The web site where we used to download pre-built ffmpeg binaries
seems to have disappeared.
> CI on Windows: Disable ffmpeg download, the link is broken

- src/iv/imageviewer.cpp
This can cause cache re-reads unnecessarily because it thinks you're
asking for potentially different configuration hints every time you
set the ImageBuf to a different subimage.
> iv shouldn't open with config unless it really means it

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
What data format does oiiotool write for its outputs? The ones
specified by -d, if supplied, but otherwise it will make a guess based
on the types of inputs it has seen.
This patches makes several improvements:
* Multi-subimage files were getting very confused because different
subimages may want different data formats, and it was at best
remembering data formats overall and by channel name, but not taking
subimages into consideration. Make this much more specific by
remembering both raw channel names (for all subimages), as well as
specific channels of named subimages.
* The way the input data formats were remembered had repeaded (and
non-matching) code depending on whether the input was read
immediately or lazily.  That is now cleared up, with the logic
refactored and expressed only …
> oiiotool: Improve guessing about output format based on inputs

- src/cmake/externalpackages.cmake
This PR adds date_time to the required boost components in cmake.
In order to save on CI, I compile/stage only the (shared lib) boost components needed for OIIO (and other deps).
Based on _src/cmake/externalpackages.cmake_, those should have been filesystem, system, thread & regex.
Without this change, cmake setup is completing successfully yet results in linker errors (see below).
With this change, cmake setup fails to detect the correct boost libraries while also documenting what libraries are actually required.
Linker erros without this change
> -- Build files have been written to: snip/oiio-Release-2.2.6.1/cmBuild
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
> LINK : fatal error LNK1181: cannot open …
> require boost date_time explicitly in cmake

- src/iff.imageio/iff_pvt.cpp
This used to work, was inadvertently broken in #2398, in Nov 2019, and
no release of OIIO 2.1 ever had it working!  (I guess people don't
come across 16 bit iff files very often?)
> Fix broken read of 16 bit iff files

- src/heif.imageio/heifoutput.cpp
- src/iv/imageviewer.h
- src/iv/ivgl.h
- src/libOpenImageIO/color_ocio.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture_pvt.h
- src/libutil/argparse.cpp
- src/libutil/filter.cpp
- src/nuke/txReader/txReader.cpp
- src/nuke/txWriter/txWriter.cpp
- src/oiiotool/oiiotool.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
- src/term.imageio/termoutput.cpp
This is good for optimization, allowing "de-virtualization" of function
calls in cases when the compiler can be sure that there can be no further
subclassing.
> Use 'final' liberally

- src/libOpenImageIO/maketexture.cpp
It was setting it, but later, too late for the particular case where
constant_color_detect was used and found a constant color and
also the config spec came in without any tile preference (still 0's).
So move the default initialization up to the top.
> make_texture was not correctly setting tile sizes

- src/include/OpenImageIO/benchmark.h
- src/include/OpenImageIO/simd.h
Fixed ARM NEON code path in src/include/OpenImageIO/simd.h, and a single-line change for a compile error in src/include/OpenImageIO/benchmark.h
All tests in simd_test binary are passing
- [x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x ] I have ensured that the change is tested somewhere in the testsuite
- [x ] My code follows the prevailing code style of this project.
> Fixed ARM NEON code path in simd.h, all tests in simd_test are passing

- .github/workflows/ci.yml
- src/build-scripts/gh-installdeps-centos.bash
One of our CI matrix entries -- building with clang -- has
mysteriously broken with compile errors complaining about reallocarray
being inconsistently declared in stdlib.h and gif_lib.h. It just broke
a few days ago, unrelated to any changes on our part. I have no idea
if it was the compiler or gif library that got updated and then broke.
Whatever. Insulate ourselves from random changes on GHCI by converting
this test to use one of the ASWF containers that we can count on to
have stable dependencies installed.
> Fix CI break

- src/libtexture/imagecache.cpp
For IC::add_tile() and IC::get_tile(), the documentation advertised that
passing chend < chbegin meant "all channels". But the implementation was
setting chend=nchannels but not setting chbegin to 0.
> IC bug fix: add_tile/get_tile not peroperly honoring chend < chbegin

- src/include/OpenImageIO/strutil.h
Cuda 10.1 seems to have trouble because of the `__attribute__` used in
`OPENIMAGEIO_PRINTF_ARGS`. Declan Russell suggests modifying the `#if`
to avoid using it for `__CUDACC__`.
LG further observes that `OPENIMAGEIO_PRINTF_ARGS` is only used for the
declaration of two functions, it seems like a nice decluttering to
just directly use the short attribute exactly where it is needed
instead of having a lengthy explanation and possibly defining
`__attribute__` everywhere as a side effect.
> Fix Cuda build break

- src/jpeg.imageio/jpegoutput.cpp
Allows saving progressive jpegs by adding the attribute "jpeg:progressive", an int which if non-zero will tell libjpeg to create a progressive file. 
TODO
> Add support for saving progressive jpegs

- .github/workflows/ci.yml
> CI: lock down on clang-format 10

- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/maketexture.cpp
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
There was no formal error setting! Errors were echoed to the optional
output stream, if supplied. But that's not good enough.
> Fix propagation of errors from make_texture

- src/build-scripts/install_homebrew_deps.bash
Now that we use Linux and the ASWF docker containers for the
"clang-format" test, there's no reason to have logic in this setup
script for Mac to choose a more restrictive set of package for that
case.
Same for clang-tidy and static libs tests -- we don't do these tests, and
if we add one, we will surely do it with one of the Linux containers.
> CI: Simplify install_homebrew_deps.bash for modes we don't use

- src/doc/imageinput.rst
- src/doc/imageinput.tex
Related to #2744
The discussion around #2744 came to the conclusion that the status quo already allows relatively efficient reading of data into separate per-channel buffers. This PR adds a section to the docs to make this approach more discoverable.
I didn't add a test, but since adding this to the docs makes this kind of use of the API "official" I maybe should...?
> Docs: illustrate reading image data into separate per-channel buffers

- .github/workflows/ci.yml
- src/build-scripts/build_libraw.bash
- src/cmake/externalpackages.cmake
- testsuite/raw/ref/out-libraw-0.20.2-gh.txt
- testsuite/raw/ref/out-libraw-0.20.2.txt
* Accommodate changes for 0.20.2 that Homebrew now has with some
updated reference output.
* Mistake in variable naming meant we weren't testing libraw master as
we previously thought.
> CI: Better libraw testing

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
ImageBuf methods subimage(), nsubimages(), miplevel(), nmiplevels(),
and file_format_name(), which are concerned with the file to which the
ImageBuf refers, only make sense for an ImageBuf that directly
refers to a file -- either by being constructed/reset from a filename,
or in some cases, being a direct unmodified copy of such an imageBuf. All
other cases, including pixel-copies of other ImageBufs (even those
that came from files), it is merely an in-memory image and doesn't
really refer to a file.
Clarify the docs (and fix the implementation) to ensure that for
any ImageBuf that is not a simple reference to a file, these methods
return a suitable default value.
Fixes #2755 
> Clarify certain ImageBuf methods for copied images

- src/build-scripts/build_opencolorio.bash
- src/cmake/modules/FindOpenColorIO.cmake
OCIO master recently renamed the symbol in its headers that we used to
detect its version, breaking OIIO's build against the current OCIO
top of tree master.
This change makes our FindOpenColorIO.cmake work with both old and new
OCIO.
Also, cut out other useless OCIO building (for our purposes) by having
our build_opencolorio.cmake disable buildig of GPU tests (which,
recently, became controlled by a different option than is used to
disable building all the other tests).
> Changes for recent OpenColorIO v2

- .github/workflows/ci.yml
We were running some CI tests only for PRs or for certain branches.
This may save some time, but I found that I was, more often than not,
naming my branches to trigger all tests to run. That's silly. Just run
all the tests every time, it's not that expensive.
> CI: Just run all tests, don't try to cleverly exclude some

- src/cmake/pythonutils.cmake
Without this, it was still getting confused on my Mac with multiple
python versions installed at the same time.
> Build: Require exact version if PYTHON_VERSION is specified

- src/doc/imagebuf.rst
- src/doc/imagebufalgo.rst
- src/doc/requirements.txt
- src/doc/texturesys.rst
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagebufalgo.h
* Bump breathe release to the latest (we'e been holding back because of
errors that we fix in the other elements of this patch, below)
* Changing declaration formatting, particularly in the ImageBuf and
ImageBufAlgo chapters, eliminates function ambiguity warnings and even
python exceptions we were getting in Breathe before.
* Document missing texture option fields and improve formatting.
* Instruct Doxygen to not catalog deprecated ImageBufAlgo functions.
> Improvements to docs and breathe setup

- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/typedesc.h
- src/libutil/fmath_test.cpp
Use `__builtin_bswap` when available. These seem to be 8-15x faster than
the std::swap-based implementation when multiple data values are
being swapped. (It's not dramatically better when swapping a single
value, either way it's pretty fast.)
Also add correctness unit test and benchmark for swap_endian.
> fmath.h: Use intrinsics for swap_endian

- src/libOpenImageIO/exif.cpp
- src/png.imageio/png_pvt.h
- src/png.imageio/pnginput.cpp
At present, it only reads Exif from png, it doesn't write.
Fixes #2573 
> Read exif encoded in PNG files

- src/doc/conf.py
- src/doc/imagebufalgo.rst
- src/doc/index.rst
- src/doc/requirements.txt
Inspired by OpenColorIO's beautiful docs, I'm adding the "sphinx_tabs"
extension to our docs, and testing them out in one little spot in
ImageBufAlgo to see if we like the effect.
Please look at https://openimageio.readthedocs.io/en/rtd/imagebufalgo.html
look at the first couple screenfuls to see the example of how the
tabs look. Opinions are welcome. Should we do this kind of thing more
extensively?
> Docs: Set up to try sphinx_tabs extension

- .github/workflows/ci.yml
Some permissions on GH changed due to security concerns, and that broke
the setup-nuget action we were using... which turned out to be obsolete,
anyway, and switching to the new recommended replacement fixes everything.
> Unbreak CI on Windows

- src/bmp.imageio/bmpinput.cpp
Negative heights indicate the file is stored with the y-axis inverted from normal. Interestingly the comment above was correct, but the code was checking the width instead of the height.
> Fix bmp row order

- src/cmake/checked_find_package.cmake
- src/cmake/externalpackages.cmake
Upon reading cmake docs mre carefully, it's clear that when you pass a
version to find_package (which does much of the heavy lifting inside
checked_find_package), it DOESN'T MEAN you want that version or
later. It means you want to find a version that is "compatible" with
the named version. The meaning of "compatible" is up to the package.
Some packages define it as being >= the requested version. Others
define it as being the same major release, or same major AND minor
release, or exact.
But generally speaking, we only care about the minimum version (e.g.,
"I want FooBar 8.0 or later"). And it's not guaranteed that is what
the package's compatibility will do. In fact, FooBar may be using
compatibility mode "SameMajorVersion", which will make our find of
FooBar succeed for 8.0, 8.1, 8.2, …
> Extend checked_find_package with VERSION_MIN and VERSION_MAX

- src/doc/imageioapi.rst
- src/doc/pythonbindings.rst
- src/field3d.imageio/field3doutput.cpp
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebuf_test.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/libOpenImageIO/imageioplugin.cpp
- src/openexr.imageio/exroutput.cpp
- src/python/py_oiio.cpp
- testsuite/python-imageinput/ref/out-alt.txt
- testsuite/python-imageinput/ref/out-alt2.txt
- testsuite/python-imageinput/ref/out-python3.txt
- testsuite/python-imageinput/ref/out-travis-py2.7-pybind2.3.txt
- testsuite/python-imageinput/ref/out-travis.txt
- testsuite/python-imageinput/ref/out.txt
- testsuite/python-imageinput/src/test_imageinput.py
TL;DR: This could crash during openexr output, turned out to be a subtle
race condition.
Long explanation:
Metadata gets prefixed with `<formatname>:` in cases where it's only
meant to be understood by the reader or writer of one format.  Formats
that support arbitrary metadata filter out any items that are prefixed
by the name of a different format (so you don't, for example, when
converting file formats, incorrectly copy a TIFF-specific metadata
hint into an OpenEXR file as literal metadata).
The specific code we used in the OpenEXR writer tried to do this but
got the threading locks wrong, and this could lead to very rare, subtle
crashes. It could have been fixed by a 3-line very local fix, but...
I also noticed that the same code was replicated in Field3D output (and
quite incorrectly …
> Fix rare OpenEXR multithread output crash

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
Filesystem::IOFile constructor now upon an error opening the file will
set the error message appropriately.
Move IOProxy::error() implementation from inline to be in
filesystem.cpp to hide its details, use a static mutex to make error
set and retrieval be thread-safe (we presume that the rare chance that
multiple threads will be setting or getting IOProxy errors
simultaneously are rare enough that it's not a thread performance
issue, and if the user is getting file I/O errors, a bit of minor
locking is the least of their worries).
Better checking of these errors in OpenEXR input and output open
operations.  Hopefully this means that exr file I/O errors will
percolate up more helpful error messages.
> Better error reporting for IOFile, esp. for OpenEXR writes

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/build_webp.bash
- src/build-scripts/gh-installdeps-centos.bash
- src/build-scripts/gh-installdeps.bash
- src/webp.imageio/webpinput.cpp
The WebPData::size is a size_t, on 32 bit systems it will balk at our
putting a uint64_t in it. Downcast explicitly so the warning doesn't
flag us.
Also some changes to ensure adequate testing of webp in CI. (Even though
we only CI test 64 bit systems, so this was not related to the specific
build break being fixed... but an excuse to make sure we are hitting it
a reasonable amount in CI.)
> Fix webp compile break on 32 bit systems

- .github/workflows/ci.yml
- src/build-scripts/install_homebrew_deps.bash
* No need to uninstall openssl for mac ci (in fact, it breaks things now)
* Mac CI python and numpy install refinement
> Mac CI cleanup

- src/include/OpenImageIO/ustring.h
- src/libutil/ustring.cpp
- src/libutil/ustring_test.cpp
OSL has some concerns about how ustring hash collisions could impact its
strategy for strings on GPU.
This patch adds some instrumentation to ustring to detect hash
collisions.  Added static ustring methods total_ustrings() and
hash_collisions(). The latter tells you the number of collision pairs,
including optionally enumerating them into a vector of ustrings. Also,
`getstats(verbose=true)`, in Debug builds only, will print all of the
colliding pairs.  These are both somewhat expensive if there are lots
of strings (my laptop takes about 4 seconds to find and print all
collisions for 10M ustrings). So if you are concerned about
performance in debug builds, call getstats(false) instead if you have
a truly enormous ustring table.
> ustring hash collision instrumentation

- src/openexr.imageio/exrinput.cpp
Fix for a few issues parsing rational values with large denominator in OpenEXR header.
Incorrect use of array index can cause divide by zero crash (observed consistently on Windows with repro image).
Conditional comparison was assigning 1 or 0 to int f declaration instead of the actual gcd value.
Changed gcd type parameter to long long to avoid uint->long int overflow on windows (long int is only 4-bytes on MSVC).
> Fix crash parsing OpenEXR header.

- .github/workflows/ci.yml
- src/build-scripts/gh-win-installdeps.bash
- testsuite/TESTSUITE-README.md
* Enable the tests to run for Windows CI. This will show failures until we fully fix it. But those reminders will be a constant prompt to keep working on this. We can always disable tests again if this is more of an annoyance than a helpful reminder.
* I noticed that several tests were failing because of lack of proper text rendering. Using vcpkg to install freetype on the Windows CI test gets another 6 tests working correctly!
* I added a TESTSUITE-README.md where I made some notes about how the test failure downloadable artifacts work and to update reference output when it differs per platform. Over time, we can grow this document to be a more comprehensive developer documentation for how the testsuite works.
This chips away a bit at #2797 (though of course only solves a few of those …
> Fix several Windows CI tests involving text

- src/heif.imageio/heifinput.cpp
valid_file was commented out, comment reffered to missing definitions. These defs are not missing currently.
> Re-add the HeifInput valid_file check

- .github/workflows/ci.yml
- src/build-scripts/build_pybind11.bash
- src/cmake/pythonutils.cmake
- src/python/CMakeLists.txt
- src/python/py_oiio.h
Use pybind11 functions to set up python module, it's got superior logic
to what we were doing.
Bump pybind11 version default in build_pybind11.bash
Fixes #2806
> Some refactoring to remove unnecessary linkage to python libs

- INSTALL.md
- src/doc/builtinplugins.rst
- src/heif.imageio/heifoutput.cpp
Requires libheif built with libaom or dav1d/rav1e. I have tested this, but really not very extensively. It shouldn't cause any regressions though.
> Enabled AVIF encoding with libheif (#2811)

- src/python/py_oiio.h
This did not seem to warn before a recent patch were I switched to using a pybind11 configuration macro.
> Fix recently-symptomatic python2 vs clang warnings

- src/heif.imageio/heifinput.cpp
- src/heif.imageio/heifoutput.cpp
With some recent heic related packages, we lost the ability to build
against some older libheif versions that we purport to support. We may
eventually want to raise the minimum supported libheif, but in the
mean time, this restores the prior build abilities.
> Fix build break for older libheif

- src/libOpenImageIO/color_ocio.cpp
The functions we depend on are all still there, they just moved from
these headers into the main OpenColorIO.h.
> Fix build break against OpenColorIO master -- headers disappeared

- .github/workflows/ci.yml
- src/build-scripts/build_libjpeg-turbo.bash
- src/build-scripts/build_libtiff.bash
- src/build-scripts/ci-build-and-test.bash
- src/build-scripts/gh-win-installdeps.bash
- testsuite/python-imageinput/ref/out-python3-win.txt
- testsuite/python-imageoutput/run.py
- testsuite/runtest.py
* Change to finding a consistent Python version (3.7)
* Install numpy
* On Windows, convert crlf to lf before diffing reference output, so we
don't get mismatches just because of LF vs CRLF.
* Update ref output on testsuite/python-imageinput
* Fix windows detection in runtest.py oiio_relpath
* Fix some semicolon problems that were making bash command lines conused
Along for the ride:
* Have ci-build-and-test.bash send OIIO_CTEST_FLAGS as extra args to ctest
* Remove some needless verbosity from the dependency building scripts.
> CI: fix Windows python tests

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
Similar to C++17 std::filesystem::path::generic_string(), but for a
filepath sent as string_view.
While I was there, I noticed that a few Filesystem functions that I
declared as `noexcept` actually call things that can throw, so I put a
few try/catch in stratgic spots. Nobody had reported a problem with
this, and maybe it would be fine, but it's the right thing to do.
> Filesystem::generic_filepath.

- .github/workflows/ci.yml
- src/iconvert/iconvert.cpp
- src/idiff/idiff.cpp
- src/oiiotool/oiiotool.cpp
- testsuite/jpeg-corrupt-header/ref/out.txt
- testsuite/missingcolor/ref/out.err.txt
- testsuite/oiiotool-copy/run.py
- testsuite/oiiotool-readerror/ref/out.err-alt.txt
- testsuite/oiiotool-readerror/ref/out.err-alt2.txt
- testsuite/oiiotool-readerror/ref/out.err-debug.txt
- testsuite/oiiotool-readerror/ref/out.err.txt
- testsuite/oiiotool-text/run.py
- testsuite/oiiotool/run.py
- testsuite/runtest.py
- testsuite/texture-overscan/run.py
* Try to address the OpenEXR thread pool hanging when we call exit().
* Strive to remove all exit() calls after any file reads happen,
in oiiotool, iconvert, and idiff.
* This does not stop all hanging.
* Temp workaround: for the Windows CI tests, use ctest commands to
allow each test to timeout 4 times before giving up. To be clear,
this does not solve the problem, it only masks it. But it helps
us "pass" those tests, exposing any other problems occurring with
them, and we will return later to find the source of any residual
timeouts.
* Update ref output for several tests where the differ slightly under Windows.
* Make runtest.py convert text output line endings cr-lf -> lf before
comparing to reference output. (This eliminates unnecessary diffs.)
* Update many tests' run.py file to use …
> Various fixes to make more Windows CI tests pass

- src/libOpenImageIO/exif.cpp
I had a crash on reading a JPEG image coming from a Canon EOS1200D.
After investigation, it appears that an IFD offset was larger than the buffer size. This is tested for various Exif IFD but not for the one spotted in this commit (INTEROP).
I am not sure why I have this problem in the first place (Bad header ? or memory leak ?)  but I assume this check won't hurt.
> [exif] memory leak in exif parse

- .github/workflows/ci.yml
- src/build-scripts/build_pugixml.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/Findpugixml.cmake
* CI use latest PugiXML release
* Have the 'latest' test use OCIO v2 RC1
* Bump which version of fmt we download by default
> CI: Bump some dependency versions that we test against

- testsuite/null/run.py
This fixes the testsuite/null test on Windows.
> Windows CI fix: windows shell treats quotes differently

- src/cmake/modules/FindOpenJpeg.cmake
Added openjpeg verson 2.4 to all search paths in `src/cmake/modules/FindOpenJpeg.cmake`
> added openjpeg-2.4 to OpenJpeg_include_paths

- src/include/OpenImageIO/platform.h
But only for C++ >= 17 when inline constexpr variables became available.
It defines to simply constexpr for older C++.
> platform.h: define OIIO_INLINE_CONSTEXPR to be `inline constexpr`

- src/libOpenImageIO/imagebuf_test.cpp
This is a weird thing we're doing in this very artificial test,
removing a file when the IB reading it is still alive. That's safe on
Unix, where a file with an open file handle still be safe to read even
if it's removed.  But it's not kosher on Windows.  Fix by simply making
sure that in this test, we aren't doing the unadvised thing of having
the IB still active on the file we're deleting. This should fix the
unit_imagebuf test that is failing our Windows CI.
> imagebuf_test: reset the IB before we remove the file it's reading

- src/cmake/pythonutils.cmake
This subtle change basically allows the python bindings to work correctly on windows.
For some background, I don't think I've ever gotten OIIO python bindings to work on windows, I've always chalked this up to using different versions of MSVC and never thought much of it (and just learned to only use the bindings at work).
All dependencies would have been installed via `vcpkg`.
The sort of error I would typically see was:
```python
>>> import OpenImageIO
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing OpenImageIO: The specified module could not be found.
```
Not terribly informative, but if instead I do:
```python
from ctypes import cdll
cdll.LoadLibrary("./OpenImageIO.cp38-win_amd64.pyd")
```
We get a popup message …
> Changing pybind11 bindings to used SHARED rather than using MODULE

- src/build-scripts/gh-win-installdeps.bash
We were failing this test because of lack of JPEG support in the TIFF we
were building. Rather than fight it, just use vcpkg to get tiff.
> Windows CI: get tiff-suite test passing on Windows

- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/string_view.h
- src/libutil/span_test.cpp
- src/oiiotool/oiiotool.cpp
When we wrote our `span<>`, we based it off the draft for std::span,
which at that time specified span::size() as ptrdiff_t, which is
signed. By the time std::span got finalized in C++20, it was changed
to size_t, which is unsigned. Ick. Switching to size_t will be an API
break, so we can't do that until we're at a version where it's ok to
make breaking changes.
But we can stage a few changes that will make that future transition
easier.
* Add std::size() and std::ssize() wrappers for both span and
string_view.  This gives downstream apps the opportunity to avoid
span::size(), instead using std::size(the_span), which is guaranteed
to be unsigned, and std::ssize(the_span), which is guaranteed to be
signed, and both of these will work now as well as after we make the
other breaking changes. …
> Start staging span and string_view size and ssize changes

- src/include/OpenImageIO/strongparam.h
- src/libutil/CMakeLists.txt
- src/libutil/strongparam_test.cpp
Consider this a design review. The point is all explained in depth in the comments, I won't restate it here.
This is an idea I've been contemplating for a long time. I want people to think about whether using this idiom -- sparingly, in   the kinds of places where we may have used an enum to bring more clarity than a bare bool or int -- would help improve code readability and reduce parameter passing errors. If so, I'd like to start using it. But if people think it's a needless  flourish that detracts from code readability, then I can be persuaded to abandon it.
> StrongParam helper for disambiguating parameters

- src/libOpenImageIO/color_ocio.cpp
- src/oiiotool/oiiotool.cpp
Ugh, the argument order of the headers and documentation didn't match
that of the implementation, with the inverse and unpremult args swapped.
Let's declare that the documented version is correct, and fix the implementation
to match.
> Fix argument order mismatch on IBA::ociolook and ociofiletransform

- src/cmake/externalpackages.cmake
This was causing failed CI tests and probably confused users.
libheif 1.10 is very broken on MacOS. The author says that 1.11 will come soon.
> Don't use the version of libheif that's known to be broken on Mac

- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
libtiff trunk is removing these custom types from future
versions. They have been there forever, since long before the std
versions were present.
> Use std types, not TIFF-defined types

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/ci-build-and-test.bash
- src/include/OpenImageIO/color.h
- src/libOpenImageIO/color_ocio.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_colorconfig.cpp
Oops, we used the wrong name for the env variable, and that CI test
wasn't getting the OCIOv2 RC all along!
Add OIIO::ColorConfig::OpenColorIO_version_hex().
Have oiiotool --help print the OCIO version.
Also Bump the pybind11 version for the "latest" test, and update
INSTALL.md a bit to document the latest versions known to work of
several dependencies.
> OpenColorIO v2 miscellany

- .github/workflows/ci.yml
- src/iv/ivgl.cpp
Also bump the number of allowed timeouts on Windows to help pass
tests until we fully track down the OpenEXR deadlock problem.
> Build break fix for new Qt version in VFX Platform 2021

- src/include/OpenImageIO/detail/farmhash.h
- src/include/OpenImageIO/hash.h
- src/include/OpenImageIO/strutil.h
- src/libutil/hash_test.cpp
Do some adjustment/simplification of the macros that set up the right
decorators on the new inline farmhash.
Some additional constexpr's, including Strutil::strhash().
Add to hash_test verification of the actual results of each of the
hashes, so we know that we don't break them over time, that they give
the same result on all platforms, and most immediately, to 100% verify
that the new constexpr inline version of the hash precisely matches
the old procedure call one.
Augment the existing benchmarking of the hashes to include
farmhash::inline.  It tries a variety of string sizes. I was worried
that the constexpr/inline version would be a performance hit because
it can't use any of the SSE intrinsics (which, ugh, aren't declared
constexpr in the headers).  But it turns out that the inline …
> Modify hash_test to verify correctness and stability of the hashes

- .github/workflows/ci.yml
- src/build-scripts/ci-startup.bash
This speeds up CI builds by 1/2 - 2/3 of total time, for PRs that are
minor changes by reusing the compiled results from previous runs.
Most of the remaining time cannot be squeezed down -- it's the
instantiation of docker containers and running the testsuite
itself. But the build (including of dependencies we build from
scratch) is dramatically faster.
Currently, this depends on ccache, so is for Linux/Mac only. I'm also
working on doing something similar for Windows, but it's not ready for
review yet.
> Speed up CI with GitHub 'cache' action + ccache

- src/cmake/compiler.cmake
I thought I did this a long time ago, but I keep forgetting after release branches to turn off the warnings.
Our CI tests will still turn warnings into errors so we catch them during development, but for *release* branches, ordinary users will have builds that are more tolerant of warnings.
> Turn off STOP_ON_WARNING default for release branches

- src/cmake/externalpackages.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
- testsuite/openexr-damaged/ref/out-exr3.0-clang-ptex.txt
Need some include fixes to more gracefully handle the case where
Imath_ROOT points to a custom build (say, of Imath 3.x), but there is
a system installation of a different version (say, OpenEXR 2.x in
/usr/include, which could easily end up earlier in the path list).
Also update some reference output due to recent bug fixes in OpenEXR,
where error messages changed.
> Imath/OpenEXR 3.x fixes

- src/psd.imageio/psdinput.cpp
Fixes #2846 
I realise that this key isn't specified in the documentation as one with an 8 byte length, but this certainly appears to fix this issue and causes the "remaining" variable in load_global_additional() to drop to exactly zero.
> Fix loading PSB with cinf tag

- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
I have submitted a PR to Imath that adds "interopability" constructors
and assignment, that use some templates to allow seamless
construction, assignment, and passing of "foreign" vector types to
Imath vectors. This makes it easier library A that uses Imath vector
types in its API to interact with app or library B that has a custom
internal vector type, without a ton of ugly casts and copies.
(See https://github.com/AcademySoftwareFoundation/Imath/pull/91)
These created a few minor conflicts with OIIO's internal SIMD classes
and their construction and casting from Imath types. This patch cleans
up the ambiguities:
* Make Imath::V4f -> simd::vfloat4 and Imath::M44f -> simd::matrix44
constructor `explicit`.
* Make the simd types `simd()` method (returning the underlying raw SIMD
type) also …
> Changes to accommodate upcoming Imath vector conversion changes

- src/build-scripts/install_homebrew_deps.bash
Homebrew just upgraded to Qt6, and that breaks us. Peg to Qt5 as a
temporary measure to let our CI pass, until somebody figures out what
needs to be fixed for full Qt6 compatibility.
> CI: Use Qt5 as a temporary measure

- src/gif.imageio/gifinput.cpp
Calling ImageInput::open() with a file path that doesn't exist will cause OIIO to attempt to load the missing file with all plugins. When it gets to the gif plugin the file descriptor is not checked correctly (windows only). This causes an assert inside DGifOpenFileHandle() when it calls _setmode().
> Fix error checking for file descriptor in gifinput on windows

- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imageoutput.cpp
There were some flaws in the logic of IB::set_write_format that could
cause a crash when used in conjunction with a file format that doesn't
support per-channel data types (even if the set_write_format call
specified a single type rather than per-channel types!).
There are basically two problems I fixed here.
First, in ImageBuf::write, where we are dealing with the fact that
set_write_format previously registered a request, be extra careful
that the "default" data format is the "biggest" type out of the
per-channel choices, and also make sure that if all the channels are
identical, we just use the default type and clear the channelformats
vector.
Secondly -- and more importantly to the crash itself -- in
ImageOutput::to_native_rectangle, if the output file format does not
suport …
> Fix crash related to ImageBuf::set_write_format

- src/raw.imageio/rawinput.cpp
> Make RAW files handle Unicode filenames on Windows

- src/doc/Doxyfile
- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
The oiiotool --colorconvert operator (and the other color conversion ops)
have an optional modifier ":unpremult=1" that will bracket the color
transformation with an unpremultiply/premltiply. But the implied
colorconvert that happens upon input and output with --autocc has no such
option, which is an oversight. This patch adds the ability to control
whether autocc transformations happen in an unpremultiplied state (which I
believe they SHOULD, generally speaking).
Also beef up the docs and help messages in some areas where I
coincidentally realized that -i and -o explanations omitted some of
the possible options.
> oiiotool --autocc now has optional :unpremult=1 modifier

- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/strutil.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_addsub.cpp
- src/libOpenImageIO/imagebufalgo_channels.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagebufalgo_copy.cpp
- src/libOpenImageIO/imagebufalgo_deep.cpp
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/libOpenImageIO/imagebufalgo_mad.cpp
- src/libOpenImageIO/imagebufalgo_muldiv.cpp
- src/libOpenImageIO/imagebufalgo_opencv.cpp
- src/libOpenImageIO/imagebufalgo_orient.cpp
- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageioplugin.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture3d.cpp
- src/libtexture/texture_pvt.h
- src/libutil/strutil.cpp
- src/python/py_imagebuf.cpp
- src/python/py_imagebufalgo.cpp
- src/python/py_imageoutput.cpp
- src/term.imageio/termoutput.cpp
Update old calls to Strutil::format to new fmt conventions, convert
some sprintf-like calls to std::format like calls.
This is not meant to be comprehensive; there is more work to do.
It's just an opportunistic bite at getting some of it done.
> More format modernization

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
A recent commit in the OpenEXR master changed which headers are
transitively included by other OpenEXR headers, and that broke our
build until this patch adds the missing headers explicitly.
The change may or may not be reverted on the OpenEXR side, but this
patch to OIIO at least unbreaks our CI in the mean time, and has
no down-side.
> Fix build breaks against recent OpenEXR 3.x additions

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/gh-installdeps.bash
- src/libutil/spin_rw_test.cpp
- src/libutil/spinlock_test.cpp
- src/oiiotool/oiiotool.cpp
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
Fix minor warnings and deprecations of C++20.
Bump to more modern ubuntu images for recent-year tests and make some
related adjustments. Also make sure that the "latest" and "bleeding edge"
tests are using python3, they were inadvertently still using python2.
> CI: test C++20 on the Linux bleeding edge test.

- src/libOpenImageIO/maketexture.cpp
- testsuite/oiiotool-maketx/ref/out-win.txt
- testsuite/oiiotool-maketx/ref/out.txt
- testsuite/oiiotool-maketx/run.py
This patch prevents Inf from showing up in texture file output of
make_texture by clamping to the range of `half`.
When making a texture out of float values, it's not too hard to end up
with valid but large float values that are outside the range
representable by a `half` (fp16) value and therefore will get
converted to an `Inf`, which nobody wants in their texture.
This is a bit more computation, but it only happens if the image source
was half or float, and the output texture file is half, so it doesn't
represent any additional expense at all for most texture conversions,
which are of integer based files.
> make_texture: Clamp half texture values to prevent Inf values popping up

- src/libutil/ustring.cpp
- src/libutil/ustring_test.cpp
This patch ensures that two ustrings will never have the same hash value.
The basic strategy is that the usual 64 bit hash of the characters provides
an initial guess. If no other string has already used that hash (as is
almost always the case), we use it. However, if a different string already
took that hash value, we rehash, and repeat until we find an unused hash.
We maintain a "reverse hash map" that relates hashes to ustrings to
help figure this out efficiently. (Note: This adds at least another 16
bytes per unique ustring to maintain the reverse map. Do we care?
Probably few applications are in the business of creating more than a
few million distinct strings.)
Because we are recording the collisions as they happen, this also
greatly simplifies (and reduces to trivially low cost) …
> Overhaul ustring hash collision handling

- src/targa.imageio/targainput.cpp
- testsuite/targa-tgautils/ref/out.txt
- testsuite/targa-tgautils/run.py
All of our prior tga tests had valid thumbnails. The code skipped the
thumbnail if the "offset to the thumbnail" was 0. But if the offset was
nonzero but the thumbnail record at that spot had a 0x0 size, we just
ran merrily along, and on Windows in debug mode even it an assert.
This patch makes it understand that a 0x0 thumbnail size means no
thumbnail.
I added an image from Doug Rogers, the reporter of the problem, to the
oiio-images repo in the targa directory, and updated the OIIO testsuite
to also check that image. (So testsuite will fail for people who don't
update their oiio-images repo.)
Also changed some stray refs to &vector[0] to vector.data().
Fixes #2900
> Targa read fix for tga files with 0-sized thumbnails

- src/tiff.imageio/tiffinput.cpp
- testsuite/tiff-suite/ref/out-alt.txt
- testsuite/tiff-suite/ref/out-alt2.txt
- testsuite/tiff-suite/ref/out-jpeg9b.txt
- testsuite/tiff-suite/ref/out.txt
The problem occurs when a tiff file has vertical size which is not multiple of the tile size.
For example tile size 64x64 and size 1240x1240. In this case, when `libtiff` reads the tiles on the last row, it moves the data to the bottom of the tile (vertically), but oiio starts reading from the top of the tile.
I have a pre-existing .tx file which is not loaded correctly.
This is the result without the fix:
And this is with the fix:
I also tested with `zackthecat.tif` from the tiff test suite. In this case the whole image is shifted because the tile is bigger than the image: resolution 234x213 with tile size 240x224
with 2.2.11.1
vs with the fix
I have not run the tests locally - not sure how yet, but I suppose the fix works and test cases need to be updated
command used:
```
./oiiotool -i …
```
> Fix reading tiff files when size is not multiple of tile size

- src/doc/imageioapi.rst
- src/doc/oiiotool.rst
- src/include/OpenImageIO/imageio.h
- src/oiiotool/oiiotool.cpp
Added utility function OIIO::get_extension_map() which returns a
`std::map<std::string, std::vector<std::string>>` listing all
image file formats and their presumed file extensions.
`oiiotool --list-formats` helps to test this and is useful in its own
right.
Closes #2615
> get_extension_map and oiiotool --list-formats

- src/build-scripts/gh-win-installdeps.bash
- src/cmake/externalpackages.cmake
- src/jpeg.imageio/CMakeLists.txt
GitHub Actions in its wisdom has removed pre-installed Boost from the Windows
images, causing our CI to fail early in the cmake configure stage when finding
dependencies, doesn't even get as far as starting to compile any modules.
Instead, this change gets boost from vcpkg, just the pieces we need.
Unfortunately, although this approach finds the headers and completes the build,
several testsuite tests fail.
I need to track down the test failures, but even as it stands, this is still a step forward,
compared to having no idea at all if a PR going through CI breaks the Windows build.
> Fix missing boost path on recently broken GHA CI

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
Ordinarily, oiiotool will exit upon encountering an error (such as an
input file not being found). When operating on a frame range or with
frame number wildcards, that means that it will exit without attempting
the rest of the frame range.
The new `--skip-bad-frames` command line argument means that an error
will skip the rest of that iteration, but not exit, instead starting
fresh on the next frame in the sequence. (But if any frame in the
sequence encounters an error, the exit code of the oiiotool command
will still be EXIT_FAILURE.)
> oiiotool --skip-bad-frames

- src/include/OpenImageIO/color.h
For the case of applying a color transformation to just one color, we
were sloppy and set the strides to 0 (just one color means we are not
iterating from point to point using the strides).
OpenColorIO 1.x didn't care, but OpenColorIO 2.0 throws an exception if
the strides don't look valid.
Thanks to Thomas Metais for the fix suggestion.
> Avoid OCIO 2 exception by setting strides correctly

- .github/workflows/ci.yml
- src/include/OpenImageIO/detail/farmhash.h
Apparently all the recent farmhash changes are fine with C++14 mode,
and fine with C++11 mode on gcc 4.8, but gets some errors when
used in newer compilers (gcc6+) using C++11 mode.
Add a CI test with gcc10 but with C++11 compatibility to verify this fix.
We will remove this test once we retire C++11 compatibility.
Fixes #2909
> Fix function name ambiguity in farmhash.h for C++11 and certain compilers

- src/doc/builtinplugins.rst
- src/libOpenImageIO/imageinout_test.cpp
- src/tiff.imageio/tiffinput.cpp
Also beef up docs, which had neglected to mention that proxy was
supported for a few other formats.
Closes #2920
> TIFF: support IOProxy for input

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/exif.cpp
- src/libOpenImageIO/maketexture.cpp
- src/libOpenImageIO/xmp.cpp
- src/nuke/txWriter/txWriter.cpp
In many cases, this informative debugging code was left over from when
parts of this code was strictly a command line utility. It's not
appropriate for a library call, especially on Windows.
Make sure every last output to std::cerr is guarded by some
preprocessor symbol that would only be enabled when one of the
developers is trying to do some "printf debugging".
Closes #2922
> Eliminate the last few std::cerr outputs

- INSTALL.md
- Makefile
- src/cmake/compiler.cmake
This does not (YET) change the minimum to C++14. For now, you can still
build for C++11 -- and with compilers that only support C++11 -- by using
CMAKE_CXX_STANDARD=11.
By changing the default, we hope to more thoroughly test everybody's
ability to compile C++14, ahead of the actual cut-off when we make that
the true miimum.
Also, the latest OpenVDB 8.0 does has C++14 as a minimum, so compiling
in C++11 mode will automatically disable OpenVDB support if OpenVDB >=
8 is what is found. We expect an increasing number of our dependencies
to drop support for C++11, so we want our default compilation mode to
be one that doesn't silently drop format support without
users/builders being aware of it.
> Change default C++ standard to 14

- src/include/OpenImageIO/hash.h
C++11 build of OIIO failed with:
```
[  1%] Building CXX object src/libutil/CMakeFiles/OpenImageIO_Util.dir/argparse.cpp.o
In file included from /Users/devernay/Development/oiio-2.2.13.0/src/libutil/argparse.cpp:16:
In file included from /Users/devernay/Development/oiio-2.2.13.0/src/include/OpenImageIO/argparse.h:20:
In file included from /Users/devernay/Development/oiio-2.2.13.0/src/include/OpenImageIO/paramlist.h:17:
In file included from /Users/devernay/Development/oiio-2.2.13.0/src/include/OpenImageIO/attrdelegate.h:13:
In file included from /Users/devernay/Development/oiio-2.2.13.0/src/include/OpenImageIO/typedesc.h:29:
In file included from /Users/devernay/Development/oiio-2.2.13.0/src/include/OpenImageIO/strutil.h:24:
/Users/devernay/Development/oiio-2.2.13.0/src/include/OpenImageIO …
```
> fix c++11 build

- src/build-scripts/build_libjpeg-turbo.bash
- src/build-scripts/build_libpng.bash
- src/build-scripts/build_libtiff.bash
- src/build-scripts/build_opencolorio.bash
- src/build-scripts/build_openexr.bash
- src/build-scripts/build_pugixml.bash
- src/build-scripts/build_pybind11.bash
- src/build-scripts/build_webp.bash
- src/build-scripts/build_zlib.bash
- src/build-scripts/gh-installdeps.bash
It seems that for CMake, --config should only be used in conjunction
with --build. Who knew? Things are breaking right and left now, especially
on GitHub Actions CI. But also on my laptop.
Hypothesis: maybe this was silently ignored in older cmake versions, but
now with CMake 3.20 is a hard error? Yeah, it seems that the GHA machines
now have cmake 3.20 installed, and they did not until a few days ago.
> CMake: don't use --config inappropriately

- .github/workflows/ci.yml
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenEXR.cmake
Ever since adding OpenEXR 3.0 support, we had some cases where
installations that built the 2.x IlmBase and OpenEXR portions
separately and installing to separate areas, were not being found
correctly.
Also make some minor changes to ci.yml to make sure we are documenting
the right openexr versions used for each test.
Fixes #2928
> Build: be robust to certain OpenEXR 2.x config files

- src/libOpenImageIO/imagebufalgo.cpp
Fixes the bug reported in #2937, whereby non RGBA images were effectively reading into negative memory when passed to `fillholes_pushpull`
> Added logic to copy along the alpha_channel when generating sub-images for fillholes_pushpull

- src/cmake/externalpackages.cmake
- src/include/CMakeLists.txt
- src/include/OpenImageIO/Imath.h.in
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
We broke things subtly for older OpenEXR when we added the 3.x
support.  Without this fix, our exported CMake config files weren't
properly exporting the OpenEXR include path as the interface includes
for OIIO libraries. This doesn't affect the OIIO build itself, but it
can affect downstream libraries that use OIIO as a dependency and
rely on our exported cmake config files.
We also remove the need for OpenEXR/OpenEXRConfig.h entirely through
header configuration.
> Adjust openexr includes

- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- src/bmp.imageio/bmpoutput.cpp
Temporary allocations were made and freed for each scanline read or
written. Do it once per image and reuse. When reading, eliminate one
temp buffer by writing data into its final location, also eliminating
a needless extra copy of each scanline.
> BMP: eliminate wasteful allocation and copying

- site/spi/Makefile-bits
- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
Support single channel, 8-bit grayscale bmp files. 
I did not add a test.
This is a small bug fix that should not need a CLA, updated documentation or tests. The code, except for the color_table_is_all_gray method, is copy/paste from an email exchange with Lary Gritz or from Larry's own lg-bmp branch where he cleaned up memory allocations when reading bmp files.
> support single channel 8-bit bmp

- src/libOpenImageIO/imagebufalgo_opencv.cpp
Avoid unnecessary allocation in to_OpenCV 
No, I did not add documentation or a test. 
This is a minor change that does not warrant a CLA.
The [cv::Mat::create](https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html#a55ced2c8d844d683ea9a725c60037ad0) method does the same thing as the constructor but "Allocates new array data if needed." And when not needed, which is my use case when all the images I process are the same size, ``create`` does nothing. This is more efficient than the implementation where a new mat is …
> use dst.create rather than constructor w/move

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
This teaches oiiotool's command line expression substitution (`{...}`)
syntax to understand that
getattribute(name)
should be replaced by the value that OIIO::getattribute(name,...) would
retrieve. The `name` may optionally be single or double quoted, but doesn't
have to be if it's a simple identifier.
Some examples:
oiiotool --echo "{getattribute('oiio:simd')}"
oiiotool --echo "{getattribute(library_list)}"
oiiotool --echo "{getattribute(extension_list)}"
> oiiotool: allow expression substitution to include getattribute(name)

- CMakeLists.txt
Make whether namespace includes the patch number be dependent on
whether it's a dev or release branch. We generally want the patch
in the namespace for master, but not release.
> CMake: Adjust namespace digits

- src/doc/help2man_preformat.py
----
This PR aims to fix a bunch of warnings in Debian Lintian tool about
the usage of the wrong field to define the name of the manual page.
> Rename TITLE to NAME in help2manpages.py script

- .github/workflows/ci.yml
- CHANGES.md
- INSTALL.md
- src/cmake/compiler.cmake
- src/cmake/externalpackages.cmake
- src/include/OpenImageIO/dassert.h
- src/include/OpenImageIO/platform.h
- testsuite/cmake-consumer/CMakeLists.txt
This also bumps compiler minimums to gcc 6.1, clang 3.4, MSVS 2017,
and icc 17 (all because those are the first versions to fully support
C++14).
This has been coming and has been socialized for a long time, with
nobody voicing serious objection. So here it is.
This WILL NOT be backported to release branches. The new minimums only
affect OIIO 2.3 and later.
When last discussed on the oiio-dev mail list, I said I would aim to
introduce this change on May 1. I will not merge this PR earlier than
that, and I will tag a developer preview release before that happens.
> Bump C++ minimum to 14

- src/libtexture/imagecache.cpp
Fixed a crash in ImageCacheFile::read_unmipped when sampling a channel index greater than the number of channels we're sampling (see Description below)
This is a proposed fix for issue #2959 
To give a bit more information: `ImageCacheFile::read_unmipped` crashes when trying to read from a generated mipmap, when its called with a `chbegin` greater than the number of channels we're sampling.
This is because that method creates a temp image buffer with `chend - chbegin` channels only, and then at the end of the method, it will get its pixels by calling its `get_pixels` methods, and by providing a ROI with unchanged `chbegin` and `chend`.
And in the beginning of `ImageBuf::get_pixels` this line result in a crash in our case: `roi.chend = std::min(roi.chend, nchannels());`
Let's say we were …
> fixed a crash in ImageCacheFile::read_unmipped

- .github/workflows/ci.yml
- src/build-scripts/build_opencolorio.bash
- src/include/OpenImageIO/color.h
- src/libOpenImageIO/color_ocio.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_colorconfig.cpp
This started out as just trying to fix our CI on the "bleeding edge"
building against OCIO master and complaining about a recently committed
OCIO deprecation of Config::parseColorSpaceFromString.
But it turned out that the new OCIO v2 method, getColorSpaceFromFilepath,
didn't work quite the same way and broke our tests. So I ended up having
to implement a bit more of a complicated set of functionality:
* Config::parseColorSpaceFromString now wraps the OCIO version if it's
available, but implements the equivalent logic if OCIO is new enough
that the function is deprecated.
* As a bonus, our pCSFS now works (didn't before) in cases where lack of
OCIO support or missing config meant the OCIO functionality wasn't
available. That is, it works on our meager set of default color spaces
that are …
> Adjustment for OpenColorIO 2.1 (in dev) deprecating method

- .clang-format
- .github/workflows/ci.yml
- src/bmp.imageio/bmpinput.cpp
- src/dds.imageio/ddsinput.cpp
- src/heif.imageio/heifinput.cpp
- src/ico.imageio/icooutput.cpp
- src/include/OpenImageIO/image_view.h
- src/jpeg2000.imageio/jpeg2000output.cpp
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/libtexture/texture3d.cpp
- src/libtexture/texturesys.cpp
- src/libutil/strutil.cpp
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/png.imageio/png_pvt.h
- src/pnm.imageio/pnmoutput.cpp
- src/psd.imageio/psdinput.cpp
- src/rla.imageio/rlainput.cpp
- src/rla.imageio/rlaoutput.cpp
- src/targa.imageio/targainput.cpp
- src/targa.imageio/targaoutput.cpp
- src/term.imageio/termoutput.cpp
- src/tiff.imageio/tiffoutput.cpp
This makes several minor formatting changes, mostly related to how
clang-format 11 has improved ability to track the alignment of `=` in
successive statements, even when one of those statements is split
across two lines.
> Update the CI clang-format to use llvm 11 (from 10)

- src/libOpenImageIO/xmp.cpp
- testsuite/psd/ref/out-alt.txt
- testsuite/psd/ref/out.txt
Found some files that encountered the problem described here:
https://prepression.blogspot.com/2017/06/metadata-bloat-photoshopdocumentancestors.html
https://feedback.photoshop.com/conversations/photoshop/photoshop-corrupt-ancestors-tag-in-xmp-causing-giant-file-sizes/5f5f45f74b561a3d426ba97f
The pathologically long lists of "photoshop:DocumentAncestors" tags (a
4MB PNG of which 3MB consisting of XMP) was tripping us up with an
O(n^2) handling of appending to lists for those attributes.
It seems like this was a widely acknowledged problem that has been fixed
in Photoshop 20.0.2 (January 2019) and later.
Solution:
* Just skip the problem tag; I can discern noreal use for preserving
it in any OIIO context.
* More generally, be on the lookout for pathological or corrupt XMP by
keeping track …
> Fix runaway parsing time for pathological XMP metadata

- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- src/bmp.imageio/bmpoutput.cpp
- src/doc/builtinplugins.rst
We would welcome a patch that adds this capability.
> Clarify that our BMP implementation does not support RLE files.

- src/bmp.imageio/bmp_pvt.cpp
- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- src/bmp.imageio/bmpoutput.cpp
This changes no code, it's just a slight reorg, and I wanted the no-code-change movement to be a separate PR than the forthcoming code-change patch so that it's easier to read.
> BMP refactor: move BMPInput and BMPOutput to the files where they are used

- src/cmake/Config.cmake.in
OpenImageIO's exported config has a dependency on Imath/OpenEXR.  For
Imath 3, I accidentally used OpenEXR_VERSION when I should have said
Imath_VERSION. Makes no differece if they're in sync. But should
somebody downstream have a separately compiled Imath and OpenEXR that
just might be different patch versions, it could break builds by
rejecting if the Imath version appears to be behind the OpenEXR
version. There's no guarantee that Imath and OpenEXR will always be
released exactly in sync.
> Fix exported cmake config, it confused imath and openexr versions

- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- src/bmp.imageio/bmpoutput.cpp
- src/doc/builtinplugins.rst
- src/iconvert/iconvert.cpp
- testsuite/bmp/ref/out.txt
- testsuite/bmp/run.py
* Read RLE-compressed images correcty now! Both 4 and 8 bpp varieties.
* Reading: respect a configuration hint "bmp:monochrome_detect" that if
set to 0, will disable the detection of monochrome palettes and spoofing
to look like a single-channel image. The default is 1.
* Writing: Write single channel BMP as 8 bit palette images (not 24/32
bit images). This fixes a problem I discovered related to the recent
change that reads 8 bit palette images as if they were single channel.
The lack of symmetry there made problems for round-tripping an image
and having it end with the same apparent number of channels as it
started with.
* Beef up the testsuite/bmp tests, now test against a wider set of sample
BMP images from bmpsuite (including rle compressed images).
Fixes #2969
> Improvements to BMP

- src/cineon.imageio/libcineon/CineonHeader.cpp
- src/dpx.imageio/libdpx/DPXHeader.cpp
- src/include/OpenImageIO/sysutil.h
- src/rla.imageio/rla_pvt.h
- src/rla.imageio/rlaoutput.cpp
We still had a few stray localtime() calls (which is not reentrant,
because it depends on a global buffer), even though all along we had a
"safe" wrapper in Sysutil::get_local_time, which internally calls safe
versions localtime_r or localtime_s (depending on the OS).
> Change localtime() calls to Sysutil::get_local_time

- src/build-scripts/build_OpenJPEG.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenJPEG.cmake
Rename FindOpenJpeg -> FindOpenJPEG to match the conventions used by
that project, in particular for its exported CMake config files.
(We don't yet rely on their exported configs, I need to do some
homework to see if they exist and are reliable as far back as the
oldest OpenJPEG release that we support.)
> Build: FindOpenJPEG.cmake improvements

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindTBB.cmake
For TBB 2021, headers moved around, and our FindTBB.cmake was failing.
But actually, starting with TBB 2021, TBB exports a proper cmake config!
So take advantage of that by preferring to load TBB from a config file.
Fixes #2963
> Fix broken build against TBB 2021

- src/bmp.imageio/bmpinput.cpp
- src/libOpenImageIO/imageinput.cpp
In ImageInput::read_scanlines and read_image, if somehow the image has
a spec with 0 size, it will lead to a divide by zero error. Check this
and fail safely.
For BMP in particular, do some sanity checks to catch corrupted headers.
Fixes #2982
> Avoid divide-by-0 error computing chunk size for invalid image sizes

- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/color_ocio.cpp
The docs were ambiguous about what would happen for many-channel
images, and the behavor in fact was to copy and color transform only up
to the first 4 channels, leaving additional channels in the
destination undefined (though in practice they turned out black).
Clarify now that for colorconvert, colormatrixtransform, ociolook,
ociodisplay, and ociofiletransform, the first 4 channels are assumed
to be RGBA to undergo the transformation, and any additional channels
will be copied unaltered from source to destination (not set to black).
> Clarify behavior of color conversion on image with > 4 channels

- src/ffmpeg.imageio/ffmpeginput.cpp
A few varieties of encoded videos with bit depth 12 and having alpha
were not marked as such, and falling to the default case that reported
them as 8 bit RGB.
> Fix some ffmpeg encodings that didn't realize they were >8bit, alpha

- src/libutil/ustring.cpp
There's something wrong with the behind the scenes tricks we're using
to doctor the internal string representation. Is it because of big
endian?  The "alternate" string rep? Something else different on
Apple's libc++ on M1?
Fix for now by just disabling that clause. The only harm is that
ustring internals will take more memory on that platform. That's
better than crashing!
When I have more hands-on access to an M1 (or when GitHub Actions
supports running CI tests on M1), I'll return to this for a proper
fix.
Fixes #2858
> Fix ustring crash on M1 (ARM) based Mac.

- src/libOpenImageIO/maketexture.cpp
It's meaningless to try to use make_texture on input images that are
"deep".  We never even thought to check for this, which led to a
cascade of problems resulting in a segfault.
Fixes #2950
> make_texture now detects and rejects deep images

- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
We were double-printing error messages. If maketx/oiiotool is itself
printing errors returned by IBA::make_texture, it is not necessary to
pass std::cout to make_texture so that it can echo the message to the
console itself.
> Fix redundant error message for maketx and oiiotool -otex

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/gh-installdeps.bash
- src/include/OpenImageIO/string_view.h
- src/libOpenImageIO/imagebufalgo_opencv.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/oiiotool/oiiotool.cpp
* Use g++11 on the bleeding edge CI test
* Remove OIIO_CONSTEXPR20 decls from string_view -- gcc 11, even in
C++20 mode, doesn't have std::string fully constexpr plumbed, it's
not ready for this.
* Suppress gcc11 warnings about arithmetic with enums that occur in the
OpenCV headers.
* Suppress gcc11 warning (correct) in the spot where we were trying to
force a crash for testing purposes.
> gcc 11 support

- .github/workflows/ci.yml
- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/simd.h
- src/include/OpenImageIO/typedesc.h
- src/python/py_oiio.h
Also need to back off the top of fmt master when using gcc11, it seems
to have some trouble with.
> Fix to accommodate changed preprocessor name in imath master.

- src/libutil/filesystem.cpp
When using filesystem::directory_iterator, I was using operator++,
which can throw exceptions for OS errors. I should have used
increment(ec) instead. Throw in a surrounding try/catch just in case,
since even increment is not marked as noexcept.
> More exception safety in Filesystem directory iteration

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindLibRaw.cmake
- src/raw.imageio/rawinput.cpp
LibRaw 0.19 and earlier use auto_ptr in public headers, which was
deprecated in C++11 and removed in C++17. 
When this combo is detected, issue a warning message from CMake.
> Clang + C++17 + LibRaw < 0.20 don't mutually get along

- src/include/OpenImageIO/detail/farmhash.h
Try to `#undef` at the end all the things that are `#define` by
farmhash.h that are not namespaced with `FARMHASH_`.
Fixes #3000 from @johnhaddon
> Clean up preprocessor mess left by farmhash.h

- CREDITS.md
- src/doc/texturesys.rst
- src/libtexture/imagecache.cpp
For our in-house renderer, we need support for an additional UDIM format of:
/path/to/file/textureName_u##v##.ext
I also added support for the Houdini UDIM naming convention of:
/path/to/file/textureName%(UDIM)d.ext
Should be clear based on previous discussion I've had with Larry.
But in a nutshell, add missing naming conventions for UDIM files.
Not yet but I will.
- [] I have ensured that the change is tested somewhere in the testsuite
> Add custom UDIM support

- src/cmake/checked_find_package.cmake
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>
I think, there's a typo when setting REQUIRED_DEPS. This patch fixes it.
no
> fix typo for REQUIRED_USE

- .github/workflows/ci.yml
- src/doc/Doxyfile
- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/typedesc.h
* New fmt 8.0.0 is out -- make sure we test against both that and their
current master.
* Starting with fmt 8.0, we need to wrap non-constexpr format spec
strings passed to fmt::format() in a fmt::runtime. A format string
that started out as a string literal nonetheless looks like a
non-constant by the time it gets to std::format via our wrapper
functions. This only triggers the error with gcc11 and -std=c++20,
so it was a little tricky to understand at first.
* Update the idioms we use for Strutil::format and sprintf to use
"perfect forwarding". (Dunno if that makes a practical difference,
but it covers all our bases.)
* For Strutil::sprintf, just `using ::fmt::sprintf` and eliminate the
wrapper entirely. (Though we express the wrapper inside
`#ifdef OIIO_OXYGEN_ONLY` so that it fully …
> fmt related fixes

- src/doc/imageioapi.rst
- src/include/OpenImageIO/typedesc.h
- src/libutil/CMakeLists.txt
- src/libutil/typedesc.cpp
- src/libutil/typedesc_test.cpp
- src/python/py_typedesc.cpp
- testsuite/python-typedesc/ref/out-python2.txt
- testsuite/python-typedesc/src/test_typedesc.py
* Add TypeDesc support for metadata that is a 2D or 3D bounding box,
represented as an array of 2 VEC2 aggregates (for 2d) or VEC3
aggregates (for 3d), having the BOX semantic. The basetype
determines whether it's an integer-based (generally for pixel
ranges) or float-based (generally for 3D spatial) bounds. The new
text representations are "box2" and "box3" (for float-based), and
"box2i" and "box3i" (for int-based).
* Somehow we never had a C++ test thoroughly exercising all the corners
of TypeDesc. Now we do: typedesc_test.cpp
* The test revealed a number of edge cases we don't handle well, now
shored up.
> TypeDesc improvements

- src/doc/builtinplugins.rst
- src/dpx.imageio/dpxoutput.cpp
- src/dpx.imageio/libdpx/DPXStream.h
- src/dpx.imageio/libdpx/OutStream.cpp
- src/libOpenImageIO/imageinout_test.cpp
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>
Converts dpx output (input is already) to use the IO proxy layer (I recently
had a reason to write dpx, but couldn't make a memory stream).
just tested with dpx image tests
> Convert dpx output to be ioproxy enabled

- src/libOpenImageIO/maketexture.cpp
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
- testsuite/maketx/ref/out.txt
- testsuite/oiiotool-maketx/ref/out-rhel7.txt
- testsuite/oiiotool-maketx/ref/out-win.txt
- testsuite/oiiotool-maketx/ref/out.txt
This patch provides an optional parameter `--uvslopes_scale` for the `--bumpslopes` exporter to output the derivatives in the normalized UV space and scale them by a user defined constant. 
Originally, we decided to store the derivatives in texel space rather than the UV space to prevent floating point overflow when using the half float format (67c863d). However, expressing the derivatives in UV space is interesting because it is resolution independent and convenient when the resolution is not accessible. We restore this ability thanks to this optional parameter and a scale factor to prevent the overflow when using the half format. A typical value of 256 is recommended to prevent half floating point overflow with texture resolutions up to 32k. The value is stored as an extra attribute in …
> Add a scaled slopes UV normalization options for --bumpslopes.

- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
ImageInput and ImageOutput have ways for the caller to say that there
should be no "fan-out" in the internals of what the reader or writer
needs to do. But TIFF wasn't honoring this.
> TIFF: honor caller request for single threaded

- src/doc/Doxyfile
- src/include/OpenImageIO/errorhandler.h
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/ustring.h
- src/libutil/strutil_test.cpp
* strutil.h already had a symbol called OIIO_FORMAT_IS_FMT defined to
0 or 1 that reveals (to clients of OIIO) whether Strutil::format()
behaves like printf (the old and current way) or like std::format
(the future way). Now we adjust so that the caller may pre-set the
value to force one implementation or the other, at least for the
"inline" functions of the headers.
* As an aid to downstream packages trying to ensure that they aren't
using the function slated for eventual deprecation or behavior
change, you can now define OIIO_HIDE_FORMAT to cause a deprecation
warning now on those functions that will eventually change or be
deprecated. This can help to identify any places where you call the
future-deprecated functions and change them to a "safe" variety.
> More fmt transition aids

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenCV.cmake
Only for master+, will not be backported to release branches.
> Bump minimum OpenCV supported to >= 3.0

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libutil/spinlock_test.cpp
I don't think issues have been reported, so maybe this wasn't a
problem in practice for reasons I've long forgotten about, but doing
some other work in ImageBuf, I noticed what I think was a thread
safety problem.
ImageBuf reads are done lazily, a lot of operations call
validate_spec() or validate_pixels() which can trigger a call to
init_spec() or read() if they have not yet been done, and those had a
spin mutex protecting them from being called at the same time. But the
underlying read() and init_spec() themselves did not have any lock,
which made me worried about what would happen if one user thread was
explicitly calling read() while another was calling it implicitly
through validate.
Also, spin_lock is probably inappropriate for something that could
trigger an entire image read from …
> Beef up thread safety of ImageBuf init_spec() and read().

- src/targa.imageio/targainput.cpp
- testsuite/targa-tgautils/ref/out.txt
There are several alpha choices. We were assuming that color values
were unassociated (need to be premultiplied) unless it was marked as
premultiplied alpha. But it seems that, actually, we should only
premultiply if it's "useful alpha". [Indeed, their terminology is
the worst.]
Rename the m_alpha member to m_alpha_type to clarifywhat it holds.
Also add the alpha type to the metadata as "tga:alpha_type" to make it
easier to inspect the value in tga files.
> Targa: fix alpha handling

- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/color_test.cpp
Currently, it only tests the linear <-> sRGB and linear <-> Rec709
transformations.
This was meant to uncover the issue in #2929, but it passes CI tests
on Windows, so maybe it was a MSVS compiler bug that has since 
been fixed?
> Make a unit test for color.h contents

- .github/workflows/ci.yml
- src/openexr.imageio/CMakeLists.txt
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- src/openexr.imageio/exroutput.cpp
- testsuite/missingcolor/ref/out.err-openexrcore.txt
- testsuite/oiiotool-readerror/ref/out.err-opencore.err.txt
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>
Experimental only version of use of the C layer for reading images, to be used for evaluating the new API, and testing improved thread behavior when higher level application (i.e. renderer) has it's own pile of threads hammering away at textures.
At this point, just smoke test that iv can load a couple of images.
> [WIP] Experimental use of openexr C layer in openimageio

- src/doc/Doxyfile
- src/doc/imagebuf.rst
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/strutil.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
Internally, ImageBuf has for some time now supported strided or
non-contiguous buffers (for IBs that reside in memory, rather than in
an ImageCache). It was originally anticipated to accommodate cases
where we would want pixels or scanlines to have particular alignment
or spacing, such as to be even multiples of the SIMD width.
But we never allowed the kind of IB that "wraps" an application's
memory buffer to specify the strides, in case the app buffer was in
some layout that was not contiguous. This patch adds that ability, by
amending that constructor with stride values (which are optional and
default to AutoStride, which indicates that contiguity should be
assumed). This is 100% back compatible for source code.
This lets you do some cool things with in-memory buffers:
* More flexible …
> ImageBuf: Expose strides to ctr from wrapped buffer

- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/imagebufalgo_draw.cpp
Allow multiple lines of text to be specified per call, as long as you
don't mind single spacing.
> IBA::render_text and `oiiotool --text` honor linefeed chars

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/oiiotool/printinfo.cpp
- testsuite/oiiotool/ref/out.txt
- testsuite/oiiotool/run.py
- testsuite/openexr-v2/ref/out.txt
The existing semantics of `oiiotool -info`, `-info -v` and `-stats`
are that these options set flags so that each time a file is opened
for the first time, it will print the metadata and/or stats. But these
do not allow you to create new images and print their metadata or stats
(at least, not without writing to disk and reading those files).
This patch extends the expression substition syntax to recognize the
following new metadata notations:
* `METABRIEF` : a string containing the brief one-line description that
would be printed with `oiiotool -info`.
* `META` : a multi-line string containing the full metadata that would
be printed with `oiiotool -info -v`.
* `STATS` : a multi-line string containing the image statistics that would
be printed with `oiiotool -stats`.
Some interesting use …
> Allow oiiotool to print metadata of computed images

- src/doc/maketx.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/maketexture.cpp
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
Slightly amends PR 3012
* Add docs for this recently-added feature.
* Change the make_texture configuration hint to "maketx:uvslopes_scale"
for symmetry with all the other texture conversion configuration names.
Everything works as before, including setting "uvslopes_scale"
metadata in the file.  (But still accept the name without the
prefix as a synonym.)
* Change it to a float for a bit more flexibility.
> Document and minor changes to uvslopes_scale argument to bumpslopes

- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool/ref/out.txt
- testsuite/oiiotool/run.py
It's never been pretty or useful, we removed it from the docs long ago. Let's finally axe it.
> oiiotool: Get rid of long-deprecated, useless --histogram function

- src/cmake/externalpackages.cmake
Addresses #2956. Apologies for the long radio silence on this, I've been quite busy lately...
This patch modifies the build system to make it possible to control
whether OIIO should link Boost in the form of static or dynamic
libraries, independently from the LINKSTATIC setting, without
having to use the fully custom route (BOOST_CUSTOM).
This is done by preserving the value of the Boost_USE_STATIC_LIBS
variable, if it has been defined by the user. If the value
of Boost_USE_STATIC_LIBS has NOT been explicitly defined, it is
set to match the value of the LINKSTATIC variable, which should
result in Boost being linked in the same way as other dependencies.
The existing CI workflows should (hopefully) be able to detect any anomalies in the common build scenarios.
To test this specific …
> Make finding Boost more flexible.

- src/doc/imagebufalgo.rst
- src/idiff/idiff.cpp
- src/iinfo/iinfo.cpp
- src/include/OpenImageIO/color.h
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/simd.h
- src/include/OpenImageIO/texture.h
- src/include/OpenImageIO/tiffutils.h
- src/include/OpenImageIO/typedesc.h
- src/iv/imageviewer.cpp
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imagebufalgo_yee.cpp
- src/libOpenImageIO/imageinout_test.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libOpenImageIO/maketexture.cpp
- src/oiiotool/diff.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/printinfo.cpp
- src/python/py_imagebufalgo.cpp
And make sure to switch all of our internal uses of those to the
preferred new equivalents!
Also, hide some deprecated things from the documentation system so that
new people won't be tempted to use them.
These are all things that have been deprecated starting with OIIO 2.0
(or in some cases, even earlier). Multiple releases (2.0, 2.1, 2.2)
have gone by with them commented or documented as deprecated, but
without our adding the warnings. It's about time. We're still not
taking them away entirely, I usually don't do that until we've had at
least one release where it's been marked as OIIO_DEPRECATED, and also
only do true removals of API at major releases. But we're laying the
groundwork for being able to totally remove these when we eventually
have a 3.0 release.
> Mark some long-deprecated things with OIIO_DEPRECATED

- src/include/OpenImageIO/imagecache.h
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
Most of the rest of the IC methods that take a filename, also have
a version that takes a handle.
Closes #3034
> ImageCache: add a variety of invalidate() that takes an ImageHandle*

- .github/workflows/ci.yml
- INSTALL.md
OpenEXR -> 3.1.0
pybind11 -> 2.7.0
OCIO -> 2.0.1
> CI: update "latest" releases we test against, notably OpenEXR 3.1

- src/doc/imageioapi.rst
- src/libOpenImageIO/imageio.cpp
- src/libutil/thread.cpp
OpenCue-launched apps are encouraged to honor the setting of
CUE_THREADS to limit the number of threads they use. This change makes
oiiotool a better citizen when run as part of an OpenCue job.
CUE_THREADS has lower precedence than the more OIIO-specific
`OPENIMAGEIO_THREADS`.
For ordinary command line usage, this should not change behavior, since
you wouldn't expect CUE_THREADS to be set.
(Also fix docs which incorrectly named `OPENIMAGEIO_TEXTURE_OPTIONS`.)
> Let CUE_THREADS help determine default number of threads for OIIO

- src/include/OpenImageIO/sysutil.h
- src/libutil/sysutil.cpp
I realized that 3037 breaks ABI compat, so restore the 1-argument
version of Sysutil::getenv. This makes it backportable.
> Augment PR 3037 to make it not break ABI compat

- src/libOpenImageIO/imageio_pvt.h.in
- src/libOpenImageIO/imageioplugin.cpp
- src/libtexture/imagecache.cpp
Imagecache repeatedly has to determine whether a filename is a type
of file that's "procedural" and does it expensively -- every time, it
creates the type of ImageInput in question just to ask it if it
supports("procedural").
We can ask this of each plugin type once, when we first register it.
Then just look it up when we need it.
This is strictly internal, has nothing to do with public APIs.
> Streamline determination of whether file type is procedural.

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- src/openexr.imageio/exroutput.cpp
- testsuite/openexr-v2/ref/out.txt
Some of the OpenEXR sample files had an attribute "version".
All along, I assumed this was telling me the version of the OpenEXR file
itself, so I was passing it along and also renaming "openexr:version".
Turns out I was wrong! This is just arbitrary metadata. Who knows why
it's in some of these files? Maybe nobody. But it's not meant to indicate
the file format version, and indeed it does not correctly reflect it.
In fact, there is no simple API call in the OpenEXR API that tells you
the file format version, you have to infer it from the features
present (multi-part or deep or long attribute name indicate changes
that came along with OpenEXR 2.x, but there is no version number in
the file per se).
So I'm just going to stop doing this rename, let "version" be "version",
it's just some …
> exr read: don't rename "version" attribute to "openexr:version"

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Added this handy function that figures out if the first string contains
any character present in the second string.
Also rewrite the comments describing parse_until and parse_while for
better clarity and correctness.
> Strutil::contains_any_char()

- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagecache.h
- src/iv/imageviewer.cpp
- src/iv/ivimage.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/maketx/maketx.cpp
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/testtex/testtex.cpp
I noticed when working on an ImageCache thing that even the smallest
change to imagecache.h was causing a substantial amount of the
codebase to needlessly recompile even though very few places really
need to use the IC APIs directly.
It took a little bit of juggling of some declarations, but this patch
allows imagebuf.h to be able to treat ImageCache and ImageCacheTile as
opaque, forward-declared types, without the need for every file that
needs imagebuf.h to also have to parse imagecache.h and everything it
might pull in.
This speeds up my development cycle substantially in many cases, and
it also speeds up compilation of user code (by a small amount) by
avoiding parsing of imagecache.h in circumstances where the user code
only needed to know about ImageBuf but not ImageCache.
There's a …
> imagebuf.h: remove inclusion of imagecache.h

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
Sometimes we use a filename, or pieces of it, as a regex.
But filenames can have characters that are interpreted differently when
part of a regex pattern (like `.`, which in a filename is literal, but
in a regex means to match any character!).
So this handy utility inserts the right backslashes so the filename will
end up as a literal match when part of a regex.
Furthermore, there's an optional parameter `simple_glob`, which when
true, will also substitute `?` with `.?` and `*` with `.*`.
We then use this to fix a latent bug in scan_for_matching_filenames():
it could have incorrectly matched files during the search.
> Filesystem::filename_to_regex

- .github/workflows/ci.yml
- src/build-scripts/build_opencolorio.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenColorIO.cmake
- src/libOpenImageIO/CMakeLists.txt
For the upcoming OCIO 2.1, the library names will incorporate the
major/minor version numbers, so our Find module needs to take that into
consideration.
Work towards eventually using OCIO exported configs (though still not
100% working now, may need fixes on their end).
Change CI to use the OCIO's that come in the aswf containers instead
of building from scratch in many cases.
Fixes #3048
> Updates to handling OpenColorIO library naming

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/testtex/testtex.cpp
- testsuite/texture-udim/ref/out-batched.txt
- testsuite/texture-udim/ref/out.txt
- testsuite/texture-udim/run.py
The primary issue being addressed here was that get_texture_info() on a
udim pattern filename (like `"foo_<UDIM>.exr"`) was unable to retrieve
info, except for an extremely narrow range of queries, because of course,
different UDIM "tiles" might have different attributes or be missing.
So in consultation with Lee Kerley, we decided that get_texture_info should
work as follows:
* If the attribute exists and has the same value for all of the
matching UDIM file files, then succeed and return the value.
* If any of the tile files does not contain the attribute, or if the
attribute doesn't have the same value in all found files, then it's
a failure and the value cannot be retrieved.
This necessitated a more rebust accounting of all the tile files
comprising a UDIM pattern, by doing a full …
> Udim improvements

- src/webp.imageio/webpinput.cpp
This request changes the type of `WebpInput::m_decoded_image` from `std::unique_ptr<uint8_t>` to `std::unique_ptr<uint8_t[]>` which ensures `operator delete[]` is called as the variable is initialized with a `operator new uint8_t[]` expression in `WebpInput::open()`.. This mismatched new/delete pair was causing errors when compiling programs with ASAN enabled.
When ASAN was enabled the webp portion of imageinout_test was triggering the sanitizer. After this change the test completes successfully.
> WebpInput: Fixed mismatched new[] and delete

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
* At the suggestion of Luke Emrose, add rcontains() and ircontains(),
which are like contains/icontains, but start the search at the end
of the string rather than the beginning. This is measurably faster
than contains() for the case when you are reasonably certain that if
the search pattern is found at all, it is highly likely to be close
to the end of the string. (They're approximately the same speed when
the pattern is not found.)
* To verify this, I added a bunch of benchmarking to strutil_test.
* The benchmarks also revealed that contains was about 2x slower than
calling find! It should be the same. I don't know what the underlying
boost::algorithm::contains is doing differently than find, but whatever.
Changing our implementation of Strutil::contains to simply call find
doubles its …
> Strutil: Add rcontains, ircontains, improve contains, docs

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/oiiotool/printinfo.cpp
- testsuite/maketx/run.py
- testsuite/oiiotool-maketx/run.py
- testsuite/oiiotool/ref/out.txt
- testsuite/oiiotool/run.py
The existing --info and --stats seem a little confusing and
inflexible.  Unlike the majority of oiiotool arguments which are
evaluated in order, these merely set flags which apply to the entire
oiiotool command (specifically, they cause all image inputs to print
the metadata or image statistics at the time that the input are read
from disk).  There isn't a way to make it apply to a single image, nor
to print the metadata or stats of any *computed* image, leading some
people to awkwardly save a computed image and re-read it merely to
print information about it.
So in this patch, we add new commands
* `--printinfo` which is like `-info -v` but is done immediately for
the "current" image on the top of the stack (even if it's a computed
image and does not correspond to any disk file).
* …
> New oiiotool commands: --printinfo, --printstats

- src/build-scripts/build_OpenJPEG.bash
- src/build-scripts/build_gif.bash
- src/build-scripts/build_libjpeg-turbo.bash
- src/build-scripts/build_libpng.bash
- src/build-scripts/build_libraw.bash
- src/build-scripts/build_libtiff.bash
- src/build-scripts/build_pugixml.bash
- src/build-scripts/build_pybind11.bash
- src/build-scripts/build_webp.bash
- src/build-scripts/build_zlib.bash
For building the Rust bindings we need to provide crates.io with a complete source tree that does not depend on external downloads. So during the process of generating the bindings we want to download all the dependencies, then when building the crate we do no further network communication and jsut build the already downloaded dependencies.
To do this I've added support for two environment variables to the relevant build scripts: OIIO_DEP_BUILD_ONLY and OIIO_DEP_DOWNLOAD_ONLY that do what you would expect.
N/A
> add flags to control stages of dependency build

- src/doc/builtinplugins.rst
- src/raw.imageio/rawinput.cpp
- testsuite/raw/ref/out-libraw-0.20.2-gh.txt
- testsuite/raw/ref/out-libraw-0.20.2.txt
- testsuite/raw/ref/out-libraw0.18.11.txt
- testsuite/raw/ref/out-libraw0.18.8-gh.txt
- testsuite/raw/ref/out-libraw0.18.8-gh2.txt
- testsuite/raw/ref/out-libraw0.19.5-gh.txt
- testsuite/raw/ref/out-libraw0.20.0-gh.txt
- testsuite/raw/ref/out-libraw0.20.0.txt
- testsuite/raw/ref/out-libraw0.21.0-gh.txt
- testsuite/raw/ref/out-libraw0.21.0-mac.txt
- testsuite/raw/ref/out.txt
This PR introduces a number of fixes/updates for the RAW plugin.
1. It fixes the output when raw:Demosaic is set to "none". Previously pixel output was indexed incorrectly into the raw buffer and did not take into account rotation or possible "junk" pixels.
2. Implements raw:balance_clamped mode that will apply a per-channel clamp on all pixel values that are over the saturation level of the sensor. This eliminates issues where clipped highlights take on an unwanted hue shift. This is especially useful when stacking HDRI exposures.
3. Implements raw:apply_scene_linear_scale and raw:camera_to_scene_linear_scale, which allows users to scale libraw output to expected levels. The default scale factors are currently hard coded, but experimentally these settings have proven "good enough" over …
> RAW plugin improvements

- .github/workflows/ci.yml
- src/libutil/timer_test.cpp
* On Windows, increase number of tries for tests that timeout.
* On all CI runs, allow timer_test to be less accurate.
> Try to decrease spurious CI failures

- src/cmake/checked_find_package.cmake
* New SETVARIABLES option sets named cmake variabes to true if the
package is found.
* DEBUG should print variables even if not found. Duh, failing to find
the package is the most important debugging situation.
> cmake: checked_find_package enhancements

- src/cmake/modules/FindOpenCV.cmake
- src/cmake/modules/FindTBB.cmake
- src/cmake/testing.cmake
This PR implements minor build fixes for Windows:
- *OpenCV* when built on Windows produces libraries with versions, e.g. `opencv_core453.lib`. This addresses #1707.
- Pulling [openexr-images](https://github.com/AcademySoftwareFoudation/openexr-images) does not work because of a typo in the URL.
I have experienced quite some troubles building with various dependencies that I ended up deactivating. I will open a separate issue for that.
N/A
> PR: Minor Windows Build Fixes

- testsuite/runtest.py
Fixes python error about OIIO_TESTSUITE_ROOT not defined in the case
where the testsuite dir wasn't found in the standard places. This can
happen if you put the build directory in an unusual location that's
not right in the main project area.
> Testsuite: fix use of OIIO_TESTSUITE_ROOT

- testsuite/missingcolor/ref/out.err-openexrcore.txt
- testsuite/missingcolor/ref/out.err.txt
- testsuite/oiiotool-readerror/ref/out.err-alt.txt
- testsuite/oiiotool-readerror/ref/out.err-alt2.txt
- testsuite/oiiotool-readerror/ref/out.err-debug.txt
- testsuite/oiiotool-readerror/ref/out.err-openexrcore.txt
- testsuite/oiiotool-readerror/ref/out.err.txt
- testsuite/openexr-damaged/ref/out-exr2.2-alt.txt
- testsuite/openexr-damaged/ref/out-exr2.2-travis.txt
- testsuite/openexr-damaged/ref/out-exr2.2.txt
- testsuite/openexr-damaged/ref/out-exr2.3.txt
- testsuite/openexr-damaged/ref/out-exr2.4-clang-noptex.txt
- testsuite/openexr-damaged/ref/out-exr2.4-clang-ptex.txt
- testsuite/openexr-damaged/ref/out-exr2.4-noptex-spi.txt
- testsuite/openexr-damaged/ref/out-exr2.4-noptex.txt
- testsuite/openexr-damaged/ref/out-exr2.5-clang-ptex.txt
- testsuite/openexr-damaged/ref/out-exr2.5.txt
- testsuite/openexr-damaged/ref/out-exr3.0-clang-ptex.txt
- testsuite/openexr-damaged/ref/out-exr3.0.txt
- testsuite/runtest.py
To help make testsuite pass even with nonstandard relative path to the
build area, slightly change how we reference the OCIO config that is
in the testsuite.
> More testsuite cleanup for arbitrary build directory

- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imagespec_test.cpp
Added missing de-serialization of extra_attribs from XML
Added a test to imagespec_test
> formatspec: Implemented deserialization of extra_attribs from XML

- src/build-scripts/build_OpenJPEG.bash
- src/build-scripts/build_gif.bash
- src/build-scripts/build_libjpeg-turbo.bash
- src/build-scripts/build_libpng.bash
- src/build-scripts/build_libraw.bash
- src/build-scripts/build_libtiff.bash
- src/build-scripts/build_pugixml.bash
- src/build-scripts/build_pybind11.bash
- src/build-scripts/build_webp.bash
- src/build-scripts/build_zlib.bash
I realized after #3058 was merged that I often share and copy a lot of
these little dependency build scripts across multiple projects, so I
wanted to remove the OIIO-specific naming.
> Build scripts: rename OIIO_DEP_DOWNLOAD_ONLY to DEP_DOWNLOAD_ONLY

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
Before doing all the work of copying the image, first see if the
`--ch` is actually specifying any change versus the image as it
stands. If not, skip all the copying and just stick to the image we
have.
The main benefit here is if you have a --ch primarily for "conformance",
e.g. you want to reduce to a known subset of channels and remove any
extra that may be unanticipated in the input, but it's possible that
the input will come to you already with only the desired channels. As
an example,
oiiotool in.exr --ch R,G,B ...more ops... -o out.exr
Previously, if in.exr aleady had channels R,G,B (and no other), there
would be some unneceessary expense of creating (in memory) a new image
for the output of --ch copying data to fill it in. With this patch,
the --ch would very nearly turn into a …
> oiiotool --ch : reduce expense for no-op

- CMakeLists.txt
- Makefile
Use a cmake idiom so that you need an explicit `-DCMAKE_INSTALL_PREFIX=`
in order to write over /usr/local or any potentially sensitive area.
In the absence of this being set explicitly, it will configure the
cmake build so that an "install" ends up in ./dist (which is what the
Makefile wrapper did all along).
> Build: Be careful about default installation directory

- src/include/OpenImageIO/timer.h
- src/libutil/timer.cpp
- src/libutil/timer_test.cpp
Add methods to the Timer class that allows you to add (or subtract, if
negtive) to the total elapsed value of a timer.
> Timer::add_seconds, add_ticks

- src/oiiotool/diff.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
oiiotool --runstats tries to report how much time was taken by each
operation.  But it has always had a major flaw: Because we try to read
input files lazily and use ImageCache underneath, only in certain
circumstances do the true cost of reading the files show up in the
entry for "-i"; often the cost gets wrongly credited to the other
command (like --add or -o) whose operations triggered the I/O.
This patch addresses the problem, and I think correctly credits I/O
time where it belongs.
The workhorse here is a new helper class within oiiotool,
OTScopedTimer, which does some tricks to try to account for both
direct read time and ImageCache I/O time, subtracting those from the
op it was instructed to time and instead adding it to the counter for
"-i".  Because the destructor apportions time …
> oiiotool: Overhaul operations timing

- .github/workflows/ci.yml
- src/build-scripts/build_pybind11.bash
- src/build-scripts/gh-installdeps.bash
- src/python/py_imagebufalgo.cpp
* CI test against ASWF's latest VFXPlatform-2022 docker container,
including Python 3.9.
* Pesky crash resulted in testsuite/python-imagebufalgo, laboriously
traced to IBA_color_range_check releasing the GIL too liberally. The
scoped release cannot contain the tuple construction!
* Audited the rest of py_imagebufalgo.cpp and found the same mistake in
only one other place: IBA_histogram. Was asymptomatic so far, but fixed
now.
* Presumably we just got lucky and these bugs were never symptomatic
until we started building against Python 3.9.
* Noticed that the recent change in build tree layout where we now
copy the test images into the build/testsuite area, resulted in HUGE
GHA build artifacts for failed tests. Modify ci.yml use of
upload-artifact action to exclude those directories.
> CI test for VP2022, fix revealed python binding bugs

- src/doc/builtinplugins.rst
- src/tiff.imageio/tiffoutput.cpp
Add support for the IOProxy functionnality to tiffoutput. 
I just did the same pretty much as what was done in tiffinput
Please review or ignore - I don't have much time to make more changes on this
DIdn't add a test
> tiffoutput: support ioproxy

- src/tiff.imageio/tiffoutput.cpp
Calling close() in open will forget too much state. All we want to do
here is make sure the TIFF file itself is closed at that point (so it
can be re-opened in append mode to add a subsequent subimage).
> Additional TIFF IOProxy bug fix -- we don't want a full init inside open

- THIRD-PARTY.md
- src/libOpenImageIO/color_ocio.cpp
- testsuite/common/OpenColorIO/ocio-v2_demo.ocio
- testsuite/oiiotool-color/ref/out.txt
- testsuite/oiiotool-color/run.py
When OIIO that was built against OCIO 1.x, but encounters an OCIO 2.x
config file, OCIO could throw an exception that was not caught by
OIIO.  The problem was the call to OCIO::GetCurrentConfig(), it should
have been inside the try/catch block.
> OCIO: better catching of exceptions.

- .github/workflows/ci.yml
We weren't using a recognized notation, and so our artifacts were
including huge files unintentionally.
> CI: Adjust how we specify what to exclude from failure artifacts

- src/include/OpenImageIO/color.h
- src/libOpenImageIO/color_ocio.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool-color/ref/out-ocio1.1.0.txt
- testsuite/oiiotool-color/ref/out-ocio1.1.0b.txt
- testsuite/oiiotool-color/run.py
- testsuite/runtest.py
Add tests to be sure we have reasonable error reporting for at least
two important cases: a specified OCIO config file is not found at all,
and an OCIO config is present but cannot be read (in particular, if
the config is newer than the library). Because the exact error spewage
is different for each OCIO version, and apparently also depending on
the exact version of the yaml library that OCIO used, we have a few
different possible output references.
> Rewrite ColorConfig::reset for clearer logic and better err handling

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
This is a very low priority change, but every little bit helps when it
comes to limiting boost's footprint as thing we used to require it for
become available in the standard library.
> When possible (>= C++17) use std::gcd instead of boost

- src/libOpenImageIO/imagebuf.cpp
When it comes time to read_image() into the ImageBuf's internal
memory, we should have said to convert to `m_spec.format`, which
describes the buffer we allocated. Instead, we asked for `convert`,
which is the user request, which at that time can still be UNKNOWN,
which indicates to preserve the file's data format, which in fact does
not necessarily match the internal buffer.
This becomes especially troublesome for images with mixed per-channel
data types, which will obviously never match the internal buffer since
ImageBuf only internally stores one data format for all channels.
Fixes #2691
> Fix ImageBuf::read bug for images of mixed per-channel data types

- src/cmake/Config.cmake.in
- src/cmake/externalpackages.cmake
- src/libOpenImageIO/color_ocio.cpp
When $OCIO was not set at all, the call to OCIO::GetCurrentConfig()
was checking it again and writing the info message that none was found
to stdout, which we really don't want.  And as Patrick pointed out
recently, asking for the "current" config is suspect, since who knows
exatly what the app has done.
So we're making the following executive decision: At least from OIIO's
viewpoint, if you want an OCIO color config, you either have to name it
expliticly, or have it determined by the `$OCIO` env variable. That makes
cleaner logic, and also rids us of the info messages.
I also now have the exported cmake config set
`OpenImageIO_HAS_OpenColorIO`. This makes it easier for downstream
consumers of our exported OpenImageIOConfig.cmake to know if the OIIO
build they have found has build-in …
> Adjust logic of getting OCIO config

- .github/workflows/ci.yml
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/openexr.imageio/CMakeLists.txt
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
Instead of a build-time option for enabling (and always using) the
experimental OpenEXR "core" library...
* Build support for it by default any time we're using a new enough
OpenEXR version (>= 3.1). You can still hard-disable it being compiled
in at all with `-DOIIO_USE_EXR_C_API=OFF`.
* Select whether it's actually used with the global OIIO attribute
"openexr:core" (default to 0, disabled, for now).
This easily lets an app select support at runtime, and also may be
selected by user with environment variable
`OPENIMAGEIO_OPTIONS="openexr:core=1".
This all is intended to make it easier to benchmark use of this new
feature, switching back and forth without a rebuild.
> Always have OpenEXRCore C library on tap -- with option

- src/libutil/strutil_test.cpp
I had a hunch about a problem. Was wrong, this function worked correctly
all along. But I'm keeping the beefed-up test.
> strutil_test: add a test of split when the separator is not found

- src/build-scripts/build_webp.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindLibsquish.cmake
- src/dds.imageio/CMakeLists.txt
- src/field3d.imageio/CMakeLists.txt
- src/heif.imageio/CMakeLists.txt
- src/openvdb.imageio/CMakeLists.txt
- src/webp.imageio/CMakeLists.txt
Background: Old style CMake was to use FindFoo.cmake modules, which
set FOO_INCLUDES and FOO_LIBRARIES variables. Best new cmake practices
are for the upstream packages themselves to export a FooConfig.cmake
and friends, which set up cmake targets. Of course, many packages don't
provide exported configs, so we use the old Find modules for many of
our dependencies.
I've slowly been migrating our Find modules to set up targets in addition
to the variables, and favoring use of the targets over the variables.
But I was wrong about this. It's more than just a choice of style.
When targets are used, use of transitive linkage (especially for static
library versions of dependencies) make the dependency targets show up in
our own exported OpenImageIOConfig.cmake. But to a downstream package,
now …
> Build: fix over-eager use of targets

- src/cmake/fancy_add_executable.cmake
- src/testtex/CMakeLists.txt
If set to ON, will include the testtex program in the install.
The default is OFF, which builds it for tests, but doesn't install it
with the real command line utilities.
> Build: Add ENABLE_INSTALL_testtex option

- src/libOpenImageIO/color_ocio.cpp
Make sure OCIO isn't spraying info messages at the console when we
first ask for a config.
> Suppress OCIO console info output

- .github/workflows/ci.yml
- src/openexr.imageio/exrinput_c.cpp
- testsuite/missingcolor/ref/out.err-openexrcore.txt
- testsuite/oiiotool-readerror/ref/out.err-openexrcore.txt
The old libOpenEXR/libIlmImf (default) implementation handled
multithreading on the exr side of things, inside the readPixels method.
The new (experimental, enabled only by option) OpenEXRCore
implementation leaves the threading to the caller, and we weren't
doing it, so the performance was unsurprisingly awful.
This patch turns the implementations of the exrcore-based
read_native_scanlines and read_native_tiles (and also the deep
versions thereof) to use parallel-for loops, restoring parallel
processing to the exr reader when using OpenEXRCore.
Reading of whole scanline and tiled images now is on par or slightly
faster (a few %) than when using the main OpenEXR library. Reading of whole
scanline and tiled *deep* images is substantially faster (2-3x!) than
before.
I did some extra …
> Add multithreading to exr core read_scanlines and read_tiles

- src/doc/builtinplugins.rst
- src/tiff.imageio/tiffoutput.cpp
We were already passing this on to libtiff when it handles the
compression.  But for the case where we were calling zlib ourselves
(to facilitate multi-thread compression, which libtiff doesn't do),
we were just using the default compression.
This is inspired by a great [blog post](https://aras-p.info/blog/2021/08/05/EXR-Zip-compression-levels/)
by Aras Pranckevičius in which he made a similar change to OpenEXR
and benchmarked the results. He reported approximately a slightly more
than 2x write speed increase, while getting files that were only around
2% larger.
I tried replicating his experiment for TIFF, and while I don't quite
get results as good as he did, it still is really interesting.  I
tested with 100 images randomly selected from the [Animal Logic Lab
USD …
> TIFF output: Honor zip quality request when we do our own compression

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
Oiiotool::extract_options was kind of fishy and brittle before --
splitting the string at ':' characters, then split each piece (which
should form a `name=value` pattern) at the first '=' character. There
are probably many malformed option strings that would have had weird
results with the prior naive parsing method. And it has been noted
that it can't handle a value that is intended to be a Windows filename
(like "C:/foo"), nor a searchpath (like "/usr/bin:/usr/local/bin").
Rewrite to parse it more carefully as name=value pairs delimited by
':'. In the process, we now have the ability to have the value be
enclosed by a single or double quoted string, in which case the
contents of the quote may themselves contain a colon, for example, the
following command and modifier is now no longer a …
> Allow quotes in oiiotool command modifiers

- src/libtexture/imagecache.cpp
If think that our inventory of UDIM tile files won't find names with
wildly out-of-range tile indices, you haven't been working in a
production studio! When those indices imply tile numbers < 0, we were
running off the beginning of the vector when filling in the udim
table, to hilarious results.
> Guard against invalid UDIM tile numbering

- src/doc/Doxyfile
- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/texture.h
- src/include/OpenImageIO/typedesc.h
- src/libOpenImageIO/formatspec.cpp
Owing to our C++11 focus in previous years, we had a number of places
were constants were declared as `static constexpr`. When done in
headers, this potentially causes separate copies of those constants to
be instantiated in each module that includes the header. It's not
really harmful the way we're using it for small constand objects, but
it's wasteful to potentially have dozens of copies of each those
constants by having it repeated in each module.
C++17 has a new idiom, `inline constexpr` that is more like we want --
makes it a true compiler constant that doesn't get instantiated in the
memory of each module.
We still have to cater to C++14, and in platform.h we already had a
C++-standard-dependent definition of OIIO_INLINE_CONSTEXPR that was
almost correct. Fix it (it wasn't …
> Use `inline constexpr` for C++17

- src/build-scripts/gh-win-installdeps.bash
- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
One more boost extraction:  tokenizer.
The only place we used it is Filesystem::searchpath_split, which can
easily be rewritten in terms of the Strutil parsing functions.
While I'm at it, add a new version that returns the vector instead
of needing to pass in a ref.
> Rewrite Filesystem::searchpath_split to remove boost::tokenizer

- .github/workflows/ci.yml
- src/doc/builtinplugins.rst
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
When building against OpenEXR >= 3.1.3, exr output now allows zip/zips
compression to take a quality metric (such as compression
"zip:4"). The range is from 1-9, 4 is the default, and it's a control
over speed of compression vs compression ratio (higher number is more
expensive but may result in smaller files). This only affects
compressed output -- it's lossless and will be read to the same pixel
values upon input.
This is also incentive to upgrade to OpenEXR >= 3.1.3, because its new
default (and ours) is 4, versus the old (implied, not directly
controlled) 6. This change was made because compared to 6, it's
significantly faster to write exr files with zip compression 4 (tens
of % faster), while only increasing file size by 1-2%, so that seemed
like the right tradeoff. Lower numbers …
> exr output: Support new OpenEXR zip compression level choices

- src/build-scripts/build_libtiff.bash
Also make the default version of libtiff we build be the current 4.3
> build_libtiff.bash: Allow override of build type

- src/python/py_oiio.cpp
While working on OCIO unit tests for Windows I noticed a familiar error with the use of raw `ssize_t` type, which appear to not always be guaranteed to exists on MSVC. This just use the actual `py::ssize_t` type defined in pybind11. Note for now, I'll just disable python bindings on our CI builds as we don't really use them anyway.
Error here: https://github.com/remia/OpenColorIO/runs/4090745925?check_suite_focus=true#step:6:3531
> Fix ssize_t build issue on Windows

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
This new oiiotool command lets you set global OIIO attributes, i.e.,
making calls to OIIO::attribute(). It allows oiiotool command lines to
set some additional OIIO-wide options for which no specific oiiotool
command flags could otherwise access.
> oiiotool --oiioattrib

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/libOpenImageIO/imageioplugin.cpp
When ImageInput::create() or open() is called, it first uses the
extension of the filename to guess which reader plugin to try (for
example, "foo.jpg" will try the jpeg reader). If that fails, however,
the default behavior is to then try EVERY reader to see if any will
open the file, in case it guessed wrong, or the extension is used by
more than one format, or the file was simply given the wrong
name. Thus, ultimately, OIIO will never fail to open a valid image
file in a known format, even if the file is wildly misnamed. However,
it's a lot faster to open a correctly named file, because it will try
that one first, before trying a long succession of readers in the hope
that eventually one will work.
There are three cases where this is not the desired behavior:
1. You are confident that …
> New global OIIO attribute: "try_all_readers"

- src/doc/builtinplugins.rst
- src/tiff.imageio/tiffoutput.cpp
TIFF has an absolute limit of 4GB file size due to use of uint32
offsets within the file. If you try to write a big enough TIFF image,
it will fail. This is not a software problem, it's a limitation of the
original TIFF file specification itself.
The underlying libtiff supports a nonstandard "bigtiff" extension that
uses 64 bit offsets. This patch switches to this automatically for
images whose uncompressed size would get too close to (or exceed) the
4GB limit.  Any such files can be read by OIIO-based software, as well
as anything else using a relatively modern version of libtiff, but may
not be readable by independent TIFF reading implementations.
This is a mixed bag, though. On one hand, this at least lets us write
files that would have been an error before.  But note that some files …
> tiff output: switch to "bigtiff" for really big images

- src/oiiotool/oiiotool.cpp
When outputting to formats that don't support negative pixel origins
(such as JPEG), we crop away the negative areas. But we did not
consider the case where the entire data window was in the negative
region!
> oiiotool: Fix bug autocropping to positive area for all-negative data

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
* `parse_values()` and `scan_values()` both can parse a series of
values in a string, with optional prefix, suffix, and separator. The
scan versions just figure out the values, the parse versions
optionally can update a string_view& like the other parsing
functions in Strutil.
* `scan_datetime` parses the int components of a string that looks like
"YYYY:MM:DD hh:mm:ss" (and a few minor variants).
* Fix stoui -- it was previously casting stoi results, which is not
correct.
* Add `from_string<>` specialties for `double`, `int64_t`, `uint64_t`.
> Strutil: add new utilities for parsing values out of strings

- src/libOpenImageIO/imageoutput.cpp
Scratch memory allocation in `ImageOutput::to_native_rectangle` was accidentally using the number of channels squared.
We encountered a case where saving a 2K EXR file with 107 channels would use more than 50GB.
I don't have a simple isolated repro case. It requires writing tiles with a stride that does not match the stride in the image file. But hopefully the error in the code is clear.
I did not add a test, it's not clear there is a good mechanism to verify memory usage like this with a test.
> Fix excessive memory usage when saving EXR file with many channels

- src/doc/builtinplugins.rst
- src/webp.imageio/webpinput.cpp
* Typo in webp section -- said "gif:LoopCount" when we meant
"webp:LoopCount".
* In the code, did not actually set the "oiio:LoopCount" metadata
that the docs said would be set.
* Opportunistic fix: TIFF docs said we only suported IOProxy for input,
but we have supported it for output for a while now.
> Fix docs/behavior with webp "LoopCount"

- site/spi/Makefile-bits
Running make at SPI currently complains about not finding llvm 11.0.1 (we don't have it; the closest one is 11.0.0) - is it ok to move up to 12.0.1 (which we do have installed)?
make now builds without complaining about not finding llvm 11.0.1
> SPI Specific: default to LLVM 12.0.1

- src/libutil/typedesc.cpp
- src/libutil/typedesc_test.cpp
The official names we use are "box2" and "box3", but users of Imath
know these as box2f/box3f, so accept these as synonyms when
constructing a TypeDesc from a string.
> TypeDesc ctr from string: accept "box2f", "box3f"

- src/hdr.imageio/rgbe.cpp
- src/iconvert/iconvert.cpp
- src/iv/imageviewer.cpp
- src/libutil/paramlist.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/png.imageio/png_pvt.h
- src/rla.imageio/rlainput.cpp
- src/targa.imageio/targaoutput.cpp
`sscanf()` still has locale-dependent behavior that we wish to avoid
because it can lead to subtle bugs for people whose machines are
configured for certain locales.
This patch removes from the OIIO codebase almost every remaining
sscanf use (and definitely every one that could harbor locale bugs).
Instead, we use the rich set of parsing functions we've added to
Strutil over the years, which are locale-independent, and in most
cases are also faster than the standard C/C++ equivalent.
> Banish sscanf

- src/libtexture/imagecache.cpp
In the early days of OIIO, it was 100MB. Ten years ago, we bumped it
to 256MB. I've heard a rumor that computer memories have grown in the
last 10 years, and so have the size of images some people deal
with. So it seems reasonable to raise it to 1GB.
> Raise ImageCache default tile cache size to 1GB

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/install_homebrew_deps.bash
- src/dds.imageio/ddsinput.cpp
- src/libutil/strutil.cpp
- src/png.imageio/png_pvt.h
* Add a test for MacOS 11
* Updated supported versions of dependencies
* Move linux clang test to clang13 on vfx2022 container
* Switch clang-format test to use clang12 (and minor adjustments that result)
> CI enhancements: MacOS 11, other updates

- src/cmake/compiler.cmake
This adds a new cmake variable in our build system, TIME_COMMANDS,
that when set ON will adjust the compile and link rule launch to
include a time command. This is probably only useful when also setting
`CMAKE_BUILD_PARALLEL_LEVEL=1` so that build are happening serially.
The use case is to investigate how long each module takes to compile,
for optimizing the build.
> Build: option to time individual compile commands

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
When I implemented `oiiotool --invert`, I knew that the default should
be to only invert the first three channels (presumably R,G,B) and not
anything beyond, because we wouldn't want to invert the Alpha channel.
But I botched it, and instead what happened is that if given an RGBA
image, it would just leave the A black in the result image.
So this patch has two improvements:
1. If there are more channels in the source image than we are
inverting, make sure to copy the other channels unmodified, don't
just leave them blank.
2. Allow optional modifiers chbegin= and chend=, so users can change
the default if they want a different channel set to be inverted.
> Fix to `oiiotool --invert` : avoid losing the alpha channel values

- src/oiiotool/oiiotool.cpp
ImageBufAlgo has both premult and repremult (as well as unpremult).
But oiiotool only exposed unpremult and premult, but not repremult.
This little patch rectifies that oversight.
Just to remind everybody of the difference:
`premult` just multipies the color channels by alpha, like it says.
Note that for a pixel that has Alpha = 0 but nonzero color, this will
crush the color to black.
That's fine if you have an *original* image that's unpremultiplied and
you want to do a one-time conversion to premultiplied.
But there's another use case, which is when you start with a
premultiplied image, you need to temporarily unpremultiply it (like
for a color space conversion), and then re-premultiply it. In that
case, you may have those glowing pixels in the original image, the
unpremult will …
> oiiotool --repremult

- CMakeLists.txt
- src/cmake/compiler.cmake
* Make PROJECT_VERSION_RELEASE_TYPE be a cache string, so individual
build configs or sites can override it.
* Change OpenImageIO_IS_SUBPROJECT to PROJECT_IS_TOP_LEVEL (and with
the opposite sense), to match CMake 21+ behavior. And no need to set
it ourselves if using cmake 21+.
> CMake tweaks

- src/include/OpenImageIO/filesystem.h
Makes for an easy one-call dump of a vector or other contiguous buffer to a file.
> filesystem.h: New write_binary_file utility template

- src/cmake/testing.cmake
- src/dds.imageio/ddsinput.cpp
- src/doc/builtinplugins.rst
- testsuite/dds/ref/out.txt
- testsuite/dds/run.py
* Add a DDS test, apparently we never had one.
* Remove DDS setting of "texturetype", we don't ever use that, it's only
"textureformat" that we use. Not sure how that crept in there years ago.
> DDS: add test, minor adjustments

- src/libOpenImageIO/imageinout_test.cpp
* --onlyformat or env IMAGEINOUT_TEST_ONLYFORMAT to test only one format.
* --no-delete to preserve the temporary files for inspection
* other debugging checks
> imageinout_test debugging aids

- src/libOpenImageIO/maketexture.cpp
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
This patch is an attempt to implement the pre-processing parts from Brent Burley's Histogram-Preserving Blending paper. It generates two float array lookup tables - one for transforming each image channel to a Gaussian distribution (the invCDF float array) and one for transforming from the Gaussian distribution back to the image's distribution (the CDF array). 
This will let whoever is consuming the image (like a shader) do the blending on Gaussian distributed data and transform the blended result back to the image distribution, preserving details better than a regular blend.
> Add support for writing Gaussian forward and inverse transform lookup tables

- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/maketexture.cpp
When the make_texture option monochrome_detect is used to collapse 3
identical channels to 1, it was leaving the first channel name in
place (for example, "R"). That was confusing, because at this point,
we're not trying to represent a red image, we're trying to represent a
grayscale image. A strategic call to `default_channel_names()` clears
it up, imposing the standard "Y" we use for a single channel luminance
image.
Also amended the documentation of IBA::channels(). It turned out not
to be the way I called channels() that was the problem here, but by
the time I figured that out, I had already seen that its docs could be
improved.
Fixes #3204
> make_texture()/maketx fix to channel name with monochrome_detect

- src/doc/maketx.rst
- src/doc/oiiotool.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/maketexture.cpp
Also, fixed the fact that direct calls to make_texture() were not given
proper defaults for the cdfsigma and cdfbits options.
Related to PR #3159
> Add documentation for new texture CDF options

- src/cmake/modules/FindLibRaw.cmake
This was deleted a few months back, but I think I did not realize
it still served a purpose. We don't use JasPer directly, but LibRaw
does, so if we are using static LibRaw, we still need it here.
Fixes #3209
> Restore code that finds Jasper when using static libraw

- src/build-scripts/ci-startup.bash
- src/cmake/compiler.cmake
- src/cmake/testing.cmake
Maybe somebody else is building this as a subproject or has a variable
called "CI"?
* For our CI runs, set an env variable "OpenImageIO_CI" (not just
generic "CI").
* Make sure STOP_ON_WARNING is true for our CI runs, even for release
branches -- but now check OpenImageIO_CI, not CI, in case somebody
else has set that.
> Use a project-specific var for whether we're running in CI

- src/gif.imageio/gifinput.cpp
- src/gif.imageio/gifoutput.cpp
- src/include/OpenImageIO/filesystem.h
- src/include/OpenImageIO/imageio.h
- src/jpeg.imageio/jpeg_pvt.h
- src/jpeg.imageio/jpeginput.cpp
- src/jpeg.imageio/jpegoutput.cpp
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/libutil/filesystem.cpp
As we move toward fully equipping all image format implementations
with full IOProxy support, it's clear that a lot of repeated code is
error-prone. I first tried to collect this in a mixin class, but then
re-implemented after realizing that we can use the existing PIMPL
ImageInput::Impl and ImageInput::Impl classes, without changing any
ABI or making new headers.
This patch add a couple data members to the Impl data -- an
`IOProxy*`, (the current proxy, used for both passed-in and created
proxies) and also a `unique_ptr<IOProxy>` used when we have to create
our own and want to make sure it's destroyed with the ImageInput or
ImageOutput.
Then we add a number of protected member functions to ImageInput and
ImageOutput, not meant to be ever called by "users" of the OIIO APIs,
but used …
> Better IOProxy support for image format implementations

- src/cineon.imageio/cineoninput.cpp
- src/doc/stdmetadata.rst
- src/dpx.imageio/dpxinput.cpp
- src/dpx.imageio/dpxoutput.cpp
- src/hdr.imageio/hdrinput.cpp
- src/iv/ivimage.cpp
- src/libOpenImageIO/color_ocio.cpp
- src/png.imageio/png_pvt.h
- src/rla.imageio/rlainput.cpp
- src/rla.imageio/rlaoutput.cpp
- src/targa.imageio/targainput.cpp
- src/targa.imageio/targaoutput.cpp
For some reason, in the early days I got in the habit of having OIIO
input readers call their color space "GammaCorrected2.2" (for example)
when they appeared to be a straight-up gamma. (Generally only used for
certain fairly old formats that date from before sRGB existed.)
But there appears to be a widely used convention of naming OpenColorIO
spaces "GammaX.Y", so I'm switching OIIO to conform that
convention. It's more straightforward and increases the chances that
it will match the names of color spaces that already exist in people's
OCIO configs.
> Name gamma-corrected color spaces "GammaX.Y"

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageoutput.cpp
Helper functions ioproxy_opened() and iotell() should have been const
all along, since they just return back information and should not
change state of the proxy, and also ioproxy() should have both const
and non-const versions.
> Minor ImageInput/ImageOutput IOProxy handling tweaks

- src/dds.imageio/ddsinput.cpp
- src/doc/builtinplugins.rst
As well,
* Add a DDS test, apparently we never had one.
* Remove DDS setting of "texturetype", we don't ever use that, it's only
"textureformat" that we use. Not sure how that crept in there years ago.
> DDS input IOProxy support

- src/doc/builtinplugins.rst
- src/pnm.imageio/pnminput.cpp
- src/pnm.imageio/pnmoutput.cpp
- testsuite/pnm/ref/out.txt
Also fix longstanding bugs in PNM input:
* We weren't correctly emulating random scanline access, as is expected
(but in practice rarely used) of all ImageInput implementations.
* We weren't marking the color space in any way, now we do mark as
"Gamma2.2", which is the correct/preferred interpretation according
to the PNM spec.
> PNM overhaul to support IOProxy

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/gh-installdeps.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenJPEG.cmake
- src/jpeg2000.imageio/jpeg2000input.cpp
- src/jpeg2000.imageio/jpeg2000output.cpp
* The main event here is that we're now telling OpenJPEG to use
threading when compressing/decompressing JPEG-2000 files.  This
improves the speed of JPEG-2000 reading on my laptop by 2-3x!  The
threading feature was added to OpenJPEG 2.2 for decode, and 2.4 for
encode.
* CI: Build OpenJPEG 2.4 for the "latest releases" test, and build
their master for our "bleeding edge" test.
* Fixes to deal with the in-progress 2.5 deprecating a struct field.
* Generally clean up our detection of what OpenJPEG version we are
using.
* Some clean-up of the FindOpenJPEG.cmake file, use PATH_SUFFIXES.
> JPEG2000: enable multithreading, other fixes

- CMakeLists.txt
- src/cmake/testing.cmake
For that matter, don't set up and copy the tests at all when it's off.
Fixes #3189
> CMake: don't download missing test data if BUILD_TESTING is off

- src/include/OpenImageIO/strutil.h
- src/libutil/argparse.cpp
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
This string utility computes the "edit distance" between two strings.
Currently it only uses the Levenshtein metric, but it has room for
future expansion by taking a parameter that can specify which metric
to use. Levenshtein is an algorithm for computing how many single
character insertions or deletions are necessary to turn one string
into the other.
I have a few ideas for where this can be useful, but as one
demonstration, I also modify the ArgParse class internals so that if a
command is not found, it will print a suggestion naming the valid
command option that has the closest edit distance (but only if one
choice is <= 2 edits away, and only if it's not a single-character
option, in order to reduce the number of useless suggestions). Here's
its behavior in action:
$ iinfo --stat …
> Strutil::edit_distance()

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/tiff.imageio/tiffinput.cpp
Add two new global OIIO attributes: "limits:channels" and
"limits:imagesize_MB" which are imposed limits for validating a
reasonable number of channels and total uncompressed image size,
respectively. We presume that an image file header describing an image
that purports to exceed these is most likely corrupted or even
maliciously crafted. The limits, therefore, are designed to avoid
crashes, absurd memory allocations, or other cascading errors that
would result from taking such a claim at face value (for example,
a file that appears to have tens of thousands of color channels).
The limits default currently to a maximum of 1024 color channels, and
a maximum uncompressed data size of a single 2D image to 32GB.  These
seem reasonable today, but if such large sizes become likely to be
seen …
> Protect against corrupt headers with image size and channel limits

- src/dpx.imageio/dpxinput.cpp
- src/dpx.imageio/dpxoutput.cpp
- src/png.imageio/pnginput.cpp
- src/png.imageio/pngoutput.cpp
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
After setting up the new IOProxy helper methods for ImageInput and
ImageOutput, here we go back to the readers/writers that had used
proxies for a long time, and switch them to using the new helpers.
> IOProxy cleanup -- use new helper methods for TIFF, DPX, and PNG.

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture3d.cpp
- src/libtexture/texturesys.cpp
TextureSystem is designed primarily for tiled images (typically 64x64
pixels each), but to handle untiled images, it just treats the whole
image as one big tile. That means for very large untiled images, you
might end up with one VERY large tile, and if the image is large
enough, the size and/or offset computations therein may overflow a
32 bit int.
This patch attempts to make all the offset computations in the texture
system be 64-bit safe.
> Make texture system 64-bit safe for tile access

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texturesys.cpp
Errors encountered while reading tiles were getting lost as we used
ImageBuf::Iterator to iterate over an image. Have the iterator keep a
flag for whether it encountered an error, set to true if the
ImageBuf::retile indicates an error occurred during the read.
Also, some ImageCache errors might get lost on the way to
TextureSystem calls, fix that as well.
> Improve error propagation from ImageCache to higher levels

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
When doing operations with filters that have negative lobes, you can
sometimes get visible ringing artifacts in very high contrast regions
of HDR images (you tend not to see these artifacts in images that have
range [0,1] because the ringing is very low amplitude unless the input
is very large).
You can do "highlight compensation" to reduce the artifacts when they
occur by doing --rangecompress, which does a log transform on the
input, then the filtered op, then --rangeexpand to transform back to a
linear space. But that makes for kind of verbose and clumsy command
lines, and makes it easy to err by doing the transforms in the wrong
sequence or omitting one.
The -otex command takes a highlightcomp=1 modifier, which does this
bracketing automatically, foolproof, with a compact notation. …
> oiiotool: allow all filtered ops to take highlightcomp= modifier

- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/ustring.h
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/oiiotool/printinfo.cpp
Also tagged Strutil and ustring::fmtformat as 'nodiscard', to produce
warnings if people call it and ignore the results. (As was the case in
my own bug that I tracked down in the course of this patch.)
> oiiotool internals: convert all error and warning to fmt style

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagespec_test.cpp
- src/python/py_imagespec.cpp
For each ImageSpec ctr that takes a TypeDesc, add another one
that's the same but takes a string_view (which is just a simple
pass-through of the TypeDesc-from-string_view).
> ImageSpec: New constructors to accept string for data type

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/build_pybind11.bash
* Use the new pybind11 v2.9.0 for 2022 and "latest" tests.
* Bump the default version built by build_pybind11.bash to 2.8.1.
* Adjust the pybind11 version used in many of the other CI tests, to
give an even spread across versions, and to make each of the
"vfx platform" CI tests use the pybind11 version that was available
near the start of its repsective year.
> CI: pybind11 version bumps

- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagebuf.h
- src/python/py_imagebuf.cpp
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imagebuf/src/test_imagebuf.py
Deduce the ImageSpec from the shape and type of the ndarray, and
copy its contents into the ImageBuf.
Closes #2954
> Python: ImageBuf constructor/reset from numpy array

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
* Docs: we previously only documented the "width=" optional modifier.
Add height, color1, color2.
* Change behavior ever so slightly so that if the "height=" modifier is
not supplied, the height defaults to the "width".
> `oiiotool --pattern checker` tweak and documentation fix

- src/doc/imagebufalgo.rst
- src/python/py_imagespec.cpp
- src/python/py_roi.cpp
- testsuite/python-roi/ref/out.txt
- testsuite/python-roi/src/test_roi.py
Somehow we never implemented a copy() method for ROI, which of course is
super useful if you want to make an actual copy of an ROI and modify
the copy.
I also realized that ImageSpec.copy() unnecessarily/incorrectly set
return_value_policy to reference_internal, but actually it should be a
real copy, which it has to be anyway because the implementation
creates a separate copy.
> Python: implement ROI.copy()

- src/doc/imageinput.rst
- src/doc/imageoutput.rst
- src/doc/pythonbindings.rst
- src/python/py_imagespec.cpp
- src/python/py_oiio.h
- src/python/py_paramvalue.cpp
- testsuite/python-imagespec/ref/out-python3.txt
- testsuite/python-imagespec/ref/out.txt
- testsuite/python-imagespec/src/test_imagespec.py
- testsuite/python-paramlist/ref/out.txt
- testsuite/python-paramlist/src/test_paramlist.py
The Python bindings for ParamValueList and ImageSpec allow a "dict"
style (associative array) interface:
imagespec["key"] = value
val = imagespec["key"]
This patch makes some minor improvements:
* Clarify in the docs that like a regular Python dict, the associative
retrieval will raise a KeyError if the key is not found.
* Add `__contains__` python method as a synonym for contains(), thus
implementing `key in dict`.
* Add `__delitem__` python method as a synonym for erase(), thus
implementing `del dict[key]`.
* Add an `ImageSpec.get()` method that is a synonym for getattribute
(which retrieves the item or returns None or a default if not
found), mirroring the behavior of Python's `dict.get()`.
> Python: improve ParamValueList and ImageSpec dict interface

- .github/workflows/ci.yml
- src/build-scripts/ci-build.bash
- src/cmake/externalpackages.cmake
New OpenColorIO and fmt versions are out.
* Bump "latest releases" test to fmt 8.1.0, and OCIO 2.1.1.
* Re-adjust CI test fmt versions across many tests to give a better
spread over the supported releases.
* Bump the default version to download and use if none is found to 8.0.0.
> CI: Bump OCIO and fmt versions

- src/include/OpenImageIO/imagebufalgo.h
This little change makes this work:
ImageBufAlgo::add (buf, { 0.2f, 0.2f, 0.2f });
instead of the more awkward
ImageBufAlgo::add (buf, cspan<float>({ 0.2f, 0.2f, 0.2f }));
and for anyplace that has Image_or_Const parameter types.
> ImageBufAlgo: Slightly more flexibility in inferring constants

- src/doc/imageoutput.rst
I found this while reading through the image output section and it seems wrong given the following examples.
Fixes the docs regarding environmental variable usage to match the examples used.
Didn't add tests
> Fix variable usage example in docs

- src/oiiotool/oiiotool.cpp
We had forgotten to mark --colorcount and --rangecheck as commands
that intentionally output to the console. This omission meant that an
oiiotool command consisting only of those would warn about no
output.  But we didn't really want it to warn in this case.
> oiiotool: don't warn for --colorcount or --rangecheck

- src/doc/imagebufalgo.rst
- src/doc/oiiotool.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagebufalgo.h
In addition to C++ code examples for each IBA function, work toward
also having equivalent Python code. Also, where applicable, show the
equivalent operation using oiiotool.
> Docs: supply more python and oiiotool examples to IBA docs

- src/include/OpenImageIO/typedesc.h
With clang 10 (haven't tested anything else) I get the following warning with the old code. Apparently `const` isn't needed and removing it fixes the warning.
```
include/OpenImageIO/typedesc.h:620:10: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
auto parse(format_parse_context &ctx) -> decltype(ctx.begin()) const // c++11
```
No, it's a compiler warning.
- [] I have updated the documentation, if applicable.
- [] I have ensured that the change is tested somewhere in the testsuite
> Fix clang 10 warning:

- src/libOpenImageIO/maketexture.cpp
I realized that a call to make_texture() with the "maketx:ignore_unassoc"
attribute set did not properly set the configuration attribute up when
opening a new ImageBuf.
> make_texture: ensure that "maketx:ignore_unassoc" is honored

- src/build-scripts/build_opencolorio.bash
- src/cmake/compiler.cmake
- src/cmake/modules/FindOpenColorIO.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
* Bugs fixed in build_opencolorio.bash, it botched some of the directory
choices when customizing where to place and build it. Also, switch to
the more standard BUILD_SHARED_LIBS cmake variable to control whether
to build dynamic or static libraries.
* Correctly handle the cmake variable VISIBILITY_MAP_FILE being set to
"" on the command line as a way to disable using the visibility map file
entirely.
* FindOpenColorIO.cmake changes:
- Prefer and use an exported cmake config for OCIO if found (is should
be present for OCIO 2.1+), unless caller set OPENCOLORIO_NO_CONFIG=ON.
- New hint OPENCOLORIO_INTERFACE_LINK_LIBRARIES lets caller force a
list of interface link libraries. This is helpful when purposely using
a static OCIO library, which itself has static dependencies, and you
need to …
> Minor build and compile fixes

- src/build-scripts/build_openexr.bash
The script that builds OpenEXR failed on Windows because it hard-coded the "Unix Makefiles" generator, contrarily to the other build scripts that do not provide a default value and work out of the box (since CMake automatically picks an appropriate generator when unspecified).
It's still possible to pick a specific generator from outside the script by defining the CMAKE_GENERATOR env variable.
> Fix OpenEXR build script for Windows

- src/tiff.imageio/tiffinput.cpp
Some rogue app out there is writing 4-channel TIFF files without the
ExtraSamples tag in the header that explains that the data is a valid
alpha channel.
We were using TIFFGetFieldDefaulted to retrieve this tag, and guess what?
The defaulted behavior changed between libtiff 4.0 and 4.3!
Changing to TIFFGetField actually turns out to fall back to the right
logic on our side, which boils down to assuming a 4th channel is alpha
if there's no other information. That seams reasonable -- RGB + mystery
channel is almost certainly RGBA.
> TIFF: gracefully handle missing ExtraSamples tag

- src/doc/builtinplugins.rst
- src/tiff.imageio/tiffoutput.cpp
Ugh, there's a situation where PhotoShop is misinterpreting an alpha
channel for certain OIIO-written TIFF files, but it's fine with some that
came from elsewhere, and the only thing that appears to be different is
that the non-OIIO one entirely lacks the EXTRASAMPLES TIFF tag.
So I'm adding an option (use with extreme caution) allowing you to
tell the TIFF output to not output this tag, even though clearly it
should be.
> TIFF: Special hint to suppress output of EXTRASAMPLES tag

- src/oiiotool/oiiotool.cpp
I realized recently that if you said something like
oiiotool foo.exr --ch R,G,B,A -o out.exr
and there was no "A" channel... it would just silently fill the channel
with 0 in the output.
This patch adds a warning if --ch is told to copy a channel that doesn't
exist in the input.
> oiiotool --ch : warn for unknown channels

- src/doc/builtinplugins.rst
- src/targa.imageio/targainput.cpp
- testsuite/targa/ref/out.txt
The main event:
* Assume that for a TGA 1.0 file (too old to have the header field
that says if alpha is associated, unassociated, or meaningless), if
the alpha is zero everywhere, it means that it's meaningless, not
unassociated, so in that case we should skip the
auto-premultiplication. (See issue #3277)
Public-ish stuff:
* Be more consistent with Targa-specific attributes all being called
"targa:foo" (most were, but one was "tga:alpha_type").
* Document all the targa-specific attributes (a few were not).
* Add "targa:version" to reveal whether the file was a TGA 1.0 or
2.0 version of the format.
Internal stuff, opportunistic:
* Some more minor conversions of string fomatting to fmt style.
* Convert some std::cerr debugging code (commented out) to the DBG macro
we use anywhere.
* The …
> Targa improvements: attribs, unassociated alpha handling, and more

- Makefile
- src/cmake/compiler.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
We were passing along, in the exported cmake config files, a demand
for downstream clients to use a C++ standard version equal to that
which we used to build OpenImageIO itself. But that's not
necessary. We may choose to build with C++17 (for example), but all of
our public APIs are safe to use for C++14.
Split the build-time options to CMAKE_CXX_STANDARD for the standard we
build this project with, and DOWNSTREAM_CXX_STANDARD for the standard
we are declaring is the minimum to *use* the library.
> Separate C++ that we build with from what we demand downstream

- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
> Filesystem::searchpath_split handle empty paths

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
Our Strutil utilities for utf8 <-> utf16 conversion were based on
Windows specific calls that we had added even before C++11 was our
minimum. Replace the Windows-specific code with std calls, and
expose them in strutil.h for all platforms (why not?).
> utf8 / utf16 conversion modernization

- .github/workflows/ci.yml
When a build breaks, having these additional files is really helpful
to track down what went wrong.
> CI: revise failed build artifact storage to capture cmake files

- src/cmake/Config.cmake.in
- src/cmake/modules/FindOpenEXR.cmake
- src/include/OpenImageIO/oiioversion.h.in
This makes sure that two new preprocessor symbols are defined in
oiioversion.h: `OIIO_USING_IMATH_VERSION_MAJOR` and
`OIIO_USING_IMATH_VERSION_MINOR`, revealing the version of Imath being
used by the build of OIIO (which may not be the same as the version
found or being used by the app that's calling OIIO). They also get
defined as CMake variables in our exported cmake configs, allowng
downstream cmake build systems to be able to easily test whether the
Imath they found is compatible with the version that we use in our
APIs.
> Embed Imath version symbols in oiioversion.h

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/pnm.imageio/pnminput.cpp
C isspace() takes an int, but on Windows when building in debug mode,
the implementation of isspace() can hit an assert if the value is < 0,
which of course it can be if you're looking at a character in a string
whose high bit is set (because char is signed).
Easiest solution is to make our own Strutil::isspace that does exactly
what we want and is safe.
Fixes #3300
> Avoid unsafe isspace()

- src/include/OpenImageIO/filesystem.h
- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/texture.h
- src/python/py_imageinput.cpp
As Doug Rogers points out in Issue #3304, it is customary for Windows
applications to use wstring extensively for Unicode support. But it's
especially critical for unicode filenames, because unlike Unix-like
OS's where fopen() and similar functions support UTF-8, on Windows
those functions are strictly ASCII, and Windows users are used to
calling _wfopen() and other nonstandard functions that expect
filenames to be std::wstring if they want to support Unicode.
This patch:
* More clearly documents through all of our classes when parameters that
represent filenames or searchpaths are assumed to support UTF-8.
* Augments ImageInput, ImageOutput, and ImageBuf so that their methods
that take file names or path lists have additional flavors that take
wstring (always implemented as an inline …
> wstring (almost) all the things

- src/include/OpenImageIO/hash.h
- src/include/OpenImageIO/strutil.h
- src/iv/imageviewer.cpp
- src/iv/ivinfowin.cpp
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libutil/filesystem.cpp
- src/oiiotool/oiiotool.cpp
We wrote our string_view before C++17 std::string_view was finalized,
and the std one doesn't have a c_str() method. For conformance with the
standard, I want to remove this over time from ours.
Part 1: There were some places we did not need to call c_str() at all,
and some places where it was much more appropriate to just use a
std::string.
This is the lowest-hanging fruit. I will have later follow-ups.
> Work toward eliminating string_view::c_str()

- CMakeLists.txt
- src/cmake/Config.cmake.in
- src/cmake/modules/FindJPEGTurbo.cmake
- src/igrep/CMakeLists.txt
- src/iinfo/CMakeLists.txt
- src/jpeg.imageio/CMakeLists.txt
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
- src/oiiotool/CMakeLists.txt
- src/openexr.imageio/CMakeLists.txt
- src/openvdb.imageio/CMakeLists.txt
- src/psd.imageio/CMakeLists.txt
- src/tiff.imageio/CMakeLists.txt
Those changes fix the produced CMake package not being relocatable, as reported in Issue https://github.com/OpenImageIO/oiio/issues/2559.
There are 3 main changes:
- Replace the absolute paths in the cmake export template with relative paths.
- Replace the absolute include path `CMAKE_INSTALL_FULL_INCLUDEDIR` with the `$<INSTALL_INTERFACE:include>` generator expression.
- Use explicit target names to link dependencies instead of the XXX_LIBRARIES variables. Using the old-style XXX_LIBRARIES injected absolute paths in the import script. With explicit targets, CMake references their names instead, and it's the responsibility of the consumer to provide proper paths/call find_package.
- This particular change forces us to spell out the exact components of some dependencies (eg. …
> Relocatable cmake package

- src/doc/builtinplugins.rst
- src/libOpenImageIO/iptc.cpp
- src/tiff.imageio/tiffoutput.cpp
IPTC data blocks seems buggy, and I don't know why. Our code?
Something in libtiff?  Since nobody is depending on it and none of our
testsuite appears to fail when disabled, only write the IPTC block if
the user explicitly asks for it.  Also, when reading them, don't
overwrite other metadata of the same name.
> TIFF: Mitigate IPTC corruptions

- src/include/OpenImageIO/imageio.h
One new method that should have been inline and non-virtual (so that
this whole set of changes does not change ABI by shifting the vtable
around) was accidentally marked virtual -- cut and paste error. This
patch fixes it to restore ABI compatibility.
This fixes a problem with #3312
> Correction to recent wstring changes: un-virtualize one method

- src/doc/pythonbindings.rst
The python documentation for `ImageBuf.set_full()` states it requires a `ROI` which doesn't seem to be the case.
This PR updates the documentation and example to match C++
This is a pure documentation update. No additional tests needed 
> update python documentation for ImageBuf.set_full() 

- src/oiiotool/oiiotool.cpp
- src/png.imageio/png_pvt.h
- src/pnm.imageio/pnminput.cpp
- testsuite/ico/ref/out.txt
- testsuite/pnm/ref/out.txt
PPM by specification is Rec709! Make it so.
PNG files were getting marked as sRGB or Gamma if certain header
attributes were found in the file, but if they were absent, we didn't
designate a color space at all. Change so that the default assumes
sRGB, in the absence of any metadata telling us for sure.
Fixes #3084
> Color space adjustment for PPM and PNG files.

- src/cmake/Config.cmake.in
- src/cmake/externalpackages.cmake
- src/include/OpenImageIO/Imath.h.in
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
* `OPENIMAGEIO_IMATH_DEPENDENCY_VISIBILITY` is a new CMake cache
variable at OIIO build time that controls whether the Imath library
dependencies will be declared as PUBLIC (default) or PRIVATE target
dependencies of libOpenImageIO and libOpenImageIO_Util.
* For *downstream projects* that consume OIIO's exported cmake config
files, setting CMake variable `OPENIMAGEIO_CONFIG_DO_NOT_FIND_IMATH`
to true will skip the find_depencency() calls for Imath and OpenEXR.
To clarify, this is not a variable that has any effect when building
OIIO, it's something set in the downstream project itself.
* Add a `OIIO_IMATH_H_INCLUDED` header guard in OpenImageIO/Imath.h,
which allows something downstream to pre-define it to prevent OIIO
headers it needs to read from using the contents of that header.
Most …
> Changes to make it easier to hide the Imath dependency

- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/ustring.h
- src/libutil/ustring.cpp
It turns out that this can crop up all the time, sometimes from
malformed metadata inside image files. We weren't noticing it because
in many cases, things ended up being turned into ustrings twice, and
the sequence string-with-nuls -> ustring() -> c_str() -> ustring()
will launder it. As I was tracking down and eliminating some of the
double ustring constructions, the metadata strings that were malformed
all along started becoming symptomatic.
Bad paradoxes follow from a ustring contain embedded NUL characters,
including ustring.c_str() and ustring.string() being different
character sequences, as well as ustring.hash() not being equal to
strhash(ustring.c_str()). One should definitely be able to count on
ustring(cstring) == ustring(ustring(cstring).c_str()).
So this patch checks for …
> Handle NUL (0) characters in ustrings by truncating.

- src/include/OpenImageIO/detail/fmt.h
- src/include/OpenImageIO/strutil.h
The very latest fmt master changes a behavior: fmt functions no longer
automatically know how to format any type that can output to an
ostream, and instead need custom formtter objects. This breaks A LOT.
Fix by defining the preprocessor symbol `FMT_DEPRECATED_OSTREAM`,
which restores the old behavior (for now, at least).
While I was at it, I moved the fmt inclusion logic out of strutil.h
and into a new separate header, detail/fmt.h. This is in turn included
from strutil.h, so nothing in user code needs to change.
> Split fmt setup into detail/fmt.h, fix fmt ostream problem

- src/targa.imageio/targainput.cpp
Skip 3 bytes between "software" and "background (key) colour" for the "software
version" (was simply missing). Avoids that m_alpha_type is overwritten with
wrong values.
Did not create a new test case. Existing targa test fails for me (probably unrelated) with:
```131/161 Testing: targa
131/161 Test: targa
Command: "/usr/bin/python3.9" "/some_prefix/src/testsuite/runtest.py" "/some_prefix/src/build-debug/testsuite/targa"
Directory: /some_prefix/src/build-debug
"targa" start time: Feb 04 09:19 CET
Output:
----------------------------------------------------------
Traceback (most recent call last):
File "/some_prefix/src/testsuite/runtest.py", line 452, in <module>
exec (code)
File "run.py", line 3, in <module>
ModuleNotFoundError: No module named 'OpenImageIO'
<end of output>
Test time = …
```
> Targa: Fix parsing of TGA 2.0 extension area.

- src/doc/maketx.rst
- src/doc/oiiotool.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/maketexture.cpp
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
- src/tiff.imageio/tiffinput.cpp
For vector displacement maps or normal maps that are in tangent space,
it is heplful to be able to record whether the data are intended to use
a local left-handed or right-handed coordinate system, and for that to
be querably from the shader accessing the map.
The `maketx --handed` option, or `oiiotool -attrib -otex:handed=...`,
or adding "handed" metadata to the configuration ImageSpec being
passed to `IBA::make_texture()` does this. It's easy for texture
formats like openexr that allow arbitrary metadata. For TIFF textures,
we embed it in the ImageDescription tag (as we do for several other
texture-specific hints).
> Add texture creation metadata: "handed"

- src/cmake/Config.cmake.in
- src/cmake/externalpackages.cmake
Add an OIIO build-time option for forcing our exported
OpenImageIOConfig.cmake to skip the find_dependency of Imath and
OpenEXR.
This is helpful if you're at a site that is trying to build OIIO
against statically compiled Imath/OpenEXR, and want to be super sure
the downstream projects are definitely not going to encounter that
find_dependency(Imath) when the read the OIIO config files.
(They could do their own `-DOPENIMAGEIO_CONFIG_DO_NOT_FIND_IMATH`,
but I want even that to be unnecessary.)
> More Imath hiding controls

- .github/workflows/ci.yml
Also, for the bleeding edge test, OpenEXR's "master" has been renamed
to "main".
> CI: bump OpenEXR version used for 'latest'

- src/cmake/pythonutils.cmake
- src/python/CMakeLists.txt
Just like we had done for the other libraries recently. And need
to make sure that the imath libs are added explicitly to the python
module's needs, since for hidden static libraries, they will not get
picked up merely by linking to libOpenImageIO.
> Hide static library dependency symbols from the python module

- src/libOpenImageIO/CMakeLists.txt
Make the imath includes respect the recently added
OPENIMAGEIO_IMATH_DEPENDENCY_VISIBILITY flag, just like the libraries
do.
> Imath fiddling

- src/include/OpenImageIO/unittest.h
Example of how I know this is better: if eps == 0, being exactly right
should *pass*, not *fail*.
> Testing: OIIO_CHECK_SIMD_EQUAL_THRESH to use <= eps

- src/oiiotool/oiiotool.cpp
We weren't doing quite the right calls to set the attributes correctly
after performing the scale.
> oiiotool --pixelaspect : fix setting of attributes

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
* New "wrap" optional modifier lets you specify which wrap mode to pass
to IBA::warp().
* fix typo in error message.
> oiiotool --warp improvements

- src/iconvert/iconvert.cpp
- src/iinfo/iinfo.cpp
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/oiiotool/printinfo.cpp
- src/python/py_imageinput.cpp
...and stop using them internally as well.
For some of the IBA functions, we were unable to fully mark them as
OIIO_DEPRECATED (so instead that hint is commentd out) because the
function signatures of the deprecated and new ones can be
ambiguous. We're just going to have to delete those when we are at a
compatibility break point, without going through a period where they
are present but marked as deprecated.
> Mark a bunch of long-deprecated things as OIIO_DEPRECATED

- src/include/OpenImageIO/string_view.h
- src/include/OpenImageIO/ustring.h
- src/libutil/strutil_test.cpp
* Allow ustring and OIIO::string_view to auto-cast to fmt::string_view
(helps some fmt formattting of types without custom formatters).
* When std::string_view (C++17) and/or std::experimental::string_view
(some compilers pre-C++17) are available, add OIIO::string_view
auto-construction from and auto-casting to those types.
> Auto conversion from among different string_view types

- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
- src/iv/imageviewer.cpp
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture_pvt.h
- src/libutil/filesystem.cpp
c_str() was cute, but it's a little dicey and it's not present in
the C++20 std::string_view. We didn't use it in a ton of places,
so replace with other idioms so that in the future we are better
able to interchange with std::string_view or replace our own entirely
once we have flying cars and C++20 minimum.
> Wean ourselves off of string_view::c_str()

- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/paramlist.h
- src/libOpenImageIO/formatspec.cpp
- src/libutil/paramlist.cpp
Special case some methods of ParamValue, ParamList, and
ImageSpec::attribute for ustring and string_view data, to reduce some
redundant copies and/or ustring conversions.
The internal method init_noclear() is augmented with a flag that allows
the caller to specify that any string data it might point to is already
ustrings, and thus does avoid the costly default behavior of converting
strings in the data block to ustrings. (This is not publicly exposed, so
users can't screw it up.)
So the new ParamValue constructor directly from a ustring can use this
flag to avoid passing the already-ustring through the string-to-ustring
conversion a needless second time. But also, the copy constructor, move
constructor, and assignment can use the flag and avoid the extra
conversion, since by definition …
> Improvements to ParamList and ImageSpec to reduce ustring construction

- src/iinfo/iinfo.cpp
Inadvertently broken by PR 3328.
> Fix broken iinfo --stats

- src/include/OpenImageIO/string_view.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/formatspec.cpp
- src/libutil/filesystem.cpp
Seemed like a good idea when we wrote it, but subsequently,
std::string_view was accepted into C++17 without a str() method. So
for the sake of future full interchangeability with std::string_view,
stop using this method.  We will eventually deprecate it.
> Avoid internal use of OIIO::string_view::str()

- src/cmake/compiler.cmake
Slight reworking of -Werror logic to let the default behavior be
changed by setting a cmake variable. In particular, this allows us to
make a CI build disable -Werror when we need to.
Previously, having the "OpenmageIO_CI" env variable set trumped all
else and forced -Werror. Now it just contributes to the default behavior,
but setting `-DSTOP_ON_WARNING=OFF` and cmake config time can still
disable it.
> Build: allow -Werror to be disabled even on CI branches

- testsuite/maketx/run.py
- testsuite/oiiotool-maketx/run.py
- testsuite/runtest.py
Just reconciling some differences between this file and the analogous
one in OSL.
> runtest.py: Rename oiio_relpath to make_relpath

- src/include/OpenImageIO/benchmark.h
- src/include/OpenImageIO/simd.h
These are cases where we declared a template, then later gave its full
definition, and we marked the declaration of the OIIO_FORCEINLINE but
omitted it from the later definition.
This addresses some compiler warnings from icc.
> Fix inline discrepancies between template decl and redecl

- .github/workflows/ci.yml
- src/build-scripts/gh-installdeps.bash
- src/build-scripts/oneAPI.repo
- src/cmake/pythonutils.cmake
- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/platform.h
- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imagebufalgo_yee.cpp
- src/libutil/fmath_test.cpp
- src/libutil/simd_test.cpp
- src/libutil/sysutil.cpp
- src/openvdb.imageio/openvdbinput.cpp
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imagebuf/src/test_imagebuf.py
- testsuite/tiff-depths/ref/out-icc.txt
* New CI test downloads the Intel icc compiler and builds with it.
* A variety of minor fixes to address warnings from icc that were
not apparent from the other compilers.
* Some minor changes to just a few tests and reference output where
the icc-built compiler produces slightly different (usually LSB)
results.
> CI: first stab at CI builds for Intel compiler

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
Strutil::print wraps fmt::format to render the formatted output into a
std::string, then sends the string to Strutil::sync_output(), which
ensures that every string printed (or sent to a FILE or stream) is
done so atomically, using an internal mutex, and with a stream flush
after each string. But this makes it a lot more expensive than it
needs to be, when you don't need such care -- either because buffered
output is ok, or because you don't need the thread safety.
This patch:
* Adds an optional `flush` parameter to sync_output(), defaulting to
true, which controls whether sync_output flushes or not.
* Introduces Strutil::sync::print, which is the same fully
synchronous, thread-safe, non-buffering behavior that Strutil::print
has traditionally had. Use this when you need those features.
* …
> Strutil::print vs sync::print

- .github/workflows/ci.yml
- src/build-scripts/ci-startup.bash
I finally learned how the "strategy" stuff works and refactored our
CI workflow based on it.
In short, we previously treated each CI test as its own universe, with
a huge amount of repeated build logic. These changes cut down on
redundancy by, for each set of related tests, collapsing them into
just one recitation of the build script logic and a handful of
variables that create the different test variations.
Currently, the categories are (a) all tests based on ASWF containers and
corresponding to VFX Platform specs, (b) "off-year" combinations based
on the native Ubuntu installations, (c) Mac tests, (d) Windows tests,
(e) the clang-format checker.
This refactor cuts the size of the ci.yml file by more than 50%, and
makes it much easier to add or change individual test configurations
in …
> CI: Use GHA "strategy" to make test descriptions more compact

- src/include/OpenImageIO/thread.h
- src/libutil/thread.cpp
Fixes #3357, which reported problems with Clang + libc++ + Windows,
where our old code used something pthreads-specific.
> Switch to using std::this_thread::yield() now that we are C++11

- .github/workflows/ci.yml
- src/build-scripts/gh-installdeps.bash
- src/cmake/compiler.cmake
- src/include/OpenImageIO/benchmark.h
- src/include/OpenImageIO/detail/fmt.h
- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/platform.h
- src/libutil/simd_test.cpp
icx is the *new* Intel LLVM-based compiler, and it behaves a lot like
clang (versus icc, which is the "classic" Intel compiler).
* An additional CI test in ci.yml for icx.
* Tweaks in compiler.cmake and platform.h to detect and set options for
this compiler.
* A variety of warning fixes encountered for this compiler.
* Add a new cmake build-time option `ENABLE_FAST_MATH` (default: OFF)
for enabling fast-math optimizations that trade IEEE compliance for
speed. The Intel compiler enables it by default (!), so this build
option makes icx behave like the other compilers (not fast math
unless explicitly asked for), which makes the CI tests and other
behavior more consisent across compilers and platforms.
* Note: The bug that prevents some versions of fmtlib from working
with icc does not …
> Build and CI and support for the icx compiler

- src/ffmpeg.imageio/ffmpeginput.cpp
The use of ends_with instead of iends_with made it so that
capitizalized files (especially on case-independent filesystems like
Windows or some Mac filesystems) were rejected.
(And yes, I did grep the whole code base for ends_with to be sure that
this was the only place we made this mistake.)
Fixes #3362
> ffmpeg: make supported file extension check be case-insensitive

- src/jpeg.imageio/jpeginput.cpp
- src/jpeg.imageio/jpegoutput.cpp
- src/libOpenImageIO/exif.cpp
- testsuite/psd/ref/out.txt
JPEG expresses pixel aspect ratio implicitly as header fields
"xdensity" and "ydensity" (which we call "XResolution" and
"YResolution" in our metadata after the TIFF names). We also have
"PixelAspectRatio", so the three of them, if they are all used, form
an over-constrained system. Plus, they may come both in the JPEG
header and also (not necessarily having the same values) in any Exif
block.
And on top of that, the way Nuke and PhotoShop infer the aspect ratio
is BACKWARDS! (If pixelaspect = width/height of a displayed pixel,
then it's also = ydensity/xdensity. But Nuke is the other way
around. Only for JPEG, it gets it right for TIFF and OpenEXR.)
Anyhoo, there were some edge cases in which we were still getting
confused (specifically, that we were making some files that Nuke was
not …
> JPEG: better handling of PixelAspectRatio

- src/include/OpenImageIO/simd.h
> simd.h fix for armv7 -- vaddvq_s32 is only aarch64

- src/include/OpenImageIO/Imath.h.in
- src/include/OpenImageIO/detail/fmt.h
- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/simd.h
- src/include/OpenImageIO/type_traits.h
- src/libutil/CMakeLists.txt
- src/libutil/strutil_test.cpp
- src/libutil/type_traits_test.cpp
I'm a total convert to fmt (and/or std::format, std::print) and slowly
converting all prior use of sprintf and iostream to it.
If I print an Imath::V3f or a simd::vfloat3,
fmt::print ("v = {} {} {}\n", myvec[0], myvec[1], myvec[2]);
That's ok, I guess, but it's clunky and a big pain to put the format
specification for every element separately if it were a vfloat16,
say. I would like to be able to do this:
fmt::print ("v = {}\n", myvec);
and in fact, it does print all elements (thanks to some nice behavior
by fmt)!  But this does not work as expected:
fmt::print ("v = {:.3f}\n", myvec);
fmt's tricks will print all elements, but only using the default format
spec, and the spec above applied so the "whole thing", not each element,
if you see the distinction.
So this patch sets up the custom …
> Custom fmt formatters for vector types

- .github/workflows/ci.yml
- src/build-scripts/gh-win-installdeps.bash
GHA is retiring the windows-2016 image, we won't be able to use it soon.
Also bump openexr versions in a couple places.
There's some in-progress work on a VS2022 test, but ignore that for now,
it's commented out.
> CI: Remove the windows-2016 that will be imminently removed

- src/doc/pythonbindings.rst
- src/include/OpenImageIO/deepdata.h
- src/libOpenImageIO/deepdata.cpp
- src/oiiotool/oiiotool.cpp
- src/openexr.imageio/exroutput.cpp
- src/python/py_deepdata.cpp
- testsuite/oiiotool-deep/ref/out-fmt6.txt
- testsuite/oiiotool-deep/run.py
In OpenEXROutput::write_deep_scanlines and write_deep_tiles, don't
just pass the DeepData along -- handle the case of where the DD (the
buffer the caller is presenting) does not match the data types that
you said the file is going to hold. In this case, we need to make a
local temporary DD that holds a copy of the passed-in data, but with
the formats transcoded.
Some changes to DeepData were done to support this.
> Fix writing deep exrs when buffer datatype doesn't match the file

- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
When trying to break filenames into the base name and any "RESTful"
arguments (such as "/foo/bar.exr?name=value&dog=cat"), we were
just looking for presence of the "?" to determine if it was a RESTful
thingie and using that as the split position.
But this is thrown off by an odd Windows notation where names that
start with (get this) `\\?\` somehow designate long filepaths. See
See: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation
So the solution is to change Strutil::get_rest_arguments to explicitly
check for this pattern at the start of the string.
> Fix conflict between RESTful and Windows long path notation

- src/bmp.imageio/bmp_pvt.cpp
- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- testsuite/bmp/ref/out.txt
- testsuite/bmp/run.py
There are two undocumented varieties of BMP files only written by
certain Adobe apps that we did not properly handle, identified by the
size value in their header.
This is the only explanation I could find about it:
https://web.archive.org/web/20150127132443/https://forums.adobe.com/message/3272950
Fixes https://github.com/OpenImageIO/oiio/issues/3347
> BMP files - read additional varieties

- src/ffmpeg.imageio/ffmpeginput.cpp
In FFMpegInput::close(), some of the tear-down calls would happen
regardless of if their pointers were already null. Seemed safe, but
maybe not always? So check the pointers.
Fixes #3371
> ffmpeg reader: take care against possible double free

- src/python/py_oiio.h
- testsuite/python-imageinput/ref/out-alt.txt
- testsuite/python-imageinput/ref/out-alt2.txt
- testsuite/python-imageinput/ref/out-py37-jpeg9d.txt
- testsuite/python-imageinput/ref/out-python3-win.txt
- testsuite/python-imageinput/ref/out-python3.txt
- testsuite/python-imageinput/ref/out-travis-py2.7-pybind2.3.txt
- testsuite/python-imageinput/ref/out-travis.txt
- testsuite/python-imageinput/ref/out.txt
This is necessary for dealing correctly with ICCProfile ImageSpec
attributes, which are simply arrays of uint8's.
> Python: support uint8 attributes in and out

- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Oh boy, never leave anything unbenchmarked.
Turns out the boost::algorithm functions we were relying on underneath
many Strutil "case-insensitive" comparisons were ridiculously slow.
We thought they were good enough because they allowed specification of
locale, so we could just pass the static classic locale, and so they
would be inexpensive because they didn't have to query the current
locale.  But this is wrong, they were still ghastly.
So here I rewrite Strutil::iequals, iless, starts_with, istarts_with,
ends_with, iends_with in terms of a new (internal) Strutil::strcasecmp
and strncasecmp (which underneath handle differences in platform, and
use the locale-independent versions). The net result is that most of
those case-independent comparisons speed up by a factor of
50-100x. Wow.
I …
> Speed up case insensitive string comparisons

- src/build-scripts/ci-test.bash
- src/cmake/fancy_add_executable.cmake
Cut/paste error inadvertently deleted a critical cmake line that I
wasn't intending to alter or remove, that resulted in the command line
utilities not being tagged for part of the install step. Oops!
> Fix botched build from PR 3381, command line utils not installed

- src/oiiotool/diff.cpp
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/oiiotool/printinfo.cpp
This is the first tiny step to fixing all the little things that break
in a unity build. This one is pretty small fry -- the oiiotool set of
modules only needed some minor rearrangement of header file include
order.
> Make oiiotool unity-ready

- CMakeLists.txt
- src/doc/Doxyfile
- src/include/OpenImageIO/errorhandler.h
When this symbol is defined, this marks as deprecated the ErrorHandler
class methods that use sprintf formatting notation. It's not enabled
by default, but a downstream project can define the symbol in order to
help root out any uses of the old style formatting functions, to aid
identifying and changing those spots to the new style, long before
they are truly deprecated or removed from OIIO.
This change also sets up an OIIO_INTERNAL symbol that will be present
when OIIO itself is compiling, but not a downstream project using the
OIIO headers.
> OIIO_ERRORHANDLER_HIDE_PRINTF as aid for fmt conversion

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool-subimage/ref/out-oldfreetype.txt
- testsuite/oiiotool-subimage/ref/out.txt
- testsuite/oiiotool-subimage/run.py
I realized that --attrib (and several related actions) only set the
attribute as directed for the first subimage if it's a multi-image
file (such as a multi-part exr), or all of them if the -a flag is
used.  But there was no ability to set it for a particular (non-first)
subimage, like many other oiiotool actions have the ability to do.
So in this patch, I refactor the following commands to use the
OiiotoolOp and related macros, which automatically make it responsive
to the `:subimages=` optional modifiers:
--attrib
--sattrib
--eraseattrib
--caption
--orientation
--clear-keywords
--iscolorspace
As a bonus aside, one thing this lets you do is set a different
compression method per-subimage using, e.g.,
`--attrib compression:subimage=3 dwaa:100`.
But if you set compression with `--attrib …
> oiiotool: attribute actions get subimage controls

- src/cineon.imageio/libcineon/CineonHeader.cpp
- src/cineon.imageio/libcineon/CineonHeader.h
- src/cineon.imageio/libcineon/Writer.cpp
- src/dds.imageio/squish/alpha.cpp
- src/dds.imageio/squish/colourblock.cpp
- src/dds.imageio/squish/maths.h
- src/dds.imageio/squish/singlecolourfit.cpp
- src/dpx.imageio/libdpx/DPX.cpp
- src/dpx.imageio/libdpx/DPX.h
- src/dpx.imageio/libdpx/DPXHeader.cpp
- src/dpx.imageio/libdpx/DPXHeader.h
- src/dpx.imageio/libdpx/Reader.cpp
- src/dpx.imageio/libdpx/RunLengthEncoding.cpp
- src/dpx.imageio/libdpx/Writer.cpp
- src/jpeg2000.imageio/jpeg2000input.cpp
- src/jpeg2000.imageio/jpeg2000output.cpp
Here we tackle the code that implements dpx, cineon, jpeg2000, and dds.
Most of the work is in finding violations of the "one definition rule" -- using
the same name in static scope in more than one file, but to mean different things.
For example, the dpx and cineon code both internally defined a `MAX_ELEMENTS`
macro. This is made safe by prefixing it differently for each. The other necessary
changes fall mostly similar issues.
> More work to enable unity/jumbo builds

- src/include/OpenImageIO/ustring.h
- src/libutil/ustring.cpp
- src/libutil/ustring_test.cpp
If you know the hash of a ustring, this tells you the ustring.
(Caveat: in the very unlikely chance of two ustrings having the same
hash, this will return the first one it finds in the table.)
> ustring::from_hash()

- src/doc/pythonbindings.rst
- src/python/py_imagespec.cpp
- src/python/py_oiio.cpp
py_imagespec: added get_bytes_attribute to bypass decoding as utf-8 and instead returning as a Python3 bytes object
Fixes #3395
> py_imagespec: added get_bytes_attribute to bypass decoding as utf-8

- src/libOpenImageIO/imageio_pvt.h.in
- src/libOpenImageIO/imageioplugin.cpp
Reminder: When opening a file by name, first it tries to open assuming
that the file's extension indicates the format. If that doesn't work,
it tries all known format readers to see if one will work.
This patch includes several improvements to this process and surrounding
code in imageioplugin.cpp:
* When trying all formats because the extension was wrong, instead of
traversing the input_formats map in alphabetical order of the list
of all format names + extensions, try the three most common formats
we encounter (openexr, tiff, jpeg) FIRST, then try the other formats
in alphabetical order. We do this by traversing the
format_list_vector, which contains all format names in the order
they were declared, and ensure that those common formats are
declared first. Basically, this means that if …
> Improvements in opening unknown files

- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
For C++17 and beyond (and maybe earlier in some compilers), we already
used std::gcd. Now for C++14 compilers without std::gcd, we roll our
own simple gcd implementation instead of using boost::gcd. Maybe it's
slightly slower, but this is nowhere near a performance-critical
path. It's worth it to take one more step at eliminating boost.
> Eliminate use of boost::gcd

- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/platform.h
- src/libutil/fmath_test.cpp
We have a template OIIO::bit_cast which has served us for a while, but
it turns out that C++20 has std::bit_cast which operates ALMOST the
same -- unfortunately, the tempalte arguments are reversed from the
way we did it!
So here we:
* Set up a new `bitcast<>` that works exactly like C++20 std::bit_cast.
* Implement our old bit_cast in terms of the new one, for now.
* Set up `#if` trick so that the confusing OIIO::bit_cast will be
marked as deprecated beginning with OIIO 2.5, and will be removed
entirely from OIIO 3.0. (Farther out than that, we may choose to
re-introduce bit_cast as truly being identical semantics to
std::bit_cast. But before that is possible, we need to completely
ween downstream users off the old one.)
* Took the opportunity to expand the set of compilers for which …
> New bitcast is closer to std::bit_cast

- src/cmake/compiler.cmake
- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/platform.h
- src/libtexture/texturesys.cpp
- testsuite/runtest.py
- testsuite/texture-interp-closest/run.py
- testsuite/texture-mip-stochasticaniso/run.py
The Intel OneAPI LLVM-based C++ compiler, as we download it from Intel
for our CI, bumped from 2022.0.0 to 2022.1.0.
New warning popped up -- newest Intel LLVM-based compiler warns about
overriding certain floating point math flags.
Also had to adjust thresholds on a couple texture tests that have a
few pixels change slightly due to numerical differences.
> CI: adjust to upgrading Intel Clang compiler to 2022.1.0

- .github/workflows/ci.yml
- src/build-scripts/ci-build.bash
For failed CI builds, save the cmake caches in a safe place, don't zip
them up in situ, because then when I unpack them in my build area
locally, they overwrite my working cache.
> CI improvements -- don't overwrite cmake caches

- src/include/OpenImageIO/ustring.h
- src/libOpenImageIO/formatspec.cpp
- src/libutil/argparse_test.cpp
- src/libutil/paramlist_test.cpp
- src/libutil/simd_test.cpp
- src/libutil/ustring_test.cpp
- src/testtex/testtex.cpp
fmt master seems to have just deprecated the ability for
fmt::sprintf("%s") to default to printing anything that allows stream
output. This breaks use of Strutil::sprintf formatting ustrings.
This isn't yet in any tagged release of fmtlib, but I'm trying to get
ahead of it.
The quick fix is to just change those handful of places to use
std::format style calls, which we are slowly converting to anyway.
Also throw in a fmt::formater for ustrings for good measure.
> Adjust string formatters after change in fmt master

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/testtex/testtex.cpp
The udim_lookup_mutex_pool is not necessary. Just using an atomic
pointer for udiminfo.icfile is enough.
I'm seeing about a 5-8% overall speed improvement in testtex-based
intense udim benchmarks under heavy threading, a ~2% overall
improvement in a real rendered scene that uses a bunch of udim
textures (I think there are bigger bottlenecks elsewhere that I'll
move on to next, but every little bit helps).
Some testtex enhancements coming along for the ride:
* UDIM-oriented tests (automatically decuded if the test textures
contain `<UDIM>` in their name.
* --maketests will construct random test textures and use them (handy
if you need lots of textures for a big test, but don't want to store
them). The tests are based on a file pattern using std::format-like
replacement with an index. Also, …
> UDIM speedups by eliminating mutex

- src/tiff.imageio/tiffinput.cpp
You'd think there would be no way that basic failure like this could
occur after 14 years, right?
But the TIFF reader code was a little mixed up about the fact that the
internal m_next_scanline field is relative to the starting scanline of
the image, not an absolute value. But in the case of the code that has
to deal with handling the stray scanlines at the end of a strip-read
file neglected to set it properly and the end of the stripped part.
Obviously, for TIFF files with a first scanline of 0 (the vast, vast
majority), failing to adjust by this offset doesn't matter. And also
as long as the reading continued to be strictly sequential, it also
was asymptomatic. But in the presence of certain multithreaded random
access patterns, it makes a difference. Oops.
> TIFF: fix read problem with tiff files with non-zero y offset

- src/bmp.imageio/bmpinput.cpp
Check for nonsensical image dimensions or total size before doing
buffer allocation.
Fixes #3431
> BMP: detect corrupted images

- src/bmp.imageio/bmpinput.cpp
If the BMP image we're reading declares a certain sized palette, but
then has pixels that contain values outside the range of that palette
size, we would read past the end of arrays.
Fixes #3428
> BMP: protect against corroptions with palette indices out of bound

- src/libOpenImageIO/imageinput.cpp
- src/png.imageio/png_pvt.h
- src/png.imageio/pnginput.cpp
- testsuite/png/ref/out.txt
- testsuite/png/run.py
- testsuite/targa/ref/out.err.txt
Especially for corrupt/broken files. Mostly consists of more care in
bubbling up error conditions so they can be properly handled at a
high level.
Fixes #3437
> PNG: beef up error detection and propagation

- src/include/OpenImageIO/ustring.h
- src/libutil/strutil_test.cpp
- src/libutil/ustring_test.cpp
ustring is a unique string (that lives in an internal hash table) whose
representation is the pointer to the characters that live in the table.
ustring hash is its alter ego -- it also refers to a ustring in the
internal hash table, but the representation is just the hash itself.
It presents an interface that is a subset of that of ustring, and in
many ways they can be used interchangeably.  For ustringhash,
accessing the characters requires using the hash to find the string in
the table -- which is not hard, but more expensive than accessing the
charcters with a ustring, where the representation is the pointer
directly to the characters.
For some uses where you don't need access to the characters in any
performance-critical paths, this may be a more convenient
representation.  In …
> ustringhash

- src/libtexture/texturesys.cpp
Oops, calling it "m_max_tile_channels" (the name of the member
variable) instead of "max_tile_channels" (the name of the attribute)
actually prevented properly setting or retrieving the attribute by
name.
> TextureSystem: fix typo in attribute name

- src/include/OpenImageIO/benchmark.h
More care with "forceinline" so it doesn't interfere with the
"optnone" on some platforms.
Fixes  #3421
> benchmark.h: Change DoNotOptimize declaration to not conflict

- src/include/OpenImageIO/ustring.h
This makes it easier for downstream users to test if ustringhash is
available in a particular version of OIIO.
> ustring: add OIIO_USTRING_HAS_USTRINGHASH symbol

- src/libOpenImageIO/imageioplugin.cpp
The plugin was freed before the error message printed that depends on
it.
Fixes #3452
> Fix crash when ioproxy is passed to a plugin that doesn't support it

- src/include/OpenImageIO/timer.h
- src/libutil/timer.cpp
On Linux, we'd been using gettimeofday, which gives results with usec
resolution. Switch to clock_gettime, which has nsec results.
In practice, the round trip time of a pair of "get time" system calls
is about 30-50ns in either case. But the new call at least nominally
returns ns resolution values. Another way of saying that is: the
answers we get should be more accurate with this call, but the call
itself is the same expense as before, so we should still be just as
cautious about not inserting timers around events that are so brief
that the timers themselves are going to be a significant addition to
the cost.
This only effects Linux (and maybe BSD?). On MacOS, we use
mach_absolute_time(), and on Windows we use QueryPeformanceCounter(),
so neither of those platforms is affected by this …
> Timer: use clock_gettime rather than gettimeofday

- src/make/detectplatform.mk
On Apple Silicon, `uname -m` returns `arm64`. The make platform detection script was allowing `aarch64`, so similar to that one, also allow `arm64`.
n/a (build code only)
With the change, building OIIO locally on an Apple M1 laptop does get much further into the process than before (was just bailing out immediately).
> Build: allow "arm64" arch in make

- src/idiff/idiff.cpp
- testsuite/png/ref/out.txt
- testsuite/runtest.py
* --allowfailures is a big hammer to allow a certain number of pixel
mismatches by any amount.
* Convert diff to modern std::format based output.
> idiff: add --allowfailures and convert output

- .github/workflows/ci.yml
- .github/workflows/scorecards.yml
- SECURITY.md
* Create scorecards.yml, to run OSSF scorecard to check supply chain
security issues.
* Make sure actions we use don't get write perms on our repo.
* Use harden-runner action to ensure no actions on the runner
overwrite source code or have unauthorized outgoing net connections
during the GHA run.
* Use exact SHA's for actions versions to guard against hijacked
actions repos that might try to substutite something else at the
version tag we use.
* Add a SECURITY.md detailing our security policy and the private
email address to contact to report vulnerabilities.
Learned about this from a security talk.
> CI: Security fixes

- testsuite/dds/ref/out.txt
- testsuite/dds/run.py
Somewhat in preparation of addressing #2338, this adds more images into DDS test suite. The actual images are at https://github.com/OpenImageIO/oiio-images/pull/4, this one is just using them in the test python script.
Yes, this PR is **only** about the newly added tests. Of course all the `dds` tests are failing on CI without having the new images merged into the oiio-images repository (https://github.com/OpenImageIO/oiio-images/pull/4).
> dds: Add more DDS test images

- .github/PULL_REQUEST_TEMPLATE.md
When viewing this .md file in Github UI, everything seems to work. But when creating an actual PR, the links to CONTRIBUTING and CLAs point to nothing that would exist. Looks like they try to be relative links from the "create a new PR" page. Workaround seems to be to use absolute links instead.
N/A
> PR template: fix links to work in actual PR page

- src/dds.imageio/ddsinput.cpp
Previous code was doing ioread one pixel at a time. Change it to read one scanline at a time, similar to e.g. how BMP reader does it.
On a 8192x8192 rgba8 image (256MB), on Apple M1 Max `iinfo --hash` time goes from 2.19s down to 0.65s, and is now similar to the time it takes on an uncompressed TIF (0.52s) or BMP (0.71s) image.
No need for new tests, existing DDS test coverage should be fine.
> DDS: speed up reading of uncompressed images

- src/cmake/pythonutils.cmake
- src/python/__init__.py
Python 3.8 stopped loading DLLs from PATH on Windows, meaning anything that relied on that environment for shared library resolution breaks. This PR works around that behviour by manually adding PATH back to DLL resolution using `os.add_dll_directory()` in a new `__init__.py` which just re-exports everything in the current .pyd.
The new behaviour is only enabled if the environment variable `OIIO_LOAD_DLLS_FROM_PATH` is equal to "1".
> allow loading of dlls from PATH on Windows Python 3.8+

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Will be needed in a subsequent PR to fix some safety issues revealed by clang-tidy.
> Strutil::safe_strcat

- src/include/OpenImageIO/imagebufalgo_util.h
There's no reason to expose this here.
> Remove a stray reference to half.h in a public header

- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
This is a discrete step in an attempt to wean us off of boost::filesystem
> Filesystem: provide alternate implementations of last_write_time()

- src/libutil/SHA1.cpp
- src/libutil/SHA1.h
Revealed by clang-tidy. Use length-safe versions.
Also get rid of some dead code by disabling some memory-clearing
code that we don't need (we're not using SHA-1 for cryptographic
or security reasons, just for comparing images).
> Replace unsafe strcpy/strcat in SHA1.cpp

- .github/workflows/ci.yml
- src/cmake/compiler.cmake
- src/cmake/externalpackages.cmake
- src/include/OpenImageIO/filesystem.h
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
- src/libutil/filesystem.cpp
C++17 (and/or adequately new versions of the compilers) support
std::filesystem, and in those cases we no longer need boost.filesystem.
> Build: Use std::filesystem when we can

- src/libOpenImageIO/imageio.cpp
The current limit has been already hit when AMD released second-generation Epyc processors (codename Rome) back in 2019. Top models have 64 cores per CPU, or 128 threads. This means 2 socket configuration has 256 threads.
Fourth generation Epyc processors (codename Genoa) are rumored to have 96 cores per CPU, or 192 threads. This means 2 socket configuration has 384 threads. While the CPUs have not been announced yet, it makes sense to prepare for them in advance.
This is trivial change, no tests are needed. …
> Bump maxthreads to 512

- src/cmake/Config.cmake.in
Current code assumes that CMAKE_INSTALL_INCLUDEDIR and CMAKE_INSTALL_LIBDIR has exactly one filesystem component. This is not the case on e.g. Debian, where libraries for multiple architectures are supported and standard paths are as follows:
CMAKE_INSTALL_INCLUDEDIR=include
CMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu
Fortunately the Config.cmake file is installed into a path that is itself relative to CMAKE_INSTALL_LIBDIR, so we can get CMAKE_INSTALL_LIBDIR from CMAKE_CURRENT_LIST_DIR and then get CMAKE_INSTALL_INCLUDEDIR by applying relative path from CMAKE_INSTALL_LIBDIR to CMAKE_INSTALL_INCLUDEDIR on top of that.
Fixes: c8dfbd70664a3f45dfb033bb5aa55b0e8def4c12
Tested by building Debian package and a regular build without Debian-specific settings.
have previously submitted a Contributor …
> cmake: Fix value of OpenImageIO_INCLUDE_DIR in cmake config

- src/dpx.imageio/libdpx/RunLengthEncoding.h
- src/heif.imageio/heifoutput.cpp
- src/include/OpenImageIO/filesystem.h
- src/iv/imageviewer.h
- src/iv/ivgl.h
- src/libOpenImageIO/color_ocio.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture_pvt.h
- src/libutil/filter.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
- src/term.imageio/termoutput.cpp
- src/testtex/testtex.cpp
Consistently applying override specifiers helps to ensure that functions are actually overridden when they meant to be such.
This PR does not change functionality, no testing needed
- [not needed] I have updated the documentation, if applicable.
- [not needed] I have ensured that the change is tested somewhere in the testsuite
> Fix -Wsuggest-override warnings

- src/include/OpenImageIO/unordered_map_concurrent.h
Should not have passed an argument. Went undetected for a long time
because I guess we didn't previously call the erase() method. (Until
I did when working on something unrelated.)
> Fix mistake in unordered_map_concurrent

- src/jpeg.imageio/jpegoutput.cpp
- src/libOpenImageIO/exif.cpp
- src/libOpenImageIO/iptc.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- src/openexr.imageio/exroutput.cpp
- src/tiff.imageio/tiffinput.cpp
- testsuite/oiiotool/ref/out.txt
Files that have string metadata with length 0 can cause trouble
if we aren't careful. Put in a number of protections.
> Protections against 0-length string attributes

- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/libOpenImageIO/imageioplugin.cpp
This is first of two PRs that will allow ImageInput::create(), ImageOutput::create() and similar functions that query the internal format database to be able to run concurrently. The access to internal format database has the property that it is frequently read from, but very infrequently written to. Currently only one concurrent read or write operation is allowed. However, it is safe to do reads concurrently as they do not modify the data structures. The situation could be improved by using std::shared_mutex (C++17) which allows multiple concurrent "shared" locks for reads and a single exclusive lock for writing.
The ability to do concurrent read access to the internal format database is becoming important, because servers already have 256 usable threads and access to the format database …
> Make access to imageio_mutex not recursive

- src/include/OpenImageIO/filesystem.h
The current description of IOProxy::pread() and IOProxy::pwrite() is alittle ambiguous. This commit expands the description to explicitly tell what the functions are and are not required to do.
Comment-only change, no tests are needed.
- [n/a] I have updated the documentation, if applicable.
- [n/a] I have ensured that the change is tested somewhere in the testsuite
> filesystem.h: Improve documentation of pread() and pwrite()

- src/jpeg.imageio/jpeginput.cpp
All read_native_* methods of ImageInput are required to be thread-safe with any other read_native_* call or with the varieties of read_tiles() that take an explicit subimage and miplevel parameter.
JpgInput::read_native_scanline() does a seek_subimage() call internally, so it's obviously not thread safe without additional locking.
It's not possible to write a test that reliably reproduces race conditions, so there are no new tests for this PR.
- [not needed] I have updated …
> JPEG: Fix a race condition in read_native_scanline()

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
If udimfile is null, it would get dereferenced anyway. Was missing
a `return` in that case.
While I was there, I realized that ImageCacheImpl::inventory_udim and
resolve_udim had no reason to be virtual, so I removed that
qualifier. (It was probably a cut/paste error, as the
identically-named methods in TextureSystem are virtual, on
purpose. But they don't need to be for this class.)
> Bug fix: posible null pointer dereference in inventory_udim

- src/libOpenImageIO/imageio.cpp
Incorrect use of reserve(), then writing past the end of the vector.
It should have been resize(). But it can be cleaned up even further by
using assign().
> Fix incorrect assignment of oiio_missingcolor

- src/cmake/externalpackages.cmake
- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/oiioversion.h.in
- src/include/OpenImageIO/parallel.h
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/libutil/CMakeLists.txt
- src/libutil/parallel_test.cpp
- src/libutil/thread.cpp
- src/libutil/ustring_test.cpp
- src/openvdb.imageio/CMakeLists.txt
Hide nearly all of the implementation of the parallel_for family of
methods rather than expose them as inline. This gives us more freedom
to change the implementation in the future without breaking ABI.
Deprecate the parallel methods that take task functions whose first
parameter is the thread ID. The only reason they existed is because
our cobbled together thread_pool used that in its inner workings.  But
there are good reasons why we should not expose that:
* We never used it anyway.
* It was not very useful, since sometimes it was a real thread ID, but
other times it was -1 in cases where the calling thread executed the
task directly.
* It is inconsistent with other thread pool implementations that we may
wish to try in the future.
So better just to not expose those thread IDs at all. …
> parallel.h refactoring and add support for TBB

- src/jpeg.imageio/jpegoutput.cpp
Typo, was checking XRes twice instead of XRes and YRes.
> Fix aspect ratio logic in jpeg

- .github/workflows/ci.yml
- src/build-scripts/ci-build.bash
- src/cmake/compiler.cmake
- src/libtexture/environment.cpp
- src/libtexture/texture3d.cpp
- src/testtex/testtex.cpp
Stranely, this made slightly numerically different texture test
results on icc.  Switching its math mode to precise brings it back in
line with the other compilers. The differences aren't visible, so this
isn't an issue in practice, but for tests it made it hard to compare
to reference images.
> Use imath .xyz rather than [] to fix static analysis warnings

- src/doc/idiff.rst
- src/doc/pythonbindings.rst
- src/idiff/idiff.cpp
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/python/py_imagebufalgo.cpp
- testsuite/python-imagebufalgo/ref/out-freetype2.4.11-py2.7-pybind2.3.txt
- testsuite/python-imagebufalgo/ref/out-freetype2.4.11.txt
- testsuite/python-imagebufalgo/ref/out-python2-alt.txt
- testsuite/python-imagebufalgo/ref/out-python3-freetype2.4.11.txt
- testsuite/python-imagebufalgo/ref/out-python3.txt
- testsuite/python-imagebufalgo/ref/out.txt
- testsuite/python-imagebufalgo/src/test_imagebufalgo.py
Extend ImageBufAlgo::compare() to take relative metrics, which if
nonzero check the symmetric mean relative error, in addition to the
current absolute error. To be formal, this means that a value
comparison will fail if
abs(A-B) > failthresh && abs(A-B)/((abs(A)+abs(B))/2) > failrelative
Setting the failthresh to 0 is equivalent to only checking relative
error, and setting failrelative to 0 is equivalent to the (previous
behavior) of checking only absolute error.
The idiff utility is extended to take new `-failrelative` and
`-warnrelative` command line arguments.
The hope is that there are various kinds of image comparisons within
tolerances -- like we frequenty use for unit tests, shader
verification, etc. -- where this metric is more helpful than absolute
error.
> Relative image compare

- src/hdr.imageio/hdrinput.cpp
Fix vector-subscript-out-of-range on MSVC Debug builds
Also fixes potential problems with >31bit pixelsizes
Verified in our own testsuites. Happens on every .hdr file that is being read
- [X ] I have read the [contribution guidelines](https://github.com/OpenImageIO/oiio/blob/master/CONTRIBUTING.md).
- [X ] If this is more extensive than a small change to existing code, I
- [X ] I have updated the documentation, if applicable.
- [X ] I have ensured that the change is tested …
> Fix vector-subscript-out-of-range on MSVC Debug builds

- src/cmake/modules/FindFFmpeg.cmake
Fix CMake detection of FFmpeg 5.1, which refactored location of libavcodec major version in https://github.com/FFmpeg/FFmpeg/commit/f2da2e1458b76a1d6c068673430b46cf2850bc51. Seen in Homebrew https://github.com/Homebrew/homebrew-core/pull/107244
Only fixes detection and I confirmed successful build. Not sure if any breaking changes in API, but at least still compiles with newer FFmpeg.
Original cmake output for master branch with FFmpeg 5.1:
```console
❯ PKG_CONFIG_PATH=/usr/local/opt/ffmpeg/lib/pkgconfig cmake -S. -Bmaster 2>/dev/null | grep -i ffmpeg
-- FFmpeg 1.0 is outside the required range 3.0...
-- FFmpeg library not found
--     Try setting FFmpeg_ROOT ?
-- FFmpeg not found: ffmpeg plugin will not be built
```
And same with changes:
```console
❯ …
```
> cmake: fix ffmpeg 5.1 detection

- .github/workflows/ci.yml
- src/build-scripts/install_homebrew_deps.bash
Homebrew recently upgraded its default python to 3.10, which broke our Mac CI
> CI: For Mac, test python 3.9 for MacOS11, and 3.10 for MacOS12.

- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
The implementation of boost::filesystem::path::extension() and the
equivalent for std::filesystem disagreed about the result of
extension(".foo"). C++17 correctly considers ".foo" to have no
extension.
> Make Filesystem::extension work identically for C++14 and 17
