- src/dds.imageio/dds_pvt.h
- src/dds.imageio/ddsinput.cpp
* For 2-channel DDS files, label them as Y,A if the flags indicate
luminance and/or alpha, otherwise label them as R,G.
* Do not set "oiio:BitsPerSample" for cases where the dds.fmt.bpp field
is not assumed to be valid. MS docs say it's valid only if the flags
field indicates RGB, LUMINANCE, or YUV types.
> DDS improvements

- src/jpeg.imageio/jpegoutput.cpp
JFIF/JPEG files only support 1 and 3 channels. For > 3 channels, we
had just been discarding the extra. For 2 channels, we had been
discarding the second, but maybe that's not always right. Try to
distinguish between files whose names appear to be YA -- in which case
output the Y as grayscale (JFIF has no way to represent alpha anyway),
and other cases which we now promote to RGB and just make B be black.
> Improve JPEG output of 2-channel images

- src/doc/idiff.rst
- src/doc/igrep.rst
- src/doc/iinfo.rst
- src/doc/maketx.rst
- src/doc/oiiotool.rst
- src/idiff/idiff.cpp
- src/igrep/igrep.cpp
- src/iinfo/iinfo.cpp
- src/include/OpenImageIO/argparse.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/oiioversion.h.in
- src/iv/ivmain.cpp
- src/libOpenImageIO/imageio.cpp
- src/libutil/argparse.cpp
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
* ArgParse::add_version(str) tells ArgParse the version string, and
automatically adds an option --version that prints the version string
and exits.
* Add this to oiiotool, iinfo, igrep, iv, maketx.
* OIIO::getattribute("version") retrieves the version string.
> Add --version to all the things

- src/png.imageio/png_pvt.h
- src/png.imageio/pngoutput.cpp
My change consist of additional `setjmp()` that catch errors on each step of PNG metadata writing to generate an accurate error message and avoid a `longjmp()` that lead to undefined behaviors and the following buggy behavior.
A project of mine read images and write a resized version back in PNG reusing the `OIIO::ImageSpec` of the loaded image. The image below (https://www.furaffinity.net/view/31141327/) have an ICC profile that libpng dislike and it generates an error in [`png_set_iCCP` called from `PNG_pvt::write_info`](https://github.com/OpenImageIO/oiio/blob/a14523e9b754beb8e4a71e466791b429f6f3d233/src/png.imageio/png_pvt.h#L597) that perform a `longjmp()` inside the [previous call of `PNG_pvt::create_write_struct`](https://github.com/OpenImageIO/oiio/blob/a14523e9b754beb8e4a71e466791 …
> Added checks in PNG_pvt::write_info (fix SEGFAULT after "PCS illuminant is not D50" libpng error)

- src/dds.imageio/ddsinput.cpp
Reading uncompressed scanlines would copy 4 bytes from each pixel into
an int and then decode the bits, incrementing where it was reading
from by Bpp bytes each time.  But when Bpp == 3, the last pixel of
every row would therefore read an extra byte past the end of the heap
storage. Allocation padding would in practice keep it from crashing,
and that meaningless extra byte was not used in the decode because it
knew it only needed the first 3 of the integer. But found by address
sanitizer!
> Fix heap overflow in DDS input

- src/include/OpenImageIO/fmath.h
`DASSERT_MSG` is was used with the format specifier `%zd` which is unsuitable for either of the options that `oiio_span_size_type` could evaluate to. This PR should fix it for both cases (`OIIO_SPAN_SIZE_IS_UNSIGNED` is defined and not defined) by using the appropriate format specifier in each case.
Compiler warning is now gone.
> Fixes a warning from an unsuitable format specifier

- CMakeLists.txt
Rather than specify the version in the usual project() statement,
project (OpenImageIO VERSION 2.5.0.0 ...)
this patch decouples it
set (OpenImageIO_VERSION "2.5.0.0" CACHE STRING "Version")
project (OpenImageIO VERSION ${OpenImageIO_VERSION} ...)
thus allowing the possibility of overriding the version number at build confuguration time (`cmake -DOpenImageIO_VERSION=3.1.4.1`).
This should be used with extreme caution. Probably never used by most people. I don't need to describe all the ways that things can go sideways if you make your build of x.y.z.w actually be arbitrarily different from the x.y.z.w that everyone else uses and that is documented.
That said, there are two scenarios I have in mind for which this ability is very useful:
1. Sometimes, we add or deprecate API features "in …
> Build: Make the version number be a cmake cache variable

- src/cmake/Config.cmake.in
This fixes builds in projects that compile OpenImageIO as static libraries and don't themselves depend on the image libraries used by OpenImageIO such as PNG, JPEG or TIFF.
When OpenImageIO is built as a static library its targets have e.g. PNG::PNG among INTERFACE_LINK_LIBRARIES. If the including project does not itself depend on PNG, the following error would be observed:
```
Target "<...>" links to target "PNG::PNG" but the target was not found.
Perhaps a find_package() call is missing for an IMPORTED target, 
or an ALIAS target is missing?
``` …
> cmake: Add library dependencies in Config.cmake.in when building static libs

- src/include/OpenImageIO/strutil.h
- src/libutil/filesystem.cpp
- src/libutil/plugin.cpp
- src/libutil/strutil.cpp
- src/raw.imageio/rawinput.cpp
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
- src/zfile.imageio/zfile.cpp
* Add `Strutil::utf16_to_utf8(const std::u16string& utf16str)`. This is subtly different from our existing utf16_to_utf8() that takes a std::wstring, because wchar_t is not the same on all platforms.  If it really and truly is utf16-in-char16_t, you need this and can't use the utf-in-wchar_t which may be 32 bit chars.
* Add `Strutil::utf8_to_utf16wstring` (identical to the old utr8_to_utf16) to make it more self-documenting as returning a utf16-encoded wstring and NOT a u16string. Note that wchar_t is not necessarily char16_t on all platforms (it is on Windows, but it's 32 bits on Linux).
* Deprecate the ambiguously named utf8_to_utf16 for OIIO >= 2.5 and remove it for OIIO >= 3.0.
> Strutil utf conversion improvements

- src/doc/builtinplugins.rst
- src/doc/stdmetadata.rst
- src/include/OpenImageIO/tiffutils.h
- src/jpeg.imageio/jpeginput.cpp
- src/jpeg2000.imageio/jpeg2000input.cpp
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/icc.cpp
- src/openexr.imageio/exroutput.cpp
- src/png.imageio/png_pvt.h
- src/psd.imageio/psdinput.cpp
- src/tiff.imageio/tiffinput.cpp
- testsuite/jpeg2000-j2kp4files/ref/out-alt.txt
- testsuite/jpeg2000-j2kp4files/ref/out-spinux.txt
- testsuite/jpeg2000-j2kp4files/ref/out.txt
- testsuite/oiiotool-attribs/ref/out-jpeg9d.txt
- testsuite/oiiotool-attribs/ref/out.txt
- testsuite/psd/ref/out.txt
For a while, we have found embedded ICC profiles in TIFF, JPEG, JPEG-2000, PNG, and PSD (PhotoShop) files and store them in the metadata as a byte array with the name "ICCProfile".
With this patch, we further add the facility of parsing the binary ICC profile data to extract a number of other fields that we add to the ImageSpec metadata so that "oiiotool -info -v" or "iinfo 'v" will print this info.
Important caveat: You can read this for informational purposes, but changing it (e.g. with spec.attribute()) does not change the contents of the ICCProfile byte array, which is still the canonical ground truth of the profile. You have to replace the "ICCProfile" byte array to actually change the profile.
> Extract metadata from embedded ICC profiles.

- src/cmake/testing.cmake
- src/python/py_oiio.h
- testsuite/python-imagecache/ref/out.txt
- testsuite/python-imagecache/run.py
- testsuite/python-imagecache/src/test_imagecache.py
Just a couple missing pieces were preventing getattribute() from retrieving attributes that were stored as int64 or uint64. That doesn't come up very often, but one place is retrieving certain statistics that use 64 bit counters. (This comes up in ImageCache, among other places.)
While we're at it, there was no existing test dedicated to the python binding of ImageCache. So to add these getattribute calls, I made one.
There is an important caveat about ImageCache.getattribute(): In this process, I discovered that the flavor of IC.getattribute(name) where you only pass the name is BROKEN, and will always return None. You MUST use the form where you pass the type, like
x = ic.getattribute("foo", "int")
This is unfortunate and not very Pythonic, but it is the workaround for now. I will …
> Python: add ability to getattribute of int64 and uint64 data

- src/cmake/Config.cmake.in
TBB::tbb is added as a library dependency via TARGET_NAME_IF_EXISTS. Therefore if an executable links OpenImageIO static library without the executable itself depending on TBB, then TBB will not be linked in and result in link time errors.
- [not needed] I have updated the documentation, if applicable.
- [not needed] I have ensured that the change is tested somewhere in the testsuite
> cmake: Find TBB dependency in Config.cmake.in when building static lib

- src/cmake/compiler.cmake
Currently when cross-compiling for Android build fails due to usage of TRY_RUN(). In the particular case it tries to figure out whether atomics can be used without the libatomic library.
Fortunately we don't need this check because on Android NDK atomics are built-in and libatomic.so is not present. Only static dummy libatomic.a exists for compatibility with -latomic flag.
- [not needed] I have updated the documentation, if applicable.
- [not needed] I have ensured that the …
> Build: Fix cross-compiling on Android failing due to -latomic check

- src/libutil/sysutil.cpp
iOS and similar Apple platforms only support executing single process per app. Calling std::system() there fails at compile time.
> Fix build on iOS by not using std::system()

- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/texture.h
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
- src/python/py_imagecache.cpp
- src/python/py_texturesys.cpp
- testsuite/python-imagecache/ref/out.txt
- testsuite/python-imagecache/src/test_imagecache.py
- testsuite/python-texturesys/ref/out-windows.txt
- testsuite/python-texturesys/ref/out.txt
- testsuite/python-texturesys/src/test_texture_sys.py
ImageSpec and ParamValueList have had (since 2.1) a getattributetype() method, which simply returns the TypeDesc of the named attribute, or TypeUnknown if no such attribute exits. This goes along well with the related getattribute() and attribute() family of methods.
The getattribute() method was not present in ImageCache and TextureSystem, despite their having very similar
getattribute()/attribute() interfaces.
A recent issue made me realize that in the Python bindings, the IC and TS bindings for `getattribute(name)` did not work properly, always returning None, and *required* you to use the full `getattribute(name,type)` variety where you have to supply -- and already know -- the type. This isn't especially Pythonic, where you should just be able to ask by name and get a polymorphic …
> IC and TS getattributetype() -- BREAKING CHANGE

- CMakeLists.txt
- RELEASING.md
Adapted from the similar document I wrote for OSL.
This serves both as a checklist for me to make sure I don't miss any steps during a release, but also so that other people could take over release procedures if necessary or desired.
I also rearranged the order of some lines in CMakeLists.txt for clarity (but did not change the logic).
> Add RELEASING.md to document our release procedures

- src/libutil/thread.cpp
This was part of a set of obsolete calls where we recently removed the implementations, but for link compatibility, made matching shim calls and wrap the modern versions. But I missed one case.
> Reinstate missing (obsolete) parallel_for_chunked_2D variant

- src/cmake/compiler.cmake
Cmake-generated visual studio project files were using just one CPU core for all the compilation, which is not terribly fast. Add the `/MP` option so that it compiles separate .cpp files in parallel. On my (16 core, 32 thread) machine this makes a Release build of OpenImageIO.lib go from 136 sec down to 30 sec.
N/A
> Build: enable parallel compilation when using visual studio

- .github/workflows/analysis.yml
- .github/workflows/ci.yml
- .github/workflows/scorecards.yml
- src/build-scripts/ci-build.bash
* Refactor the clang-format job to be part of the aswf batch of jobs rather than separate (reduces redundant logic in the workflow file).
* Give proper names to distinguish the two Mac jobs' artifacts for broken builds.
* Revise scorecard workflow triggers: no need to run weekly, and run on push only to the main repo, no reason to run on forks.
> CI: improvements and minor refactoring

- src/dds.imageio/dds_pvt.h
- src/dds.imageio/ddsinput.cpp
- src/doc/builtinplugins.rst
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageio.cpp
- testsuite/dds/ref/out.txt
- If a DDS pixel format header contains "this is a normal map" flag set, then handle that properly (#3525):
- For a DXT5, this means it's a "DXT5nm" format. Normal X & Y components are in green and alpha channel respectively. Compute Z component from those, and the result is a 3-channel tangent space normal map.
- For ATI2/BC5 format that also has a "normal map" flag set, compute the Z component automatically too, and result is a 3-channel image. However a bunch of ATI2/BC5 normal maps out there in the wild do not have that bit set, so also have a global "dds:bc5normal" attribute to optionally turn this on.
- Fix support of R10G10B10A2 format - was producing garbage data due to code assumption that truncation down to 8 bits never needs to happen.
- Fix bit expansion ("too dark") of very …
> DDS: various improvements

- .github/workflows/ci.yml
- src/cmake/compiler.cmake
Add a new build-time cmake cache variable: FORTIFY_SOURCE
Default to empty, but can be set to 1, 2, or 3, corresponding to setting the _FORTIFY_SOURCE macro available in recent versions of clang and gcc. (I'm not sure exactly which minimum compiler version is needed for each fortification level, except that for level 3, gcc must be 12+.)
Fortification involves replacing several "unsafe" memory-related functions such as memcpy, memset, strcpy, etc, with special versions that do bounds checking, aided by some compiler smarts for understanding the likely bounds of different buffers. If I understand correctly, at level 2 it can figure out bounds of constant-sized arrays, and at level 3 it can figure out certain dynamic cases as well.
There are two use cases for this:
1. For our own CI, this …
> Build/security: Try FORTIFY_SOURCE

- src/include/OpenImageIO/imagebuf.h
This was causing build issues on MinGW.
Fixes #3576
> Remove incorrect OIIO_API from inline method declaration

- src/dds.imageio/ddsinput.cpp
- testsuite/dds/ref/out.txt
- testsuite/dds/run.py
Makes A8, L8, L8A8 formats actually work now. While developing #3573 at one time I had them working properly, but then
while fixing the address sanitizer failure for 3-channel formats I botched them again. Note to self: never again do a "yeah I'll add tests later", since if I had all of them running all the time this would not have happened. 🤦
Extend test coverage for more formats & channel size cases. With more test images recently added (https://github.com/OpenImageIO/oiio-images/pull/5), start using them for DDS tests. This covers now:
- Alpha, Luminance and Alpha+Luminance formats,
- RGB formats with rarer channel sizes (rgb10 a2, r3g3b2),
- Several "broken" DDS file cases
- Removed usage of sample-DXT1 since it is well covered by others.
have previously submitted a Contributor …
> DDS: alpha/luminance format fixes, add & enable more tests

- src/oiiotool/oiiotool.cpp
Suggested by SideFX: explicitly shut down the OpenEXR thread pool before exiting oiiotool, because sometimes on Windows it seems to hang otherwise. A better solution is probably possible on the OpenEXR side, but I don't know what it would be. (And in any case, we'd still need to do this be be well behaved when using OpenEXR versions earlier than where a fix might land.)
Solution tracked down by Edward Lam.
> oiiotool protect against OpenEXR thread deadlock on Windows

- src/dds.imageio/ddsinput.cpp
Comparing the time it takes to load DXT/BCn compressed DDS images via OIIO, I noticed that it's several times slower than in another codebase (Blender). So I started profiling, and fixing some low hanging fruit.
- After decoding a BCn block (always 4x4 pixels), it was written into destination image using quite many branches in the innermost loop. Now it still takes care of not writing outside of a destination image that might not be multiple-of-4 in size, just with way fewer branches.
- BCn decompression is multi-threaded via `parallel_for_chunked`, using at least 8 block rows per job (i.e. 32 pixel rows). This is similar to internal multi-threading done by EXR or TIF readers.
- Avoid one case of std::vector resize (which clears memory) followed by immediate overwriting of that buffer …
> DDS: optimize loading of compressed images (3-5x)

- src/build-scripts/build_libtiff.bash
Something changed in libtiff master and it doesn't build shared libs by default, breaking our "bleeding edge" CI test. So when we build it, be sure to ask for it. It can be overridden in build_libtiff by invoking it with env variable `LIBTIFF_BUILD_SHARED_LIBS=OFF`.
> CI/build: build_libtiff.bash should be sure to build shared library

- src/oiiotool/oiiotool.cpp
In some cases (at least on Windows, with static linking) the oiiotool main returns zero, but the full process returns 3 error code due to abort() being called. And that is called because a global shared image cache is already destroyed, but the image references from another global (Oiiotool itself) try to use it, get a call into a "pure virtual function" stub that is put by MSVC C runtime into a destroyed object vtable, and that ends up in an abort().
Work around that by making sure various member variables holding ImageRecRef are cleared before main() finishes and global destructors are called.
N/A -- but it does make running OIIO test suite locally much easier for me. Previously python runners that were launching oiiotool were getting exit code 3 when "everything was fine", so I had to …
> oiiotool: work around static destruction order issue (#3295)

- src/psd.imageio/psdinput.cpp
The code assumes "char" is "signed char" (as on x86), but on ARM "char" is "unsigned char". The local cast was the least intrusive solution, one could also change the signature of that function and cast in the caller ...
Verified with a proprietary test image. I'd guess that the OIIO testsuite should uncover the problem when run on ARM.
> Fix PSD import on ARM

- src/bmp.imageio/bmp_pvt.cpp
- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- testsuite/bmp/ref/out.txt
- testsuite/bmp/run.py
16 bit per pixel (e.g. 555, 565, 444) formats probably have never worked. One part of the code was assuming 5 bits in the mask, another was shifting by 4 bits, and the 16-bit pixel fetch code was reading just one byte. Fixes #2808.
The test suited added back in #2976 already had a `TODO: seems broken: g16bf555.bmp, g16bf565.bmp, g16def555.bmp` comment, which is exactly 16 bpp test cases. So I've uncommented them here, and made them work.
Also removed one `g32bf.bmp` from the tests lists; it was listed there twice (looked more like a copy-paste accident than on purpose).
employers might think my programming belongs to …
> BMP: fix reading 16bpp images (#2808)

- src/include/OpenImageIO/platform.h
Using almost any OIIO header (e.g. `imageio.h`) includes `platform.h`, which on Windows includes `<windows.h>`. That IMHO is "not ideal at all", primarily because windows headers are fairly terrible in what they hijack as preprocessor symbols, that often clash with sensible things used by other code.
The most famous ones being them defining `min` and `max`, but there are many others. Now, I tried removing inclusion of `<windows.h>` from public OIIO headers, and that _almost_ works, except for the usage of `YieldProcessor()` from an inline function in `thread.h`, which is hard to remove in a clean way.
So instead of that, here's a much smaller proposal: in addition to defining `NOMINMAX` (salvages `min` and `max` symbols) and `WIN32_LEAN_AND_MEAN` / `VC_EXTRALEAN` (salvages `small` …
> Windows: fewer windows.h includes from platform.h

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/thread.h
- src/include/OpenImageIO/timer.h
- src/libutil/filesystem.cpp
- src/libutil/plugin.cpp
- src/libutil/strutil.cpp
- src/libutil/sysutil.cpp
- src/libutil/thread.cpp
- src/libutil/timer.cpp
Including windows.h leads to a lot of possibly common names being "taken", mostly by preprocessor defines. Some of these are possible to turn off (like "max" and "min" by defining "NOMINMAX" before including <windows.h>). But many others are not possible to turn off, e.g. "near" and "far" just get defined to nothing, preventing from using variables named like that.
Additionally, includes have a cost, and while <windows.h>, being a C header does not have expensive language constructs that would slow down compilation a lot, it's still something close to 100k lines of preprocessed code to wade through.
Now, only the OIIO implementation .cpp files that actually need <windows.h> include it (all of them under "libutil").
There were two exceptions:
1) thread.h `pause()` implementation uses …
> Windows: stop including <windows.h> from public OIIO headers

- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/ustring.h
- src/libtexture/imagecache_pvt.h
- src/libutil/ustring_test.cpp
I realized that the recently added ustringhash class is confusingly similar to the (obscure, barely used, mostly forgotten) ustringHash functor. But also ustringHash doesn't need to exist, because it's equivalent to `std::hash<ustring>`, if we define it. So now we do define it, and also `std::hash<ustringhash>`, and deprecate ustringHash, to be removed entirely for 3.0.
Also, add a ustring ctr from ustringhash (explicit only for now), and `operator<` for ustringhash.
Finally, modernize a few places we still used `(void)` to just `()`.
> ustring hashing improvements

- src/include/OpenImageIO/simd.h
- src/libOpenImageIO/imageio.cpp
Related to points raised over at #3268, this improves NEON coverage a bit. It already works "out of the box" (at least when building on an Apple Silicon, using all default cmake options), but a bunch of functions were missing native NEON implementations. Also `oiio_simd_caps()` did not indicate in any way that NEON SIMD is actually compiled in.
* Use hardware float<->half conversion (similar to F16C on Intel)
* Use hardware sqrt
* Use horizontal adds in more places ("reduce_add")
* Equivalents of _mm_movemask_ps for NEON in vbool4
* Other smaller bits & bobs
None of ARM platforms are tested on Github CI here. I manually ran various `_test` executables produced by a local build before & after the changes, and everything is the same correctness wise.
Testing on Apple M1 Max, Release build, …
> SIMD: extend NEON coverage, and include neon in oiio_simd_caps

- sonar-project.properties
- src/build-scripts/ci-coverage.bash
- src/iff.imageio/iff_pvt.h
- src/python/py_oiio.cpp
* Protect against 0-sized allocation
* Exception safety in IffOutput destructor
* Using sonar.coverage.exclusions as a better way to exclude files from coverage analysis
* Null pointer safety
> Static analysis related fixes

- src/cmake/testing.cmake
On any one platform, our testsuite was only testing the old C++ or the new C core exr implementations.
Rig it to run the openexr-oriented tests twice -- once in each state (when using OpenEXR new enough to support the core library).
Doing this cleanly required adding SUFFIX and ENVIRONMENT optional parameters to the oiio_add_tests utility macro. Once that was added, the texture batch testing could be implemented that way as well, removing a bunch of hackier special purpose code.
> Testing: test both openexr old and core versions

- src/cineon.imageio/CMakeLists.txt
- src/cineon.imageio/cineoninput.cpp
- src/cmake/testing.cmake
- src/dpx.imageio/dpxinput.cpp
- testsuite/cineon/ref/out.txt
- testsuite/cineon/run.py
* Add a test for cineon -- we never directly tested it before
* Don't compile code used only for writing. We don't supporting writing cineon, so there is no point compiling the cineon module used only for writing.
* And of course, once cineon was in the testsuite, we immediately found a problem via the sanitizers! So fix buffer overflows when reading FilmEdgeCode in Cineon.  (And clean but equally sloppy, but not buggy, code in DPX as well.)
> Improve cineon build and test

- sonar-project.properties
It's not really "our code", and we use very little of that file, so it's not helpful to include it in coverage or other analysis.
> CI: Sonar analysis should exclude stb_sprintf.h

- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/ustring.h
- src/libutil/ustring.cpp
ustring::hash() and the representation of ustringhash were size_t, which might be 32 bits on some platforms. But we really would prefer ustrings hash to 64 bits, to greatly reduce the chance of hash collisions.
* Add strhash64() which is like strhash() but guaranteed to be a 64 bit value (returning uint64_t instead of size_t -- though note that these are the same on 64 bit CPUs).
* ustring::hash() and ustringhash::rep_t are now uint64_t.
* Note that std::hash(ustring) and std::hash(ustringhash) are still size_t, per the C++ definition of std::hash. So ustring::hash() may have more bits than std::hash(ustring) on 32 bit platforms.
This will NOT be backported to the release branch, since it changes ABI on 32 bit platforms.
> Ensure that ustring hashes are 64 bits

- src/build-scripts/ci-test.bash
- src/oiiotool/oiiotool.cpp
Add a hidden --unittest command to oiiotool, only functional for Debug builds, which enables additional testing of internal utility funcions and other things that are difficult to fully exercise in the testsuite from normal oiiotool commands (could be done, but would take tons of additional tests to get into particular deep edge cases).
Prototype by adding unit tests for scan_box. More will be added later now that the mechanism exists.
Simplify string_to_dataformat
Make sure to use --list-formats and --runstats during testing.
> oiiotool: Add unit tests, minor internals utility refactoring

- testsuite/oiiotool-control/run.py
- testsuite/runtest.py
This test was taking almost 30 seconds to run, without a lot of images being read or written. Turns out it was just a large number of separate oiiotool invocations, and the overhead of all those shells and programs launched adds up. Most of them were just firing up oiiotool for the sake of doing an `--echo` to print things. A little bit of restructuring to make fewer oiiotool invocations (each one doing a bunch of echo commands, each testing a different thing) cuts the time for the whole test by 50%.
I also made the runtest.py script allow certain test debugging by letting a test set the `wrapper_cmd`, and if so, will prepend every oiio utility launch with it. For example, a test could say `wrapper_cmd='time'` to time every command.
> Testing: optimize oiiotool-control test

- INSTALL.md
I recently wrote down how to build OIIO from source for myself (https://gist.github.com/aras-p/6497703c9b52f67761e6191343e43f7b), and maybe a slightly cleaned up version would be good to put into actual docs.
N/A
> Docs: write Windows build instructions

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
The existing syntax `TOP.name`, if the name wasn't found, produced an error.
This PR adds another syntax: `TOP[name]` which is identical if the named metadata is found. But if not found, this syntax just evaluates to the empty string, with no error. Both are useful, in different situations.
> oiiotool: New metadata expression syntax

- sonar-project.properties
Because we're not the originators of the code and we use only a tiny subset of what's in those files.
> CI: eliminate xxhash and farmhash code from coverage analysis

- testsuite/oiiotool-attribs/ref/out-jpeg9d.txt
- testsuite/oiiotool-attribs/ref/out.txt
- testsuite/oiiotool-attribs/run.py
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
- testsuite/oiiotool/run.py
* oiiotool tests for expressions var() and getattribute()
* Make sure we test oiiotool IMG[] expressions and several specific special attributes to retrieve.
* Add coverage of oiiotool --keyword and --clear-keywords
> Improve oiiotool test coverage

- src/include/OpenImageIO/ustring.h
- src/libutil/ustring_test.cpp
Also, change `operator<<` to output the string, not the hash itself. These changes help push us more toward the original intent of ustringhash being a drop-in replacement for ustring, any time it's more desirable to be using the hashes rather than the pointers.
> Custom fmt formatter for ustringhash prints the string, not the hash

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/libutil/filesystem_test.cpp
* Add an optional size parameter to read_text_file to limit the maximum size that will be allocated and read (default to a limit of 16MB).
* New read_text_from_command, similar use to read_text_file, but reads from the console output of a shell command.
> Strutil read_text_from_command, and limit size of read_text_file

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil_test.cpp
It's similar to trim_whitespace, but returns the trimmed result, rather than operating in-place on a `string_view&`.
Also add unit testing of trim_whitespace and trimmed_whitespace
> Strutil: trimmed_whitespace

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
* Add OIIO::getattribute() queries for "font_list", "font_file_list", and "font_dir_list", which are, respectively, the lists of fonts that were found, the list of font files (full paths), and the list of directories it searched.  All return a single string that is a semicolon-separated list of the items.
* As a consequence of the new attributes, if you are curious to see the full inventory of fonts it can find, you can just query the attribute:
oiiotool --echo "{getattribute(font_list)}"
* Some refactoring of the font inventory process (in imagebufalgo_draw.cpp) was necessary to achieve this.
* We now search for ".ttc" (TrueType collection) files, which we didn't notice before.
* We now search explicitly in share/fonts/OpenImageIO, which we neglected to do before, but found those fonts …
> Refactor font searching and add font getattribute queries

- src/libOpenImageIO/maketexture.cpp
Make extra sure to clear the oiio:ConstantColor, oiio:AverageColor, and oio:SHA-1 metadata when writing textures, if those things are not going to be set.
> maketexture: Ensure proper setting of some metadata

- src/doc/oiiotool.rst
- src/libutil/paramlist_test.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- src/oiiotool/printinfo.cpp
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-copy/run.py
- testsuite/oiiotool/run.py
It surprised me a little to realize that --printinfo prints the current spec of the top image (I mean, duh), but that may not match what you'd get with `oiiotool -info -v`, which prints the data about each file as it's read from disk, inasmuch as the "current" spec reflects the in-memory representation. So, for example, it might say the image is float, because oiiotool tends to store everything in-memory as float, rather than uint8 of the disk file.
So these changes help fix this oddity and other ambiguities I realized follow:
* Give --printinfo an optional modifier `:native=1` that will print the native (from the original file) info, if that's what you need, rather than the up-to-the-moment in-memory data.
* Also add --printinfo optional modifiers `:verbose=` and `:stats=`.
* Expression …
> oiiotool: --printinfo improvements to fix mem vs file ambiguities

- src/build-scripts/ci-test.bash
- src/doc/oiiotool.rst
- src/include/OpenImageIO/unittest.h
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
* Test oiiotool control flow syntax mistakes
* Test oiiotool --set with array of strings
* oiiotool: better adjust_geometry unit testing
Helper utility additions:
* oiiotool --no-error-exit
`--no-error-exit` causes an error to not exit immediately, but rather to try its best to continue execuing command line operations. Use with caution! This is mainly for unit tests and debugging.
`--unittest` also turns this on automatically, so that tests that are probing failures don't cause an exit.
* unittest.h: If OIIO_UNIT_TEST_QUIET_SUCCESS is defined, don't print anything extra for unit test success
> Analysis: more test related fixes to try to increase code coverage

- .github/workflows/analysis.yml
- .github/workflows/ci.yml
- .github/workflows/scorecards.yml
Changes:
* Scorecards and analysis -- allow newly launched job to cancel running old job from the same PR.
* Scorecard only runs on main repo, no need to run on forks.
* Nightly CI only runs on main repo, no need to run on forks.
> CI: adjust when workflows are run to cut needless CI runs

- src/build-scripts/ci-test.bash
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-copy/run.py
- testsuite/oiiotool-subimage/ref/out-oldfreetype.txt
- testsuite/oiiotool-subimage/ref/out.txt
- testsuite/oiiotool-subimage/run.py
* Add casual tests of oiiotool with no args (print brief usage message) and when an unknown command.
* Also changed the meaning of -q (quiet mode) to be more quiet -- in particular, not to print the full help message for errors when quiet mode is used, only print the error.
* oiiotool test sequence errors.
* Test (and fix) --selectmip and --subimage with out of range indices
> oiiotool testing and minor subimage/miplevel fixes

- .github/workflows/analysis.yml
- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
- src/libutil/ustring.cpp
- src/libutil/ustring_test.cpp
Better coverage of edge cases for escape_chars/unescape_chars, stoi hex conversion, strtod, stod, freestanding c_str(), parse_nested failure cases, base64_encode, debug.
> Testing: Additional Strutil tests

- CMakeLists.txt
Kai Pastor (@dg0yt) made an important observation that the way I recently made OpenImageIO_VERSION be a cache variable (#3549) might lead to unexpeted behavior by inadvertently retaining a version number upon recompiles if the cache itself was not cleared, and this can happen unexpectedly even when the user isn't trying to override the version.
This patch changes the behavior as follows:
You must use the special `-DOpenImageIO_VERSION_OVERRIDE=...` to override the version.
* if you do so, you are playing with fire and get what you deserve if you misuse it or change branches and don't remember to clear the cache.
If you do a normal build (without _trying_ to override the version),
* you will get the real version number because it IS NOT cached
* if you switch branches, you'll always get …
> CMake: Adjust how version overrides work

- src/doc/oiiotool.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/color.h
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/color_ocio.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_imagebufalgo.cpp
> ociodisplay gets an inverse control

- src/include/OpenImageIO/strutil.h
We use this all the time in our internals, and I'm tired of having to write Strutil::print. Too verbose. By putting it in the main OIIO namespace, OIIO internals can reference as simply print(), and external users now have a choice of saying Strutil::print() or OIIO::print().
> Expose OIIO::Strutil::print in the main OIIO namespace

- src/build-scripts/gh-installdeps.bash
Lately, it has been experiencing intermittent availability problems that causes our CI to fail while setting up dependencies.
What happens if we don't use the problematic ubuntu-toolchain-r at all?
Nothing, it seems. So eliminate it.
I think that once upon a time, it was necessary to add this repo to get certain new packages? But maybe they are mainstream enough now that it's not necessary to add this repo? In any case, it doesn't seem to hurt anything, it's one less moving part that can't fail if it's not there.
> CI: No longer add the ppa:ubuntu-toolchain-r/test repository

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libtexture/imagecache_pvt.h
I uncovered a very subtle problem that can happen with the interaction between ImageBuf, using an IOProxy, and the underlying ImageCache. Remember that when using an IOProxy, it is critical that the lifetime of the proxy outlasts any ImageInput, ImageBuf, or ImageCache that was told about it.
Consider the following code:
IOProxy proxy(...);   // temporary proxy in this local scope
ImageBuf A ("foo.exr", 0, 0, proxy);
We've set up an ImageBuf that will read from an IOProxy.  Behind the scenes, it made an ImageCache entry that remembers the IOProxy, as it has to, since it needs to use that proxy for subsequent reads. Now we read the image, and we use the `force=true` parameter to force an immediate read of the file:
A.read (0, 0, true);
It reads from the proxy. But the IB and the underlying …
> ImageBuf+IOProxy vs ImageCache subtle fixes

- src/zfile.imageio/zfile.cpp
When writing a zfile, anything that causes open() to fail will leave m_tilebuffer at 0 size. Subsequent calls to write_tiles, and also to close (which cleans up unwritten parts of the buffer at the end) did not check for this condition and would access out of bounds memory.
While I was in there, I converted the zfile.cpp error messages to the new formatting convention.
> Zfile write safety

- src/dpx.imageio/libdpx/DPXHeader.cpp
We shouldn't abort here, we should return and handle the error better (which we do).
> DPX input: Comment out assertions

- src/raw.imageio/rawinput.cpp
If raw:user_flip is set, the flip field of the raw input is replaced with the value of raw:user_flip and the original flip value is lost.
If raw:user_flip is set to 1, we can consider the user wanted to disable the buffer rotation.
We may want to display it correctly anyway. This PR proposes to store the original flip value inside the exif orientation code.
> [raw] update exif orientation with raw flip if user flip is set

- src/dpx.imageio/dpxoutput.cpp
There was a subtle error where we has a reference to an ImageSpec for one of the subimages, confusingly called m_spec, which we altered, but then didn't make the same change to the this->m_spec, and in a later spot we referenced the `m_spec` meaning the one in this. This could lead to a crash.
Fix, but not only that, rename to avoid the confusion. `spec0` is the alias we us for the spec for subimage 0, and `spec_s` is the alias we use when referencing subimage N, and we really never use m_spec anymore to avoi any confusion. This should make it easier to reason about this code in the future and avoid thise kinds of mistakes.
A second error resulted from the situation where a failure in open() would return before one or both of m_buf or m_tilebuf were allocated. If the return status of …
> DPX output: fix write errors

- src/bmp.imageio/bmpoutput.cpp
In open(), check for non-zero image offsets, which is not supported by BMP, and issue an error if found. If the spec passed in has nonzero spec.y, other code in the write functions would fail because they assumed spec.y == 0 and could therefore access memory incorrectly.
More generally, also put checks in the write functions that issue errors and take early outs if they find that they are called on a BMPOutput that is not currently open, for example if open() fails but the user doesn't check the return codes and proceeds to call the write functions anyway.
This addresses 1653
> BMP output safety

- src/include/OpenImageIO/string_view.h
avoid sanitizer warning of unsigned integer overflow
src/Components/ExternalLibraries/OpenImageIO/install/include/OpenImageIO/string_view.h:252:43: runtime error: unsigned integer overflow: 0 - 17 cannot be represented in type 'unsigned long'
#0 0x10d0adf61 in OpenImageIOMaya_v2_4::basic_string_view<char, std::__1::char_traits<char> >::compare(OpenImageIOMaya_v2_4::basic_string_view<char, std::__1::char_traits<char> >) const string_view.h:252
(adding new test cases if …
> avoid sanitizer warning unsigned integer overflow

- src/rla.imageio/rlainput.cpp
This has been causing CI tests to fail.
There's something about gcc12 when using -std=c++20 that is making this line fail when assigning a char* versus a std::string into an element of a std::vector.
> Try to squash warning in gcc 12.1 + C++20

- src/iff.imageio/iff_pvt.h
- src/iff.imageio/iffoutput.cpp
* Maya IFF documentation says IFF file has max resolution of 8192, and our implementation only allows writing RGB and RGBA, so check these limits when an IFF file is opened for output.
* Make sure scratch space allocates enough for tile padding.
* Check for non-zero image origin coordinates (which are not allowed in IFF files).
* Change some 16-bit loop variables to uint32_t to avoid possible overflow.
Fixes TALOS-2022-1654, TALOS-2022-1655, TALOS-2022-1656
> IFF output safety

- src/psd.imageio/psdinput.cpp
When reading PSD file, if reading the thumbnail doesn't pass basic sanity checks, we consider that a hard error reading the file.  One check that we do is to make sure that our computation of the byte width of the uncompressed thumbnail (`bpp/8 * width`) matches what the file says the `widthbytes` is.
BUT... it seems that it might round up to an even (or maybe 4-multiple?) of columns, presumably for scanline alignment reasons. And so we were considering whole PDF files unreadable if they fell into this case.
This PR primaril loosens the test to allow some padding up to a multiple of 4.
Fixes #3658
> PSD reading: don't reject padded thumbnails

- src/dpx.imageio/dpxoutput.cpp
- src/dpx.imageio/libdpx/DPXColorConverter.cpp
Many parts of this imported file are unused by OIIO. `#if 0` them away, so they aren't part of static analysis or code coverage.
> DPXColorConverter.cpp: exclude unused portions

- src/oiiotool/oiiotool.cpp
We were over-allocating the color vector, and that was throwing off the operation of IBA::render_point for cases where the image had no alpha channel.
> oiiotool --point fix problem when there's no alpha

- src/include/OpenImageIO/detail/fmt.h
- src/include/OpenImageIO/span.h
- src/libutil/strutil_test.cpp
* Make sure the cspan alias also allows the Extent template argument.
* Add a custom formatter for {fmt} to print spans, like we did for Imath types.
> span minor improvements

- src/libOpenImageIO/maketexture.cpp
When creating a texture, the old logic was to set the file metadata "DateTime" to the current time, unless update mode was used, in which case it was set to the file's write timestamp of the input file.
But that made it impossible to explicitly set that metadata, and also a big PITA for testing because it meant the metadata of any written texture would be the time of its writing, and so appear different every time.
This change alters the logic: update mode still sets DateTime to the last update time of the input file, as before; other cases will only set DateTime if it isn't already set, but not alter it if the input carries that metadata already.
> make_texture: allow existing DateTime to remain

- .github/workflows/ci.yml
- src/build-scripts/gh-installdeps.bash
Also be more robust to the libheif and libde265 repos being occasionally down.
> CI: test against latest webp, and deal with its master->main repo change

- src/bmp.imageio/bmpoutput.cpp
- src/dpx.imageio/dpxoutput.cpp
- src/fits.imageio/fitsoutput.cpp
- src/gif.imageio/gifoutput.cpp
- src/hdr.imageio/hdroutput.cpp
- src/heif.imageio/heifoutput.cpp
- src/ico.imageio/icooutput.cpp
- src/iff.imageio/iffoutput.cpp
- src/include/OpenImageIO/imageio.h
- src/jpeg.imageio/jpegoutput.cpp
- src/jpeg2000.imageio/jpeg2000output.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/openexr.imageio/exroutput.cpp
- src/png.imageio/pngoutput.cpp
- src/pnm.imageio/pnmoutput.cpp
- src/rla.imageio/rlaoutput.cpp
- src/sgi.imageio/sgioutput.cpp
- src/targa.imageio/targaoutput.cpp
- src/term.imageio/termoutput.cpp
- src/tiff.imageio/tiffoutput.cpp
- src/webp.imageio/webpoutput.cpp
- src/zfile.imageio/zfile.cpp
Many ImageOutput::open implementations start out with various validity checks -- such as whether the ImageSpec requests a resolution, number of channels, or other features simply not allowed by that file format. This is not only repetitive, but which checks are done by each file type is somewhat haphazard, error-prone, hard to get full test coverage (must we separately test each possible failure case for every file format?), and the error messages are not always consistent across formats. Frankly, most of the format writers assume that the caller has a full understanding of supports() and will never send requests for features that are unsupported, which is obviously not a careful approach.
This PR proposes adding a utility method ImageOutput::check_open(), which performs all validity …
> Centralize ImageOutput validity checks

- src/build-scripts/install_homebrew_deps.bash
Something changing in homebrew caused CI on the macos11 test case to fail, starting a few days ago. This fixes.
> CI: Fix broken Mac CI with proper numpy install

- src/bmp.imageio/bmp_pvt.h
- src/bmp.imageio/bmpinput.cpp
- src/doc/builtinplugins.rst
- testsuite/bmp/ref/out.txt
Seems like a reasonable assumption for BMP files.  It's not strictly correct -- there are header fields on V4 and V5 BMP files that communicate color primaries and gamma, but honestly, I do not have any idea if anybody uses them or whether they're more misleading than helpful. For now, assuming that a BMP file is meant for output on an sRGB display seems like it's likely to be true.
> BMP: set colorspace to sRGB

- src/libutil/strutil.cpp
Another fix for the latest Apple clang, continuing #3709 (I missed these other spots).
> Build: Suppress warnings about deprecated std::codecvt_utf8_utf16

- src/libutil/hashes.cpp
Remove the xxhash stuff from hashes.cpp -- it long ago moved to xxhash.cpp. Also, comment out the bjhash implementations that OIIO itself doesn't use or expose publicly, since there's no point compiling it (or having it count against us in coverage analysis).
> hashes.cpp: remove or exclude from compilation unused functions

- src/libutil/filesystem.cpp
IOMemReader::pread catch out-of-range read positions.
Fixes #3711
Along the way, I noticed that the system pread & pwrite return a ssize_t rather than a size_t as our IOProxy methods do, so I need to catch the negative value returns that they use to indicate errors.
> IOProxy read/write error handling improvements

- src/include/OpenImageIO/ustring.h
Hide from Cuda some things that can't possibly work in Cuda.
> ustring.h: cuda guards

- src/include/OpenImageIO/simd.h
Fixes #3721
Please read the comments in #3721. This is the "local" fix for the build break due to the type mismatch. It is a band-aid. And it may be the best solution for the 2.4 branch if we don't want to potentially break ABIs by changing the definition of any public types.
Still pending is to examine the issue of whether it was a mistake to define vbool4 storage for neon as uint32x4_t or if we should change it to int32x4_t to better match the non-simd reference implementation. After debating that (and identifying somebody with access to an ARM-based machine to test the solution for us), we may return to tackle this more fundamental change.
> ARM: Fix signed/unsigned simd mismatch in vbool4::load

- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imagebufalgo_yee.cpp
- src/oiiotool/diff.cpp
- src/oiiotool/oiiotool.cpp
- testsuite/diff/ref/out-fmt6.txt
- testsuite/diff/run.py
- testsuite/oiiotool-deep/ref/out-fmt6.txt
We had no testsuite exercise of --pdiff, add it.
Along the way, I saw tha we were getting the "you didn't have any output" warning when using pdiff, so fix that.
And some other minor changes: formatted output update, some other tightening up of things.
A little bit of jiggling the contents of XYZtoLAB_color to work around what I think is a compiler error with icx -- it was generating NaNs for reasons I was unable to understand or fix, but not if I rearranged the code slightly. All the other compilers and versions had correct behavior.
> oiiotool --pdiff: test, be sure to count it as making output

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/build_libtiff.bash
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
libtiff 4.5 was just released, so confirm that we build against it, update the "latest versions" CI test to use 4.5.
More careful sorting out of libtiff version numbers for conditional compilation.
Get rid of some ancient tiff version guards that are related to libtiff versions that are older than we currently support.
When building against libiff 4.5, use the new open calls that allow per-file error handlers, which is better than the old global error handlers for thread safety of multiple threads reading from the same ImageInput if there are errors.
Convert error messages to std::format form.
> tiff updates for libtiff 4.5

- src/include/OpenImageIO/fmath.h
Turns out the clang/gcc intrinsics themselves compile to the same memcpy idiom that I was using for the general case. So there is no need for the clutter of the specialization.
> Remove useless bitcast specializations

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/simd.h
It should not have been set in platform.h (inside the cpuid function!) in the first place. And apparently, though this was ok for Windows ARM, on Mac ARM it's an error because that symbol is already defined. So only redefine it if it's currently undefined. And move the whole check and definition into simd.h where all the other ARM_NEON stuff lives.
> Move ARM_NEON definition and fix possible double define

- .github/workflows/ci.yml
Investigate later. For now, this is necessary for us to pass CI.
> CI: Temporarily lock fmt to 9.1.0 because its master seems broken

- src/build-scripts/gh-installdeps.bash
The new 2023 one on the Intel site seems to require a glibc too new to be compatible with the one on the ASWF CentOS-7 based containers, so has been breaking our CI for a couple weeks.
> CI: Lock down to older icc so it's not broken

- src/include/OpenImageIO/fmath.h
Note that these intrinsics don't seem to be available for gcc. They are available on clang, but are defined in terms of the memcpy trick. But in Intel, they seem to actually help.
> Revert 3728, that was ill advised

- src/doc/conf.py
- src/doc/imagebufalgo.rst
- src/doc/imageioapi.rst
- src/doc/oiiotool.rst
- src/doc/requirements.txt
- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/string_view.h
I think this looks better.
Also a few minor tweaks to typos and misquotes.
> Docs: for rtd, upgrade sphinx/breathe versions, use furo theme

- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/formatspec.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_imagespec.cpp
- testsuite/python-imagespec/ref/out-python3.txt
- testsuite/python-imagespec/ref/out.txt
- testsuite/python-imagespec/src/test_imagespec.py
Sets color space metadata. While conceptually, the main job is to call `attribute("oiio:ColorSpace",name)`, this is a central spot to add logic that adjusts or removes other contradictory metadata.
> ImageSpec:set_colorspace()

- src/png.imageio/png_pvt.h
- src/png.imageio/pngoutput.cpp
- testsuite/png/ref/out-libpng15.txt
- testsuite/png/ref/out.txt
- testsuite/png/run.py
Stores any EXIF data from the given ImageSpec into the PNG eXIf chunk.
[corporate](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-CORPORATE)).~~ Change is small enough to not require a CLA
> Add EXIF write support to PNG output.

- .gitignore
- Makefile
- src/build-scripts/ci-test.bash
- src/cmake/testing.cmake
- src/include/OpenImageIO/typedesc.h
- src/libutil/typedesc.cpp
- src/libutil/typedesc_test.cpp
- src/openexr.imageio/exroutput.cpp
- src/python/py_imagecache.cpp
- src/testtex/testtex.cpp
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imagebuf/src/test_imagebuf.py
- testsuite/python-imagecache/ref/out-python27.txt
- testsuite/python-imagecache/ref/out-win.txt
- testsuite/python-imagecache/src/test_imagecache.py
- testsuite/texture-threadtimes/run.py
* Better Typedesc testing of 'tostring' with fmt style formatting commands, and fix a bug that uncovered.
* Refine 'make CODECOV=1' behavior
* Beef up python-imagecache test to test getpixels, more attribute, invalidate.
* Better testing of python IB construction from numpy array.
* testtex: Use correct guard to avoid compiling unused code for coverage analysis testtex: get rid of unused 3d warp code.
* Add texture-threadtimes test
* Eliminate redundant code in exroutput.c by implementing write_scanline using write_scanlines.
> Additional testing and improved code coverage (and minor fixes)

- src/libOpenImageIO/maketexture.cpp
- src/maketx/maketx.cpp
- testsuite/maketx/ref/out.txt
- testsuite/maketx/run.py
* Tests for maketx -u, --attrib, --sattrib, --cdf
* maketx was documeted to take --cdf as a simple flag, but was incorrectly implemented as requiring a (pointless) nonzero argument. Fix it and hope nobody was depending on the undocumented behavior.
* maketx -v arg never had any effect. Add it back.
> Testing: improve testing of maketx

- src/psd.imageio/psdinput.cpp
- testsuite/psd/ref/out.txt
- testsuite/psd/run.py
Refactoring in #1641 incorrectly caused this to be set on the last layer rather than the composite image as before. Now set it on the composite image and every layer, as all of them use unassociated alpha.
Test was added.
> Fix wrong oiio:UnassociatedAlpha metadata for PSD files

- src/doc/builtinplugins.rst
- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
- testsuite/iinfo/ref/out-fmt6.txt
- testsuite/iinfo/ref/out.txt
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imageinput/ref/out-alt.txt
- testsuite/python-imageinput/ref/out-alt2.txt
- testsuite/python-imageinput/ref/out-py27-jpeg9d.txt
- testsuite/python-imageinput/ref/out-py27.txt
- testsuite/python-imageinput/ref/out-py37-jpeg9d.txt
- testsuite/python-imageinput/ref/out-python3-win.txt
- testsuite/python-imageinput/ref/out-python3.txt
- testsuite/python-imageinput/ref/out-ubuntu-py2.7-pybind2.3.txt
- testsuite/python-imageinput/ref/out.txt
Some background: TIFF allows for pixel values to be encoded in some alternative color spaces, like YCbCr, CIELAB, etc., and this is indicated by the TIFF PhotometricInterpretation tag. Since in practice we almost never encounter these encodings in the wild, and they require a lot of custom code to handle (for example, YCbCr also comes along with the ability to subsample the chroma, and options for different placements of the subsampled positions, yuck), for most of these cases we just lean on libtiff's ability to convert the whole thing to RGBA for us, and so in that case, we return to the user the pixels as RGBA, and set the "tiff:ColorSpace" metadata just as an advisory to indicate how it had been encoded in the file. But we don't support writing any of those. (One exception is that we …
> TIFF: refine logic for setting PhotometricInterpretation on output

- src/include/OpenImageIO/timer.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
Timer:
* Fix goof where m_printdtr was a bool but was tested for equality to an enum. It happened to work like that, but only coincidentally.
* Add another enum value that allows a debugging message to be printed upon construction of the timer, in addition to its destruction.
* Switch from printf style to std::print style formatting of the debugging messages.
LoggedTimer:
* Modify to allow modifying the call count.  This turns out to be helpful for times when one logged function calls another logged function (like if a special case is broken out) and they both log to the same timer -- it makes it look like just one invocation instead of two.
> Minor Timer and LoggedTimer class tweaks

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool-xform/run.py
No need for separate :offset= modifier, the :to= can already be used for this purpose.
This simplifies the changes from #3751
> Simplify oiiotool --resize recent changes

- src/include/OpenImageIO/imagebufalgo_util.h
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/oiiotool/oiiotool.cpp
Examining some timings and function call counts, I saw that a typical oiiotool command was spending a surprising amount of time in ImageBufAlgo::zero(), not just more runtime overall, but also calling it many more times than I thought it should.  For example,
oiiotool -create 4096x4096 3 -colorconvert srgb acescg
called ImageBufAlgo::zero()... 4 times, totaling as much time as the colorconvert operation.
The idiom used in `IBA::op(dst, src, ...)` which initializes the `dst` IB if it's not already initialized will call the IB constructor that zeros out its contents (so you don't have every new IB full of garbage pixel values). But for IBA functions, this is almost never necessary, since the IBA function itself will tend to overwrite all pixel values. Not always, of course -- since IBA …
> Spend less wasted time zeroing out ImageBuf

- CMakeLists.txt
- src/iff.imageio/CMakeLists.txt
- src/iff.imageio/noproxy-iff_pvt.cpp
- src/iff.imageio/noproxy-iff_pvt.h
- src/iff.imageio/noproxy-iffinput.cpp
- src/iff.imageio/noproxy-iffoutput.cpp
When we recently added IOProxy support to the Maya iff file reader in PR 3647, something broke for certain (but not all) iff files, and I have productions stumbling over this.
It's proving tricky to track down and I have shows needing a fix immediatly, so this change sets up a CMake variable ENABLE_RLA_IOPROXY, default to ON, but when set to OFF, it switches back to the old "no proxy" versions of the iff reader.
Disabling this will get me out of my current emergency -- at the cost of not having IOProxy for iff, which I don't need at this moment anyway -- and give me some breathing room to fix the problem for real, at which point I will re-remove the old code.
> iff: Temporarily address breakage with optional IOProxy revert

- src/libutil/strutil.cpp
If char16_t is used as template argument, this leads to an unresolved symbol for MSVS 2017. Use int16_t instead of char16_t in this case. 
Fixes #3762
[corporate](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-CORPORATE)).~~ This is just a small change
(adding new test cases if necessary).~~ Not applicable.
> Fix unresolved external symbol for MSVS 2017 (#3762)

- src/openexr.imageio/exroutput.cpp
Avoids conditional jump on uninitialised values in close(). Not sure whether ONE_LEVEL is the best value here ...
Without that fix, valgrind reports a conditional jump on uninitialised values on code like
```
auto out = OIIO::ImageOutput::create( "exr");
```
> Initialize OpenEXROutput::m_levelmode() in init().

- testsuite/python-imagebufalgo/src/test_imagebufalgo.py
Add a shim that can run both the "returns an IB" and "modifies an IB" version of each IBA function for better test coverage.
> test: Better testing of python IBA functions

- src/libOpenImageIO/imageoutput.cpp
For non-0-origin images, we were checking the resolution range incorrectly (`>=` vs `>`).
Also were printing the error message with the wrong notation, should have shown a half-open range as `[beg,end)` and not `(beg,end]`.
> fix: ImageOutput::check_open error conditions

- src/fits.imageio/fits_pvt.h
- src/fits.imageio/fitsinput.cpp
There are two ways to fail the FITS magic number check: fail to read the bytes, or the bytes don't match the magic number. It seemed suspicious that we call close() for the latter but not the former. Combine them into a single error response (they had the same message, anyway).
Also, make sure FitsInput::init() fully clears some other data structures.  Oversight?
I don't know if any of these things are real bugs, but they look sloppy and potentially problematic, so fixing them up.
> fix(fits): Make sure to close if open fails to find right magic number

- src/cmake/compiler.cmake
Fix #3773
I did test it on my local Linux system, and it properly detects that it doesn't need to link against . I also tested compiling the test source file in a system that needs linking against latomic (32-bit ubuntu 14.04 using clang, there is probably some other system that is this way as well) and the compile itsself did indeed fail with undefined reference errors, as expected. So this check should be just as robust. 
> Don't use check_cxx_source_runs to make cross-compiling easier

- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/texture.h
- src/include/OpenImageIO/thread.h
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
There turns out to be a way to get wedged into a mutual deadlock on the file handle cache, with how get_texture_info on a udim pattern checks to see if the attribute requested is present and equally valued in all constituent files of the udim set. This hits the handle set pretty hard, and if multiple threads are hammering the same sets and rapidly cycling textures out of the cache, there can be trouble, it seems.
Remedies in this patch:
* When it's trying to close files because the number of handles is too high, we already had it so that if we only exceeded the max_files limit by a little bit, we would simply try to get the lock, and abandon the attempt if somebody else is holding it, but if we are quite a bit over, then stay and wait for the lock to be released.
In this patch, we make …
> fix(IC/TS): Avoid deadlock situations with file handle cache

- .github/workflows/ci.yml
- INSTALL.md
- testsuite/python-colorconfig/ref/out-ocio111-python27.txt
* Don't use deprecated, soon to be disabled, ubuntu-18.04 runner. Switch to running on ubuntu-20.04, but use docker containers that supply ubundu-18,04.
* Bump 'latest' version of openexr, webp, pugixml.
> ci: updates to runners, dependencies

- src/libutil/strutil_test.cpp
Upshot: when you are doing a straight-up concatenation, `concat(a, b)` is about 2x faster than `format("{}{}", a, b)`.
> Add benchmarking of ways to concatenate strings.

- src/tiff.imageio/tiffinput.cpp
- src/tiff.imageio/tiffoutput.cpp
TIFF output using JPEG compression seems unreliable, and after several hours trying to chase it down, I'm not making much progress.  As far as I can tell, this has always (or at least for a long time) been broken, and nobody noticed, which is strong circumstantial evidence that it's not something people need or are trying to use, and therefore it doesn't seem like a good use of more time to fix a feature that no one uses.
So I'm hiding all the TIFF output with jpeg compression support behind `#if` guards and disabling them for now. This will cause requests to use jpeg compression for TIFF output to just revert to the default zip compression.
Reading TIFF files that are jpeg-compressed seems fine, this doesn't disable our ability to read the files, just to produce them.
It is also worth …
> Disable writing TIFF with jpeg compression

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageio.cpp
When we build against OpenEXR >= 3.1, default to using the new "exrcore" APIs unless disabled at build time with `-DOIIO_USE_EXR_C_API=OFF` or at runtime through the global openexr:core attribute.
> perf(exr): change to using exr-core for reading by default

- sonar-project.properties
No need to configure the cache anymore,
SonarCloud now has automatic analysis caching.See:
https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache.
Also, the filesystem cache was not persisted.
> Remove SonarCloud cache setup as it is now offered by default

- src/libOpenImageIO/maketexture.cpp
- testsuite/maketx/ref/out.txt
- testsuite/maketx/run.py
- testsuite/oiiotool-maketx/ref/out-rhel7.txt
- testsuite/oiiotool-maketx/ref/out-win.txt
- testsuite/oiiotool-maketx/ref/out.txt
- testsuite/oiiotool-maketx/run.py
Currently, if you run `oiiotool` with `--bumpslopes` and `--cdf` at the same time (or `-obump:cdf=1`), the CDF is only produced for the first four (of six) channels. The techniques described in Burley (2019) actually do apply reasonably to the squared derivative channels, so it's useful to allow all six channels to have CDFs here.
`maketx` and `oiiotool-maketx` tests updated with new relevant tests.
> Add support for CDFs of bumpslopes channels

- src/python/py_oiio.cpp
For cases of calls like `ImageOutput.write_image(array)`, this improves the error messages when the array dimensions don't match the size of the image we're writing, in two ways:
1. For the case of 2D images where the dims don't match, print what the array shape actually is and what was expected. That's more helpful than just saying "can't figure out array shape" and printing the number of dimensions (but not the shape).
2. A mistake caused a number of error messages to be substituted by a cryptic "can't handle numpy array with noncontiguous channels", but that was only supposed to be for one particular case; fix that.
> fix(python): improve error messages of bad python array sizes

- src/include/OpenImageIO/fmath.h
I ran into the problem described in #2929 and did a little digging to see if I could find the source of the bad color conversions. I tracked it down to `fast_exp2()` https://github.com/OpenImageIO/oiio/blob/a77e36250fadfb4c391688eb1df4b3dd88d5e367/src/include/OpenImageIO/fmath.h#L2050-L2080
and in particular the return statement on L2071. In the process of trying to figure out what part of that return statement was going awry, I found that separating the bitcasts to separate variables as in this PR, the problem went away. All testing was done with the `color_test` added in #3023.
It also succeeded when adding various `std::cout` lines to check what the values of each computation were, so it does sound like a compiler optimization that does or does not get triggered is the problem. …
> Fix `fast_exp2` with MSVC and sse4.2

- src/oiiotool/oiiotool.cpp
- src/openexr.imageio/exroutput.cpp
We know that there are some corner cases on Windows when it can be unsafe to exit because the Ilm thread pool (which is used implicitly by OpenEXR) hangs. The exact conditions that cause this are not well understood.
Some time back, in PR 3582, we added an explicit shutdown in oiiotool right before we exit, to alleviate the problem. But this doesn't help for other apps like idiff, nor for apps that use libOpenImageIO and aren't aware of the problem, so wouldn't know to do this.
This patch changes to a different strategy: In set_exr_threads(), which will always be called any time we use openexr files, use `std::atexit()` to ensure that when the program terminates -- any program using OpenImageIO in cases when openexr was used -- we set the IlmThread global thread pool size to 0 to shut it …
> fix: Controlled shutdown of IlmThread pool in all apps in which we use it.

- src/heif.imageio/heifinput.cpp
- src/heif.imageio/heifoutput.cpp
I've come across some unsupported files from Canon cameras that have a .hif extension. These are HEIC/HEIF files with a slightly changed extension. I have no idea why Canon decided to do this. Without any changes I am able to open the images, probably because it checks the header, but I am unable to write to paths with a hif extension.
Some random articles/forum posts mentioning the HIF format in relation to Canon cameras:
https://www.cameralabs.com/jpeg-vs-heif-canon-hif-comparison/
https://www.dpreview.com/forums/thread/4558661
https://www.reddit.com/r/canon/comments/kjc6xl/new_eos_r6_owner_here_photo_files_show_up_as_hif/
I did not add tests to the project, but I did compile the library into our application on Windows and Mac environments and verified that the old version does not …
> Support HIF extension

- src/cmake/testing.cmake
The `openexr-images` repo was never updated after the default branch was renamed to `main`. This will fix the following silent errors in CI:
```
Cloning into '/__w/oiio/oiio/build/testsuite/openexr-images'...
warning: Could not find remote branch master to clone.
fatal: Remote branch master not found in upstream origin
```
Additionally, the cmake attempted to symbolically link local repos like `oiio-images` if they were found. Unfortunately this type of link will fail unless running as admin on Windows (which is rare) and the COPY_ON_ERROR directive did _not_ work here (cmake 3.24; weird; sigh...).  The output will now look something like the following:
```
-- Linking oiio-images from C:/Users/jesse/source/oiio-images
-- Link result failed to create symbolic link …
```
> Fix incorrect branch name when cloning openexr-images for the tests

- src/include/OpenImageIO/detail/fmt.h
The latest version of libfmt began using the `__float128` type but this is [not supported in the NVPTX backend for LLVM](https://discourse.llvm.org/t/compiling-cuda-code-fails/61240/13). A way to detect this particular platform seems to be to check both `__CUDA_ARCH__` and  `__clang__`.
I am not disabling it entirely on any CUDA target because NVCC 10+ understands `_float128` and generates instructions for it when tested on godbolt. 
Following up from https://github.com/OpenImageIO/oiio/issues/3809.
> Fix float128 compilation of NVPTX backend for LLVM

- src/psd.imageio/psd_pvt.h
- src/psd.imageio/psdinput.cpp
- testsuite/psd/ref/out.txt
The PSD reader was written 12 years ago by a GSOC student and has changed little since. The following is not a knock on that student, who clearly did a good job if his code has survived mostly unomdified for over a decade. In chasing down problems with handling extremely large psd files, I've noticed some oddities and inefficiencies that need fixing. It's not an emergency, so I'll handle it in pieces.
The item addressed by this patch is memory usage and thread concurrency. It turns out that the reader allocates memory for the scanline reads as it goes... and basically keeps it in the ImageInput until it's destroyed, even though it will never actually be used again. I guess it's just trying to save the next allocation if it reads the same scanline again or on the next subimage? But this …
> fix(psd): Improve memory efficiency of PSD read

- src/bmp.imageio/bmpinput.cpp
- src/dpx.imageio/dpxinput.cpp
- src/include/OpenImageIO/imageio.h
- src/jpeg.imageio/jpeg_pvt.h
- src/jpeg.imageio/jpeginput.cpp
- src/libOpenImageIO/imageinput.cpp
- src/openexr.imageio/exrinput.cpp
- src/png.imageio/pnginput.cpp
- src/sgi.imageio/sgiinput.cpp
- src/tiff.imageio/tiffinput.cpp
Every format that has an existing `valid_file(std::string)` implementation, and which supports an
ioproxy, now also has a `valid_file(IOProxy)` implementation for completeness.
The existing std::string overloads have been implemented in terms of the IOProxy overload where
possible to cut down on the boilerplate. This is done at the base of the hierarchy in ImageInput.
The remaining formats that support ioproxy, but do not currently have a `valid_file` method, will be
submitted in a follow-up PR as the additional logic required for those will require closer review.
I haven't had much time/luck to sort out running the tests locally on Windows, or setting up a parallel WSL
environment, so I admit this is coming in with no test coverage beyond it working locally for me in a
test app. The app …
> Add an ImageInput::valid_file(IOProxy) overload

- site/spi/Makefile-bits
- src/include/OpenImageIO/detail/fmt.h
Working toward clean build with the new gcc 13.1. This isn't the whole story, but it is one thing necessary.
> build: Disable new warning for fmt headers in gcc13

- src/libOpenImageIO/maketexture.cpp
- src/oiiotool/oiiotool.cpp
`make_texture()` already took a configuration option "maketx:forcefloat" (defaults to 1), which if set to 0 disables the conversion to a float buffer for intermediate computation.
For `oiiotool -otex`, there was no way to specify this. This patch allows it to be disabled with the new optional modifier `-otex:forcefloat=0`.
Also, in make_texture, this option only controlled the initial conversion of the whole buffer to float, but the downsized levels all were float either way. This patch now uses the forcefloat config option to also control the buffers used for downsizing.
Disabling forcefloat like this has a speed penalty (the downsizing math on float buffers is faster than going in and out of float for every indvidual value) and loses some precision in the process of repeatedly …
> Improve make_texture for very large images

- src/python/py_oiio.cpp
`ssize_t` is a posix type, msvc seemingly doesn't know about leading to a build error with MSVC 2019
usage elsewhere in this files used the `py::ssize_t` type, which seems to fix this
> Fix: Build error with MSVC

- src/cineon.imageio/libcineon/CineonHeader.cpp
I'm honestly not sure why some GHA CI jobs suddenly started warning about this in the past day or so. Something must have updated on their end. But switching to the safer Strutil equivalents fixes it.
> ci: Fix warnings

- src/include/OpenImageIO/oiioversion.h.in
- src/include/OpenImageIO/simd.h
- src/libutil/timer_test.cpp
We have some OIIO 1.x era type aliases float4, int4, etc., for the
simd types that have long since been renamed vfloat4, vint4, etc.
Hide those aliases when buiding OIIO itself, to be sure we aren't
inadvertently using them. And indeed, in one spot, we were! (Fix it.)
Introuce a new preprocessor symbol, `OIIO_DISABLE_DEPRECATED`, which
if set to an encoded version number (such as 20100 for version 2.1) by
a downstream package, indicates that we are permitted to hide
declarations that were considered deprecated from that version
on. This is an aid to downstream projects who wish to enforce that
they are not inadvertently using any deprecated OIIO calls which may
disappear in a future release.
So back to the deprecated simd names: Also hide them if
`OIIO_DISABLE_DEPRECATED` is defined to …
> cleanup: root out deprecated simd type names; `OIIO_DISABLE_DEPRECATED`

- src/cmake/compiler.cmake
- src/include/OpenImageIO/texture.h
- src/libtexture/texturesys.cpp
- src/testtex/testtex.cpp
As Fabrice Macagno points out on the mail list, we weren't setting the correct variable name CMAKE_CXX_VISIBILITY_PRESET.
Fixing this -- and finally hiding all the symbols correctly -- uncovered an instance where testtex was relying on some classes that should have been hidden in libOpenImageIO. For symbol visibility reasons, move the functionality of testtex's test_hash() function to be in TextureSystem itself. This is a much cleaner separation.
> build(cmake): Fix incorrect variable name to control symbol visibility

- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-copy/run.py
Fixes #3837
oiiotool already attempted to trim extra channels when outputting to a format that can't support it. It correctly handled the two common cases:
* More than 4 channels for formats that don't have `supports("nchannels")` will drop after the first 4 channels.
* More than 3 channels for formats that don't have `supports("alpha")` will drop after the first 3 channels.
But this omits an interesting (but rare) corner case: a 4 channel file where the last channel is NOT alpha, and the output file supports an alpha channel but not arbitrary channels. A concrete example might be an input file that is exr with channels R, G, B, Z, writing to a PNG file (which can support RGB or RGBA). We wouldn't want to write what appears to be an RGBA file if that last channel isn't really alpha.
Also, …
> fix(oiiotool): don't propagate unsupported channels

- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/libOpenImageIO/imageioplugin.cpp
Make pvt::imageio_mutex be a recursive_mutex
Fixes #3842
> fix(int): prevent possible deadlock when reaading files with wrong extensions

- src/gif.imageio/gifinput.cpp
fix #3840: heap-buffer-overflow in file src/gif.imageio/gifinput.cpp, line 368
> fix heap-buffer-overflow in file src/gif.imageio/gifinput.cpp, line 368

- src/dds.imageio/ddsinput.cpp
- src/dpx.imageio/dpxinput.cpp
- src/hdr.imageio/hdrinput.cpp
- src/psd.imageio/psdinput.cpp
- src/webp.imageio/webpinput.cpp
- testsuite/dds/ref/out.txt
- testsuite/psd/ref/out.txt
Following up #3826, this implements efficient `valid_file` support for DDS, DPX, PSD, HDR, and WEBP.
The quick magic/signature checks were abstracted into small helper functions where necessary to eliminate duplicate code.
For WEBP, some redundant checks were also removed and there's also a fix for a `uint64_t` vs `size_t` check which would have caused issues on 32-bit builds.
The PSD changes exposed an issue with array attributes. During a normal ImageInput create+open sequence, an ImageInput may be opened then closed and then opened again.
Array attributes are not cleared as part of close and so their contents will be doubled up next time they are read into the existing `m_spec`. This PR does not fix that general problem but now that PSD has a proper valid_file which doesn't do an open, …
> Implement valid_file(IOProxy) overloads for DDS, PSD, and WEBP

- src/raw.imageio/rawinput.cpp
When reading a raw image while having a `user_flip` set to 1, we set the orientation Exif tag to LibRaw's flip value (so that LibRaw doesn't rotate and/or mirror the buffer but the image still gets displayed correctly).
However LibRaw's convention for flip values differ from Exif orientation values: https://www.libraw.org/comment/5176#comment-5176.
In this PR we fix this issue by converting LibRaw flip values to Exif orientation values. This conversion is based on:
- https://www.libraw.org/comment/5178#comment-5178 (conversion proposed by LibRaw's maintainer)
- https://github.com/LibRaw/LibRaw/blob/6fffd414bfda63dfef2276ae07f7ca36660b8888/src/write/file_write.cpp#L22 (LibRaw's function for applying the flip).
Tested on:
- CR2 images with flip values 1, 5 and 6
- ARW images with flip …
> raw input: fix LibRaw flip to Exif orientation conversion

- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool-copy/ref/out.txt
Make all oiiotool actions take ot as a parameter.
This is a necessary first step to being able to parallelize over frame ranges.
Also finally convert the last of the `int argc, const char**argv` idioms to `cspan<const char*>`.
> refactor(oiiotool): Get rid of the global Oiiotool singleton.

- .github/workflows/ci.yml
- src/libtexture/texturesys.cpp
I found that this was needed after weekend OS update of my laptop.
Also added MacOS-13 CI test.
> build(Mac): Fixes for latest xcode on MacOS 13.3 Ventura

- src/raw.imageio/rawinput.cpp
When reading a raw image, setting the `user_flip` to 1 meant ignoring the `flip` value (to avoid buffer rotation from LibRaw).
However the value 1 for the `user_flip` is **not neutral**: values lie between 0 and 7 (see https://www.libraw.org/docs/API-datastruct-eng.html#libraw_image_sizes_t), and 1 corresponds to a horizontal mirror (in my understanding of the source code).
The proposed fix is to use 0 as `user_flip` value for ignoring the `flip` value.
This modification invalidates the changes made in this PR: https://github.com/OpenImageIO/oiio/pull/3847.
Therefore, flip to orientation conversion has been adapted to match exactly LibRaw's documentation, which handles only rotations (+90, +180, -90 degrees).
The previous PR was only tested on images of landscape and human faces, hence …
> raw input: fix user_flip usage

- src/jpeg.imageio/jpegoutput.cpp
In `jpegoutput.cpp` when computing the density fields the relationship between `XRes`, `YRes` and `aspect` is `aspect = XRes / YRes`.
However this relationship was not respected in one specific case, when `aspect >= 1.0` and `XRes` and `YRes` are not set.
This PR solves this problem by enforcing the correct relationship.
Related to: https://github.com/OpenImageIO/oiio/issues/2822
> jpeg output: fix density calculation

- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebufalgo_opencv.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
Various improvements to OpenCV support:
* IBA::from_OpenCV and to_OpenCV now set error messages for every type of failure they encounter, instead of returning false with no explanation. For from_OpenCV, the error message can be retrieved from the ImageBuf returned; for to_OpenCV, the error message can be retrieved from the global OIIO::geterror(). Several assertions were removed, instead relying on error return codes and messages.
* Add global OIIO attribute "opencv_version" which allows you to find out what version of OpenCV OIIO was built against, which was previously impossible to know without seeing the build-time status messages. This can be retrieved via
OIIO::get_int_attribute("opencv_version")
and also you can find out from the command line with
oiiotool --echo …
> feat(OpenCV): Improve OpenCV support -- errors, version, half

- src/doc/imageinput.rst
- src/doc/imageoutput.rst
Fixes #3846 by updating Python examples.
Current code examples for [ImageInput](https://openimageio.readthedocs.io/en/latest/imageinput.html) and [ImageOutput](https://openimageio.readthedocs.io/en/latest/imageoutput.html) raise a SyntaxError in Python 3:
```python
File "<cwd>\main.py", line 13
return
^^^^^^
SyntaxError: 'return' outside function
```
It seems these code examples might be for Python 2.7. Perhaps it would be worth creating an extra tab instead of replacing the old code?
Tested on Python 3.11, no issues. …
> ImageInput and ImageOutput docs updated to Python 3.

- src/doc/imagebuf.rst
- src/doc/imageinput.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagecache.h
A variety of minor documentation fixups:
- Use Python 3 style 'print' statements consistently everywhere (some snippets had a mix of both)
- Correct the usage of `ImageSpec::channels` instead of `ImageSpec::nchannels`
- Template syntax errors in two C++ snippets
- Document the new default for `max_memory_MB`
> A variety of minor documentation fixups

- src/include/OpenImageIO/oiioversion.h.in
- src/include/OpenImageIO/simd.h
I got the test backwards, and it was incorrectly hiding the definition for the default case of OIIO_DISABLE_DEPRECATED == 0.
> fix(simd.h): Fix sense of hiding deprecated type names

- src/cmake/externalpackages.cmake
We set it, but we didn't use it where it was intended.
> build: Fix use of OIIO_LOCAL_DEPS_PATH

- src/psd.imageio/psdinput.cpp
When reading a PSD file, if it contains a thumbnail, we read it from the in-memory blob with a combination of an IOMemReader and an ImageBuf.  But... we always named it "thumbnail.jpg" without considering that multiple simultaneous PSD files reading identically named images (but which are in fact different) could cause a weird kind of clashing in any underlying use of ImageCache!
The simple fix is to use ordinary ImageInput approach to reading the thumbnail from the IOMemReader, but just store it in the ImageBuf.
Fixes #3824
> fix(psd): Prevent simultaneous psd thumbnail reads from clashing

- src/cmake/externalpackages.cmake
The comment was right, but the test seems to have had a typo we didn't catch in review.
> build: Fix fmt vs gcc warning that had version typo

- src/libutil/thread.cpp
Part of solving #3851.
When decreasing the number of threads in `thread_pool::Impl::resize` it was possible for the threads marked for termination to still be fully alive at process exit time if the call to `resize` and the exit of the main function were close enough to each other.
This change makes `resize` wait for the threads to actually join guaranteeing the threads have been shut down in a orderly manner when the `resize` function exits.
N/A
[corporate](https://github.com/OpenImageIO/oiio/blob/master/src/doc/CLA-CORPORATE)). - small change no CLA …
> Fix: Wait for terminated threads to join in thread_pool::Impl::resize

- src/jpeg2000.imageio/jpeg2000output.cpp
J2K output was defaulting to UINT8 when asked to output an unsupported type. It should have been UINT16 to try to minimize the amount of precision loss.
Fixes #3876
> fix(jpeg2000): better pixel type promotion logic

- src/openexr.imageio/exroutput.cpp
PR #2147, addressing issue #1844, is related to an apparent OpenEXR bug wherein single channel tiled images where the tile dimensions were not a power of 2 and >= 16 would not work properly with dwa compression. We work around the problem by automatically substituting zip compression in those cases. But it was implemented with a subtle bug, forgetting that tile_size == 0 for untiled images, and thus we were silently switching from dwa to zip compression for all *untiled* single channel images of any size (which presumably were never problematic). This patch fixes the test so we are not changing the compression for the untiled files.
> fix(exr): correction to dwa vs zip logic when outputting OpenEXR

- src/libOpenImageIO/exif.cpp
Make sure we can input exif tags as strings containing numbers when number are required.
E.G. if my input is "Orientation"=>"8", i would like the jpeg output to contains the value 8 for the exif tag orientation.
> [exif] Convert paramvalue string to integer when needed

- src/libOpenImageIO/color_ocio.cpp
If colorconvert, ociolook, ociodisplay, ociofiletransform fail
because OCIO support is not enabled, make sure the error message
makes that clear.
> fix(IBA): Improve error message for IBA::ocio functions

- INSTALL.md
- src/build-scripts/gh-installdeps.bash
- src/heif.imageio/heifinput.cpp
- src/heif.imageio/heifoutput.cpp
The strukturag repo for libheif recently upgraded the version it was serving from 1.14 to 1.16, and that caused our tests to fail because (a) some of the codec support has been moved to plugins that are loaded at runtime and those are now distributed in packages we need to install separately; (b) you must call heif_init() or it won't know about the optional plugins.
> ci: Fix broken heif dependency and test

- src/build-scripts/build_llvm.bash
* Remove leftover logic from when we used TravisCI.
* Pick a default for LLVM_DISTRO_NAME so it works when the script is run standalone when not on GitHub Actions CI. (But it's still really only meant to run on x86 Ubuntu, and not designed for anything useful outside of our CI.)
* Eliminate all the complexity with old LLVM versions -- in practice, our CI only uses this to download fairly modern clang versions.
Fixes #3891
> ci: Simplify build_llvm.bash script

- INSTALL.md
- README.md
repology has a handy tool that will show all the package distros
and which version of openimageio they supply.
> docs: Add repology badge to README and package versions to INSTALL

- src/include/OpenImageIO/detail/farmhash.h
- src/include/OpenImageIO/string_view.h
- src/libutil/strutil_test.cpp
The underlying farmhash algorithm (which is the basis for Strutil::strhash, and thus ustring's hash representation) turned out to not be properly constexpr under certain circumstances and needed to be expressed a different way to be fully constexpr on all platforms and for all strings.
New implementation suggested by Alex Wells.
Also, make sure string_view ctr from char* can be constexpr, even for
C++14. This is related for the sake of the strhash calls that, when
taking string literals, actually choose the variety that accepts a
string_view.
> fix(strutil.h): ensure proper constexpr of string hashing

- src/cmake/modules/FindWebP.cmake
- src/webp.imageio/CMakeLists.txt
I use CMake with [`CMAKE_FIND_PACKAGE_PREFER_CONFIG`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html). WebP installs its own config files which but doesn't respect `CMAKE_DEBUG_POSTFIX` in `WEBP_LIBRARIES`. Linking to the target resolves that issue.
It would be usefull to add a test pipline where CMake is called with `CMAKE_FIND_PACKAGE_PREFER_CONFIG`. However this is out of scope to this PR and should be done by a separate patch. Unfortunately, I don't currently have the time to familiarize myself enough to do this myself.
employers might think my programming belongs to them, then …
> Fix WebP linking if CMAKE_FIND_PACKAGE_PREFER_CONFIG is ON

- src/cmake/externalpackages.cmake
I use CMake with [`CMAKE_FIND_PACKAGE_PREFER_CONFIG`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html). OpenEXR installs its own config files which set `OpenEXR_VERSION` instead of `OPENEXR_VERSION`.
It would be usefull to add a test pipline where CMake is called with `CMAKE_FIND_PACKAGE_PREFER_CONFIG`. However this is out of scope to this PR and should be done by a separate patch. Unfortunately, I don't currently have the time to familiarize myself enough to do this myself. …
> If OpenEXR is found by cmake config file, OpenEXR_VERSION is set instead of OPENEXR_VERSION

- src/include/OpenImageIO/simd.h
Clean up the `#if` tests that disable Intel SIMD when not on Intel architectures, which incorrectly disabled ARM NEON when on ARM.
Fixes #3909
> build: Fix broken OIIO_NO_NEON definition

- src/psd.imageio/psdinput.cpp
- testsuite/psd-colormodes/ref/out.txt
- testsuite/psd-colormodes/run.py
During the CMYK to RGB conversion in PSDInput, the alpha channel was never copied to the RGBA output. Converting a PSD to JPEG worked because it ignored all the 0 alpha values, but converting to WebP would result in a fully transparent image.
I added a cmyk-with-alpha.psd test to the psd-colormodes test to check this
> CMYK PSD files should copy alpha

- src/doc/builtinplugins.rst
- src/ico.imageio/icoinput.cpp
This updates ICOInput to use the IOProxy model so it can read from files or the IOMemReader
The current ICO tests still pass exercising the new code. I didn't see anything in the other formats with IOProxy support to explicitly test the in memory options
> Adding IOProxy support to ICOInput

- src/include/OpenImageIO/hash.h
- src/libtexture/imagecache_pvt.h
- src/libtexture/texturesys.cpp
Optimises the code in the tile hash function. During a render this function is called billions of times so this small improvement adds up, in some test scenes it reduces total render time by an average of about 2%.
See https://godbolt.org/z/jMzz4PTce for the exact details. A summary would be:
- Reduced instruction count from 75 to 61, this is due to the redundant add and shift operations that can be implicitely handled by taking advantage of the member layout in the class.
- Halves the number of memory fetch instructions because all accesses are now 64-bit.
- Removes branching instructions and extra memory indirection inside `ustring::hash()`.
There is a slight change in behaviour, which is that the hash is now computed from the `m_file` pointer rather than from …
> Remove redundant instructions from tile hash

- src/iconvert/iconvert.cpp
> refactor: Convert iconvert.cpp stream io and sprintf to modern

- src/python/py_oiio.cpp
When an incoming 1-dimensional, buffer-like, object was used in Python, the corresponding check inside OIIO would overflow if its length exceeded a signed 32bit value.
An error similar to `Pixel data array error: Python array shape is [2304000000] but expecting h=24000, w=24000, ch=4` would be raised.
I modified a few similar calculations and tried to follow the predominant pattern already used.
Tested using the following snippet which would previously fail:
```
import OpenImageIO as oiio
import numpy as np
filename = "t:/foo.png"
xres = 24000
yres = 24000
channels = 4  # RGB
pixels = np.zeros(xres * yres * channels, dtype=np.uint8)
spec = oiio.ImageSpec(xres, yres, channels, "uint8")
image = oiio.ImageOutput.create(filename)
image.open(filename, spec)
if not image.write_image(pixels): …
```
> Fix arithmetic overflow in oiio_bufinfo (Python interop)

- CHANGES.md
- INSTALL.md
- src/cmake/externalpackages.cmake
- src/raw.imageio/rawinput.cpp
Rationale:
* LibRaw 0.18 was released in last 2016, so we are stil supporting all libraw from up to 6 years back.
* LibRaw 0.18 is necessary for ACES, plus it improves a lot of metadata handling.
* LibRaw 0.20 is the minimum that can be used when compiling with C++17, and we will almost certainly move to C++17 as a minimum in OIIO 2.6, so it seems like LibRaw 0.18 is reasonable minimum for the upcmoming 2.5.
Remove some cruft that's no longer necessary if we drop support for 0.15-0.17.
> build(deps): Raise minimum libraw to 0.18

- .github/workflows/ci.yml
- CHANGES.md
- INSTALL.md
- src/build-scripts/build_openexr.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenEXR.cmake
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
This will not be backported to the release branch, it's only for OIIO 2.5 and later.
> build(deps): Raise OpenEXR minimum from 2.3 to 2.4

- src/include/OpenImageIO/paramlist.h
- src/include/OpenImageIO/typedesc.h
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
- src/libutil/typedesc.cpp
- src/libutil/typedesc_test.cpp
I think it will be handy to be able to have ParamValue contain ustringhashes and have a TypeDesc that can describe it explicitly.
> api: extend TypeDesc and ParamType to represent ustringhash

- src/cmake/compiler.cmake
When building the code with Xcode ("cmake -G Xcode"), there are 1000+ warnings about implicit 64 to 32 bit conversion.
This change adds a compile option to suppress such warnings when generating an Xcode project.
None required
> build: suppress Xcode warnings

- src/bmp.imageio/bmpinput.cpp
fix #3947: runtime error: signed integer overflow in file src/bmp.imageio/bmpinput.cpp:302
- [Y] I have read the [contribution guidelines](https://github.com/OpenImageIO/oiio/blob/master/CONTRIBUTING.md).
- [Y] My code follows the prevailing code style of this project.
> fix runtime error: signed integer overflow in file src/bmp.imageio/bmpinput.cpp:302

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/ustring.h
- src/libutil/ustring_test.cpp
* Add string literal operators for ustring and ustringhash so you can write: ``` "foo"_us "bar"_ush ``` Note that on Cuda (but not on the host), this ustringhash construction is constexpr.
* Add a new `ustringhash(const char*, size_t)` constructor, which is also constexpr on the device side.
* Mark the existing `ustringhash(string_view)` constructor as constexpr on the device side.
We can mark those things as constexpr on the device side because on the Cuda side, the implementation only takes the hash (which is constexpr), and does not actually add a ustring to the table (which cannot be constexpr). To make such declarations easy, add a new macro to platform.h, `OIIO_DEVICE_CONSTEXPR` which is constexpr for the device, merely inline for the host.
> dev(ustring.h): string literal operator for ustring and ustringhash

- src/libtexture/texturesys.cpp
Disable GCC warnings around mismatched new/delete for shared_texturesys creation
> Silence gcc new/delete warnings for texturesys

- src/include/OpenImageIO/unittest.h
- src/libutil/timer_test.cpp
On overloaded VMs, the timer_test is ureliable and fails spuriously too often.
Two strategies in this patch, hope some combination does the trick:
1. Increase the absolute error allowed for the timing tests when doing CI runs.
2. Add just a bit more relative error (via a new unit test macro, OIIO_CHECK_EQUAL_THRESH_REL).
Hopefully this will cut down on CI failures for unit_timer test case.
> ci: Make more robust timer_test

- .github/workflows/ci.yml
- INSTALL.md
- src/cmake/testing.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imageio.cpp
- src/openexr.imageio/CMakeLists.txt
We had disabled the use of the "openexr core" library by default, even for OpenEXR versions that nominally support it, when it was discovered that it stil didn't support the DWA compression types.
That has finally been added to the OpenEXR trunk as well as the OpenEXR 3.1.10 release. When we are building against a sufficiently new OpenEXR to fully support all the compression types for exr core, then re-enable it by default.
Bump the "latest" CI tests to OpenEXR 3.1.11.
> exr: Re-enable openexr core default when recent enough

- src/libOpenImageIO/imageioplugin.cpp
Fixes a typo in the debug output triggered during the image plugin search sequence.
nonconforming.
> Fix typo in debug output

- src/cmake/externalpackages.cmake
Enable set of Boost_NO_BOOST_CMAKE through make using MY_CMAKE_FLAGS=-DBoost_NO_BOOST_CMAKE:BOOL=OFF.
> Added check for Boost_NO_BOOST_CMAKE, ignore if already set

- src/include/OpenImageIO/platform.h
- src/libutil/CMakeLists.txt
- src/libutil/filesystem.cpp
- src/libutil/plugin.cpp
- src/libutil/strutil.cpp
- src/libutil/sysutil.cpp
- src/libutil/thread.cpp
- src/libutil/timer.cpp
* Avoid possible double define of NOMINMAX in platform.h
* Move other Windows symbol definitions into the cmake file instead of
repeating them in certain .cpp files.
Fixes #3964
> build(win): Fix windows.h pre-definitions

- GOVERNANCE.md
Proposal from Thiago to add Jesse Yurkovich, representing Blender, to the TSC.
We didn't have voting member quorum at the latest TSC meeting, so we'll do the vote by PR.
Voting TSC members: please poke the "approve" button on this PR or add an comment denoting approval (or a nay vote if that is your preference).
> Admin: Add Jesse Yurkovich to the TSC

- RELICENSING.md
- src/ico.imageio/icooutput.cpp
- src/include/OpenImageIO/export.h
- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageioplugin.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
- src/libutil/filesystem_test.cpp
- src/libutil/thread.cpp
- src/oiiotool/imagerec.cpp
- src/testtex/testtex.cpp
- testsuite/runtest.py
- testsuite/texture-wrapfill/run.py
This is Update 4, the original PR is ongoing and we will continue to update as additional people relicense.
Per PR #3905 (https://github.com/OpenImageIO/oiio/pull/3905), update the RELICENSING document with the names of people and companies who have signed on to the relicensing thus far, and update the SPDX license notices on source files whose extant authorship (per 'git blame') comprises only authors who have relicensed.
> admin: Relicense code under Apache 2.0

- src/heif.imageio/heifinput.cpp
Typo introduced in #3894 broke our ability to build against libheif < 1.13. A conditional compilation that should have kicked in for >=1.16 was mistakenly written as 1.6.
> build: Fix broken libheif < 1.13

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
Advanced users know to check error returns and retrieve errors.
New users often just try OIIO calls with no error checks when they don't get behavior they want, ask questions to the dev team. We hypothesize that if they only saw the text of the error messages that they never retrieved, they could probably self-diagnose many of their problems.
This patch makes an ImageBuf, when it is destryed, print any pending error messages that were never retrieved. It happens by default, but can be disabled by setting the new global attribute "imagebuf:print_uncaught_errors" to 0 (it defaults to 1).
This doesn't cover everything, but for ImageBuf and ImageBufAlgo, maybe it will help some users? It could annoy advanced users who intend to not retrieve error messages (why?) but still don't want this …
> feat(ImageBuf): auto print uncaught IB errors

- .github/workflows/ci.yml
- INSTALL.md
- src/cmake/externalpackages.cmake
- src/include/OpenImageIO/detail/fmt.h
- src/include/OpenImageIO/strutil.h
Bump fmt minimum to 7.0 for OIIO 2.5.  fmt 7.0 is 3 years old, so let's stop doing extra work to support 6.x. It's not that we depend on newer features per se, but I'd like to no longer need separate reference output for some tests whose formatting behavior changed slightly between 6.x and 7.0.
Rig CI to properly test "latest" and "bleeding edge" fmt. It turns out we had not yet been testing 10.1 or keeping up with their master.
In the process, I discovered that the combo of fmt >= 10.1 and gcc >= 11 results in a mangled AVX math heisenbug, symptomatic in our simd_test.  I struggled with this on and off for many days, having great difficulty reproducing (though it does fail every time and deterministically, I just can't seem to narrow it to a smaller example). It only happens with gcc, …
> build: Bump fmt minimum 7.0, fix fmt+gcc bugs

- src/libutil/strutil.cpp
While testing out the 2.5 beta for use in Blender, I hit an odd build error[1] apparently related to include order. Apparently `windows.h` should be included before `shellapi.h`[2]. Swapping the order does fix things, however, it turns out neither is used in this particular file so just remove them both.  Unsure why we didn't see it until now.
[1]
```
20>[9/146] Building CXX object src\libutil\CMakeFiles\OpenImageIO_Util.dir\strutil.cpp.obj
20>FAILED: src/libutil/CMakeFiles/OpenImageIO_Util.dir/strutil.cpp.obj
20>cl : Command line warning D9002: ignoring unknown option '/arch:sse2'
20>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\shellapi.h(68): error C2146: syntax error: missing ';' before identifier 'DECLSPEC_IMPORT'
20>C:\Program Files (x86)\Windows …
```
> Remove unnecessary headers from strutil.cpp causing build trouble

- src/include/OpenImageIO/ustring.h
To my eyes, these two constructors look like they should be treated as doing exactly the same thing:
MyType()
: mymember(...)
{ }
and
MyType()
{
mymember = ...;
}
But nvcc in Cuda mode says no, if the constructor is constexpr, the former is okey dokey, but latter gives a warning. Fine, Cuda, whatver you say.
> fix(ustring): fix Cuda warnings

- src/python/py_imagecache.cpp
- testsuite/python-imagecache/ref/out-python27.txt
- testsuite/python-imagecache/ref/out-win.txt
- testsuite/python-imagecache/ref/out.txt
- testsuite/python-imagecache/src/test_imagecache.py
This C++ method of ImageCache was never exposed previously.
> feat(python): Implement ImageCache.get_imagespec()

- src/doc/builtinplugins.rst
- src/png.imageio/png_pvt.h
- src/png.imageio/pngoutput.cpp
* Implement PNGOutput::write_scanlines, previously we only had write_scanline. Sadly, being able to write multiple scanlines at once reduces overhead by much less than I had hoped. But there's a bit of savings, so I'll keep it.
* Rely on libpng's ability to do endianness byte swapping (for new enough libpng). This means that when we do need byte swapping and it's one of the cases where libpng can do it, we can avoid an extra copy.
* New compression recognized: "pngfast", which translates to the Z_BEST_SPEED setting. I don't particularly recommend this, but it's useful for benchmarking.
* New compression recognized: "none", which turns off compression. Also not recommended, as it makes the files much larger. Mostly done for benchmarking and other comparisons.
* Don't unconditionally copy …
> png: a variety of minor optimizations to the PNG writer

- src/libOpenImageIO/exif.cpp
When writing out EXIF headers in PNG files, the `tiff_version` field wasn't handling endianness properly.
This lead to some tools like `exiv2` refusing to process the file at all[1]
[1] https://github.com/Exiv2/exiv2/issues/2745
nonconforming.
> Write out proper tiff header version in png EXIF blobs

- .github/workflows/ci.yml
- CMakeLists.txt
- src/build-scripts/build_abi_tools.bash
- src/build-scripts/ci-abicheck.bash
- src/build-scripts/gh-installdeps.bash
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
This patch adds a new test to the CI matrix: verifying that we do not break the ABI during releases.
Basically, in addition to building the current checkout, it also builds a checkout of the designated "ABI standard" (generally, the first non-beta release of a major version), then generates ABI dumps of both versions and runs the ABI compliance checker using the tools from https://github.com/lvc
Making two builds sounds expensive, but both builds are rigged to be minimal, since only the main two libraries are needed for ABI checks (we can turn off the binary tools, unit tests, python bindings, and support for many formats), and of course the test suite need not run. So actually, it's less expensive than most of the test matrix entries, and it helps ensure that we don't accidentally break …
> build: Test ABI compliance

- src/ffmpeg.imageio/CMakeLists.txt
- src/heif.imageio/CMakeLists.txt
Trying out my first Mackerel from:
https://github.com/OpenImageIO/oiio/issues/3916
> Print build-time warnings for LGPL gotchas

- testsuite/docs-examples-cpp/CMakeLists.txt
- testsuite/docs-examples-cpp/run.py
- testsuite/docs-examples-cpp/src/docs-examples-imagebuf.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imagebufalgo.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imagecache.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imageioapi.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imageoutput.cpp
- testsuite/docs-examples-cpp/src/docs-examples-texturesys.cpp
- testsuite/docs-examples-cpp/src/docs-examples-writingplugins.cpp
- testsuite/docs-examples-python/run.py
- testsuite/docs-examples-python/src/docs-examples-imagebuf.py
- testsuite/docs-examples-python/src/docs-examples-imagebufalgo.py
- testsuite/docs-examples-python/src/docs-examples-imagecache.py
- testsuite/docs-examples-python/src/docs-examples-imageinput.py
- testsuite/docs-examples-python/src/docs-examples-imageioapi.py
- testsuite/docs-examples-python/src/docs-examples-imageoutput.py
- testsuite/docs-examples-python/src/docs-examples-texturesys.py
- testsuite/docs-examples-python/src/docs-examples-writingplugins.py
I had previously prototyped an instance of this for the ImageOutput chapter.
This patch makes empty placeholders for all of the other API chapters. They don't contain any actual tests or generate any output now, but they do build and run, so people can drop new examples into them without having to worry about how to set up new files for each chapter.
> testing: Set up placeholders for docs-examples-are-tests

- src/doc/oiiotool.rst
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageio_pvt.h.in
- src/oiiotool/oiiotool.cpp
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imagebuf/src/test_imagebuf.py
The behavior of ImageBuf has always been that an IB referencing from a file is backed by ImageCache unless you carefully use read() with the "force" parameter set to true.  The IC can be really helpful if you only need *part* of the file, or if you have so many large IB's at once that you want IC to manage the memory for you to keep the total reasonable.
Over the years, I've started to wonder if this was the right approach for the default.  It's much more typical that IBs aren't big enough or numerous enough to gain much from the IC, and it's usually worse performance to have it IC-backed. Plus, now the properties of the ImageCache (size, behavior for nontiled images, etc.) can affect the performane of ImageBuf without users understanding why.
So this patch tries on a different approach: …
> ImageBuf: Only back IB with IC when passed an IC

- README.md
- src/doc/Building_the_docs.md
For the upcoming DevDays, I wanted to spruce up our main README to make it easier to find info, and I wrote a new guide for how to locally build the documentation.
> docs: Spruce up the main README and add "Building_the_docs"

- src/include/OpenImageIO/fmath.h
It was possible for `bit_range_convert` to be called with a 0 for the `FROM_BITS` parameter leading to an infinite loop in its processing.
Fixes #3993 
The test image from the above bug is now able to be read correctly.
nonconforming.
> Prevent infinite loop in bit_range_convert

- src/libtexture/imagecache_pvt.h
A static_assert was added recently as part of PR #3898, which assures that the size of a TileID is a multiple of 8 bytes. But on architectures with 32 bit pointers, this assertion fails. Which is not quite what we want, because the code isn't wrong if the struct isn't a multiple of 8 bytes; it's just less efficient. And we don't want to fail for 32 bit arch.
Bottom line: only do this check to ensure we're in the most efficient case if we're 64 bits. Nobody's expecting highest performance on a 32 bit machine anyway.
Fixes #4001
> build: Don't fail for 32 bit builds because of static_assert check

- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
The following sequence would have a floating point exception:
// Readable IB backed by ImageCache
ImageBuf buf("file.exr"),  0, 0, ImageCache::create());
// Make a mutable iterator, even though it's an image file reference.
ImageBuf::Iterator<float> it(buf);  <----- CRASHES INSIDE HERE!
The problem was in ImageBuf::IteratorBase::init_ib, several steps taken if it's a mutable IB looking at a "read-only" IC-backed file, including calling make_writable() on teh buffer. But we neglected to set m_localpixels to true.
Fixes #3770
> fix(ImageBuf): fix crash when mutable Iterator used with read-IB

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageio.cpp
- src/libtexture/imagecache.cpp
- src/oiiotool/oiiotool.cpp
In the ongoing effort to help newcomers to OIIO diagnose their own problems, this uses a trick to print any global error messages that never got retrieved by OIIO::geterror() at the time that the program exits.  (This is all similar to a change we made recently that adds an analogous behavior to ImageBuf, but in this case it's for those error messages that don't have an object like an ImageBuf to attach to.)
This should have no effect on anybody who diligently checks OIIO::has_error() or OIIO::geterror() after any failed calls that would send error messages to that global store. Also, it is possible to disable the behavior by setting the new global attribute "oiio:print_uncaught_errors" to 0.
But for users who don't know to check errors and are experiencing baffling behavior with OIIO, …
> feat: print unretrieved global error messages

- src/libOpenImageIO/maketexture.cpp
Our exr writer uses some special hints starting with "openexr:" to control aspects of the writing, and the reader sets these to communicate some things about the file it's reading.
But what happens if... the actual exr file has metadata of tha same name. Oops, those get carried along and mess with things. We had previously accounted for this by suppressing arbitrary metaname named "openexr:lineOrder" if we find it in the input (the actual lineorder comes from a header field, not named metadata, but OIIO uses the name "openexr:lineOrder" to communicate it back as metadata.
Turns out that there are two more that we need to proactively suppress: "openexr:levelmode" and "openexr:roundingmode". There's no good reason for those to ever be in an exr file (like I said, those names are NOT how …
> fix(exr): suppress exr attributes that interfere with our hints

- src/doc/idiff.rst
- src/idiff/idiff.cpp
Teach `idiff` to accept a directory as the 2nd argument.
Fixes #4009
Functional tests for `idiff` don't currently exist. Manual testing verifies it works as advertised.
(adding new test cases if necessary). (N/A)
exposed the new functionality as oiiotool options). (N/A)
nonconforming.
> idiff: allow users to specify a directory as the 2nd argument

- src/doc/imagebufalgo.rst
- testsuite/docs-examples-cpp/ref/out.txt
- testsuite/docs-examples-cpp/run.py
- testsuite/docs-examples-cpp/src/docs-examples-imagebufalgo.cpp
- testsuite/docs-examples-python/ref/out.txt
- testsuite/docs-examples-python/run.py
- testsuite/docs-examples-python/src/docs-examples-imagebufalgo.py
Convert C++ and Python examples from the "imagebufalgo" chapter into tests within the "docs-examples" testsuites (#3992).
nonconforming.
> docs: Convert examples within the imagebufalgo chapter.

- src/libOpenImageIO/imagebufalgo_opencv.cpp
We were using parallel_convert_image but not realizing that asking for the IB::localpixels() would give us nullptr for an IC-backed image.
Instead, "wrap" the cv::Mat with an IB and then use IBA::copy().  This handles both in-memory and IC-backed ImageBuf's, and also has many other advantages (such as format conversion) we may wish to take advantage of in the future.
Fixes #3800
> fix: to_OpenCV fails for ImageCache-backed images

- src/doc/imageinput.rst
- testsuite/docs-examples-cpp/ref/out.txt
- testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
- testsuite/docs-examples-python/src/docs-examples-imageinput.py
Added the simple input tests from the ImageInput chapter of the docs as C++ and Python examples, a part of the larger issue #3992 . Followed prototype (https://github.com/AcademySoftwareFoundation/OpenImageIO/wiki/Converting-documentation-examples-to-tests) approach.
nonconforming.
> Added tests for Simple Image input and updated rst

- INSTALL.md
- src/cmake/externalpackages.cmake
Looks like OpenVDB >= 10.0 requires a minimum of C++17. Warn at build time if trying to use an OpenVDB too new for the C++ compiler being used.
> build: Protect against mismatch of OpenVDB vs C++

- Makefile
- site/spi/Makefile-bits
- src/cmake/compiler.cmake
This is for master only! Will not be backported to any release branch.
We are assuming the 2.5 release family will be the last to support C++14, and the next year's 2.6 family will raise the minimum to C++17. We're not ready to throw that switch yet, but as an intermediate step, let's raise the *default* level to C++17. It's still possible to compile for C++14, but to do so, one must proactively `-DCMAKE_CXX_STANDARD=14`.
This has two benefits:
1. The majority of people who are already using a C++17-capable compiler will take advantage of those features by default, instead of needlessly restricting to C++14.
2. The people using a compiler that tops out at C++14 (e.g., gcc 6.3) are going to have to set `-DCMAKE_CXX_STANDARD=14`, thus making them aware that (in master anyway) they're …
> build: Make C++17 be the default (C++14 is still the minimum for now)

- src/cmake/externalpackages.cmake
Revision of PR #4023
I have since determined that although OpenVDB raised their own build requirements to C++17 starting with 10.0, it wasn't until 10.1 that C++17-isms crept into their header files and force downstream projects to need C++17 to consume OpenVDB's headers. So we can go back to allowing use of OpenVDB 10.0 even when we are building with C++14.
> build: Adjust OpenVDB version requirements vs C++17

- src/doc/builtinplugins.rst
- src/raw.imageio/rawinput.cpp
``raw:threshold``
- float
- Libraw parameter for noise reduction through wavelet denoising..
The best threshold should be somewhere between 100 and 1000.
- ``raw:fbdd_noiserd`` - int - Controls FBDD noise reduction before demosaic. 0 - do not use FBDD noise reduction, 1 - light FBDD reduction, 2 (and more) - full FBDD reduction
nonconforming.
> LibRaw wavelet denoise options

- src/doc/imagebufalgo.rst
- testsuite/docs-examples-cpp/ref/out.txt
- testsuite/docs-examples-cpp/run.py
- testsuite/docs-examples-cpp/src/docs-examples-imagebufalgo.cpp
- testsuite/docs-examples-python/ref/out.txt
- testsuite/docs-examples-python/run.py
- testsuite/docs-examples-python/src/docs-examples-imagebufalgo.py
Takes the make_texture section of the imagebufalgo doc and turns it into a unit test in both python and c++.
This adds a make_texture section to the `docs-examples-cpp` test and the `docs-examples-python` test.
nonconforming.
> make_texture doc2test

- src/iv/imageviewer.cpp
- src/iv/imageviewer.h
This change adds a menu item "Split off" under the menu "File" which creates a new window and initialises it with the currently displayed image. 
I have tested the UI changes on Mac and linux, I don't have a Windows machine currently. 
No other functionality should be affected by this change.
nonconforming.
> feat: split off the current image in iv into a separate window (#2058)

- src/libOpenImageIO/imagebuf_test.cpp
To help with some other investigation I'm doing, amend imagebuf_test with benchmarks to compare the relative speeds of traversing a big ImageBuf with Iterator, ConstIterator, or just using pointers on an equivalently large array.
> testing: imagebuf_test add benchmarks for iterator traversal

- .readthedocs.yml
RTD recently cut off old configuration file style and these additions were needed.
> docs: Fix RTD configuration for v2

- src/include/OpenImageIO/sysutil.h
- src/libutil/atomic_test.cpp
- src/libutil/sysutil.cpp
It is a implemented by simply wrapping boost::physical_concurrency(). So this is one more step in eliminating boost from our requirements.
Until it's fully removed, just make it be a synonym for hardware_concurrency().
We don't seem to use physical_concurrency anywhere, and I'm not sure what it's good for. The underlying boost impementation just falls back to hardware_concurrency on many platforms or circumstances.
Note for the record that Sysutil::hardware_concurrency() is also redundant, and merely wraps the std::thread function of the same name.
> Deprecate Sysutil::physical_concurrency()

- testsuite/tiff-misc/ref/out-libtiff403-b.txt
- testsuite/tiff-misc/ref/out-libtiff403-c.txt
Everything works, no code changes needed. But with some libtiff builds, there is some variation in exactly which error messages bubble up when reading certain corrupted files. This fixes some recently broken CI.
> ci: Add tiff-misc reference for slightly changed error messages

- .github/workflows/ci.yml
It's started failing on GHA and is old enough that it's not worth trying to track down what's broken. We still have MacOS 12 and 13 tests in the matrix.
> ci: Remove MacOS-11 test

- .github/workflows/ci.yml
- INSTALL.md
Switch "bleeding edge" test to gcc13, "latest releases" test to gcc12
> ci: test against gcc-13

- .clang-format
Used to be no problem, but after a recent VSCode update, this seems to have been causing errors when asking VSCode to format. No idea why this recently became problematic.
> fix: Remove redundant line in .clang-format

- CMakeLists.txt
- src/libOpenImageIO/color_ocio.cpp
- src/oiiotool/oiiotool.cpp
- src/raw.imageio/rawinput.cpp
- src/term.imageio/termoutput.cpp
The important bug fix is in oiiotool image input when autocc is used, where we reversed the sense of a test and did the autocc-upon-input if the file's color space was equivalent to the scene_linear space (pointlessly), and skipped the conversion if they were different (oh no, big bug!).
Along the way:
* Add missing try/catch around OCIO call that should have had it.
* Some very ugly SPI-specific recognize-by-name color space heuristics. I hate this, sorry, but it solves a really important problem for me.
* A bunch of additional debugging messages during color space inventory, enabled only when debugging, so nobody should see these but me.
* A couple places where we canonicalize the spelling of "oiio:ColorSpace".
Note that there is still an issue with the color space classification using …
> fix(oiiotool): --autocc bugfix and color config inventory cleanup

- src/include/OpenImageIO/simd.h
A recent change (PR 4026) tried to include Imath.h in cases where there was no SSE support (to provide a fallback implementation of matrix invert, because simd.h's native one requires SSE), but it had a mistake -- it used `#if !OIIO_SIMD_SSE` prior to that symbol being defined! This caused the header to always be included, which is not what we wanted, as we desired for that header to not be exposed in the public headers.
This patch offers a temporary/partial fix by simply moving that guarded include later in the file to after OIIO_SIMD_SSE is defined. For architectures that support SSE, at least, this achieves our goal of not exposing Imath.h in public headers.
I need this patch right away to solve a particular problem I'm running into.
Longer term, we note that this isn't a full solution …
> fix(simd.h): fix leaking of Imath.h into public headers

- src/idiff/idiff.cpp
- testsuite/diff/ref/out-fmt6.txt
- testsuite/diff/ref/out.txt
- testsuite/diff/run.py
- Fix perceptual test false positive by removing the initialization of `cr` to avoid losing the information when leaving block scope
Included additional test with parameter `-fail 1`, which was giving a false positive pass for a perceptual difference. 
This was due to the fact that the result variable `cr` was getting out of scope for the perceptual calculation and the first `if (cr.nfail <= imagesize_t(allowfailures)) {` was testing for the result of the absolute difference instead of the perceptual difference.
Before:
```
Comparing "img1.exr" and "img2.exr"
PASS
```
After:
```
Comparing "img1.exr" and "img2.exr"
64 x 64, 3 channels
Mean error = 0
RMS error = 0
Peak SNR = 0
Max error  = 1 @ (5, 17, R)  values are 0.1, 0.1, 0.1 vs 0.1, 0.6, 0.1
0 pixels (0%) over 0.008
121 pixels (2.95%) …
```
> fix(diff): Fix issue when computing perceptual diff

- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
Add a few more assertion checks and error messages in imagebufalgo_test.
I observe that if somebody runs the testsuite with `$OCIO` set to a config that doesn't contain the required color space names for this test, it will fail. As a backstop, use the default built-in config if the initial request fails. That will always give a working processor between these spaces if OCIO >= 2.2 is being used.
Also one more tiny SPI-specific enhancement to hacky identification of nonconforming color space names in our old configs.
> test: improve color management test in imagebufalgo_test

- testsuite/python-colorconfig/ref/out-ocio22-python27.txt
Slightly different output to match for the combo of OCIO >= 2.2, but simultaneously Python 2.7 -- which was not in our CI test matrix, so I missed it, but ran into it at work.
> test: Add one more ref output for python-colorconfig test

- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
vint4::load from unsigned char pointer got pre-SSE4 code path. Testing on Ryzen 5950X / VS2022 (with only SSE2 enabled in the build):
- vint4 load from unsigned char[]: 946.1 -> 4232.8 Mvals/sec
vint4::store to unsigned char pointer got simpler/faster SSE code path, and a NEON code path. Additionally, it got test correctness coverage, including what happens to values outside of unsigned char range (current behavior just masks lowest byte, i.e. does not clamp the integer lanes).
- vint4 store to unsigned char[]: 3489.8 -> 3979.3 Mvals/sec
- vint8 store to unsigned char[]: 5516.9 -> 7325.3 Mvals/sec
NEON code path as tested on Mac M1 Max (clang 15):
- vint4 store to unsigned char[]: 4137.2 -> 6074.8 Mvals/sec
vint4 store to unsigned char pointer got actual correctness checking test, which …
> SIMD: faster vint4 load/store with unsigned char conversion

- src/ptex.imageio/CMakeLists.txt
In some environments, only one kind of the library could be available.
Choose proper fallback in such cases. Prefer static library, if
LINKSTATIC is ON and dynamic otherwise.
nonconforming.
> ptex: support for static library

- src/jpeg2000.imageio/jpeg2000input.cpp
- src/jpeg2000.imageio/jpeg2000output.cpp
Without getting the version properly, we weren't disabling use of a deprecated field for OpenJpeg >= 2.5, as we thought we were.
This fixes recently broken CI when building against the current openjpeg master.
> fix(jpeg2000): include the headers we need to discern version

- src/png.imageio/pngoutput.cpp
There was a flaw in PNGOutput::write_scanlines when the y range of scanlines to write consisted of less than the whole image, and alpha de-association was needed -- we used the whole-image size instead of the y range of scanlines size.
Fixes #4044
> fix(png): Fix crash for writing large PNGs with alpha

- .github/workflows/macarm.yml
I didn't have the condition right -- the `if` isn't respected in the `pull_request` section, so this job was running on every PR instead of just the ones with "macarm" in the branch name. But I think `branches` works with `pull_request`.
> ci: restrict Mac ARM running

- src/libOpenImageIO/imageioplugin.cpp
Fix for #4084. Will now check if the given filename exists before checking for REST parameters.
I did not look into test cases for this, but I ran the following command before and after the change:
Before:
```
bin % ./oiiotool \?.png -o \?-output.png
oiiotool ERROR: read : "?.png": ImageInput::create() called with malformed filename
Full command line was:
> oiiotool ?.png -o ?-output.png
```
After: 
```
bin % ./oiiotool \?.png -o \?-output.png
```
No output, `?-output.png` created.
test that runs clang-format and fix anything that it highlights as …
> Only check REST arguments if the file does not exist

- INSTALL.md
Minimal change to update link to OpenEXR's new Test Images page. I poked around a bit to find a "friendlier" variant of the link but could find none.  
Note that the section containing this link implies that folks need to download these files themselves and should be "placed in a sibling directory to oiio-testimages". The problem is that not even OpenEXR lists the repository for the test images nor does the page linked above offer a download.
Should we list out the openexr-images repo address too and say to just clone that?
Fixes #4042
test that runs …
> Fix link to openexr test images

- src/libOpenImageIO/imagebufalgo_channels.cpp
For the in-place case (where src and dst refer to the same IB), we were doing an unnecessary full-image copy.
> perf: Improve perf of IBA::channels in-place operation

- src/iv/CMakeLists.txt
It's a little involved to explain why, but at work a combination of libraries and some trickery with static linkage led me to really need a way to inject another library into the mix, just for iv linkage.
> build: Add a way to cram in a custom extra library for iv

- src/iv/ivgl.cpp
For image with more than 4 channels, we were misallocating the OpenGL buffer by using the total channels instead of the 4 we wanted to create the texture out of. Also, make sure the calculation usees wide types to avoid possible integer overflow.
> fix(iv): avoid crash with OpenGL + multi-channel images

- testsuite/docs-examples-python/run.py
- testsuite/docs-examples-python/src/docs-examples-imagebufalgo.py
We did `import OpenImageIO as oiio` then instead of using `oiio`, we used `OpenImageIO`.
This was failing sometimes. Frankly, I'm not sure why it ever worked.
Maybe it works on some versions of Python but not others?
I dunno. But this fixes it everywhere and is clearly correct.
> test: Fix docs test, used wrong namespace

- src/include/OpenImageIO/fmath.h
Use gcc __builtin_bit_cast when available.
Get rid of specializations -- they are not needed, as verified by godbolt.
> OIIO::bitcast adjustments

- src/libOpenImageIO/CMakeLists.txt
Remove duplicate dependecy for OpenImageIO_Util to fmt.
OpenImageIO target already depends on fmt through OpenImangeIO_Util library.
nonconforming.
> clean up after removing Findfmt.cmake

- src/raw.imageio/rawinput.cpp
If you are looping i over range [0,width), and want index to go the other direction, you need `index = width - 1 - i`, not `index = width - i`.
Identified by Sonar static analysis.
> fix(raw): Avoid buffer overrun for flip direction cases

- src/doc/imagebufalgo.rst
The function signatures in the header didn't match those in the docs, after some previous changes. It's probably been broken in the docs for some time. Nobody noticed?
> docs: Fix broken IBA color management documentation

- src/dpx.imageio/libdpx/WriterInternal.h
- src/libOpenImageIO/imagebufalgo_mad.cpp
- src/oiiotool/printinfo.cpp
- src/png.imageio/pngoutput.cpp
- src/testtex/testtex.cpp
* pngoutput.cpp: Catch possible exceptions.
* printinfo.cpp: assertions to assure we don't dereference a null pointer.
* testtex.cpp: make sure allocated chunk is initialized
* WriterInternal.h: Catch condition that could lead to buffer underflow.
* imagebufalgo_mad.cpp: Simplify pointless clause. The prior test was redundant. Since a few lines above, if B was an image but A was not, we swapped to ensure that A was always an image. So here, we can just test A to know for sure that at least one of them is an image. That makes the test here simpler, but it also makes it more clear to static analysis that from this point forward, A can't be nullptr.
> Fixes to reduce problems identified by static analysis

- src/include/CMakeLists.txt
- src/include/OpenImageIO/detail/fmt.h
- src/include/OpenImageIO/typedesc.h
- src/include/OpenImageIO/ustring.h
Bleeding edge CI test failures due to more changes in fmt's trunk. Solutions:
* Accommodate some recent header refactoring in fmt.
* Straighten up some const issues that worked before, but break under the latest fmt. Making the custom formatter's 'format' method be const fixes the latest, but breaks some of the oldest versions of fmt we support, so we add the const only from fmt 9.0 on.
> build(deps): deal with changes in fmt's trunk

- src/include/OpenImageIO/simd.h
This PR fixes vfloat16 round function. Intrinsic `_mm512_roundscale_ps` was
used incorrectly, and caused failure on Zen4 CPU.
```
/var/tmp/portage/media-libs/openimageio-2.5.5.0-r1/work/OpenImageIO-2.5.5.0/src/libutil/simd_test.cpp:1579:
FAILED: round(F) == mkvec<VEC>(std::round(F[0]), std::round(F[1]), std::round(F[2]), std::round(F[3]))
values were '-1.5 0 1.5 4 -1.5 0 1.5 4 -1.5 0 1.5 4 -1.5 0 1.5 4' and '-2 0 2 4 -2 0 2 4 -2 0 2 4 -2 0 2 4'
``` 
In old code `_mm512_roundscale_ps (a, (1<<4) | 3)` meant the following:
```
[0001] - Number of fixed points to preserve
[0] - Use MSCSR exception mask
[0] - Select mode from imm
[11] - Truncate mode
```
Effectively enabling rounding to nearest 0.5, not to integer.
References:
* https://www.felixcloutier.com/x86/vrndscalepd#fig-5-29
* …
> Fix AVX-512 round function

- src/cmake/externalpackages.cmake
OpenVDB >= 10.1 is incompatible with building OIIO using C++14. We had tried to disable this disallowed combination, but a typo prevented it from working properly.
> build: correctly disable OpenVDB when it's incompatible

- src/iv/imageviewer.cpp
A better default for users is probably to assume a 2.2 value if the GAMMA env variable is not set. If you want something different, set GAMMA proactively or use a real color managed workflow.
Will this break anybody in important ways?
Fixes #318
> iv: Assume iv display gamma 2.2

- src/libutil/paramlist_test.cpp
- src/libutil/typedesc.cpp
We had all along omitted an important 'int' conversion case for an internal to_floats() helper function that's used by the TypeDesc::convert_type utility. Which is in turn used by ParamValue::get_float() and ParamValueList::get_float().
All of these would fail to return the proper float if the underlying data was an int, despite these functions saying that they would have no trouble returning the float equivalent of int data when asked.
I added a test that verifies that it's wrking.
> fix: certain int->float type conversions in TypeDesc/ParamValueList

- src/include/OpenImageIO/paramlist.h
- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/span_util.h
- src/libOpenImageIO/deepdata.cpp
- src/libutil/paramlist_test.cpp
- src/libutil/span_test.cpp
* New header span_util.h with span-related helpers: 
- make_span/make_cspan helps for converting vectors & arrays to spans when passing to templated functions. 
- spancpy, spanset, spanzero are memory-safe, range-checking substitutions for memcpy, memset when working with spans.
* Add range check DASSERT to span access in debug mode. There were a couple spots where we were taking the address of an out-of-range value that needed to be adjusted to use a better idiom.
* ParamValue: extra OIIO_DASSERT range check for get() method.
* Simplify constructors by replacing `&x[0]` with using `data()`, which is always well-defined.
* Fix typos in span.h comments
The range checking imposes no extra cost for release/optimized builds. But it might help us for CI analysis and any time we're debugging.
> span and range checking enhancements

- src/cmake/externalpackages.cmake
Fixes #4135 
Thanks to @OgreTransporter for the suggestion.
> build: don't fail pybind11 search if python is disabled

- .github/workflows/analysis.yml
- src/jpeg.imageio/jpegoutput.cpp
- src/jpeg2000.imageio/jpeg2000input.cpp
- src/libtexture/texturesys.cpp
- src/oiiotool/printinfo.cpp
* jpeg output: Extra memory check
* TS: batch texture call fixed to handle any number of channels
* TS: assert to guard against possible null pointer dereference
* oiiotool printinfo: clarify assertion for the sake of static analysis
* jpeg2000 reader: assertion to ensure we don't dereference a null pointer
> Internals: various fixes for memory safey and reduce static analysis complaints

- src/oiiotool/oiiotool.cpp
- testsuite/perchannel/ref/out.txt
- testsuite/perchannel/run.py
Remember that ImageBuf only stores one pixel data type per buffer, but of course they may have differing-per-channel types in image files. So how does oiiotool know what to write? There is a series of heuristics: -d is for explicit user control, if not, then try to deduce it from the input files.
A bedrock precept is that `oiiotool in.exr -o out.exr` ought to write the same channel types that it read in.
The logic to implement this with the various image operations and possible overrides can be hard to get right. Indeed, I did not get it right. It made mistakes even in simple cases like the above. And the code was complicated and hard to understand, as well.
This PR rewrites a couple functions that implement this chunk of this logic, both correcting several errors as well as (I hope) …
> fix(oiiotool): Overhaul and fix bugs in mixed-channel propogation

- src/gif.imageio/gifinput.cpp
- src/iff.imageio/iff_pvt.h
- src/iff.imageio/noproxy-iff_pvt.cpp
- src/include/OpenImageIO/oiioversion.h.in
- src/jpeg.imageio/jpeginput.cpp
We did this separately each place we needed it. Do it just once, in a public header, and give it a name that won't clash with other packages.
> cleanup: Coalesce redundant STRINGIZE macros -> OIIO_STRINGIZE

- src/iff.imageio/iffoutput.cpp
Static analysis has been yelling about code in iffoutput.cpp possibly overrunning buffers, and frankly the code in this module is so confusing that I can't tell if it's correct or not. (It's 13 years old, hasn't been touched for a long time.)
In an ideal world, this would all be rewritten to use spans so the buffer lengths are known and checked. But I don't really have the time or inclination to rewrite it -- after all, iff is not a very important file format, though I do think it's used enough that we can't drop it entirely.  The payoff from a full rewrite is marginal. So I came up with the following compromise, embodied by this PR:
I'm making spans of the regions we're ultimately reading from and writing to, passing those down the chain of function calls, and so even though the actual …
> safety: refactor iffoutput.cpp for memory safety

- src/libOpenImageIO/imageio.cpp
* Make sure clang variants are before clang and things that might emulate gcc are before gcc.
* Use the right symbol for detecting ICC
* Capitalize `__linux__` correctly, oops.
> fix: Fixes to buildinfo queries

- src/include/OpenImageIO/typedesc.h
Signed-off-by: Scott Wilson <scott@propersquid.com>
This PR is for allowing the TypeDesc type to be used directly in a C API without indirection, and therefore also in a Rust API without indirection.
I added static asserts for the TypeDesc so it should validate if the struct is okay at compile time.
nonconforming.
> Allow TypeDesc to be used directly in a C API by forcing it to be POD.

- src/cmake/testing.cmake
- src/doc/builtinplugins.rst
- src/doc/imageinput.rst
- src/doc/stdmetadata.rst
- src/heif.imageio/heifinput.cpp
- testsuite/heif/ref/out-libheif1.4.txt
- testsuite/heif/ref/out-libheif1.5.txt
- testsuite/heif/ref/out-libheif1.9-with-av1.txt
- testsuite/heif/ref/out-libheif1.9.txt
- testsuite/heif/run.py
It seems that unlike most image formats where we merely note the camera rotation but don't rotate the pixels, the heic reader automatically rotated.
The trick is that using the C++ API wrapper of libheif, there is no way to pass the decoder options struct that is where you need to say not to auto-transform.  Needed to drop down to the lower level C API for this one spot.
We want this format to behave like the others -- the orientation is advisory, and it's up to the app how to deal with it. But we have back compatibility to deal with.
If a rotated image is aecountered, OIIO 2.5 and earlier will by default still auto-rotate to preserve compatibility, but OIIO 2.6+ will not auto-rotate.
When not rotating, the Orientation metadata will reflect the desired display orientation of the image, …
> fix(heic): Don't auto-transform camera-rotated images

- .github/workflows/ci.yml
Not much to say here, it worked the first time as soon as the new containers were published.
> ci: Add vfx platform 2024

- .github/workflows/ci.yml
- CMakeLists.txt
- src/doc/imagebufalgo.rst
- src/include/OpenImageIO/filter.h
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/paramlist.h
- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/typedesc.h
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libutil/filter.cpp
- src/libutil/filter_test.cpp
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
- src/libutil/typedesc_test.cpp
Many IBA functions take lots of optional parameters, which are from time to time augmented, leaving us with a clutter of semi-deprecated versions.
This PR prototypes a new approach, which is to make IBA functions have explicit parameters for their core/necessary controls, and the minor optional behavioral control parameters are passed as keyword/value argument lists. I think this has a few really big advantages over explicit parameter lists with ever-growing optional parameters:
1. It makes the call sites very readable, since the keywords document what the parameters do.
2. It allows us to add (or deprecate) optional parameters without ABI breaking changes, and without proliferation of many versions of each function.
A new class is added: ParamValueSpan, which as the name implies, is …
> api: prototype using optional keyword/value params for ImageBufAlgo

- src/libOpenImageIO/color_ocio.cpp
Automatically recognize some additional color space name synonyms:
"srgb_texture", "lin_rec709" and "lin_ap1" are names that MaterialX and USD use as canonical names.
Also add common permutation "srgb_tx" and "srgb texture" as additional aliases for srgb.
Fixes #4165
> fix: Add some color space aliases

- src/libOpenImageIO/imagebufalgo_draw.cpp
A variable was declared unconditionally but only used when Freetype is enabled. Move its declaration to be within the right conditional, on order to avoid compiler warnings about unused static variables.
> fix(build): Fix warning when Freetype is disabled

- .github/workflows/ci.yml
We had picked a version that is too new to run on the ASWF docker containers, so wasn't actually working properly when CI failed and we wanted the artifact uploaded.
> ci: Adjust GHA upload-artifact action version

- src/libutil/strutil.cpp
- src/libutil/strutil_test.cpp
Remove boost from `Strutil`. Use existing mechanisms and STL features instead. 
Relates to #4158
nonconforming.
> Remove boost from strutil.cpp

- src/include/OpenImageIO/simd.h
- src/libutil/simd_test.cpp
The operation it's supposed to be performing is to merge in the gathered value where the mask is set, and leave mask=0 lanes unchanged. But for our "no SIMD" fallback (i.e., no AVX2 for 4- and 8-wide), we incorrectly implemented it as setting the unmasked lanes to 0!
This was quite wrong, and unfortunately masked by the fact that our test of the function initialized a variable to 0. Change to a better number. The best number.
> fix(simd.h): gather_mask was wrong for no-simd fallback

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/heif.imageio/heifinput.cpp
We inadvertently started using libheif functions that only became available in their version 1.16.0. Guard against that and now we recommend at least that version (but we aren't yet changing the minimum requirement). This fixes a build break introduced in #4142 (but only breaks for older libheif).
> fix(heif): Fixes to recent orientation support

- src/openexr.imageio/exroutput.cpp
Apparently, the specific combination of not having OCIO available at build time, and C++17 or higher, and we were missing one header we needed in this module.
> build: need additional include

- .github/workflows/ci.yml
- src/build-scripts/gh-win-installdeps.bash
Needed some fixups with its python version to get it fully working.
> ci: Enable Windows 2022 CI tests

- src/libutil/CMakeLists.txt
Add a `OpenImageIO_BUILD_STATIC_UTIL_LIBRARY` CMake variable that, if enabled, will build a separately named static version of the OpenImageIO_Util library, in addition to the dynamic one. It has a separate name, libOpenImageIO_Util_static, and a separate exported cmake target, `OpenImgaeIO::OpenImageIO_Util_static.`
This can be a help to applications that only need OpenImageIO_Util, and not the main OpenImageIO library, and furthermore would prefer a static library so they don't need a runtime dependency on our dynamic libraries.
Cavat emptor: Beware that there are singletons inside ustring, the oiio thread pool, and possibly others I'm not remembering at the moment. It could be a bad thing to have an application that contains both the static and dynamic versions of libOpenImageIO_Util, …
> build: make an OpenImageIO_Util_static library and target

- src/include/OpenImageIO/span.h
> refactor: Make span default ctr and assignment be `= default`

- src/iv/ivgl.h
[BUG] glTexImage3D not in QOpenGLFunctions but in QOpenGLExtraFunctions https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/4180
CMake and VS compiling iv without issues
nonconforming.
> bugfix: glTexImage3D

- src/cmake/modules/FindOpenColorIO.cmake
... in the OCIO 1.x case where we relied on our own Find module rather than an exported cmake config from OCIO itself. This is desired for uniformity of naming with the exported configs of the later versions.
> build: FindOpenColorIO failed to properly set OpenColorIO_VERSION

- CMakeLists.txt
- src/cmake/checked_find_package.cmake
- src/cmake/compiler.cmake
- src/cmake/externalpackages.cmake
- src/cmake/fancy_add_executable.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
- src/nuke/txReader/CMakeLists.txt
- src/nuke/txWriter/CMakeLists.txt
- src/python/CMakeLists.txt
We had lots of stray usage of add_defintions, add_compile_options,
etc.  In modern cmake, this is considered bad form, since it makes
subprojects pollute the global option lists. A better way is to add
all these to specific targets, so now that's what we do in this PR.
This should make all the definitions and options we want to set for
compilng OIIO's code not have any interference with subprojects, or
with higher-level surrounding projects.
> build: switch to target-based definitions

- src/include/OpenImageIO/texture.h
- src/libtexture/texoptions.cpp
For OSL, we want to be able to decode a wrapmode directly from a ustringhash without having to expensively convert it to ustring.
nonconforming.
> Overload decode_wrapmode to support ustringhash

- src/cmake/checked_find_package.cmake
- src/cmake/externalpackages.cmake
Add another optional flag to our checked_find_package cmake function -- CONFIG means only accept a config for the package, never use a FindBlah.cmake module.
(Reminder: this is in contrast to the existing PREFER_CONFIG option, which tries a config first, then if that fails, will try the module, and also different from the default if neither is used, which is to prefer the module over the exported config.)
And rig our search for DCMTK to use the new CONFIG option. There is a FindDCMTK.cmake modules that comes with cmake, and for at least some versions of cmake, it seems subtly broken in such a way that actually wrecks our finding of other packages properly.
> build: have checked_find_package accept CONFIG, fix DCMTK

- src/include/OpenImageIO/detail/farmhash.h
- src/include/OpenImageIO/strutil.h
- src/libutil/strutil_test.cpp
> fix: Restore internals of strhash to compile on 32 bit architectures

- src/build-scripts/gh-win-installdeps.bash
Windows CI was failing because it couldn't get a proper libtiff from VcPkg, which in turn is because lzma is a dependency of the libtiff build in VcPkg, and for the time being, it looks like VcPgk is failing to get lzma which is part of the big xz debacle of 2024.
So work around for now by just building our own libtiff rather than relying on VcPkg. Seems to work fine.
> ci: Fix broken Windows CI by building our own libtiff

- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/exif.cpp
- src/libOpenImageIO/xmp.cpp
- src/libtexture/imagecache_pvt.h
- src/libutil/CMakeLists.txt
- src/libutil/thread.cpp
- src/oiiotool/CMakeLists.txt
- src/oiiotool/oiiotool.h
A tiny bit more progress towards #4158.
None of the code was actually dependent on the fact that these containers are sorted by key. Switching to the robin containers instead removes one less use of boost in the project.
It passes the tests that I can run locally -- will be looking at the actual CI results to confirm everything passes, since I can't get all tests to pass locally (even without this change).
nonconforming.
> Replace uses of boost flat_map and flat_set with robin_map and robin_set

- src/build-scripts/gh-win-installdeps.bash
- src/cmake/externalpackages.cmake
- src/include/OpenImageIO/sysutil.h
- src/libutil/CMakeLists.txt
- src/libutil/sysutil.cpp
To shed the boost dependency, we are disabling stacktrace for now. It's not vital and probably not worth keeping boost just for that.
C++23 has std::stacktrace, so as compilers add support for this, we will phase it back in.
We can also add it back if somebody has an alternate suggestion for a 3rd party solution that is a simply drop-in replacement, portable, lightweight dependency, with compatible license. A good compromise might be this one: https://github.com/jeremy-rifkin/cpptrace But I think what I'm proposing is that we accept this PR first, get rid of boost, then we can come back to looking at cpptrace as potentially a way to restore the functionality prior to C++23.
> build: Remove boost::stacktrace

- src/libOpenImageIO/CMakeLists.txt
- src/libutil/CMakeLists.txt
The Analysis workflow seems to be failing since this [run](https://github.com/AcademySoftwareFoundation/OpenImageIO/actions/runs/8448478726)
It seems that two targets `libOpenImageIO`, `libutil` were left out during the [switch to target-based definitions] (https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4193) refactor  and have no `-ftest-coverage -fprofile-arcs` options added in the CODECOV=1 mode.
The issue (on master) can be reproduced locally by running:
`CMAKE_GENERATOR=Ninja CMAKE_BUILD_TYPE=Debug CODECOV=1 ./src/build-scripts/ci-build.bash`
Generated build error:
```
FAILED: bin/optparser_test
: && ccache /usr/bin/c++ -g -ftest-coverage -fprofile-arcs src/libutil/CMakeFiles/optparser_test.dir/optparser_test.cpp.o -o bin/optparser_test …
```
> Fix Analysis workflow build - add missing gcov build options

- src/cmake/testing.cmake
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/openexr.imageio/exroutput.cpp
- testsuite/openexr-decreasingy/ref/out.txt
- testsuite/openexr-decreasingy/run.py
This change fixes out-of-bounds reads and incorrect scanline ordering when OpenEXR's decreasingY lineOrder mode is used.
OpenEXR expects to process scanlines in decreasing order when the decreasingY lineOrder option is enabled. This change fixes the code that provides the chunks of scanlines to OpenEXR so that the proper scanlines are available when it accesses the FrameBuffer OIIO created. The old code was providing incorrect scanlines AND setting up the FrameBuffer with incorrect pointers so out-of-bounds reads were occurring.
The key things to keep in mind are:
- Chunks of scanlines need to be sent to OpenEXROutput::write_scanlines() from the bottom of the image to the top when decreasingY is enabled. If the chunk's scanline range does not contain the scanlines OpenEXR is expecting to …
> Fix out-of-bounds reads when using OpenEXR decreasingY lineOrder.

- src/include/OpenImageIO/texture.h
The doc comment said it should initialize, and the analogous structure for scalar texturing, TextureOpt, initialized. Missed this one.
Fixes #4219
> fix(TS): fix missing initialization in TextureOptBatch

- src/include/OpenImageIO/detail/fmt.h
We disable fmt execptions and force it to do one of our ASSERT's instead.  But fmt in their main branch recently added `[[noreturn]]` annotations in a way that cause this to be compiler errors for our overrides.  Needed an extra std::terminate() call to guarantee the noreturn promise.
> fix(fmt.h): fix build break from recent fmt change

- src/libtexture/texturesys.cpp
> style: Fix clang-format problem caused by 4221

- .github/workflows/analysis.yml
- .github/workflows/ci.yml
- CONTRIBUTING.md
- INSTALL.md
- Makefile
- conanfile.txt
- docs/ROADMAP.md
- src/build-scripts/gh-installdeps.bash
- src/build-scripts/gh-win-installdeps.bash
- src/build-scripts/install_homebrew_deps.bash
- src/cmake/externalpackages.cmake
- src/doc/oiiointro.rst
- src/libutil/CMakeLists.txt
- src/libutil/thread.cpp
- src/python/py_imagebufalgo.cpp
- src/python/py_oiio.h
As Marie Kondo would say, Boost no longer sparks joy for us, so we take one last look, thank it for its many years of service to our project, and then send it on its way.
Fixes #4158
> build(deps): Remove the very last references to boost

- src/include/OpenImageIO/color.h
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/refcnt.h
- src/include/OpenImageIO/texture.h
- src/include/OpenImageIO/timer.h
This is just the first step in many for removing deprecated things along the way to a 3.0 release. I'm doing a little at a time.
I believe that here I'm only removing things that (a) have been deprecated since 2.0 or earlier, (b) most or maybe all were marked with OIIO_DEPRECATED and so should have been triggering warnings for a long time if used downstream (thus, almost certainly nobody is using it), and (c) are inline definitions, so this change should not appear to break link ABIs.
> cleanup: Remove some long-deprecated things

- INSTALL.md
The instruction for building from source on Windows is incorrect and causes building to fail. I fixed it.
> Fix building failed from source on Windows

- src/libutil/CMakeLists.txt
> fix(build): libOpenImageIO_Util does need DL libs, we removed it incorrectly

- src/doc/imageioapi.rst
- src/doc/oiiotool.rst
- src/include/OpenImageIO/hash.h
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool-attribs/ref/out-jpeg9d.txt
- testsuite/oiiotool-attribs/ref/out.txt
It was pointed out that oiiotool and maketx's habit of embedding their exact command line arguments in the Software and ImageHistory metadata of output images was potentially problematic in that it might inadvertently leak important internal data (for example, file paths may reveal secret projects, etc.).
This patch changes the behavior of oiiotool and maketx as follows:
* The default behavior is now to use `"OpenImageIO <version> <hash>"` where `<hash>` is the SHA-1 hash of the command line arguments (which allows you to tell if two files use the same command line args, but doesn't let you know what they were).
* A new `--history` argument (or setting OIIOTOOL_METADATA_HISTORY env variable to a nonzero integer) instead uses the full command line arguments with no obfuscation. (This used …
> security: change command line embedding for oiiotool & maketx output

- .github/workflows/ci.yml
- INSTALL.md
- Makefile
- src/build-scripts/build_openexr.bash
- src/build-scripts/gh-win-installdeps.bash
- src/cmake/externalpackages.cmake
- src/cmake/modules/FindOpenEXR.cmake
- src/include/OpenImageIO/Imath.h.in
- src/include/OpenImageIO/half.h.in
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libutil/typedesc_test.cpp
- src/oiiotool/CMakeLists.txt
- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exroutput.cpp
These are build-breaking changes that impose a new minimum OpenEXR/Imath version supported of 3.1 or higher.
Needless to say, this will not be backported to any release branches, which guarantee that they will never raise the minimum supported versions of any dependencies. This is just for future OIIO. There is already a "developer preview" branch dev-2.6.1 marking the last spot in master in which the old dependencies are supported.
Fixes #4156
> build!: Move OpenEXR/Imath minimum to 3.1

- src/jpegxl.imageio/jxloutput.cpp
This is a trivial fix for build with warnings treated as errors.
> Fixed the sign compare causing build failure

- src/libOpenImageIO/imageioplugin.cpp
Only use the OIIO_LIBRARY_PATH environment variable by default.
Searching through such system paths has some risk loading plugins installed for another purpose or that may be incompatible.
If the previous behavior is desired, applications can add these environment variables to the plugin search path manually.
N/A
nonconforming.
> Don't use (DY)LD_LIBRARY_PATH as plugin search paths

- INSTALL.md
- src/include/OpenImageIO/detail/fmt.h
- src/libutil/strutil.cpp
clang/llvm 18 (and probably other compilers soon) has made noisy warnings about the C++17-deprecated unicode conversions. Actually replacing them enirely with something else is rather hairy, we will tackle that later.
In the mean time, this patch seems to be the minimal change to disable the warnings that should be totally easy to backport.
These seem to be the only changes necessary to make a clean build with clang 18.
> build: Disable clang18 warnings about deprecated unicode conversion

- src/libOpenImageIO/imagebufalgo_draw.cpp
The nullptr at the end of default_font_name was left over from a time that we iterated by going through array elements until we hit the nullptr that signalled we had passed the last valid element. At some point we switched to a range-for, which iterates over every element of the array without needing an "end sentinel", and we should have eliminated the nullptr but failed to do so.
Fixes #4248
> fix: fix crash when no default fonts are found

- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebuf_test.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
Remove some long-ago deprecated printf-like error functions. Mark as deprecated some other ones that we will remove when it gets closer to 3.0 release. I think these are the very last uses internally of the old style that we want to remove.
> cleanup: more old style format deprecation

- src/doc/builtinplugins.rst
- src/pnm.imageio/pnminput.cpp
- src/pnm.imageio/pnmoutput.cpp
- testsuite/pnm/ref/out.txt
Fixes added:
- import/export support for 8/16 uint 32-float
- pnm:bigendian
- pnm:pfmflip for float pfm files (GIMP flip float PFM files by default, Photoshop do not)
- update in documentation
nonconforming.
> pnm-plugin

- .github/workflows/ci.yml
- src/build-scripts/install_homebrew_deps.bash
- src/libutil/plugin.cpp
This is a continuation of PR 4246, had one more spot where we needed to disable warnings for unity builds involving clang18 and deprecated unicode conversion functions.
There's some changes included to ci.yml and install_homebrew_deps.bash that are part of work I did to make it easier for me to force it to use clang-18 for certain tests while working on this.
> build: More warning elimination for clang18

- src/doc/builtinplugins.rst
- src/dpx.imageio/dpxinput.cpp
- src/ffmpeg.imageio/ffmpeginput.cpp
- src/fits.imageio/fits_pvt.h
- src/fits.imageio/fitsinput.cpp
- src/gif.imageio/gifinput.cpp
- src/ico.imageio/icoinput.cpp
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebuf.cpp
- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exrinput_c.cpp
- src/openvdb.imageio/openvdbinput.cpp
- src/tiff.imageio/tiffinput.cpp
- testsuite/dpx/ref/out.txt
- testsuite/fits/ref/out.txt
Background: Some formats that support multi-image files know as soon as they are opened and read the header what the total subimage count is.  Others (I'm looking at you, TIFF) can't know without reading each subimage in succession until you hit the end of the file. Format readers who can easily figure it out open first opening are supposed to set attribute "oiio:subimages" to the number of subimages, or 0 / unset if it can't be cheaply or immediately determined.
ImageBuf has a `nsubimages()` method that you'd think would give you the right count, and it did when all IBs were read through the ImageCache (which fully inventories the subimages of any file it reads). But when OIIO 2.5 changed IB behavior to only be backed by IC when explicitly requested, we effectively lost this …
> fix: Improve IB::nsubimages and other related fixes

- testsuite/heif/ref/out-libheif1.12-orient.txt
Some weird combination of old libheif library gives a different oiio:OriginalOrientation result. Need this ref because that's how it behaves in that version (which I have to build against at work), but it's not worth tracking down a "fix" because it's so old and works fine on newer versions.
> testing: Add new heif test output

- src/cmake/externalpackages.cmake
Recent libtiff versions export cmake configs that, if you built libtiff as a static library, will reference targets it set up when it built, but which are nonstandard names and won't exist when you build and consume their config exports. Ugh!
Some can be swept under the rug by turning off some libtiff optional dependencies, but I can't seem to get rid of a target CMath::CMath that static libtiff target wants. It just points to the math library. So I'm just setting that up so it will be found when we do the find_package(tiff). Oh, the hoops we jump through for badly constructed packges.
> build: Add CMath target for the sake of static libtiff

- src/openexr.imageio/exroutput.cpp
Add proxy support for EXR multipart output by taking the setup code from the other open() overload and calling the constructor accepting a stream instead of a filename.
I did not add any new tests. Is proxy support tested by the testsuite?
nonconforming.
> Add proxy support for EXR multipart output (#4263)

- src/libOpenImageIO/color_ocio.cpp
- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
A small piece of the ongoing switch to std::format/print style text output. This part is for error and debugging output when reading/writing exr images.
I also switched conditional compilation to the DBG macro idiom that I've used elsewhere, where it takes a combination of DEBUG compile and setting of environment variable OIIO_DEBUG_OPENEXR to trigger the printf style debugging (the first use case of this was in our color management code, which I also modify slightly here to conform).
Also opportunistically simplify gcd declaration now that we're C++17 minimum.
> cleanup: change raw cerr stream output to print

- testsuite/oiiotool-color/run.py
We didn't notice before because our CI didn't test with OCIO on Windows.
> test: Fix windows quoting for test

- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/simd.h
We've been plagued on and off for a long time with spurious wrong results in our SIMD versions of exp and log. It was really squirrelly, came and went with changes to seemingly unrelated code, and had long periods of time with no symptoms or ability to reproduce it. It just started popping up again in CI in the dev-2.5 branch, consistently.
Today I think I finally tracked it down for real. I believe the problem was actually in the SIMD bitcast_to_int and bitcast_to_float functions, for the variety that was 8-wide when running on 4-wide hardware, and the 16-wide one when running on 8-wide (or less) hardware.
Background: When real 16-wide HW is not available, we define the 16-wide vectors as an array of two 8-wide vectors. (Same for 8 vs 4, I'll spare you explaining it all twice.) So most …
> fix(simd.h): fix longstanding probem with 16-wide bitcast for 8-wide HW

- .github/workflows/ci.yml
- INSTALL.md
- src/build-scripts/gh-installdeps.bash
- src/libtexture/imagecache_pvt.h
- src/python/py_imagecache.cpp
* Switch runner type for bleeding edge, use gcc14 and python 3.12
* Various minor gcc-14 + C++20 + Python 3.12 fixes
Notable: gcc14 warns about std::atomic_load for share_ptr as deprecated, since C++20 provides a true atomic shared pointer.
> build: gcc-14 support, testing, CI

- src/include/OpenImageIO/fmath.h
In PR #4268, I accidentally changed the clause addressing what is seemingly a bug with older MSVS. I'm just putting things back the way they were. It's not a new change, just restoring this line closer to the way it was about 3 commits back.
> fix(fmath.h): One more fast_exp fix

- src/include/imageio_pvt.h
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/buildopts.h.in
- src/libOpenImageIO/imageio.cpp
This file imageio_pvt.h.in was used as the input template for CMake to create imageio_pvt.h, doing a couple build variable substitutions along the way. But this was inconvenient (because it doesn't look like a real .h file to editors or clang-format) and it turns out that there were only 2 lines that needed the substitution.
So in this patch, we split the file, making 99% of it just plain old imageio_pvt.h that needs no rewriting, and the couple lines that need variable substitions becomes buildopts.h.in and is included only from the one source file that actually cares, imageio.cpp.
Other than cleaving those two definitions off to another header and some file renaming, I haven't changed any of the other content of the headers, so there should be no change in code the compiler sees or …
> refactor: move most of imageio_pvt.h.in to just a regular .h

- INSTALL.md
While making a CI to build python wheels for OIIO on windows I spotted a few issues in the instructions, these edits made it work for me.
Small adjustment to expected paths for the manual instructions.
- [-] I have ensured that the change is tested somewhere in the testsuite
- [-] If I added or modified a C++ API call, I have also amended the
- [-] My code follows the prevailing code style of this project. If I haven't
nonconforming.
> fix: Update INSTALL.md for windows

- src/cmake/set_utils.cmake
A few minor fixes for things I noticed as I started to actually use these new utilities in other branches I'm working on.
> build: Some minor corrections to the new set utils

- src/build-scripts/gh-win-installdeps.bash
This cuts down CI time, as before we were building both release and debug versions of the packages.
The dependency building step of our CI typically took around 6.5-7 minutes previously, and with this patch, now typically is about 5 minutes and sometimes slightly less.
Thanks so much to @cedrik-fuoco who pointed me at this feature of vcpkg which had eluded me for a long time!
> ci: For Windows CI, build only release of vcpkg packages

- CMakeLists.txt
- src/cmake/pythonutils.cmake
- src/cmake/testing.cmake
- src/doc/CMakeLists.txt
- src/libOpenImageIO/CMakeLists.txt
Latest versions of cmake are warning about FindPython being a deprecated module, they recommend FindPython2 or FindPython3 instead. In master, we're already python3 minimum, so go ahead and switch this to the modern method.
> build: Upgrade to more modern python3 finding

- src/include/OpenImageIO/typedesc.h
- src/include/OpenImageIO/ustring.h
We're seeing nvcc compilation warnings like the following:
```
ustring.h(869): warning #20012-D: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
__attribute__((host)) __attribute__((device)) 
```
According to nvidia's documentation (https://docs.nvidia.com/cuda/archive/10.1/cuda-c-programming-guide/index.html#compiler-generated-functions), functions that are explicitly-defaulted should not have execution space specifiers like \_\_device\_\_ or \_\_host\_\_. Instead the compiler will determine the annotations from the functions that invoke it.
This patch goes through the ustring and typedesc headers and removes OIIO_HOSTDEVICE from all defaulted functions.
corresponding Python bindings …
> fix: Address ignored annotation nvcc warnings on explicitly-defaulted functions

- .github/workflows/ci.yml
Split the CI "oldest/hobbled" test into two different tests:
* oldest -- test against the oldest supported versions of all dependencies.
* hobbled -- test against most optional dependencies missing and optional feature disabled (including no SSE, no OCIO, etc.).
And add an additional test:
* local-builds -- a test that builds and uses every dependency that we know how to build locally/automatically.
> ci: new tets: oldest, hobbled, localbuilds

- src/doc/Doxyfile
- src/doc/builtinplugins.rst
- src/doc/maketx.rst
- src/doc/oiiointro.rst
Also, tell doxygen to use multiple threads.
> docs: Fixes to formatting and sphinx warnings

- src/include/OpenImageIO/unordered_map_concurrent.h
- src/libtexture/imagecache.cpp
Simplifies the clearing of the tile cache so it no longer allocates a vector of tile IDs prior to erasing them all.
nonconforming.
> Simplify tile cache clearing.

- CMakeLists.txt
- src/build-scripts/ci-startup.bash
- src/cmake/compiler.cmake
- src/cmake/cuda_macros.cmake
- src/doc/oiiotool.rst
- src/include/imageio_pvt.h
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/oiio_gpu.cpp
- src/oiiotool/oiiotool.cpp
Build-time check for Cuda toolkit as optional dependency.  This can be explicitly disabled with OIIO_USE_CUDA=OFF (though currently, it defaults to off, you have to turn it on at build time because this is all still experimental).  When this is enabled at build time, C++ preprocessor symbol OIIO_USE_CUDA will be defined within the OIIO codebase.
OIIO global `attribute("gpu:device", "CUDA")` can be used to enable CUDA functionality, which at this point doesn't do anything other than initialize the CUDA device and find out information about it.  Several global `getattribute("cuda:*")` queries let you find out some information about any device found.
I'm trying to keep a lot of the approaches fairly generic, so that the interface won't need to change much to allow OpenCL or Metal or whatever …
> Rudimentary CUDA support infrastructure

- src/libutil/CMakeLists.txt
This is the continuation of [4305 ](https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4305)(Add extra step to Makefile config target to force CMake to rescan). 
The error occurs when configuring with `make OpenImageIO_BUILD_MISSING_DEPS=all` option which fails the build as `libuitil` does not have `./dep/dist/include` on the path.
The original solution was to rerun cmake and let it rescan paths. This step was only required to run once - after the initial CMake configuration step. This kind off worked but I'm still unsure why. So instead of that we can just add the missing location to CMakeLists.
> Add missing includes to libutil CMake target.

- src/include/OpenImageIO/simd.h
Fully remove some things that have had deprecation warnings for a long, long time (mostly since 1.x), so we think it can't possibly break anyone.
Add deprecation warnings to some things that have been nominally deprecated for some time. The build warnings will serve as final notice that they will fully disappear by OIIO 3.0 release.
This is part of a series of small steps to fully deprecate a whole lot of cruft between now and the 3.0 release.
> cleanup: simd.h deprecations

- src/idiff/idiff.cpp
- src/iff.imageio/iffinput.cpp
- src/iff.imageio/iffoutput.cpp
- src/include/OpenImageIO/fmath.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo_mad.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libutil/simd_test.cpp
- src/rla.imageio/rlainput.cpp
- src/rla.imageio/rlaoutput.cpp
In several places, we still used OIIO versions of isnan/isinf/isfinite and is_same.  All of there for some time have been aliased to the std versions (having our own was mostly a pre-C++11 artifact). Change those OIIO::foo to std::foo throughout the codebase, and hide the old declarations themselves behind some guards that:
1. Will eliminate them completely as soon as the version is higher than 2.6.x.
2. Makes them invisible now internally to OIIO (so we aren't accidentally using them ourselves), and to external projects (like OSL) that define OIIO_DISABLE_DEPRECATED to hide deprecated things.
3. Add deprecation warnings if they are not hidden by the logic of (2) above.
Before 3.0 release is final, we will truly remove them entirely, but these staged warnings will help people with the …
> cleanup: deprecations in fmath.h

- src/include/CMakeLists.txt
This continues the adventure from #4082 where the processing of fmt headers, both locally built and externally referenced, causes large rebuilds to occur when making small or even zero changes between builds.
Since that previous PR is stuck I'll try again here.
This makes two sets of changes:
- Check if our generated files exist before writing to them (in the externally referenced case)
- Use `copy_if_different` to prevent redundant copies from occuring, and triggering timestamp updates (in the local build case)
Note that while this seems to fix the problem, the build is still not "clean" wrt fmt processing. The following will be be seen when triggering a build, with zero changes since the last build, within VS:
```
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 …
```
> build: Avoid rebuilds due to processing of fmt headers

- src/include/OpenImageIO/typedesc.h
- src/libutil/typedesc.cpp
- src/null.imageio/nullimageio.cpp
Fully remove some things that have had deprecation warnings for a long, long time (mostly since 1.x), so we think it can't possibly break anyone.
Add deprecation warnings to some things that have been nominally deprecated for some time. The build warnings will serve as final notice that they will fully disappear by OIIO 3.0 release.
> api: deprecate things in typedesc.h

- src/doc/imageioapi.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/typedesc.h
- src/libutil/typedesc.cpp
- src/python/py_typedesc.cpp
- testsuite/python-typedesc/ref/out-python2.txt
- testsuite/python-typedesc/ref/out.txt
- testsuite/python-typedesc/src/test_typedesc.py
Like the existing Vector2i, but, you know, 3.
Along the way, fixed a bug in the way the Vector2i type is represented as a string.
> api: Add TypeDesc::Vector3i

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/tiff.imageio/tiffoutput.cpp
TIFF export with EXIF metadata (e.g. oiio::ColorSpace) creates invalid TIFF files in the presence of an I/O proxy ("TIFF directory is missing required "ImageLength" field"). The reasons is that TIFFSetDirectory() requires to read some of the previously written data, but neither writer_readproc() nor the available proxy implementations support that. Note that TIFF output does not yet use this new scheme for I/O proxy that was used for many other plugins.
I think writer_readproc() should not take any shortcuts and just forward the call to the I/O proxy.
Is there a reason why IOFile (in write mode) and IOVecOutput do not allow to re-read written data? This looks like an artificial restriction of the underlying resources. An alternative not modifiying these two implementations would be to let …
> Fix TIFF export with EXIF data and I/O proxy

- CMakeLists.txt
- src/iconvert/iconvert.cpp
- src/igrep/igrep.cpp
- src/iinfo/iinfo.cpp
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/oiioversion.h.in
- src/libOpenImageIO/imagebufalgo_opencv.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageioplugin.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/texturesys.cpp
- src/null.imageio/nullimageio.cpp
- src/oiiotool/printinfo.cpp
- src/python/py_imageinput.cpp
- src/python/py_imageoutput.cpp
- testsuite/iinfo/ref/out-fmt6.txt
- testsuite/iinfo/ref/out.txt
- testsuite/python-imagespec/ref/out-python3.txt
- testsuite/python-imagespec/ref/out.txt
Track down and fix many places internal to OIIO where we were still using deprecated API calls.
Add deprecation warnings to some things that have been nominally deprecated, but weren't already tagged as such.
Guard deprecated things behind OIIO_DISABLE_DEPRECATED so that downstream projects can hide them to help them find and change any use of the deprecated calls, and behind !defined(OIIO_INTERNAL) so they are hidden from the rest of the internals of our code base.
Make some of the deprecated things inline, so that their final removal later doesn't constitute a link ABI compatibility change. (We do absorb an ABI compatibility boundary with this PR, so I've bumped the version number appropriately.) Move all the OIIO-namespace level deprecated items to the end of imageio.h so they're as …
> api: deprecation cleanup in imageio.h

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/include/CMakeLists.txt
- src/include/OpenImageIO/Imath.h
- src/include/OpenImageIO/half.h
In master, since we have raised the minimum Imath/OpenEXR to 3.x, no more 2.x, we no longer need generate our Imath.h and half.h from templates, they can be turned into regular header files.
Additionally, define IMATH_HALF_NO_LOOKUP_TABLE in half.h before including Imath/half.h, which ensures that the Imath code we include converts float <-> half using actual inline code and not the lookup table. This can reduce or sometimes eliminate the need to link agains Imath only for the sake of accessing that lookup table.
> int: Simplify openexr includes

- src/doc/imagebuf.rst
- src/doc/imageioapi.rst
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/paramlist.h
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libutil/benchmark.cpp
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
Inspired by a question by Vlad Erium, I have added a simpler way for C++ users of OIIO to construct IBA-like functions for simple unary and binary operations on ImageBufs where each pixel is independent and based only on the corresponding pixel of the input(s).
The user only needs to supply the contents of the inner loop, i.e. just doing one pixel's work, and only needs to work for float values. All format conversion, sizing and allocation of the destination buffer, looping over pixels, and multithreading is automatic.
If the actual buffers in question are not float-based, conversions will happen automatically, at about a 2x slowdown compared to everything being in float all along, which seems reasonable for the extreme simplicity, especially for use cases where the buffers are fairly …
> feat(iba): IBA::perpixel_op

- .github/workflows/ci.yml
They upgraded to a version that requires a glibc newer than is in the pre-2023 ASWF containers.
> Fix GHA CI after they upgraded nodejs

- src/build-scripts/gh-installdeps.bash
This was breaking CI for us. Hard break for icc/icx tests, since those REQUIRED a yum install of the intel compilers. Softer undetected break for all the ASWF <= 2022 containers based on CentOS 7, which were not failing outright but were failing to install certain optional packages.
The solution (for now) is to configure yum to exclude the missing repo.
> ci: deal with CentOS 7 EOL and disappearance of yum mirrors

- src/iv/imageviewer.cpp
Enable the ImageCache for the `iv` tool. It more or less expects it to be present and certain features, like loading the Image's mip-levels, requires the ImageCache to be used.
nonconforming.
> fix: iv should enable the ImageCache

- src/include/OpenImageIO/imageio.h
I should not have hidden virtual functions behind OIIO_DISABLE_DEPRECATED checks. Never make the vtbl possibly vary for clients of the library from the way we built it!
> fix: Fix deprecation masking of virtual functions

- src/doc/imageioapi.rst
- src/doc/imageoutput.rst
- src/libOpenImageIO/imageioplugin.cpp
The old name, OIIO_LIBRARY_PATH, was inconsistently named in two ways:
First, it was not clear that it was specific to searching for plugins, and since it is related to the to the global attribute "plugin_searchpath", I thought making it mention plugins specifically would be more clear.
Second, I noticed that all of the publicly documented environment variables that are "for users" started with OPENIMAGEIO_, except for this one. There are a bunch of environment variables we check that begin with OIIO_, but all but this one are intended for developers when testing or debugging.
So I'm using a new name that is consistent with both principles.
Henceforth, the naming rule about environment variables is:
* `OPENIMAGEIO_FOO` for public interfaces, are fully documented and intended for …
> api: consistent naming of OPENIMAGEIO_PLUGIN_PATH env variable

- src/dpx.imageio/libdpx/EndianSwap.h
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imagebufalgo_util.h
- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/span_util.h
- src/libOpenImageIO/color_ocio.cpp
- src/libOpenImageIO/deepdata.cpp
- src/libOpenImageIO/exif.h
- src/libOpenImageIO/imagebufalgo_channels.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
- src/libOpenImageIO/imageinout_test.cpp
- src/libutil/argparse.cpp
- src/libutil/filesystem.cpp
- src/oiiotool/oiiotool.cpp
- src/png.imageio/png_pvt.h
- src/psd.imageio/psdinput.cpp
- src/raw.imageio/rawinput.cpp
With 3.0 coming soon, it's time to break compatibility by switching OIIO::span::size() to return an unsigned value, matching C++20 std::span.
The history is that when we first added OIIO::span, at that time, the C++ draft proposal for std::span included a signed size() result, but by the time it got finalized into C++20, it was changed to unsigned to match all the other std containers, but it was too late for us to switch without breaking API compatibility rather seriously.
> api: Make span::size() return size_t

- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/maketexture.cpp
It's silly to copy the full metadata from the source (which could include big things like ICC profiles) to EVERY level of a MIPmap.
This mostly applies to TIFF textures, since OpenEXR MIPmaps don't store attributes separately for each MIP level anyway.
This can be disabled (that is, make it copy full metadata to all levels of the MIPmap) by setting a new make_texture configuration hint, "maketx:mipmap_metadata" to nonzero.
> make_texture: only write full metadata to the first mip level

- docs/Deprecations-3.0.md
- src/idiff/idiff.cpp
- src/include/OpenImageIO/imagebuf.h
- src/iv/ivimage.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libOpenImageIO/maketexture.cpp
- src/oiiotool/imagerec.cpp
- src/python/py_imagebuf.cpp
* Add deprecation warnings to the varieties of ImageBuf constructor and `reset()` that don't take subimage and miplevel parameters. The equivalent is to just pass `0` for both of those parameters. The warned constructors have been marked as deprecated since OIIO 2.2.
* The misspelled `ImageBuf::make_writeable()` has been given deprecation warnings. Since OIIO 2.2, the correct spelling is `make_writable`.
* The `ImageBuf::error()` method that uses printf-style formatting now has deprecation warnings. Use `ImageBuf::errorfmt()` instead.
* The `ImageBuf::interppixel_NDC_full()` method, which has been marked as deprecated since OIIO 1.5, now has deprecation warnings. Use `interppixel_NDC()` instead.
Undeprecate the name+spec varieties of constructors. They were documented as deprecated but …
> api: imagebuf.h add deprecation warnings to deprecated things

- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texturesys.cpp
Reduces the memory footprint of the `LevelInfo` struct. Three changes are here, in order of most to least impactful:
- Makes one `ImageSpec` optional, most of the time `spec` and `nativespec` are the same, it appears they are only different when autotile is enabled, this saves about 160 bytes.
- Uses `std::unique_ptr<float[]>` (8 bytes) instead of `std::vector<float>` (24 bytes).
- Reorders members to remove excess padding.
We noticed this memory usage on scenes with per-face textures with multiple mips per face. For a scene with 12.5 million mips, this saves about 2GB.
Note, it would probably also be possible to remove the `polecolorcomputed` member, instead relying on the `polecolor` pointer. But since this bool occupies existing padding in the struct it wouldn't save any memory …
> Reduce LevelInfo memory usage.

- src/doc/oiiotool.rst
- src/oiiotool/expressions.cpp
- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
- testsuite/oiiotool/ref/out.txt
- testsuite/oiiotool/run.py
Improvements to expression evaluation of oiiotool command line arguments surrounded by `{braces}`.
* Just like `TOP` refers to the top image on the stack, now `BOTTOM` refers to the bottom image.
* Referring to images with `IMG[id]` previously worked if `id` was a literal integer or an image label or an image filepath. But now it can be any expression that evaluates to any of those things. So, for example, you could say `{IMG[i].filename}` to get the filename of the i-th image down the stack (where `i` is a variable), or `{IMG[NIMAGES-2].width}` to get the x resolution of the 2nd-from-bottom image on the stack.
* The `--label` and `--set` commands check that the name you use for an image label or user variable follow the "C identifier" lexical rules: must be alphanumeric + underscore, but …
> feat(oiiotool): Expression eval improvements: BOTTOM, IMG[expression], check label/var names

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/png.imageio/png_pvt.h
Raised from 1.5.13 (maybe? we never carefully checked) to 1.6.0 minimum, which was released in 2013 (so absolutely nobody should be bothered by this).
> deps: Raise libPNG minimum to 1.6.0

- src/include/OpenImageIO/imagebufalgo.h
As suggested by Moritz Moeller
> docs: clarify that IBA::rotate  params are pixel coordinates

- src/libOpenImageIO/imagebuf.cpp
Fixes a simple copy/paste error in a copy constructor where the y coordinate gets initialised twice instead of y and z.
This is a trivial change, I don't think it needs any additional testing.
nonconforming.
> fix: copy/paste error in the ImageBuf iterator copy constructor

- src/doc/imageioapi.rst
- src/doc/oiiotool.rst
- src/maketx/maketx.cpp
- src/oiiotool/oiiotool.cpp
It's not just in oiiotool. This seems clearer and adheres to the env variable naming convention we chose.
Reminder: This controls whether command line history gets written to output image metadata by default by oiiotool and maketx. We historically did it, but recently stopped because of security concerns.
> int: Rename env OIIOTOOL_METADATA_HISTORY -> OPENIMAGEIO_METADATA_HISTORY

- src/doc/builtinplugins.rst
- src/include/OpenImageIO/tiffutils.h
- src/jpeg.imageio/jpegoutput.cpp
- src/libOpenImageIO/iptc.cpp
JPEG output configuration hint "jpeg:iptc" (default: 1), if set to 0, will suppress IPTC block output to the file.
In the process, we changed the return type of utility function encode_iptc_iim() to return true if anything was successfully encoded, false otherwise.
> feat(jpeg): output hint "jpeg:iptc"

- src/doc/builtinplugins.rst
- src/raw.imageio/rawinput.cpp
The main purpose of this change is to make it possible to use OIIO for reading raw files in rawtoaces instead of calling LibRaw directly. There are the changes:
- add the missing hints needed to implement all combinations of white-balancing methods and matrix methods provided by rawtoaces.
- add the DNG-specific attributes
The change adds this functionality:
- new "raw:user_black" hint to override the default black point
- new "raw:use_auto_wb" hint to force LibRaw to white balance by averaging over the whole image.
- new "raw:grey_box" hint to make LibRaw to white balance by averaging over the given rectange.
- new "raw:dng:XXX" attributes added to the output ImageBuf if the input image is a DNG file. The attributes consist of 2 sets of [calibration illuminant; calibration matrix, XYZ to …
> raw: improvements to raw plugin

- src/iff.imageio/noproxy-iff_pvt.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/strutil.h
- src/include/imageio_pvt.h
- src/libOpenImageIO/imagebufalgo_opencv.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageioplugin.cpp
- src/libOpenImageIO/maketexture.cpp
This is needed for the related OpenCV-related PR
> api: move OIIO::pvt::error and log_time into the exposed OIIO namespace

- src/include/OpenImageIO/simd.h
https://github.com/lgritz/OpenImageIO/commit/4cb956b0a0a123376e468a5b5e6e188178ec077e lost this removal when resolving a merge conflict. This properly removes it.
Signed-off-by: Thiago Ize
https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4076 implemented matrix44::inverse() so that we could stop including Imath.h. It removed the Imath.h include in the master/dev-2.6 branch but the dev-2.5 branch kept the include, likely because of an improperly resolved merge conflict. This PR removes the include like in master.
No tests are needed. As long as it compiles, this should be good. I verified this builds on arm64. …
> Finish removing Imath include

- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/memory.h
- src/include/OpenImageIO/paramlist.h
- src/include/OpenImageIO/refcnt.h
- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/libOpenImageIO/imagespec_test.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_memory_print.h
- src/libtexture/imagecache_memory_pvt.h
- src/libtexture/imagecache_pvt.h
- src/libutil/paramlist.cpp
- src/libutil/paramlist_test.cpp
First PR of two, following @lgritz and I discussions on memory tracking in the OIIO::ImageCache.
- Add two template methods and their specializations for types various to help memory tracking:
```c++
// return the total heap allocated memory held by the object and its members
template<typename T> inline size_t heapsize(const T& t);
// return the total memory footprint including the size of the structure itself
template<typename T> inline size_t footprint(const T& t);
```
- Specialized for: ParamValue, ParamValueList, ImageSpec, ImageInput, ImageOutput, std::vector, std::shared_ptr, std::unique_ptr, oiio::intrusive_ptr, ImageCacheImpl related objects.
- New files: 
- `include/memory.h` : adds base and few types specialization of heapsize and footprint.
- …
> api: add pvt::heapsize() and pvt::footprint() methods and image cache memory tracking

- src/libOpenImageIO/imagebufalgo_channels.cpp
- src/oiiotool/imagerec.cpp
- src/tiff.imageio/tiffoutput.cpp
Fix a bug in oiiotool wherein `-i:ch=...` (input only a subset of channels when reading from a file) was not adjusting the spec's alpha_channel and z_channel -- that is, they still contained the OLD channel numbers of those things, which not only could be wrong due to the reordering, but they might be out of range of the new number of channels.
Also a related fix in the TIFF reader, to fix a possible dereference of an empty vector. This was being triggered by that out-of-range alpha_channel. Maybe that can't happen anymore with the above bug fix, but it still feels like the safer way to proceed.
This was all found by the sanitizers in CI -- and only recently, despite this code having this bug for a long time. So yay for sanitizer CI!
> fix(oiiotool): `-i:ch=...` didn't fix up alpha and z channels

- .github/workflows/ci.yml
- Makefile
- src/build-scripts/ubsan-suppressions.txt
- src/cmake/compiler.cmake
CI sanitizers in master have been failing lately. A different PR addresses the root cause, but this patch contains some improvements I made along the way while investigating it:
* CMake: Change the SANIIZE build variables to use set_cache, thus allowing easier override by env variable.
* Bumped the CI sanitizer test to use the 2024 container and latest compilers.
* Suppress UB warnings in STL function.h, where it's claiming undefined behavior in the std::function guts called by ArgParse internals. Only seen failing on my Mac, wasn't actually failing in the GHA CI. I'm pretty sure it's a false positive.
* Also, only on my Mac building against OpenVDB 11, it found some UB in OpenVDB, which I'm suppressing (I think it's also false positive).
> build: CI sanitizer test improvements

- INSTALL.md
- src/cmake/externalpackages.cmake
- src/heif.imageio/heifinput.cpp
- src/heif.imageio/heifoutput.cpp
This version dates from early 2021 (so still supporting back 3.5 years).
The reason for the bump is to simplify a bit on our part and avoid older versions known to be broken or lacking certain features.
This is for master/2.6/3.0 only, will not be backported to 2.5, since we never raise minimum dependencies in already-released branches.
> build(deps): Raise libheif minimum to 1.11

- src/iv/ivmain.cpp
Microsoft's runtime library doesn't support the standard setenv() function. _putenv_s() should be used instead.
Without fix iv do not compiling:
`E:\GH\OpenImageIO\src\iv\ivmain.cpp(119,9): error C3861: 'setenv': identifier not found [E:\GH\OpenImageIO\build\src\iv\iv.vcxproj]`
nonconforming.
> fix for setenv() on Windows

- docs/Deprecations-3.0.md
- src/cmake/fancy_add_executable.cmake
- src/cmake/modules/FindOpenCV.cmake
- src/cmake/pythonutils.cmake
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imagebufalgo_opencv.h
- src/include/OpenImageIO/imageio.h
- src/include/imageio_pvt.h
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imageio.cpp
- src/oiiotool/CMakeLists.txt
- src/oiiotool/oiiotool.cpp
- src/python/CMakeLists.txt
- src/python/py_imagebufalgo.cpp
Fully linking OpenCV against libOpenImageIO is burdensome for people downstream, especially those who want a static version of libOpenImageIO.
There were only three IBA functions that use OpenCV: to_OpenCV(), from_OpenCV(), and capture_image(), and all three are fairly short. Move them to a separate header, imagebufalgo_opencv.h, make them fully INLINE (so they don't actually produce object code in libOpenImageIO, which therefore does not need to link against OpenCV).
Applications wanting these three functions should include this header and will be responsible themselves for ensuring that the include paths and linkage of their application makes provisions for finding and using OpenCV. All other applications don't need to deal with OpenCV dependency at all.
Our own oiiotool (for --capture) …
> build: Don't link libOpenImageIO against OpenCV

- src/iconvert/iconvert.cpp
- src/idiff/idiff.cpp
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/texture.h
- src/iv/imageviewer.cpp
- src/iv/ivmain.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
- src/libOpenImageIO/imagecache_test.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
- src/maketx/maketx.cpp
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.h
- src/python/py_imagecache.cpp
- src/python/py_texturesys.cpp
- src/testtex/testtex.cpp
Change IC::create() and TS::create() to return shared_ptr instead of a raw pointer. This cleans up a lot of lingering lifetime management issue of these classes. The switch to 3.0 is an opportunity to make breaking changes to these APIs.
For the sake of downstream users, we define preprocessor symbols
OIIO_IMAGECACHE_CREATE_SHARED and OIIO_TEXTURESYSTEM_CREATE_SHARED to signal that the new APIs are present. Some very minor changes may be needed at the call site.
> api: use shared_ptr for ImageCache and TextureSystem

- src/iff.imageio/iffinput.cpp
- src/iff.imageio/iffoutput.cpp
- src/iff.imageio/noproxy-iffinput.cpp
- src/iff.imageio/noproxy-iffoutput.cpp
Nominally, fix four places where "it's" was used when "its" was appropriate. Realistically, force the EasyCLA dialog so that I can get an individual CLA in place, my employment with ARRI having terminated on 15 July of this year.
Did not add a test; this was a removal of a typo in a comment, repeated across four files.
nonconforming.
> Fix typo where apostrophe was used for possessive of 'it'

- src/iv/ivmain.cpp
It was disabled to make prettier formatting for getargs, but neglected to turn it back on for the rest of the file.
I also changed a few old `<<` stream output to `print()`.
> style: Turn on clang-format for ivmain.cpp

- src/ptex.imageio/ptexinput.cpp
Don't read or store full metadata on every MIP level for every face. That can really add up! Ptex can only have one set of metadata, the format itself doesn't allow it to vary from face to face.
> ptex: Store full metadata only at subimage 0, miplevel 0 for ptex files.

- src/png.imageio/pnginput.cpp
- testsuite/png/ref/out-libpng15.txt
- testsuite/png/ref/out.txt
In trying to avoid doing the color conversion pointlessly for pixels with alpha=0, I accidentally also managed to skip the multiplication by alpha for those pixels. Oops.
> fix(png): bug in associateAlpha botched alpha=0 pixels

- src/libOpenImageIO/imagebufalgo_xform.cpp
It was documented and declared, but implementation was missing in action.
> fix(iba): Add missing version of warp

- src/include/OpenImageIO/imagebufalgo_util.h
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_orient.cpp
Because IBA::transpose changes resolution, it doesn't pass the input image to IBAPrep(), and there was a special case there that always set destination to float if there were no source images.
So change transpose to specifically request a format, to be the same as the input image.
And that required a tweak to IBAPrep allowing us to specify such a thing (there was already an option that meant "force it to float", but not the general case of an arbitrary type).
> fix(iba): IBA::transpose() didn't set output image's format to input

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageoutput.cpp
Second PR of two, following @lgritz and I discussions on memory tracking in the OIIO::ImageCache.
- the memory tracking system from https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4322 is not sufficient to track OIIO public objects that can be overriden. 
- add virtual `heapsize()` method to ImageInput and ImageOutput that return the total heap allocated memory held by the structure and its members.
Related PR from Larry : https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4317
First PR: https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4322
> api: add virtual heapsize() to ImageInput and ImageOutput

- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/texture.h
- src/libtexture/environment.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_memory_print.h
- src/libtexture/imagecache_memory_pvt.h
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture3d.cpp
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
Background: The ImageCache and TextureSystem had historically been implemented as pure virtual abstract base classe defining an interface, then a hidden concrete subclass. The flexibility this was intended to provide was never really used; instead the imagined main client for the flexibility, OSL, has a different mechanism for customizing the texture system (via their RendererServices class). Meanwhile, this has made the interfaces to IC and TS impossible to change without breaking the ABI.
So this PR does the following:
* ImageCache and TextureSytem are fullly de-virtualized, and are now concrete classes, no hidden subclassing, no virtual methods. As such, removing or changing existing methods will be an ABI break, but adding new methods is not.
* Each now use a PIMPL idiom, where all …
> refactor: de-virtualize IC and TS

- src/doc/oiiotool.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/color.h
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/color_ocio.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_colorconfig.cpp
- src/python/py_imagebufalgo.cpp
- ColorProcCacheKey: Update definition, signature, and usage to support caching NamedTransform processor handles.
(Note: **ABI-breaking**)
- ColorConfig: add NamedTransform convenience functions: `getNumNamedTransforms`, `getNamedTransformNameByIndex`, `getNamedTransformNames`, `getNamedTransformAliases`
- ColorConfig: add `createNamedTransform` function returning new ColorProcessorHandle
- Add `ImageBufAlgo::ocionamedtransform` functions
- oiiotool: add `--ocionamedtransform` operator
- python: add NamedTransform convenience function bindings
- python: add `ImageBufAlgo.ocionamedtransform(...)` bindings
- Update `oiiotool` and `python` documentation with examples
OCIO-2 config authors may define a set of stand-alone "source-agnostic" `NamedTransforms`. Unlike the `colorconvert`, …
> feat: implement support for OCIO NamedTransforms

- src/include/OpenImageIO/detail/fmt.h
- src/include/OpenImageIO/strutil.h
- src/include/imageio_pvt.h
- src/libOpenImageIO/imageio.cpp
- src/libutil/strutil.cpp
- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool/ref/out.txt
- testsuite/oiiotool/run.py
When fmt arguments don't match the format string, fmt will throw an exception, or terminate if we disable exceptions (which we do).  For gcc11+, we tried intercepting these, but let's do it for all platforms, and let's not terminate ourselves, but insted print and log the error.
But, oof, to do this properly, I needed to move some error recording functionality from libOpenImageIO to libOpenImageIO_Util and make it owned more properly by strutil.cpp, so that this all works even when only using the util library. The logic isn't changing, it's just moving over to the other library.
This all helps to address #4388
Unfortunately, the exception thrown by fmt doesn't tell us the bad format string itself. That would have really allowed to probably zero right in on it. But at least we know it's …
> fix: Don't let fmtlib exceptions crash the app

- src/doc/index.rst
The link points to the Apache 2.0 license, we just never changed the label here.
> docs: Switch license name in docs

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- src/build-scripts/gh-installdeps.bash
- src/doc/Makefile
This allows somebody who is enhancing the docs to check the results entirely through CI without having to set up the dependencies necessary for docs on their end. (Perfect for Dev Days.) It also ensures that any changes we make to the code base don't break the documentation somehow, because now a successful docs build will be part of the CI.
Note that the docs building job leave behind an artifact, which will be a zip file of the directly containing the HTML docs, just like one would fine on RTD, so you can download that zip file and view the docs it made to verify that everything looks right.
I made the docs builder a separate workflow, but I also changed some things in the CI workflow for the sake of making them more similar.
> ci: add a workflow that builds docs

- src/libOpenImageIO/imagebufalgo_demosaic.cpp
- testsuite/oiiotool-demosaic/ref/out.txt
- testsuite/oiiotool-demosaic/run.py
Fixes the bug where IBA::demosaic only works with float images. 
Fixes#4416
I've extended the unit tests to run on float, half, uint16, uint8 images.
nonconforming.
> fix demosaicing of int images

- CMakeLists.txt
- src/include/OpenImageIO/function_view.h
- src/include/OpenImageIO/imagebufalgo_util.h
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
When I added perpixel_op recently, I didn't get the function signature right. It only would work for plain old function pointers, and would not work properly for "functors" or lambdas with capture. I should have used function_view which can do a light-weight wrapper of all three, so now I do. Also modified imagebufalgo_test to explicitly test all three forms to be sure they work.
Also update function_view ever so slightly.
> api: Adjust IBA::perpixel_op function signature

- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
With 3.0 approaching, it seems like the only time to make these changes that I made note of a while back:
* It seems to me that `tell()` should be const because it isn't going to modify or change the state of the IOProxy.
* It seems to me that `flush()` should NOT be const, because it probably does change internal state.
> api: IOProxy const method adjustments

- src/cmake/externalpackages.cmake
We no longer supply a FindOpenColorIO.cmake, so it makes no difference. But it was getting in the way of a weird case where a wrapping project wanted to supply one.
> build: No need for OCIO search to use PREFER_CONFIG

- testsuite/oiiotool-demosaic/ref/out.txt
- testsuite/oiiotool-demosaic/run.py
This test was running very slowly, taking too long in all circumstances, but shockly causing GHA CI Mac runners to hit the test timeout sometimes.
It turns out we were doing a lot of redundant work. There was no need to make separate pattern and bayer images for every data type. Instead, hoist the test image generation out of the loop and just make one (float), then use `-i:type=<type>` to read it into an ImageBuf of the appropriate data type.
This cuts the time for this test to run by about 3x.
> test: Optimize running of oiiotool-demosaic test

- src/doc/imagebufalgo.rst
- src/doc/pythonbindings.rst
Oops.
I didn't really have time to add an "example" right now. I hope to return to beef this up (or that somebody else takes it on).
> docs: IBA::st_warp was missing from the documentation

- CMakeLists.txt
- src/doc/imagebuf.rst
- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/span.h
- src/iv/imageviewer.h
- src/iv/ivgl.cpp
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
- src/libOpenImageIO/imagebufalgo.cpp
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/imagebufalgo_deep.cpp
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imagebufalgo_xform.cpp
- src/libOpenImageIO/maketexture.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/texturesys.cpp
- src/python/py_imagebuf.cpp
- src/python/py_oiio.h
- src/term.imageio/termoutput.cpp
- src/testtex/testtex.cpp
Next round of making safer interfaces. Primarily, this adds new span-baesd versions of ImageBuf::get_pixels, set_pixels, setpixel, getpixel, interppixel, interppixel_NDC, interppixel_bucibuc, interppixel_bicubic_NDC.
The old ones took raw pointers and implied sizes -- these still exist but are considered "unsafe" and aimed at experts and special cases. (If a downstream project wants to be sure not to use them, they can define symbol "OIIO_IMAGEBUF_DEPRECATE_RAW_PTR" before including imagebuf.h to force deprecation warnings.)
The new additions instead take a span -- a combined pointer and length that can be bounds-checked (in debug mode). I strongly encourage people to use the new interface, as it forces the caller to think hard about the exact region of memory that's ok to read from or …
> api(IB)!: Add span based ImageBuf methods for getpixel/setpixel

- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool-control/ref/out.txt
Basically, this switches to creating the colorconfig that oiiotool uses from statically constructed to build-on-demand, which should slightly lower runtime overhead for oiiotool invocations that don't need to do any color transformations.
> perf(oiiotool): use pointer not static for internal color config

- testsuite/oiiotool/ref/out-fmt8.txt
For old versions of fmt library, some error output was slightly different.
Address it with an additional acceptable reference output for the oiiotool
test.
> testing: add test ref for old fmt

- src/raw.imageio/rawinput.cpp
This adds a null pointer check in the raw input plugin when the user requested raw bayer data for a file format which doesn't have it. With this fix OIIO shows an error instead of crashing in such case.
This fixes the issue mentioned in the comments of #4361. The title issue of #4361 has been resolved in LibRaw 0.22.0, so we can close that issue, I guess.
This also fixes the crash on 5 out of 6 examples in #3115. The last one is unrelated, and I don't have a good fix for that at this time (crash due to the raw buffer having half resolution, with the pixel aspect ratio of 0.5). Perhaps we could create a separate issue and close #3115. 
I have not added any tests for this change specifically, as it is fairly trivial. 
I have started working on a more comprehensive test suite for the raw …
> fix(raw) check for nullptr in raw input plugin

- src/pnm.imageio/pnminput.cpp
Fixes #4445
This avoids UB by initializing a variable.
I ran valgrind after the fix: no longer issues error.
```
==77256== 
==77256== HEAP SUMMARY:
==77256==     in use at exit: 25,167,390 bytes in 8,232 blocks
==77256==   total heap usage: 183,524 allocs, 175,292 frees, 4,415,783,216 bytes allocated
==77256== 
==77256== LEAK SUMMARY:
==77256==    definitely lost: 0 bytes in 0 blocks
==77256==    indirectly lost: 0 bytes in 0 blocks
==77256==      possibly lost: 0 bytes in 0 blocks
==77256==    still reachable: 25,167,390 bytes in 8,232 blocks
==77256==         suppressed: 0 bytes in 0 blocks
==77256== Rerun with --leak-check=full to see details of leaked memory
==77256== 
==77256== For lists of detected and suppressed errors, rerun with: -s
==77256== ERROR SUMMARY: 0 errors from 0 …
```
> Initialize m_pfm_flip before use to avoid UB.

- src/doc/imageinput.rst
- testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
- testsuite/docs-examples-python/src/docs-examples-imageinput.py
Convert error checking C++ and Python examples from the "imageinput" chapter into tests within the "docs-examples" testsuites (https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/3992).
nonconforming.
> docs:imageinput-errorchecking

- testsuite/python-colorconfig/ref/out-ocio24.txt
This fixes OIIO's CI "bleeding edge" test that broke when OCIO pushed
to their main the new config files that will be in OCIO 2.4. (Yay!)
> testing: Update test ref output for OpenColorIO 2.4

- src/doc/imageinput.rst
- testsuite/docs-examples-cpp/run.py
- testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
- testsuite/docs-examples-python/run.py
- testsuite/docs-examples-python/src/docs-examples-imageinput.py
Convert tiles C++ and Python examples from the "imageinput" chapter into tests within the "docs-examples" testsuites (https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/3992).
nonconforming.
> docs: Convert ImageInput tiles examples from docs to tests

- src/doc/imagebufalgo.rst
- testsuite/docs-examples-cpp/ref/out-arm.txt
- testsuite/docs-examples-cpp/ref/out.txt
- testsuite/docs-examples-cpp/run.py
- testsuite/docs-examples-cpp/src/docs-examples-imagebufalgo.cpp
- testsuite/docs-examples-python/ref/out-arm.txt
- testsuite/docs-examples-python/ref/out.txt
- testsuite/docs-examples-python/run.py
- testsuite/docs-examples-python/src/docs-examples-imagebufalgo.py
This a documentation to testsuite conversion for cpp and python for the ImageBufAlgo Chapter, Section: Image Arithmetic up to the div function.
The PR also fixes a python testing image file reference in ..docs-examples-python/ref/out.txt, where reference images "simple.tif" and "scanlines.tif" should have the docs-examples-cpp prefix (see ..docs-examples-python/run.py line 11 for details).
Verified in SPI build environment that existing tests are working. …
> docs: convert to test for ImageBufAlgo Partial Image Arithmetic

- src/jpeg.imageio/jpeginput.cpp
- src/openexr.imageio/exrinput.cpp
- src/png.imageio/pnginput.cpp
This PR is ment to address this feature request: https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/3974
I added `check_open` for these file format's ImageInput while following each file specfication:
- PNG: https://www.w3.org/TR/png/#11IHDR
- JPEG: https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format#JFIF_APP0_marker_segment
- EXR: https://openexr.com/en/latest/OpenEXRFileLayout.html#header-attributes-all-files
test that runs …
> Added check_open for PNG, JPEG, and EXR readers

- src/iconvert/iconvert.cpp
- src/include/OpenImageIO/imagecache.h
- src/include/OpenImageIO/texture.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagecache_test.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_pvt.h
- src/libtexture/texture_pvt.h
- src/libtexture/texturesys.cpp
- src/oiiotool/imagerec.cpp
- src/python/py_imagecache.cpp
- src/testtex/testtex.cpp
First draft of frontend changes for  issue #4436.
- [ ] change backend to reduce memory usage (might be a different PR)
> api: remove redundant ImageSpec from ImageCache (issue #4436)

- src/iv/imageviewer.cpp
- src/iv/imageviewer.h
- src/iv/ivgl.cpp
- src/iv/ivgl.h
Adding data and display window overlay in iv.
Dashed line: Display window
Solid line: Data window
nonconforming.
> feat: add iv data and display windows overlay

- src/libOpenImageIO/imageoutput.cpp
When writing a partial tile, the unused pixels still go through float conversion.
This means, that floating point operations are done on uninitialized data.
This can easily lead to NaN and to floating point exceptions, if those were to be enabled.
This change will set the shared buffer used for all partial tiles to all zero pixels.
Tested by running valgrind before and after the change
FIXES: #4461
test that runs clang-format and fix anything that it …
> [image output] Initialize pixels of partial tile conversion buffer.

- src/doc/builtinplugins.rst
- src/raw.imageio/rawinput.cpp
PR is to address https://github.com/AcademySoftwareFoundation/OpenImageIO/issues/3881 feature request. The reported wanted to expose `imgdata.rawparams.max_raw_memory_mb` as `raw:max_raw_memory_mb`
I was able to compile my code successfully, no new test were added for this.
nonconforming.
> feat(raw): raw reader - exposing max_raw_memory_mb

- .github/workflows/ci.yml
- src/build-scripts/install_homebrew_deps.bash
It's an old flavor not well supported by homebrew any longer, so what's happening is that most of the dependency packages we ask to install have to build from source, which means it takes a long long time.
By disabling OpenCV and Qt homebrew installation for it, we can make it fast again. Neither the minimal OpenCV interop, nor osltoy (the only thing that needs Qt) are exercised by the automated testsuite anyway, so I don't think there's any loss of testing functionality in practice.
> ci: Streamline the old MacOS-12 CI test

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- INSTALL.md
- src/build-scripts/build_openexr.bash
- src/cmake/externalpackages.cmake
OpenEXR 3.3 was just released and its main branch has bumped its advertised version to 4.0 (the latter breaking our "bleeding edge" CI test).
Raise our "latest releases" test to use 3.3.
Our "bleeding edge" test picking up the now-called-4.0 OpenEXR main branch required some minor logic changes to not reject the version as too new to be compatible.
> ci: Test against OpenEXR 3.3 and deal with its 4.0 bump

- docs/ROADMAP.md
> Update OpenImageIO Roadmap

- src/openexr.imageio/exroutput.cpp
Starting with OpenEXR 3.1.3, the preferred API call for setting DWAA/DWAB compression level has changed. We never changed the OIIO side. Luckily, OpenEXR seems to have kept respecting the old API calls we were making (passing as an attribute). But this modernizes the approach, now that we don't have OpenEXR 2.x support to maintain.
But in the process, we also fixed a bug! Turns out we weren't
propagating the compression properly -- if the compression name
was plain "dwaa", we ignored any "openexr:dwaCompressionLevel"
attribute, effectively.
> fix(openexr): modernize dwa compression level setting

- CMakeLists.txt
When building OIIO as a subdirectory of a super-project (with `add_subdirectory`), it is better to honor the output directories specified by the parent project.
In our project, it was causing issues because OIIO libs were ending in a different folder from USD plugins, which thereby failed to load correctly in the build tree.
nonconforming.
> build: Don't change CMAKE_XXX_OUTPUT_DIRECTORY when built as subdir

- src/cmake/testing.cmake
- testsuite/dpx/ref/out.txt
- testsuite/gif/ref/out.txt
- testsuite/ico/ref/out.txt
- testsuite/png-damaged/run.py
- testsuite/png/ref/out-libpng15.txt
- testsuite/png/ref/out.txt
- testsuite/psd/ref/out.txt
- testsuite/rla/ref/out.txt
- testsuite/rla/run.py
I refactored the companion project full of testing images, putting all the clutter in the main directory into a subdirectory for each file type. These are the main OpenImageIO changes needed as a result.
> testing: Fixup after directory refactor of OpenImageIO-images

- src/include/OpenImageIO/imagebuf.h
- src/include/OpenImageIO/imagebufalgo_util.h
I was profiling the builds and saw that modules with lots of template expansion dominate the compile time. For example,
imagebufalgo_pixelmath.cpp alone took 290s to compile on my 2020 MacbookPro (!), and imagebufalgo_addsub.cpp took 84 seconds.
This is all due to the combnatorics of expanding IBA templates via the DISPATCH macros in imagebufalgo_util.h separately for every type that the arguments can be. But I claim that most combinations are rarely if ever used. I mean, how often does anybody need IBA::add() to add an int8 image to an int16 image? So this PR rewrites those macros to simplify the cases as follows:
* The common pixel data types are float, half, unint8, and uint16.
* Specialized versions are fully expanded only when the result and input images are one of these types. …
> perf: Reduce compile time by trimming template expansion in IBA

- CMakeLists.txt
- src/bmp.imageio/bmpinput.cpp
- src/bmp.imageio/bmpoutput.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/pnm.imageio/pnmoutput.cpp
A few minor changes were needed to keep a working build, due to things long ago rigged to be disabled as soon as the version bumped.
> Bump version to 3.0.0.0, prepare for beta

- src/include/OpenImageIO/strutil.h
- src/libutil/strutil.cpp
This finally switches Strutil::format to use std::format conventions. You can still access the old printf convention via `Strutil::old::format()`, and can explicitly access the new convention uniformly on both 2.x and 3.x via `Strutil::fmt::format()`.
It also removes a long-deprecated vformat function.
We've been waiting for 3.0 to make this non-back-compatible change.
> api: Change Strutil::format to default to std::format conventions

- .github/workflows/ci.yml
- src/build-scripts/gh-installdeps.bash
It's failing to get Mesa packages for some reason. Disable Qt and OpenCV on this one test to work around it for now.
> ci: Fix broken bleeding edge test

- src/include/OpenImageIO/texture.h
- src/testtex/testtex.cpp
I got part way through the OSL side changes to accommodate what we did
recently with TextureOpt and TextureOptBatch. Ugh, it's a lot harder than
I thought and I don't know how to finish the job without postponing the
3.0 release even more, which is unacceptable at this point. So here I do
to TextureOptBatch to get out of this mess:
* "Version" TextureOptBatch like we did for TextureOpt (should have done
that all along).
* Revert "v1" to the same byte-for-byte layout we used to have, which
involves using `int` for some fields as it implicitly did before, because
the new enum classes totally change the field sizes and struct layout.
* Sketch out in comments what v2 might look like, to more fully match the
TextureOpt. The introduction of struct versioning means we can make that
change for …
> TS: Version TextureOptBatch like we did for TextureOpt

- .github/workflows/docs.yml
Times we DON'T need to test rebuilding the docs:
* When just the ci.yml workflow changes (like when we bump what versions of dependencies ci tests use).
* When tests changes only by altering their run.py.
But DO try rebuilding docs:
* When cpp files change that are outside of src/, such as the cpp files in the testsuite that are used to supply code snippets that appear in the docs.
> ci: Limit when automatic docs building ci happens

- src/iinfo/iinfo.cpp
- src/oiiotool/printinfo.cpp
- testsuite/iinfo/ref/out-fmt6.txt
- testsuite/iinfo/ref/out.txt
A logical error was causing us to not correctly cycle through the successive MIP levels. Somehow, we missed this all these years.
You can tell that there was something wrong all along by examining the testsuite/iinfo test output (which we have updated here) -- in the old/wrong one, the statistics "FiniteCount" suspiciously stayed the same for all MIP levels, which is clearly wrong. Now you can see that it does correctly reflect the reduced resolution of each MIP level.
This bug was limited to 'iinfo' itself. There wasn't any inherent problem with reading MIP levels directly with ImageInput or ImageBuf.
The line with the bug has been unchanged for 14 years! We were trying to be clever about not double-reading, except that the only context in which this was called, that would never have …
> fix(iinfo): iinfo was not reading MIP levels correctly

- src/cmake/externalpackages.cmake
Detect libbz2 only if necessary, i.e., FFmpeg or FreeType is enabled. This avoids an unnecessary dependency on libbz2 if these features are disabled.
In particular, with vcpkg, OpenImageIO might pick up a dependency on libbz2.so from the host system since bzip2 from vcpkg is not listed as a dependency of OpenImageIO (if the FFmpeg and FreeImage features are disabled, and bzip2 is not already installed for other reasons).
Build issue, no additional tests. …
> Detect libbz2 only if FFmpeg or FreeType is enabled.

- Makefile
- src/cmake/dependency_utils.cmake
- src/raw.imageio/rawinput.cpp
Address a few small issues encountered during CMake configuration step and during build using Makefile `BUILD_MISSING_DEPS` option enabled.
- Mismatch between expected libraw versions specified in `build_libraw.bash` 0.21.3 and `externalpackages.cmake` 0.20.0
- OpenEXR link error in libutil tests
- Update top level Makefile to accept `BUILD_MISSING_DEPS` as string instead of bool. Pass the string option down to CMake
Verified build completes with no errors: `BUILD_MISSING_DEPS=all make`
> BUILD_MISSING_DEPS - fix minor configuration options

- src/libOpenImageIO/maketexture.cpp
I don't understand why, but for certain combinations of gcc, fmt, etc., we were getting exceptions from fmt. I finally caught it in the act! It seems related to formatting specs that looks like `{:-20s}`. Maybe this used to be allowed but isn't officially supported? Anyway, left justification is default anyway, so there's no point to the `-`. Removing it makes fmt happy, no more exceptions.
> fix: address fmt exceptions for left justification

- src/libOpenImageIO/imagebufalgo_draw.cpp
Suggestion for issue #4504.
The PR removes the code that looks for font folders based on a prefix and suffix list. Instead, adds all known system font folders per each platform. The global "font_searchpath" attribute, `OPENIMAGEIO_FONTS` and `OpenImageIO_ROOT` environment variables are still searched as before, such as fonts directories relative to the currently running binary. However $HOME and $SystemRoot folders (with all previous suffixes) are not searched anymore, thus this is a breaking change, and the documentation might need to be updated accordingly.
The search order did not change. It's still "font_searchpath" attribute, environment variables, system font folders, folders relative to binary.
doesn't change …
> Update font enumeration

- docs/Deprecations-3.0.md
- src/include/OpenImageIO/string_view.h
Because it's not in std::string_view.
If you must use this functionality (with caution about when it is safe), then use the freestanding `OIIO::c_str(OIIO::string_view)` function instead.
I would like to include this warning in 3.0.
> api: Deprecate OIIO::string_view::c_str()

- .github/workflows/ci.yml
- INSTALL.md
The GHA macos-12 runner is deprecated and soon to be retired. It's already flaky and they're doing purposeful outages to remind people (the cloud equivalent of turning the lights on and off right before the bar closes).
We still want to test earlier MacOS-12 compatibility to match VFX Reference Platform, so use the macos-13 runner as the minmum but set MACOSX_DEPLOYMENT_TARGET=12.0 to test that configurations.
Also, the MacOS-15 runner is in beta, so add that to the mix. (Along the way, that also verifies that we run fine against python 3.13.)
> ci: Retire deprecated macos12 runner, try beta macos15

- src/libOpenImageIO/imagebufalgo.cpp
- testsuite/docs-examples-cpp/ref/out-arm.txt
- testsuite/docs-examples-cpp/ref/out.txt
- testsuite/docs-examples-python/ref/out-arm.txt
- testsuite/docs-examples-python/ref/out.txt
Replacing 3x IBA + Helper function that generate 4 fulls size image buffers with single unsharp_mask_impl() that use parallel_image() to compute unsharp: 
src + contr * (((src - blur) < threshold) ? 0.0 : (src - blur))
Added two pass 1D convolution for a kernels higher than 3x3
```
ImageBuf sharped(input.spec());
const int repeats = 50;
std::cout << "Start sharpening\n";
auto start = std::chrono::high_resolution_clock::now();
for (int i = 0; i < repeats; i++)
{
//ok = ImageBufAlgo::unsharp_mask(sharped, input, "gaussian", 15.0f, 10.0f, 0.01f);
ok = ImageBufAlgo::unsharp_mask(sharped, input, "gaussian", 5.0f, 2.0f, 0.05f);
std::cout << ".";
}
std::cout << "\n";
auto part1 = std::chrono::high_resolution_clock::now();
std::chrono::duration<double> elapsed_part1 = part1 - start;
std::cout << …
```
> IBA::Unsharp_mask() speed and memory optimization

- src/include/OpenImageIO/imagebufalgo.h
- src/include/OpenImageIO/imageio.h
- src/include/imageio_pvt.h
- src/libOpenImageIO/imagebufalgo_draw.cpp
- src/libOpenImageIO/imageio.cpp
Fixes #4503.
Add an API to query available fonts based on family and style name. The API can be used to build a UI where users can select a font from a list.
- **font_families()**: Return the list of available font families in alphabetical order.
- **font_styles(family)**: Return the list of available font styles of a given font family.
- **font_filename(family, style)**: Return the font filename that defines the font with the given family and style.
test …
> api: Add API to query available font families and styles

- src/cmake/add_oiio_plugin.cmake
- src/cmake/build_Freetype.cmake
- src/cmake/build_PNG.cmake
- src/cmake/externalpackages.cmake
- src/ico.imageio/CMakeLists.txt
- src/libOpenImageIO/CMakeLists.txt
- src/png.imageio/CMakeLists.txt
- src/png.imageio/png_pvt.h
> deps: Add build recipe for PNG

- src/doc/imageoutput.rst
It was pointed out on Slack that this example was unclear as to what should be passed to open().
> docs: Clarify 'copy_image' example

- src/raw.imageio/rawinput.cpp
The function libraw_filter_to_str() converts the `imgdata.idata.filters` field to human readable form, by mapping a few hardcoded values. I found the issue by converting images with disabled demosaicing, which writes the Bayer pattern into the ImageBuf metadata. The Panasonic GX9 didn't have any pattern recognised; The Canon R5 was incorrectly recognised as GMCY.
The `imgdata.idata.filters` actually contains a sequence of 2-bit values, where each represents an index in a 4-character long string `imgdata.idata.cdesc`. I have modified the code to extract the channels from `imgdata.idata.cdesc` as expected.
I have also disabled the normalisation code, which I believe was incorrect, and never executed due to the issue above.
The current tests pass, however, I'll start a discussion on the …
> [fix] raw: fix channel layout

- CHANGES.md
- CMakeLists.txt
This will mark the official start of the OIIO 3.0 era.
When this is merged and tagged tomorrow, 3.0 will be the new current fully-supported production release family, and 2.5 will be the obsolete release family that only gets important fixes.
> Stage for v3.0.0.3

- src/openexr.imageio/exrinput.cpp
When the exr "name" metadata (used for the names of subimages/parts) existed but was the empty string, we were treating it like it didn't exist (and upon write substituted our own "subimageXY" name, as we are wont to do for unnamed parts). But now we've seen multi-part exrs where the name is "" (exists, but empty string) and we want a read-write cycle to preserve that. Even though it's not a very sensible or helpful part name, it's technically legal, so we should honor it.
> fix(exr): allow an empty "name" metadata to be read

- .github/workflows/ci.yml
Slow Mac runners sometimes take too long and fail needlessly.
> ci: increased the macos timeout slightly to fix spurious failures

- src/oiiotool/oiiotool.cpp
These commands, which are intended to alter the top image on the stack, were each allocating and copying an image unnecessarily for each operation. By changing the implementation to the right calls that know it doesn't need to make a copy (already a feature I'd implemented in the OiiotoolOp helper class) greatly speeds them up.
> perf: oiiotool --line --text --point --box speedups

- README.md
- docs/dev/Architecture.md
Having such a document is one of the remaining steps to getting our OpenSSF Best Practices silver level badge.
> doc: First stab at an archiecture overview

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
> fix(exr): Avoid integer overflow for large deep exr slice strides

- src/jpeg2000.imageio/jpeg2000input.cpp
Primary cost of detecting whether a given file is valid jpeg2000 file is the thread pool initialization and shutdown that  `Jpeg2000Input::open` does (the actual thread pool part is inside OpenJpeg code).
So add a dedicated `valid_file()` implementation that only needs to check 12 bytes of the header. While at it, I changed already existing `isJp2File()` to `is_jp2_header()` to better match naming conventions used elsewhere, and instead of trying to handle both little and big endian cases by manual repetition of two sets of magic integers, let's do just byte comparisons with `memcmp` instead.
On my PC (Ryzen 5950X, SSD, Windows VS2022), doing `ImageInput::create()` on 1138 files where they are not images at all (so OIIO in turns tries all the input plugins on them):
- Before: **3.4 …
> jpeg2000: valid_file implementation, much faster than trying to open

- src/libutil/strutil.cpp
OIIO 2.3.13 with PR #3307 changed MultiByteToWideChar/WideCharToMultiByte usage to C++11 <codecvt> functionality, but that has two issues:
1) it is *way* slower, primarily due to locale object access (on Visual C++ STL implementation in VS2022 at least). Since primary use case of these conversions is on Windows, maybe it is better to use a fast code path.
2) whole of <codecvt> machinery is deprecated with C++17 accross the board, and will be removed in C++26. I've kept the existing functions in there since otherwise it would have been an API break, but really maybe with OIIO 3.0 they should have been un-exposed. Too late now though :(
Performance numbers: doing ImageInput::create() on 1138 files where they are not images at all (so OIIO in turns tries all the input plugins on them). Ryzen …
> perf: faster utf8<->utf16 conversion on Windows

- src/cmake/add_oiio_plugin.cmake
- src/libOpenImageIO/CMakeLists.txt
- src/raw.imageio/CMakeLists.txt
When using pkgconfig the value of `<NAME>_CFLAGS_OTHER` can contain compiler flags along with preprocessor definitions. If there is a compiler flag and its passed to `target_compile_definitions` then it will be treated as if it is a preprocessor definition.
Found a case where a statically compiled LibRaw with a statically compiled Little-CMS caused `LibRaw_DEFINITIONS` to have `-pthread` in its listing which was passed to the compiler as a definition, `-D-pthread`. This caused a build failure with `auto-moc`.
Add an additional parameter for the `add_oiio_plugin` macro to take `COMPILE_OPTIONS` and pass those to `target_compile_options` which can differentiate between compiler flags and preprocessor definitions. Pass `LibRaw_DEFINITIONS` to the CMake macro to prevent the above error.
Issue …
> build: Use target_compile_options

- src/include/OpenImageIO/imageio.h
- src/include/imageio_pvt.h
- src/libOpenImageIO/imageio.cpp
We don't do anything with this at the present time, but this PR reserves and documents this attribute for future use.
The intent is to be able to set whether we want image readers to try being as tolerant as possible when reading a file with flaws (press on and see if the rest of the file is ok?), or be more conservative and abandon reading any file as soon as a corruption or invalid data is encountered (because that might be a clue that the file is arbitrarily corrupted or even maliciously constructed).
I documented it as defaulting to 0 (err on the side of being permissive of bad input), with high-security applications being responsible for setting it to 1. But it's open for debate if people think that a better default is to be strict and let applications who want to be more tolerant be …
> api: Add global attribute `imageinput:strict`

- .github/workflows/analysis.yml
- .github/workflows/build-steps.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- src/build-scripts/ci-startup.bash
- src/build-scripts/install_homebrew_deps.bash
The logic for the GHA steps was repeated across multiple workflows and platforms. Consolidate it all into a common "ci-steps" workflow, and have all the other workflows reference that when possible. This should hopefully make maintenance of the CI scripts easier in the future, with less redundancy of the step logic.
The only major place where we deviate is that we have a separeately specified set of steps for the "old" VFX Platform 2021 and 2022 based tests (because we need to specify different container arguments to it).
> ci: refactor using a single steps workflow

- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/tiff.imageio/tiffoutput.cpp
It was syntactically correct, but without an actual variable, there was no RAII scope and so it destructs immediately, causing the timers to capture 0 time.
Found by Sonar warnings.
> fix: some LoggedTimer instances lacked a variable name

- src/doc/stdmetadata.rst
- src/libOpenImageIO/iptc.cpp
- testsuite/jpeg-metadata/ref/out.txt
It escaped our notice before that the IPTC spec dictates length limits for many fields. Getting this wrong can confuse some software, including Photoshop, apparently.
This patch enforces length limits wherever we could figure them out from the IPTC spec -- it will simply truncate those strings that are too long before writing them to a binary IPTC tag.
For this reason, we also are ending the practice of automatically translating several IPTC fields to and from what we figured were the equivalent generic metadata names. This was perhaps a dubious practice to begin with, but now the enforcement of length limits for IPTC (but not the generic metadata) makes it even more frought. There is probably nobody depending on this behavior (and maybe few OIIO users depending on IPTC support at all?), …
> fix: IPTC fields have length limits

- sonar-project.properties
- src/dpx.imageio/dpxoutput.cpp
- src/include/OpenImageIO/benchmark.h
- src/libOpenImageIO/color_ocio.cpp
- src/libutil/filesystem.cpp
- src/libutil/sysutil.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
Chipping away at minor warnings and areas identified by static analysis as potentially problematic or hard to analyze.
* benchmark.h: suppress warnings about uninitialized Benchmarker members.
* dpxoutput.cpp: change some raw pointers to spans
* dead code removal (color_ocio.cpp, filesystem.cpp, sysutil.cpp)
* exclude build-scripts from static analysis
* some misc warning suppression
> fix: various internal fixes to address Sonar and other warnings

- .github/workflows/build-steps.yml
- .github/workflows/ci.yml
- .github/workflows/scorecard.yml
* Upgrade upload-artifact action, old one is being deprecated.
* Update checkout and cache actions to latest.
* Fix workflow warning: save-always is not really an input to
actions/cache.
> ci: Upgrade to newer actions

- src/cmake/testing.cmake
- testsuite/ptex/ref/out.txt
- testsuite/ptex/run.py
* Ptex testsuite entry had been accidentally disabled somewhat recently when we switched to using Ptex exported cmake config instead of our own find module, because the "found" variable changed from PTEX_FOUND to Ptex_FOUND.
* Change the test to print stats, thus forcing the ptex test to read pixels instead of just header info, which improves the testing coverage of ptexinput.cpp.
> testing: improve Ptex testing

- src/doc/oiiotool.rst
Correct `botromright` typo in `oiiotool` documentation.
> doc: fix typo in oiiotool's gradient fill argument

- src/null.imageio/nullimageio.cpp
- testsuite/null/ref/out.txt
- testsuite/null/run.py
This improves the mediocre testing line coverage in nullimageio.cpp from 50% to 95%.
* Test writing
* Test reading of tiled and MIP-mapped null images
* Test setting and reading of attributes
* Simplify some code
* Along the way, identified and fixed a nullimage bug -- it was answering that it supported "rectangles" but had no write_rectangle method. Testing works!
> testing: better testing coverage of null image reader/writer

- INSTALL.md
- src/build-scripts/build_cmake.bash
* When the script was run on aarch64, it was actually hard-coded to retrieve a version older than we currently require as a minimum. Use the CMAKE_VERSION hint just like we do for x86_64.
* Bump the default version that this script makes to the latest, 3.31.3.  (This does not change OIIO's minimum required cmake version, it merely changes the default if this hepler script that we use for CI is run without any specific version requested.)
> build: fix build_cmake.bash script for aarch64, bump its default version

- .github/workflows/ci.yml
For reasons that are unclear (maybe a change to which python versions are installed where on the GH runners?) this seems to have broken within the past couple days, in a way that did not correspond to any change we made on the OIIO side.
> ci: Fix Windows 2019 CI -- make python version match the runner

- src/doc/oiiotool.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagebufalgo.h
- src/libOpenImageIO/imagebufalgo_demosaic.cpp
- src/libOpenImageIO/imagebufalgo_demosaic_prv.h
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/raw.imageio/rawinput.cpp
Implements X-Trans pattern demosaicing using a simple bilinear algorithm. Adds the Xtrans pattern layout to the ImageBuf attributes in the raw reader plugin. 
I have implemented unittests in imagebufalgo_test.cpp which cover all permutations of the Bayer and X-Trans layouts, as the X-Trans pattern is a bit too complicated to generate using oiiotool.
nonconforming.
> [feat]IBA:demosaic add X-Trans demosaicing

- .github/workflows/ci.yml
- INSTALL.md
* Bump the 'latest' test to test the actual latest, 1.15.
* Be sure that the 'oldest' tests actually test the oldest we support, 1.8.
* Sprinkle around a couple other versions that we don't test currently.
> ci(deps): Adjust some pugixml versions

- .github/workflows/ci.yml
- CMakeLists.txt
- src/doc/Doxyfile
- src/include/OpenImageIO/oiioversion.h.in
TL;DR: In main, change the enclosing namespace from `OpenImageIO_v3_1` to a 2-level scheme: `OpenImageIO::v3_1`.  This can't be backported to the current release for obvious ABI cmopatibility reasons; it is a forward-looking change only.
More ponderous explanation follows:
We have for some time had a single namespace that incorporates the version, defaulting to `OpenImageIO_v3_0` in the current release, for example.  A namespace alias, `OIIO`, always aliases the current namespace, so client applications can just say `OIIO::foo` without needing to change source code for every minor release (let alone if a build-time option sets up a custom namespace).
By bumping the namespace for every minor release, we use the symbol names themselves to enforce a rigid ABI compatibility test, so you can't …
> api: make a 2-level namespace scheme

- src/include/OpenImageIO/paramlist.h
- src/include/OpenImageIO/typedesc.h
- src/libutil/paramlist.cpp
Convenience methods that give a bounded span of the data that a PV holds.
> paramlist.h: ParamValue::as_span(), as_cspan()

- src/cmake/testing.cmake
- src/softimage.imageio/softimageinput.cpp
- testsuite/softimage/ref/out.txt
- testsuite/softimage/run.py
Also some very minor code cleanup that was helpful in setting up the test cases and getting better code coverage.
> testing: at long last, set up a softimage reading test

- testsuite/jpeg-corrupt/ref/out-alt4.txt
Found a version of a dependency with a slightly different error wording that got reported back.
> testing: Additional ref output for jpeg-corrupt test

- src/psd.imageio/psdinput.cpp
- testsuite/psd/ref/out.txt
- testsuite/psd/run.py
Perform the endian byteswap on the correct buffer area for PSD RLE decoding.  The original code used `dst` but that pointer is modified from its original value as it progresses through decoding.
Fixes #4599 
It might be prudent to add a test for this.  Is the repro file attached to the bug too big for this repo(842kb) or do you want them in the oiio-images repo maybe?
nonconforming.
> fix(pdf): Perform endian byteswap on correct buffer area for PSD RLE

- src/libOpenImageIO/imagebufalgo_demosaic.cpp
Fixes a bug in demosaicing where the code ignores the ROI channels.
The old behaviour was to always decode into the first 3 channels.
None of the current tests use preallocated output buffers. Should we have some? The change is fairly trivial though.
nonconforming.
> fix(IBA): demosaic - fix roi channels

- src/raw.imageio/rawinput.cpp
Adds attributes to the output ImageBuf for the black level and bit depth when the raw bayer buffer is requested.
I believe we don't test the retrieved metadata currently. We may want to start doing that eventually?
nonconforming.
> feat(raw): add black level and BPS metadata

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/texture.h
- src/include/OpenImageIO/typedesc.h
- src/include/imageio_pvt.h
Our minimum C++ version allows `inline constexpr`, just use it.
> cleanup: no longer need OIIO_INLINE_CONSTEXPR macro

- .github/workflows/wheel.yml
Use the publicly-available ARM-native linux runners for CI checks and building Python wheels
> ci: Switch to using ARM-native linux runners

- .github/workflows/wheel.yml
We were only running the wheel workflow on pushes of TAGS, but this change also will run it when we push to release, and dev-3.* branches.
My usual release workflow is to first push the "release" branch, watch for it to pass CI, then add the tag and push the tag and draft the release.  If a problem with the wheel workflow isn't discovered until we've already pushed the tag, then a fix will require a new tag and new release (we never re-tag a release). So this change will allow us to catch any problems with the wheel worflow BEFORE we actually irrevocably make the tag, since it's no big deal to add corrections to the branch before tagging. It still won't upload the wheels until the tag itself is pushed.
> ci: Run wheel workflow on certain pushes

- src/libOpenImageIO/imagebuf.cpp
The implementation of IB::pixeltype() was:
- Make sure at least the spec had been read (lazy read).
- If there are "local pixels", return the pixel type from the spec, otherwise return the cache pixel type.
But there is a flaw in this logic: If only the metadata has been read but not the pixels, the local pixels might not be allocated yet, but also there is not a cache and no cached pixel type, so pixeltype() will return UNKNOWN even though we do already know what type of pixels will be stored when they are eventually read.
The correct logic is:
- Make sure at least the spec had been read (lazy read).
- If it's a cached image, return the cache pixel type, otherwise return the pixel type from the spec (which will be correct because we definitely have read the spec at this point).
Also, for …
> fix(ImageBuf): IB::pixeltype() did not always return the right value

- src/cmake/compiler.cmake
- src/cmake/fancy_add_executable.cmake
- src/libutil/CMakeLists.txt
As part of the recent big python wheel merge, compiler.cmake got changed in a subtle way in how it sets CMAKE_INSTALL_RPATH.
This broken iv for me on a Mac with dynamic libraries. Strangely (and I'm too lazy to chase down exactly why), oiiotool seems fine.  So this was missed entirely by the CI, which never runs 'iv', since it's an interactive app. (Note to self: we should find some way to at least verify that it can execute as part of the testsuite.)
Anyway, I believe that this change adds the install lib area back to the path, and it does seem to repair my ability to run iv on my end.
> fix(build): Fix recently broken rpath setting

- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool-control/ref/out.txt
When you use frame or view wildcards, for example:
oiiotool foo.%04d.tif -o bar.%04d.exr
we noticed that if NO files matched, no iteration would occur. You would get this output:
```
$ oiiotool foo.%04d.tif -o bar.%04d.exr
oiiotool WARNING : oiiotool produced no output. Did you forget -o?
```
But maybe this is not helpful and it should be some kind of error to ask for a match and not get one? Or at least give a more clear explanation of what happened.
This PR detects the case where there is no match of the wildcard at all, warns about that, and then tries interpreting the command line literally (no wildcard expansion). So now the output is
```
$ oiiotool foo.%04d.tif -o bar.%04d.exr
oiiotool WARNING : No frame number or views matched the wildcards
oiiotool ERROR: read : File does not …
```
> oiiotool: better handling of wildcards that match no files

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- testsuite/dup-channels/ref/out.txt
- testsuite/iinfo/ref/out-fmt6.txt
- testsuite/iinfo/ref/out.txt
- testsuite/maketx/ref/out-macarm.txt
- testsuite/maketx/ref/out.txt
- testsuite/oiiotool-attribs/ref/out-jpeg9d.txt
- testsuite/oiiotool-attribs/ref/out.txt
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-deep/ref/out-fmt6.txt
- testsuite/oiiotool-deep/ref/out.txt
- testsuite/oiiotool-fixnan/ref/out.txt
- testsuite/oiiotool-maketx/ref/out-macarm.txt
- testsuite/oiiotool-maketx/ref/out-rhel7.txt
- testsuite/oiiotool-maketx/ref/out-win.txt
- testsuite/oiiotool-maketx/ref/out.txt
- testsuite/oiiotool-subimage/ref/out.txt
- testsuite/oiiotool/ref/out.txt
- testsuite/openexr-chroma/ref/out.txt
- testsuite/openexr-decreasingy/ref/out.txt
- testsuite/openexr-luminance-chroma/ref/out-macarm.txt
- testsuite/openexr-luminance-chroma/ref/out.txt
- testsuite/openexr-multires/ref/out.txt
- testsuite/openexr-suite/ref/out.txt
- testsuite/openexr-v2/ref/out.txt
- testsuite/openexr-window/ref/out.txt
- testsuite/rational/ref/out.txt
Fill in OpenEXR lineOrder attribute when parsing the header in OpenEXRCoreInput::PartInfo::parse_header()
nonconforming.
> fix(exr): fill in OpenEXR lineOrder attribute when reading

- src/cmake/compiler.cmake
- src/include/OpenImageIO/image_view.h
The newer versions of the compilers we now use no longer need this.
> cleanup: Get rid of some compiler symbols no longer needed

- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imagebuf_test.cpp
There was a bug in span_from_buffer when strides were negative (basically, we were subtracting, when adding was correct since those strides were negative values).
Also added a negative stride test to imagebuf_test.cpp. Embarrassed that we didn't already have this, since it would have caught the problem.
> fix(ImageBuf): Fix bug in ImageBuf construction from ptr + neg strides

- src/doc/oiiotool.rst
- src/oiiotool/expressions.cpp
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
Included two additional metadata boolean checks for constant and black frame images, so that handling for those image cases are facilitated.
IS_CONSTANT and IS_BLACK return 1 when true, and 0 when false.
No new tests added to testsuite for now, but tested with local build copy of oiiotool and test images to ensure it behaved as expected.
nonconforming.
> feat(oiiotool): oiiotool new expression eval tokens IS_CONSTANT, IS_BLACK

- .github/workflows/wheel.yml
- src/cmake/compiler.cmake
Also, make the wheel workflow work on pushes when the branch name
contains the substring "python" or "wheel", and when any of the cmake
build files in src/cmake (which control building of dependencies,
among other things), even if none of the python bindings themselves
are touched. This means that if you suspect your work might cause a
wheel to break even though you're not modifying the python bindings
directly, you can ensure that the wheel workflow will run on CI simply
by naming your branch to contain one of those words.
> build: fix recently broken rpath to restore python wheel building

- src/cmake/compiler.cmake
Always use patch-specific SO versioning for scikit-build-core-based builds, even when OpenImageIO_SUPPORTED_RELEASE=ON.
Fixes #4621
Ensures that Python-based builds only bundle a single copy each of libOpenImageIO and libOpenImageIO_Util shared libraries. 
Previously, `$ uv sync -v --reinstall -Ccmake.define.OpenImageIO_SUPPORTED_RELEASE=1` would bundle both .so.3.0 and .so.3.0.3 copies of libraries when installing to a local virtual environment. 
With this fix, only .so.3.0.3 copies of libraries are installed.
> fix(wheels): Ensure python-based builds use maj.min.patch SO versioning

- pyproject.toml
- src/python/__init__.py
Adds "numpy" as a runtime requirement for the Python wheels.
Fixes #4637
> ci(wheels): Add `numpy` as a runtime requirement

- .github/workflows/ci.yml
- src/build-scripts/build_llvm.bash
- src/build-scripts/gh-installdeps.bash
- testsuite/raw/ref/out-libraw-0.20.2-gh.txt
In the process, port a more modern build_llvm.bash from osl.
> ci: Move away from soon-to-be-deprecated ubuntu-20.04 GHA runner

- src/include/OpenImageIO/sysutil.h
- src/iv/ivmain.cpp
- src/libutil/sysutil.cpp
Replaces the system() call with posix_spawn() on macOS to preserve environment variables. This is essential for Debug builds using DYLD_IMAGE_SUFFIX=_debug to prevent Qt from loading mixed configurations.
Run the iv application in background mode on macOS without the -F flag, using a Debug configuration. Previously, the system() call did not inherit the parent environment variables, causing a mix of Debug and Release versions of Qt to be loaded.
test that …
> fix(sysutil): improve the implementation of Sysutil::put_in_background on macOS

- src/jpeg.imageio/jpeginput.cpp
- src/jpeg2000.imageio/jpeg2000input.cpp
- src/png.imageio/png_pvt.h
- src/psd.imageio/psdinput.cpp
- src/tiff.imageio/tiffinput.cpp
- testsuite/psd/ref/out.txt
The main thing here is that it turns out that when trying to parse the ICC profiles from Photoshop PSD/PSB files, we weren't storing the attributes in the correct way. Everything else, we shoved in both the "common" and "composite" imagespecs, but we left ICC data out of the composite spec.
While I'm at it, I made two other ICC related changes:
* Among the several formats with ICC profiles, we were inconsistent about whether we report errors for corrupt ICC profiles and treat the whole image as broken, or just ignore the errors entirely. Fixed in various places to make a consistent policy of always checking the errors, and reporting/terminating if the "imageinput:strict" global attribute is true, allowing it to just ignore the broken ICC record if that attribute is false.
* Found a spot …
> ICC profile reading improvements, especially for PSD

- .gitattributes
Starter purpose is giving hints to GitHub's language analysis.
> admin: Set up .gitattributes file

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- src/build-scripts/gh-installdeps.bash
When test building the docs, lock down breathe and furo versions to exactly what we use on RTD.
Also, to speed up the workflow: run on native Ubuntu rather than on an ASWF container (eliminates needless container download), and make sure that we don't waste time installing dependencies that we don't need.
These changes speed up the docs workflow from around 3:40 to around 2:00.
> ci: for docs workflow, lock down versions and speed up

- .github/workflows/build-steps.yml
- .github/workflows/ci.yml
- src/build-scripts/gh-installdeps.bash
- src/build-scripts/run-clang-format.bash
- src/cmake/compiler.cmake
- testsuite/docs-examples-cpp/src/docs-examples-imagebuf.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imagebufalgo.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imagecache.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imageinput.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imageioapi.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imageoutput.cpp
- testsuite/docs-examples-cpp/src/docs-examples-texturesys.cpp
- testsuite/docs-examples-cpp/src/docs-examples-writingplugins.cpp
Old: Do a build with target 'clang-format', relying on our build system.  But that means that we need to do the cmake config step, and need a bunch of dependencies set up so that the config doesn't fail.
New: Make a new run-clang-format.bash utility to issue the commands for the right files. No "build" is requred, and the only dependencies we need are the minimum it takes to run clang-format itself.
These changes reduce the approximate total elapsed time of a CI clang-format job from nearly 7:00 to around 0:45.
Also, I noticed that we never had been clang-format testing the .cpp and .h files in the testsuite itself. So enable that now, and commit the small amount of reformatting that it identified.
> ci: Improved clang-format CI task

- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/string_view.h
Since C++17 defines std::size(C) (defaulting to returning C.size()), we don't need to define our own now that C++17 is our minimum.
It seemed harmless to define it anyway for quite a while...  but then a few days ago, the GitHub Windows CI runners upgraded their version of MSVS, and we started getting some very odd test failures that I was able to trace to std::size somehow returning the wrong size in some cases, and printf debugging revealed that the one we supplied wasn't even the one being called.
I can't say I understand exactly what was going wrong. I was debugging by repeatedly submitting small changes with debugging scaffolding to GH to see how it works in a CI run, since I have no access to a local Windows machine (at about 1/2 hour turnaround time for each iteration!).  Once I …
> fix: eliminate needless definitions of std::size

- src/png.imageio/pnginput.cpp
- src/png.imageio/pngoutput.cpp
The current width/height limit enforced by the `check_open` API is too low for PNG files. Each dimension can technically be up to `2^31 - 1` but using that value would defeat the purpose of the check here. Use `1 << 20` like what is used for TIFF and EXR instead.
The situation was triggered while trying to write an 85000x28400 px image, which is smaller than 65536*65536 but the dimensions are checked individually rather than as a total pixel count or similar.
Also looks like the PNG output was allowing too many channels so fix that too.
exposed the new functionality as oiiotool …
> fix(png): increase allowed width/height limit

- src/cmake/externalpackages.cmake
When USE_PYTHON is disabled, don't even bother looking for python.
> build: Better disabling of work when USE_PYTHON=0

- src/psd.imageio/psdinput.cpp
There were some psb files that were not opening with oiiotool, failing on the signature.
Some keys were missing for the additional layer information, leading to the pointer to misalign when reading the file, expecting the next 4 bytes rather than 8 bytes where needed for parsing.
No additional test suites added.
After deliberating, it is unclear if we should have a strict mode, or keep parsing the rest of the file after a failed signature, given that in this case the signature is not the part that's actually causing the issue. Might be useful as a future feature, if there is an use case for that?
corresponding Python bindings (and if altering ImageBufAlgo …
> Bug fix: Updated tags for psb

- src/include/OpenImageIO/span.h
From an array of known size, we can implicitly construct a span of dynamic length, or of fixed length equal to the array length.  Use template enable_if trick to restrict to these cases.
Previously, the constructor would have allowed a fixed-length span to be constructed from an array of differing length, which should obviously have been disallowed.
> api(span.h): Only allow span-from-array if array for compatible size

- INSTALL.md
- src/build-scripts/build_libpng.bash
- src/cmake/build_PNG.cmake
* The GitHub account has changed (the old one redirects, but still, let's update to the current canonical name).
* Update the version we use in CI and for "autobuild" to the latest tagged release instead of one that's years old.
> ci: Update libPNG address and version for ci & autobuild

- src/include/OpenImageIO/span.h
- src/libutil/span_test.cpp
Additions to `OIIO::span<>`:
* New flavors of `as_bytes()`, `as_writable_bytes()` that take a raw pointer + length, turning them into `cspan<byte>` and `span<byte>`, respectively.
* `span_cast<T>()`: "cast" a span of one type into a span of a different type covering the same memory. Use with caution!
Safety improvements to existing functionality:
* front(), back(): Add a debug assertion to validate that there is at least one element.
* first(), last(), subspan(): clamp offsets and counts so that the result can't possibly return a span referencing memory that wasn't inside the original bounds.
* The copy constructor that takes a non-matching span was much too flexible. Now it uses enable_if to ensure that it can't be used to change data types or lengths, it can only turn span of non-const …
> api(span.h): OIIO::span improvements

- src/tiff.imageio/tiffinput.cpp
The default value for m_bitspersample should be 1 when TIFFTAG_BITSPERSAMPLE is not present in the directory.
nonconforming.
> fix(tiff): the default value for bitspersample should be 1

- src/oiiotool/oiiotool.cpp
The following command fails for images with mip map levels due to a bug:
```
oiiotool mipmap_images.*.exr --siappendall -o all_images.exr
```
If the option `-a` is not appended to the command, mip levels higher than 0 should be ignored, instead it just segfault due to out of bound access; I just fixed the it in the PR cf. [my comment below](https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4671#discussion_r1999705885).
> fix: invalid loop bound when appending mipmap textures using oiiotool

- .github/workflows/build-steps.yml
- .github/workflows/ci.yml
* Give names to some CI steps that didn't have them -- makes it nicer to read the logs and CI status dashboard.
* Make sure no job nametag is a substring of another, or it might find the wrong cache, which is based on the job name.
> ci: step naming adustments

- src/doc/imagebuf.rst
- src/doc/oiiotool.rst
- src/doc/pythonbindings.rst
- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/oiiotool/oiiotool.cpp
- src/python/py_imagebuf.cpp
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-copy/run.py
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imagebuf/src/test_imagebuf.py
Clarify that IB::copy_metadata and oiiotool --pastemea fully replace all existing metadata with that of the other IB.
Add a new IB::merge_metadata() and oiiotool --mergemeta that merges in metadata from the other IB, preserving metadata in `this` that was not in the other IB.  Optionally, metadata that existed in both can be overridden.  Optionally, a subset of metadata to be merged can be selected via a regex.
> feat: ImageBuf::merge_metadata and oiiotool --mergemeta

- src/include/OpenImageIO/paramlist.h
- src/oiiotool/oiiotool.h
I still think that the "abi break" is a false positive. But I really didn't need the new constructor that seemed to confuse the abi checker, so just to be extra sure that there is no break that I simply misunderstand, change to make abicheck happy.
> fix: Partial reversion to fix ABI checker false positive

- .github/workflows/wheel.yml
The Intel Macs had this problem last week and #4668 fixed it. Now suddenly the ARM Macs had it this week. Seems to be something changing on the skbuild side.
> ci: Fix wheel building on Mac ARM (continuation of #4668)

- src/cmake/build_libdeflate.cmake
When using `OpenImageIO_BUILD_LOCAL_DEPS` environment variable to build all OIIO's dependency locally, OIIO's build script specifies a set of default versions of the dependent libraries. In particular, `ebiggers/libdeflate` is set to `1.20`.
This 1.20 version of libdeflate fails to build on platforms where AVX512 is not available and the make tool chain did not correctly tell the C compiler about it. 
```
-- Building package TIFF  locally
--         Building package libdeflate  locally
--                 Building local libdeflate 1.20 from https://github.com/ebiggers/libdeflate
/usr/tmp/ccCelbo5.s: Assembler messages:
/usr/tmp/ccCelbo5.s:649: Error: unsupported instruction `vpdpbusd'
/usr/tmp/ccCelbo5.s:650: Error: unsupported instruction `vpdpbusd'
```
This issue is fixed in libdeflate …
> Bump libdeflate to 1.23 in local building cmake to avoid AVX512 not available errors

- .github/workflows/ci.yml
- INSTALL.md
Bump to the latest in several cases. Also make sure the INSTALL.md is in line with what we support and/or test.
> ci: bump dependencies for "latest versions" CI test

- .github/workflows/wheel.yml
- CMakeLists.txt
- INSTALL.md
- src/build-scripts/build_Freetype.bash
- src/build-scripts/build_OpenJPEG.bash
- src/build-scripts/build_opencolorio.bash
- src/build-scripts/build_pybind11.bash
- src/cmake/build_Freetype.cmake
- src/cmake/build_OpenColorIO.cmake
- src/cmake/build_pybind11.cmake
The latest cmake in some package repos is 4.0. CMake 4.0 drops support for compatibility with cmake < 3.5, and thus errors when building our own dependencies that happen to have their own cmake scripts asking for compatibility with something older than that.
Setting CMAKE_POLICY_VERSION_MINIMUM=3.5 environment and/or cmake variable seems like a hack that could hide true incompatibilities, but will get us past this for now.
Change our own minimum to the range of 3.18.2...4.0 to correctly reflect the range of versions that we believe will work.
> build: cmake 4.0 compatibility

- src/include/OpenImageIO/span.h
- src/libOpenImageIO/exif-canon.cpp
- src/libOpenImageIO/exif.cpp
- src/libOpenImageIO/exif.h
We recently started getting some CI failures on the "bleeding edge" test that uses the new gcc 14, seems that the newest cut of that compiler was giving us new warnings where it suspected we were writing past the valid bounds of some memory areas, but it was very hard to decipher the circumstances and either find the bug or convince myself that is was a false positive.
To help me debug it, I switched some of the internals of exif.cpp that passed around raw pointers in very hard-to-validate ways to instead using spans with explicit lengths, in the hopes that the debug-mode bounds checking it provides would allow me to more easily track down the problem.
Now it no longer gets compiler warnings.
Did I fix a very subtle bug in the process?
Does the reformulation with spans make it easier for …
> int: Switch to spans for some exif manipulation, fixing warnings

- src/python/py_imageinput.cpp
- src/python/py_imageoutput.cpp
Seems that for quite some time, there have been particular circumstances in which the Python bindings have leaked ImageInput or ImageOutput objects.  That's bad enough on its own, but it also leaves file handles open if code was depending on the fact that the ImageInput and ImageOutput destructors close the files if they haven't already been closed.
I think the offending part is that the `unique_ptr<ImageInput>` extracts its raw pointer and gives it to Python, on the mistaken assumption that it would be reference counted as a python object.  But apparently, it's not. Oops.
Leaving it as a unique_ptr turns out to be fine, as far as pybind11 is concerned! And on top of that, if you give an uninitialized unique_ptr to pybind11, it considers that a Python `None`, which means we can further …
> fix(python): fix handle leak

- src/doc/builtinplugins.rst
These values are read & written as integers
and don't work unless they are accessed using int accessors.
m_dib_header.hres = m_spec.get_int_attribute("XResolution");
Correct documentation.
BMP uses integer access:
- `./src/bmp.imageio/bmpinput.cpp:`, `m_spec.attribute("XResolution", (int)m_dib_header.hres);`
- `./src/bmp.imageio/bmpoutput.cpp`, `m_dib_header.hres = m_spec.get_int_attribute("XResolution");`
> Docs: correct the type for BMP x/y density

- src/doc/builtinplugins.rst
From the PDF:
https://pub.smpte.org/doc/st268/20030505-pub/st0268-2003.pdf
3.31 X scanned size: Defines the horizontal size of the original scanned optical image in millimeters. [42.1]
3.32 Y scanned size: Defines the vertical size of the original scanned optical image in millimeters. [42.2]
----
This is a small PR that simply clarifies the units in the documentation.
> Docs: specify the units for DPX scanned size

- src/sgi.imageio/sgiinput.cpp
The SGI IRIS format is big-endian so incoming multi-byte fields need to be swapped. This wasn't being done in the `valid_file` call so the magic test would always fail on little-endian platforms.
nonconforming.
> fix(sgi): Fix valid_file to properly swap bytes on little-endian platforms

- src/dicom.imageio/dicominput.cpp
Some new changes in DCMTK 3.6.9 that triggers warnings.
> fix(build): Fix new dcmtk 3.6.9 vs C++ warning

- src/doc/oiiotool.rst
- src/oiiotool/oiiotool.cpp
- testsuite/oiiotool-text/ref/out.txt
- testsuite/oiiotool-text/run.py
`--render_text:measure=1` causes the render_text command to set user variables `TEXT_X`, `TEXT_Y`, `TEXT_WIDTH`, and `TEXT_HEIGHT` (as if set by `--set`) to the origin offset and dimensions of the rendered text size. These can then be accessed in subsequent expression evaluation.
`--render_text:render=0` causes the text to not actually be rendered into the image. (The default is 1.) This is primarily of use in conjunction with `measure=1` if you want to measure the size that text would have taken, then use the variables for subsequent commands, but not actually draw the text.
> feat(oiiotool): add --render_text modifiers measure= and render=

- src/doc/builtinplugins.rst
- src/raw.imageio/rawinput.cpp
The raw input plugin populates the attributes in the ImageSpec from the libraw structures in the RawInput::open_raw() method. That is done before the actual image data being decompressed on demand in RawInput::read_native_scanline(). Libraw re-calculates some values after the pixels get available, it is impossible to access those, as the ImageBuf's spec does not get updated, and the updated ImageSpec is not available from outside of RawInput when/after the pixels are being processed.
An example: the initial values for the white balancing weights get populated from the image file metadata, those get copied into the ImageSpec. If the libraw was configured to white balance by averaging the pixels of the whole image or a region, the white balancing weights would get re-calculated by libraw …
> feat(raw): add raw:ForceLoad hint

- INSTALL.md
- src/cmake/build_Robinmap.cmake
* Raise auto-build version of Robinmap to 1.4.
* Add the magic CMAKE_POLICY_VERSION_MINIMUM to our auto-build of Robinmap in case an older version is selected for auto-build. (Mimicking the fix we did for other packages.)
* Add Robin-map to the INSTALL.md list of dependencies, somehow it had been overlooked before.
> build: Address Robin-map vs CMake 4.0 compatibility

- INSTALL.md
INSTALL.md bolds *changed* minimums of dependencies since the last release. Now that 3.0 is released and main is working toward 3.1, remove those highlights from the last release so they won't get mixed up with future changes for 3.1.
> doc: INSTALL.md reset updated minimum dependencies from 3.0

- src/include/imageio_pvt.h
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
Inspired by a link from EmilDohne in an unrelated PR, this introduces `default_init_allocator`, an experimental custom allocator that default initializes, rather than value-0-initializes, POD/non-class types.
This is useful for being able to make a std::vector with this allocator (`default_init_vector`), thus having the property of not incurring a large cost of needlessly initializing the elements when they are allocated, as a default std::vector does.
I picked two spots sort of randomly, in which we previously avoided using std::vector and instead did a unique_ptr / new[] dance to do scoped heap allocation without paying the vector initialization tax. By using default_init_vector, we avoid the extra cost while still using the much more convenient vector type.
These two places are just to …
> int: Experimental default_init_allocator and default_init_vector

- src/include/OpenImageIO/typedesc.h
* Use constexpr inside BaseTypeToC templates.
* Add BaseTypeToC_v and TypeDescToC_v convenience aliases, much like is done in C++ standard type trait helpers.
> api(typedesc.h): tidying of type trait templates

- CMakeLists.txt
Somewhere along the road to 3.0, the build files changed in such a way that OIIO_SITE was not correctly passed down to C++ symbols, and some SPI-specific (sorry) color space handling was inadvertently disabled as a result. This restores things to the way it was in 2.5, and should not affect anybody else.
Also eliminate some old SPI-specific code that's no longer needed (and clearly hasn't been needed for a long time, because we had been naming the site "spi" but testing "SPI", and no problems were evident with skipping that ancient code).
> build: Fix broken OIIO_SITE customization

- src/include/OpenImageIO/platform.h
- src/include/OpenImageIO/simd.h
- src/libOpenImageIO/imageio.cpp
* We passed a bad flag to _mm512_cvtps_ph intrinsics because of what I can only imagine was a bad cut-and-paste years ago. (Harmless because it set bits never used, but a warning on Windows.)
* Remove clauses for AVX512-EL, I'm not sure why they were there, because those instructions were only for "Knights Landing" which was never made available to the general public and has been discontinued. It must be that years ago, I got a little overzealous with the SIMD intrinsics.
> simd.h: address compiler warnings

- src/doc/imageioapi.rst
- src/include/OpenImageIO/fmath.h
- src/include/OpenImageIO/image_span.h
- src/include/OpenImageIO/image_view.h
- src/include/OpenImageIO/imageio.h
- src/include/imageio_pvt.h
- src/libOpenImageIO/CMakeLists.txt
- src/libOpenImageIO/image_span_test.cpp
- src/libOpenImageIO/imageio.cpp
- src/libutil/fmath_test.cpp
- src/libutil/span_test.cpp
* `image_span<T,Rank>` is a 2D-to-4D bounded span with byte-measured strides (describing data layout with dimensions for channel, x, y, z) for us to have future APIs deal with bounded+strided regions rather than YOLOing raw pointers.  Among other advantages, image_span will have robust bounds checking in debug builds. It also simplifies interfaces to pass a single image_span that encapsulates everything about an up-to-4D data layout, rather than needing to pass a long list of individual pointers, sizes, and strides.
* I've templated image_span on Rank, but default to Rank=4 and am using that version only in practice. The templating by rank allows future expansion to describe one scanline (rank 2) or 2D image plane (Rank 3) if we want to do so for certain API calls, but I'm not sure yet …
> api: add image_span, deprecate image_view

- src/include/OpenImageIO/simd.h
This useless symbol was removed in PR #4724, but maybe downstream things used it and will break simply because it was removed, even though it never would have been nonzero. It should not have been completely removed except at a compatibility-breaking version boundary.
> build: Restore OIIO_AVX512ER_ENABLED preprocessor symbol

- src/include/OpenImageIO/fmath.h
- src/libutil/fmath_test.cpp
This also fixes a sonar warning about being unsure of a raw pointer was used out of range.
> fmath.h: add span-based bit_unpack() utility

- src/libOpenImageIO/exif.cpp
I think what we were doing here was fine all along, but the idiom was confusing to static analyzers who identified a danger that we were memcpy'ing into a field that was potentially not big enough. A minor restructuring of the code and a new assertion should verify that it's safe and also make it clear to the static analyzer that we aren't falling into the case it warned about.
> int: Address safety warnings in pvt::append_tiff_dir_entry

- .github/workflows/build-steps.yml
- .github/workflows/ci.yml
- .github/workflows/release-sign.yml
- .github/workflows/scorecard.yml
- .github/workflows/wheel.yml
Seems to shave about 5s off of each and every CI run variant. Every little bit helps.
Also update the versions of some actions we're using to the latest.
> ci: save time by not checking out entire project history

- INSTALL.md
- src/build-scripts/install_homebrew_deps.bash
- src/cmake/build_libuhdr.cmake
- src/cmake/externalpackages.cmake
- src/cmake/modules/Findlibuhdr.cmake
- src/doc/oiiointro.rst
- src/jpeg.imageio/CMakeLists.txt
- testsuite/jpeg-ultrahdr/ref/out-macarm.txt
I discovered, by testing against the latest libultrahdr, that only starting in 1.3 does it support the "64 bit 'half' RGBA" variety of UHDR that is the flavor used by the testsuite example. But our "auto-build" is pegged to 1.2, which means that all along, we were not decoding that test file properly as UHDR and our test reference output was therefore wrong. We also didn't detect libuhdr's version at all, let alone exclude versions that were too old.
Remediations:
* Amend Findlibuhdr.cmake to detect the version from symbols in its header files.
* Have our search for libuhdr enforce a minimum version of 1.3. (I feel bad about "changing minimum dependencies" in a release branch, which we usually disallow, but I think this time is an exception since we know versions < 1.3 are broken.)
* …
> build: Detect libultrahdr version and enforce minimum of 1.3

- src/include/OpenImageIO/detail/fmt.h
- src/libutil/strutil.cpp
Certain version combinations of fmt and gcc were warning, and it all boiled down to the knots we tied ourselves into to replace the function fmt uses instead of throwing exceptions, when they are disabled. I can't seem to find any harm in letting it do its default thing, so simplify our side to silence the warnings.
> build: fix fmt throwing behavior warnings

- src/doc/requirements.txt
PR #4736 bumped the version of sphinx we use on readthedocs, and that was incompatible with the old version of furo we specified.
I'm not sure how the problem was not caught by our "docs" workflow.
> docs: Fix furo requirement after recently breaking docs

- src/doc/oiiotool.rst
- src/oiiotool/imagerec.cpp
- src/oiiotool/oiiotool.cpp
A constellation of closely related fixes and additions related to oiiotool `-i` behavior:
* When using `-i:now=1` to force for immediate read rather than using an ImageCache, it would "forget" any prior setting of `--native`. This is fixed now to correctly combine desire for bypassing the cache with hinting to maintain native data type.
* When restricting channel subset with `-i:ch=...`, use of the `--native` flag was incorrect in some cases -- it would use the overall best single data format of all channels, rather than restricting that to the selected channel range. So, for example, if you said `-i:ch=R,G,B,A` and those channels were all `half`, but channel 17 (not selected) was `float`, you would get a conversion to float rather than keeping the selected channels at their native half. …
> oiiotool: -i:native=1, fix --native behavior, fix convert datatype

- CMakeLists.txt
- src/include/OpenImageIO/image_span.h
- src/include/OpenImageIO/imageio.h
- src/include/OpenImageIO/span.h
- src/include/OpenImageIO/typedesc.h
- src/include/imageio_pvt.h
- src/libOpenImageIO/image_span_test.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imageoutput.cpp
- src/libutil/typedesc_test.cpp
- testsuite/docs-examples-cpp/src/docs-examples-imageoutput.cpp
* ImageOutput methods that write scanlines, tiles, and images, which are the main customization points for format output implementations, are given additional methods that take `image_span` in place of raw pointers and strides.
* Generally, for each, there is a templated version that takes `image_span<T>` that communicates both the memory area and the data type conversion requested, a "base case" that takes an explicit TypeDesc for the conversion type and a `image_view<std::byte>` giving the raw memory layout, and a `span<T>` convenience version for when there are contiguous strides. Note that when reading mixed channel data types in "native" mode (no type conversion, just leave the data in its original types), you have to use the std::byte image_span version, since the idea is not to do …
> api!: add image_span versions of ImageOutput methods

- src/include/OpenImageIO/simd.h
- src/libOpenImageIO/imagebufalgo_pixelmath.cpp
- src/libtexture/texturesys.cpp
- src/libutil/simd_test.cpp
While I was investigating some SonarQube warnings about our simd `shuffle<>` templates (which are a false positive and I have a separate PR to simply silence it), I did get to thinking about the naming, and want to make a couple changes:
* I decided that the 1-template-argument version of this function, `shuffle<int i>(simd_type)` would actually be more clear and self-documenting if renamed `broadcast_element` to emphasize that it is taking just one simd lane/element and broadcasting it to all lanes. (The multi-argument shuffle really is doing a true shuffle, giving an index for each lane to make a permutation of swizzle, so I'm not renaming that one.) To avoid breaking source compatibility, I am leaving the old name as well as a synonym, but commenting it as deprecated and I will phase …
> simd.h: renaming and fixing of shuffle template

- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
Oops, this internal vector called `reserve()` and then filled in results. Should have been `resize()`.
> fix(exr): did not properly allocate 'missingcolor' vector

- .github/workflows/wheel.yml
- INSTALL.md
- src/python/stubs/generate_stubs.py
Provides a path for users who can't build the stubs locally
if the stub check fails, it should generate new stubs and save it as an artifact, so that from the GH page showing the test failure, the user who submitted the PR can download the file, inspect it, and add it to their PR even if they didn't have the capacity to generate it on their end. (This is basically mimicking our "clang-format" test, which when it fails, allows people to download the diffs to apply on their end even if it's not possible for them to actually run "clang-format" with the right version on their own machine.)
corresponding Python bindings (and if altering ImageBufAlgo functions, …
> Upload python stubs as an artifact in CI

- src/iv/ivmain.cpp
I've found a couple issues with iv when launched with a directory name as input, while iterating through the files in the directory:
1. Crash on .DS_Store file
2. The files with extension in capital letters are not recognised as valid images, due to case-sensitive compare. Capitalised extensions are common in raw camera images.
No tests, the changes are trivial, and in UI-specific code, not easy to test.
test that runs clang-format and fix anything that …
> fix(iv) fix crash on .DS_Store; fix uppercase extensions

- .github/workflows/ci.yml
- testsuite/python-imageinput/ref/out-python3-win-2.txt
Apparently, the runners used to check things out on drive D:, but today
they are doing so on C:, and that changes some filenames in the reference
output.
Also, fix missing nametag needed for Windows artifacts.
> ci: update ref output to compensate for GitHub windows drive changes

- .gitignore
- src/iv/imageviewer.cpp
- src/iv/imageviewer.h
- src/iv/ivgl.cpp
- src/iv/ivgl.h
- src/libtexture/imagecache_pvt.h
Fixes #4718
See the demo of problems that were fixed and of fixes in action over here: https://www.loom.com/share/3bdee20b32434e0bbba47d393928d4f7
There are fixed for three problems:
1) Window is not resizing when new image is loaded in (it still does when image being loaded is the only one)
2) When you using scroll mouse wheel it is taking into account where the cursor is (there is some corner case when it doesn't do it perfectly, that I can't catch when it doesn't follow it exactly, but a bit of panning fixes it)
~~3) Switching between images recenters (if image is smaller) or making some other panning nessery to have image in the viewport. I believe it is doing same stuff what happens when window is resized.~~ This has been reverted.
need to update the documentation, for example if …
> Fix #4718 do not resize on open and other zoom fixes

- src/iv/ivgl.cpp
Improve sharpness of text in pixel view tool for HiDPI screen
Before:
After:
nonconforming.
> Use screen pixel ratio to render sharp text in pixel view tool

- src/libOpenImageIO/imageinput.cpp
- src/libOpenImageIO/imageoutput.cpp
II and IO were documented as initializing their internal "how many threads to use when reading/writing this particular file" to the global "threads" OIIO attribute. But they did not, they always initialized to 0 ("all the threads") even if the global attribute had been set differently prior to creation of the reader or writer.
> fix: ImageInput/ImageOutput did not set per-file threads correctly

- src/doc/builtinplugins.rst
- src/webp.imageio/webpinput.cpp
- src/webp.imageio/webpoutput.cpp
Similar to other formats like PNG, make WEBP respect the `oiio:UnassociatedAlpha` attribute value in case client applications are already handling the alpha association themselves.
Unsure how best to test this?
nonconforming.
> feat(webp): Respect the `oiio:UnassociatedAlpha` attribute

- src/iv/ivmain.cpp
Master version of the iv today when opening on mac sometimes opens without a focus, which causes top menu bar not to be populated (just `iv` on the left). Workaround is to switch back and forth once to and from another app for menu bar too get populated.
It is unclear to me how reliably replicate the bug so that I have a solid prove, that this fix works. But since building with this line it never happend to me yet.
Maybe more knowledgable in Qt can verify if it makes sense.
already run clang-format before submitting, I definitely …
> fix(iv): Bug fix for iv window loosing focus on mac on startup

- src/python/py_imagebufalgo.cpp
Only symptomatic on debug builds, but I was seeing exceptions from pybind11 about bad GIL release. I traced it to the recent implementations of demosaic. Apparently it's not safe to release the GIL until AFTER the call to py_to_stdvector. Which makes sense when you think about it -- we need the lock whenever we are interacting directly with Python calls or data structures (such as what py_to_stdvector is doing), but we release it when we're done with the python and only calling OIIO internals (such as IBA::demosaic() itself).
> fix(python): IBA.demosaic had GIL release in wrong spot

- src/doc/builtinplugins.rst
- src/webp.imageio/webpoutput.cpp
WEBP uses the `WebPConfig::factor` setting to also control how hard it tries to compress when lossless compression is used. It also uses another `WebPConfig::method` setting to further tune both lossless and lossy schemes. [1]
Expose both of these settings so client applications using OIIO can adjust these values as they see fit.
This PR makes 4 changes:
- Adds support for using a `lossless:factor` value for the `compression` attribute. The 'factor' value controls the effort that WEBP uses during the compression process.
- Adds support for using a `webp:method` int attribute. The value of this attribute controls the `WebPConfig::method` setting. Note: this is different than the compression settings but will also affect speed and quality in various ways.
- Sets `WebPPicture::use_argb` to …
> feat(webp): Allow finer grained control over WEBP compression settings

- src/doc/oiiotool.rst
- src/include/OpenImageIO/filesystem.h
- src/libutil/filesystem.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/oiiotool.h
- testsuite/oiiotool/ref/out.txt
- testsuite/oiiotool/run.py
Fixes #4598.
It was noted in the issue that running `oiiotool` with output filename inside a folder that doesn't exist will cause OIIO to consume time and resources, but fail eventually due to the folder not existing.
Take for example the command:
```
oiiotool --create-dir -i input.png -o ./output_folder/output.png -o ./output_folder_2/output.png
```
During the output action, it creates the directories if needed (`output_folder` and `output_folder_2`), and outputs the images into the folder.
Added unit tests. Tested it locally, and it creates both the above folders and outputs the image.
corresponding Python bindings (and if altering ImageBufAlgo …
> feat(oiiotool): Added create-dir cmd arg to create dir if it doesn't exist

- .github/workflows/ci.yml
- testsuite/docs-examples-cpp/ref/out-linuxarm.txt
- testsuite/docs-examples-python/ref/out-linuxarm.txt
- testsuite/psd/ref/out-linuxarm.txt
- testsuite/psd/run.py
- testsuite/texture-interp-closest/run.py
- testsuite/tiff-depths/ref/out-linuxarm.txt
GHA offers free runners for Linux on ARM based machines. Let's throw them into the testing mix!
A very small number of tests needed additional reference outputs saved, due to a few LSB type errors in the math.
> ci: Add Linux ARM test

- src/doc/builtinplugins.rst
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- src/openexr.imageio/exroutput.cpp
After adding the new `htj2k` compression codec to OpenEXR,  here we enable it in the OIIO stack so it will be recognized by the library and binary tools, such as using `oiiotool` to directly change compression type into htj2k.
EXR side is planning to do a round of renaming of enum names (https://github.com/AcademySoftwareFoundation/openexr/pull/2048), and therefore this MR is marked as Draft for visibility for now. The enum names should be changed to `htj2k` name after 2048 on the EXR side goes into the mainline.
I'm also trying to study if more changes on the OIIO side is required to enabled the new `htj2k` codec throughout the OIIO tool chain... suggestions welcome.
Draft MR, more test will be followed up.
Does this need a new test?
need to update the documentation, for example if this …
> Add `htj2k` as a compression option for the OpenEXR plugin in OIIO

- src/include/OpenImageIO/image_span.h
- src/libOpenImageIO/image_span_test.cpp
- src/libOpenImageIO/imageio.cpp
A utility to confirm that an image_span (possibly with non-contiguous strides) entirely fits within another contiguous span.
> api: image_span_within_span

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageoutput.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exroutput.cpp
- testsuite/openexr-suite/ref/out.txt
- testsuite/openexr-suite/run.py
We documented this function as checking the valid range of pixel coordinates, but we CALLED it everywhere as if we were only checking the resolution.
But we IMPLEMENTED as if we were checking the range, generating errors for outputting exr files with negative pixel window origins. But why was nobody seeing those errors when writing exr files with negative origins?  Because the openexr writer BOTCHED it by not noticing the return value and considering it a failure.
Oh boy. All my fault.
So the fix:
* Change the comment documenting check_open() to match the way we had been using it at the call sites.
* Change the implementation of check_open() to match this by no longer checking whether all four corners were in the range -- only check if each dimension's size is within the limit for that …
> fix: ImageOutput::check_open logic was flawed

- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
As a reminder, the global OIIO attribute "missingcolor", or the file-specific ImageInput open hint "oiio:missingcolor" is designed to treat missing scanlines or tiles as not a true error, but instead just pass over them and substitute the missingcolor value for those missing areas on the file.
The nature of this PR is that while we had implemented this behavior fully for tile-based exr files, we never did so for scanline-based files. So here we do.
Now then, unfortunately, it does not work. I think it's a bug in the OpenEXR library itself, but we're still trying to figure that out. But nonetheless, I believe this change is correct.
> fix(exr): not honoring 'missingcolor' for scanline files

- src/libtexture/imagecache.cpp
Oops, my bad. Looks like #4664 (merged about a week ago) and #4783 (merged today, but authored before #4664 was merged) interacted in a way that produced a build break. This tiny fix is essential to unbreak it.
> fix: build break from untested combo of two PRs

- src/iv/ivgl.cpp
Small PR to improve redability of shader code parts.
> Use R"()" syntax for glsl shader strings for better readability

- .github/workflows/ci.yml
Just on the "bleeding edge" CI job, we were refraining from doing the apt-get update. It was breaking something last year.  Now NOT doing it is breaking something in this CI test, just since this week (presumably some default package on the GH runners changed, I haven't been able to isolate any other reason). But bringing all the apt packages up to date makes it go away.
> ci: fix broken bleeding edge CI

- src/doc/oiiotool.rst
- src/oiiotool/expressions.cpp
- testsuite/oiiotool-control/ref/out.txt
- testsuite/oiiotool-control/run.py
When doing oiiotool command line expression substitution, asking for this metadata evaluates to the number of subimages in the referenced image.
The purpose is that asking to retrieve, say, `{TOP.'oiio:subimages'}` might look right, but generally it's only added to images (or format readers) that are potentially multi-image. Whereas SUBIMAGES is not actual image metadata, it's just an evaluation token that will always be the number of subimages.
> feat(oiiotool): New expression pseudo-metadata term: SUBIMAGES

- src/include/OpenImageIO/simd.h
On Windows ARM64, when building with `clang-cl`, LLVM can sometimes use it's own built-in `intrin.h` file, located in `<LLVM INSTALL PATH>\lib\clang\20\include`.
This file, as opposed to the built-in one that ships with the Windows SDK that MSVC uses, doesn't have an inclusion of `arm_neon.h`. This PR adds a small check to the `simd.h` file to include this header.
I didn't add an extra check to specifically only do this for clang, as it seemed a little messy - I can do this, but it's relatively harmless for MSVC given `intrin.h` includes it anyway for that compiler.
This change has already been in place for some time in Blender, this is just an upstreaming PR for that change: https://projects.blender.org/blender/blender/src/commit/ea604b6b80e49adb51d12df4e4edd5af1c51f446/build_files/build_ …
> fix: Add arm_neon.h include on Windows ARM64 with clang-cl

- src/dds.imageio/ddsinput.cpp
- src/include/OpenImageIO/imageio.h
- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exrinput_c.cpp
- src/ptex.imageio/ptexinput.cpp
- src/tiff.imageio/tiffinput.cpp
ImageOutput::supports() recognized queries for "multiimage" and "mipmap".  But ImageInput::supports() only recognized "multiimage". Add "mipmap" to make it easier for client software to know if the image file format they're reading from allows the possibility of MIP-mapping.
As far as I can tell, only OpenEXR, TIFF, Ptex, and DDS do, among the file types we currently support.
> api: Add new ImageInput::supports() query: "mipmap"

- src/cmake/modules/FindJXL.cmake
- src/jpegxl.imageio/CMakeLists.txt
I'm unsure how this could have worked correctly. There were three different variables used before, now there is only one.
nonconforming.
> build(jxl): Use correct cmake variables for the include directories

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imagebuf.cpp
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- src/tiff.imageio/tiffinput.cpp
- testsuite/jpeg2000/ref/out.txt
- testsuite/png-damaged/ref/out.txt
- testsuite/python-imagebuf/ref/out-alt-python3.txt
- testsuite/python-imagebuf/ref/out-alt.txt
- testsuite/python-imagebuf/ref/out-python3.txt
- testsuite/python-imagebuf/ref/out.txt
- testsuite/python-imagebuf/src/test_imagebuf.py
An important clarification: ImageInput::seek_subimage() returns false
but does not set an error message if the only thing wrong is
requesting a non-existent subimage or miplevel, and similarly,
ImageInput::spec() and spec_dimensions() set an empty spec (easy to
tell by spec.format == TypeUnknown) in that case. All three of these
only set an error message if the reason it couldn't perform the task
because there was actually something wrong with the file or the
I/O. (Put another way, it's common to use these to simply probe which
subimages or mip levels exist, and returning false for "no it doesn't"
isn't really an error, it's expected behavior.)
OK, then.
We weren't always following these rules, sometimes setting
error messages when we shouldn't.
Other times (in different routines) when we …
> fix(ImageBuf): Better errors for nonexistant subimages/mips

- src/build-scripts/gh-win-installdeps.bash
Among other simplifications, remove all vcpkg builds from windows CI, don't need them.  Just rely on our auto-build. Shortens the build time on Windows!
> ci: Simplify gh-win-installdeps, no more vcpkg

- src/cmake/build_pystring.cmake
We have been having intermittent CI failures when the auto-build of OpenColorIO triggers the auto-build of Pystring, and then sometimes immediately seems to think the version it installed is not correct.
I'm jiggling some things here to see if I can get it to stop occasionally failing. I've run the testsuite on this patch several times without seeing any failures that in recent days had been happening typically in 1-2 jobs per CI run. So maybe this fixes it? I'd be lying if I claimed to have a coherent and full explanation for exactly why these changes help.
> build: Adjust pystring finding

- src/doc/imagebuf.rst
- src/include/OpenImageIO/image_span.h
- src/include/OpenImageIO/imagebuf.h
- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/imageoutput.cpp
We've already done ImageInput, ImageOutput, ImageCache, TextureSystem.
This applies the analogous set of changes to the public APIs of ImageBuf -- adding span and image_span versions of all the API calls that previously required raw pointers and strides. Many of the internals are still using the old versions, but at least this takes care of the interface.
> api: image_span-ify ImageBuf

- src/heif.imageio/heifinput.cpp
- src/heif.imageio/heifoutput.cpp
seeing build failures when building against libheif 1.19+
```
/private/tmp/openimageio-20250701-18561-96sl0/OpenImageIO-3.0.8.0/src/heif.imageio/heifinput.cpp:390:37: error: no matching member function for call to 'get_plane'
390 |     const uint8_t* hdata = m_himage.get_plane(heif_channel_interleaved,
|                            ~~~~~~~~~^~~~~~~~~
/opt/homebrew/include/libheif/heif_cxx.h:909:32: note: candidate function not viable: no known conversion from 'int *' to 'size_t *' (aka 'unsigned long *') for 2nd argument
909 |   inline const uint8_t* Image::get_plane(enum heif_channel channel, size_t* out_stride) const noexcept
|                                ^                                    ~~~~~~~~~~~~~~~~~~
/opt/homebrew/include/libheif/heif_cxx.h:914:26: note: candidate function …
```
> Fix HEIF stride type mismatch in input/output classes

- src/include/OpenImageIO/imageio.h
- src/libOpenImageIO/imageio.cpp
It was implemented as int, documented as float.  Change the docs to match what was always indended (int), and also switch the implementation so that either int or float will be transparently accepted.
> fix: correct docs and type of "resident_memory_used_MB" attribute

- src/libOpenImageIO/imagebuf.cpp
- src/libOpenImageIO/maketexture.cpp
As reported on Slack
(https://academysoftwarefdn.slack.com/archives/C05782U3806/p1751642730171029), between OIIO 2.5 and 3.0, we had a big slowdown when doing a multithreaded `maketx --envlatl`, which was traced almost entirely to the new mutex lock in ImageBuf::IteratorBase::init_ib(), which were all happening inside the call stack of `resize_block_<float>()`.
The reason was that it was calling ImageBuf::interppixel_NDC for every pixel, which in turn works by creating (internally) an ImageBuf::ConstIterator to sample the 4 nearby pixels. But every one of those ConstIterator constructors called init_ib, which briefly grabbed the mutex for the IB, which in addition to being wasteful on its own, caused the threads to block on each other.
The solution is straightforward: there is no need to …
> perf: Speed up maketx --envlatl when multithreaded by over 10x.

- pyproject.toml
pybind11 3.0 seems to break this process, so lock down to no later than the last version before it broke.
> build: For python stub generation, lock pybind11

- src/libutil/sysutil.cpp
Switch to posix_spawnp for macOS background launch to enable PATH lookup, this is a fix for:
https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4640
Description:
Previously, the code used posix_spawn with argv[0] as the executable name. This failed when argv[0] was not an absolute or relative path (e.g., just "iv"), because posix_spawn does not perform PATH lookups.
Switched to posix_spawnp, which behaves like execvp and searches PATH when argv[0] does not contain a '/' character. This allows the program to re-spawn in the background using the original command name, without requiring _NSGetExecutablePath() to resolve the full path.
> Switch to posix_spawnp for macOS background launch to enable PATH lookup

- .github/workflows/ci.yml
- INSTALL.md
Also found one stray test that was using a pybind11 version older than we claim to use, so bump that up to the advertised minimum.
> ci: Bump 'latest releases' tests to use pybind11 3.0.0

- src/jpeg2000.imageio/jpeg2000input.cpp
Add missing C++ header file
On the F41 and F42 compilation using LLVM based Clang++ failed.
[ 23%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/jpeg2000.imageio/jpeg2000input.cpp.o /usr/src/github.com/1div0/OpenImageIO/src/jpeg2000.imageio/jpeg2000input.cpp:462:9: error: use of undeclared identifier 'va_start'
462 |         va_start(args, fmt);
|         ^
/usr/src/github.com/1div0/OpenImageIO/src/jpeg2000.imageio/jpeg2000input.cpp:464:9: error: use of undeclared identifier 'va_end'
464 |         va_end(args);
|         ^
2 errors generated.
exposed the new …
> fix(build): update jpeg2000input.cpp to include cstdarg

- src/ffmpeg.imageio/ffmpeginput.cpp
avcodec_close (AVCodecContext *avctx) removing in ffmpeg 7.2 and was deprecated for couple years
Global avcodec_close (AVCodecContext *avctx)
Do not use this function. Use avcodec_free_context() to destroy a codec context (either open or closed). Opening and closing a codec context multiple times is not supported anymore – use multiple codec contexts instead.
In ffmpeg master, it has already been removed. But still work in v7.1
- [x ] I have read the [contribution guidelines](https://github.com/AcademySoftwareFoundation/OpenImageIO/blob/main/CONTRIBUTING.md).
exposed the new …
> ffmpeg: Replace deprecated and soon removed avcodec_close with avcodec_free_context in ffmpeg plugin.

- src/libOpenImageIO/imageioplugin.cpp
Inside ImageInput::create(), there's a section where the created ImageInput tries to do a quick call to its valid_file() method to do an inexpensive check that the file appears to be the right file format corresponding to the ImageInput subclass. However, it always called the variety of valid_file() that takes a string filename, ignoring the fact that create() itself may have been passed an IOProxy, which should always take precedence over trying to open a real file.
> fix(ImageInput): incorrect IOProxy logic related to valid_file

- src/openexr.imageio/exr_pvt.h
- src/openexr.imageio/exrinput.cpp
- src/openexr.imageio/exrinput_c.cpp
- testsuite/dup-channels/ref/out.txt
- testsuite/iinfo/ref/out-fmt6.txt
- testsuite/iinfo/ref/out.txt
- testsuite/maketx/ref/out-macarm.txt
- testsuite/maketx/ref/out.txt
- testsuite/oiiotool-attribs/ref/out-jpeg9d.txt
- testsuite/oiiotool-attribs/ref/out.txt
- testsuite/oiiotool-copy/ref/out.txt
- testsuite/oiiotool-fixnan/ref/out.txt
- testsuite/oiiotool-maketx/ref/out-macarm.txt
- testsuite/oiiotool-maketx/ref/out-rhel7.txt
- testsuite/oiiotool-maketx/ref/out-win.txt
- testsuite/oiiotool-maketx/ref/out.txt
- testsuite/oiiotool-subimage/ref/out.txt
- testsuite/oiiotool/ref/out.txt
- testsuite/openexr-chroma/ref/out.txt
- testsuite/openexr-decreasingy/ref/out.txt
- testsuite/openexr-luminance-chroma/ref/out-macarm.txt
- testsuite/openexr-luminance-chroma/ref/out.txt
- testsuite/openexr-multires/ref/out.txt
- testsuite/openexr-suite/ref/out.txt
- testsuite/openexr-v2/ref/out.txt
- testsuite/openexr-window/ref/out.txt
- testsuite/rational/ref/out.txt
New logic for reading OpenEXR files:
1. If the new colorInteropID is present, that's the color space.
2. Use the OCIO file naming rules, if that indicates a color space.
3. Otherwise, leave it blank, don't mae any assumptions.
It was a mistake for 3.0 to assume that completely unlabeled openexr files are lin_rec709.
> exr: Don't assume unlabeled OpenEXR files are lin_rec709

- testsuite/maketx/ref/out-alt.txt
PRs #4840 and #4841 crossed in flight with their tests passing individually, but they needed one small adjustment to reference output in order to to account for their interaction in main.
> test: Update ref output

- .github/workflows/ci.yml
ABI changed slightly after #4827. (Allowed in main but requires an update of the reference.)
Also, bump to using the 2025 container for the ABI check.
> ci: Update ABI check standard

- .github/workflows/ci.yml
- INSTALL.md
- src/iconvert/iconvert.cpp
- src/idiff/idiff.cpp
- src/iinfo/iinfo.cpp
- src/include/OpenImageIO/platform.h
- src/libOpenImageIO/exif.cpp
- src/libOpenImageIO/formatspec.cpp
- src/libOpenImageIO/imagebufalgo_test.cpp
- src/libOpenImageIO/imageio.cpp
- src/libOpenImageIO/imagespeed_test.cpp
- src/libOpenImageIO/maketexture.cpp
- src/libOpenImageIO/printinfo.cpp
- src/libtexture/imagecache.cpp
- src/libtexture/imagecache_memory_print.h
- src/libtexture/texturesys.cpp
- src/libutil/CMakeLists.txt
- src/libutil/benchmark.cpp
- src/oiiotool/diff.cpp
- src/oiiotool/expressions.cpp
- src/oiiotool/oiiotool.cpp
- src/oiiotool/printinfo.cpp
- src/rla.imageio/rlainput.cpp
- src/term.imageio/termoutput.cpp
* CI build as C++23 for bleeding edge test
* Fixes to disambiguate OIIO::print from std::print.  Apparently, at least for gcc14, std::print ends up in the global namespace and really messes with things.
* Change to the library that contains the implementation of C++23 stacktrace in gcc14 vs 12/13.
> build: C++23 support

- .github/workflows/ci.yml
- src/build-scripts/build_pybind11.bash
- src/cmake/build_pybind11.cmake
And a bunch of other minor updates:
* Change from 'testing' to regular containers
* Add forgotten 'export'
* Update default self-build pybind11 to 3.0.0
> ci: Add a VFX Platform 2026 CI job

- src/include/OpenImageIO/strutil.h
- src/include/OpenImageIO/typedesc.h
- src/libOpenImageIO/imagebufalgo_compare.cpp
- src/libOpenImageIO/maketexture.cpp
- src/libOpenImageIO/printinfo.cpp
- src/libtexture/environment.cpp
- src/libutil/fmath_test.cpp
- src/libutil/strutil.cpp
- src/oiiotool/printinfo.cpp
- src/testtex/testtex.cpp
These patch fix the build on NetBSD 11.99.1. There were a couple problems:
- some missing `str*i*()` functions
- `isnan` etc. not being used from the proper `std::` namespace
- a missing header for `va_list`
- NetBSD also handles `long long` differently from `int64`
- 
nonconforming.
> build: fix build on NetBSD

- .github/workflows/analysis.yml
Something must have changed with the containers, it was failing on the build step, before ever getting to the actual sonar analysis.
Switch to the same container and OCIO version that we use for the regular 2024 era container CI.
> ci: fix analysis workflow configuration

- .github/workflows/ci.yml
- src/build-scripts/build_libpng.bash
- src/build-scripts/gh-installdeps.bash
- src/cmake/build_PNG.cmake
- src/doc/builtinplugins.rst
* The "oldest" didn't really test against the oldest we claim to support.
* The "latest versions" didn't really test against the latest versions.
* The "bleeding edge" didn't really test against libpng master.
* The auto-build was unnecessarily a few releases behind.
* Documentation touch-ups
> ci: better spread of libpng versions we test against

- src/ffmpeg.imageio/ffmpeginput.cpp
- testsuite/ffmpeg/ref/out-ffmpeg6.1.txt
- testsuite/ffmpeg/ref/out-ffmpeg8.0.txt
Many codecs don't provide `bits_per_raw_sample`. The bit depth of the luma channel is the closest equivalent to a single bit depth then, while the chroma channels may be subsampled.
Tested on basically all the video files on my computer, they all give a non-zero bit depth that looks correct now.
nonconforming.
> fix: FFmpeg sets zero oiio:BitsPerSample

- testsuite/heif/ref/out-libheif1.12-orient.txt
- testsuite/heif/ref/out-libheif1.4.txt
- testsuite/heif/ref/out-libheif1.5.txt
- testsuite/heif/ref/out-libheif1.9-alt2.txt
- testsuite/heif/ref/out-libheif1.9-with-av1-alt2.txt
- testsuite/heif/ref/out-libheif1.9-with-av1.txt
- testsuite/heif/ref/out-libheif1.9.txt
- testsuite/heif/run.py
PR #4880 checked in some output reference that contained version numbers, which passed in main but failed when backported to 3.1. This repairs it and makes the output suitable for any version that contains the patch.
> ci: Fix testsuite/heif ref output

- src/raw.imageio/rawinput.cpp
This adds thumbnail support to the raw input plugin. 
Fixes #4107
This supports 3 of the 4 formats of thumbnails Libraw provides: BMP, JPEG, JPEGXL(untested). H265 is not supported, I don't know of any camera using it, and expect the code being significantly different from the other formats, given that the H265 is a movie container.
One thing I don't like about this implementation - I understand there is no way to query the number of thumbnails available in the file? We are expected to iterate, until `get_thumbnail()` returns false? If `get_thumbnail()` returns false not because there is no thumbnail for the requested index, but any other reason, we are not going to try reading past that index.
I have tested manually with a bunch of raw images having either JPEG or BMP thumbnails. 
I have …
> feat(raw): add thumbnail support to the raw input plugin

- src/gif.imageio/gifoutput.cpp
The version of open that takes an array of subimage specs didn't use them properly for finding the FramesPerSecond hint (or the ioproxy!).
Fixes #3716
> fix: gif output didn't handle FramesPerSecond attribute correctly

- src/cmake/testing.cmake
- src/jpeg2000.imageio/CMakeLists.txt
PR #4875, switched to using openjph's exported cmake config instead of
our own FindOpenJPH.cmake, and in the process also renamed OpenJPH ->
openjph to follow their convention.
But I botched it, still using the old OPENJPH_LIBRARIES (etc.)
variables instead of fully switching to the correct targets exported
from their config.
This PR minimally fixes that error, re-enabling use of openjph.
Fixes #4893
> build: fix openjph target use

- .github/workflows/build-steps.yml
We recreated the SonarCloud project to clear the 404s. This commit fixes the workflow condition by comparing to the string '1', so the Sonar scan step runs and uploads results.
Updates the GHA workflow guard so the Sonar scan actually executes:
- Change `if: inputs.sonar == 1` → `if: inputs.sonar == '1'` because `inputs.sonar` is a string (from `workflow_call` inputs).
No unit tests added (CI-only change). Validation: run the “Analysis” workflow and confirm SonarCloud receives results.
> fix: sonar scan guard

- .github/workflows/docs.yml
These additional things need not trigger a CI test build of the online documentation:
* Build scripts
* Markdown docs that aren't part of the documentation we're generating (like the main README.md, INSTALL.md, etc.)
Doing so just makes CI take longer and wastes resources.
> ci: Add more exceptions to when we test docs building

- .github/workflows/build-steps.yml
- .github/workflows/ci.yml
- src/build-scripts/gh-installdeps.bash
- src/cmake/cuda_macros.cmake
- src/cmake/dependency_utils.cmake
We recently had a problem where our use of a dependency was broken, and it had gone unnoticed because none of our CI jobs actually had the dependency present and tested it. This can easily happen because so many of our dependencies are "optional" -- our build will just give a warning and silently disable the functionality that would have been supported by the missing dependency.
We have long had build-time options `OpenImageIO_REQUIRED_DEPS`, to consider specific dependencies (or "all") required even if they would ordinarily be optional, and `OpenImageIO_OPTIONAL_DEPS`, to make exceptions. But we didn't use these in CI.
So this PR makes sets `OpenImageIO_REQUIRED_DEPS=all` to make all dependencies ostensibly required, and then list all exceptions explicitly. This should make it much more …
> ci: require all dependencies, with explicit exceptions

- src/doc/pythonbindings.rst
- testsuite/docs-examples-python/src/docs-examples-imagebuf.py
- testsuite/docs-examples-python/src/docs-examples-imagebufalgo.py
- testsuite/docs-examples-python/src/docs-examples-imagecache.py
- testsuite/docs-examples-python/src/docs-examples-imageinput.py
- testsuite/docs-examples-python/src/docs-examples-imageioapi.py
- testsuite/docs-examples-python/src/docs-examples-imageoutput.py
- testsuite/docs-examples-python/src/docs-examples-texturesys.py
- testsuite/docs-examples-python/src/docs-examples-writingplugins.py
- testsuite/runtest.py
Closes #4752
Add Python type hints into documentation, in places where example code defines a function. That ended up being just `src/doc/pythonbindings.rst`. I also updated `testsuite/runtest.py` and the functions in `testsuite/docs-examples-python/src/docs-examples-*.py`.
While I was in `pythonbindings.rst`, I noticed a couple places with `py::method` (note the double colon). These lines didn't render in the docs, so I removed the extra colon to match other usage.
I locally built the docs to make sure html looks good. I ran the tests with `ctest` and the tests ran, so I'm taking that as a sign that `runtest.py` still works.
corresponding Python bindings …
> Add type hints to Python docs

- .github/workflows/ci.yml
- INSTALL.md
- pyproject.toml
- src/build-scripts/build_OpenJPEG.bash
- src/build-scripts/build_libjpeg-turbo.bash
- src/build-scripts/build_libraw.bash
- src/build-scripts/build_libtiff.bash
- src/build-scripts/build_pugixml.bash
- src/build-scripts/build_pybind11.bash
- src/build-scripts/build_webp.bash
- src/build-scripts/ci-test.bash
- src/cmake/build_TIFF.cmake
- src/cmake/build_WebP.cmake
- src/cmake/build_libjpeg-turbo.cmake
- src/cmake/build_pybind11.cmake
- src/cmake/dependency_utils.cmake
Raise the version we "autobuild" for some packages:
* OpenJPEG 2.5.2 -> 2.5.4
* pybind11 3.0.0 -> 3.0.1
* libtiff 4.6.0 -> 4.7.1
* webp 1.4.0 -> 1.6.0
* libjpeg-turbo 3.0.4 -> 3.1.2
And some minor debugging and other aids along the way:
* After a build, on linux, do a `ldd` to verify what libraries are linked dynamically for the logs.
* Enhance build_dependency_with_cmake macro to allow optional commands: GIT_COMMIT, GIT_SHALLOW, QUIET
> build: Update autobuild defaults for some dependencies

- .github/workflows/ci.yml
- INSTALL.md
- testsuite/python-colorconfig/ref/out-ocio25.txt
A test needed updating because the set of color spaces in the built-in config are different than for 2.4.
Fixes #4915
> deps: Support for OpenColorIO 2.5

- .github/workflows/ci.yml
- CHANGES.md
- CMakeLists.txt
- CONTRIBUTING.md
- SECURITY.md
- docs/dev/RELEASING.md
Odds and ends of administrative and minor docs changes to stage for a final/first 3.1 release.
> Stage for 3.1.6.1 -- full release

- src/cmake/build_GIF.cmake
- src/cmake/build_GIF_CMakeLists.txt
- src/cmake/dependency_utils.cmake
Fixes #4387 
Added build_GIF.cmake module for GIF library dependency management. Since GIFLIB does not provide a CMakeLists.txt, I created a custom one that gets added to the cloned repository.
The flow is similar to other libraries with cmake support, so I added a conditional statement in the build_dependency_with_cmake macro that, if a cmakelists.txt path is provided, will add/replace existing CMakeLists.txt files on the cloned repository.
I checked that all jobs were successful on the CI. Small side note that some jobs, like `VFX2024 clang/C++17 py3.11 exr3.2 ocio2.3 / clang++ c++17 py3.11`, already have GIFlib with the correct minimum version installed so the jobs pass without build_GIF being run. 
doesn't change …
> build(gif): Add GIF library auto-build
